### ISSUE TITLE
openssl verify returns "unable to get local issuer certificate"

### ISSUE THREAD

**Issue by user371** [openssl/openssl#3225] opened 2017-04-14 09:16 UTC
Hey everyone, 

I am trying to write a code which receives a bunch of certificate chains and returns the invalid chains from it.
I am having troubles verifying certificate chains in windows (in linux, running exactly the same commands returns the expected output and copying the certificates folder from /etc/ssl/certs to the windows machine and specify it as CApath doesn't change the output).
Because I get the certificates chains as an input, the chain lengths are not constant (sometimes they includes only 1 certificate that is selfsigned (and valid)). 
Let cert0.pem be the servers certificate and certk.pem the root CAs certificate. 
According to my research online I'm trying to verify the certificate as follows: 
1. Create a file certs.pem which contains the certificate chain in the order: 
   certk.pem, certk-1.pem,... cert0.pem 
2. Use the command (ca.pem is a file containing root certificates): 
openssl verify -CAfile ca.pem certs.pem

But sometimes the verification goes wrong even for valid chains, as in the following output:

C = US, O = GeoTrust Inc., CN = GeoTrust Global CA 
error 20 at 0 depth lookup: unable to get local issuer certificate 
error certs.pem: verification failed

(The CA file is imported from the os directory, and I can't solve the problem by adding the problemtaic certificates to it (the input is enormose and I can't allow errors in real runtime)).

When I try to verify each certificate with the one signing it, the verification works well, but the verification of the whole chain - including the root (against my local store), returns the attached output.
I am attaching 3 examples of chains which I had trouble verifing (the certificates are pretty old, so I'm verifing them using the command "openssl verify -attime 1433116800-CAfile ca.pem certs.pem")
https://pastebin.com/c2T89t6D
https://pastebin.com/YRUrNG8z
https://pastebin.com/uYdd4PHf

Where did I go wrong ? How can I verify those chains ?
Please advise

**Comment by noloader** [comment] 2017-06-05 12:47
> Where did I go wrong ? How can I verify those chains ?
> Please advise

You should probably ask questions on the [OpenSSL Users mailing list](https://www.openssl.org/community/mailinglists.html)

**Comment by mattcaswell** [comment] 2018-01-22 13:55
Not a bug report. Closing.

**Closed by mattcaswell** 2018-01-22 13:55 UTC
