### ISSUE TITLE
EVP_PKEY_CTX_set_ec_paramgen_curve_nid() doesn't reject NID_sm2  when compiled with 'no-sm2'

### ISSUE THREAD

**Issue by sahanaprasad07** [openssl/openssl#15597] opened 2021-06-02 17:31 UTC
when compiled with no-sm2, we see that the following program does not fail in the way it did in 1.1.1.k
with the error
"elliptic curve routines:EC_GROUP_new_by_curve_name:unknown group:crypto/ec/ec_curve.c:418
elliptic curve routines:pkey_ec_ctrl:invalid curve:crypto/ec/ec_pmeth.c:231"
The expectation is that as in 1.1.1k, 3.0 also rejects NID_sm2 in EVP_PKEY_CTX_set_ec_paramgen_curve_nid().
Currently it accepts NID_sm2 in 3.0.

I understand that the program is not fully complete, and probably EVP_PKEY_paramgen() or EVP_PKEY_keygen() should be used after EVP_PKEY_CTX_set_ec_paramgen_curve_nid(). But since 1.1.1k already failed at this point, I'd like to know if any behaviour around sm2 has changed in 3.0. At the first look, pkey_ec_ctrl() doesn't seem to have modified a lot.

```
#include <stdio.h>
#include <openssl/ec.h>
#include <openssl/evp.h>
#include <openssl/err.h>

int main(int argc, char *argv[])
{
    EVP_PKEY_CTX *pctx = NULL;
    int ret = 1;

    if ((pctx = EVP_PKEY_CTX_new_id(EVP_PKEY_EC, NULL)) == NULL) {
        ERR_print_errors_fp (stderr);
        goto done;
    }

    if (EVP_PKEY_paramgen_init(pctx) != 1) {
        ERR_print_errors_fp (stderr);
        goto done;
    }

    if (!EVP_PKEY_CTX_set_ec_paramgen_curve_nid(pctx, NID_sm2)) {
        ERR_print_errors_fp (stderr);
        goto done;
    }

    ret = 0;
 done:
    EVP_PKEY_CTX_free(pctx);

    return ret;
}
```

Thanks in advance.

**Comment by slontis** [comment] 2021-06-02 23:48
Underneath everything is using providers now,  so it is completely different.
EVP_PKEY_CTX_set_ec_paramgen_curve_nid() internally just copies the params that will be used by the generation function. So there is no 'fetch' during this set phase - and it does not yet have a partial EC_KEY built.

**Comment by slontis** [comment] 2021-06-02 23:49
You could also do a fetch yourself to see if the algorithm exists.

**Comment by slontis** [comment] 2021-06-02 23:52
See the migration_guide.doc for changes related to SM2.
You should be doing this.

````
if ((pctx = EVP_PKEY_CTX_new_id(EVP_PKEY_SM2, NULL)) == NULL) {
````

**Comment by slontis** [comment] 2021-06-02 23:54
or even better
````
pctx = EVP_PKEY_CTX_new_from_name(NULL, "SM2", NULL);
````

**Comment by slontis** [comment] 2021-06-02 23:55
i.e SM2 is a separate algorithm from EC.

**Comment by t8m** [comment] 2021-06-03 12:20
I agree with slontis that this is not a bug. Such kind of behavioral difference between 1.1.1 and 3.0 is to be expected. If this test is checking for presence of SM2 implementation then the suggestions from @slontis above are better for 3.0 as those will fail immediately in no-sm2 build.

**Comment by tomato42** [comment] 2021-07-09 17:16
@sahanaprasad07 I think you can close this issue now

**Comment by t8m** [comment] 2021-07-13 07:12
Closing

**Closed by t8m** 2021-07-13 07:12 UTC
Labels: resolved: answered, triaged: question
