### ISSUE TITLE
TLSv1.3: openssl s_client shows "OCSP response: no response sent" even if server sends it

### ISSUE THREAD

**Issue by tatsuhiro-t** [openssl/openssl#3150] opened 2017-04-08 10:32 UTC
My server uses `SSL_CTX_set_tlsext_status_cb` to setup OCSP callback, and  `SSL_set_tlsext_status_ocsp_resp` is used to pass OCSP data to openssl library.
I dissected the communication between openssl s_client and my server, and it shows that server sent OCSP response as an extension status_request in Certificate message.
But openssl s_client showed "OCSP response: no response sent".

If I try TLSv1.2, it shows OCSP response correctly.

I use openssl master branch.

**Comment by mattcaswell** [comment] 2017-04-10 12:15
I can't reproduce this. I used s_server using the "-status_file" option to send a response (I used ocsp-response.der from test/recipes) and s_client successfully received and displayed the OCSP response. Are you able to create a minimal reproducer that demonstrates the issue?

**Comment by tatsuhiro-t** [comment] 2017-04-10 13:31
My server endpoint is located at https://nghttp2.org:13443/
It looks like s_client does not show ocsp response if server sends multiple certificates (leaf and intermediate).  My server uses the certificate issued by Let's Encrypt, and it sends its own leaf certificate as well as intermediate certificate.  Wireshark shows that status_request extension after leaf certificate.

You can reproduce this locally with s_server using -cert_chain with -cert file.
I might misunderstand how -cert_chain works, but from s_client output, it can specify intermediate certificate.

**Comment by tatsuhiro-t** [comment] 2017-04-10 13:45
It looks like `init_status_request` is called twice, and in the second call, probably for the intermediate one, it deletes ocsp body from first one.

**Comment by tatsuhiro-t** [comment] 2017-04-10 13:53
If OpenSSL only uses the ocsp response data encountered in the first status_request extension, then this could be fixed by discarding ocsp response other than 1st one.
If OpenSSL is extended to handle ocsp response per certificate, then current structure has no room for them.

**Comment by mattcaswell** [comment] 2017-04-26 16:03
Should be fixed by 735d5b59

**Closed by mattcaswell** 2017-04-26 16:03 UTC
