### ISSUE TITLE
X509_verify_cert returns different result with OpenSSL 3.0

### ISSUE THREAD

**Issue by metsma** [openssl/openssl#18691] opened 2022-06-30 11:44 UTC
X509_verify_cert returns different result with OpenSSL 3.0 than 1.1 and
changing chain certificate order changes OpenSSL 3.0 result outcome.

Test Certificate: [test.txt](https://github.com/openssl/openssl/files/9019195/test.txt)
Issuer: C=LT, O=VI Registru Centras - I.k. 124110246, OU=Registru Centro Sertifikavimo Centras, CN=VI Registru Centras RCSC (IssuingCA-A)
Subject: C=LT, O=VI Registru Centras - I.k. 124110246, OU=Registru Centro Sertifikavimo Centras, CN=VI Registru Centras OCSP (IssuingCA-A)
X509v3 Subject Key Identifier: C7:D1:A1:7B:74:F8:1E:9D:DD:AF:10:08:9A:C6:AE:5C:10:FC:D9:63
X509v3 Authority Key Identifier: keyid:4A:4A:CE:E8:D2:C1:D7:88:7C:26:FB:A8:7E:9C:BB:08:40:62:CD:3E

There are three potential issuer CA certs with a matching subject DN in
the CAfile, none have an issuer in the CAfile, so verification will fail
to find the trust anchor regardless of which is chosen:

[chain.txt](https://github.com/openssl/openssl/files/9019419/chain.txt)
[chain_reverse.txt](https://github.com/openssl/openssl/files/9019423/chain_reverse.txt)
Certificate:
Issuer: C=LT, O=VI Registru Centras - I.k. 124110246, OU=Registru Centro Sertifikavimo Centras, CN=VI Registru Centras RCSC (PolicyCA)
Subject: C=LT, O=VI Registru Centras - I.k. 124110246, OU=Registru Centro Sertifikavimo Centras, CN=VI Registru Centras RCSC (IssuingCA-A)
X509v3 Subject Key Identifier: 4A:4A:CE:E8:D2:C1:D7:88:7C:26:FB:A8:7E:9C:BB:08:40:62:CD:3E
X509v3 Authority Key Identifier: keyid:C3:71:C6:BC:03:A7:97:FF:1D:9B:D4:5D:7F:E3:20:3F:49:42:2C:71

Certificate:
Issuer: C=LT, O=VI Registru Centras - I.k. 124110246, OU=Registru Centro Sertifikavimo Centras, CN=VI Registru Centras RCSC (PolicyCA)
Subject: C=LT, O=VI Registru Centras - I.k. 124110246, OU=Registru Centro Sertifikavimo Centras, CN=VI Registru Centras RCSC (IssuingCA-A)
X509v3 Subject Key Identifier: 7E:46:D5:F1:38:4E:AE:0D:86:A8:49:49:C1:5C:DF:06:8F:EA:BF:93
X509v3 Authority Key Identifier: keyid:C3:71:C6:BC:03:A7:97:FF:1D:9B:D4:5D:7F:E3:20:3F:49:42:2C:71

Certificate:
Issuer: C=LT, O=VI Registru Centras - I.k. 124110246, OU=Registru Centro Sertifikavimo Centras, CN=VI Registru Centras RCSC (PolicyCA)
Subject: C=LT, O=VI Registru Centras - I.k. 124110246, OU=Registru Centro Sertifikavimo Centras, CN=VI Registru Centras RCSC (IssuingCA-A)
X509v3 Subject Key Identifier: 02:17:EB:FE:C0:A7:41:79:97:50:68:3E:5E:18:48:66:42:0D:F8:FA
X509v3 Authority Key Identifier: keyid:78:CA:E3:3E:8F:16:B6:D6:9C:B3:06:6A:41:82:19:EE:C8:9F:2F:BB

The first one has matching subject key id, while the last does not.
It appears that OpenSSL 1.1.1 is able to find the matching issuer
regardlss of of the CAfile order, while OpenSSL 3.0 seems to stop
at the first matching subject DN.
openssl 1.1 with default chain
```
openssl verify -CAfile chain.txt -attime 1498620657 test.txt
test.pem: C = LT, O = VI Registru Centras - I.k. 124110246, OU = Registru Centro Sertifikavimo Centras, CN = VI Registru Centras RCSC (IssuingCA-A)
error 2 at 1 depth lookup:unable to get issuer certificate
```
openssl 1.1 with reverse chain
```
openssl verify -CAfile chain_reverse.txt -attime 1498620657 test.txt
test.pem: C = LT, O = VI Registru Centras - I.k. 124110246, OU = Registru Centro Sertifikavimo Centras, CN = VI Registru Centras RCSC (IssuingCA-A)
error 2 at 1 depth lookup:unable to get issuer certificate
```
openssl 3.0 with default chain
```
openssl verify -CAfile chain.txt -attime 1498620657 test.txt
C = LT, O = VI Registru Centras - I.k. 124110246, OU = Registru Centro Sertifikavimo Centras, CN = VI Registru Centras RCSC (IssuingCA-A)
error 30 at 1 depth lookup: authority and subject key identifier mismatch
error test.pem: verification failed
```
openssl 3.0 with reverse chain
```
openssl verify -CAfile chain_reverse.txt -attime 1498620657 test.txt
C = LT, O = VI Registru Centras - I.k. 124110246, OU = Registru Centro Sertifikavimo Centras, CN = VI Registru Centras RCSC (IssuingCA-A)
error 2 at 1 depth lookup: unable to get issuer certificate
error test.pem: verification failed
```
I think expected result should be same whatever order of chain.

**Comment by vdukhovni** [comment] 2022-07-01 04:10
You really should include some of the details from my reply to your question to openssl-security.  Where I explain the role of the multiple potential issuers differing only in the issuer's SKID.

**Comment by vdukhovni** [comment] 2022-07-01 04:11
@DDvO You may want take the lead on this one.

**Comment by DDvO** [comment] 2022-07-02 04:09
I did not see this different error outcome per se as a bug.
I cannot imagine that there is a requirement in any official specification like RFC 5280 saying that,  e.g., 
"unable to get issuer certificate" should be preferred to "authority and subject key identifier mismatch",
such that it should be considered freedom of the implementer which error to present.
One could even argue that the latter error diagnostics is more interesting to obtain.
Could well be that by backtracking all error codes are produced, just in different order.

**Comment by DDvO** [comment] 2022-07-02 04:10
I can of course accept this as a bug if you provide an extension of your scenario 
where you add a suitable trust anchor such that verification succeeds with OpenSSL 1.1 but fails with 3.0.
If so, please provide the full contents of all certs involved (as attachments or PEM-encoded texts) 
such that the problem can be reproduced for debugging.

**Comment by vdukhovni** [comment] 2022-07-02 04:21
@DDvO I don't know whether you saw the thread on openssl-security, but the issue here is not really the error code, but the fact that the behaviour in 3.0 is cert-order-dependent.  And the reason for that is that with 3.0 the certificate with the matching SKID is not found when earlier cert with the same CA subject DN appears first in CAfile.

The OP has three potential issuer certs for the EE cert in the CAfile, cer1 has a matching SKID, while cert2 and cert3 do not.  When the CAfile is reversed, cert3 is read first and its mismatching SKID causes the error to be a SKID mismatch, rather than a failure to find a parent issuer for cert1.

**Comment by DDvO** [comment] 2022-07-02 22:48
@metsma, I just noticed that your above post does include the certs you mention,
so I've been able to reproduce the situation, but with the difference that for OpenSSL 3.0 the result I got is the opposite of yours:
```
openssl verify -CAfile chain.txt -attime 1498620657 test.txt
C=LT, O=VI Registru Centras - I.k. 124110246, OU=Registru Centro Sertifikavimo Centras, CN=VI Registru Centras RCSC (IssuingCA-A)
error 2 at 1 depth lookup: unable to get issuer certificate
error test.txt: verification failed
```
```
openssl verify -CAfile chain_reverse.txt -attime 1498620657 test.txt
C=LT, O=VI Registru Centras - I.k. 124110246, OU=Registru Centro Sertifikavimo Centras, CN=VI Registru Centras RCSC (IssuingCA-A)
error 30 at 1 depth lookup: authority and subject key identifier mismatch
error test.txt: verification failed
```
but this should not really make a difference on the matter.

I traced through the chain building in 1.1.1 and in 3.0 and found that in **both** versions
`X509_STORE_CTX_get1_issuer()` stops at the first cert with matching subject DN:
```
subjectKID: 4A:4A:CE:E8:D2:C1:D7:88:7C:26:FB:A8:7E:9C:BB:08:40:62:CD:3E
authorityKID: C3:71:C6:BC:03:A7:97:FF:1D:9B:D4:5D:7F:E3:20:3F:49:42:2C:71
```
So with the default chain the other two matches are no more considered.
Consequently, with the reverse chain all three such certs are considered:
```
subjectKID: 02:17:EB:FE:C0:A7:41:79:97:50:68:3E:5E:18:48:66:42:0D:F8:FA
authorityKID: 78:CA:E3:3E:8F:16:B6:D6:9C:B3:06:6A:41:82:19:EE:C8:9F:2F:BB
subjectKID: 7E:46:D5:F1:38:4E:AE:0D:86:A8:49:49:C1:5C:DF:06:8F:EA:BF:93
authorityKID: C3:71:C6:BC:03:A7:97:FF:1D:9B:D4:5D:7F:E3:20:3F:49:42:2C:71
subjectKID: 4A:4A:CE:E8:D2:C1:D7:88:7C:26:FB:A8:7E:9C:BB:08:40:62:CD:3E
authorityKID: C3:71:C6:BC:03:A7:97:FF:1D:9B:D4:5D:7F:E3:20:3F:49:42:2C:71
```

of the three certs with matching subject DN in case

So it turns out that your conjecture

> It appears that OpenSSL 1.1.1 is able to find the matching issuer
> regardlss of of the CAfile order, while OpenSSL 3.0 seems to stop
> at the first matching subject DN.

does not really hold.

The explanation for the changed error code is actually different:
When no fully suitable cert (including matching SKID) can be found,
* before version 3.0, chain building always returned "unable to get issuer certificate" or "unable to get local issuer certificate".
* since version 3.0, or to be more precise, after PR #14094 got merged, chain build aims to be more precise on why no such issuer cert was found.

With the default chain in your example, the first cert with matching subject DN also has a matching SKID and chain building stops at this point. Consequently the error to be reported is (both in 1.1.1 and 3.0): "unable to get issuer certificate"

With the reversed chain in your example, the last cert with matching subject DN is
```
Certificate:
Issuer: C=LT, O=VI Registru Centras - I.k. 124110246, OU=Registru Centro Sertifikavimo Centras, CN=VI Registru Centras RCSC (PolicyCA)
Subject: C=LT, O=VI Registru Centras - I.k. 124110246, OU=Registru Centro Sertifikavimo Centras, CN=VI Registru Centras RCSC (IssuingCA-A)
X509v3 Subject Key Identifier: 02:17:EB:FE:C0:A7:41:79:97:50:68:3E:5E:18:48:66:42:0D:F8:FA
X509v3 Authority Key Identifier: keyid:78:CA:E3:3E:8F:16:B6:D6:9C:B3:06:6A:41:82:19:EE:C8:9F:2F:BB
```
This cert is found to be not suitable because its SKID does not match, and this is what OpenSSL 3.0 actually reports: "authority and subject key identifier mismatch".
This fact is a more precise explanation why the chain building fails, while OpenSSL 1.1.1 just reports "unable to get issuer certificate".

**Comment by DDvO** [comment] 2022-07-02 22:48
> @DDvO I don't know whether you saw the thread on openssl-security

So far, I'm not on the openssl-security mailing list, but I've just applied for getting access to it.

> but the issue here is not really the error code, but the fact that the behaviour in 3.0 is cert-order-dependent. And the reason for that is that with 3.0 the certificate with the matching SKID is not found when earlier cert with the same CA subject DN appears first in CAfile.

As I just explained above, this is not the actual reason.

> The OP has three potential issuer certs for the EE cert in the CAfile, cer1 has a matching SKID, while cert2 and cert3 do not. When the CAfile is reversed, cert3 is read first and its mismatching SKID causes the error to be a SKID mismatch, rather than a failure to find a parent issuer for cert1.

Yes, an the reason is the improvement done in #14094.

> This is at least a behaviour change from 1.1, and could actually be a problem if cert1 were a valid trust-anchor, or had a parent TA in the CAfile. As it is, all three ultimately fail.

No worries, the success or failure of chain building is not affected.

**Comment by DDvO** [comment] 2022-07-02 22:53
@vdukhovni, is the behavior of OpenSSL chain building (both in 1.1.1 and 3.0) correct to stop looking for matching issuer certs (i.e.g, certs that have a suitable subject DN etc.) as soon as a cert with matching SKID is found in the list?
Or would it be better for completeness to continue searching the list?

**Comment by vdukhovni** [comment] 2022-07-03 00:54
I had assumed that 1.1.x kept looking for match until it found the right SKID. But I could be wrong about that.  If such behaviour is possible on an AKID/SKID mismatch that would I think be a useful behaviour.

**Comment by DDvO** [comment] 2022-07-03 05:23
> I had assumed that 1.1.x kept looking for a match until it found the right SKID. 

Argh, in my large response above an important condition was missing, which I just added:
> **[update:]** and matching SKID, so in this case **[/update]**

so please re-read.
Indeed also 1.1.1 kept looking for a match until it found the right SKID.

Yet the point is that both 1.1.1 and 3.0 stop looking when finding the right SKID, which makes the overall search order-dependent.
My suspicion is that for completeness it would be better to consider also further certs in the list (as long as no full chain can be built).

**Comment by vdukhovni** [comment] 2022-07-03 05:27
Are you sure that 3.0 also keeps looking for the right SKID?  The OP's report seems to suggest that 3.0 stops as soon the subject DN of the potential issuer CA matches the issuer DN of the issued cert.  I did not run a detailed test with 3.0 to confirm, so this could be a misinterpretation of the observations.

Note that if the OP's CAfile also contained a trust anchor for the intermediate CA cert, 1.1 would would have succeed the cert verification, but 3.0 might have failed if it stopped looking for a matching SKID too early (in the CAfile in which the wrong SKID was listed first).

**Comment by DDvO** [comment] 2022-07-03 05:59
> Are you sure that 3.0 also keeps looking for the right SKID? The OP's report seems to suggest that 3.0 stops as soon the subject DN of the potential issuer CA matches the issuer DN of the issued cert. I did not run a detailed test with 3.0 to confirm, so this could be a misinterpretation of the observations.

As I wrote, **both** versions, also 3.0, has this behavior to stop at the first matching SKID.
So, as I explained, the different error code has a different explanation: the changes in #14094, which do not introduce a bug but a feature.

> Note that if the OP's CAfile also contained a trust anchor for the intermediate CA cert, 1.1 would would have succeed the cert verification, but 3.0 might have failed if it stopped looking for a matching SKID too early (in the CAfile in which the wrong SKID was listed first).

No, because then still for all other candidate certs the SKID does not match for both the default and reverse example chains.
And as I tried to explain, the search behavior is identical for both 1.1.1 and 3.0

I meanwhile have the strong suspicion that if there was **a second (different) intermediate cert with a matching SKID** (4A:4A:CE:E8:D2:C1:D7:88:7C:26:FB:A8:7E:9C:BB:08:40:62:CD:3E) for which a trust anchor is present, this intermediate cert is not considered with the order given in the default chain.
So I suspect that there is an incompleteness of the chain building in both 1.1.1 and 3.0.

@metsma, can you provide for testing such a new intermediate cert and a trust anchor for it?

**Comment by DDvO** [comment] 2022-07-03 19:57
I meanwhile found that the scenario I mentioned earlier today can readily be modeled with the standard OpenSSL test certs, 
and my suspicion of incompleteness of the chain building proves right (for both 1.1.1 and 3.0 ) - see #18708.

**Comment by DDvO** [comment] 2022-07-03 20:01
@metsma, thanks for reporting this issue.
In my view the scenario you gave does not directly point to a bug, but to a feature, so I suggest closing it.
OTOH, its analysis gave rise to detecting an actual bug that already exists before OpenSSL 3.0: #18708.

**Comment by vdukhovni** [comment] 2022-07-03 21:48
I've verified that both 1.1.1 and 3.0 manage to find the issuer with the right DN and SKID regardless of certificate order.

The only thing that seems to be odd, is that with 3.0 the error returned when the root CA is missing from the trust store and the "wrong" issuer is listed first, then the error reported is a SKID mismatch, rather than inability to find an issuer for the "right" issuer.  The error is surprising, since the real problem is lack of a root issuer not a SKID mismatch.

Below "vca-cert.pem" (the "right" issuer) and "vca-cert2.pem" (the "wrong" issuer) have the same subject (and issuer) DNs but different keys and SKIDs:

```
$ OpenSSL_3.0/bin/openssl verify -show_chain -CAfile <(cat vroot-cert.pem vca-cert2.pem vca-cert.pem) vee-cert.pem 
vee-cert.pem: OK
Chain:
depth=0: CN = server.example (untrusted)
depth=1: CN = CA
depth=2: CN = Root CA

$ OpenSSL_3.0/bin/openssl verify -show_chain -CAfile <(cat vca-cert2.pem vca-cert.pem) vee-cert.pem 
CN = CA
error 30 at 1 depth lookup: authority and subject key identifier mismatch
error vee-cert.pem: verification failed
0006931101000000:error:16000069:STORE routines:ossl_store_get0_loader_int:unregistered scheme:../openssl/crypto/store/store_register.c:237:scheme=file
0006931101000000:error:80000002:system library:file_open:No such file or directory:../openssl/providers/implementations/storemgmt/file_store.c:269:calling stat(/Volumes/gitvol/viktor/ssl/OpenSSL_3.0/ssl/certs)

$ OpenSSL_3.0/bin/openssl verify -show_chain -CAfile <(cat vca-cert.pem vca-cert2.pem) vee-cert.pem 
CN = CA
error 2 at 1 depth lookup: unable to get issuer certificate
error vee-cert.pem: verification failed
0096711201000000:error:16000069:STORE routines:ossl_store_get0_loader_int:unregistered scheme:../openssl/crypto/store/store_register.c:237:scheme=file
0096711201000000:error:80000002:system library:file_open:No such file or directory:../openssl/providers/implementations/storemgmt/file_store.c:269:calling stat(/Volumes/gitvol/viktor/ssl/OpenSSL_3.0/ssl/certs)
```

On the other hand with 1.1.1, when the root is missing, the error is the same regardless of intermediate issuer certificate order
```
$ OpenSSL_1_1_1/bin/openssl verify -show_chain -CAfile <(cat vroot-cert.pem vca-cert2.pem vca-cert.pem) vee-cert.pem
vee-cert.pem: OK
Chain:
depth=0: CN = server.example (untrusted)
depth=1: CN = CA
depth=2: CN = Root CA

$ OpenSSL_1_1_1/bin/openssl verify -show_chain -CAfile <(cat vca-cert2.pem vca-cert.pem) vee-cert.pem
CN = CA
error 2 at 1 depth lookup: unable to get issuer certificate
error vee-cert.pem: verification failed

$ OpenSSL_1_1_1/bin/openssl verify -show_chain -CAfile <(cat vca-cert.pem vca-cert2.pem) vee-cert.pem
CN = CA
error 2 at 1 depth lookup: unable to get issuer certificate
error vee-cert.pem: verification failed
```

To create the certs I ran in `test/certs`:
```
./mkcert.sh genroot "Root CA" vroot-key vroot-cert
./mkcert.sh genca "CA" vca-key vca-cert vroot-key vroot-cert
./mkcert.sh genca "CA" vca-key2 vca-cert2 vroot-key vroot-cert
./mkcert.sh genee server.example vee-key vee-cert vca-key vca-cert
```

**Comment by vdukhovni** [comment] 2022-07-03 21:49
Bottom line, 3.0 emits an unexpected error when failing to find the parent issuer.

**Comment by DDvO** [comment] 2022-07-04 04:55
As I wrote, In my view it's more interesting/helpful to get a more specific error, such as key ID mismatch or cert expired.
Yet others may prefer to get the original, more general but also less informative error, namely cannot get issuer cert.

In fact, the latter error code may have more than one root cause, due to one candidate cert having more than one problem or multiple candidate certs having their issues. And with the current error reporting this causes one of them to be given, which is necessarily order dependent and thus agreeably suboptimal.

IMO the ideal solution would be to give both the most general error (cannot get issuer cert) and a list/trace of reasons for that.
This could be implemented pretty straightforwardly using the Trace API.

**Comment by vdukhovni** [comment] 2022-07-04 13:56
Well, as "interesting" as it might be, SKID mismatch is the *wrong* error.  There is a matching issuer in the trust store, as evidenced by the "OK" result when the root CA is prepended to the store.

The correct error report is generated by OpenSSL 1.1.1.  There is no SKID mismatch, the matching intermediate CA is present in the cert store.  The SKID mismatch on the skipped first CA is irrelevant when a SKID match is found for the second.

**Comment by DDvO** [comment] 2022-07-04 19:00
All right, I'll make sure that the most general error code is provided again as the primary outcome.
And will add a trace option that will provide for all candidate certs (with matching subject DN) that are not accepted the exact reason why.

**Comment by vdukhovni** [comment] 2022-07-04 19:11
> All right, I'll make sure that the most general error code is provided again as the primary outcome. And will add a trace option that will provide for all candidate certs (with matching subject DN) that are not accepted the exact reason why.

Note, this isn't about more or less "general", but rather *most proximate*, generality has nothing to do with it.  The immediate cause of the problem is failure to find an issuer for the certificate at depth 1, and so that's what needs to be reported.

**Comment by DDvO** [comment] 2022-07-04 21:50
I'm going to provide soon a PR that on
```
OPENSSL_TRACE=X509_VERIFY apps/openssl verify -show_chain -CAfile <(cat vca-cert2.pem vca-cert.pem) vee-cert.pem
```
will produce:
````
TRACE[C0:A7:82:17:41:7F:00:00]:X509_VERIFY: X509 chain building start
TRACE[C0:A7:82:17:41:7F:00:00]:X509_VERIFY:     handling target certificate at depth 0:
TRACE[C0:A7:82:17:41:7F:00:00]:X509_VERIFY:         Subject: CN=server.example
TRACE[C0:A7:82:17:41:7F:00:00]:X509_VERIFY:          Issuer: CN=CA
TRACE[C0:A7:82:17:41:7F:00:00]:X509_VERIFY:         Serial Number: 2 (0x2)
TRACE[C0:A7:82:17:41:7F:00:00]:X509_VERIFY:         Validity
TRACE[C0:A7:82:17:41:7F:00:00]:X509_VERIFY:             Not Before: Jul  4 18:48:10 2022 GMT
TRACE[C0:A7:82:17:41:7F:00:00]:X509_VERIFY:             Not After : Jul  5 18:48:10 2122 GMT
TRACE[C0:A7:82:17:41:7F:00:00]:X509_VERIFY:         X509v3 Subject Key Identifier: 
TRACE[C0:A7:82:17:41:7F:00:00]:X509_VERIFY:             D8:4A:F9:66:E0:A6:5E:4B:3E:4C:9C:C2:3F:D3:8E:69:FD:FB:B0:BC
TRACE[C0:A7:82:17:41:7F:00:00]:X509_VERIFY:         X509v3 Authority Key Identifier: 
TRACE[C0:A7:82:17:41:7F:00:00]:X509_VERIFY:             7D:3F:C6:10:AC:00:4E:DD:3A:05:B6:98:43:82:EF:3B:C8:CF:CF:A3
TRACE[C0:A7:82:17:41:7F:00:00]:X509_VERIFY:       checking candidate issuer certificate:
TRACE[C0:A7:82:17:41:7F:00:00]:X509_VERIFY:         Subject: CN=CA
TRACE[C0:A7:82:17:41:7F:00:00]:X509_VERIFY:          Issuer: CN=Root CA
TRACE[C0:A7:82:17:41:7F:00:00]:X509_VERIFY:         Serial Number: 2 (0x2)
TRACE[C0:A7:82:17:41:7F:00:00]:X509_VERIFY:         Validity
TRACE[C0:A7:82:17:41:7F:00:00]:X509_VERIFY:             Not Before: Jul  4 18:48:10 2022 GMT
TRACE[C0:A7:82:17:41:7F:00:00]:X509_VERIFY:             Not After : Jul  5 18:48:10 2122 GMT
TRACE[C0:A7:82:17:41:7F:00:00]:X509_VERIFY:         X509v3 Subject Key Identifier: 
TRACE[C0:A7:82:17:41:7F:00:00]:X509_VERIFY:             CE:4C:2A:C9:7F:68:18:86:DC:EB:E5:87:79:FE:22:30:47:16:D3:D9
TRACE[C0:A7:82:17:41:7F:00:00]:X509_VERIFY:         X509v3 Authority Key Identifier: 
TRACE[C0:A7:82:17:41:7F:00:00]:X509_VERIFY:             90:26:89:EC:D4:95:36:32:30:D9:16:F1:C8:D1:4A:21:4A:45:40:6D
TRACE[C0:A7:82:17:41:7F:00:00]:X509_VERIFY:       candidate issuer certificate rejected due to error 30: authority and subject key identifier mismatch
TRACE[C0:A7:82:17:41:7F:00:00]:X509_VERIFY:       checking candidate issuer certificate:
TRACE[C0:A7:82:17:41:7F:00:00]:X509_VERIFY:         Subject: CN=CA
TRACE[C0:A7:82:17:41:7F:00:00]:X509_VERIFY:          Issuer: CN=Root CA
TRACE[C0:A7:82:17:41:7F:00:00]:X509_VERIFY:         Serial Number: 2 (0x2)
TRACE[C0:A7:82:17:41:7F:00:00]:X509_VERIFY:         Validity
TRACE[C0:A7:82:17:41:7F:00:00]:X509_VERIFY:             Not Before: Jul  4 18:48:08 2022 GMT
TRACE[C0:A7:82:17:41:7F:00:00]:X509_VERIFY:             Not After : Jul  5 18:48:08 2122 GMT
TRACE[C0:A7:82:17:41:7F:00:00]:X509_VERIFY:         X509v3 Subject Key Identifier: 
TRACE[C0:A7:82:17:41:7F:00:00]:X509_VERIFY:             7D:3F:C6:10:AC:00:4E:DD:3A:05:B6:98:43:82:EF:3B:C8:CF:CF:A3
TRACE[C0:A7:82:17:41:7F:00:00]:X509_VERIFY:         X509v3 Authority Key Identifier: 
TRACE[C0:A7:82:17:41:7F:00:00]:X509_VERIFY:             90:26:89:EC:D4:95:36:32:30:D9:16:F1:C8:D1:4A:21:4A:45:40:6D
TRACE[C0:A7:82:17:41:7F:00:00]:X509_VERIFY:       candidate issuer certificate accepted
TRACE[C0:A7:82:17:41:7F:00:00]:X509_VERIFY:     handling further certificate at depth 1:
TRACE[C0:A7:82:17:41:7F:00:00]:X509_VERIFY:         Subject: CN=CA
TRACE[C0:A7:82:17:41:7F:00:00]:X509_VERIFY:          Issuer: CN=Root CA
TRACE[C0:A7:82:17:41:7F:00:00]:X509_VERIFY:         Serial Number: 2 (0x2)
TRACE[C0:A7:82:17:41:7F:00:00]:X509_VERIFY:         Validity
TRACE[C0:A7:82:17:41:7F:00:00]:X509_VERIFY:             Not Before: Jul  4 18:48:08 2022 GMT
TRACE[C0:A7:82:17:41:7F:00:00]:X509_VERIFY:             Not After : Jul  5 18:48:08 2122 GMT
TRACE[C0:A7:82:17:41:7F:00:00]:X509_VERIFY:         X509v3 Subject Key Identifier: 
TRACE[C0:A7:82:17:41:7F:00:00]:X509_VERIFY:             7D:3F:C6:10:AC:00:4E:DD:3A:05:B6:98:43:82:EF:3B:C8:CF:CF:A3
TRACE[C0:A7:82:17:41:7F:00:00]:X509_VERIFY:         X509v3 Authority Key Identifier: 
TRACE[C0:A7:82:17:41:7F:00:00]:X509_VERIFY:             90:26:89:EC:D4:95:36:32:30:D9:16:F1:C8:D1:4A:21:4A:45:40:6D
TRACE[C0:A7:82:17:41:7F:00:00]:X509_VERIFY: X509 chain building failure
CN=CA
error 2 at 1 depth lookup: unable to get issuer certificate
error vee-cert.pem: verification failed

```

**Comment by vdukhovni** [comment] 2022-07-04 21:54
Looks great!  Many thanks.

**Comment by beldmit** [comment] 2022-07-05 08:02
I strongly like this output.

What I'm not fond of is that this output requires special build of openssl with enabled trace...

**Comment by DDvO** [comment] 2022-07-06 10:24
> I strongly like this output.
> 
> What I'm not fond of is that this output requires special build of openssl with enabled trace...

I fully agree.
I also dislike the fact that the trace API is not available to the majority of OpenSSL users, i.e. those who use a precompiled installation.

Actually this morning I was thinking about how to solve this.
My plan is to provide the output both 
* via the trace API 
* directly to `stdout`, if enabled by a new verification context flag, which will be triggered by the `-verbose` option of the `verify` app.

**Comment by vdukhovni** [comment] 2022-07-06 19:18
More useful and safe than a write to `stdout` (which may break the application, overwriting critical files, inject traces into network sockets, ...) would be a new callback, that can receive and log trace information as it sees fit.  The `app` commands can then use the callback to write to `stdout` or `stderr` as appropriate.  Libraries MUST NOT write diagnostic information directly to `stdout` or `stderr`.

**Comment by vdukhovni** [comment] 2022-07-06 19:21
By way of comparison, MIT kerberos supports the "KRB5_TRACE=filename" environment variable, the library (unless setuid, ..., i.e. `safe_getenv()`) writes diagnostics to the trace file, not to `stdout`.  On platforms with "/dev/fd/" and "/dev/stderr" one can ask for output to file descriptors rather than "disk" files.

**Comment by DDvO** [comment] 2022-07-07 05:18
Thanks for your comments including hints.
I agree a library should not decide to print to `stdout`.

A simpler mechanism than to provide a callback and a more flexible way than to use a file reference is to use an output BIO.
So I'm going to add to the verification context a `BIO *out` and the setter
```
void X509_STORE_CTX_set0_trace_output(X509_STORE_CTX *ctx, BIO *out);
```
(which can be used by `apps/verify.c` to the value of the `bio_out` variable defined for the apps).

**Closed** 2022-07-12 12:01 UTC
Labels: branch: master, triaged: bug, branch: 3.0
