### ISSUE TITLE
OCSP_basic_sign() crashes starting in alpha14 if passed dgst=NULL

### ISSUE THREAD

**Issue by jwalch** [openssl/openssl#14816] opened 2021-04-09 19:01 UTC
Caused by this commit: e6c2f96489fc0c006845c8597f8ceed2f01f76ee

Arguably it would be helpful if EVP_MD_name() simply returned NULL in this situation, but AFAIK the unconditional de-reference is a long-standing behavior going back to previous releases. I'll leave it for others to debate on whether to address that here or just spot-fix this isolated regression.

**Comment by slontis** [comment] 2021-04-12 01:48
This is a duplicate of https://github.com/openssl/openssl/issues/14809..
I will close this one.. Issue is addressed in https://github.com/openssl/openssl/pull/14826

**Closed** 2021-04-12 01:48 UTC
Labels: issue: bug report
