### ISSUE TITLE
ChaCha SVE compiling error when  __AARCH64EB__ enabled

### ISSUE THREAD

**Issue by myesboy** [openssl/openssl#20024] opened 2023-01-11 03:52 UTC
error file: openssl-openssl-3.1.0-beta1_a76_be/crypto/chacha/asm/chacha-armv8-sve.pl

/opt/buildtools/gcc-arm-10.3-2021.07-x86_64-aarch64_be-none-linux-gnu/bin/aarch64_be-none-linux-gnu-gcc  -Icrypto -I. -Iinlude -Iproviders/implementations/include  -DBSAES_ASM -DECP_NISTZ256_ASM -DKECCAK1600_ASM -DMD5_ASM -DOPENSSL_BN_ASM_MONT -DOM3_ASM -DPOLY1305_ASM -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DSM4_ASM -DVPAES_ASM -DVPSM4_ASM -fPIC -pthread -Wa,--noexecstackypto -mtune=cortex-a76 -DOPENSSL_USE_NODELETE -DOPENSSL_PIC -DOPENSSLDIR="\"/usr/local/ssl\"" -DENGINESDIR="\"/usr/local/lib/"/usr/local/lib/ossl-modules\"" -DOPENSSL_BUILDING_OPENSSL -DNDEBUG  -c -o crypto/chacha/libcrypto-lib-chacha-armv8-sve.o cryS
crypto/chacha/chacha-armv8-sve.S: Assembler messages:
crypto/chacha/chacha-armv8-sve.S:612: Error: unexpected comma after the mnemonic name `rev' -- `rev ,'
crypto/chacha/chacha-armv8-sve.S:613: Error: unexpected comma after the mnemonic name `rev' -- `rev ,'
crypto/chacha/chacha-armv8-sve.S:614: Error: unexpected comma after the mnemonic name `rev' -- `rev ,'
crypto/chacha/chacha-armv8-sve.S:615: Error: unexpected comma after the mnemonic name `rev' -- `rev ,'

line:472 - 483
sub SVE_TRANSFORMS() {
$code.=<<___;
#ifdef	__AARCH64EB__
	rev	@x[0],@x[0]
	rev	@x[2],@x[2]
	rev	@x[4],@x[4]
	rev	@x[6],@x[6]
	rev	@x[8],@x[8]
	rev	@x[10],@x[10]
	rev	@x[12],@x[12]
	rev	@x[14],@x[14]
#endif

maybe it should be 
sub SVE_TRANSFORMS() {
$code.=<<___;
#ifdef	__AARCH64EB__
	rev	@sxx[0],@sxx[0]
	rev	@sxx[2],@sxx[2]
	rev	@sxx[4],@sxx[4]
	rev	@sxx[6],@sxx[6]
	rev	@sxx[8],@sxx[8]
	rev	@sxx[10],@sxx[10]
	rev	@sxx[12],@sxx[12]
	rev	@sxx[14],@sxx[14]
#endif

may copy it from chacha-armv8.pl and forget to change it.

**Comment by tom-cosgrove-arm** [comment] 2023-01-11 08:32
This is a duplicate of #19902 which we (Arm) are working on

**Comment by mattcaswell** [comment] 2023-01-11 10:41
Duplicate of #19902

**Comment by mattcaswell** [comment] 2023-01-11 10:41
Closing. To be tracked via #19902

**Closed by mattcaswell** 2023-01-11 10:41 UTC
Labels: issue: bug report
