### ISSUE TITLE
Support for Intel SHA extensions (Goldmont CPUs) possibly broken

### ISSUE THREAD

**Issue by Posolsvetla** [openssl/openssl#3241] opened 2017-04-18 11:00 UTC
Hi, this is a follow up on #2975 
Unfortunately, the test performed by an user of our application has negative result, so it seems that #2992 doesn't fix the issue.
For the general description of the issue, please see #2975.

Additional info:
OpenSSL 1.0.2k with cherry-picked #2992 acting as a client, statically build into a custom application.
The pcapng capture example from the test run: [s_ytimg_com_tcp_stream_11.zip](https://github.com/openssl/openssl/files/928678/s_ytimg_com_tcp_stream_11.zip)
Please note log reports in there in these packet comments:
- frame 8: Alert to be sent to the server (not actually sent)
- frame 9: error:1408D07B:SSL routines:ssl3_get_key_exchange:bad signature

I tested the signature in the Server Key Exchange on non-Goldmont CPU with the code snippet based on the ssl3_get_key_exchange function; the signature is correct.

Please let me know if additional info is needed. I can provide several more pcapng captures if necessary.

**Comment by kroeckx** [comment] 2017-04-22 22:01
@dot-asm: Can you look at this?

**Comment by dot-asm** [comment] 2017-04-24 20:13
I still can't reproduce the problem with `s_client -connect 172.217.16.206:443 -cipher ECDHE-ECDSA-AES128-GCM-SHA256 -servername s.ytimg.com`, not under sde -glm, not on Goldmont hardware on Linux or Windows. The parameters are from provided pcap. Which actually calls for following question. List of ciphersuites offered by client in provided pcap doesn't look like one offered by default 1.0.2 build, and in such case what were config parameters, build- or run-time? Can you yourself reproduce the problem with s_client?

**Comment by Posolsvetla** [comment] 2017-04-25 06:35
Hi,
I haven't reproduced it myself, as I do not have a Goldmont HW yet. I ordered a NB a few days ago, but haven't received it yet. I will perform the tests ASAP.
As for the setup:
`perl Configure VC-WIN64A enable-ssl2 no-rc4 no-comp no-err no-sock -DWINNT -D_NO_CRT_STDIO_INLINE`
`/LTCG` added to the `MKLIB` in `ms/nt.mak`
`/GL /Gw /Zo /guard:cf` added to the `CFLAG` in `ms/nt.mak`
The cipher suites were set via `SSL_CTX_set_cipher_list`, with each cipher suite explicitly named (e.g. `ECDHE-ECDSA-AES128-GCM-SHA256`).
The elliptic curves were set via `SSL_set1_curves`.

**Comment by dot-asm** [comment] 2017-04-25 13:43
> as I do not have a Goldmont HW yet.

You can download Intel SDE (first link if you google for "intel sde") and run the program that you referred to above (as "I tested the signature in the Server Key Exchange on non-Goldmont CPU with the code snippet based on the ssl3_get_key_exchange function; the signature is correct.") and execute it as `\some\where\sde -glm -- yourprog`. Or you can execute openssl as `\some\where\sde -glm -- openssl s_client ...`.

**Comment by Posolsvetla** [comment] 2017-05-03 07:33
Hi, thanks much for the hint, I was able to proceed and reproduce.
I found something, but as I have almost zero knowledge about both asm and perl, I'm not sure.
From this: `pshufd \$0xb1,$ABEF,$ABEF # BAFE`
this was generated during the build process: `pshufd xmm1,xmm1,1h`
which doesn't seem right to me.
Could you please confirm and/or could you please attach both `sha256-x86_64.asm` and `sha512-x86_64.pl` from which it was generated, so I can compare myself?
Thanks much.

**Comment by dot-asm** [comment] 2017-05-03 16:34
Spot on! Good catch! There is kind of a problem. Your report means that you used Microsoft assembler, and we don't support it, nasm is declared as the only supported option. Well, in 1.0.2 context it's a little bit ambiguous, because it's mentioned only in INSTALL.W32, but fact of life is that we abstain from Microsoft assembler as general rule. Now! This doesn't actually mean that problem won't be addressed (it will), but you can as well just put nasm on your %PATH% and rebuild to get working build.

On side note I'd also argue that /GL is not necessarily appropriate choice for code like OpenSSL, because it enables compiler to thwart security countermeasures.  As a rule of thumb I'd recommend default options when building OpenSSL, and which options do you use to compiler your application code is your business.

Another side note about /guard:cf. I didn't succeed to make it work with development branch. Can you confirm that it works with 1.0.2? I.e. do you *link* *your* application with /guard:cf? On the other hand nasm doesn't work with /guard:cf yet (bug report was filed), so you kind of have to use Microsoft assembler, that is still unsupported:-). But as mentioned this doesn't mean that *this* problem won't be fixed. Even though we don't support it now, we don't rule out that it can be in the future...

**Comment by shigeki** [comment] 2017-05-03 23:34
We have the same issue in https://github.com/nodejs/node/issues/12691 and confirmed that the issue is resolved by using nasm. We also found that `OPENSSL_ia32cap="~0x1000000000000000:~0"` can be a workaround.

I'm aware that masm is unsupported and we are planning to switch using nasm in the next upgrade version of Node with OpenSSL-1.1.x because it forces an additional requirement of nasm for building. Is there any chance to fix this in the current openssl-1.0.2?

**Comment by dot-asm** [comment] 2017-05-04 01:51
> Is there any chance to fix this in the current openssl-1.0.2?

As already said, *this* particular problem *will* be addressed. But problem that masm is not really/fully supported won't, at least not at this time.

**Comment by shigeki** [comment] 2017-05-04 11:03
Thanks for your reply. I'm waiting for your address.

**Comment by Posolsvetla** [comment] 2017-05-04 13:00
**masm vs nasm** - TBH I was completely unaware of this stuff, as far as I remember, I followed mostly INSTALL.W64 and our current build script is based on that; thank you for the info
**/GL** - which flags to use is somehow mandated by my colleague, I will pass your concerns to him
**/guard:cf** - I don't have much info about this personally: I know only that my colleagues had to add support for it into the code they maintain in order to work, I just link their resulting static library.
If it _really_ works, I don't know, I just checked with _dumpbin_ if the resulting binary is according to https://msdn.microsoft.com/en-us/library/windows/desktop/mt637065(v=vs.85).aspx

As for the bug:
I found the culprit: `$self->{value} =~ s/0x([0-9a-f]+)/0$1h/ig if ($masm);` inside `x86_64-xlate.pl`, but as I'm new to perl, I couldn't figure out how to make it work properly for the `b1` value inside the `$1`. It works correctly, if there is no `b` at the start of `$1` value.

**Comment by dot-asm** [comment] 2017-05-04 14:17
See #3385.

> I couldn't figure out how to make it work properly for the b1

Neither could I... Workaround was to simply copy `$self->{value}` to a variable. No, it doesn't make sense...

**Comment by dot-asm** [comment] 2017-05-04 14:30
To double-clarify /guard:cf. There is dilemma, we don't support nasm, but /guard:cf is known to not work with nasm-assembled code. Well, /guard:cf is about indirect jumps and calls, so that /guard:cf works with nasm-assembled modules as long as they are not involved in indirect jumps/calls. I can't think of one in 1.0.2 context, so that it might work with 1.0.2. Which is why I asked if you can actually confirm it. I interpret your message as that you can confirm that your application has those additional Guard CF tables (that you can observe with dumpbin) yet your application works without crashing. This effectively confirms that /guard:cf works with 1.0.2 [at least with algorithms used by your application]. Thanks for report!

**Comment by dot-asm** [comment] 2017-05-04 14:37
> OPENSSL_ia32cap="~0x1000000000000000:~0"

Just in case, the fact that it did the trick is kind of circumstantial. The moment you specify first word, second one is automatically zeroed. [It's backward compatibility thing.] The above value masks AVX, but since Goldmont can't AVX, effectively it was equivalent of `:0`.

**Comment by shigeki** [comment] 2017-05-04 15:05
Whoops, it is true for the doc really says that
> For example assigning  ':~0x20' would disable AVX2 code paths, and ':0' - all post-AVX
    extensions.

I misread and was wrong. Thanks for clarification.

**Comment by dot-asm** [comment] 2017-05-05 14:59
Fix is committed. Closing. Thanks again.

**Closed by dot-asm** 2017-05-05 14:59 UTC

**Comment by shigeki** [comment] 2017-05-09 02:52
We've confirmed that the issue was resolved with 4ae5993cab1b1c42cfc99180c00ae0a235ce940c in https://github.com/nodejs/node/issues/12691#issuecomment-299793715. Thanks.

**Comment by richsalz** [comment] 2017-05-09 11:59
Thank you for checking!

**Comment by bubble932** [comment] 2019-03-06 06:53
Would you tell me how to use openssl Intel SHA extension codes to compute the SHA1 or SHA256 in Goldmont CPUs instead of other implementations？

**Comment by bubble932** [comment] 2019-03-06 06:53
> We've confirmed that the issue was resolved with [4ae5993](https://github.com/openssl/openssl/commit/4ae5993cab1b1c42cfc99180c00ae0a235ce940c) in [nodejs/node#12691 (comment)](https://github.com/nodejs/node/issues/12691#issuecomment-299793715). Thanks.

Would you tell me how to use openssl Intel SHA extension codes to compute the SHA1 or SHA256 in Goldmont CPUs instead of other implementations？Thanks！
