### ISSUE TITLE
--debug not work

### ISSUE THREAD

**Issue by little-bird-in-china** [openssl/openssl#5652] opened 2018-03-17 07:34 UTC
When config build with --debug on windows,
the result .lib file size is same with the --release,
so i doubt that --debug option is working.

**Comment by levitte** [comment] 2018-03-17 08:18
I assume we're talking about OpenSSL 1.1.0 or newer...

Did you have any other options apart from the config target, or was `--debug` it?
Thing is that in that case, you're building shared libraries, and libcrypto.lib is only an import library, and you should look at the size of the .dll files instead.

**Comment by little-bird-in-china** [comment] 2018-03-18 07:27
Yes, I use the latest openssl version, my build option is

perl Configure VC-WIN64A --debug --prefix=...
and
perl Configure VC-WIN64A --release --prefix=...

followed by
nmake
nmake test
nmake install

**Comment by dot-asm** [comment] 2018-03-18 15:01
As @levitte said, you are looking at wrong files. In builds without no-shared .lib files will be same size, because these are import libraries. One can view them as just a list of subroutine names in specific dll. And it's those specific dlls that would be different in --debug vs. --releases cases. One can also compare flags in generated makefiles. You will see /Od (disable optimizations) in one generated with --debug. At least I can confirm that it's the case when I try it. Closing this.

**Closed by dot-asm** 2018-03-18 15:01 UTC
