### ISSUE TITLE
Regression caused by the keep_random_devices_open change

### ISSUE THREAD

**Issue by t8m** [openssl/openssl#7136] opened 2018-09-06 11:23 UTC
Application that links to OpenSSL but never initialized the RNG because it does not use it will now try to open all the system random devices at exit.

See:
https://bugzilla.redhat.com/show_bug.cgi?id=1624554

rand_cleanup_int() will try to call RAND_set_rand_method(NULL) which will initialize the RNG if it was not initialized before, which will cause it to try to open all the random devices configured by DEVRANDOM.

First it is debatable whether /dev/random should be present in the list at all on Linux however that is not the main problem.

Also the order of     
rand_pool_cleanup();
RAND_set_rand_method(NULL);
in function rand_cleanup_int() looks problematic to me. But perhaps it would be just sufficient  to add if (meth != NULL) condition for the RAND_set_rand_method(NULL) call.

**Comment by romen** [comment] 2018-09-06 13:32
This seems like a duplicate of #7022, fixed by #7023

**Closed as completed** 2018-09-07 07:22 UTC
