### ISSUE TITLE
version 1.1.1o 80-test_ssl_new Dubious, test returned 1

### ISSUE THREAD

**Issue by Roko131** [openssl/openssl#18482] opened 2022-06-06 09:31 UTC
Hi, I build openssl-1.1.1o on pop-os 22.04, basically Ubuntu 22-04, but make test `test_ssl_new` fails.

perl configdata.pm --dump output:
[config.txt](https://github.com/openssl/openssl/files/8843422/config.txt)

Notice I had already openssl 3 installed:
```
openssl version
OpenSSL 3.0.2 15 Mar 2022 (Library: OpenSSL 3.0.2 15 Mar 2022)
```

To install openssl-1.1.1o I tried:

```
sudo apt install build-essential checkinstall zlib1g-dev
```

```
$ cd ~/Downloads
$ wget https://www.openssl.org/source/openssl-1.1.1o.tar.gz
$ tar xf openssl-1.1.1o.tar.gz
```

```
$ cd ~/Downloads/openssl-1.1.1o
$ ./config --prefix=/opt/openssl-1.1.1o --openssldir=/opt/openssl-1.1.1o shared zlib
$ make
$ make test
```
But make test failed, failed test test_ssl_new,

I'll add as file the ouput of 

```
make TESTS=test_ssl_new V=1 test
```

[test_ssl_new_fails_output.txt](https://github.com/openssl/openssl/files/8843304/test_ssl_new_fails_output.txt)

Any suggestions? Thanks

Still - I added here (what I think) the relevant part:

```
# Subtest: Test configuration 12-ct.conf
    1..3
../../util/shlib_wrap.sh /usr/bin/perl -I ../../util/perl ../generate_ssl_tests.pl ../ssl-tests/12-ct.conf.in > 12-ct.conf.157495.tmp => 0
    ok 1 - Getting output from generate_ssl_tests.pl.
    ok 2 - Comparing generated sources.
        # Subtest: ../ssl_test
        1..1
            # Subtest: test_handshake
            1..6
            ok 1 - iteration 1
            # ERROR: (int) 'result->result == test_ctx->expected_result' failed @ test/ssl_test.c:33
            # [2] compared to [0]
            # INFO:  @ test/ssl_test.c:34
            # ExpectedResult mismatch: expected Success, got ClientFail.
            # 139834698314176:error:14094415:SSL routines:ssl3_read_bytes:sslv3 alert certificate expired:ssl/record/rec_layer_s3.c:1543:SSL alert 
number 45
            not ok 2 - iteration 2
            ok 3 - iteration 3
            # ERROR: (int) 'result->result == test_ctx->expected_result' failed @ test/ssl_test.c:33
            # [2] compared to [0]
            # INFO:  @ test/ssl_test.c:34
            # ExpectedResult mismatch: expected Success, got ClientFail.
            # 139834698314176:error:14094415:SSL routines:ssl3_read_bytes:sslv3 alert certificate expired:ssl/record/rec_layer_s3.c:1543:SSL alert number 45
            not ok 4 - iteration 4
            # ERROR: (int) 'result->result == test_ctx->expected_result' failed @ test/ssl_test.c:33
            # [4] compared to [0]
            # INFO:  @ test/ssl_test.c:34
            # ExpectedResult mismatch: expected Success, got FirstHandshakeFailed.
            # 139834698314176:error:14094415:SSL routines:ssl3_read_bytes:sslv3 alert certificate expired:ssl/record/rec_layer_s3.c:1543:SSL alert number 45
            not ok 5 - iteration 5
            # ERROR: (int) 'result->result == test_ctx->expected_result' failed @ test/ssl_test.c:33
            # [4] compared to [0]
            # INFO:  @ test/ssl_test.c:34
            # ExpectedResult mismatch: expected Success, got FirstHandshakeFailed.
            # 139834698314176:error:14094415:SSL routines:ssl3_read_bytes:sslv3 alert certificate expired:ssl/record/rec_layer_s3.c:1543:SSL alert number 45
            not ok 6 - iteration 6
        not ok 1 - test_handshake
../../util/shlib_wrap.sh ../ssl_test 12-ct.conf.157495.tmp => 1
    not ok 3 - running ssl_test 12-ct.conf

    #   Failed test 'running ssl_test 12-ct.conf'
    #   at ../test/recipes/80-test_ssl_new.t line 148.
    # Looks like you failed 1 test of 3.
not ok 12 - Test configuration 12-ct.conf

#   Failed test 'Test configuration 12-ct.conf'
#   at /home/nirr/Downloads/openssl-1.1.1o/test/../util/perl/OpenSSL/Test.pm line 1212.
```

**Comment by mattcaswell** [comment] 2022-06-06 09:39
Duplicate of #18456

**Comment by mattcaswell** [comment] 2022-06-06 09:39
Closing as it is a duplicate

**Closed by mattcaswell** 2022-06-06 09:39 UTC
Labels: issue: question
