### ISSUE TITLE
"openssl x509 -checkend" produces output with -noout in openssl 1.1.1

### ISSUE THREAD

**Issue by hannob** [openssl/openssl#7992] opened 2019-01-06 12:25 UTC
"openssl x509 -checked" in openssl 1.1.1 ignores the -noout parameter. In 1.0.2 this worked correctly and wouldn't produce any output, only an error code.

OpenSSL 1.1.1:
```
openssl x509 -checkend 86400 -noout -in [any cert still valid for a day]
Certificate will not expire
```

OpenSSL 1.0.2:
```
openssl x509 -checkend 86400 -noout -in [any cert still valid for a day]
```
(no output)

**Comment by mspncp** [comment] 2019-01-07 00:10
Hmmm... I believe this is intended behaviour: According to the manual page, the `-noout` option prevents only the output of the encoded version of the request, not the entire output. Just think of the command `openssl x509 -noout -text ...`:  It's neither the case nor desired that the entire output is dropped in this case, right?

I was curious however to find out when and why this behaviour changed. From comparing the source code of `x509_main` between 1.1.1 and 1.0.2 it was not obvious. I did a a little bisection, but I gave up because bisecting was too tedious  (the build system has changed too much between those versions). So the only thing I can say that the new behaviour is already present in 1.1.0.

**Comment by mspncp** [comment] 2019-01-09 12:37
@hannob did my reply answer your question? Can this issue bed closed?

**Comment by hannob** [comment] 2019-01-09 12:58
No.
If this is intended behavior then the intended behavior is bad. I'd suggest trying to apply a "least surprise for the user" principle. If "-noout" does not mean "no output" something doesn't make sense.

My use case is that I have a check of a certificate expiration and I check the return code for the result. Having no way of suppressing the output doesn't make any sense.

**Comment by t-j-h** [comment] 2019-01-09 13:10
It has always meant suppress the output to the output file for the object being output in whatever format it is being output. It has never meant suppress all output.

The strange thing is that the checkend option uses the *out* BIO rather than *STDout* BIO and I would consider that is actually an error.

Trying this:

openssl x509 -subject -in <cert>
openssl x509 -subject -noout -in <cert>

Your argument would suggest that it is intended that output for status items (and not the object) should go to the same place. That would be rather unexpected behaviour. It should be consistent.

It also seems that serial and ocspid are also treated in that manner. The mix of handling there isn't sensible and isn't documented and should be made consistent.

**Comment by seseiteu** [comment] 2019-03-28 09:54
That textual representation of the result should indeed go to stdout - I stumbled about this because a cron job started sending me alarming messages about my certificates *not* going to expire ;)

**Comment by mgedmin** [comment] 2019-09-12 07:50
What's the difference between `-noout` and `-nocert`? `--help` says

     -noout                No output, just status
     -nocert               No certificate output

Which would lead a user like me to think that `-noout` is meant to suppress _all_ output, and `-nocert` if you merely want to suppress the output of the encoded certificate.

`-nocert` is not documented in the [manual page](http://manpages.ubuntu.com/manpages/bionic/en/man1/x509.1ssl.html) on my system.

Anyway, if `-noout` is working as designed, can we please have a different option (`-quiet`?) to suppress output in scripts that only care about the exit status from `-checkend NNN`?

**Comment by waynegemmell** [comment] 2019-11-22 12:34
I would like to +1 this request. I'm going to have to wrap this function somehow to suppress the output in my script. Far from ideal.

**Comment by rbricheno** [comment] 2020-07-30 18:49
This also broke my scripts. In case any lazy sysadmin ends up here wanting a quick fix, you can just redirect stdout to /dev/null (and the exit status is still available).

Old:
```
  if ! openssl x509 -checkend $seconds -noout -in $cert; then
    # Stuff
  fi
```
New:
```
  if ! openssl x509 -checkend $seconds -noout -in $cert >/dev/null; then
    # Same stuff
  fi
```

**Comment by t8m** [comment] 2021-05-06 16:56
I am afraid changing this could break things that expect the output now. So I am closing this as wontfix.

**Closed by t8m** 2021-05-06 16:56 UTC
