### ISSUE TITLE
Failed to build openssl-src-300.3.2+3.3.2 in rust project

### ISSUE THREAD

**Issue by metercai** [openssl/openssl#25368] opened 2024-09-03 18:48 UTC
The routine compilation in GitHub action encountered a failure today due to the upgrade of 3.3.2

log:
2024-09-03T18:18:49.7286681Z   running cd "/home/runner/work/simpleai_base/simpleai_base/target/x86_64-unknown-linux-gnu/release/build/openssl-sys-a8783d2b6f7231a7/out/openssl-build/build/src" && env -u CROSS_COMPILE AR="ar" CC="sccache cc" RANLIB="ranlib" "perl" "./Configure" "--prefix=/home/runner/work/simpleai_base/simpleai_base/target/x86_64-unknown-linux-gnu/release/build/openssl-sys-a8783d2b6f7231a7/out/openssl-build/install" "--openssldir=/usr/local/ssl" "no-dso" "no-shared" "no-ssl3" "no-tests" "no-comp" "no-zlib" "no-zlib-dynamic" "--libdir=lib" "no-md2" "no-rc5" "no-weak-ssl-ciphers" "no-camellia" "no-idea" "no-seed" "linux-x86_64" "-O2" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64"
2024-09-03T18:18:49.7292338Z   Configuring OpenSSL version 3.3.2 for target linux-x86_64
2024-09-03T18:18:49.7293269Z   Using os-specific seed configuration
2024-09-03T18:18:49.7293900Z   Created configdata.pm
2024-09-03T18:18:49.7294541Z   Running configdata.pm
2024-09-03T18:18:49.7295379Z   Created Makefile.in
2024-09-03T18:18:49.7295866Z   Created Makefile
2024-09-03T18:18:49.7296522Z   Created include/openssl/configuration.h
2024-09-03T18:18:49.7296992Z 
2024-09-03T18:18:49.7297302Z   **********************************************************************
2024-09-03T18:18:49.7298037Z   ***                                                                ***
2024-09-03T18:18:49.7299033Z   ***   OpenSSL has been successfully configured                     ***
2024-09-03T18:18:49.7300160Z   ***                                                                ***
2024-09-03T18:18:49.7301084Z   ***   If you encounter a problem while building, please open an    ***
2024-09-03T18:18:49.7302239Z   ***   issue on GitHub <https://github.com/openssl/openssl/issues>  ***
2024-09-03T18:18:49.7303319Z   ***   and include the output from the following command:           ***
2024-09-03T18:18:49.7304223Z   ***                                                                ***
2024-09-03T18:18:49.7305216Z   ***       perl configdata.pm --dump                                ***
2024-09-03T18:18:49.7306150Z   ***                                                                ***
2024-09-03T18:18:49.7428039Z   ***   (If you are new to OpenSSL, you might want to consult the    ***
2024-09-03T18:18:49.7429479Z   ***   'Troubleshooting' section in the INSTALL.md file first)      ***
2024-09-03T18:18:49.7430448Z   ***                                                                ***
2024-09-03T18:18:49.7431265Z   **********************************************************************
2024-09-03T18:18:49.7433496Z   running cd "/home/runner/work/simpleai_base/simpleai_base/target/x86_64-unknown-linux-gnu/release/build/openssl-sys-a8783d2b6f7231a7/out/openssl-build/build/src" && "make" "depend"
2024-09-03T18:18:49.7437097Z   running cd "/home/runner/work/simpleai_base/simpleai_base/target/x86_64-unknown-linux-gnu/release/build/openssl-sys-a8783d2b6f7231a7/out/openssl-build/build/src" && MAKEFLAGS="-j --jobserver-fds=8,9 --jobserver-auth=8,9" "make" "build_libs"
2024-09-03T18:18:49.7440973Z   /usr/bin/perl util/mkinstallvars.pl PREFIX=. BINDIR=apps APPLINKDIR=ms LIBDIR= INCLUDEDIR=include "INCLUDEDIR=./include" ENGINESDIR=engines MODULESDIR=providers "VERSION=3.3.2" "LDLIBS=-ldl -pthread " > builddata.pm
2024-09-03T18:18:49.7442854Z 
2024-09-03T18:18:49.7443099Z   --- stderr
2024-09-03T18:18:49.7443716Z   "pairs" is not exported by the List::Util module
2024-09-03T18:18:49.7444910Z   Can't continue after import errors at util/mkinstallvars.pl line 14.
2024-09-03T18:18:49.7446122Z   BEGIN failed--compilation aborted at util/mkinstallvars.pl line 14.
2024-09-03T18:18:49.7447042Z   make: *** [builddata.pm] Error 255
2024-09-03T18:18:49.7448664Z   thread 'main' panicked at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/openssl-src-300.3.2+3.3.2/src/lib.rs:633:9:

**Comment by friesoft** [comment] 2024-09-03 18:51
You are having the same error as I did in https://github.com/openssl/openssl/issues/25366
Your List::Util perl module version is too old - there is already a patch in the linked issue/pullrequest fixing the issue :)

**Comment by t8m** [comment] 2024-09-03 18:53
Duplicate of #25366

**Closed by t8m** 2024-09-03 18:53 UTC
Labels: issue: bug report

**Comment by levitte** [comment] 2024-09-04 12:01
Fixed in #25367
