### ISSUE TITLE
x86_64 assembly not compatible with execute-only (XO) TEXT segments

### ISSUE THREAD

**Issue by jpboivin** [openssl/openssl#14058] opened 2021-02-03 16:50 UTC
Hello, I've been trying to make OpenSSL (1.1.1) work using assembly on a platform using a **x86_64** processor. This platform marks all **TEXT** segments as **execute-only** (_XO_), prohibiting read/write accesses for security. From what I've seen, no assembly is ever making a distinction from text and data sections.

As a workaround, I've manually added `.data` annotations where needed for my use cases:
- **aesni-x86_64.pl**:  the code block containing `Lbswap_mask`, `Lkey_rotate`, `Lkey_rotate192` and others.
- **x86_64-mont5.pl**: the code block containing `Linc`
- **ecp_nistz256-x86_64.pl**: the code block containing `Lpoly`, `LordK` but also  the other block for `ecp_nistz256_precomputed`
- **ghash-x86_64.pl**: the code block containing `Lbswap_mask`
- **sha1-x86_64.pl**: the code block containing `K_XX_XX`
- **sha512-x86_64.pl**: the code block containing the $TABLE (`K256` or `K512`)

**Comment by jpboivin** [comment] 2024-06-11 20:42
Note that the problem remains, it is just that I continue to have a patch (now on top of 3.0.x) to manually add .data sections around constants (duplicating the .text section prefix) for algorithms that we use.

With that said, I’d gladly try to propose a PR if OpenSSL maintainers can provide hints to the solution they’d like to see for such problem, considering that the assembly syntax using Perl is quite specific to OpenSSL.

**Comment by nhorman** [comment] 2024-06-11 20:44
If you're will (and thank you), yes that would be great, I'll move this to being a community issue and assign you to it.

Thanks for your quick response!

**Comment by davidben** [comment] 2024-06-11 20:46
I don't think this is inactive, but a triaging mistake. @Sashan already did this for x86-64 in https://github.com/openssl/openssl/pull/23997

**Comment by nhorman** [comment] 2024-06-11 20:51
oh, you're riight, so he did, this can be closed as a duplicate of that, though I'll leave it open until  @jpboivin confirms its working for him.

@jpboivin can you test with the head of the master branch please?  It seems it might save you some work :)

**Comment by jpboivin** [comment] 2024-06-11 20:52
Thanks for pointing out to this :) 

I’ll test it as soon as I can and let you know!

**Comment by jpboivin** [comment] 2024-06-17 12:55
Cherry picked both fc807a0349bbddb00273465097177025d9b4e25e and 25391acc140e215774242bf3b0a51d59754a23f4 in our 3.0.13-based branch (no conflicts) instead of my fix/workaround and tested on the special platform we support and everything works fine.

This issue can be closed as resolved by https://github.com/openssl/openssl/pull/23997.

Note: Not sure if you want to cherry-pick the fix in 3.0.x as it is the latest LTS and it seems trivial to do so.

**Comment by nhorman** [comment] 2024-06-17 14:51
ack, closing

**Closed by nhorman** 2024-06-17 14:51 UTC
Labels: triaged: feature
