### ISSUE TITLE
openssl: symbol lookup error: openssl: undefined symbol: EVP_mdc2, version OPENSSL_1_1_0

### ISSUE THREAD

**Issue by danglibin** [openssl/openssl#11856] opened 2020-05-18 07:30 UTC
The view version appears after installation
openssl: symbol lookup error: openssl: undefined symbol: EVP_mdc2, version OPENSSL_1_1_0
But I can't unload it

**Comment by romen** [comment] 2020-05-18 08:20
This kind of error in general happens when you have an application dinamically linked at build time against a more recent version of libcrypto, but then at runtime the system-wide installation of libcrypto (version 1.1.0) is being loaded.

There are notes about custom installations and how to instruct the loader to find the intended version of libcrypto at build time and at run time in INSTALL.md and NOTES.UNIX (or one of the other NOTES files depending on the platform you are targeting)

**Comment by romen** [comment] 2020-05-18 08:24
More details about your platform and involved openssl versions in your system, and how they were compiled and installed would be required to give a more fitting answer.

**Comment by danglibin** [comment] 2020-05-18 08:26
It was fixed after rebooting, but there was another problem
Create certificate error
Can't open /opt/openssl/openssl.cnf for reading, No such file or directory
139833848874304:error:02001002:system library:fopen:No such file or directory:crypto/bio/bss_file.c:69:fopen('/opt/openssl/openssl.cnf','r')
139833848874304:error:2006D080:BIO routines:BIO_new_file:no such file:crypto/bio/bss_file.c:76:

**Comment by danglibin** [comment] 2020-05-18 08:27
重新启动后已修复，但是存在另一个问题
创建证书错误
无法打开/opt/openssl/openssl.cnf进行读取，没有这样的文件或目录
139833848874304：错误：02001002：系统库：fopen：没有这样的文件或目录：crypto / bio / bss_file.c：69：fopen（'/ opt / openssl / openssl.cnf'，'r'）
139833848874304：错误：2006D080：BIO例程：BIO_new_file：无此类文件：crypto / bio / bss_file.c ：76：

**Comment by romen** [comment] 2020-05-18 08:52
Does /opt/openssl/openssl.cnf exist?
How did you compile? Usually if the prefix is /opt/openssl the conf file is expected in /opt/openssl/etc/

**Comment by danglibin** [comment] 2020-05-18 09:00
The original/opt/openssl was updated under/usr/local/openssl, but the original/opt was deleted

**Comment by romen** [comment] 2020-05-18 09:07
Did you recompile with the updated prefix for the install in /usr/local/openssl?

Moving the installed files is not enough: the paths set during configuration are used in the build process to instruct the library and the apps on where to look for certain files!

**Comment by danglibin** [comment] 2020-05-18 11:44
Whether it is possible to reinstall or respecify routing forces

**Comment by romen** [comment] 2020-05-18 11:51
@danglibin I am sorry, I am not sure I understand your comment

**Comment by danglibin** [comment] 2020-05-19 02:51
Just looking for a solution

**Comment by wesysec** [comment] 2020-05-22 03:25
I experienced this same issue.  I recently upgraded two Ubuntu 18.04 boxes to 20.04.  After the upgrade openssl package went to 1.1.1f.  This broke API calls to one of our internal solarwinds servers.  I upgraded to openssl 1.1.1g and then experienced the same symbol lookup error described here.  After running "sudo ldconfig" the issue was resolved.  Ultimately I tried backporting to 1.1.1e and that same process worked as well.  Seems there is some strange issue in 1.1.1f.  I'm not a software engineer (security guy here) so I apologize if this is a little off topic.  Just wanted to share my experience and what worked for me.

**Comment by mattcaswell** [comment] 2020-05-22 08:14
This seems to  be a dupe of #11227. Please see the advice and guidance there.

**Comment by mattcaswell** [comment] 2020-09-24 14:34
Closing this, since it seems to be answered by my last comment.

**Closed by mattcaswell** 2020-09-24 14:34 UTC
Labels: triaged: question

**Comment by kamrankausar** [comment] 2022-09-21 10:57
Ubuntu 20.04
Getting same error, but when get the openssl version using sudo, then its working, getting below error using normal user
openssl: symbol lookup error: openssl: undefined symbol: EVP_mdc2, version OPENSSL_1_1_0

**Comment by vallard** [comment] 2022-09-21 11:06
same.

**Comment by audioscavenger** [comment] 2022-12-28 23:34
same here, ubuntu 20.04, did everything right, installed to /usr/local but compiled binaries have sane error

**Comment by zengtai** [comment] 2023-03-16 03:51
> 

`sudo ldconfig` works for me too.
