### ISSUE TITLE
Build failure with musl libc due to use of obsolete makecontext

### ISSUE THREAD

**Issue by ncopa** [openssl/openssl#7406] opened 2018-10-15 19:42 UTC
Build failure on Alpine Linux:
````
${LDCMD:-gcc} -pthread -m64 -Wa,--noexecstack -Wall -O3 -Os -fomit-frame-pointer -Os -fomit-frame-pointer -g -Wa,--noexecstack -L.  -Wl,--as-needed \
        -o apps/openssl apps/asn1pars.o apps/ca.o apps/ciphers.o apps/cms.o apps/crl.o apps/crl2p7.o apps/dgst.o apps/dhparam.o apps/dsa.o apps/dsaparam.o apps/ec.o apps/ecparam.o apps/enc.o apps/engine.o apps/errstr.o apps/gendsa.o apps/genpkey.o apps/genrsa.o apps/nseq.o apps/ocsp.o apps/openssl.o apps/passwd.o apps/pkcs12.o apps/pkcs7.o apps/pkcs8.o apps/pkey.o apps/pkeyparam.o apps/pkeyutl.o apps/prime.o apps/rand.o apps/rehash.o apps/req.o apps/rsa.o apps/rsautl.o apps/s_client.o apps/s_server.o apps/s_time.o apps/sess_id.o apps/smime.o apps/speed.o apps/spkac.o apps/srp.o apps/storeutl.o apps/ts.o apps/verify.o apps/version.o apps/x509.o \
         apps/libapps.a -lssl -lcrypto -lz -ldl -pthread 
/usr/lib/gcc/x86_64-alpine-linux-musl/8.2.0/../../../../x86_64-alpine-linux-musl/bin/ld: ./libcrypto.so: undefined reference to `getcontext'
/usr/lib/gcc/x86_64-alpine-linux-musl/8.2.0/../../../../x86_64-alpine-linux-musl/bin/ld: ./libcrypto.so: undefined reference to `setcontext'
/usr/lib/gcc/x86_64-alpine-linux-musl/8.2.0/../../../../x86_64-alpine-linux-musl/bin/ld: ./libcrypto.so: undefined reference to `makecontext'
collect2: error: ld returned 1 exit status
````

The `getcontext`, `setcontext` and `makecontext` were marked obsolescent in [POSIX.1-2001](http://pubs.opengroup.org/onlinepubs/009695399/functions/makecontext.html#tag_03_356_08) and removed from POSIX.1-2008, which means that OpenSSL is not portable to any modern libc.

**Comment by wongsyrone** [comment] 2018-10-16 00:36
The temporary workaround is to add `no-async` configure option when using musl-libc.

**Comment by dot-asm** [comment] 2018-10-17 08:15
#7420.

**Comment by dot-asm** [comment] 2018-10-19 08:33
#7420 is merged. Closing. For the record, yes, I reproduced the problem and confirmed the fix.

**Closed by dot-asm** 2018-10-19 08:33 UTC

**Comment by mohitbansal19** [comment] 2020-06-25 07:25
We upgraded openssl from 1.0.2o to 1.1.1d and using "powerpc-hac-linux-uclibc" and "x86_64-hm-linux-uclibc" for compiling. 
Openssl is compiled successfully but when we compile ntp module (4.2.8p9) getting some undefined references:- 
libcrypto.so: undefined reference to `getcontext'
libcrypto.so: undefined reference to `setcontext'
libcrypto.so: undefined reference to `makecontext'

We are compiling openssl with ASYNC and no-async operation will not work with us.
Can someone help me here?

Thanks
Mohit Bansal

**Comment by mattcaswell** [comment] 2020-06-25 13:29
> We are compiling openssl with ASYNC and no-async operation will not work with us.
Can someone help me here ASAP?

I find it slightly strange that you must have ASYNC support if you are upgrading from 1.0.2 - because ASYNC support did not exist in 1.0.2. If you really *must* have it, then it looks like you're out of luck...you don't seem to have getcontext/setcontext/makecontext support in your libc - which is an absolute requirement for that functionality to work. You either have to swap to some other libc, or disable async.
