### ISSUE TITLE
Test suite failure in 70-test_sslrecords.t

### ISSUE THREAD

**Issue by kroeckx** [openssl/openssl#3562] opened 2017-05-25 21:59 UTC
In https://buildd.debian.org/status/fetch.php?pkg=openssl&arch=kfreebsd-i386&ver=1.1.0f-1&stamp=1495748849&raw=0 I'm getting:
```
Test Summary Report
-------------------
../../test/recipes/70-test_sslrecords.t     (Wstat: 0 Tests: 10 Failed: 0)
  Parse errors: Tests out of sequence.  Found (5) but expected (4)
                Tests out of sequence.  Found (6) but expected (5)
                Tests out of sequence.  Found (7) but expected (6)
                Tests out of sequence.  Found (8) but expected (7)
                Tests out of sequence.  Found (9) but expected (8)
Displayed the first 5 of 8 TAP syntax errors.
Re-run prove with the -p option to see them all.
Files=95, Tests=534, 71 wallclock secs ( 1.27 usr  0.37 sys + 52.25 cusr 19.22 csys = 73.10 CPU)
Result: FAIL
```

**Comment by mattcaswell** [comment] 2017-05-25 22:04
I have seen this in Travis too:

https://travis-ci.org/openssl/openssl/jobs/234814816

It doesn't seem to be happening at the moment, so I think it is intermittent. So far I have not been able to reproduce it.

**Comment by kroeckx** [comment] 2017-05-25 22:26
Here I see more of the same type, also in other tests:
https://buildd.debian.org/status/fetch.php?pkg=openssl&arch=hurd-i386&ver=1.1.0f-1&stamp=1495750462&raw=0

**Comment by mattcaswell** [comment] 2017-05-25 22:30
But can you reproduce locally? If so...how?

**Comment by kroeckx** [comment] 2017-05-25 22:43
The only thing I can say currently is that I only see it in shared builds. Since that's now the default, I guess you test that too?

**Comment by mattcaswell** [comment] 2017-05-25 22:58
Yes

**Comment by kroeckx** [comment] 2017-05-26 10:54
It at least seems very reproducible on hurd-i386:
https://buildd.debian.org/status/logs.php?pkg=openssl&ver=1.1.0f-1&arch=hurd-i386

**Comment by mattcaswell** [comment] 2017-05-26 11:20
I think I know what is happening. There is a race condition going on. I think the bug has been there for a long time, but I suspect commit 76e0d0b21c has somehow made it visible because it is related to the way the test output is printed and parsed by the harness.

I took a detailed look at the output from this travis failure:

https://travis-ci.org/openssl/openssl/jobs/236307668

The complaint from the test harness is this:
````
../test/recipes/70-test_sslrecords.t     (Wstat: 0 Tests: 10 Failed: 0)
  Parse errors: Tests out of sequence.  Found (4) but expected (3)
                Tests out of sequence.  Found (5) but expected (4)
                Tests out of sequence.  Found (6) but expected (5)
                Tests out of sequence.  Found (7) but expected (6)
                Tests out of sequence.  Found (8) but expected (7)
Displayed the first 5 of 9 TAP syntax errors.
````
IIRC the test harness parses the output from the tests looking for the "ok" line but, from the above errors, it looks like it sees tests 1 and 2, and then the next test result it sees is 4! So what happens to test 3? Well it *is* run and the output *is* there. Here it is:

````
Waiting for server process to close: 22624
depth=0 C = UK, O = OpenSSL Group, OU = FOR TESTING PURPOSES ONLY, CN = Test Server Cert
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 C = UK, O = OpenSSok 3 - Too many in context empty records test
L Group, OU = FOR TESTING PURPOSES ONLY, CN = Test Server Cert
verify error:num=21:unable to verify the first certificate
verify return:1
````
So, the test harness it printing out the results of the test, but some other process is still running at the time and it is printing out stuff, so the "ok" message appears in the middle of a line where the test harness is not expecting to find it.

Looking at the proxy, it closes off a test run like this:
````
    if($server_sock) {
        $server_sock->close();
    }
    if($client_sock) {
        #Closing this also kills the child process
        $client_sock->close();
    }
    if($proxy_sock) {
        $proxy_sock->close();
    }
    if(!$self->debug) {
        select($oldstdout);
    }
    $self->serverconnects($self->serverconnects - 1);
    if ($self->serverconnects == 0) {
        die "serverpid is zero\n" if $self->serverpid == 0;
        print "Waiting for server process to close: "
              .$self->serverpid."\n";
        waitpid( $self->serverpid, 0);
        die "exit code $? from server process\n" if $? != 0;
    }
    return 1;
````
So you can see it waits for the server pid to indicate the process has finished before continuing, but on the client side it just relies on the client to close itself down when the proxy closes its socket. If the client is busy doing something else at the time (like printing stuff on the screen), then it may not notice immediately so there may be a short delay until it closes itself down. Probably what we need to do is make the Proxy wait on the client process pid too.

**Comment by mattcaswell** [comment] 2017-05-26 12:12
See #3567 for my proposed fix.

**Closed** 2017-05-26 18:15 UTC
