### ISSUE TITLE
OpenSSL version mismatch. Built against 1000207f, you have 100010bf

### ISSUE THREAD

**Issue by monajalal** [openssl/openssl#1631] opened 2016-09-27 19:44 UTC
Please advise how to fix this:
```
jalal@klein:~$ ssh -i "hyunwoo_key.pem" ubuntu@ec2-52-23-201-2.compute-1.amazonaws.com
ssh: /home/jalal/computer_vision/MCR/v901/bin/glnxa64/libcrypto.so.1.0.0: no version information available (required by ssh)
ssh: /home/jalal/computer_vision/MCR/v901/bin/glnxa64/libcrypto.so.1.0.0: no version information available (required by ssh)
OpenSSL version mismatch. Built against 1000207f, you have 100010bf
```
Further details of my question can be found here: http://askubuntu.com/questions/830466/libcrypto-so-1-0-0-no-version-information-available-required-by-ssh

**Comment by FdaSilvaYY** [comment] 2016-09-27 21:19
Built against 1000207f, => it was build against an OpenSSL version labeled 1.0.2f ( f is the 7th letter  and last f means final ) 
you have 100010bf     => it is loading the binaries of OpenSSL version labeled 1.0.1 l  ( L is 12th letter, 0x0b in hexa) 

Your app don't find the right version of the lib who has been used to build it.

HTH.

**Comment by mattcaswell** [comment] 2016-09-27 22:50
This is caused by running Ubuntu supplied applications that are built against the Ubuntu patched version of OpenSSL, but linking them at run time against a non-Ubuntu supplied version of OpenSSL. I have added further details against your askubuntu question. As this is not an OpenSSL problem (its a problem with your Ubuntu setup), I am closing this issue.

**Closed by mattcaswell** 2016-09-27 22:50 UTC
