### ISSUE TITLE
openssl with ChaCha20-Poly1305 to encrypt file

### ISSUE THREAD

**Issue by nonvwvnon** [openssl/openssl#26284] opened 2024-12-30 03:00 UTC
Need to know openssl 1.1.x or openssl 3.x had the feature of using ChaCha20-Poly1305 to encrypt file
I would appreciate your engineer give an example on how to do it from commandline.
Thank you.

**Comment by 0xGSMonkey** [comment] 2024-12-30 06:27
Have you tried using ```openssl list -all-algorithms``` ? There are so many algorithms.

**Comment by t8m** [comment] 2024-12-30 16:56
No, it is not possible to encrypt a file with Chacha20-Poly1305 from an openssl command line.

**Comment by t8m** [comment] 2024-12-30 16:58
Actually a duplicate of #24421

**Closed by t8m** 2024-12-30 16:58 UTC
Labels: branch: master, help wanted, triaged: feature
