### ISSUE TITLE
[Feature Request] Implement Maximum Fragment Length TLS extension

### ISSUE THREAD

**Issue by damv** [openssl/openssl#955] opened 2016-04-08 17:20 UTC
The maximum fragment length extension seems to not be supported by OpenSSL.
This extension enables to negociate the maximum fragment length value, which is 16kB by default.
It is mandatory to interact with embedded clients which do not have enough RAM to allocate 16kB buffers.
A patch has been submitted (see https://groups.google.com/forum/#!topic/mailing.openssl.dev/fQxXvCg1uQY) in 2014 to support this extension. It was made for RFC 4366 but the last version RFC 6066 does not seem to change the extension definition (see https://tools.ietf.org/html/rfc6066#appendix-A).
If somebody review this patch and integrate it to openSSL, it would benefit the IoT world.

**Comment by richsalz** [comment] 2016-04-09 12:47
Just so you know, it is very very late in the dev cycle for this release.  Personally I doubt this will make it into 1.1

**Comment by iduhetonas** [comment] 2017-01-05 10:36
Second on this, as we have a solution that uses mbedtls with an option to change the maximum fragment length for saving on limited RAM space, but no option seems to currently exist for OpenSSL.

**Comment by MrBuddyCasino** [comment] 2017-04-26 09:24
This is an important feature to add. The current state of IoT security is shameful, but requiring 32KB of buffers (16K RX + 16K TX) for an SSL connection is not helping the cause. We could easily reduce it with this feature and make adoption SSL less painful for embedded projects, as the mbedTLS project already supports it.

**Comment by muellerc** [comment] 2017-06-08 21:50
Hi guys,

any progress here after one year?

**Comment by mattcaswell** [comment] 2017-06-08 22:48
Yes, it is being actively worked on in #1008

**Comment by FdaSilvaYY** [comment] 2017-11-05 17:15
Just landed into master branch as cf72c75 !

**Comment by kaduk** [comment] 2018-01-10 20:31
This was done in #1008; closing this issue after an unfortunately long delay.

**Closed by kaduk** 2018-01-10 20:31 UTC
Labels: feature

**Comment by oudebooijink** [comment] 2018-02-07 11:37
Can we make this compatible with tlsSocket.setMaxSendFragment() in the Node TLS module ? This still has a maximum of 16834 .

**Comment by mattcaswell** [comment] 2018-02-07 11:45
Well that's a comment for the Node guys really. But I assume that function is just a thin wrapper around the OpenSSL `SSL_set_max_send_fragment()` function.

16384 is a maximum imposed by the TLS specification and cannot be changed without a spec change. There is no incompatibility between the functionality in this PR and `SSL_set_max_send_fragment()`. This PR is about adding the ability for the two peers to negotiate between them what fragment size they will use (up to the max of 16384). The  `SSL_set_max_send_fragment()` function is about one peer unilaterally deciding to set its own maximum fragment size to a given value (up to the 16384 max). So they are doing different jobs.

**Comment by oudebooijink** [comment] 2018-02-07 12:04
Ok, thank you for clarifying. Do you know of any PR that implements a bigger fragment size than 16384?

**Comment by mattcaswell** [comment] 2018-02-07 12:06
> Ok, thank you for clarifying. Do you know of any PR that implements a bigger fragment size than 16384?

No. Like I said this would require a spec change by IETF. AFAIK this is not being looked at by anyone.
