### ISSUE TITLE
code confusion when I read this

### ISSUE THREAD

**Issue by willmafh** [openssl/openssl#26245] opened 2024-12-23 02:53 UTC
https://github.com/openssl/openssl/blob/b3bb214720f20f3b126ae4b9c330e9a48b835415/crypto/evp/p_lib.c#L1505

Is there anyone can explain it to me? Is this a typo? Why does it use `e == NULL` instead of `e != NULL` here?

**Comment by t-j-h** [comment] 2024-12-23 07:09
Looks like a bug to me ...

**Comment by baentsch** [comment] 2024-12-24 11:52
fwiw, this is not an exactly intuitive code pattern; it's correct, but not obvious. Worthwhile adding a comment in the code to close out the issue and avoid others wondering again? If not, what's the approach to close issues in general? Should this linger with the tags "bug" and "not a bug"? Seems a bit strange, no?

**Comment by t8m** [comment] 2024-12-30 10:35
@baentsch Feel free to add a PR with an appropriate comment.

As for the issue lingering around - I did not immediately close it to give the reporter time to react. But I am closing it now.

**Closed by t8m** 2024-12-30 10:35 UTC
Labels: resolved: not a bug, triaged: bug

**Comment by baentsch** [comment] 2025-01-02 11:33
Thanks for the explanation @t8m. As this a) pertains to engines that are not particularly "appreciated" in the age of providers and b) you already closed the issue, I'd leave this alone - assuming this code will vanish together with engine support, so no-one will stumble across this anyway again.
