### ISSUE TITLE
openssl 3.0 : Speed test gives zero result when using pipe tee.

### ISSUE THREAD

**Issue by jaingaurav2712** [openssl/openssl#17532] opened 2022-01-17 10:03 UTC
failure logs:
**$ openssl speed -engine devcrypto -multi 8 -elapsed -evp aes-128-cbc | tee test.log**
```
Forked child 0
Forked child 1
.....
+R:1130:AES-128-CBC:3.000000
+R:[  254.685282] audit: type=1701 audit(1637346259.131:4): auid=4294967295 uid=0 gid=0 ses=4294967295 pid=19312 comm=\"openssl\" exe=\"/usr/bin/openssl\" sig=11 res=1
1107:AES-128-CBC:3.000000
+R:112[  254.699678] audit: type=1701 audit(1637346259.135:5): auid=4294967295 uid=0 gid=0 ses=4294967295 pid=19310 comm=\"openssl\" exe=\"/usr/bin/openssl\" sig=11 res=1
6:AES-128-CBC:3.000000
+R:1158:A[  254.716612] audit: type=1701 audit(1637346259.135:6): auid=4294967295 uid=0 gid=0 ses=4294967295 pid=19313 comm=\"openssl\" exe=\"/usr/bin/openssl\" sig=11 res=1
ES-128-CBC:3.000000
+R:1151:AES-[  254.733550] audit: type=1701 audit(1637346259.135:7): auid=4294967295 uid=0 gid=0 ses=4294967295 pid=19306 comm=\"openssl\" exe=\"/usr/bin/openssl\" sig=11 res=1
128-CBC:3.000000
Forked child 7[  254.749111] cryptodev: driver unloaded.
version: 3.0.0
built on: built [  254.750503] audit: type=1701 audit(1637346259.139:8): auid=4294967295 uid=0 gid=0 ses=4294967295 pid=19309 comm=\"openssl\" exe=\"/usr/bin/openssl\" sig=11 res=1
on: Tue Sep  7 11:46:32 2021 UTC[  254.774136] audit: type=1701 audit(1637346259.139:9): auid=4294967295 uid=0 gid=0 ses=4294967295 pid=19308 comm=\"openssl\" exe=\"/usr/bin/openssl\" sig=11 res=1
options:bn(64,64) 
compiler: aa[  254.791039] audit: type=1701 audit(1637346259.139:10): auid=4294967295 uid=0 gid=0 ses=4294967295 pid=19307 comm=\"openssl\" exe=\"/usr/bin/openssl\" sig=11 res=1
[  254.808101] audit: type=1701 audit(1637346259.143:11): auid=4294967295 uid=0 gid=0 ses=4294967295 pid=19311 comm=\"openssl\" exe=\"/usr/bin/openssl\" sig=11 res=1
rch64-poky-linux-gcc  -mcpu=cortex-a53 -march=armv8-a+crc+crypto -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Wdate-time --sysroot=recipe-sysroot -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=                      -fdebug-prefix-map=                      -fdebug-prefix-map=                      -fdebug-prefix-map=  -DOPENSSL_USE_NODELETE -DOPENSSL_PIC -DOPENSSL_BUILDING_OPENSSL -DNDEBUG
CPUINFO: OPENSSL_armcap=0xbf
evp                  0.00         0.00         0.00         0.00         0.00         0.00 
```

Success log without pipe tee
**$ openssl speed -engine devcrypto -multi 8 -elapsed -evp aes-128-cbc**
```
Forked child 0
Forked child 1
...
Got: +H:16:64:256:1024:8192:16384 from 1
Got: +F:25:AES-128-CBC:400765.22:1724501.33:4028330.67:5834410.67:6174037.33:6167133.55 from 1
Got: +H:16:64:256:1024:8192:16384 from 2
Got: +F:25:AES-128-CBC:421415.38:1731370.67:4025088.00:5618005.33:6164548.49:6149461.33 from 2
Got: +H:16:64:256:1024:8192:16384 from 3
Got: +F:25:AES-128-CBC:426242.14:1732794.65:4022528.00:5638826.67:6179498.67:6208385.28 from 3
Got: +H:16:64:256:1024:8192:16384 from 4
Got: +F:25:AES-128-CBC:411833.56:1685205.33:4016213.33:5669205.33:6108501.33:6160384.00 from 4
Got: +H:16:64:256:1024:8192:16384 from 5
Got: +F:25:AES-128-CBC:425812.97:1480362.67:4025344.00:5775018.67:6119424.00:6187690.67 from 5
Got: +H:16:64:256:1024:8192:16384 from 6
Got: +F:25:AES-128-CBC:370832.00:1633536.00:4013738.67:5734058.67:6149461.33:6154922.67 from 6
Got: +H:16:64:256:1024:8192:16384 from 7
Got: +F:25:AES-128-CBC:391856.00:1567424.00:4017322.67:5698560.00:6083925.33:6198613.33 from 7
version: 3.0.0
built on: Tue Sep  7 11:46:32 2021 UTC
options: bn(64,64)
compiler: aarch64-poky-linux-gcc  -mcpu=cortex-a53 -march=armv8-a+crc+crypto -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Wdate-time --sysroot=recipe-sysroot -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=                      -fdebug-prefix-map=                      -fdebug-prefix-map=                      -fdebug-prefix-map=  -DOPENSSL_USE_NODELETE -DOPENSSL_PIC -DOPENSSL_BUILDING_OPENSSL -DNDEBUG
CPUINFO: OPENSSL_armcap=0xbf
evp               2848.76k    11555.19k    28148.57k    39968.09k    42979.40k    43226.59k
```

**Comment by t8m** [comment] 2022-01-18 11:08
Unfortunately I cannot reproduce this issue. Is the `-engine devcrypto` critical to reproduce it?

**Comment by jaingaurav2712** [comment] 2022-01-18 11:12
Yes ```-engine devcrypto``` is critical.
using this we are trying to offload symmetric cipher ```aes-128-cbc``` via cryptodev module.

this test is working well with previous openssl versions (1.1.1l) and broken in openssl 3.0

**Comment by jaingaurav2712** [comment] 2022-03-28 11:11
any update on this?

**Comment by t8m** [comment] 2022-10-11 15:27
Duplicate of #17995

**Closed by t8m** 2022-10-11 15:27 UTC
Labels: help wanted, triaged: bug, branch: 3.0
