### ISSUE TITLE
X25519 Incorrect Key Exchange

### ISSUE THREAD

**Issue by reaperhulk** [openssl/openssl#6687] opened 2018-07-10 12:16 UTC
While integrating the [wycheproof](https://github.com/google/wycheproof) tests into another project I stumbled across what appears to be an issue with the x86_64 assembly implementation for x25519. The following code works fine on OpenSSL 1.1.0 and early 1.1.1 betas, but fails after commit https://github.com/openssl/openssl/commit/0e5c8d566029a995d1fa23cac0f828c39519d97f (when the x25519 assembly is enabled). The `tcId` numbers in the code below can be correlated to the [x25519 wycheproof vectors](https://github.com/google/wycheproof/blob/2904be69e9d666bf3064fdc15093747e695cfae6/testvectors/x25519_test.json) to see a bit more context.

Edit: This is reproducible on an Intel i7-6820HQ CPU

```c
#include <assert.h>
#include <stdio.h>
#include <string.h>
#include <openssl/crypto.h>
#include <openssl/evp.h>
#include <openssl/x509.h>


int main(void) {
    OPENSSL_init();
    int res;
    int ret = 0;
    unsigned char *public[5];
    unsigned char *private[5];
    unsigned char *shared[5];
    /* pkcs8 prefix added to the private keys: 302e020100300506032b656e04220420 */
    /* tcId: 50 */
    public[0] = OPENSSL_hexstr2buf("f0ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff7f", NULL);
    private[0] = OPENSSL_hexstr2buf("302e020100300506032b656e04220420288796bc5aff4b81a37501757bc0753a3c21964790d38699308debc17a6eaf8d", NULL);
    shared[0] = OPENSSL_hexstr2buf("b4e0dd76da7b071728b61f856771aa356e57eda78a5b1655cc3820fb5f854c5c", NULL);
    /* tcId: 62 */
    public[1] = OPENSSL_hexstr2buf("f0ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff", NULL);
    private[1] = OPENSSL_hexstr2buf("302e020100300506032b656e0422042060887b3dc72443026ebedbbbb70665f42b87add1440e7768fbd7e8e2ce5f639d", NULL);
    shared[1] = OPENSSL_hexstr2buf("38d6304c4a7e6d9f7959334fb5245bd2c754525d4c91db950206926234c1f633", NULL);
    /* tcId: 67 */
    public[2] = OPENSSL_hexstr2buf("0ab4e76380d84dde4f6833c58f2a9fb8f83bb0169b172be4b6e0592887741a36", NULL);
    private[2] = OPENSSL_hexstr2buf("302e020100300506032b656e04220420a0a4f130b98a5be4b1cedb7cb85584a3520e142d474dc9ccb909a073a976bf63", NULL);
    shared[2] = OPENSSL_hexstr2buf("0200000000000000000000000000000000000000000000000000000000000000", NULL);
    /* tcId: 68 */
    public[3] = OPENSSL_hexstr2buf("89e10d5701b4337d2d032181538b1064bd4084401ceca1fd12663a1959388000", NULL);
    private[3] = OPENSSL_hexstr2buf("302e020100300506032b656e04220420a0a4f130b98a5be4b1cedb7cb85584a3520e142d474dc9ccb909a073a976bf63", NULL);
    shared[3] = OPENSSL_hexstr2buf("0900000000000000000000000000000000000000000000000000000000000000", NULL);
    /* tcId: 69 */
    public[4] = OPENSSL_hexstr2buf("2b55d3aa4a8f80c8c0b2ae5f933e85af49beac36c2fa7394bab76c8933f8f81d", NULL);
    private[4] = OPENSSL_hexstr2buf("302e020100300506032b656e04220420a0a4f130b98a5be4b1cedb7cb85584a3520e142d474dc9ccb909a073a976bf63", NULL);
    shared[4] = OPENSSL_hexstr2buf("1000000000000000000000000000000000000000000000000000000000000000", NULL);
    for (int i=0; i < 5; i++) {
        printf("Iteration %d\n", i);
        EVP_PKEY *pkey = EVP_PKEY_new();
        assert(pkey != NULL);

        res = EVP_PKEY_set_type(pkey, NID_X25519);
        assert(res != 0);

        res = EVP_PKEY_set1_tls_encodedpoint(pkey, public[i], 32);
        assert(res != 0);

        BIO *private_bio = BIO_new_mem_buf(private[i], 48);
        assert(private_bio != NULL);

        EVP_PKEY *skey = d2i_PrivateKey_bio(private_bio, NULL);
        assert(skey != NULL);

        EVP_PKEY_CTX *ctx = EVP_PKEY_CTX_new(skey, NULL);
        assert(ctx != NULL);

        res = EVP_PKEY_derive_init(ctx);
        assert(res == 1);

        res = EVP_PKEY_derive_set_peer(ctx, pkey);
        assert(res == 1);

        size_t keylen = 32;
        unsigned char buf[32] = {0};
        res = EVP_PKEY_derive(ctx, buf, &keylen);
        assert(res == 1);
        res = memcmp(buf, shared[i], 32);
        if (res != 0) {
            printf("Shared key does not match expectation\n");
            printf("computed: %s\n", OPENSSL_buf2hexstr(buf, 32));
            printf("expected: %s\n", OPENSSL_buf2hexstr(shared[i], 32));
            ret = 1;
        } else {
            printf("Test case iteration %d passed\n", i);
        }
    }
    exit(ret);
}
```

(This test code obviously leaks memory like a sieve, but that doesn't matter for this purpose)

**Comment by bernd-edlinger** [comment] 2018-07-11 10:02
Hmm, the private key is 2^255 - 16 which is larger than 2^255-19, thus invalid.
how can they expect a correct answer ?

**Comment by bernd-edlinger** [comment] 2018-07-11 11:34
yes, look at x25519_fe64_tobytes it converts 2^255-16 to 2^255-16 not 3

**Comment by sneves** [comment] 2018-07-11 11:59
All of `x25519_fe64_add`, `x25519_fe64_sub`, and `x25519_fe64_tobytes` have problems. `x25519_fe64_tobytes` did not properly normalize every 256-bit integer to the appropriate range. `x25519_fe64_add` and `x25519_fe64_sub` are missing one last carry handling step in the rare case where the addition/subtraction by 38 overflows once again. Fixing this, with another conditional addition/subtraction of 38, fixes all failing tests.

It remains to be determined whether these are the only incorrect carries. I have no no other cases so far.

**Comment by davidben** [comment] 2018-07-11 17:48
Re the public key being larger, see https://tools.ietf.org/html/rfc7748#section-5:

>   Implementations MUST accept non-canonical values and process them as
>   if they had been reduced modulo the field prime.  The non-canonical
>   values are 2^255 - 19 through 2^255 - 1 for X25519 and 2^448 - 2^224
>   \- 1 through 2^448 - 1 for X448.

**Comment by dot-asm** [comment] 2018-07-11 20:54
> look at x25519_fe64_tobytes it converts 2^255-16 to 2^255-16 not 3

It doesn't actually have to return 3. Such values are referred to as partially reduced, and they are common place as intermediate results. What counts here(*) is to tie *final* value prior it's returned to application. That's what fe64_tobytes failed to do.

(*) "Here" means in x25519, as in other cases it might be necessary to fully reduce even intermediate results.

**Comment by dot-asm** [comment] 2018-07-11 20:57
> x25519_fe64_add,

Addition failed if *both* inputs were partially reduced.

> x25519_fe64_sub

Subtraction can't fail even if both inputs are partially reduced, so one doesn't need any extra steps.

**Comment by dot-asm** [comment] 2018-07-11 21:03
#6699.

**Comment by dot-asm** [comment] 2018-07-11 21:10
>> x25519_fe64_sub

> Subtraction can't fail even if both inputs are partially reduced, so one doesn't need any extra steps.

This might need closer consideration... I mean I might be wrong about this, I need to sleep on it...

**Comment by sneves** [comment] 2018-07-11 21:22
`x25519_fe64_sub` fails, in particular, when subtracting `0xffff....ffff` from `0`. the result should be `ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffb5` (modulo 2^256-38) but it is instead `1`.

**Comment by bernd-edlinger** [comment] 2018-07-12 08:55
Yes, I think that is right.
we want to compute 0 - (2^256-1) modulo 2^256-38
the result is negative, therefore we add 2^256-38:
-2^256+1 + 2^256-38 = -37
but the result is still negative, therefore we add again 2^256-38:
-37 + 2^256-38 = 2^256-75
or (0xffff....ffffb5).

**Comment by dot-asm** [comment] 2018-07-12 09:08
#6699 is updated to cover even subtraction. I got confused by certain asymmetry. For addition to fail *both* inputs need to be partially reduced, while for subtraction to fail subtrahend *alone* needs to be partially reduced. Thanks for straighting it up!

**Comment by bernd-edlinger** [comment] 2018-07-12 09:10
Yes, the problem is that the mathematical meaning of the inputs/outputs is nowhere documented.
no C code, only the assmbler code.

**Comment by bernd-edlinger** [comment] 2018-07-12 09:17
For the addition consider, we want to add two numbers in the range 0..2^256-1
we want the result to be accurate modulo 2^256-38.
So if A + B < 2^256-1 we are done.
consider A=2^256-1 and B=2^256-1
A+B = 2*2^256-2
Since that is larger than 2^256-1 we subtract 2^256-38:
2*2^256-2 - 2^256+38 = 2^256+36
Since this is still larger than 2^256-1 we subtract 2^256-38 again:
2^256+36 - 2^256+38 = 74
which is in the range 0..2^256-1 so we are done.

**Comment by dot-asm** [comment] 2018-07-12 09:35
Yes, amended version does that. Original version worked if at most one input was partially reduced. (BTW, it's A+B<2^256. And "accurate modulo" is a bit misleading, because partially reduced output is still permitted. I mean "accurate modulo" suggests that result is always fully reduced.)

**Comment by bernd-edlinger** [comment] 2018-07-12 09:53
We need the result to be in the range 0..2^256-1 and be equivalent modulo 2^256-38,
so for instance 1 and 2^256-37 would be equivalent, you can choose which one.

**Comment by dot-asm** [comment] 2018-07-12 09:56
As for nowhere documented. Trouble is that it's infeasible to write all the background, and there always be something that is implied to be known :-( I've added some minimalistic comment though...

**Comment by dot-asm** [comment] 2018-07-12 09:59
> We need the result to be in the range 0..2^256-1 and be equivalent modulo 2^256-38, so for instance 1 and 2^256-37 would be equivalent, you can choose which one.

Right. But if this is remark to remark about "accurate modulo" is being confusing, then it kind of makes my point. "Accurate" implies *single* possibility, while you say yourself we are free to choose between *two*...

**Comment by bernd-edlinger** [comment] 2018-07-12 10:09
Sure, I see your point, and I only wanted to clarify what I mean.
For me, I did not know before-hand what fe64 was supposed to do.
But fe51 is not any better, FWIW.

**Comment by dot-asm** [comment] 2018-07-15 17:16
Fix is merged. Thanks for report!

**Closed by dot-asm** 2018-07-15 17:16 UTC
