### ISSUE TITLE
alpha3: Testsuite fails on hurd due to truncated error code

### ISSUE THREAD

**Issue by sebastianas** [openssl/openssl#12276] opened 2020-06-25 22:17 UTC
The test 04-test_err.t fails on hurd:

> 04-test_err.t ...................... 
>  The results of this test will end up in test-runs/test_err
> 1..1
>     # Subtest: ../../test/errtest
>     1..4
>     ok 1 - preserves_system_error
>     ok 2 - vdata_appends
>     ok 3 - raised_error
>     # ERROR: (string) 'expected == p' failed @ ../test/errtest.c:56
>     # --- expected
>     # +++ p
>     #    0:- ':error::system library:test_print_error_format:Operation not per'
>     #    0:+ ':error::system library:test_print_error_format:(os/kern) invalid'
>     #                                                        ^^^^^^^^^ ^^^^^^^
>     #   64:- 'mitted:errtest.c:30:'
>     #   64:+ ' address:errtest.c:3'
>     #         ^^^^^^^^^^^^^^^^^^^^
>     # 
 >    not ok 4 - test_print_error_format
 >../../util/wrap.pl ../../test/errtest => 1
 >not ok 1 - running errtest

errtest.c does:
>     ERR_PUT_error(ERR_LIB_SYS, 0, 1, "errtest.c", 30);

where 1 should be EPERM. And EPERM on hurd is 
> bigeasy@exodar:~$ grep EPERM /usr/include/i386-gnu/bits/errno.h
>  EPERM                          = 0x40000001,  /* Operation not permitted */
> #define EPERM                          0x40000001

So it is an int and it does not fit in 24bit which I believe is the what the code relies on judging by looking at ERR_PACK() and ERR_GET_REASON(). 
The errno number one is EKERN_INVALID_ADDRESS which explains the actual printed error message.

I don't think that this macros / kind of error handling is something new. I noticed that this test is behind 
OPENSSL_NO_DEPRECATED_3_0. Is this "reducing errno to 24bits" deprecated or just this set of functions?
Any idea what we can do about it?

**Comment by levitte** [comment] 2020-06-26 09:05
Duplicate of #12217

**Comment by levitte** [comment] 2020-06-26 09:11
This was reported once already, but does fill in details I asked about there.  Thank you.

> I don't think that this macros / kind of error handling is something new. I noticed that this test is behind
OPENSSL_NO_DEPRECATED_3_0. Is this "reducing errno to 24bits" deprecated or just this set of functions?
> Any idea what we can do about it?

Just the functions, the 24-bit limitation is still there.  The hurd errno values are...  a bit of a surprise!  (they are perfectly valid, though, since [the errno is an `int`](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/errno.h.html))

I'm currently out of ideas what to do with it, but will look.

**Comment by richsalz** [comment] 2020-06-26 13:02
For now, just test/mask with 24-bit and if not the same, set to zero?

**Comment by levitte** [comment] 2020-06-26 13:30
> For now, just test/mask with 24-bit and if not the same, set to zero?

Uhmmmmm...  and that helps, how?  Or well, if you do have a concrete idea that works, PR welcome!

**Comment by sebastianas** [comment] 2020-06-26 17:14
So I shifted the upper bit down:

```
diff --git a/include/openssl/err.h b/include/openssl/err.h
index aa8ffa9765f8d..618e3c0f11a79 100644
--- a/include/openssl/err.h
+++ b/include/openssl/err.h
@@ -164,12 +164,16 @@ struct err_state_st {
 # endif
 
 # define ERR_PACK(l,f,r) ( \
-        (((unsigned int)(l) & 0x0FF) << 24L) | \
-        (((unsigned int)(f) & 0xFFF) << 12L) | \
-        (((unsigned int)(r) & 0xFFF)       ) )
+        (((unsigned int)(l) & 0x0FF)      << 24L) | \
+        (((unsigned int)(f) & 0xFFF)      << 12L) | \
+        (((unsigned int)(r) & 0x40000000) >> 19L) | \
+        (((unsigned int)(r) & 0x7FE)            ))
 # define ERR_GET_LIB(l)          (int)(((l) >> 24L) & 0x0FFL)
 # define ERR_GET_FUNC(l)         (int)(((l) >> 12L) & 0xFFFL)
-# define ERR_GET_REASON(l)       (int)( (l)         & 0xFFFL)
+# define ERR_GET_REASON(r) ( \
+        (((unsigned int)(r) & 0x800) << 19L) | \
+        (((unsigned int)(r) & 0x7FF)            ))
+

```
However this has a problem that `r' is evaluated twice. So I made this:
```
# define ERR_PACK(l,f,r)                                \
 ({                                                      \
          unsigned int _r = r;                           \
          (((unsigned int)(l)  & 0x0FF)      << 24L) | \
          (((unsigned int)(f)  & 0xFFF)      << 12L) | \
          (((unsigned int)(_r) & 0x40000000) >> 19L) | \
          (((unsigned int)(_r) & 0x7FF)            );   \
 })
 
 # define ERR_GET_REASON(r)              \
 ({                   \
          unsigned int _r = r;                    \
          (((unsigned int)(_r) & 0x800) << 19L) | \
          (((unsigned int)(_r) & 0x7FF)       );  \
 })
```

This then breaks compiling crypto/asn1/asn1_err.c with:
```
In file included from ../crypto/asn1/asn1_err.c:11:
../include/openssl/err.h:175:2: error: braced-group within expression allowed only inside a function
  175 |  ({                                                      \
      |  ^
../crypto/asn1/asn1_err.c:17:6: note: in expansion of macro 'ERR_PACK'
   17 |     {ERR_PACK(ERR_LIB_ASN1, 0, ASN1_R_ADDING_OBJECT), "adding object"},
      |      ^~~~~~~~
```

However, if we ignore that part for a moment I think that int_err_get_item() and build_SYS_str_reasons() expect the plain number and the lookup has also to match this. I tried to add the offset to the but the test now returns NULL instead. I think I don't understand how the error-string magic.

**Comment by richsalz** [comment] 2020-06-26 18:19
Ignore the ```f``` in 3.0  I am working on a PR to document this stuff, and do some cleanup.

**Comment by richsalz** [comment] 2020-06-26 19:41
@sebastianas can you look at #12289 ?

**Comment by sebastianas** [comment] 2020-06-26 20:45
On 2020-06-26 12:41:59 [-0700], Rich Salz wrote:
> @sebastianas can you look at #12289 ?

I applied that commit on top of alpha3 and the testsuite passed on
Debian-hurd.

I peaked a little at ERR_PACK() and it only looks at 0xFFF so I don't
fully understand why it works but appears to do so…

Sebastian

**Comment by richsalz** [comment] 2020-06-26 21:56
It skips the test if EPERM is too big. :)

**Comment by sebastianas** [comment] 2020-06-28 14:35
On 2020-06-26 14:57:03 [-0700], Rich Salz wrote:
> It skips the test if EPERM is too big. :)
Ah :)

Are those large errno numbers somehow a limitation for the platform? I
mean error codes like EAGAIN, EBUSY, ESHUTDOWN are returned and special
handling is required. If they are truncated then application can not act
on them. Or do I miss something?

Sebastian

**Comment by richsalz** [comment] 2020-06-28 16:55
OpenSSL assumes that errno fits in 0x3FF bits when reporting errno.  I don't think anyone else has seen this problem on other platforms, which probably makes it low-priority to fix.

**Comment by levitte** [comment] 2020-06-29 12:53
Would you mind having a look at #12314?

**Comment by sebastianas** [comment] 2020-06-29 20:14
On 2020-06-29 05:54:09 [-0700], Richard Levitte wrote:
> Would you mind having a look at #12314? 

Applied the three patches from that pull request and run hurd:

|04-test_err.t .. 
|# The results of this test will end up in test-runs/test_err
|1..1
|    # Subtest: ../../test/errtest
|    1..4
|    ok 1 - preserves_system_error
|    ok 2 - vdata_appends
|    # ERROR: (int) 'ERR_GET_REASON(e) == ERR_R_INTERNAL_ERROR' failed @ ../test/errtest.c:114
|    # [68] compared to [1048644]
|    not ok 3 - raised_error
|    # ERROR: (string) 'expected == p' failed @ ../test/errtest.c:58
|    # --- expected
|    # +++ p
|    #    0:- ':error::system library:test_print_error_format:Operation not per'
|    #    0:+ ':error::system library:test_print_error_format:<NULL>:errtest.c:'
|    #                                                        ^^^^^^^^^^^^^^^^^
|    #   64:- 'mitted:errtest.c:30:'
|    #   64:+ '30:.'
|    #         ^^^^
|    # 
|    not ok 4 - test_print_error_format
|../../util/wrap.pl ../../test/errtest => 1
|not ok 1 - running errtest

Sebastian

**Comment by levitte** [comment] 2020-06-29 20:28
Thank you.

"not ok 3" shows that the test misuses `ERR_LIB_SYS` in that test.  The following patch should fix it, would you mind testing?

``` diff
diff --git a/test/errtest.c b/test/errtest.c
index b7523a31a8..8f9bab7be1 100644
--- a/test/errtest.c
+++ b/test/errtest.c
@@ -108,7 +108,7 @@ static int raised_error(void)
     file = __FILE__;
     line = __LINE__ + 2; /* The error is generated on the ERR_raise_data line */
 #endif
-    ERR_raise_data(ERR_LIB_SYS, ERR_R_INTERNAL_ERROR,
+    ERR_raise_data(ERR_LIB_ERR, ERR_R_INTERNAL_ERROR,
                    "calling exit()");
     if (!TEST_ulong_ne(e = ERR_get_error_all(&f, &l, NULL, &data, NULL), 0)
             || !TEST_int_eq(ERR_GET_REASON(e), ERR_R_INTERNAL_ERROR)
```

"not ok 4" is a little more surprising...  I'll spend some time trying to figure that out.  I assume something's not quite right in 'build_SYS_str_reasons`

**Comment by levitte** [comment] 2020-06-29 20:32
I just tested myself, that wasn't quite enough

**Comment by levitte** [comment] 2020-06-29 20:35
I pushed two fixup commits to #12314, please try them on

**Comment by sebastianas** [comment] 2020-06-29 21:18
On 2020-06-29 13:36:04 [-0700], Richard Levitte wrote:
> I pushed two fixup commits to #12314, please try them on

->

|04-test_err.t .. 
|# The results of this test will end up in test-runs/test_err
|1..1
|    # Subtest: ../../test/errtest
|    1..4
|    ok 1 - preserves_system_error
|    ok 2 - vdata_appends
|    ok 3 - raised_error
|    # ERROR: (string) 'expected == p' failed @ ../test/errtest.c:58
|    # --- expected
|    # +++ p
|    #    0:- ':error::system library:test_print_error_format:Operation not per'
|    #    0:+ ':error::system library:test_print_error_format:<NULL>:errtest.c:'
|    #                                                        ^^^^^^^^^^^^^^^^^
|    #   64:- 'mitted:errtest.c:30:'
|    #   64:+ '30:.'
|    #         ^^^^
|    # 
|    not ok 4 - test_print_error_format
|../../util/wrap.pl ../../test/errtest => 1
|not ok 1 - running errtest

Sebastian

**Comment by levitte** [comment] 2020-06-29 21:50
I wonder why we get a `<NULL>`...  @sebastianas, can you help us debug?  I suspect `openssl_strerror_r` (defined in `crypto/o_str.c`) may give `build_SYS_str_reasons` incorrect results...

**Comment by levitte** [comment] 2020-06-29 21:52
Oh!  I may have found it!

**Comment by levitte** [comment] 2020-06-29 21:53
I just pushed another fixup commit.

**Closed** 2020-07-05 19:17 UTC
Labels: triaged: bug
