### ISSUE TITLE
3.0.0-alpha14 - "unknown type name 'uint128_t'"

### ISSUE THREAD

**Issue by sfackler** [openssl/openssl#14863] opened 2021-04-13 23:53 UTC
When creating a 32 bit x86 build of the new 3.0.0-alpha14, I am seeing a compilation failure in the new curve_448/arch_64 code: https://github.com/sfackler/rust-openssl/pull/1264/checks?check_run_id=2338389758. Specifically,

```
crypto/ec/curve448/arch_64/f_impl.c:71:5: error: unknown type name 'uint128_t'; did you mean 'uint32_t'?
   71 |     uint128_t accum0 = 0, accum4 = 0;
      |     ^~~~~~~~~
      |     uint32_t
```

OpenSSL `#define`s uint128_t to be `__uint128_t` in a header, so this minimal test reproduces the issue:

```
$ cat test.c
#include <stddef.h>

int main() {
        __uint128_t x = 0;
}
$ gcc test.c
$ gcc -m32 test.c
test.c: In function ‘main’:
test.c:4:2: error: unknown type name ‘__uint128_t’; did you mean ‘__int128__’?
    4 |  __uint128_t x = 0;
      |  ^~~~~~~~~~~
      |  __int128__
```

**Comment by sfackler** [comment] 2021-04-14 00:00
Oh, the issue may be that I'm just passing `-m32` as an extra argument to `Configure`, but the check for 128 bit integer support in the script only uses the value of CROSS_COMPILE + CC. Is that a problem on my end or should the script change to add extra flags to the check? https://github.com/openssl/openssl/commit/a72da9ecebcd8e9b9caf6a3d05251a7008e9c614

**Comment by mattcaswell** [comment] 2021-04-14 08:57
This is a dupe of #14804. Closing this in favour of that one.

**Closed by mattcaswell** 2021-04-14 08:57 UTC
Labels: issue: bug report
