### ISSUE TITLE
1 Test fails: test\recipes\80-test_ssl_new.t (Test 12 Failed) in 1.1.1o

### ISSUE THREAD

**Issue by AachoLoya** [openssl/openssl#18476] opened 2022-06-05 08:46 UTC
Downloaded OpenSSL 1.1.1o from openssl.org and build myself. Followed the same procedure that I've followed with previous builds and all tests always pass. This time, 1 test failed, curious if its a build issue, a bug or I need to update some config parameter?

**Enabled features:**

    ```
    aria
    asm
    async
    autoalginit
    autoerrinit
    autoload-config
    bf
    blake2
    camellia
    capieng
    cast
    chacha
    cmac
    cms
    ct
    deprecated
    des
    dgram
    dh
    dsa
    dso
    dtls
    ec
    ec2m
    ecdh
    ecdsa
    engine
    err
    filenames
    gost
    hw(-.+)?
    makedepend
    md4
    mdc2
    multiblock
    nextprotoneg
    pinshared
    ocb
    ocsp
    pic
    poly1305
    posix-io
    psk
    rc2
    rc4
    rdrand
    rfc3779
    rmd160
    scrypt
    seed
    siphash
    sm2
    sm3
    sm4
    sock
    srp
    srtp
    sse2
    ssl
    static-engine
    stdio
    tests
    threads
    tls
    ts
    ui-console
    whirlpool
    tls1
    tls1-method
    tls1_1
    tls1_1-method
    tls1_2
    tls1_2-method
    tls1_3
    dtls1
    dtls1-method
    dtls1_2
    dtls1_2-method
    ```

**Test Output**

    ```
    test\recipes\80-test_ssl_new.t .................. Dubious, test returned 1 (wstat 256, 0x100)
    Failed 1/29 subtests


    Test Summary Report
    -------------------
    test\recipes\80-test_ssl_new.t                (Wstat: 256 Tests: 29 Failed: 1)
    Failed test:  12
    Non-zero exit status: 1
    Files=158, Tests=2329, 230 wallclock secs ( 0.92 usr +  0.23 sys =  1.16 CPU)
    Result: FAIL
    NMAKE : fatal error U1077: 'C:\Perl64\bin\perl.exe' : return code '0x1'
    Stop.
    NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual 
    Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\bin\HostX86\x86\nmake.exe"' : return code '0x2'
    Stop.
    ```

**Comment by t8m** [comment] 2022-06-06 08:13
Closed as duplicate of #18456

**Closed by t8m** 2022-06-06 08:13 UTC
Labels: issue: question
