### ISSUE TITLE
Openssl 1.1.0i fails a test in debug

### ISSUE THREAD

**Issue by Justin-Bieber** [openssl/openssl#7008] opened 2018-08-18 18:32 UTC
**Specs:**
OS: Win7 x64
Compiler: VS2015 Update 3
OpenSSL: 1.1.0i

**Problem:**
`nmake test` fails on openssl-**1.1.0i** for one of the tests under debug configuration:

`perl Configure debug-VC-WIN64A no-shared --debug --prefix="C:\My libs\OpenSSL\1.1.0i\Debug64"`

![nmake test - error](https://user-images.githubusercontent.com/23444447/44302224-e5ce2a80-a313-11e8-9c71-694b4b57b9b4.png)

Everything passes fine under release configuration.

**Comment by mspncp** [comment] 2018-08-19 08:28
I searched a little and found issue #6953.

**Comment by mspncp** [comment] 2018-08-19 08:29
cc @mattcaswell

**Comment by Justin-Bieber** [comment] 2018-08-19 17:28
Output of `nmake V=1 TESTS=test_err test`:


```
Microsoft (R) Program Maintenance Utility Version 14.00.24210.0
Copyright (C) Microsoft Corporation.  All rights reserved.

	"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\nmake.exe" depend && "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\nmake.exe" _tests

Microsoft (R) Program Maintenance Utility Version 14.00.24210.0
Copyright (C) Microsoft Corporation.  All rights reserved.


Microsoft (R) Program Maintenance Utility Version 14.00.24210.0
Copyright (C) Microsoft Corporation.  All rights reserved.

	mkdir .\test\test-runs
A subdirectory or file .\test\test-runs already exists.
	set SRCTOP=.
	set BLDTOP=.
	set RESULT_D=.\test\test-runs
	set PERL=C:\Program Files\Perl64\bin\perl.exe
	set OPENSSL_ENGINES=C:\Users\JustinBieber\Desktop\openssl-1.1.0i_DEBUG\engines
	set OPENSSL_DEBUG_MEMORY=on
	"C:\Program Files\Perl64\bin\perl.exe" ".\test\run_tests.pl" test_err
test\recipes\04-test_err.t .. 
1..1
..\errtest.exe: 1 test case
** preserves_system_error failed **
--------
..\errtest.exe: 1 test failed (out of 1)
..\errtest.exe => 1
not ok 1 - running errtest
#   Failed test 'running errtest'
#   at C:\Users\JustinBieber\Desktop\openssl-1.1.0i_DEBUG\util\perl/OpenSSL/Test/Simple.pm line 77.
# Looks like you failed 1 test of 1.
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/1 subtests 

Test Summary Report
-------------------
test\recipes\04-test_err.t (Wstat: 256 Tests: 1 Failed: 1)
  Failed test:  1
  Non-zero exit status: 1
Files=1, Tests=1,  0 wallclock secs ( 0.03 usr +  0.00 sys =  0.03 CPU)
Result: FAIL
NMAKE : fatal error U1077: '"C:\Program Files\Perl64\bin\perl.exe"' : return code '0x1'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\nmake.exe"' : return code '0x2'
Stop.
```

**Comment by mspncp** [comment] 2018-08-19 17:55
Thank you @Justin-Bieber for sending us the test output. Your issue is a duplicate of issue #6953. Please follow that issue, a patch should appear shortly. Closing this one.

**Closed by mspncp** 2018-08-19 17:55 UTC
