### ISSUE TITLE
Incompatibilty symetric cryp with aes-256-cbc between 1.1.1 and 3.0.11

### ISSUE THREAD

**Issue by rohahner** [openssl/openssl#23406] opened 2024-01-28 01:37 UTC
I encrypt a text in OpenSSL 1.1.1n (Debian openssl/oldoldstable,now 1.1.1n-0+deb10u3 amd64) with following commands:
echo "Dies ist ein text um verschlüsselt zu werden" > aaa1.txt
openssl enc -e -aes-256-cbc -pbkdf2 -base64 --pass pass:"Hallo" -salt -S "2A3F456D12688790" -in aaa1.txt -out aaa2.txt
cat aaa2.txt | tr '\n' '#'
# Result encrypt: U2FsdGVkX18qP0VtEmiHkO02ami7wbg+E2dfUs9hVCCgOTu7e5l1fOttLWUl7yvN#xc5rApKZNIOfHDVNaFcG4A==

Then i try to decrypt the string on OpenSSL 3.0.11 (openssl/stable,now 3.0.11-1~deb12u2 amd64) with following commands:
openssl enc -d -aes-256-cbc -pbkdf2 -base64 --pass pass:"Hallo" -salt -S "2A3F456D12688790" -in aaa2.txt -out aaa3.txt
cat aaa3.txt
# Result decrypt: ~}▒e▒[L$SJ=▒▒▒▒_▒=▒7▒m/▒t um verschlüsselt zu werden

If i encrypt the string with OpenSSL 3.0 i get on OpenSSL 1.1.1 following message:
bad magic number

If test a longer text (e.g. 1000Words) only the start is buggy, but the rest of test is OK.

The Encryption Parameters for both versions are the same:
#----------
#OpenSSL 1.1.1n  15 Mar 2022
#bufsize=8192
#salt=2A3F456D12688790
#key=2908E50339EFA4FF1CB36E314A6F4BF996DA54B60D938EACB57161F1367FBDD2
#iv =AD15EBAC50DCDD748E67C834EB71CD60
#bytes read   :       46
#bytes written:       90
#----------
#OpenSSL 3.0.11 19 Sep 2023 (Library: OpenSSL 3.0.11 19 Sep 2023)
#bufsize=8192
#salt=2A3F456D12688790
#key=2908E50339EFA4FF1CB36E314A6F4BF996DA54B60D938EACB57161F1367FBDD2
#iv =AD15EBAC50DCDD748E67C834EB71CD60
#bytes read   :       46
#bytes written:       65

I hope this a bug and not a feature

**Comment by t8m** [comment] 2024-01-29 15:23
Duplicate of #22057

**Closed by t8m** 2024-01-29 15:23 UTC
Labels: issue: bug report
