### ISSUE TITLE
SSL_CTX_new/SSL_new/SSL_connect memory leaks

### ISSUE THREAD

**Issue by qhdhuowen** [openssl/openssl#23359] opened 2024-01-22 13:53 UTC
[openssl.txt](https://github.com/openssl/openssl/files/14010916/openssl.txt)

Like the content in the OpenSSL. txt file, I use openssl to implement tls communication client program, and my client program cannot exit, need to constantly initiate and disconnect links, openssl version is: OpenSSL 1.1.1k FIPS 25 Mar 2021, however, whether I use thread calls, or use process program calls, I find that the memory information occupied by the program is increasing, there are two detection methods, respectively, mtrace to view the stack information, and use pidstat to view the amount of memory occupied by the program.

**Comment by t8m** [comment] 2024-01-22 14:46
Duplicate of #23358

**Closed by t8m** 2024-01-22 14:46 UTC
Labels: issue: question
