### ISSUE TITLE
hangs trying to create .csr

### ISSUE THREAD

**Issue by stan-spotts** [openssl/openssl#23148] opened 2023-12-25 05:36 UTC
I'm trying to create a root CA certificate and created the encrypted key with this:

`openssl ecparam -out myorg.key -name prime256v1 -genkey`

But when I tried to next create a root certificate and self-sign it, it hung after I entered my organizational unit (OU) name. The line was this:

`openssl.exe req -new -sha256 -key myorg.key -out myorg.csr`

After I hit [enter on this, I got the following and you can see the responses. After the OU one, it just sat.

```
You are about to be asked to enter information that will be incorporated
into your certificate request.
What you are about to enter is what is called a Distinguished Name or a DN.
There are quite a few fields but you can leave some blank
For some fields there will be a default value,
If you enter '.', the field will be left blank.
-----
Country Name (2 letter code) [AU]:**US**
State or Province Name (full name) [Some-State]:**Pennsylvania**
Locality Name (eg, city) []:**Philadelphia**
Organization Name (eg, company) [Internet Widgits Pty Ltd]:**My Company**
```
This is on Windows 10, OpenSSL 3.2.0 23 Nov 2023 (Library: OpenSSL 3.2.0 23 Nov 2023).

**Comment by jamuir** [comment] 2023-12-25 05:49
It is possible that you may have to hit "return" a few times to get the openssl app to respond (this was reported in issue #23145).

Could try that and report the result back here?

**Comment by jamuir** [comment] 2023-12-25 05:58
Also, in the output you posted, I see that user inputs are surrounded by asterisks, e.g. `**US**`.

When I try to do that, I get an error:

```
$ openssl.exe req -new -sha256 -key myorg.key -out myorg.csr
You are about to be asked to enter information that will be incorporated
into your certificate request.
What you are about to enter is what is called a Distinguished Name or a DN.
There are quite a few fields but you can leave some blank
For some fields there will be a default value,
If you enter '.', the field will be left blank.
-----
Country Name (2 letter code) [AU]:**US**
String too long, must be at most 2 bytes long
```

Were are the asterisks coming from?

**Comment by stan-spotts** [comment] 2023-12-26 15:28
Asterisks were for me expecting bold and forgetting I put the info in between code tags :).

**Comment by stan-spotts** [comment] 2023-12-26 15:29
I'll be darned - I hit [Enter] three more times after the org name and the Org Unit prompt appeared!

**Comment by jamuir** [comment] 2023-12-26 17:23
We are not sure why `openssl req` is waiting for multiple presses of "return".

If I could reproduce the behaviour, then I could debug it, but, unfortunately, I have not been able to do so.

Could you post the output of `perl configdata.pm --dump` here?

**Comment by t8m** [comment] 2023-12-27 09:31
Duplicate of #23145

**Closed by t8m** 2023-12-27 09:31 UTC
Labels: issue: bug report

**Comment by jamuir** [comment] 2023-12-27 17:42
Even though Tomas has closed this, it would still be helpful to have the output of `perl configdata.pm --dump` since we could then compare it to what is provided in the other ticket.

**Comment by jamuir** [comment] 2024-01-10 20:11
@stan-spotts:  would you be able to post the output of `perl configdata.pm --dump` to help us debug this?

**Comment by stan-spotts** [comment] 2024-01-12 13:04
I would, but perl? Not even on my system.  Is there something else I can send?

**Comment by t8m** [comment] 2024-01-12 13:46
I assume then, you did not build openssl yourself. Where did you get the binaries?

**Comment by stan-spotts** [comment] 2024-01-12 14:06
Got it from here: https://slproweb.com/download/Win64OpenSSL-3_2_0.msi

was going to use the version that came with git, but after upgrading git that was version 3.1.4. I wanted to try 3.2.0, so installed this. Chocolaty would only install version 3.1.1 I think.
