### ISSUE TITLE
build of branch OpenSSL_1_1_1-stable is broken

### ISSUE THREAD

**Issue by CedricCouton** [openssl/openssl#11497] opened 2020-04-08 13:20 UTC
Hello,

From this morning If i use : /Configure darwin64-x86_64-cc and make I have some errors like : 

crypto/rand/drbg_ctr.c:25:5: error: use of undeclared identifier 'u32'
    u32 n = 16, c = 1;
    ^
cc  -I. -Iinclude -fPIC -arch x86_64 -O3 -Wall -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DAESNI_ASM -DVPAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/usr/local/ssl\"" -DENGINESDIR="\"/usr/local/lib/engines-1.1\"" -D_REENTRANT -DNDEBUG  -MMD -MF crypto/rc2/rc2_skey.d.tmp -MT crypto/rc2/rc2_skey.o -c -o crypto/rc2/rc2_skey.o crypto/rc2/rc2_skey.c
crypto/rand/drbg_ctr.c:28:11: error: use of undeclared identifier 'n'
        --n;
          ^
crypto/rand/drbg_ctr.c:29:9: error: use of undeclared identifier 'c'
        c += p[n];
        ^
cc  -I. -Iinclude -fPIC -arch x86_64 -O3 -Wall -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DAESNI_ASM -DVPAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/usr/local/ssl\"" -DENGINESDIR="\"/usr/local/lib/engines-1.1\"" -D_REENTRANT -DNDEBUG  -MMD -MF crypto/rc2/rc2cfb64.d.tmp -MT crypto/rc2/rc2cfb64.o -c -o crypto/rc2/rc2cfb64.o crypto/rc2/rc2cfb64.c
crypto/rand/drbg_ctr.c:29:16: error: use of undeclared identifier 'n'
        c += p[n];
               ^
crypto/rand/drbg_ctr.c:30:17: error: use of undeclared identifier 'u8'
        p[n] = (u8)c;
                ^
crypto/rand/drbg_ctr.c:30:11: error: use of undeclared identifier 'n'
        p[n] = (u8)c;
          ^
crypto/rand/drbg_ctr.c:31:9: error: use of undeclared identifier 'c'
        c >>= 8;
        ^
crypto/rand/drbg_ctr.c:32:14: error: use of undeclared identifier 'n'
    } while (n);

**Comment by mattcaswell** [comment] 2020-04-08 13:56
Dupe of #11487

**Closed by mattcaswell** 2020-04-08 13:56 UTC
Labels: issue: bug report
