### ISSUE TITLE
Illegal instruction with 'fips_hmactest' on ppc32

### ISSUE THREAD

**Issue by hliebel** [openssl/openssl#3351] opened 2017-05-01 07:12 UTC
Hi.

We've seen an issue with running FIPS v2.0.14 on an older PPC32. The break seems to have come in when moving from FIPS v2.0.12 to v2.0.13.

Running the tests on our controller I get the following:
```
# ./fips_test_suite
        FIPS-mode test application
        FIPS 2.0.14 validated module 15 Nov 2016

                DRBG AES-256-CTR DF test started
                DRBG AES-256-CTR DF test OK
1. Non-Approved cryptographic operation test...
        a. Included algorithm (D-H)......successful
        POST started
                Integrity  test started
                Integrity  test OK
                DRBG AES-256-CTR DF test started
                DRBG AES-256-CTR DF test OK
                DRBG AES-256-CTR test started
                DRBG AES-256-CTR test OK
                DRBG SHA256 test started
                DRBG SHA256 test OK
                DRBG HMAC-SHA256 test started
                DRBG HMAC-SHA256 test OK
                X9.31 PRNG keylen=16 test started
                X9.31 PRNG keylen=16 test OK
                X9.31 PRNG keylen=24 test started
                X9.31 PRNG keylen=24 test OK
                X9.31 PRNG keylen=32 test started
                X9.31 PRNG keylen=32 test OK
                Digest SHA1 test started
                Digest SHA1 test OK
                Digest SHA1 test started
                Digest SHA1 test OK
                Digest SHA1 test started
                Digest SHA1 test OK
                HMAC SHA1 test started
                HMAC SHA1 test OK
                HMAC SHA224 test started
                HMAC SHA224 test OK
                HMAC SHA256 test started
                HMAC SHA256 test OK
                HMAC SHA384 test started
Illegal instruction
# 
# ./fips_hmactest
Illegal instruction
```

When I try to use GDB to find the spot where it breaks it points to somewhere around OPENSSL_ppc64_probe().

If I build the FIPS container with the '-no-asm' flag it seems to work ok.

Build flags we use:
```
# Clean with the current settings first to remove unused files.
echo "** Cleaning FIPS - Errors can be ignored"
rm -rf build/
make clean

echo "** Configuring FIPS"
export MACHINE=ppc
export ARCH=ppc
export SYSTEM=linux-ppc
export CROSS_COMPILE=powerpc-linux-
export HOSTCC=gcc
export FIPSDIR="$PWD/build"
export FIPS_SIG="$FIPSDIR/../util/incore"
export RELEASE=2.6.18

/usr/bin/perl Configure linux-ppc -Wa,--noexecstack fips shared no-bf no-camellia no-cast no-idea no-md2 no-md5 no-mdc2 no-rc2 no-rc4 no-rc5 no-ripemd no-seed


echo "** Building FIPS"
make -j2
make install
make -j2 build_tests
```

System information:
```
# uname -a
Linux eclipse-207 2.6.18 #414 PREEMPT Wed Feb 22 01:32:36 AEDT 2017 ppc unknown
# 
# cat /proc/cpuinfo 
processor       : 0
cpu             : G2_LE
revision        : 1.4 (pvr 8082 2014)
bogomips        : 174.59
chipset         : 8272
vendor          : Motorola
machine         : PQ2 ADS PowerPC

mem size                : 0x04000000
console baud            : 115200

core clock      : 264 MHz
CPM  clock      : 132 MHz
bus  clock      : 66 MHz
```

Thanks,
Harry

**Comment by dot-asm** [comment] 2017-05-01 14:28
First of all, you shouldn't see OPENSSL_ppc64_probe when debugging fips_test_suite, it's called fips_openssl_ppc64_probe. In other words question is if you really see OPENSSL_ppc64_probe? Secondly, illegal instruction exceptions caused by probe functions are *managed*. This means that they do show in debugger, but remain transparent otherwise. See https://www.openssl.org/docs/faq.html#PROG17 for details. [In the context you should probably keep in mind that FIPS module doesn't necessarily plays along with debugger. Specifically if you set breakpoints. This is because setting breakpoint is customarily implemented by modifying code, and FIPS module can detect it and will fail to initialize].

Anyway! The real problem is that 2.0.14 was apparently rendered unsuitable for PPC32. This is because a number of POWER8 modules were backported and engaged in 64- *and* 32-bit builds, *but* I failed to recognize that generic sha512-ppc module is so old that it doesn't have dedicated PPC32 SHA512 implementation. As result code with 64-bit instructions was emitted and compiled (and never executed on POWER8). And this is where your programs crash, not in either of the probe functions. One can argue that you should have failed to compile it, but that would be question to your compiler vendor. Bottom line is "just stick with 2.0.13".

**Comment by hliebel** [comment] 2017-05-02 04:06
Hi.

Yes, 'fips_openssl_ppc64_probe' is what I saw. I copied the wrong thing. Thanks for the extra info. I was only trying to use the debugger to try and find the bad instruction.

We are using an older GCC (4.1.1) to compile our stuff in Buildroot. It should be pretty vanilla, but I guess the tools might be showing their age.

Does that mean we are going to be stuck on an older version of FIPS forever or is this something that will be fixed in a new releases?

Thanks,
Harry

**Comment by dot-asm** [comment] 2017-05-02 13:42
> tools might be showing their age.

I meant that assembler could have failed/refused to assemble 64-bit instructions when asked to generate 32-bit object module. And *older* assembler probably would, but yours is new enough. In other words what I'm saying is kind of opposite, i.e. that your tools are not *old* enough :-) Well, formally speaking new tool could do that too, after all assembler "knows" that it's generating 32-bit code.

> is this something that will be fixed in a new releases?

"will" is wrong in the context, because its development is not driven by our will, it takes somebody to sponsor changes. But there hardly is any downside in sticking to specific version, because newer versions *add* new platform support, there normally are no changes to shared code. Closing...

**Closed by dot-asm** 2017-05-02 13:42 UTC
