### ISSUE TITLE
tests/hazmat/primitives/test_aead.py fails with segfault

### ISSUE THREAD

**Issue by kroeckx** [openssl/openssl#10400] opened 2019-11-10 07:48 UTC
A log like https://travis-ci.org/openssl/openssl/jobs/609797102?utm_medium=notification&utm_source=github_status shows:
```
tests/hazmat/primitives/test_aead.py s.................................. [  2%]
..............................................s......................... [  2%]
[...]
...................................................................Segmentation fault (core dumped)
/home/travis/build/openssl/openssl/util/shlib_wrap.sh sh /home/travis/build/openssl/openssl/test/recipes/95-test_external_pyca_data/cryptography.sh => 139
not ok 1 - running Python Cryptography tests
```

**Comment by mattcaswell** [comment] 2021-04-21 08:15
This is a duplicate of #14425

**Closed by mattcaswell** 2021-04-21 08:15 UTC
Labels: branch: master, tmp: HIGH, triaged: OTC evaluated, triaged: bug
