### ISSUE TITLE
Incorrect response for RSA Signature Generation 9.31

### ISSUE THREAD

**Issue by amrithathorath** [openssl/openssl#10869] opened 2020-01-16 16:41 UTC
I'm trying to generate RSA 9.31 signature using OpenSSL 1.1.1. I see a mismatch in the signature generated in some instances when compared against results generated with OpenSSL 1.0.2*. 3-4 out of 10 instances fail to match results when compared to OpenSSL 1.0.2*, remaining of the instances match.

Here is my code and output for OpenSSL 1.1.1d

```
memcpy(tmpdinfo, hash, md_len);    // hash is the hash of message passed in
tmpdinfo[md_len] = RSA_X931_hash_id(NID_sha1);
RSA_private_encrypt((md_len + 1), tmpdinfo, signature, rsa, RSA_X931_PADDING);

```
Test input and output:

```
[mod = 2048]

n = bff722714050aebb23a9bd018c3e9ba26a47f53816eeac7e10543958702d9265c8d67784fe03c07bfceac05e7f2a434971dfa2a5ea461893450ced52fcb3f143a85fb3a9194417ff220258840a3359a104079ccd201afec091bab6587d4cfe0b95bba34ef74a70b392a92a93f026c9bed41eb4ec80452492a2ad524e6b0333c5787b34ee941829020bb75ee5dd216b3734823ddd547d50f8a7e711f8a24fd7dbc0bd2f062ccaba98cdbf62c15d2521b39ce44c53125604493e482ae35f945c4efff1d01414b0aad33de77b020ea4aedf3d88171fe51b22881bc70c639f8b6f1b5a70ed39aa121a8f44887dcbbfce29e1e508d1b0f0666693b476d81faa6a18bd

e = 00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010001

SHAAlg = SHA1
Msg = b9ff7c8599c14f08669e2c531def1b2025cce1f18475d39953f0e9ff6ff4131f7206d051e2e2fccea81ce970c307b2b93dd6cc175e01de6621ebd3b7e4c12d5063a59cf4e70ccf64bb648a25e0fbf984011c44d8a97b6307b4d2344b04cdca36752408f412066fd189be35fadc9197885ae570bacea90982f6f0334436df93da
S = 3dc6cfb9984d233f47f1631d02a5862b7614be63edbeaf7c36730d511bd145f907b03aedcc2ef3bf376c4955893ea8f5b887a10e6204e243c85cb1e4ef3ea8206a0864eb3f9ee2f4f8cb3b5696640efce67298e50165bf8e57bbbaaec86e5d069dbaebf5b18ca9b2bb98dc61af562a2f262216fa1cf94ea478a48f62c75f0484cb45e32af7a388bada471837d8aaa2ea9e2fad8a6b5aaa0068420085b125d468dc2e1a62f140ba344015a47157778eb98a6450dc219539aeb07e7378ab57fb6e630adf91b45399a84069186a2c61f226d233a40a41066ada1ac8c04dd58a3edb7397945f975ed87a2e535b279898c04d9fb46722c8bdf47f588227b84bd92ffb   // output
```

With OpenSSL 1.0.2 (integrated with fipscanister), the code and output are shown below:

`
FIPS_rsa_sign(rsa, message, 128, EVP_sha1(), RSA_X931_PADDING, 0, NULL, signature, &siglen);
`

Test input and output:

```
[mod = 2048]

n = bff722714050aebb23a9bd018c3e9ba26a47f53816eeac7e10543958702d9265c8d67784fe03c07bfceac05e7f2a434971dfa2a5ea461893450ced52fcb3f143a85fb3a9194417ff220258840a3359a104079ccd201afec091bab6587d4cfe0b95bba34ef74a70b392a92a93f026c9bed41eb4ec80452492a2ad524e6b0333c5787b34ee941829020bb75ee5dd216b3734823ddd547d50f8a7e711f8a24fd7dbc0bd2f062ccaba98cdbf62c15d2521b39ce44c53125604493e482ae35f945c4efff1d01414b0aad33de77b020ea4aedf3d88171fe51b22881bc70c639f8b6f1b5a70ed39aa121a8f44887dcbbfce29e1e508d1b0f0666693b476d81faa6a18bd

e = 00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010001

SHAAlg = SHA1
Msg = b9ff7c8599c14f08669e2c531def1b2025cce1f18475d39953f0e9ff6ff4131f7206d051e2e2fccea81ce970c307b2b93dd6cc175e01de6621ebd3b7e4c12d5063a59cf4e70ccf64bb648a25e0fbf984011c44d8a97b6307b4d2344b04cdca36752408f412066fd189be35fadc9197885ae570bacea90982f6f0334436df93da
S = 823052b7a8038b7bdbb859e489991576f43336d4292ffd01d9e12c07545c4c6cc1263c9731d4ccbcc57e7708f5eb9a53b95801978841364f7cb03b6e0d7549233e574ebdd9a5350a29371d2d73cf4aa41d9503e81eb53f3239fefba9b4dea104f800b75945bdc700d7104e3240d09f8fadfc9df2634bd5ee2a08c2eba3a42f40ad3551c39c74a047317046ae0476c84c96529052e922a6f83fa51172f12a0372e48f14a33b8a00648da9be5005ad92fa127ffb76f0c0ca9a8dc9b76ab43c60e09ce6f082605d112afd7e6297e242bcb86b547315a414b7ae00fe4c15ca01303fe6d958da12b34215163522a42735699445546a8e27a872145bf4b0675e90e8c2

```
Thanks in advance.

**Comment by bernd-edlinger** [comment] 2020-01-23 18:38
OpenSSL 1.0.2 gives the wrong result.
The intention is to return min(S,n-S), but that is apparently broken in 1.0.2
the second signaure value is exactly n-S. but BN_cmp did apparently return the wrong result
here:
https://github.com/openssl/openssl/blob/12ad22dd16ffe47f8cde3cddb84a160e8cdb3e30/crypto/rsa/rsa_eay.c#L449-L452

**Comment by bernd-edlinger** [comment] 2020-01-23 19:11
@romen regarding BN_cmp, I think this does not work for FIXED_TOP bignums,
since bn_check_top does make an exception for them, but this does only work for
normalized BNs:
https://github.com/openssl/openssl/blob/cf0843c09101fa7a1718c4423543358b7fe1876a/crypto/bn/bn_lib.c#L652-L655

**Comment by amrithathorath** [comment] 2020-01-23 19:19
@bernd-edlinger : Thanks for the response.
In my comment above, the first set of results is using OpenSSL-1.1.1 (which I think i incorrect) and second set is OpenSSL-1.0.2. You said second set looks correct which is OpenSSL-1.0.2.

Also the results using OpenSSL-1.0.2 passed CAVP testing.

**Comment by bernd-edlinger** [comment] 2020-01-23 19:38
The first signature looks correct, since the S is smaller than the second one.

**Comment by amrithathorath** [comment] 2020-01-23 19:41
I'm just baffled how the wrong results would pass CAVP testing!

**Comment by bernd-edlinger** [comment] 2020-01-23 19:50
Ah, well, maybe I misread the code above.
Could be that it actually intended return max(S,n-S).

**Comment by amrithathorath** [comment] 2020-01-23 20:08
In that case, the first signature "3dc6cfb9984d233f...." (generated by OpenSSL-1.1.1) is smaller than "823052b7a803..." (generated by OpenSSL-1.0.2). So may be the bug is in new OpenSSL?

**Comment by bernd-edlinger** [comment] 2020-01-24 07:04
I really can't tell, as far as I see both openssl 1.0.2 and 1.1.1 behave identical,
both compute S and N-S and then return the **smaller** of the two.
The potential issue with BN_cmp does not affect this, since neither of these numbers
do have the FIXED_TOP bit set.

It it however possible that ANSI X.931 requires something different here, but I do not
have access to that spec.

**Comment by bernd-edlinger** [comment] 2020-01-24 08:01
which version of openssl 1.0.2 did you test with,
could it be based on the branch OpenSSL-fips-2_0-stable ?
In other words, does your rsa_eay.c look like this,
https://github.com/openssl/openssl/blob/d11e6a4410d5aae70ad545d085d344644c33d9cc/crypto/rsa/rsa_eay.c#L494-L500
which does `if (BN_cmp(ret, f))` instead of `if (BN_cmp(ret, f) > 0)`
that would match the value that you reported, since it always uses N-S ?

**Comment by amrithathorath** [comment] 2020-01-24 14:31
I'm using OpenSSL-1.0.2p with OpenSSL-fips-2.0.16.
This is what I see:
```
if (padding == RSA_X931_PADDING) {
        BN_sub(f, rsa->n, ret);
        if (BN_cmp(ret, f) > 0)
            res = f;
        else
            res = ret;
    } 
```

**Comment by bernd-edlinger** [comment] 2020-01-24 16:49
I don't understand what you are doing,
if I do `git checkout OpenSSL-fips-2_0_16` I see:
```
        if (padding == RSA_X931_PADDING)
                {
                BN_sub(f, rsa->n, ret);
                if (BN_cmp(ret, f))
                        res = f;
                else
                        res = ret;
                }
```
So if you use the fips version it is obviously wrong.
but if I do `git checkout OpenSSL_1_0_2p` I see
```
    if (padding == RSA_X931_PADDING) {
        BN_sub(f, rsa->n, ret);
        if (BN_cmp(ret, f) > 0)
            res = f;
        else
            res = ret;
```
But what exactly do you mean with
> I'm using OpenSSL-1.0.2p with OpenSSL-fips-2.0.16.

**Comment by mattcaswell** [comment] 2020-01-24 17:00
> But what exactly do you mean with
>> I'm using OpenSSL-1.0.2p with OpenSSL-fips-2.0.16.

The FIPS 2 Object Module works in conjuction with a FIPS capable version of OpenSSL. You need *both* in order for it to work. I assume that is what @amrithathorath is referring to.

If the problem is in OpenSSL-fips-2.0.16 then that is out of support and won't be fixed.

**Comment by amrithathorath** [comment] 2020-01-24 18:12
@bernd-edlinger : I'm meant exactly what @mattcaswell mentioned above.
@mattcaswell : The issue is I'm not sure if the bug is in 1.1.1 or the 1.0.2 code.

**Comment by bernd-edlinger** [comment] 2020-01-24 20:27
So since you explicitly call FIPS_rsa_sign you not use the RSA code from OpenSSL 1.0.2p
however if you use this command line
`$ apps/openssl rsautl -in /dev/null -inkey apps/privkey.pem -passin pass:1234 -sign -x931 -hexdump`

You will see always a signature less than N/2, which may or may not be correct
according to ANSI X.931, but as far as I can tell, ANSI standards do cost $$$,
so I just don't know what is written there, it could as well demand greater than N/2.

However the code from the FIPS module can't be correct, since the the BN_cmp
compares S, against N-S, and since N is odd, the if condition BN_cmp(ret,f)
is always nonzero, and the else path is impossible to reach, so it is pointless
to write such a complicated condition that is always fulfilled.

**Comment by lisarabe** [comment] 2020-01-28 15:34
I have had the same issue.  When I test RSA 9.31 (1.1.1) with CAVP vectors, some of the results are correct and some are incorrect.  These tests worked on 1.0.2 with the FIPS Object Module but don't work correctly on 1.1.1.

**Closed** 2020-01-29 14:30 UTC
