### ISSUE TITLE
OpenSSL(1.1.1g) is getting crashed on MAC

### ISSUE THREAD

**Issue by AshishDurgapal** [openssl/openssl#13066] opened 2020-10-03 09:49 UTC
Issue in OpenSSL version : 1.1.1g

We are getting crash(segmentation fault) in OpenSSL in method **openssl_strerror_r**  when we received Unknown error (error code 107) on MAC while it is working fine with Linux .

In our application, we have upgraded the OpenSSL version from 1.1.1b to 1.1.1g and after that whenever we initialized curl (CURL_GLOBAL_INIT) then it gets crashed  in OpenSSL function openssl_strerror_r while OpenSSL version 1.1.1b is working fine because in OpenSSL version 1.1.1b you have used strerror function instead of strerror_r  call in openssl_strerror_r method. 

Flags that we used to compile OpenSSL in MAC is given below.
./configure darwin64-x86_64-cc no-shared no-asm no-capieng no-threads no-rc4 -D_GNU_SOURCE (For 64bit)
Note* : Crash is observed in both the architecture(x86 & x64)

Given below is the code section where crash is observed.

```
221 int openssl_strerror_r(int errnum, char *buf, size_t buflen)
222 {
223 #if defined(_MSC_VER) && _MSC_VER>=1400
224     return !strerror_s(buf, buflen, errnum);
225 #elif defined(_GNU_SOURCE)
226     char *err;
227 
228     /*
229      * GNU strerror_r may not actually set buf.
230      * It can return a pointer to some (immutable) static string in which case
231      * buf is left unused.
232      */
233     err = strerror_r(errnum, buf, buflen);
234     if (err == NULL || buflen == 0)
235         return 0;
236     /*
237      * If err is statically allocated, err != buf and we need to copy the data.
238      * If err points somewhere inside buf, OPENSSL_strlcpy can handle this,
239      * since src and dest are not annotated with __restrict and the function
240      * reads src byte for byte and writes to dest.
241      * If err == buf we do not have to copy anything.
242      */
243     if (err != buf)
244         OPENSSL_strlcpy(buf, err, buflen);
245     return 1;
246 #elif (defined(_POSIX_C_SOURCE) && _POSIX_C_SOURCE >= 200112L) || \
247       (defined(_XOPEN_SOURCE) && _XOPEN_SOURCE >= 600)
248     /*
249      * We can use "real" strerror_r. The OpenSSL version differs in that it
250      * gives 1 on success and 0 on failure for consistency with other OpenSSL
251      * functions. Real strerror_r does it the other way around
252      */
253     return !strerror_r(errnum, buf, buflen);
254 #else
255     char *err;
256 
257     /* Fall back to non-thread safe strerror()...its all we can do */
258     if (buflen < 2)
259         return 0;
260     err = strerror(errnum);
261     /* Can this ever happen? */
262     if (err == NULL)
263         return 0;
264     OPENSSL_strlcpy(buf, err, buflen);
265     return 1;
266 #endif
267 }
```
------------------------------------------------------------------------------------------------------------
when we get unknown error :107 at line 233 , in that case strerror_r returned some trash value which causes the crash while copying NULL value in some buffer at line 244. 
![image](https://user-images.githubusercontent.com/72299058/94988545-ae6e7680-058b-11eb-9460-4ce5d663e65a.png)

As you can see that variable buf contain invalid value.

**Comment by mattcaswell** [comment] 2020-10-05 08:22
Looks like the `strerror_r` implementation differs between Linux and Mac. Here is the documentation for the Linux version:

https://linux.die.net/man/3/strerror_r

Note that if `_GNU_SOURCE` is defined then you get a GNU specific implementation, while if it is not you get the "XSI compliant" version. The Mac documentation on the other hand looks like this:

https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man3/strerror_r.3.html

This just seems to describe the XSI compliant version, and does not have the "GNU" variant.

The detection for this in `openssl_strerror_r`, just checks to see if `_GNU_SOURCE` is defined and, if it is, uses the GNU variant. You have explicitly defined `_GNU_SOURCE` in your configure line and so `openssl_strerror_r` is fooled into expecting a GNU specific `strerror_r` implementation. Unfortunately on MAC the GNU variant doesn't exist and hence we see the crash.

So, the next question is, why do you need to define `_GNU_SOURCE` on your configure line? Does the crash go away if your drop it?

**Comment by AshishDurgapal** [comment] 2020-10-05 11:39
Hi @mattcaswell ,

After excluding flag _GNU_SOURCE, everything is running fine on MAC.

We had included the _GNU_SOURCE as we want to configure the OpenSSL with same flags in different platforms.

**Comment by mattcaswell** [comment] 2020-10-05 12:22
Thanks. In that case it seems to me that this is not a bug in OpenSSL, but a problem in your command line flags. Closing this.

**Closed by mattcaswell** 2020-10-05 12:22 UTC
Labels: triaged: bug
