### ISSUE TITLE
EVP_sha3_256() prehash works with RSA, but not with ECDSA

### ISSUE THREAD

**Issue by rwfranks** [openssl/openssl#8957] opened 2019-05-19 20:25 UTC
Specifying a reference to EVP_sha3_256() as the md prehash argument to

   EVP_DigestSignInit( ctx, NULL, md, NULL, pkey )

appears to work if pkey is an RSA key, fails catastrophically if the same experiment is performed using an ECDSA key.

**Comment by mattcaswell** [comment] 2019-05-20 10:04
Can you be a bit more specific about what you mean by "fails catastrophically"?

**Comment by rwfranks** [comment] 2019-05-20 11:23
Result of running  t/51-ECDSA-P256.t after substituting EVP_sha3_256() in place of EVP_sha256() at lib/Net/DNS/SEC/ECDSA.pm, line 55, with corresponding change in SEC.xs:
 
ok 1 - use Net::DNS::SEC;
ok 2 - use Net::DNS::SEC::Private;
ok 3 - use Net::DNS::SEC::ECDSA;
ok 4 - set up ECDSA public key
ok 5 - set up ECDSA private key
ok 6 - set up non-ECDSA public key
ok 7 - set up non-ECDSA private key
libcrypto error (SEC.xs line 257) at blib/lib/Net/DNS/SEC/ECDSA.pm line 75.
# Looks like you planned 13 tests but ran 7.
# Looks like your test exited with 255 just after 7.
make: *** [Makefile:1088: test_dynamic] Error 255
	libcrypto.so.3 => /home/rwf/devel/openssl-SNAP-20190517/lib64/libcrypto.so.3 (0x00007fc13f352000)

[Net::DNS::SEC 1.13  SEC.xs]
200 int checkret(const int ret, int line)
201 {
202         if ( ret == 1 ) return ret;
203         croak("libcrypto error (%s line %d)", __FILE__, line);
204 }
205
206 #define checkerr(arg)   checkret( (arg), __LINE__ )
...
255        m = (unsigned char*) SvPVX(message);
256        EVP_MD_CTX_reset(ctx);
257        checkerr( EVP_DigestSignInit( ctx, NULL, md, NULL, pkey ) );
258        slen = sizeof(sigbuf);
259        r = EVP_DigestSign( ctx, sigbuf, &slen, m, SvCUR(message) );
260        EVP_MD_CTX_free(ctx);
261        EVP_PKEY_free(pkey);
262        checkerr(r);
263        RETVAL = newSVpvn( (char*)sigbuf, slen );

Analogous test involving t/23-RSA-SHA256.t and lib/Net/DNS/SEC/RSA.pm appears to work as expected (at least, does not crash).

PS: I withdraw the word "catastrophically";  the hard stop comes from croak at line 203

**Comment by mspncp** [comment] 2019-05-20 11:46
_(Note: I only inserted triple backquotes to improve readability of the output. No textual changes.)_

**Comment by rwfranks** [comment] 2019-05-20 13:52
Thanks

**Comment by mattcaswell** [comment] 2019-05-20 16:40
> Result of running t/51-ECDSA-P256.t after substituting EVP_sha3_256() in place of EVP_sha256() at lib/Net/DNS/SEC/ECDSA.pm, line 55, with corresponding change in SEC.xs:

So it seems you are using an external test suite to generate this error, which makes it a bit difficult to reproduce it. However, after a bit of fiddling around with some other OpenSSL internal tests I ran into this error when I tried an EVP_DigestSignInit() operation with this digest type:

```
# 139974244096896:error:100C508A:elliptic curve routines:pkey_ec_ctrl:invalid digest type:crypto/ec/ec_pmeth.c:327:
````
It seems to come from here:
https://github.com/openssl/openssl/blob/538f38db50e4ead178025689d28bda316b15c242/crypto/ec/ec_pmeth.c#L320-L331

As you can see there are no SHA3 variants in that list. A bit more digging turned up this:

https://tools.ietf.org/html/draft-turner-lamps-adding-sha3-to-pkix-01

Which never seemed to make it out of draft stage, although the OIDs do seem to be official NIST ones from here:

https://csrc.nist.gov/projects/computer-security-objects-register/algorithm-registration#DSA

So it appears that SHA3 is ok to use with ECDSA, but my guess is that the ec_pmeth.c code above was never updated with these oids when SHA3 support was integrated.

**Comment by mattcaswell** [comment] 2019-05-20 16:42
The fix seems straight forward enough (just add the relevant sha3 variants into the above list). It would be nice to add some test vectors for this too - but I don't know if there are any.

This is probably a good first issue.

**Comment by rwfranks** [comment] 2019-05-20 17:19
Please let me know when fix goes into daily snapshot.
I already have some test examples to play with.
Thanks

**Comment by rwfranks** [comment] 2019-05-20 17:46
NIST test vectors available at:

https://csrc.nist.gov/CSRC/media/Projects/Cryptographic-Algorithm-Validation-Program/documents/sha3/sha-3bittestvectors.zip

**Comment by richsalz** [comment] 2019-05-20 17:52
Those test vector are for SHA3, not CMS using SHA3, right?

**Comment by rwfranks** [comment] 2019-05-21 01:17
For our present purpose, we are only interested in vectors with (bit) length a multiple of 8 from the ShortMsg and LongMsg files.

**Comment by dlegaultbbry** [comment] 2019-05-21 15:42
Possibly a dupe of https://github.com/openssl/openssl/issues/7323 I opened a while ago

**Comment by p-steuer** [comment] 2019-05-21 16:43
@rwfranks  can you verify if PR https://github.com/openssl/openssl/pull/8970 fixes the issues ?

**Comment by rwfranks** [comment] 2019-05-22 13:40
Proposed change works for me.

Verification that the SHA3 implementation satisfies NIST test vectors is left as an exercise for the student.
See earlier posts

**Closed** 2019-05-22 15:05 UTC
Labels: good first issue, help wanted

**Comment by rwfranks** [comment] 2019-05-22 15:15
Thanks
