### ISSUE TITLE
libcrypto may clean itself up too early due to use of atexit()

### ISSUE THREAD

**Issue by greghudson** [openssl/openssl#16668] opened 2021-09-23 14:51 UTC
libcrypto uses atexit() to register OPENSSL_cleanup().  I haven't tracked down the discussion of this approach; I guess maybe it was seen as more portable than using `__attribute__((destructor))` or similar.  It sort of is, although it relies on beyond-standard behavior of Unix-like platforms, and on Windows it is necessary to use _onexit() instead.

Unfortunately, using atexit() puts libcrypto in its own category of libraries when it comes to finalization order.  At process exit, every atexit() handler is run in reverse order, followed by ordinary library destructors in outermost-to-innermost order (tested on Ubuntu 18.04; I can provide test libraries and a build script on request).  So, if another library uses libcrypto and defines its own finalizer using `__attribute__((destructor))`, it will discover that libcrypto has already cleaned itself up, and calls to functions like OSSL_PROVIDER_unload() will crash.  To work around this, the dependent library will need to itself use atexit() (making sure to cause libcrypto initialization to happen first, and using _onexit() instead on Windows), putting itself into the same category of atexit()-using libraries.

**Comment by t8m** [comment] 2021-09-23 15:52
I do not think we can change this in released versions. So I am calling this a feature.

**Comment by paulidale** [comment] 2021-09-23 22:17
Destructor attributes are not universal, so we'd need to keep the atexit code in addition.
Windows has an equivalent I believe.

I'm also not aware of a guarantee that destructors are run after atexit.  I've seen implementations where both are done by the code that wrappers `main()`.

**Comment by nhorman** [comment] 2024-06-10 12:48
we have a tracking issue to cover the removal of atexit here: https://github.com/openssl/project/issues/632

which is currently likely to be moved to 4.0 (I thiink)

as  such, can we mark this as a duplicate of that issue and close it?

**Comment by nhorman** [comment] 2024-08-13 20:35
marking as a dup of https://github.com/openssl/project/issues/632

**Closed by nhorman** 2024-08-13 20:35 UTC
Labels: branch: master, triaged: feature
