### ISSUE TITLE
dhparam -check doesn't check it's a safe prime

### ISSUE THREAD

**Issue by kroeckx** [openssl/openssl#13501] opened 2020-11-24 16:12 UTC
When I use `openssl dhparam -check < dh8192.pem`, in master the check is done in 4 ms. In 1.1.1 it takes 29 s.

I expect the check to at least very that it's a safe prime, which takes time, and should take longer in master than in 1.1.1. I'm not sure if we want to do other checks.

**Comment by t8m** [comment] 2020-11-24 17:58
What is in the dh8192.pem? Is it one of the known primes or is it a randomly generated safe prime?

**Comment by kroeckx** [comment] 2020-11-24 18:00
> What is in the dh8192.pem? Is it one of the known primes or is it a randomly generated safe prime?

It's a randomly generated one.

**Comment by kroeckx** [comment] 2020-11-24 18:17
This is the file I have:
-----BEGIN DH PARAMETERS-----
MIIECAKCBAEAp8cbg5K0mZGsVdpAPooH7ut34TSCEUWP0qri/6wR2znpZi8OzJwG
7Cvw7koVJLFR1QULvOHiX5SoATOIo6NiuvGNC6KKI2yt6PF9WuvdLTSqsyDxT/lq
sd+zavdcAaCZUiEjN+UVAkhLMwqcGsyL2YD09xrFJkY0scb2330d8+OBma0A9SQx
5Xa9VmO8w+AbQY7Lar7eQdt9YsSwY+DoSr//TQSIPmQlz2mNFdoiyd23wk1nJPA+
Lcekgo6p/PHPFjKLBSeNbx8gIihS6jaXOXemVag0ta0KdU/0BdzzF15VhO5hmNLm
BJMacIbaGloMAQjRixqGH2LDBtDP9Apgi1TQsstil9sSR+e3p8uYdjOAYwnIHGuO
UfTnsgD8oVKeoAgjm09CG2PQTSZdUq7RPlNpU1/8gsMK+2Ul9NKWY2nyMQnVeN8v
cnYXHoTzPCl9MbzAqe+RVuYGokDRCW4nJYi5DDp7K5Ae+Rzxk02spH3A9OU2UEC6
jzzf5HyqTHsAojrBHAi5P4riL+t7SeX7K/lVHDR5VZYEzuC+GJ2khsCNE0dKM7rM
TwC7zbMdtQJXEMsHgZ7QJQV9qrbxFjzqMwXuaFHvxnHXOuWnYtnMoOFl/vh0K2Ws
TSq+ocpXTLpg4dQ2cSIVPlZg1Cg7/THfPLNrEsfdr5k9UwrMzvjdmVPuFuOBA6fI
ls2ngKeVlg3Dt5OCFtkOSvYpWVytmP9R+gsRrfu+DYO04HmEtGTBQeIQQTUoMO6d
UOeu/UnpR+gvzB6A6exzzo+e7BB4z9piDfWZuztB0jg0COvYpCxEA0Ydf7uLkM9M
P3r8954m1prFH5rkWyk3TVOd84PQ6KJ2V1R8u05ZCPVnLn1SmvX3K+66aj/vehHE
V6gVAGgfUTCKajylzFLD4x20ZqcJb34JSrbY68n48NLbVPbb0Ycg6E5ZkUltP2uJ
k9WPhrltk5n5qJJ2BYuAyWVcpWNMvLEQIBoXV5Mz2T7jqUEHUUdBDCkXk52WcUNP
MH6T51jE6GBLnql40KmVTV4KygxsJH5jxdtwwkw3YJn1YKTd2Cqtw4aSB3jjpPvI
f621U17PDfutCV/vTiZqOGO8HPjnmkuZ7lnJJp+OkBubW25plwLWX9UNJ7RvkIaN
PMLRR/izUKCnhchup16azPh+B7Kw2iiBdgSF66SVsqSDpIyVCOPapRQMgCcrFK5o
v47XparCjJUyazdC2n3Imb+moymZwtIo3b2A+wa7fuMatfm7BW1ymeR5sCByFG9K
BcYP3R/s2yDeqAMjoF5BlqWfEYbP77KcZ27yjNyHcB4sNWUjBNVaSvjHsmxagt9i
vMZL/wOmg/y/X3hwqcyqjZtzOX6VTGPPpwIBAg==
-----END DH PARAMETERS-----

**Comment by t8m** [comment] 2020-11-24 18:37
The reason for the regression is that the provided params validation routine called with the EVP_PKEY_check_params calls DH_check_params_ex instead of DH_check_ex. I suppose we will need some extra parameter for that full validation as that full check is not usable for checking parameters online.

**Comment by paulidale** [comment] 2020-12-01 09:00
This depends on what type of key it is.

In 1.1.1 we check that it is a safe prime.  In master we don't.

Outcome: add an option to the call to allow either underlying call to be used.

**Comment by mattcaswell** [comment] 2021-02-10 14:32
Fix for this in #14146.

**Closed** 2021-02-15 04:32 UTC
Labels: branch: master, triaged: OTC evaluated, triaged: bug
