### ISSUE TITLE
SHA-3 (Keccak) support

### ISSUE THREAD

**Issue by bricss** [openssl/openssl#439] opened 2015-10-12 07:46 UTC
Add support of new standardized SHA-3 hash algorithm.

Since FIPS has released it as a standard:
http://csrc.nist.gov/groups/ST/hash/sha-3/sha-3_standardization.html
http://keccak.noekeon.org/fips202final.html

**Comment by GamePad64** [comment] 2015-12-22 22:12
Well, it would be very good.

**Comment by PanosSakkos** [comment] 2015-12-24 22:06
:+1:

**Comment by ladar** [comment] 2015-12-29 11:29
I'd like to see this as well. I'm curious if it's even on the roadmap? It will need to be added eventually, so I'm wondering if the plan is to be preemptive, or wait until an IETF RFC (like TLS or DANE) requires it? The 1.1.0 branch seems like a good place to start experimenting with support for it (even if it just a low level interface for now, and not all the way up the stack to the EVP/BIO layers).

**Comment by joostrijneveld** [comment] 2016-01-15 12:25
I agree that having SHA-3 available as a basic primitive available through `sha.h` would already be helpful, even if not yet implemented throughout the rest of the library.

**Comment by richsalz** [comment] 2016-01-15 16:10
It is not on the roadmap for 1.1; we've got too much other stuff to do.  The only way it could possibly happen is if someone provides code that's integrated and consistent with the rest of openssl.

**Comment by robertwagner** [comment] 2016-09-19 14:01
Is this something you can use?

https://github.com/rhash/RHash/blob/master/librhash/sha3.c

**Comment by ladar** [comment] 2016-10-24 21:26
Just tickling this ticket since it looks like the keccak primitives got merged into master with c3086f4630bee8972f7fc0829bec524bb5fd0baf, But alas, they aren't integrated up the API stack yet. I'm tempted to give it a shot, but thought others on this thread might have more time/experience then myself.

**Comment by mattcaswell** [comment] 2016-10-25 08:48
I suspect @dot-asm has this on his roadmap.

**Comment by richsalz** [comment] 2016-10-25 18:22
It’s being worked on….

**Comment by ladar** [comment] 2016-10-26 06:34
Hi @richsalz is there a fork (or branch) you can point me at where this work is occurring?

**Comment by levitte** [comment] 2016-10-26 06:57
@ladar, there isn't one yet.

**Comment by richsalz** [comment] 2016-10-26 15:51
No.  Everything that will end up in OpenSSL is done as PR's, so just watch.  Or make your own PR :)

**Comment by ladar** [comment] 2016-10-28 22:41
I get that everything is happening via pull requests. I was just wondering if there was a repo/fork you knew about that made progress beyond what @dot-asm has submitted? I was looking for something that offered integration with the higher level interfaces... if one does pop up, let me know, and/or tickle this thread... 

I tried searching on my own but got nada... and the fork summary page, which will sometimes help point to external repos with improvements, doesn't work for OpenSSL. You're too popular.

https://github.com/openssl/openssl/network

**Comment by bellaj** [comment] 2016-11-19 16:50
👍

**Comment by ladar** [comment] 2016-11-26 08:15
The patch links above have been updated to use the ED25519_keypair_from_seed() nomenclature, discussed on the boringssl thread below. I updated the patch so they APIs would remain consistent with each other.

https://boringssl-review.googlesource.com/#/c/12040/

**Comment by mattcaswell** [comment] 2016-11-26 09:17
You've seen this right?

https://github.com/openssl/openssl/blob/master/crypto/sha/keccak1600.c

Nothing in the public header files yet though, but a work in progress.

**Comment by ladar** [comment] 2016-11-26 10:14
Hi @mattcaswell ... yes, I have looked at the referenced file, and the keccak implementation. My comment was in regards to whether a branch/fork existed where someone had added support to the higher level interfaces, like the EVP_() and HMAC_() functions, or definitions to the obj_mac.h file, etc. 

P.S. My comment about Ed25519 a couple of hours ago was intended for the Ed25519 issue (and not SHA3), so I apologize for posting it here by mistake.

**Comment by MNFaust** [comment] 2017-06-14 13:25
Has there been any movement on this? Would love to see SHA3 implemented.

**Comment by richsalz** [comment] 2017-06-14 13:26
Yes, look at recent commits.

**Comment by kroeckx** [comment] 2017-07-05 07:30
I think the current state is that the algorithms itself are included, but that all the EVP related changes are missing like having an EVP_sha3_256().

**Comment by richsalz** [comment] 2017-08-16 14:39
all done.

**Closed by richsalz** 2017-08-16 14:39 UTC
Labels: feature
