### ISSUE TITLE
pkcs12 utility fails to read input from stdin

### ISSUE THREAD

**Issue by petrovr** [openssl/openssl#13826] opened 2021-01-10 15:04 UTC
All openssl releases could create pkcs#12 files with input from stream, stdin for example.
This feature fail with current master.

Code snippet for NSS engine regression tests (https://gitlab.com/e_nss/e_nss/-/blob/master/tests/ca/ca-cre-certs.sh#L233)
```
...
  ( cat ../$N-priv.pem
    cat ../$N-cert.pem
    cat ./crt/level1.crt.pem
    cat ./crt/root0.crt.pem
  ) | \
  $OPENSSL pkcs12 -export \
    -passin $keypass -passout $p12pass \
    -out $TMPDIR/$N.p12
...
```
Error:
```
...
Could not read private key from -in file from <stdin>
0067C347877F0000:error:1E080020:DECODER routines:decoder_process:BIO lib:crypto/encode_decode/decoder_lib.c:572:
...
```

**Comment by t8m** [comment] 2021-01-11 10:13
This is duplicate of #13185

**Comment by petrovr** [comment] 2021-01-17 16:42
Yet another report - https://github.com/lsh123/xmlsec/issues/309 perhaps related - like error in OpenSSL library function.
Perhaps openssl uttility fail due to same reason.

More or less but function failures should be covered by regression tests.

Utility could output more precise message as "... from -in file from <stdin>" does not look correct. Which one "-in" argument or "input"?

**Comment by t8m** [comment] 2021-03-05 19:26
I was wrong. This is not a true duplicate as there are additional problems with the pkcs12 utility. With #14407 reads the key fine from stdin however reading the certificates still fails.

**Comment by petrovr** [comment] 2021-03-13 14:08
Does not work with current master.
Message is "No filename or uri specified for loading certs of certificates from -in file".

**Comment by petrovr** [comment] 2021-03-13 14:10
I change title as more correct is to point that utility fail to accept all input from standart stream. This is regression.

**Comment by t8m** [comment] 2021-03-15 13:17
Now that #14449 and #14407 are merged, this should be fixed.

**Closed by t8m** 2021-03-15 13:17 UTC
Labels: branch: master, tmp: HIGH, triaged: bug
