### ISSUE TITLE
Reduce test log noise on Travis

### ISSUE THREAD

**Issue by ekasper** [openssl/openssl#1440] opened 2016-08-10 11:49 UTC
We might be hitting the log limit soon if we add more tests, see #1439.

The detailed logs are very helpful but really we are only interested in failure logs. Can we reduce log output for passing tests?

**Comment by ekasper** [comment] 2016-08-10 11:49
@levitte

**Comment by davidben** [comment] 2016-08-10 15:12
If there's some way to convince Travis to make the compile collapsable when that passed but tests failed, that would also be handy. The compile is rather noisy. It seems Travis has some ability to fold things in the log viewer, but I'm not clear on how it works.

The compile could also stand to be quieter. [Ninja](https://ninja-build.org/) does this nice buffering thing where it only shows a build line (or, in console mode, it keeps it all on one status line), but once a command fails or shows warinings, it prints the full command and build output for just edge. (Ninja is wonderful. Now that you all have the new buildsystem, I wonder how hard it'd be to make a Ninja output for it...)

**Comment by ekasper** [comment] 2016-08-11 10:10
We could `make -s`? That might be _too_ quiet (you only see the compile error but not the failing compile line - sometimes we may want to see the build line options) but we can always revisit if we ever end up needing more information? Pretty much 100% of the time now I end up loading a huge log only to scroll to the end to see where it failed.

**Comment by richsalz** [comment] 2016-08-11 12:12
I’m in favor of 'make -s' for exactly the same reason.
And we could replace the Configure output with just a repeat of its command-line arguments, for example.

**Comment by levitte** [comment] 2016-08-11 14:49
(I'm on vacation this week, but...) 

Regarding ninja, it should be extremely easy. Make a config that mentions `build.ninja` (or whatever the default name is) as build file instead if `Makefile`, then create `Configurations/unix build.ninja.tmpl`. That's about it. 

It would be cool to add an option to `Configure` to choose another build file than the default (`Makefile` for Unix, `makefile` for Windows, `descrip.mms` for VMS) 

(going back to vacation)

**Comment by richsalz** [comment] 2016-08-11 16:57
I believe supporting anything beyond make is a waste of time.

**Comment by davidben** [comment] 2016-08-11 17:24
To be clear, I pointed to ninja primarily as an example of how to do build output well, not saying you should use it. Buffering and replay full command on error is really the way to go.

Whether you all want to support ninja I'll leave to you. But I would highly recommend trying it once. (Give the BoringSSL build a go. We do make and ninja via cmake.) Ninja is wonderful.

**Comment by levitte** [comment] 2016-08-11 17:27
Ninja support doesn't have to be part of our mainstream source. It can be a side project that simply adds two files and that's it.

**Comment by levitte** [comment] 2016-08-15 12:27
Back to the actual issue, there's unfortunately no way to separate the build from the test, as they're both in the `script` step.  I can't really see a way to separate build and test in different steps, which means they won't be separately collapsible.

We might want to consider an enhancement of our runner.  Currently, it just runs all tests through `Test::Harness`'s `runtests()`.  Instead, we could use `execute_tests`, which returns a lot of interesting values including exactly what tests failed, and have the runner save those in a file (let's call it a test status file for further reference) while doing the usual printout of failed tests.

With that, our `.travis.yml` could do a first `make test` without verbosity, and then re-run `make test` with the additional arguments `TESTS={test names picked up from the test status file)` and `V=1`.  That would limit the verbosity to the specific tests that failed.

**Comment by levitte** [comment] 2016-08-15 12:28
The other option is to have the test runner do all of the above automatically if verbosity is on, regardless of Travis and anything else.

**Comment by ekasper** [comment] 2016-08-15 13:14
So I suggest
1) get Configure to spit out the configure line (@levitte, will you do that when back?), then `make -s` in .travis.yml for quick relief
2) not a fan of re-running tests on failure to get the log - tests can be flaky so the original failure may not be easily reproducible. Can we write the test output to a log file (one per recipe), then dump it to the console if the test failed? This can be for post 1.1.0.

**Comment by levitte** [comment] 2016-08-15 13:36
> 1) get Configure to spit out the configure line (@levitte, will you do that when back?)

If you can explain to me exactly what "the configure line" is supposed to be.  I assume, btw, that this would be *in addition* to what it currently spits out.

> then `make -s` in .travis.yml for quick relief

Sure.  I'm frankly not keen on it since that will never show the command line for failing compiles, buuuuut that's seldom needed anyway.  So yeah, sure.

> 2) not a fan of re-running tests on failure to get the log - tests can be flaky so the original failure may not be easily reproducible. Can we write the test output to a log file (one per recipe), then dump it to the console if the test failed? This can be for post 1.1.0.

It's kind of meh to do so, it means that we must recreate *all* the mechanisms to make the summary at the end of running the tests.  I can't say that prospect makes me very entusiastic...

**Comment by ekasper** [comment] 2016-08-15 16:20
> I'm frankly not keen on it since that will never show the command line for failing compiles, buuuuut that's seldom needed anyway. So yeah, sure.

So long as you see the Configure, I think that's practically never needed in the remote Travis logs. We can also have one BUILDONLY run emit the full build log, just in case.

**Comment by levitte** [comment] 2016-08-15 16:54
> So long as you see the Configure, I think that's practically never needed in the remote Travis logs. We can also have one BUILDONLY run emit the full build log, just in case.

#1457

**Comment by levitte** [comment] 2016-08-16 08:40
Now that #1457 is merged, I think we've done quite a bit to reduce the noise.  I suggest closing this issue.

**Comment by FdaSilvaYY** [comment] 2016-08-16 18:28
Suggestion : 
Move these two defines from command-line 
`... -DOPENSSLDIR="\"/usr/local/ssl\"" -DENGINESDIR="\"/usr/local/lib/engines-1.1\"" ... `
into opensslconf.h file who is already a generated file ...

These path could even be larger on windows plateforms...
@levitte : any opinion ?

**Comment by levitte** [comment] 2017-01-12 21:05
Apparently, I missed that last question.

The problem is the the paths for OPENSSLDIR and ENGINESDIR is generated from build file (Makefile) values, and since that differs between the platforms, it's a bit hard to do.  `opensslconf.h` is generated from `opensslconf.h.in` and values in `configdata.pm`, which in turn is generated by `Configure`.  In other words, it's not the easiest thing to accomodate...

**Comment by mattcaswell** [comment] 2017-05-02 09:54
Ping @levitte. Can we close this?

**Comment by levitte** [comment] 2017-05-02 11:40
Yup

**Closed by levitte** 2017-05-02 11:40 UTC
