### ISSUE TITLE
DH_generate_key requires q now

### ISSUE THREAD

**Issue by matbech** [openssl/openssl#11108] opened 2020-02-17 02:45 UTC
In the past, it was possible to call DH_generate_key when only (per documentation) the parameters p and g were set. Now, it seems that in some situations, q is required as well otherwise DH_generate_key fails with 0.

Pseudo code:
DH *dh = DH_new();
// p and g are provided, q is not
DH_set0_pqg(dh, p, NULL, g);
DH_generate_key(dh);

I was debugging this issue and this check in the generate_key function in dh_key.c https://github.com/openssl/openssl/blob/master/crypto/dh/dh_key.c#L249 fails because q is NULL:

            /*
             * The safe prime group code sets N = 2*s
             * (where s = max security strength supported).
             * N = dh->length (N = maximum bit length of private key)
             */
            if (dh->length == 0
                || dh->params.q == NULL
                || dh->length > BN_num_bits(dh->params.q))
                goto err;

DH_get_nid returns NID_modp_2048

**Comment by kroeckx** [comment] 2020-02-17 20:57
This seems to be new code introduced in commit f11f86f6ec7fb31bde1da2810ac975c032205321

@slontis: Can you look at it?

**Comment by slontis** [comment] 2020-02-17 22:07
Will do..

**Comment by slontis** [comment] 2020-02-18 01:21
Thank you for finding this..

Note that you could also use DH_new_by_nid() instead of DH_new() for this case and you would not have seen the issue.

**Comment by markt-asf** [comment] 2020-02-18 23:00
My testing suggests that f11f86f introduced an additional regression that is not fixed by #11114.
The scenario I am testing is (I'd provide sample code but I'm testing with Apache Tomcat and the Tomcat Native Connector so the test environment is non-trivial. I'm hoping my description will suffice.):

- server configured with RSA key/cert (no DH parameters present)
- server configured for TLSv1.2 only
- client attempting to connect with TLS_DHE_RSA_WITH_AES_256_GCM_SHA384

With 1.1.1 and master prior to f11f86f the client handshake succeeds. In master, after f11f86f the handshake fails. Applying #11114 does not resolve the issue.
If I call `SSL_CTX_set_dh_auto(c->ctx ,1);` at the end of the server SSL Context configuration, the client handshake succeeds again.

The issue appears to be `dh->length ==0` at [line 248 of dh_key.c](https://github.com/openssl/openssl/blob/master/crypto/dh/dh_key.c#L248)

**Comment by slontis** [comment] 2020-02-19 00:11
@markt-asf it is a similiar problem to the setting of q.. will include the fix in the same PR.

**Closed** 2020-03-06 21:49 UTC
Labels: triaged: bug
