### ISSUE TITLE
Cross Compile to x86_64-linux-android

### ISSUE THREAD

**Issue by cyokenn** [openssl/openssl#24838] opened 2024-07-10 14:24 UTC
I am trying to cross compile OpenSSL on Windows x64 targeting x86_64-linux-android using `cargo build --target=x86_64-linux-android`. However, during the compilation process, the path for the `mysys` Perl installation inside of the OpenSSL make file is being overridden with a Windows-style path, leading to an invalid path and a compiler crash. 

**Issue:**

When using `cargo` to build a project that depends on OpenSSL for the target `x86_64-linux-android`, the `mysys` Perl path is incorrectly being replaced with a Windows-style path, causing the compiler to fail to locate the Perl executable. 

**Steps to Reproduce:**

Note: Only replicatable in a Windows Environment.

1. Install the `x86_64-linux-android` target for Rust.
2. Install msys or any other UNIX compatable Perl.
3. Target the correct version of Perl inside .cargo/config.toml.
2. Create a simple Rust project that depends on OpenSSL.
3. Run `cargo build --target=x86_64-linux-android`.

**Expected Behavior:**

The compiler should correctly locate and use the `mysys` Perl installation at the specified path.

**Actual Behavior:**

The `mysys` Perl path is overridden with a Windows-style path, which results in the compiler failing to find the Perl executable and crashing.

**Environment:**

- Windows x64
- Rust toolchain: rustc 1.79.0 (129f3b996 2024-06-10)
- OpenSSL version: [Specify your OpenSSL version here]
- `mysys` Perl installation: [Specify the path to your `mysys` Perl installation here]

**Log Output:**

```
--- stderr
  /usr/bin/sh: line 1: C:msys64usrbinperl.exe: command not found
  make: *** [Makefile:2906: builddata.pm] Error 127
  thread 'main' panicked at C:\Users\PFG346\.cargo\registry\src\index.crates.io-6f17d22bba15001f\openssl-src-300.3.1+3.3.1\src\lib.rs:621:9:
```

I believe this issue is related to the cross-compilation environment not correctly handling the `mysys` Perl path.
I would appreciate any guidance on how to resolve this issue.

**Comment by t8m** [comment] 2024-07-10 14:50
Crosscompiling on Windows to Linux (or other posix-like systems) is not supported.

Making this a community feature request and labeling with help wanted as it is unlikely to be a priority for the OpenSSL team any time soon.

**Comment by t8m** [comment] 2024-07-10 14:54
Actually a duplicate of #24700

**Closed by t8m** 2024-07-10 14:54 UTC
Labels: branch: master, help wanted, triaged: feature
