### ISSUE TITLE
Broken AppVeyor builds in master after commit b0940b33a60

### ISSUE THREAD

**Issue by t8m** [openssl/openssl#10749] opened 2020-01-03 17:18 UTC
The commit b0940b33a60cbfa broke the AppVeyor builds in the master branch CI:
See for example https://ci.appveyor.com/project/openssl/openssl/builds/29200540

**Comment by mspncp** [comment] 2020-01-03 17:35
This is a duplicate of #10648
A fix is in #10719, waiting for @levitte's (or someone else's) approval.

**Comment by richsalz** [comment] 2020-01-03 17:38
Close this as a dup?  Since the build is broken, someone on the OTC  should just approve #10719 and do the merge now, right?

**Comment by mspncp** [comment] 2020-01-03 17:39
> someone on the OTC...

...who understands some basic Perl ;-)

**Comment by mspncp** [comment] 2020-01-03 17:50
> Close this as a dup? 

Since the titles very are different and @t8m obviously didn't see my issue, I'd prefer to keep it open and add a second 'Fixes' line to my pr.

**Comment by richsalz** [comment] 2020-01-03 17:50
No, more about quoting cmd.exe input, as you yourself said :)

**Comment by mspncp** [comment] 2020-01-03 17:53
Yes, you are right.

**Closed** 2020-01-08 17:03 UTC
Labels: branch: master, resolved: duplicate, triaged: bug
