### ISSUE TITLE
BIO_read change in 1.1.0c broke Python and MIT KRB5

### ISSUE THREAD

**Issue by tiran** [openssl/openssl#1919] opened 2016-11-14 16:12 UTC
Commit 122580ef71e4e5f355a1a104c9bfb36feee43759 broken Python's ssl module and MIT KRB5's OpenSSL plugin for MS-KKDCP (Kerberos over HTTPS). In both programs a combination of SSL_read() returning -1, SSL_get_err() returning SSL_ERROR_SYSCALL and ERR_get_error() returning 0 leads to a failure when the connection is terminated.

Patrick Uiterwijk found the bug in MIT KRB5 first. I was able to reproduce the issue with Python. I used git bisect and Python's test suite to locate the commit.

https://hg.python.org/cpython/file/tip/Modules/_ssl.c#l533
Python bug https://bugs.python.org/issue28689
https://github.com/krb5/krb5/blob/master/src/plugins/tls/k5tls/openssl.c#L516

**Comment by mattcaswell** [comment] 2016-11-14 16:20
Closing this as a dupe of #1903.

**Closed by mattcaswell** 2016-11-14 16:20 UTC
