### ISSUE TITLE
ossl_store_handle_load_result() unsupported for valid CRL

### ISSUE THREAD

**Issue by googlebleh** [openssl/openssl#24333] opened 2024-05-05 17:56 UTC
Using version `3.3.0` I see the following error while loading a CRL
```
$ openssl crl -inform PEM -in crl.rsa.2048.pem
Could not find CRL from crl.rsa.2048.pem
40A7026C52770000:error:1608010C:STORE routines:ossl_store_handle_load_result:unsupported:crypto/store/store_result.c:151:
```
This also happens on master, (`067fbc01b9e867b31c71091d62f0f9012dc9e41a` at the
time of writing). This did not happen with openssl version `3.2.1`
```
$ openssl crl -inform PEM -in crl.rsa.2048.pem
-----BEGIN X509 CRL-----
MIICWDCCAUAwDQYJKoZIhvcNAQENBQAwgegxCzAJBgNVBAYTAlVTMQswCQYDVQQI
...
```
This issue impacts users' ability to connect to VPNs with openvpn
```
$ sudo openvpn --config myconfig.ovpn
2024-05-04 22:56:30 OpenVPN 2.6.10 [git:makepkg/ba0f62fb950c56a0+] x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] [DCO] built on Mar 20 2024
2024-05-04 22:56:30 library versions: OpenSSL 3.3.0 9 Apr 2024, LZO 2.10
2024-05-04 22:56:30 DCO version: N/A
Enter Auth Username: ********
Enter Auth Password: ********
2024-05-04 22:56:33 OpenSSL: error:068000E9:asn1 encoding routines::utctime is too short:
2024-05-04 22:56:33 OpenSSL: error:0688010A:asn1 encoding routines::nested asn1 error:Field=revocationDate, Type=X509_REVOKED
2024-05-04 22:56:33 OpenSSL: error:0688010A:asn1 encoding routines::nested asn1 error:Field=revoked, Type=X509_CRL_INFO
2024-05-04 22:56:33 OpenSSL: error:0688010A:asn1 encoding routines::nested asn1 error:Field=crl, Type=X509_CRL
2024-05-04 22:56:33 OpenSSL: error:0488000D:PEM routines::ASN1 lib:
2024-05-04 22:56:33 CRL: cannot read CRL from file [[INLINE]]
2024-05-04 22:56:33 CRL: loaded 0 CRLs from file -----BEGIN X509 CRL-----
MIICWDCCAUAwDQYJKoZIhvcNAQENBQAwgegxCzAJBgNVBAYTAlVTMQswCQYDVQQI
...
```
openvpn is able to establish a connection after downgrading openssl back to
3.2.1 on my machine.

See attached for the CRL I used to reproduce this issue. [`crl.rsa.2048.pem.tar.gz`](https://github.com/openssl/openssl/files/15213954/crl.rsa.2048.pem.tar.gz)

**Comment by googlebleh** [comment] 2024-05-05 18:00
I did not see any mention of removing support in 3.3's [CHANGES.md](https://github.com/openssl/openssl/blob/openssl-3.3/CHANGES.md). maybe I missed something?

**Comment by t8m** [comment] 2024-05-06 10:28
This is a duplicate of https://github.com/openssl/openssl/discussions/24301

**Closed by t8m** 2024-05-06 10:28 UTC
Labels: issue: bug report

**Comment by ahungry** [comment] 2024-12-10 01:48
Is there a flag of some sort to parse the content in the old method, and be able to read it and view the invalid date formats that reside within?  

Short of finding this github issue, or reading through the openssl source, how would one such as myself, or the original author, be able to come to the same conclusion of what the problem was?
