### ISSUE TITLE
OpenSSL regression when a servername callback is set

### ISSUE THREAD

**Issue by beldmit** [openssl/openssl#16075] opened 2021-07-14 13:20 UTC
This change has introduced a regression:

https://github.com/openssl/openssl/blob/e77be2e20175f5ae3f96952f5b9fce557bc00fb1/ssl/statem/statem_lib.c#L1524-L1531

https://github.com/openssl/openssl/pull/13304 and https://github.com/openssl/openssl/pull/13305 introduced the behaviour change: when servername callback is set, we suppose that we are TLS1.3-capable
(see https://github.com/openssl/openssl/issues/13291 as rationale)

If we have an httpd with DSA key pair in default configuration (without any explicit protocol settings), and connecting to it via s_client, we get an alert in response to a ClientHello.

What happens inside:
When no explicit protocol is set, we get a TLS 1.3-capability flag on the server side (see the link)
When we see the flag, we choose a TLS 1.3 ciphersuite 
Then we are trying to find TLS 1.3-compatible signature algorithm relying to the previously found ciphersuite.
As we don't find it, here we get the handshake failure.

No code outside the libssl is triggered, so I think it's an openssl bug.

To deal with it, in theory it is possible to, if we are both capable to tls 1.3 and tls 1.2, change the state of connection back and switch off the tls1.3 capability. Don't know how to do it in practice, BTW...

**Comment by beldmit** [comment] 2021-07-14 13:21
I kindly ask @mdounin, @mattcaswell and @kaduk to look at this issue.

**Comment by t8m** [comment] 2021-07-14 13:58
I'd say _do not do that_ - and by that meaning configuring a server with just a DSA key pair and not setting explicitly the maximum TLS version being TLS-1.2.

IMO this is clearly a wontfix issue unless there is some kind of easy fix that won't cause further regressions in other corner cases.

**Comment by tomato42** [comment] 2021-07-14 14:01
The thing is that using DSA keys without explicitly setting supported TLS version did work, and does work with s_server (as it doesn't use SNI by default).

**Comment by t8m** [comment] 2021-07-14 14:01
The thing is, nothing is perfect. :grin:

**Comment by beldmit** [comment] 2021-07-14 14:02
@t8m, yes - but "Just a DSA key pair without setting minimal version" is a minimal case (I didn't get able to reproduce it with pure s_client/s_server case)

**Comment by t8m** [comment] 2021-07-14 14:03
Please come up with real world scenario that needs to work. And no - a server using SNI with just a DSA key pair is not one.

**Comment by mdounin** [comment] 2021-07-14 14:04
The problem is that when callbacks are present (servername callback as added in #13291 fixes, or certificate callback as present in the original TLSv1.3 implementation), OpenSSL cannot proactively disable TLSv1.3 based on certificates set, because it does not know which certificates will be set after the callback is called. On the other hand, current code is not capable of disabling TLSv1.3 after the callback is called and it becomes known that TLSv1.3 cannot be used. The only solution now is to explicitly disable TLSv1.3 in such configurations.

Alternative solution is to implement something to gracefully fallback to TLSv1.2 if after the callback it becomes clear that TLSv1.3 cannot be used (previously suggested [here](https://github.com/openssl/openssl/issues/13291#issuecomment-720604856)). This is a major change though, and explicitly disabling TLSv1.3 in such configurations might be a better solution.

**Comment by tomato42** [comment] 2021-07-14 14:07
> Please come up with real world scenario that needs to work. And no - a server using SNI with just a DSA key pair is not one.

Even if apache isn't configured to use virtual hosts and has just one DSA certificate it still uses callbacks, so a simplest possible configuration with Apache and DSA keys is broken by this change.

**Comment by tomato42** [comment] 2021-07-14 14:14
> OpenSSL cannot proactively disable TLSv1.3 based on certificates set, because it does not know which certificates will be set after the callback is called.

That's not true. If the certificates OpenSSL knows about cannot be used in TLSv1.3 (like DSA or any ECDSA that uses curves outside P-256, P-384, P-521, Ed25519 or Ed448), then it should disable TLSv1.3, precisely because they can't be used with TLSv1.3.

And it's nothing new, while you can configure OpenSSL to support different ciphersuites in different virtual hosts, you can't configure OpenSSL to support different protocol versions in different virtual hosts.

**Comment by kaduk** [comment] 2021-07-14 14:26
> while you can configure OpenSSL to support different ciphersuites in different virtual hosts, you can't configure OpenSSL to support different protocol versions in different virtual hosts.

(You can if you use the early callback instead of the servername callback.)

**Comment by mdounin** [comment] 2021-07-14 16:03
> That's not true. If the certificates OpenSSL knows about cannot be used in TLSv1.3 (like DSA or any ECDSA that uses curves outside P-256, P-384, P-521, Ed25519 or Ed448), then it should disable TLSv1.3, precisely because they can't be used with TLSv1.3.

In the particular case OpenSSL doesn't know which certificates will be used because of the callbacks set. Note that callbacks might always set certificate which can be used with TLSv1.3, regardless of what is set (or not set, as in #13291) in the context.

If the goal is to minimize cases when TLSv1.3 is not automatically disabled, then the `is_tls13_capable()` logic can be changed to something like "disable TLSv1.3 if we see DSA regardless of callbacks set". But that this approach will result in TLSv1.3 being disabled in non-trivial configurations, and there will be no way to explicitly fix things except by hiding DSA from OpenSSL (in contrast to the current behaviour, where it is trivial to disable TLSv1.3 if needed).

> And it's nothing new, while you can configure OpenSSL to support different ciphersuites in different virtual hosts, you can't configure OpenSSL to support different protocol versions in different virtual hosts.

Sure. The problem which was addressed in #13291 wasn't about not being able to configure different protocols in different virtual hosts, it was about not being able to enable TLSv1.3 due to OpenSSL incorrectly auto-disabling it.

**Comment by tomato42** [comment] 2021-07-15 12:02
> But that this approach will result in TLSv1.3 being disabled in non-trivial configurations, and there will be no way to explicitly fix things except by hiding DSA from OpenSSL (in contrast to the current behaviour, where it is trivial to disable TLSv1.3 if needed).

that's my point, that those non-trivial configurations already are legacy deployments (as they can't use TLS 1.3), but just because they are legacy, doesn't mean we should break them, especially in a minor release of a LTS branch

in other words, there's no way anybody is running a DSA cert or a Brainpool cert or a P-224 cert by mistake. And I'm pretty sure they are more interested in keeping such configuration working without messing with configuration files than in getting TLS 1.3 connections to a co-hosted page that uses more typical certificates.

**Comment by t8m** [comment] 2021-07-15 12:52
I still would like to see one real world case that uses this configuration (DSA cert only, brainpool cert only, P-224 cert only) and SNI.

**Comment by mdounin** [comment] 2021-07-15 14:19
> those non-trivial configurations already are legacy deployments (as they can't use TLS 1.3)

Non-trivial configurations I was talking about _can_ use TLSv1.3, as long as callbacks provide appropriate certificates, but OpenSSL incorrectly disabled TLSv1.3 in those configurations. Moreover, #13291 clearly shows configurations which aren't legacy but instead quite modern, yet OpenSSL incorrectly disabled TLSv1.3 in these configurations.

**Comment by tomato42** [comment] 2021-07-15 14:46
@t8m I don't understand what do you mean by "one real world case"? If you're asking for an Internet accessible server like that, then we both know there are no servers that use DSA certs. But that doesn't tell us anything about private networks.

@mdounin And I have no problem with breaking them in a 3.0.0 branch. 1.1.1 is supposed to be a stable release, where no ABI breaking changes go in. Legacy or not, DSA is compiled by default in 1.1.1.

**Comment by t8m** [comment] 2021-07-16 06:44
> I don't understand what do you mean by "one real world case"?

I mean a real customer case. Of course I understand you cannot present a Red Hat customer case without their consent here but perhaps there would be some customer willing to comment here?

**Comment by beldmit** [comment] 2021-07-16 12:15
@t8m, I'll try to ask at openssl-users

**Comment by kaduk** [comment] 2021-07-16 19:55
> I kindly ask ... @kaduk to look at this issue.

My stance is basically unchanged since https://github.com/openssl/openssl/pull/13304#issuecomment-722583136 -- there's a tradeoff, and some configurations are going to be broken no matter what we do; all we can do is shuffle around which ones those are.  (It's my opinion that attempting to shuffle around handshake processing so that we can attempt to gracefully fall back to TLSv1.2 after we discover that TLSv1.3 cannot work, will introduce more breakage than it fixes.  There are too many callbacks and undocumented requirements on the order in which callbacks are invoked, and on the order between callbacks and specific parts of handshake processing, for a human to be able to unwind things while retaining all the changes already made by callbacks that were called.

From a practical perspective, if anything your application code is doing could affect what TLS version gets negotiated (such as switching from a certificate that is compatible with TLS 1.3 to one that isn't, or vice versa), it needs to be done in the early callback, since that's the only one that runs before version negotiation.  The TLS protocol spec also assumes that version negotiation is done as the first part of handshake processing.

**Comment by beldmit** [comment] 2021-07-17 19:33
I don't think I will be able to deal with it fast, but the "ideal" solution I see is iterating all the possible protocols from the best to the worth version (with callback calls and internal downgrades). It also could make the ClientHello parsing code less spaghettish, but I'm not sure it's worth such efforts.

**Comment by t8m** [comment] 2023-10-26 14:54
Closing. This is getting less and less useful. Of course if someone comes up with a pull request it will be considered.

**Closed by t8m** 2023-10-26 14:54 UTC
Labels: branch: master, branch: 1.1.1, resolved: wont fix, triaged: bug
