### ISSUE TITLE
multiple vhost SSLProtocol error

### ISSUE THREAD

**Issue by moztabaahmed** [openssl/openssl#4302] opened 2017-08-30 23:06 UTC
I am not a programmer, but it seems like a issue with openssl. not apache. I've included the openssl ticket here. Please suggest further. Thanks

Issue: https://rt.openssl.org/Ticket/Display.html?user=guest&pass=guest&id=3183

Apache bug track discussion:

https://bz.apache.org/bugzilla/show_bug.cgi?id=55707

PS: Kindly don't close with just one reply. I get it that you guys are busy, but it's not polite to just close after one reply.

**Comment by mattcaswell** [comment] 2018-01-22 16:43
This appears to be a dupe of #4301 where all of the above links were added and the discussion took place. I'll leave this open for now because you asked me not to close it straight away...but it does seem that it was already fairly well discussed. So lacking further progress this will be closed soon.

**Comment by kaduk** [comment] 2018-01-22 22:15
My take on this is that we have fixed the underlying bug (no way to modify the supported TLS versions in response to the SNI value in the ClientHello) with the clienthello callback in master/1.1.1.  It's up to Apache to make use of that new functionality as they gain compatibility with the new release, but there is literally nothing else within the OpenSSL release policy that we can do to help with this issue.  Therefore, I think this issue should be closed.

**Closed** 2018-02-03 23:29 UTC
