### ISSUE TITLE
TLS1.3, in psk-only mode, server still send key_share extension

### ISSUE THREAD

**Issue by william-zk** [openssl/openssl#13918] opened 2021-01-21 09:56 UTC
Openssl version: 1.1.1

Use s_server can got it:
```
openssl s_server -accept 127.0.0.1:4433  -key ecc-root.key -cert ecc-root.crt -max_early_data 10000 -psk 00110011
```

Bug Description:
For all types of client psk, server will return key_share extension for ecdhe key-exchange, even in psk-only mode. In [rfc8446-section4.2.9](https://tools.ietf.org/html/rfc8446#section-4.2.9), there is a description that `  psk_ke:  PSK-only key establishment.  In this mode, the server MUST NOT supply a "key_share" value`

Actually, I think openssl does not provide a mechanism  for `PSK-only key establishment`. The lack of this mechanism will cause some problems, imagine this: A user used to deploy tls1.2 in his server, and use session-ticket for session resumption, when he update to tls1.3, he will find all tls connection will do a full ecdhe key-exchange, then cpu overflow happen.

**Comment by mattcaswell** [comment] 2021-01-21 10:15
OpenSSL does support psk_ke key establishment if the peer does not support psk_dhe_ke, e.g. if the client only offers psk_ke then an OpenSSL server can be configured to successfully complete a handshake. Similarly if an OpenSSL client encounters a server that only supports psk_ke then it can be configured to successfully complete the handshake.

In both cases, in order to do so, the option `SSL_OP_ALLOW_NO_DHE_KEX` must be set. This can be set via the config file using the `AllowNoDHEKEX` directive.

It is not currently possible to disable `psk_dhe_ke` being offered by an OpenSSL client, or accepted by an OpenSSL server. It will always be used in preference if it is available. This was a deliberate design decision made during the TLSv1.3 development in order to simplify the implementation (so it is not a bug). It also has security benefits.

I'm not really convinced that we need to support this.

**Comment by william-zk** [comment] 2021-01-21 12:18
> I'm not really convinced that we need to support this.

I think there should be a way to determine if a server can just use the key in psk, such as tls1.2, if client use session-ticket do session resumption, server can just use key in ticket without any other key exchange process. Though it's not perfect forward security,  but effective, save the cpu costing.

Tls1.3 in openssl is not compatible with this process, a client with session ticket still HAVE TO do ecdhe key exchange, even if with option `SSL_OP_ALLOW_NO_DHE_KEX ` .

**Comment by kaduk** [comment] 2021-02-05 20:11
As Matt says, the decision to not allow a client to offer just a PSK-only (no DH) TLS 1.3 key exchange was a deliberate decision during TLS 1.3 development, and the information you present was known at the time of that decision.  I don't see any arguments being presented that would change that decision, so I think that we are likely to close this issue with no changes to the code. Note that it is possible, via supported groups, to configure what algorithm is used for the key share; x25519 is a fairly lightweight choice.

**Closed** 2021-02-22 17:18 UTC
Labels: resolved: wont fix, triaged: feature

**Comment by jeremyherbert** [comment] 2022-09-22 06:54
Hi,

Just to report a situation where this does matter: I am working on a device with an extremely constrained connection, where individual bytes matter. I am trying to use TLS 1.3 with PSK.

With TLS1.2 I get the following usage:
```
$ openssl s_client -tls1_2 -connect localhost:5555 -psk abcdabcdabcdabcd -cipher PSK-AES128-GCM-SHA256 -no_ticket -msg
...
SSL handshake has read 150 bytes and written 185 bytes
...
```

But with TLS1.3 I get the following:
```
$ openssl s_client -tls1_3 -connect localhost:5555 -psk abcdabcdabcdabcd -ciphersuites TLS_AES_128_GCM_SHA256 -sigalgs "ed25519" -curves "X25519" -msg -no_ticket -noservername
...
SSL handshake has read 225 bytes and written 299 bytes
...
```

So in total the TLS1.3 handshake is 524 bytes, whereas the TLS1.2 handshake is 335 bytes. In this, the key share extension uses 42 bytes in each direction, which would bring the total down to 440 bytes - quite a significant saving for  data which is not actually used. 

(also, removing the session key middlebox compatibility stuff would bring it down to 374 bytes I think - still worse than TLS1.2, but getting pretty close)

Also:
```
$ openssl version
OpenSSL 1.1.1f  31 Mar 2020
```
