### ISSUE TITLE
expired certificate in test

### ISSUE THREAD

**Issue by andrt17** [openssl/openssl#18498] opened 2022-06-07 16:41 UTC
Hello,

It is not a big issue, just something annoying. I've redone a openssl1.1.1.o configuration today and got an error in  the test 80-test_ssl_new.t 
test/recipes/80-test_ssl_new.t (Wstat: 256 Tests: 29 Failed: 1)
  Failed test:  12
  Non-zero exit status: 1
Files=1, Tests=29, 10 wallclock secs ( 0.17 usr  0.03 sys +  9.67 cusr  1.03 csys = 10.90 CPU)
Result: FAIL

C:\Strawberry\perl\bin\perl.exe -I ..\..\util\perl ..\generate_ssl_tests.pl ..\ssl-tests\12-ct.conf.in > 12-ct.conf.32136.tmp => 0
    ok 1 - Getting output from generate_ssl_tests.pl.
    ok 2 - Comparing generated sources.
        # Subtest: ..\ssl_test.exe
        1..1
            # Subtest: test_handshake
            1..6
            ok 1 - iteration 1
            # ERROR: (int) 'result->result == test_ctx->expected_result' failed @ test\ssl_test.c:33
            # [2] compared to [0]
            # INFO:
            # ExpectedResult mismatch: expected Success, got ClientFail.
            # 38520:error:14094415:SSL routines:ssl3_read_bytes:sslv3 alert certificate expired:ssl\record\rec_layer_s3.c:1544:SSL alert number 45
            not ok 2 - iteration 2

So i digged further and it seems that the openssl-1.1.1o\test\certs\embeddedSCTs1.pem ( at least) is expired

openssl x509 -in E:\adt\openssl-1.1.1o\test\certs\embeddedSCTs1.pem -text
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 7 (0x7)
        Signature Algorithm: sha1WithRSAEncryption
        Issuer: C = GB, O = Certificate Transparency CA, ST = Wales, L = Erw Wen
        Validity
            Not Before: Jun  1 00:00:00 2012 GMT
            **Not After : Jun  1 00:00:00 2022 GMT**

So i think the tests certificates that are delivered, have to be reviewed for expiration date.

Regards.

**Comment by gjasny** [comment] 2022-06-08 06:57
Duplicate of #18456

**Comment by t8m** [comment] 2022-06-08 07:22
Duplicate of https://github.com/openssl/openssl/issues/18456

**Closed by t8m** 2022-06-08 07:22 UTC
Labels: issue: bug report
