### ISSUE TITLE
openssl ocsp-server crashes by invalid request 3 / malformedrequest (1)

### ISSUE THREAD

**Issue by RaSchmidt1960** [openssl/openssl#3043] opened 2017-03-27 19:40 UTC
Hi,

I have set up a openssl CA with OCSP-Server and revocation list.
It works, but the  OCSP-Server crashed by unexpectedly requests.
(A ocsp-request from a other computer using openssl ocsp  works correctly)

The problem/crashes are reproducibility as follows:
Enter the address of the OCSP-Server into the address line of a normal browser (e.g. firefox) and send the request. You got a information from the browser to save a file. 

At the same time the OCSP-Server crashes with the log-info: Responder Error: malformedrequest (1) 
and with the monitor output: Invalid request 3

The used port (socket) is blocked for the time-out of the operating system (FIN_WAIT eg. 120Sek).
The openssl ocsp server can only be restarted after the expiry of the time-out of FIN_WAIT.

**Comment by richsalz** [comment] 2017-03-27 19:50
We need more information, such as a backtrace, packet capture, and so on.
Please provide that or close this issue.

**Comment by RaSchmidt1960** [comment] 2017-03-27 19:56
OpenSSL 1.0.2g  1 Mar 2016
Ubuntu 16.04.2 LTS
openssl ocsp runs with root right

what do you mean by backtrace

**Comment by richsalz** [comment] 2017-03-27 20:01
The server crashed, get a backtrace such as via GDB.  And/or get a packet trace so that we can reproduce this. "Some program sent some data and my program crashed" is impossible for anyone to help with.

**Comment by RaSchmidt1960** [comment] 2017-03-27 20:08
I will tomorrow install GDP and take a backtrace, it's here at 22:07

**Comment by RaSchmidt1960** [comment] 2017-03-28 08:25
Hi,
i have take the GDP-backtrace as follow:

pidof openssl
350

gdb 2>&1 | tee gdb-openssl_ocsp.txt
handle SIG33 pass nostop noprint
set pagination 0
attach 350
continue 

  Cert-OCSP-request from another (Linux-) computer with openssl
  answer from server: good

  call the OCSP address from the (windows-) browser (firefox)
  openssl ocsp crashed as described above (same happens with an ocsp request with chilkat, but chilkat  deviates to the revocation-list)

backtrace full
  No stack.
info registers
  The program has no registers now.
x/16i $pc
  No registers.
quit

I attached a certificat and root/ca-cert, You can check the ocsp-request with openssl and then call the OCSP address from the browser - you will see that the ocsp-server not works after the call of OCSP address from the browser. After ca. 120 sec. (waiting of time-out of the operating system FIN_WAIT) the system starts the ocsp-server again.

[edifact.rs-utilityservice.de.zip](https://github.com/openssl/openssl/files/874905/edifact.rs-utilityservice.de.zip)

here comes the GDB-log:
[gdb-openssl_ocsp.txt](https://github.com/openssl/openssl/files/874856/gdb-openssl_ocsp.txt)

**Comment by richsalz** [comment] 2017-03-28 12:15
Well, you did try.  But it's still not sufficient.

If you want someone to help you figure this out, you need to make it absolutely simple for them to reproduce the problem, or at least identifier *which function* is crashing.  So far you have not done that.

1. Run your server under the debuger, print the backtrace when it crashes.
2. Compile with debugging enabled
3. Get a packet trace and show *the exact sequence of bytes in the request message* that cause the crash.


Look.  This is a free software project

**Comment by RaSchmidt1960** [comment] 2017-03-28 13:26
Hi,
its right, it is a open software project, but anyone offers professional support - the software shut be working.
Sorry, the debug modus a.s.o. is not so my profession, but i would give you the access infos for the server. At this time, the server contains no relevant private data and i can take a new setup of the server without any problems after your check. Please, contact me under welcome@geekmail.de

**Comment by johndoe31415** [comment] 2017-08-10 06:15
@RaSchmidt1960 Is this issue still relevant? I'd try to help you debug it, if that offer is still up.

**Comment by baahmi** [comment] 2017-08-10 11:05
Just hit the issue.. Reproduction : telnet localhost 2560 and hit enter a couple of times and the openssl ocsp process exits. Using centos 7, openssl-1.0.1e-51.el7_2.5.x86_64

**Comment by richsalz** [comment] 2017-08-10 12:28
Thanks for trying.  Does it also fail on supported versions, like 1.0.2 or 1.1.0?  If you can't try, that's okay; you probably gave Johannes enough information to work at it :)

**Comment by johndoe31415** [comment] 2017-08-10 16:06
Alright, I can reproduce the issue with current HEAD. Setting up a responder with

```
openssl ocsp -port 2223 -rkey x.key -rsigner x.crt -CA x.crt -timeout 120 -index x.idx
```

Sending some junk to it via telnet, the process exits:

```
Waiting for OCSP client connections...
Invalid request
Responder Error: malformedrequest (1)
```

I'll make some pizza with my wife and look into this right after that.

**Comment by johndoe31415** [comment] 2017-08-10 18:01
Alright, poked around a bit. To me, it looks like the "-ignore_err" does exactly what you want (even though the documentation might be slightly misleading). But, instead of terminating when an error occurs, it simply retries with another request. I haven't checked if that option is available with older OpenSSL versions. But could either @RaSchmidt1960 or @baahmi confirm that the responder doesn't actually *crash*, but really just exits?

Because that'd also explain the original output of @RaSchmidt1960 when running in gdb. "No registers" is shown because presumably the process has already exited (gracefully). If you'd hit a SIGSEGV, there would be register contents (and a backtrace) available.

**Comment by baahmi** [comment] 2017-08-10 23:03
Thanks johndoe31415.
The -ignore_err option keeps the responder running on my version, which for our use case is a good enough solution.

**Comment by johndoe31415** [comment] 2017-08-11 13:21
Thanks for clarifying, @baahmi -- I've also received word from @RaSchmidt1960 via email that this also solved his problem. Therefore the root cause is misleading/missing documentation. Addressed in PR #4143.

**Comment by richsalz** [comment] 2017-08-11 23:14
#4143 merged, closing this.

**Closed by richsalz** 2017-08-11 23:14 UTC

**Comment by blodamigo** [comment] 2022-11-17 12:54
> Alright, poked around a bit. To me, it looks like the "-ignore_err" does exactly what you want (even though the documentation might be slightly misleading). But, instead of terminating when an error occurs, it simply retries with another request. I haven't checked if that option is available with older OpenSSL versions. But could either @RaSchmidt1960 or @baahmi confirm that the responder doesn't actually _crash_, but really just exits?
> 
> Because that'd also explain the original output of @RaSchmidt1960 when running in gdb. "No registers" is shown because presumably the process has already exited (gracefully). If you'd hit a SIGSEGV, there would be register contents (and a backtrace) available.
> 
> Edit: To expand on this, when I run
> 
> ```
> openssl ocsp -port 2223 -rkey x.key -rsigner x.crt -CA x.crt -timeout 120 -index x.idx -ignore_err
> ```
> 
> Then, I can trigger multiple malformed requests and the responder stays alive:
> 
> ```
> Waiting for OCSP client connections...
> Invalid request -- bad HTTP verb
> Responder Error: malformedrequest (1)
> Invalid request -- bad HTTP verb
> Responder Error: malformedrequest (1)
> Invalid request -- bad HTTP verb
> Responder Error: malformedrequest (1)
> ```
Thank you. **-ignore_err**  solved my problem
