### ISSUE TITLE
Unable to build OpenSSL

### ISSUE THREAD

**Issue by Ba0Nguyen** [openssl/openssl#24377] opened 2024-05-13 05:03 UTC
<img width="662" alt="Screenshot 2024-05-12 at 8 49 11 PM" src="https://github.com/openssl/openssl/assets/161372304/1cf476e6-6633-4ccc-af93-e12ea56b0d53">

**Comment by tom-cosgrove-arm** [comment] 2024-05-13 07:28
With just a screenshot, rather than a copying the text output, and without even showing the command you ran, or details of the system you are on, this is not going to be possible to answer.

However, I suspect that this issue is really a duplicate of the discussion in #23852, where the OP was asked to talk to the authors of the dockcross package, which is where we suspect the issue is.

This issue is likely to be closed as a duplicate

**Comment by t8m** [comment] 2024-05-13 09:58
Yeah, duplicate of #23852

**Closed by t8m** 2024-05-13 09:58 UTC
Labels: issue: question
