### ISSUE TITLE
PKCS7_verify fails when pkcs7/smime contains additional intermediate certificates

### ISSUE THREAD

**Issue by jmiltner** [openssl/openssl#1997] opened 2016-11-24 09:28 UTC
When we switched to OpenSSL 1.1.0c (from 1.0.2j), all of a sudden a part of our code that verifies the signature of a specific type of PKCS7 message no longer can verify the trust of the signer certificate.
The PKCS7 contains the signer certificate, plus two additional intermediate CA certificates (aka untrusted CA certs), our code provides the root CA certificate as a trusted certificate in the "store" param to `PKCS7_verify()`.
This used to work and IMHO, the documentation can be read to allow this scenario, since the complete chain of certificates is given by the 
- signer certificate from the PKCS7 
- two intermediate CA certs from the PKCS7
- the root CA cert as a trusted certificate

These 4 certs are form a signing chain and root in the trusted root CA.

This worked in OpenSSL 0.9.7 through 1.0.2, but with 1.1.0, this no longer works, because apparently, the intermediate CA certs are no longer taken into account:
when I provide them as additional chain certs in the "_certs_" parameter to `PKCS7_verify()` , the verification works.
(However, this seems unnecessary, since `PKCS7_verify()` is documented to do exactly this if I don't pass the `PKCS7_NOINTERN` or `PKCS7_NOCHAIN` options).

My knowledge and understanding of the OpenSSL code is not nearly enough to be able to really determine whether this change is intended, but when I debugged with the 1.1.0 code I found the following:
`find_issuer()` in 1.1.0 (called from within `build_chain()`)  calls `x509_check_cert_time()` when it finds an issuer certificate in the (untrusted) X509 stack. However, in this case, it passes -1 for the "depth" parameter, which causes our verification callback NOT to be called for this certificate.

As it happens, the specific PKCS7 blob we get from a physical device contains an expired intermediate certificate (which we cannot influence, since this intermediate certificate is embedded in the device hardware, so we have a verification callback that specifically allows expired certificates).

As I said, I don't have enough knowledge of the OpenSSL code to judge whether this situation was prevented deliberately (for security concerns) or whether it's just a regression. Also I wouldn't know how / where the appropriate fix should be done, so I didn't attempt to include a patch.

I have attached a sample PKCS7 blob and the root CA we use as [pkcs7_verify issue.zip](https://github.com/openssl/openssl/files/610896/pkcs7_verify.issue.zip) - this should be sufficient to reproduce the problem. The code we use to call `PKCS7_verify()` is essentially something like this:

```C
PKCS7* p7 = d2i_PKCS7_bio(pkcs7Bio, NULL); // pkcs7Bio is a BIO reading from the pkcs7Blob file
X509_STORE* rootStore = X509_STORE_new();
X509_STORE_add_cert(rootStore, rootCACert); // rootCACert is an X509* read from the "RootCA.pem" file
BIO* contentDataBio = BIO_new(BIO_s_mem());
X509_VERIFY_PARAM_set_flags(X509_STORE_get0_param(rootStore), X509_V_FLAG_CB_ISSUER_CHECK);
X509_STORE_set_verify_cb(rootStore, acceptExpiredCertsVerificationCallback); // acceptExpiredCertsVerificationCallback essentially just ignores X509_V_ERR_CERT_HAS_EXPIRED errors
X509_STORE_set_purpose(rootStore, X509_PURPOSE_ANY);
PKCS7_verify(p7, NULL, rootStore, NULL, contentDataBio, 0 ); // fails with "unable to get local issuer certificate" in 1.1.0c, succeeds in 1.0.2j
```

The attached archive [pkcs7_verify issue.zip](https://github.com/openssl/openssl/files/610896/pkcs7_verify.issue.zip) also contains a source file "repro.c" that compiles against OpenSSL 1.0.2 and OpenSSL 1.1.0 that reproduces the issue with OpenSSL 1.1.0c (just run the compiled executable with two arguments: first one is the path to _data.pkcs7_, second one is the path to _RootCA.pem_.

**Comment by jmiltner** [comment] 2016-11-24 09:48
This regression appears to have been introduced with commit 70dd3c6593d87e4cbb56b485717cb2cfff730f3e ("Tidy up x509_vfy callback handling")...

**Comment by mattcaswell** [comment] 2016-11-24 09:53
Ping @vdukhovni.

**Comment by prsyahmi** [comment] 2016-11-24 12:35
I confirm this issue is happening with our end as well, we just switched to 1.1.0c from 1.0.2h and suddenly the verification doesn't work. The verify callback is never called for expired intermediate certificate where we provide additional timestamp and counter signature verification there.

Besides PKCS7_verify, the X509_STORE_CTX_get_chain, X509_verify_cert is also affected.
With X509_STORE_CTX_get_chain, we got only a signer and X509_verify_cert has the same issue as PKCS7_verify.

**Comment by vdukhovni** [comment] 2016-11-24 19:00
I'll take a look

**Comment by vdukhovni** [comment] 2016-11-25 05:33
Looking at the two changes noted, the logic is that when selecting certificates and encountering an expired issuer certificate we  keep going and try find a non-expired one, if at all possible.  The expired issuer is however saved, and ultimately returned if nothing better is found.  Therefore no callback should be made, since we may erroneously report an error that turns out to be irrelevant.  So those commits are fine, and are not the cause of the reported symptoms.

Mind you, if folks want to skip expiration checks, instead of callbacks, they should just set `X509_V_FLAG_NO_CHECK_TIME`.

The actual cause is fbb82a6 which changed `find_issuer` (which looks for untrusted certifictates from the peer, rather than locally stored certs) to not return an expired untrusted issuer as a last resort, in the hope that the trust store may contain suitable issuers that are not expired!  However, since we're now doing "trusted-first" unconditionally, if we're searching the untrusted store then that's the only possible source of a possible issuer.  So a revert to previous behaviour of find_issuer is likely in order, PR coming up...

**Comment by vdukhovni** [comment] 2016-11-25 05:44
Created PR #2004 which should fix this for 1.1.0-stable.  The same change should then also be made in `master`.

**Comment by jmiltner** [comment] 2016-11-25 08:46
Thanks, I can confirm that PR https://github.com/openssl/openssl/pull/2004 works for us in the actual product.

**Comment by vdukhovni** [comment] 2016-11-28 08:28
Reopening, pending integration of https://github.com/openssl/openssl/pull/2004, https://github.com/openssl/openssl/pull/2005

**Comment by vdukhovni** [comment] 2016-12-03 00:41
PRs #2004 and #2005 are now merged. Thanks for the report. Closing.

**Closed by vdukhovni** 2016-12-03 00:41 UTC
