### ISSUE TITLE
Immutable provider keys

### ISSUE THREAD

**Issue by kroeckx** [openssl/openssl#14391] opened 2021-03-02 13:09 UTC
During the OTC calls we regularly talk about immutable keys in the provider. We currently have 2 exceptions for this:
- We allow setting the cofactor
- For a key exchange, we allow setting the public key using the EVP_PKEY_set1_encoded_public_key function that is being added in 3.0

Do we want to change any of those? I think at least for the key exchange it would require a new API to do a key exchange.

**Comment by t8m** [comment] 2021-03-02 14:21
As for the set1_encoded_public_key - this might be an acceptable exception or we might just as well do a different API that would be actually probably even easier to use with the key exchange. Just allow setting the encoded public key as a parameter of the EVP_PKEY_CTX when set up for key exchange. The current API requires to set up extra EVP_PKEY with domain parameters copied from our key and then setting the public key of the peer. As the domain parameters must be the same (and they are usually supplied separately by protocols) there is no point in putting the encoded key into a separate EVP_PKEY.

Unfortunately I am afraid that for legacy purposes and backwards compatibility we would have to keep the old set_peer_key API there as well.

Similarly the cofactor could be also key exchange parameter instead of mutable field of PKEY.

**Comment by mattcaswell** [comment] 2021-03-02 14:21
> For a key exchange, we allow setting the public key using the EVP_PKEY_set1_encoded_public_key function that is being added in 3.0

Note that the new 3.0 function is effectively just a rename of the `EVP_PKEY_set1_tls_encodedpoint()` function that existed in 1.1.1.

The problem being solved by this function is the parameters and the public key coming from different locations. So to solve that we create a parameters only key, and then add a public key to it. An alternative model could be to create a parameters only key, and then create a new key based on those parameters and the public key. If we went that route then we'd have to decide what to do with the old `EVP_PKEY_set1_tls_encodedpoint()` function. An acceptable answer could be simply to remove it because, in practice, I suspect it is largely unused outside of libssl.

**Comment by t8m** [comment] 2021-03-02 14:25
Yeah, we could also do something like EVP_PKEY_dup_with_encoded_public_key() :grin: Which would create a copy of a PKEY where the domain parameters would be copied and the public key would be set from a function parameter.

**Comment by mattcaswell** [comment] 2021-03-02 14:36
Looking at how this is used in practice I see three scenarios in the code for where the parameters come from:

Result of EVP_PKEY_copy_parameters() based on our own private key
Result of generating parameters (EVP_PKEY_paramgen) from a given group name
Result of reading parameters from some DER encoding of the parameters (OSSL_DECODER_CTX_new_for_pkey).

The most common is the first of these. So the function `EVP_PKEY_dup_with_encoded_public_key()` would cover all three of these scenarios. If it *just* copies the parameters from the original key then you could eliminate all the existing `EVP_PKEY_copy_parameters` calls.

**Comment by mattcaswell** [comment] 2021-03-02 14:38
> We allow setting the cofactor

Could we take the same approach with the cofactor? i.e. you create a new key based on a pre-existing one?

**Comment by levitte** [comment] 2021-03-02 14:52
Hmmmm... an idea could be to have `EVP_PKEY_fromdata` mimic `EVP_PKEY_keygen` in so far that it can take a "templace" EVP_PKEY that contains key parameters.  API-wise, that would be fairly consistent...

**Comment by mattcaswell** [comment] 2021-03-15 10:54
Needs discussion by OTC

**Comment by paulidale** [comment] 2021-03-15 11:22
This is a duplicate of #14075, however there is useful information here.

**Closed by paulidale** 2021-03-15 11:22 UTC
Labels: branch: master, hold: need otc decision, tmp: HIGH, triaged: bug
