### ISSUE TITLE
upgrading from 1.1.1.e and 1.1.1.f causes openvpn connections using ssl to fail.

### ISSUE THREAD

**Issue by baelish** [openssl/openssl#11456] opened 2020-04-01 13:37 UTC
Apologies in advance for what is probably a poor report as it's affected me only indirectly through openvpn.

```
moiraine$>openvpn --version
OpenVPN 2.4.8 [git:makepkg/3976acda9bf10b5e+] x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Jan  3 2020
library versions: OpenSSL 1.1.1e  17 Mar 2020, LZO 2.10
Originally developed by James Yonan
Copyright (C) 2002-2018 OpenVPN Inc <sales@openvpn.net>
Compile time defines: enable_async_push=no enable_comp_stub=no enable_crypto=yes enable_crypto_ofb_cfb=yes enable_debug=yes enable_def_auth=yes enable_dlopen=unknown enable_dlopen_self=unknown enable_dlopen_self_static=unknown enable_fast_install=yes enable_fragment=yes enable_iproute2=yes enable_libtool_lock=yes enable_lz4=yes enable_lzo=yes enable_management=yes enable_multihome=yes enable_pam_dlopen=no enable_pedantic=no enable_pf=yes enable_pkcs11=yes enable_plugin_auth_pam=yes enable_plugin_down_root=yes enable_plugins=yes enable_port_share=yes enable_selinux=no enable_server=yes enable_shared=yes enable_shared_with_static_runtimes=no enable_small=no enable_static=yes enable_strict=no enable_strict_options=no enable_systemd=yes enable_werror=no enable_win32_dll=yes enable_x509_alt_username=yes with_aix_soname=aix with_crypto_library=openssl with_gnu_ld=yes with_mem_check=no with_sysroot=no
```
^ Works

```
(1/1) Arming ConditionNeedsUpdate...

~/Downloads
moiraine$>openvpn --version
OpenVPN 2.4.8 [git:makepkg/3976acda9bf10b5e+] x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Jan  3 2020
library versions: OpenSSL 1.1.1f  31 Mar 2020, LZO 2.10
Originally developed by James Yonan
Copyright (C) 2002-2018 OpenVPN Inc <sales@openvpn.net>
Compile time defines: enable_async_push=no enable_comp_stub=no enable_crypto=yes enable_crypto_ofb_cfb=yes enable_debug=yes enable_def_auth=yes enable_dlopen=unknown enable_dlopen_self=unknown enable_dlopen_self_static=unknown enable_fast_install=yes enable_fragment=yes enable_iproute2=yes enable_libtool_lock=yes enable_lz4=yes enable_lzo=yes enable_management=yes enable_multihome=yes enable_pam_dlopen=no enable_pedantic=no enable_pf=yes enable_pkcs11=yes enable_plugin_auth_pam=yes enable_plugin_down_root=yes enable_plugins=yes enable_port_share=yes enable_selinux=no enable_server=yes enable_shared=yes enable_shared_with_static_runtimes=no enable_small=no enable_static=yes enable_strict=no enable_strict_options=no enable_systemd=yes enable_werror=no enable_win32_dll=yes enable_x509_alt_username=yes with_aix_soname=aix with_crypto_library=openssl with_gnu_ld=yes with_mem_check=no with_sysroot=no
```
Fails with error messages like this: 
```
Apr 01 13:05:57 moiraine nm-openvpn[17321]: VERIFY ERROR: depth=0, error=unable to get local issuer certificate: O=**********, CN=*********************
Apr 01 13:05:57 moiraine nm-openvpn[17321]: OpenSSL: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
Apr 01 13:05:57 moiraine nm-openvpn[17321]: TLS_ERROR: BIO read tls_read_plaintext error
Apr 01 13:05:57 moiraine nm-openvpn[17321]: TLS Error: TLS object -> incoming plaintext read error
Apr 01 13:05:57 moiraine nm-openvpn[17321]: TLS Error: TLS handshake failed
```
Perhaps this issue is caused downstream but I figured if rolling back openssl fixes things that's probably where the issue lies.

**Comment by t8m** [comment] 2020-04-01 15:16
It is very unlikely that this issue would be caused by openssl differences between 1.1.1e and 1.1.1f. The changes between 1.1.1e and 1.1.1f are very minimal and in particular there were no changes related to certificate verification.  What is the system/distribution? Could it be some additional difference in the downstream packages of openssl?

**Comment by baelish** [comment] 2020-04-01 16:17
Agreed, I had a look at the release notes and thought the same, can't see how that's caused my problem but then on the same note, not sure why it would warrant changes in the downstream package either. I can report it at Arch as well. Just wanted it reported somewhere in case other people run into the same issue as I spend quite some time troubleshooting my vpn before I got here.

**Comment by baelish** [comment] 2020-04-01 16:42
Reported with Arch linux also. https://bugs.archlinux.org/task/66067

**Comment by diabonas** [comment] 2020-04-01 20:00
This is not a downstream packaging issue, commit https://github.com/openssl/openssl/commit/ba4356ae4002a04e28642da60c551877eea804f7#diff-06463ef55f4d9d5411a243b09e66c06fR110-R111 changed the response for self-signed certificates with invalid certificate extensions. To reproduce, generate a self-signed certificate with inconsistent extensions (with any OpenSSL version) using
```
openssl genrsa -out private.pem 4096
openssl req -new -key private.pem -out csr.pem
openssl x509 -req -signkey private.pem -in csr.pem -out cert.pem -extfile <(echo "basicConstraints=CA:FALSE,pathlen:0")
```
Now try verifying the generated certificate `cert.pem` using
```
openssl verify cert.pem
```
In OpenSSL 1.1.1e, this yields
```
C = AU, ST = Some-State, O = Internet Widgits Pty Ltd
error 18 at 0 depth lookup: self signed certificate
error cert.pem: verification failed
```
while OpenSSL 1.1.1f gives
```
C = AU, ST = Some-State, O = Internet Widgits Pty Ltd
error 20 at 0 depth lookup: unable to get local issuer certificate
error cert.pem: verification failed
```

I suspect your VPN provider's certificate has inconsistent extensions (and is therefore broken and should not be used), but previous OpenSSL versions didn't report this because it is a self-signed certificate.

**Comment by bernd-edlinger** [comment] 2020-04-02 04:31
Hmm, nice that we catch the invalid certificate now, and a bit unexpected,
I was more or less knowing that the out of memory would be ignored and invalid
extensions cached in that case.
That commit was merged before it was clear that there would be a 1.1.1f,
but everything happened so quickly.

**Comment by bernd-edlinger** [comment] 2020-04-02 04:35
> report this because it is a self-signed certificate

More likely did not report this ever.

**Comment by bernd-edlinger** [comment] 2020-04-02 04:36
Could we see the certificate which caused the original problem?
We need more of these invalid certificates for our testing.

**Comment by t8m** [comment] 2020-04-02 07:48
The question is why openssl allows at all producing a certificate with the invalid CA:false and pathlen:0 combination. And although the RFC 5280 explicitly disallows this it is also questionable whether openssl shouldn't be more lenient and do not mark such certificates (with pathlen 0 only) with EXFLAG_INVALID.

**Comment by bernd-edlinger** [comment] 2020-04-02 07:50
that was an example, given above, but I still would like to know what is wrong with
the certificate that was used above, it could be a parse error in one of the extenions,
maybe even a mandatory one.

**Comment by bernd-edlinger** [comment] 2020-04-02 07:52
> The question is why openssl allows at all producing a certificate with the invalid CA:false 

Because it is a foot-shoot-gun ?

**Comment by t8m** [comment] 2020-04-02 08:46
At least the error reporting should be improved. It is really bad when the only message you get from the verify command is that seemingly the issuer certificate cannot be obtained, but you get no hint on why it is so when you provided it.

**Comment by bernd-edlinger** [comment] 2020-04-02 09:25
Yes, but the error reporting is as non-trivial as the error handling.
We could probably cache the error reason and put it on the stack when the
cached result is not available to be used.

**Comment by baelish** [comment] 2020-04-02 11:27
> Could we see the certificate which caused the original problem?
> We need more of these invalid certificates for our testing.

We've confirmed the error in the server side error and are looking to replace them. Once done I will ask if I may share them. I can confirm right now that they have:

```
            X509v3 Basic Constraints: critical
                CA:FALSE, pathlen:0
```

**Comment by t8m** [comment] 2020-04-02 13:47
So this is the same issue as in the comment above. I do not care about certificates with parsing errors, they should be really marginal and if they are broken by 1.1.1f they deserve it. But I'd really propose to not mark certificate with CA:FALSE, pathlen:0 with the EXFLAG_INVALID as this is something that can occur easily given openssl itself does not check for this when you're creating a self-signed certificate.

**Comment by bernd-edlinger** [comment] 2020-04-02 13:54
can you make a PR for that or should I do that?

**Comment by t8m** [comment] 2020-04-02 14:09
PR in #11463

**Comment by vdukhovni** [comment] 2020-04-02 19:11
> > The question is why openssl allows at all producing a certificate with the invalid CA:false
> 
> Because it is a foot-shoot-gun ?

No, because OpenSSL provides tools that do what you say, and don't second-guess your intent.  Just because the certificate does not conform to PKIX, does not mean it should be impossible to generate.

Now perhaps such combinations could require `-force` flag or similar, but that would break compatibility for little gain.  More appropriate would be a new `-verify` flag that checks that the result is generally acceptable (as either a self-signed or CA-issued) certificate.

**Comment by bernd-edlinger** [comment] 2020-04-02 19:21
Yeah, I know, I made a joke, at leas I could laugh a while....

**Comment by vdukhovni** [comment] 2020-04-02 19:26
> Yeah, I know, I made a joke, at least I could laugh a while....

No worries, enjoy: https://lists.sr.ht/~jack/acme-dont-discuss/%3C874ku38utr.fsf%40jackkelly.name%3E

**Closed** 2020-04-06 08:27 UTC
Labels: issue: bug report
