### ISSUE TITLE
OpenSSL allows the client to present a SHA-1 certificate.

### ISSUE THREAD

**Issue by Immortalem** [openssl/openssl#12134] opened 2020-06-13 12:48 UTC
### Affected Versions
1.1.1g, 1.0.2u

### Setup
OpenSSL has been compiled from source in an alpine docker container. The following excerpt of the used docker file shows the build related commands:
```
RUN ./config --prefix=/build/ --openssldir=/build/ no-async 
RUN make -s && make install_sw -s
```
After building it the respective OpenSSL version and required libraries have been copied into an minimal docker container (from scratch).

The server is later started using the following command:
`openssl s_server -accept 4433 -Verify 100 -cert /cert/inputCerts/rootv3.pem -key /cert/keys/rootv3.pem -CAfile /cert/inputCerts/root.pem -verify_return_error`

All files mentioned in this report (certificates, keys, etc.) have been included in the attached zip archive.

### Issue
Both OpenSSL version allow the client to present a leaf certificate which is signed using a combination of SHA-1 and a signature algorithm. Since SHA-1 is no longer considered secure such certificates should be rejected by default.

### Reproduction
Uses OpenSSL 1.1.1 on Ubuntu 18.04.
Connect to the started server using the following command:
`openssl s_client -connect localhost:4433 -cert ECROOTv3_CAv3_LEAF_ECv3_Sha1__leaf_certificate1.pem -key eckey_secp256r1_3.pem -CAfile ECROOTv3_CAv3_LEAF_ECv3_Sha1__ca_certificate1.pem`

### Expected Result
OpenSSL should reject the certificate for its weak hash function.

### Actual Result
OpenSSL happily accepts the certificate and proceeds with the handhshake.

### Attachment
[opensslSha1.zip](https://github.com/openssl/openssl/files/4774598/opensslSha1.zip)

**Comment by FdaSilvaYY** [comment] 2020-06-13 13:04
Duplicate of #10787 ?

**Comment by Immortalem** [comment] 2020-06-13 13:12
From skimming through the conversation it looks like the other issue moves SHA-1 to a lower, non default, security level. So yes appears to be duplicate. Sorry.

**Comment by FdaSilvaYY** [comment] 2020-06-13 13:14
You are right to report, because it is not yet fixed.
Thanks for the report.

**Comment by kroeckx** [comment] 2020-06-13 13:45
In 1.1.0 and later, it depends on the security level. In the
released versions, it's currently allowed at the default security
level 1 but not at security level 2.

The master branch changed it to also rejects it at security level
1. It was decided to not change this in the 1.1.1 or older branches.

**Comment by kroeckx** [comment] 2020-09-13 18:13
Closing, since I don't think we're going to change anything related to this.

**Closed by kroeckx** 2020-09-13 18:13 UTC
Labels: issue: bug report
