### ISSUE TITLE
Silent gcc warning for unused parameter in err.h

### ISSUE THREAD

**Issue by Julien-Elie** [openssl/openssl#12584] opened 2020-08-05 06:49 UTC
Hi all,

In OpenSSL 3.0-alpha5, there's an unused parameter in the definition of ERR_GET_FUNC() in openssl/err.h:

/home/iulius/work/openssl-3.0.0-alpha5/include/openssl/err.h:223:51: attention:paramètre « errcode » inutilisé [-Wunused-parameter]
```
  223 | static ossl_inline int ERR_GET_FUNC(unsigned long errcode)
      |                                     ~~~~~~~~~~~~~~^~~~~~~
```

Easy fix with:
static ossl_inline int ERR_GET_FUNC(**ossl_unused** unsigned long errcode)

Thanks.

**Comment by kaduk** [comment] 2020-08-06 19:25
Seems to be a duplicate of #12459

**Closed** 2020-08-07 07:20 UTC
Labels: resolved: duplicate, triaged: bug
