### ISSUE TITLE
Warning LNK4248

### ISSUE THREAD

**Issue by amaljesudas** [openssl/openssl#6166] opened 2018-05-03 12:52 UTC
Hi,

I am performing CMS based encryption on files.
The environment is a mix of C++ and C#.

On building, I get the following warnings related to CMS structures:
_warning LNK4248: unresolved typeref token (0100001D) for 'engine_st'; image may not run
warning LNK4248: unresolved typeref token (01000021) for 'CMS_ContentInfo_st'; image may not run
warning LNK4248: unresolved typeref token (01000031) for 'CMS_RecipientInfo_st'; image may not run_

On doing a bit of research on Microsoft links, the cause of LNK4248 was mentioned as below:
_LNK4248 can occur when there is only a forward declaration for a type in an MSIL module (compiled with /clr), where the type is referenced in the MSIL module, and where the MSIL module is linked with a native module that has a definition for the type.
In this situation, the linker will provide the native type definition in the MSIL metadata, and this may provide for the correct behavior.
However, if a forward type declaration is a CLR type, then the linker's native type definition may not be correct._

Can anyone suggest the correct fix to avoid the above warnings?

Also there were many suggesting that the warnings are harmless and could be ignored.
Unfortunately, my work scenario calls for committing code without warnings and errors.
In this case, would it be right if I could just use fake structures and get away with the warnings ?
Eg:
struct engine_st {};
struct CMS_ContentInfo_st {};
struct CMS_RecipientInfo_st {};

Thanks in advance.

Regards,
Amal

**Comment by mspncp** [comment] 2018-05-03 13:38
Hello Amal,

these OpenSSL structures are opaque since version 1.1.0, i.e., there are only forward declarations by design. So my guess is that it is safe to ignore the warning.

Declaring your own fake structures to get rid of warningLNK4248  is not a  good idea. Instead, if you decide that LNK4248 is 'harmless', you can disable this warning explicitely using the [/IGNORE linker command line argument](https://msdn.microsoft.com/en-us/library/dn782850.aspx).

Hope that helps,
Matthias

**Comment by mspncp** [comment] 2018-05-03 13:40
Update: There seems to be a newer version of the help page, see https://docs.microsoft.com/de-de/cpp/build/reference/ignore-ignore-specific-warnings.

**Comment by mspncp** [comment] 2018-05-03 13:42
MSDN always changes the language automagically :-/ here's the link in english https://docs.microsoft.com/en-us/cpp/build/reference/ignore-ignore-specific-warnings

**Comment by amaljesudas** [comment] 2018-05-03 14:44
Hi @mspncp ,

Thanks for the bundle of information Matthias.
My version of openssl is 1.0.2n, so can I assume that it will be safe to ignore those warnings[LNK4248]?
Asking since you mentioned version 1.1.0 explicitly.

Regards,
Amal

**Comment by mspncp** [comment] 2018-05-03 15:42
In 1.0.2, most structures were not opaque yet, but an exception holds for ASN1 data structures like CMS_ContentInfo. So yes, it's the same situation here.

I don't know much of the details of dot net, but I have a suspicion what could be the cause of your error: Is it possible that you have members of type `struct CMS_ContentInfo_st` in one of your data structures, instead of type `struct CMS_ContentInfo_st *`?  In other words, are you using structs instead of pointers to structs?

In native C-Code, this would not be possible, because the compiler would not know the size of the structure and the layout of the members. The compiler only gets to see the following declaration in cms.h:

```
typedef struct CMS_ContentInfo_st CMS_ContentInfo;
```

You would get a C compiler error if you declare a variable of the structure type. These structures are only passed as opaque pointers from OpenSSL to the calling app (i.e., as `CMS_ContentInfo *`) they are allocated and freed inside OpenSSL, where the compiler has access to the full structure definition (which is in cms_lcl.h).

Now for MSIL, the situation seems to be a little bit different, because somehow the linker is able to pass type information to the MSIL module. At least that is what I read in the paragraph you cited. 

```
LNK4248 can occur when there is only a forward declaration for a type in an MSIL module (compiled with /clr), where the type is referenced in the MSIL module, and where the MSIL module is linked with a native module that has a definition for the type.

In this situation, the linker will provide the native type definition in the MSIL metadata, and this may provide for the correct behavior.

However, if a forward type declaration is a CLR type, then the linker's native type definition may not be correct
```

So instead of getting an error, you just get the strange linker warning. But the true problem is, you need to use pointers to the opaque struct and call OpenSSL api functions to create and free instances of these structs.

Please let me know if my suspicion is correct.

**Comment by amaljesudas** [comment] 2018-05-04 05:43
Actually my actual implementation of CMS encryption is inside a proper C++ static library.
There I am using a pointer of CMS_ContentInfo as shown below:
_CMS_ContentInfo *cms = NULL;
cms = SMIME_read_CMS(in, &indata);_

From a C# module, we invoke an API in another C++ dll that eventually calls the Encrypt function of our lib.

Regards,
Amal

**Comment by mspncp** [comment] 2018-05-04 06:31
This looks ok at first sight. However, I don't know much about the rules and pitfalls of mixing native and managed code (which I assume you are doing). In your place, I would spend a little more time to find out whether LNK4284 is inevitable or whether it is caused by some mistake in your application. (Maybe the managed code should not get to see the OpenSSL headers? I have no idea.) Only then you can safely disable the warning.

Hope that helps. If you manage to find a solution which could be useful for other OpenSSL users, too, it would be nice if you could share the information on this ticket. Closing the ticket for now, since it's not an OpenSSL issue.

**Closed by mspncp** 2018-05-04 06:31 UTC

**Comment by amaljesudas** [comment] 2018-05-04 06:35
Thanks Matthias.
Will surely post once I solve the same.

Regards,
Amal

**Comment by mspncp** [comment] 2018-05-04 06:37
Your're welcome! You might also want to consider posting a question to the [openssl-users](https://mta.openssl.org/pipermail/openssl-users) mailing list. Maybe there are other OpenSSL users out there which can help you with your questions.
