### ISSUE TITLE
ARMv8 (arm64, aarch64) fails "make test" at 70-test_sslmessages.t

### ISSUE THREAD

**Issue by vielmetti** [openssl/openssl#2350] opened 2017-02-02 14:53 UTC
Building openssl on ARMv8 (arm64, aarch64). I ran into a bunch of test errors, but rather than track all of them, I thought I'd just focus on one and try to get it to pass.

Please let me know what other information you need, or that would help debug this particular set of failures.

```
../test/recipes/70-test_sslmessages.t ......     
    #   Failed test 'Message type check. Got nothing, expected 2'
    #   at ../test/testlib/checkhandshake.pm line 106.
    
    #   Failed test 'Message type check. Got nothing, expected 11'
    #   at ../test/testlib/checkhandshake.pm line 106.
    
    #   Failed test 'Message type check. Got nothing, expected 14'
    #   at ../test/testlib/checkhandshake.pm line 106.
    
    #   Failed test 'Message type check. Got nothing, expected 16'
    #   at ../test/testlib/checkhandshake.pm line 106.
    
    #   Failed test 'Message type check. Got nothing, expected 20'
    #   at ../test/testlib/checkhandshake.pm line 106.
    
    #   Failed test 'Message type check. Got nothing, expected 4'
    #   at ../test/testlib/checkhandshake.pm line 106.
    
    #   Failed test 'Message type check. Got nothing, expected 20'
    #   at ../test/testlib/checkhandshake.pm line 106.
    # Looks like you planned 33 tests but ran 22.
    # Looks like you failed 7 tests of 22 run.
../test/recipes/70-test_sslmessages.t ...... 1/21 
#   Failed test 'Default handshake test'
```

**Comment by mattcaswell** [comment] 2017-02-02 15:01
test_sslmessages sets up a series of handshakes between s_client and s_server and checks that we see all the messages (with associated extensions) that we expect to be sent. If you're getting problems here then its likely something fairly fundamental is wrong. Try firing up s_server and then try to connect to it with s_client and see if it succeeds.

The other thought is that these are libssl level errors. If the other errors you are seeing are in libcrypto, to the point that libcrypto is fundamentally broken, then libssl is never going to work.

**Comment by dot-asm** [comment] 2017-02-07 11:14
I can't reproduce this on an aarch64 system. It ought to be something rather generic, or in other words not *really* OpenSSL-specific, i.e. another program in similar situation would fail too. Either way our options to resolve non-reproducible problem are naturally limited...

**Comment by mattcaswell** [comment] 2017-05-02 14:32
No further progress on this. Closing.

**Closed by mattcaswell** 2017-05-02 14:32 UTC
