### ISSUE TITLE
SSL user data gets overwritten

### ISSUE THREAD

**Issue by DenisLug** [openssl/openssl#8088] opened 2019-01-25 10:07 UTC
When I parse a TLS 1.3 custom extension with my registered callback function and write it into user data which I have set and get before ([SSL_get/set_ex_data](https://www.openssl.org/docs/man1.1.1/man3/SSL_get_ex_data.html)) I get the right values from the other host. Directly after parsing my extension the client or server tries to get the finished message and here the user data gets overwritten. I have copied the stack trace of the operation which modifies the memory of my user data.

Server:
```
Thread #1 [opp_run_dbg] 14791 [core: 0] (Suspended : Watchpoint : *0x55555a9c32df)  
    __memmove_avx_unaligned_erms() at 0x7ffff6abec85    
    WPACKET_memcpy() at packet.c:372 0x7fffefdc6719 
    WPACKET_sub_memcpy__() at packet.c:381 0x7fffefdc677a   
    tls_construct_stoc_key_share() at extensions_srvr.c:1.727 0x7fffefe06489    
    tls_construct_extensions() at extensions.c:846 0x7fffefdf8f37   
    tls_construct_server_hello() at statem_srvr.c:2.415 0x7fffefe1f44f  
    write_state_machine() at statem.c:841 0x7fffefe08622    
    state_machine() at statem.c:441 0x7fffefe079e7  
    ossl_statem_accept() at statem.c:255 0x7fffefe0753a 
    SSL_do_handshake() at ssl_lib.c:3.579 0x7fffefdecc4a    
    <...more frames...> 
```

Client:
```
Thread #1 [opp_run_dbg] 14791 [core: 2] (Suspended : Watchpoint : *0x55555a096120)  
    __memmove_avx_unaligned_erms() at 0x7ffff6abee3a    
    ssl3_read_bytes() at rec_layer_s3.c:1.395 0x7fffefdcd0a9    
    tls_get_message_body() at statem_lib.c:1.275 0x7fffefe182ef 
    read_state_machine() at statem.c:621 0x7fffefe07eb2 
    state_machine() at statem.c:432 0x7fffefe079a8  
    ossl_statem_connect() at statem.c:250 0x7fffefe0751b    
    SSL_do_handshake() at ssl_lib.c:3.579 0x7fffefdecc4a    
    inet::OpenSSL::recvRequestHSData() at OpenSSL.cc:406 0x7ffff143e96f 
    <...more frames...> 
```
Do you have any idea why OpenSSL overwrites the user data?

The version of OpenSSL is 1.1.1 stable.

Best regards
Denis

**Comment by mattcaswell** [comment] 2019-01-25 13:19
Can you share the code for your custom extension?

**Comment by DenisLug** [comment] 2019-01-25 13:35
Unfortunately it is a private repository where I'm working. But I use almost with some adaptations the same code as the apache trafficserver. 
There you can find the following parts:
- [Callback functions](https://github.com/apache/trafficserver/blob/quic-11/iocore/net/quic/QUICTransportParameters.cc#L539)
- [Store of add function](https://github.com/apache/trafficserver/blob/quic-11/iocore/net/quic/QUICTransportParameters.cc#L283)
- [Load of parse function](https://github.com/apache/trafficserver/blob/quic-11/iocore/net/quic/QUICTransportParameters.cc#L74)
- [_parameters as custom extension](https://github.com/apache/trafficserver/blob/quic-11/iocore/net/quic/QUICTransportParameters.h#L111)
- [Register of callback functions](https://github.com/apache/trafficserver/blob/quic-11/iocore/net/quic/QUICConfig.cc#L54)

If you need something specific I can try to provide it for you.

**Comment by mattcaswell** [comment] 2019-01-28 17:05
This sounds like a potential memory corruption (maybe??). I think this is going to be difficult to make much headway on without a minimal reproducer.

**Comment by DenisLug** [comment] 2019-01-29 15:32
I have created now a minimal application to reproduce the error. You can find it here: https://github.com/DenisLug/OpenSSL-TLS1.3-Custom-Extension

You need to start a client and a server. Ideally you set a breakpoint at the [end of transportParamsParseCB()](https://github.com/DenisLug/OpenSSL-TLS1.3-Custom-Extension/blob/master/OpenSSL_Client_Server.cpp#L346) and after this at the [beginning of the while loop](https://github.com/DenisLug/OpenSSL-TLS1.3-Custom-Extension/blob/master/OpenSSL_Client_Server.cpp#L110). Take a look at the data attribute of remoteTP after parsing.

The localTP is the custom extension. On receiving localTP, I parse it into the remoteTP. When parsing is finished the remoteTP is equals the localTP. But shortly after parsing remoteTP gets corrupted.

**Comment by mattcaswell** [comment] 2019-01-29 16:26
The docs for the custom extension parsing are here:

https://www.openssl.org/docs/man1.1.1/man3/SSL_CTX_add_custom_ext.html

In particular you should note this line about the parse callback:

````
The buffer B<in> is a temporary internal buffer which will not be valid after
the callback returns.
````

From reading your code it looks to me like you are storing away a pointer into this temporary internal buffer:

```
        // Store parameter
        if (end - p >= len) {
            openSSL->remoteTP->parameterMap.insert(std::make_pair(tpID, new QUICTransportParameters::Value(const_cast<uint8_t*>(p), len)));
            p += len;
        }
````
IIUC `p` here is a pointer into that buffer. The "Value" constructor has this definition:

````
QUICTransportParameters::Value::Value(uint8_t* value, uint16_t valueLength)
{
    this->data = value;
    this->length = valueLength;
}
````
So it just saves away the pointer. But since that pointer is to a temporary buffer it becomes invalid as soon as you exit the callback.

**Comment by mattcaswell** [comment] 2019-01-30 10:16
No problem. Glad we could resolve your issue. Closing.

**Closed by mattcaswell** 2019-01-30 10:16 UTC
