### ISSUE TITLE
Non-compliant SNI hostname

### ISSUE THREAD

**Issue by npmccallum** [openssl/openssl#8083] opened 2019-01-24 20:39 UTC
`openssl s_client -connect [::1]:5000 ...`

The above command sets the IP address as the SNI HostName. However, RFC 6066 states:

> Literal IPv4 and IPv6 addresses are not permitted in "HostName".

OpenSSL should not create requests the violate the standards.

As a corollary, OpenSSL does allow IP addresses in the SNI HostName on the server side. I'll leave this to you to decide whether or not to be liberal or strict in what you receive.

**Comment by briansmith** [comment] 2019-01-24 20:59
In particular, some implementations, especially any based on [webpki](https://github.com/briansmith/webpki) like [rustls](https://github.com/ctz/rustls), will reject these ClientHellos.

**Comment by richsalz** [comment] 2019-01-24 21:04
The client program is used (mainly?) for debugging.  You can use the -servername flag to get the value you want.  Adding a check for IP address syntax seems worse.

**Comment by npmccallum** [comment] 2019-01-24 21:12
@briansmith GnuTLS rejects it too. https://gitlab.com/gnutls/gnutls/issues/683

**Comment by npmccallum** [comment] 2019-01-24 21:12
@richsalz The program is *designed* for debugging. However, the program is *used* in all sorts of ways.

**Comment by npmccallum** [comment] 2019-01-24 21:14
@richsalz I don't think a check for the syntax seems worse. But that's your call. Another option would be to not propagate the SNI HostName parameter automatically. So you would have no SNI HostName parameter unless you specify `-servername ...`.

**Comment by npmccallum** [comment] 2019-01-24 21:16
There may be other reasons to validate the input that is inserted into SNI HostName. Validating input seems kind of important for a crypto library.

**Comment by kaduk** [comment] 2019-01-24 21:17
> Another option would be to not propagate the SNI HostName parameter automatically.

That seems unlikely, given that #2614 is fairly recent in terms of architecture decisions.

**Comment by briansmith** [comment] 2019-01-24 21:20
> That seems unlikely, given that #2614 is fairly recent in terms of architecture decisions.

It seems like #2614 is a regression that breaks interop in this scenerio.

**Comment by richsalz** [comment] 2019-01-24 21:25
Most users prefer populating the SNI with the server name.  Most people do not use raw IP addresses. The OpenSSL applications grew organically; "designed" is not a word that comes to mind for them.

Some may disagree with these graven-in-stone statements. :)  So be it.

**Comment by sam-github** [comment] 2019-01-30 01:11
`good first contribution`?

**Comment by InfoHunter** [comment] 2019-01-30 02:14
Trivial Note: I think some people may use `s_client` as a test tool, for instance, to test if a server can reject IP address SNI value correctly, but not sure if this kind of usage is common or not...

**Comment by mattcaswell** [comment] 2019-01-30 11:48
> good first contribution?

I added the appropriate labels.

**Comment by iamihalcea** [comment] 2019-02-05 13:52
Hi all, I'd like to get involved and since this is marked as a good first issue I thought I'd give it a go. Would it mean implementing a check for whether the servername looks like an IP or is that sort of functionality already available?

**Comment by mattcaswell** [comment] 2019-02-05 13:55
Yes that's what it needs. I'm not aware of that functionality already existing anywhere - although perhaps @levitte might know better.

**Comment by iamihalcea** [comment] 2019-02-05 15:33
There seem to be some helper methods to convert string to IP address that can be used to validate, in v3_utl.c (L1028). If you're ok with me using that I'll carry on with it

**Comment by mattcaswell** [comment] 2019-02-05 16:10
Sure. Although it is unfortunate that those functions are in libcrypto and so aren't accessible to libssl and/or the command line apps.

That also begs the question: where is the most appropriate place to do this check. Should it be inside the implementation of `SSL_set_tlsext_host_name()` which means that OpenSSL would reject an attempt to set an IP address as the SNI hostname in all circumstances. Or should it simply be in s_client (which only impacts that command line app). I suppose I might tend towards the former.

**Comment by sam-github** [comment] 2019-02-05 16:35
I think doing it in set_tlsext_host_name is  the right place, but not for 1.1.1, please. It's not backwards compatible. Node has users using IP addresses here, and while we added a warning to tell them that what they are doing is invalid, we can't completely reject it until our next semver-major/API-breaks-allowed release.

cf. https://github.com/nodejs/node/issues/14736 and https://github.com/mattiash/node/commit/e441340443c7a64b532501b8aaabf6bc0e0946b6

**Comment by richsalz** [comment] 2019-02-05 16:52
Making the syntax-check public could be worthwhile.  I'm not sure it's fully correct tho.
Also, strongly afainst putting the check into ```SSL_set_tlsext_host_name()``` as it will break debugging with s_client.

**Comment by mattcaswell** [comment] 2019-02-05 17:25
So this looks like something we should do in s_client only. Probably only where we are implicitly defaulting the SNI hostname. If the user explicitly sets the hostname to an IP address using the "-servername" option then we should allow them to do so.

**Comment by kaduk** [comment] 2019-02-05 18:13
I agree that this should not be in ```SSL_set_tlsext_host_name()``` -- AFAICT the DNS specifications do not actually forbid putting a name in the DNS whose string form happens to also be interpretable as an IP address.  It would be a pretty bad idea, of course, and lots of things would break...but it's not clear that we need to be one of them.  That is, we don't need to be in the business of deciding how to resolve the conflict within RFC 6066 when a string is both a DNS name and a literal IP address.

**Comment by briansmith** [comment] 2019-02-05 18:13
Instead of checking if the hostname looks like an IP address and avoiding SNI in that case, you should instead check if the hostname looks like a dNSName and only set SNI in that case.

**Comment by briansmith** [comment] 2019-02-05 18:15
> the DNS specifications do not actually forbid putting a name in the DNS whose string form happens to also be interpretable as an IP address

I recommend using the syntax for a presented dNSName in X.509; i.e. use the dNSName parser that the X.509 code uses. This is what Rustls is doing when it rejects OpenSSL's invalid SNI with an IP address in it.

**Comment by briansmith** [comment] 2019-02-05 18:18
> That is, we don't need to be in the business of deciding how to resolve the conflict within RFC 6066 when a string is both a DNS name and a literal IP address.

X.509 already forbids those strings as dNSNames so TLS effectively does too, since you can't have a X.509 certificate with a valid subjectAltName/dNSName of that form.

**Comment by richsalz** [comment] 2019-02-05 18:32
You seem to be ignoring the point that people often (mostly?  who knows) use the OpenSSL app for debugging and testing, not as production clients/servers.

**Comment by briansmith** [comment] 2019-02-05 18:33
@richsalz I'm subscribed to this issue because people are using `s_client` to test my implementation that enforces this constraint and reporting bugs against my implementation when the bug is in `s_client`.

**Comment by sam-github** [comment] 2019-02-05 18:47
For s_client, I can see how its useful for it to do invalid things, but it should probably warn in these cases, or make the user be explicit about their intention.

If the check for valid SNI name isn't going to be forced when setting the tls extension, it would be helpful if the check was exported as a libssl API function (maybe there is some x509 code that is close to exposable already), so that users of the tlsext API could choose to make the check themselves, and the check would be correct and consistent. Who knows what happens if we all roll the check ourselves.

**Comment by kaduk** [comment] 2019-02-05 18:48
Brian's suggestion of only automatically populating SNI if the hostname looks like a DNS name seems pretty good.  Then advanced users still have the option of manually setting a SNI string (e.g., that happens to also look like an IP address) if needed.

**Comment by iamihalcea** [comment] 2019-02-05 18:53
@sam-github [This](https://github.com/openssl/openssl/blob/master/crypto/x509v3/v3_ncons.c#L301) is the best I could find in my digging, but maybe I should focus more on libssl instead of libcrypto.

**Comment by sam-github** [comment] 2019-02-05 19:08
@iamihalcea I'm not going to be of help here, but maybe @briansmith would be, see https://github.com/openssl/openssl/issues/8083#issuecomment-460745130, if necessary and with appropriate CLA, maybe you can even steal Rust code.

**Comment by iamihalcea** [comment] 2019-02-05 20:01
@briansmith - I'm assuming your version is the one [here](https://github.com/briansmith/webpki/blob/68fcf3dd3b7f90fc51ebde1397da7b6f5d1e4034/src/name.rs#L732), am I right? If so I'll compare with the version I linked above, but I'm still not sure where I should place this code if it should be available for libcrypto, libssl and the cli apps

**Comment by briansmith** [comment] 2019-02-05 20:23
@iamihalcea Yes, that's what I use to validate the names. I suspect OpenSSL has some code *somewhere* to do the same or similar already though. It would be better to reuse what OpenSSL does (improving it as necessary) since OpenSSL probably won't accept a PR with code under my code's license.

**Comment by mattcaswell** [comment] 2019-02-06 10:26
There's some DNS checking code here (written by @vdukhovni who may also be able to offer some advice):

https://github.com/openssl/openssl/blob/8269e44f9e40831a497fe9f31ba1d65aeb49a5c1/crypto/x509v3/v3_ncons.c#L301-L392

**Comment by iamihalcea** [comment] 2019-02-06 11:22
@mattcaswell yeah, that's the one I linked above as well and it's the one which I was planning to use, but I got confused by your point that code in those files isn't accessible for libssl or the cli apps. I'll try to see how I can make in available for s_client

**Comment by mattcaswell** [comment] 2019-02-06 11:37
> I got confused by your point that code in those files isn't accessible for libssl or the cli apps

It isn't. libcrypto is entirely self contained, so internal functions aren't available to libssl or the cli apps. This gives us three choices:

1) Copy & paste the code to where ever else we need it
2) Make the code into a public libcrypto API which would make it accessible but at the disadvantage of making it publicly accessible which we don't always necessarily want to do unless there's a strong reason (once a public API is defined we have to support it for ever more, so we better make sure end user applications have a need for it, we get the design right and it is well documented)
3) Make the code into a private libcrypto API, e.g. see the functions declared in include/openssl/internal

**Comment by mattcaswell** [comment] 2019-02-06 11:38
I'd add that with (3) this is typically used to making private functions in libcrypto accessible to libssl. We don't normally use this for the cli apps. These should be considered the same as any other end user application and should use the public API.

**Comment by iamihalcea** [comment] 2019-02-06 11:43
Alright, that makes sense, I'll stay away from option (2). I'll probably go for option (1) since we don't really need a conversion tool - just checking is enough in this case.

**Comment by vdukhovni** [comment] 2019-02-07 01:33
Just a short comment on that function.  Its purpose is make sure that any CN that looks plausibly like a DNS name is checked against DNS name constraints. Therefore, within reason the function tries to be inclusive, and its matching of DNS names is not so strict as to rule out all numeric IPv4 addresses, implausible TLDs, ... it is a filter that weeds out obvious non-DNS names so as to avoid false-positives.

In the context of this issue, however we seem to be looking to determine when to automatically use a server name as an SNI hint, without explicit indication to do that from the user.  Therefore, it may be better to err more on the side of *not* matching dubious names, that could be construed as DNS names by some, but are as much or more likely to be deemed invalid by the server.  Therefore, the appropriate function might  can and should be more strict.  We do however have the advantage that the name in question did resolve to an IP address, so if is not a DNS name, it either was an IP address, or perhaps some name in local hosts file, ...  So perhaps the thing to do is filter out dotless unqualified names, and address literals, and let the rest through.

Therefore, the code for this can be quite different and simpler than the code that's filtering CNs.

**Comment by iamihalcea** [comment] 2019-02-07 09:26
Thanks @vdukhovni - I'll update the PR to match your suggestion.

**Comment by jcrowgey** [comment] 2019-02-27 04:37
https://github.com/openssl/openssl/pull/8175#issuecomment-465233747

^^^ that comment makes it seem like this issue is resolved (but didn't get automatically closed---maybe because of some sort of commit-squashing)

**Comment by ShinzaemonRonin** [comment] 2019-03-11 06:30
It is an easy fix to be honest. If you been watching the client has an attitude but for good reason I am sure. I will talk to him and explain things and if people just hop on his laptop or on his account he has been taking it the wrong way I am sure everybody just wants to help. I can promise to talk to him the problem will be solved in 2 hours. As long as he isn't mad about being stuck in a loop or having his laptop taken over and blasted on the internet or his IP address for all of his devices put out there so every one is on his devices. But I am sure he will be reasonable. I be back in 2 hours.

**Comment by ShinzaemonRonin** [comment] 2019-03-11 06:43
The reason it is blank is very simple the people who hack my phone can't see what I am doing. No IP address you can't track. I could show you how they was crying over the loss of points in the analytics. They should be trying to raid on me again here so so I can add the option address if you would like. I was going to buy a domain name before they got control of my laptop free info.

**Comment by frederikwh** [comment] 2019-07-03 16:32
@mattcaswell 
Seems like this issue should be closed.

**Comment by mattcaswell** [comment] 2019-07-04 08:55
Fixed by #8175

**Closed by mattcaswell** 2019-07-04 08:55 UTC
Labels: good first issue, help wanted
