### ISSUE TITLE
OpenSSL 3.0.0-alpha2 missing error codes in headers

### ISSUE THREAD

**Issue by reaperhulk** [openssl/openssl#11844] opened 2020-05-16 03:06 UTC
The new `PROV_R_*` error codes (and `PROV_F_*` function codes) aren't exposed in the public headers, but their values can be returned in OpenSSL errors in 3.0.0-alpha2 (e.g. `PROV_R_WRONG_FINAL_BLOCK_LENGTH`).

**Comment by kaduk** [comment] 2020-05-16 21:54
Not answering your question at all, but I'm surprised to see that there are any `PROV_F_*` codes, since providers are new in 3.0 and 3.0 also makes the change to not expose function codes from the main libraries.

**Comment by richsalz** [comment] 2020-05-16 21:58
There utility crypt still creates the ```_F_``` entries because it wasless of a change to keep the parsing for that.

**Comment by mattcaswell** [comment] 2020-05-18 07:16
There are actually a few error header files which are internal:

include/internal/propertyerr.h
include/internal/dsoerr.h
include/crypto/sm2err.h
providers/common/include/prov/providercommonerr.h

I actually forget the reasoning behind making this private. @levitte/@paulidale/@slontis - do any of you recall?

**Comment by levitte** [comment] 2020-05-18 09:07
Error codes produced by providers in general are inherently unknown, unless a public header with the reason codes for them is published by whoever authors those providers. They are further unknown because the normal thing is that the "library code" is determined dynamically.

Whether *our* providers should return codes that are entirely, partially or not at all deterministically is something we haven't talked about, at all. What we currently have is really cheating... but we have support for that kind of cheating and could continue doing so.

So, we need to determine what we want to do with the generated reason codes. Some of us devs have a regular vidcall on Tuesday mornings. I suggest we have this as a topic tomorrow.

I can answer re DSO, though. That interface was moved to become entirely internal, so the error macros became internal as well. Good thing or bad thing? That's up for debate.

**Comment by reaperhulk** [comment] 2020-09-13 03:19
Has any decision been reached here? (I don't have a strong opinion on either direction, but would like to get it resolved so I can finish out `pyca/cryptography`'s 3.0.0 support)

**Comment by kaduk** [comment] 2020-09-15 16:19
@levitte do you recall if this topic actually was discussed on one of the tuesday calls?

**Comment by levitte** [comment] 2020-09-15 17:36
Nope, we haven't touched the topic, as far as I recall.

This is really a dodgy  subject, especially in view of different providers having their own set of error codes (it's absolutely permissible), so another external provider that supplies really cool RSA acceleration will throw any checks of specific OpenSSL generated error codes off.

Mind you that we do have a "global" set of errors, those named `ERR_R_`, and I for one would rather expand those...  *a lot*, and use them, as well as encourage everyone else to do the same when applicable.  That would be the most reliable source of error codes.

If that's feasible for 3.0, I have no idea.  @paulidale, @mattcaswell, @slontis, @romen, @mspncp, can we remind each other to have a talk about this next tuesday?

**Comment by paulidale** [comment] 2020-09-15 21:45
We should have a discussion about this.  Not sure it will end up being a up _short_ discussion and we'll have several other things on the agenda.

I've been thinking about regenerating error files -- I think it would be a good sanity check even if we don't release the result.  Essentially to see that we can build from that state or not.  Lots of errors have moved between modules but didn't always get their names updated to match (I'd guess, usually they didn't).

**Comment by t8m** [comment] 2020-09-17 07:55
IMO the cleanup of the reason codes in the sense @levitte proposed could be something that could get exception to get in after beta1.
We should not really use PROV_R codes.

**Comment by levitte** [comment] 2020-09-17 08:04
> I've been thinking about regenerating error files

You mean like `cryptoo/err/openssl.txt`?

**Comment by levitte** [comment] 2020-09-17 08:14
> We should not really use PROV_R codes.

Why not?  The idea is and has always been the providers can / should have their own set of error codes.  This is by design.

Our own providers cheat like there's no tomorrow with this, they use the generated OpenSSL errors.  The mechanism that allows it is this:

https://github.com/openssl/openssl/blob/067a3057c3aab0cdd9a3cdb13c2e0000f69a4170/crypto/provider_core.c#L1046-L1055

That is, quite frankly, a hack that we have in place because we had a lot of higher priority stuff, so that piece of code is rather in the "oh bother" category than by grand design.  It is safe for now, and as far as I can see, for the extent of 3.0.x.  This will become a problem as soon as libcrypto and the FIPS module start to exist in diverging versions, i.e. error codes are not necessarily in sync in sync any longer.

**Comment by t8m** [comment] 2020-09-17 08:26
I said "should not" not "must not ever". What I mean by this is I wanted to support the idea that we should expand on the ERR_R reason codes and encourage the providers (even third party) to use these where appropriate. Of course for internal diagnostics I can understand that the providers might want to also return some fine-grained and provider specific reason code on the lower level in the error stack, but if possible the top level error should be something the calling application can really decide on.

As providers (possibly third party) can be enabled/loaded based on configuration the calling application might not know about them and their third party specific reason values. So that is something that the provider writers should have on mind.

**Comment by mattcaswell** [comment] 2020-09-24 14:33
Temporarily adding to beta 1 milestone. I'm not sure if we've reached a consensus on the way ahead here.

**Comment by richsalz** [comment] 2020-12-29 18:11
It has been three months since the last comment whch added it to the 3.0 beta required list.

I have a proposal:  OpenSSL code should use OpenSSL public errors.  External providers will have to use openssl error codes for now.  Fix it later.

**Comment by t8m** [comment] 2021-02-11 08:37
This is now fixed on master.

**Closed by t8m** 2021-02-11 08:37 UTC
Labels: branch: master, triaged: OTC evaluated, triaged: bug
