### ISSUE TITLE
openssl3.x's performance is significantly lower than 1.1.1

### ISSUE THREAD

**Issue by zuttosy** [openssl/openssl#22884] opened 2023-11-30 02:03 UTC
OpenSSL 1.1.1 is outdated, but when we tested OpenSSL 3.0 and 3.1, we found that their performance is significantly lower than 1.1.1. Which version of OpenSSL should we choose?

**Comment by mattcaswell** [comment] 2023-11-30 10:16
From a performance perspective 3.1 should be significantly better than 3.0, and 3.2 should be a bit better than 3.1. There is further work planned for 3.3 (April 2024) which should hopefully make some additional improvements.

Performance issues are highly workload dependent so it depends exactly what you are doing to what extent you will encounter performance issues.

We are interested in building a set of "representative" performance workload tests to better target our performance improvement work. There are a few tests already here but we need more/better ones:

https://github.com/openssl/tools/tree/master/perf

If you have suggestions (or better yet PRs) to add to the tests there, that would be helpful.

**Comment by nhorman** [comment] 2023-12-01 13:13
Suggest closing as a dup, to consolidate the discussion to one location

**Comment by t8m** [comment] 2023-12-01 13:14
Duplicate of #17627

**Closed by t8m** 2023-12-01 13:14 UTC
