### ISSUE TITLE
aix-cc : 32-bit : compilation issue

### ISSUE THREAD

**Issue by sanumesh** [openssl/openssl#24503] opened 2024-05-27 10:18 UTC
Hello

aix-cc configuration of master branch with xlc-16.1 compiler on AIX 7.2 gives the following error:

cc  -I. -Iinclude  -qpic -q32 -qmaxmem=16384 -qro -qroconst -qthreaded -O -DB_ENDIAN -DOPENSSL_PIC -DOPENSSLDIR="\"/home/sanumesh/openssl_myrepo_master_checkxts_64/ssl\"" -DENGINESDIR="\"/home/sanumesh/openssl_myrepo_master_checkxts_64//lib/engines-3\"" -DMODULESDIR="\"/home/sanumesh/openssl_myrepo_master_checkxts_64//lib/ossl-modules\"" -D_THREAD_SAFE -DOPENSSL_BUILDING_OPENSSL -DNDEBUG   -c -o ssl/rio/libssl-lib-poll_immediate.o ssl/rio/poll_immediate.c
"ssl/rio/poll_immediate.c", line 62.9: 1506-022 (S) "rtnevents" is not a member of "struct ssl_poll_item_st".
"ssl/rio/poll_immediate.c", line 72.25: 1506-022 (S) "reqevents" is not a member of "struct ssl_poll_item_st".
"ssl/rio/poll_immediate.c", line 88.21: 1506-022 (S) "rtnevents" is not a member of "struct ssl_poll_item_st".
"ssl/rio/poll_immediate.c", line 88.21: 1506-022 (S) "rtnevents" is not a member of "struct ssl_poll_item_st".
"ssl/rio/poll_immediate.c", line 100.17: 1506-022 (S) "rtnevents" is not a member of "struct ssl_poll_item_st".
"ssl/rio/poll_immediate.c", line 100.17: 1506-022 (S) "rtnevents" is not a member of "struct ssl_poll_item_st".
"ssl/rio/poll_immediate.c", line 107.13: 1506-022 (S) "rtnevents" is not a member of "struct ssl_poll_item_st".
"ssl/rio/poll_immediate.c", line 107.13: 1506-022 (S) "rtnevents" is not a member of "struct ssl_poll_item_st".
"ssl/rio/poll_immediate.c", line 112.13: 1506-022 (S) "rtnevents" is not a member of "struct ssl_poll_item_st".
"ssl/rio/poll_immediate.c", line 112.13: 1506-022 (S) "rtnevents" is not a member of "struct ssl_poll_item_st".
"ssl/rio/poll_immediate.c", line 115.15: 1506-022 (S) "rtnevents" is not a member of "struct ssl_poll_item_st".
make: The error code from the last command is 1.

Sandeep Umesh
AIX Security Development

**Comment by nhorman** [comment] 2024-05-28 07:46
this is an AIX issue.  https://github.com/openssl/openssl/issues/24236

the long and short of it is that AIX has rather unkindly created a global macro defining events and revents to reqevents and rtnetevents which messes up the definition of SSL_POLL_ITEMS.  The easiest solution is to change the name of the SSL_POLL_ITEM struct, but there are abi concerns there IIRC.

The AIX team should be informed of this though.,

closing this as a duplicate of #24236

**Closed by nhorman** 2024-05-28 07:46 UTC
Labels: issue: bug report
