### ISSUE TITLE
Handshake failure if client doesn't include TLS Extensions for ECC in client hello

### ISSUE THREAD

**Issue by gabrieleco** [openssl/openssl#7621] opened 2018-11-12 14:58 UTC
Hello,

starting from version 1.0.2k, handshake fails trying a connection between **a server that allows ECC** cipher (e.g.  ECDHE-RSA-AES128-GCM-SHA256) and **a client that propose ECC but doesn't include TLS Extensions for ECC in client hello**. There is the same result with latest 1.1.1
According to RFC 4492(https://tools.ietf.org/html/rfc4492) it seems that exstensions are not mandatory, if client doesn't propose them the server is free to choose any one of  the elliptic curves or point formats listed in Section 5 , instead server returns no shared cipher error message and exits
From RFC:
  

>  The client MUST NOT include these extensions in the ClientHello
   message if it does not propose any ECC cipher suites.  A client that
   proposes ECC cipher suites may choose not to include these
   extensions.  In this case, the server is free to choose any one of
   the elliptic curves or point formats listed in Section 5.  That
   section also describes the structure and processing of these
   extensions in greater detail.

The same configuration worked well in previous version (1.0.2j), it seems that this different behavior has been introduced by the commit 292bb56846ad78ac7b68a00c92153c0c9471665b  that changed   the client hello check (file  ssl/s3_srvr.c) in particular lines 1468-1470

how to reproduce:
use openssl version >=1.0.2k
server side configuration: openssl s_server -accept <port> -CAfile <cacert> -cert <servercrt> -key <serverprivatekey> -cipher ECDHE-RSA-AES128-GCM-SHA256

**Comment by mattcaswell** [comment] 2018-11-14 14:43
I can confirm this behaviour for 1.1.1 and 1.1.0, but not for 1.0.2. In my tests it seems to work just fine in 1.0.2.

The removal from 1.1.1/1.1.0 appears to have been a deliberate decision. See #1597. It seems the RFC allows us free to make our own choice on how to handle this, and from 1.1.0d onwards we have chosen to take a more conservative approach and not negotiate EC based ciphersuites if the EC extensions are missing. Arguably that change shouldn't have happened in a stable branch, and should have waited for 1.1.1 - but it seems academic now.

**Comment by bbbrumley** [comment] 2018-11-14 19:58
Dunno if it's related, but I feel it's worth mentioning that RFC4492 is recently obsoleted by [RFC8422](https://tools.ietf.org/html/rfc8422). So if quoting standards, it's worth pointing at the current one ;)

**Comment by sevabo** [comment] 2019-07-09 22:25
Hello OpenSSL community,
Wanted to report the new issue but it looks it is related to this conversation.

When ClientHello message proposes ECC cipher suite (TLS_ECDHE_ECDSA_WITH_AES_128_CCM_8 in my case) without two extensions:  Supported Elliptic Curves (10) and Supported Point Formats (11), server (that has TLS_ECDHE_ECDSA_WITH_AES_128_CCM_8 cipher suite in its certificate) does not fall back to choose any one of elliptic curves or point formats and fails to negotiate the connection with the client.
The server results in a fatal handshake failure alert due to the lack of common cipher suites.  

According to RFC 8422 standard “A client that proposes ECC cipher suites may choose not to include these extensions. In this case, the server is free to choose any one of the elliptic curves or point formats listed in Section 5.”

The version that I am using is 1.1.0j. It seems like the version 1.1.1 has the same issue.
Please correct me if I am wrong here.
Also was that feature intentionally removed starting from version 1.0.2k and will not be added back again? 
Thanks and best regards.

**Comment by vyasatavi** [comment] 2019-11-18 01:44
@mattcaswell any update on @sevabo question? I am running into the same issue. In order to use TLS13 we upgraded to openssl 1.1.1 from 1.0.2g and we are running into this issue. Legacy apps that are used to not sending the extension now fail.

**Comment by kaduk** [comment] 2020-10-15 20:48
It looks like #8115 is an attempt to resolve this issue, but the approach described in #2237 might be better overall.
I do not think there is a definitive answer to @sevabo's question ("will we definitively not add back default-group support?") at this time, though one should generally assume continuation of the status quo.

**Comment by t8m** [comment] 2021-07-19 15:46
Closing as duplicate of #2237

**Closed by t8m** 2021-07-19 15:46 UTC
