### ISSUE TITLE
ERROR: openssl/1.1.1i: Error in build() method, line 762 	self._make() while calling '_make', 

### ISSUE THREAD

**Issue by daisyvincent** [openssl/openssl#21542] opened 2023-07-25 03:56 UTC
while building source code , I found the below error. Can you tell the soluction to solve this error. For the building I am using ubuntu20.04,
gstreamer
conan 1.57
cmake 3.13
gcc 9.4
given below the error

openssl/1.1.1i: 
openssl/1.1.1i: ERROR: Package '8faa1e71bc57b8654248632a449b4c6957f7dcd5' build failed
openssl/1.1.1i: WARN: Build folder /home/alexa-auto-sdk-4.0/builder/.builder/.conan/data/openssl/1.1.1i/_/_/build/8faa1e71bc57b8654248632a449b4c6957f7dcd5
ERROR: openssl/1.1.1i: Error in build() method, line 762
	self._make()
while calling '_make', line 684
	self.run('{perl} ./Configure {args}'.format(perl=self._perl, args=args), win_bash=self._win_bash)
	ConanException: Error 1 while executing perl ./Configure "conan-Release-Android-armv8-clang-8" no-shared --prefix="/home/alexa-auto-sdk-4.0/builder/.builder/.conan/data/openssl/1.1.1i/_/_/package/8faa1e71bc57b8654248632a449b4c6957f7dcd5" --openssldir="/home//alexa-auto-sdk-4.0/builder/.builder/.conan/data/openssl/1.1.1i/_/_/package/8faa1e71bc57b8654248632a449b4c6957f7dcd5/res" no-unit-test threads PERL=perl no-tests --release  -D__ANDROID_API__=33 -fPIC no-md2
[BUILDER] ERROR: Command '['conan', 'install', '/home//alexa-auto-sdk-4.0/conan/recipes/aac-sdk-tools', '-if=/tmp/tmpuu1pzmcr', '-b', 'outdated', '-o', 'pkg_modules=aac-module-alexa', '-o', 'aac_version=dev', '-o', 'with_aasb=True', '-o', 'with_unit_tests=False', '-o', 'with_sensitive_logs=False', '-o', 'with_latency_logs=False', '-o', 'with_sampleapp=False', '-o', 'with_docs=True', '-s', 'build_type=Release', '-pr:h=aac-android', '-pr:b=default']' returned non-zero exit status 1.

**Comment by t8m** [comment] 2023-07-25 07:38
Duplicate of #21537

You should report this to conan.

**Closed by t8m** 2023-07-25 07:38 UTC
Labels: issue: bug report
