### ISSUE TITLE
In dtls, a fatal alert is generated when the record type is unknown.

### ISSUE THREAD

**Issue by liwei62** [openssl/openssl#25840] opened 2024-10-31 13:02 UTC
version: 3.0.9

Description

In the DTLS scenario, when OpenSSL receives a packet whose record type is unknown during the handshake, a fatal alert is generated.  I found that it returned -1 when rec_layer_d1.c:741 failed.

Code

https://github.com/openssl/openssl/blob/de90e54bbe82e5be4fb9608b6f5c308bb837d355/ssl/record/rec_layer_d1.c#L739-L771

RFC Reference
As RFC6347 [section-4.1.2.7](https://datatracker.ietf.org/doc/html/rfc6347#section-4.1.2.7): In general, invalid records SHOULD be silently discarded.

> Unlike TLS, DTLS is resilient in the face of invalid records (e.g., invalid formatting, length, MAC, etc.). In general, invalid records SHOULD be silently discarded, thus preserving the association

Question
According to RFC 6347, invalid records SHOULD be silently discarded. Is this a bug?

I look forward to hearing from you. Thanks.

**Comment by mattcaswell** [comment] 2024-10-31 13:37
> According to RFC 6347, invalid records SHOULD be silently discarded. Is this a bug?

Strictly its a SHOULD not a MUST so we are compliant with the RFC. But I tend to think this is an accident rather than by design, so we should probably treat this as a bug.

A PR fixing this would be welcome.

**Comment by tom-cosgrove-arm** [comment] 2024-11-01 07:55
Is this not a duplicate of #25389?

**Comment by t8m** [comment] 2024-11-01 09:42
Duplicate of #25389

**Closed by t8m** 2024-11-01 09:42 UTC
Labels: triaged: bug
