### ISSUE TITLE
TLSv1.3 cipher alias

### ISSUE THREAD

**Issue by moyaldror** [openssl/openssl#4953] opened 2017-12-18 13:02 UTC
TLSv1.3 ciphers are missing from `cipher_aliases`, can it be added?

**Comment by kaduk** [comment] 2017-12-18 21:53
There is some additional discussion at at least https://github.com/openssl/openssl/issues/2276 (and maybe other places).  So, I think some additional justification of need other than "they are missing" would be required before any action would be taken.

**Comment by moyaldror** [comment] 2017-12-23 11:42
The only good justification I see is keeping up with old aliasing - I see no reason why there should be aliases for SSLv3, TLSv1/1.2 but not for TLSv1.3

**Comment by kaduk** [comment] 2017-12-24 04:30
"TLS 1.3 exceptionalism" already holds sway in that there are not dedicated TLS 1.3 method object/functions; this case seems "similar enough" to me that I expect TLS 1.3 exceptionalism to hold sway.

**Comment by mattcaswell** [comment] 2018-01-18 16:34
This is a dupe of #2276. There is more discussion in that issue, so closing this one in favour of it.

**Closed by mattcaswell** 2018-01-18 16:34 UTC
