### ISSUE TITLE
[rt.openssl.org #3936] Bug (maybe) report

### ISSUE THREAD

**Issue by richsalz** [openssl/openssl#2428] opened 2017-02-02 20:28 UTC
Migrated from [rt.openssl.org#3936](https://rt.openssl.org/Ticket/Display.html?id=3936) (status was 'open')

Requestors:
* William.Freeman@dealertrack.com

From william.freeman@dealertrack.com on 2015-07-10 21:02:24:
```
This could be a real bug, a doc bug, or I'm just not getting it.

I'm using "-config" with "openssl req" and "openssl ca" to use an alternate openssl.cnf file.  The command bombs because (being run as non-root) it can't read the default /etc/pki/tls/openssl.cnf file, since it is owned by root and mode 600 (CentOS 6.2, openssl 1.0.1e from RPM), and the command is not being run as root.

My alternate openssl.cnf file is in the current working directory, and I have tried making the -config argument each of "openssl.cnf", "./openssl.cnf", and the full absolute path to the file.  My file is mode 600 and owned by the user running the command and has mode 600.

In no case does it complain of not being able to read my file (but maybe it never gets that far).  It complains of not being able to read the default file.

So, does -config *NOT* suppress reading of the default file (the man page implies that it does)?  Have I missed an option for suppressing it?

Is this a bug, a local installation problem, or could the documentation use improvement.

Here's an example of a failing command:

(imposter)[ imposter@imposter_bill ~/imposter/non-git/CA ]
$ openssl req -config /home/imposter/imposter/non-git/CA/openssl.cnf  -newkey rsa -nodes -keyout localhost.key -out localhost.csr
140615126005576:error:0200100D:system library:fopen:Permission denied:bss_file.c:169:fopen('/etc/pki/tls/openssl.cnf','rb')
140615126005576:error:2006D002:BIO routines:BIO_new_file:system lib:bss_file.c:174:
140615126005576:error:0E078002:configuration file routines:DEF_LOAD:system lib:conf_def.c:199:
(imposter)[ imposter@imposter_bill ~/imposter/non-git/CA ]
$
```

From unknown on 2015-09-09 20:49:34:
```
OpenSSL attempts to load the master/default conf before diving into the
subcommand and overriding the conf with the config in -config. It'll bail when
it can't read the file, but only warn if the file does not exist.

This seems wrong, and is a regression compared to 0.9.8, so I'm going to leave
this ticket open.

Meanwhile, you can work around it by setting the OPENSSL_CONF environment
variable.

Cheers,
Emilia
```

**Comment by levitte** [comment] 2018-05-17 12:06
From a look in master, it seems that we try to load module settings from the default config file regardless, and any file error is treated silently.  *However*, if the file was successfully loaded, but the configuration is somehow wrong (i.e. `CONF_modules_load` fails), *then* `openssl` will bail.

I'll do a quick test to see if I'm right.

**Comment by levitte** [comment] 2018-05-18 08:55
I've just tried the example command on current master, 1.1.0 and 1.0.2 branches.  Cannot reproduce.

Closing this

**Closed by levitte** 2018-05-18 08:55 UTC
