### ISSUE TITLE
How BN_secure_new() works?

### ISSUE THREAD

**Issue by outspace** [openssl/openssl#9622] opened 2019-08-17 19:45 UTC
BN_secure_new() as descripted in [https://github.com/openssl/openssl/blob/master/doc/man3/BN_new.pod](https://github.com/openssl/openssl/blob/master/doc/man3/BN_new.pod) 

> BN_new() allocates and initializes a BIGNUM structure. BN_secure_new() does the same except that the secure heap OPENSSL_secure_malloc(3) is used to store the value. 

But, in [https://github.com/openssl/openssl/blob/master/crypto/bn/bn_lib.c](https://github.com/openssl/openssl/blob/master/crypto/bn/bn_lib.c) I can see that it calls BN_new() and in BN_new() it calls OPENSSL_zalloc()

Is everything ok in code and docs?

**Comment by richsalz** [comment] 2019-08-17 20:26
Yes, everything is right.  The memory allocted for the BN structure is different from the memory allocated for the "string of digits" that make up the *value* of the BN.  Look for uses of ```BN_FLG_SECURE``` in that file.

I think this should be closed.

**Comment by outspace** [comment] 2019-08-17 21:05
Sory my bad, I understad that value allocated in bn_expand_internal() by OPENSSL_secure_zalloc(). But in description it called OPENSSL_secure_malloc(). 

I think it should be closed too.

**Comment by mspncp** [comment] 2019-08-17 23:06
Closing it as requested. (@outspace since you are the owner of the issue you should actually be able to close it yourself?)

**Comment by outspace** [comment] 2019-08-17 23:15
Yes, but link in [https://github.com/openssl/openssl/blob/master/doc/man3/BN_new.pod](https://github.com/openssl/openssl/blob/master/doc/man3/BN_new.pod) is still broken. Maybe you have more info about this memory?

**Comment by richsalz** [comment] 2019-08-17 23:29
The place to view the manpages online is on the openssl website, https://www.openssl.org/docs/manpages.html  Not at github.  The file at github is a *source* file, not an HTML file for the web, so the link doesn't work.

**Comment by outspace** [comment] 2019-08-17 23:32
Is it ok? [https://www.openssl.org/docs/manmaster/man3/BN_new.html](https://www.openssl.org/docs/manmaster/man3/BN_new.html)

**Comment by outspace** [comment] 2019-08-17 23:53
I will explain it to you in detail. In [https://www.openssl.org/docs/manmaster/man3/BN_new.html](https://www.openssl.org/docs/manmaster/man3/BN_new.html) page is missing link to [https://www.openssl.org/docs/manmaster/man3/OPENSSL_secure_malloc.html](https://www.openssl.org/docs/manmaster/man3/OPENSSL_secure_malloc.html).

**Comment by mspncp** [comment] 2019-08-18 09:20
So if I understand you correctly, you are talking about two different things:

- The [BN_new](https://www.openssl.org/docs/manmaster/man3/BN_new.html) entry on the website https://www.openssl.org/docs/manmaster/man3 is a broken link. I just confirmed that (cc @levitte).
- The BN_new(3) manual page should refer to OPENSSL_secure_malloc(3) in its SEE ALSO section.

Is that correct?

**Comment by mspncp** [comment] 2019-08-18 09:22
Note: this is the error I get for https://www.openssl.org/docs/manmaster/man3/BN_new.html:
```
An error occurred while processing your request.
Reference #30.720a1602.1566120050.f1e4779
```

**Comment by outspace** [comment] 2019-08-18 09:52
No, [https://www.openssl.org/docs/manmaster/man3/BN_new.html](https://www.openssl.org/docs/manmaster/man3/BN_new.html) has a broken link.

> BN_secure_new() does the same except that the secure heap **OPENSSL_secure_malloc(3)** is used to store the value.

OPENSSL_secure_malloc(3) need to be a link. 

I agree that we shold add it into SEE ALSO section.

**Comment by richsalz** [comment] 2019-08-18 12:39
See https://github.com/openssl/openssl/pull/9629

The error is because Akamai rejected the connection to openssl because the cert had expired.
(Multiple warnings were given over the past couple of weeks.)

**Closed** 2019-08-19 05:20 UTC
Labels: bug
