### ISSUE TITLE
Error reading S/MIME message on Ubuntu 14.04.5 LTS 

### ISSUE THREAD

**Issue by MikeVelazcoMtz** [openssl/openssl#2038] opened 2016-12-07 16:56 UTC
I'm doing some refactoring over an relatively old utility on my work that uses openssl to get an XML signed with PCKS7 that actually runs over CentOS, but we plan to migrate to Ubuntu. I have been looking for solutions, but almost that I find is about not having enough RAM, but this is not my case (I'm doing this refactor over a Virtual Machine with 2GB of RAM).

The command that I'm running is this:

```
openssl smime -decrypt -verify -inform DER -in "/var/www/LCO/LCO_2016-12-06_2.XML" -noverify -out "/var/www/LCO/US_LCO_2016-12-06_2.XML"

```

And the result is this:

```
Error reading S/MIME message
140637945153184:error:07069041:memory buffer routines:BUF_MEM_grow_clean:malloc failure:buffer.c:159:
140637945153184:error:0D06B041:asn1 encoding routines:ASN1_D2I_READ_BIO:malloc failure:a_d2i_fp.c:239:
```

Actually I'm using Ubuntu 14.04.5 LTS and I've updated my openssl version to OpenSSL 1.0.2j  26 Sep 2016

I've also tried to get information via [ServerFault](http://serverfault.com/questions/819191/openssl-decrypt-file-with-pcks7-signature-not-working-on-ubuntu)

I don't have much experience with openssl but if it is needed more information I'll send as fast as possible any required information.

Thanks.

**Comment by snhenson** [comment] 2016-12-11 14:01
What size is the input message?

**Comment by MikeVelazcoMtz** [comment] 2016-12-12 17:01
I don't know if the question is related to the file or sometihng in the file content so I'm leaving a download link of an exampel file. 

This [example file](https://drive.google.com/file/d/0Bwv6n_dzfk_RVU1PVEVYRzhtWlU/view?usp=sharing) is one of the files that I tried to process.

**Comment by snhenson** [comment] 2016-12-12 21:57
That example file is larger 441MB in size. When the file is initially parsed it can end up consuming at least 2x its size and in some cases considerably more. That's probably the cause of the malloc failure.

**Comment by MikeVelazcoMtz** [comment] 2016-12-12 23:24
If this where the reason, could this work on a CentOS virtual machine with a half of the RAM (1 GB)?

The Ubuntu machine has 2 GB of RAM and it is doing only this.

**Comment by snhenson** [comment] 2016-12-13 00:04
Odd... I tried your message on a virtual machine with 1GB of memory running Ubuntu 12.0.4 and it processes your file fine. Though obviously it takes some time. That is also with OpenSSL 1.0.2.

**Comment by MikeVelazcoMtz** [comment] 2016-12-13 00:46
I don't know if you have tried vagrant before, but I'm using a vagrant box: 

    ubuntu/trusty64  (virtualbox, 20160815.0.0)

and about the setup, I only updated the packages:

    apt-get update
    apt-get upgrade
    sudo apt-get autoremove
    sudo apt-get autoclean

and then installed `git`, `zip`, `nginx`, `PHP`, `ntp` and `ntpdate` via `apt-get`.

**Comment by MikeVelazcoMtz** [comment] 2016-12-20 16:58
Just as an update:

I've got the same error in a AWS Amazon Linux Image:

    Error reading S/MIME message
    139763173406560:error:07069041:memory buffer routines:BUF_MEM_grow_clean:malloc failure:buffer.c:169:
    139763173406560:error:0D06B041:asn1 encoding routines:ASN1_D2I_READ_BIO:malloc failure:a_d2i_fp.c:255:

I ran an `openssl version` and this is what I got:

    OpenSSL 1.0.1k-fips 8 Jan 2015

**Comment by richsalz** [comment] 2016-12-22 18:38
please try a more recent version than 1.0.1, which is EOL very soon.  The VM allocation doesn't matter, there are probably openssl size limits in the openssl version you are using.

**Comment by MikeVelazcoMtz** [comment] 2016-12-22 18:58
Mmm, this is a very strange error, I have been trying to get it to work unsuccessfully on AWS with Amazon AMI, CentOS 6 and 7 and locally with vagrant on Ubuntu.

On AWS, even after updating via package manager I couldn't make it work.

**Comment by richsalz** [comment] 2016-12-22 19:37
the package manager still loads 1.0.1 apparently.  you will have to download and build a new version of openssl yourself.

**Comment by JoeJasinski** [comment] 2017-07-06 16:28
I'm having the same issue with a file greater than 1.6G.  In the machine that I'm doing the decryption, I have 12GB of RAM and 8GB of swap, with plenty free.  I'm on Ubuntu 14.04, however it also doesn't work on Ubuntu 16.04 with the stock openssl version. 

I've also tried compiling from source openssl 1.1.0 and it give the same as above.  The new version *does not* solve this. 

```
/opt/openssl/dist/bin/openssl smime -decrypt -in backup.sql.bz2.enc -binary -inform DEM -inkey backup_key.pem > backup.sql.bz2
Error reading S/MIME message
140499766675264:error:07069041:memory buffer routines:BUF_MEM_grow_clean:malloc failure:crypto/buffer/buffer.c:127:
140499766675264:error:0D06B041:asn1 encoding routines:asn1_d2i_read_bio:malloc failure:crypto/asn1/a_d2i_fp.c:191:
```

These are the compile steps I followed for my custom puild:

```
sudo mkdir -p /opt/openssl
cd /opt/openssl/
sudo wget https://www.openssl.org/source/old/1.1.0/openssl-1.1.0.tar.gz
sudo tar zxvf openssl-1.1.0.tar.gz
cd openssl-1.1.0
sudo ./config --prefix=/opt/openssl/dist/ --openssldir=/opt/openssl/dist/openssldir/
sudo make 
sudo make install
```

**Comment by richsalz** [comment] 2017-07-06 16:34
Can you use the -stream flag and put the text on stdin?

**Comment by imagescape** [comment] 2017-07-07 17:18
@richsalz Thank you for your reply.  If I'm understanding your suggestion correctly, I should refactor the command to look like this? If so, I'm still getting the same error, I think.  For reference, this is the size in bytes of the backup.sql.bz2.enc file: 1651178556

```
cat backup.sql.bz2.enc | /opt/openssl/dist/bin/openssl smime \
    -decrypt -binary -stream -inform DEM \
    -inkey backup_key.pem > backup.sql.bz2
    
Error reading S/MIME message
139994497902400:error:07069041:memory buffer routines:BUF_MEM_grow_clean:malloc failure:crypto/buffer/buffer.c:127:
139994497902400:error:0D06B041:asn1 encoding routines:asn1_d2i_read_bio:malloc failure:crypto/asn1/a_d2i_fp.c:191:
```

**Comment by JoeJasinski** [comment] 2017-07-07 17:20
@richsalz Thank you for your reply.  If I'm understanding your suggestion correctly, I should refactor the command to look like this? If so, I'm still getting the same error, I think.  For reference, this is the size in bytes of the backup.sql.bz2.enc file: 1651178556

```
cat backup.sql.bz2.enc | /opt/openssl/dist/bin/openssl smime \
    -decrypt -binary -stream -inform DEM \
    -inkey backup_key.pem > backup.sql.bz2
    
Error reading S/MIME message
139994497902400:error:07069041:memory buffer routines:BUF_MEM_grow_clean:malloc failure:crypto/buffer/buffer.c:127:
139994497902400:error:0D06B041:asn1 encoding routines:asn1_d2i_read_bio:malloc failure:crypto/asn1/a_d2i_fp.c:191:
```

**Comment by richsalz** [comment] 2017-07-07 17:21
Yes, that’s what I was suggesting.  Your file is around 1.5Gig.  I’m afraid openssl just can’t handle files that big.

**Comment by JoeJasinski** [comment] 2017-07-07 17:27
@richsalz Thanks for confirming that. I guess I'll need to look for an alternative method to encrypt.

**Comment by mattcaswell** [comment] 2018-01-18 16:12
Won't be fixed.

**Closed by mattcaswell** 2018-01-18 16:12 UTC
