### ISSUE TITLE
Invalid TLS CertificateVerify max message length

### ISSUE THREAD

**Issue by maked0n** [openssl/openssl#10267] opened 2019-10-26 11:41 UTC
Currently, `SSL3_MT_CERTIFICATE_VERIFY` message length [is constrained](https://github.com/openssl/openssl/blob/master/ssl/statem/statem_clnt.c#L980) by the `TLSPlaintext` length. However, according to the [standard](https://tools.ietf.org/html/rfc8446#section-4.4.3), the maximum signature length is 65535:
```
struct {
  SignatureScheme algorithm;
  opaque signature<0..2^16-1>;
} CertificateVerify;
```
which is more than is currently allowed. Also, the standard states that

> Handshake messages MAY be coalesced into a single TLSPlaintext record or fragmented across several records

but currently, it seems the only single `TLSPlaintext` record is supported.

**Comment by mattcaswell** [comment] 2019-10-28 10:38
Max message lengths may be less than that defined in the standard. They are there as a simple check to ensure that the peer is not sending us in-feasibly large messages. In practice OpenSSL does not support any signature schemes that could create such a large signature so no handshake that would succeed will be prevented as a result of this check.

**Comment by maked0n** [comment] 2019-10-30 13:59
Thank you for your feedback.

We admit this issue is not a bug. Let me clarify the purpose of this change. We are working on SPHINCS+ algorithm implementation, which is one of the most promising candidates in post-quantum cryptography standards. So, it is likely to be added to the TLS specification in the future, and this constant will have to be changed as well. Can we discuss the possibility of accepting our PR in case we implement the suspiciously-big-message check based on the signature size extracted from SignatureScheme? It seems to be more accurate than using a fixed signature size upper bound.

**Comment by mattcaswell** [comment] 2019-10-30 14:41
> Are there any design considerations and/or other artifacts of such discussions could be read? At this point we are going to design some sort of similar thing as non intrusive as it's possible.

No. It was discussed at our face-2-face meeting last week, but its not progressed further than a discussion item.

**Comment by mkwork** [comment] 2019-10-31 08:41
Is there any chance for us to participate in such discussion(about pluggable signature schemes)? We could match our considerations with yours and sync direction. At the moment we are thinking about 2 approaches , so you could help us to pick most suitable and idiomatic.

**Comment by mattcaswell** [comment] 2019-10-31 10:01
> Is there any chance for us to participate in such discussion(about pluggable signature schemes)? We could match our considerations with yours and sync direction. At the moment we are thinking about 2 approaches , so you could help us to pick most suitable and idiomatic.

Sure. Probably the best way to get involved is to start a discussion on github on the topic by creating a feature request issue. Bear in mind though that the dev team is fully focussed on the 3.0 development at the moment so new features such as this are low down on the priority list.

**Comment by DDvO** [comment] 2020-06-22 06:19
Looks like this can be closed?

**Comment by DDvO** [comment] 2020-06-22 06:29
BTW, this appears to be a duplicate of #6433.

**Comment by mattcaswell** [comment] 2020-06-22 09:46
> Is there any chance for us to participate in such discussion(about pluggable signature schemes)? We could match our considerations with yours and sync direction. At the moment we are thinking about 2 approaches , so you could help us to pick most suitable and idiomatic.

As a note we now have fully pluggable support for key exchange in TLSv1.3:

https://github.com/openssl/openssl/pull/11914

If we were ever to do the same for signatures I expect it to follow a similar pattern and design approach.

> Looks like this can be closed?

Yes

**Closed by mattcaswell** 2020-06-22 09:46 UTC
Labels: resolved: not a bug
