### ISSUE TITLE
Missing OpenSSL license phrase in a Huawei project

### ISSUE THREAD

**Issue by Tianjiao** [openssl/openssl#5464] opened 2018-02-26 04:07 UTC
Hello

A Huawei [project](https://github.com/Huawei/eSDK_eLTE_SDK_Windows) use OpenSSL [here](https://github.com/Huawei/eSDK_eLTE_SDK_Windows/blob/master/third_party/open_src/openssl-1.0.2k/openssl-1.0.2k/LICENSE)

But it does not have license phrase in its [Readme](https://github.com/Huawei/eSDK_eLTE_SDK_Windows/blob/master/README.md) and [doc](https://github.com/Huawei/eSDK_eLTE_SDK_Windows/tree/master/doc) that are used for advertising.

According to the [OpenSSL License](https://github.com/openssl/openssl/blob/master/LICENSE), Point 3, 

> 3. All advertising materials mentioning features or use of this
> software must display the following acknowledgment:
>  "This product includes software developed by the OpenSSL Project
>  for use in the OpenSSL Toolkit. (http://www.openssl.org/)"

Why are they advertising material?
in the README, Huawei uses its brand name "Huawei" for advertising the project, and mentioning its features of the Huawei product.
in the doc, Huawei invites outside developers to join in, in order to promote its product, and include a complete SDK.

**Comment by richsalz** [comment] 2018-02-26 12:52
Basically a duplicate of #5404.  Closing.

**Closed by richsalz** 2018-02-26 12:52 UTC
