### ISSUE TITLE
X509_PUBKEY_cmp() seems incorrect

### ISSUE THREAD

**Issue by vt-alt** [openssl/openssl#11870] opened 2020-05-19 11:21 UTC
There is `static` function `X509_PUBKEY_cmp` used by `OSSL_CRMF_MSGS_verify_popo` in `crypto/crmf/crmf_lib.c"`. I wanted to copy-paste it for some gost-engine tests (since it's not exported), but found it's being strange:
```
/* returns 0 for equal, -1 for a < b or error on a, 1 for a > b or error on b */
static int X509_PUBKEY_cmp(X509_PUBKEY *a, X509_PUBKEY *b)
{
    X509_ALGOR *algA = NULL, *algB = NULL;
    int res = 0;

    if (a == b)
        return 0;
    if (a == NULL || !X509_PUBKEY_get0_param(NULL, NULL, NULL, &algA, a)
            || algA == NULL)
        return -1;
    if (b == NULL || !X509_PUBKEY_get0_param(NULL, NULL, NULL, &algB, b)
            || algB == NULL)
        return 1;
    if ((res = X509_ALGOR_cmp(algA, algB)) != 0)
        return res;
    return EVP_PKEY_cmp(X509_PUBKEY_get0(a), X509_PUBKEY_get0(b));
}
```
It should return 0 if keys match, **but** `EVP_PKEY_cmp` will return 1 if keys match.

Man: `The function EVP_PKEY_cmp_parameters() and EVP_PKEY_cmp() return 1 if the keys match, 0 if they don't match, -1 if the key types are different and -2 if the operation is not supported.`.

**Comment by bernd-edlinger** [comment] 2020-05-19 12:07
Yeah, that makes no sense at all.
Fortunatetly that X509_PUBKEY_cmp is not in the LTS branch.

@DDvO I apologize for not finding this while I was reviewing this
commit, I should not have done that review so quickly  :smile:

**Comment by bernd-edlinger** [comment] 2020-05-19 12:38
Okay, I looked at the original review of this function, and found one
unresolved review comment:
https://github.com/openssl/openssl/pull/7646/files#r234418540
I said "X509_PUBKEY_get0 can return NULL, and EVP_PKEY_cmp does not check for NULL.
That means you have to."
@DDvO said "Done" and I beleived him, and therefore approved.
@mattcaswell said on 11th dec 2018:
 https://github.com/openssl/openssl/pull/7646/files#r240675299
"Done?? I don't see it here?"
And @DDvO answerded:
"

This was done in

commit 413ed461c4edbd0b0ee5ac338361b962776ec8c4
Author: David von Oheimb <David.von.Oheimb@siemens.com>
Date:   Tue Nov 20 22:04:12 2018 +0100

    fix several missing checks for error conditions in crmf_lib.c

(but possibly it was pushed later)."

But this commit hash is nowhere.

**Comment by bernd-edlinger** [comment] 2020-05-19 12:46
Ah, while this commit is not on my local git, github is able to find it,
and it does show a change that checks the return value of
X509_PUBKEY_get0_param for bein non-zero, that was requested by myself earlier,
but my request to check the return value of X509_PUBKEY_get0 was igored.
Please, I still want the return value checked for non-zero, before passing it
on to EVP_PKEY_cmp, and of course make the return value of
X609_PUBKEY_cmp similar as EVP_PKEY_cmp, we do no binary searches
on PUBKEYs anyways.

**Comment by levitte** [comment] 2020-05-19 13:21
*My* first question is, why was `X509_PUBKEY_cmp()` implemented *in the CRMF sub-system*, when all other `X509_PUBKEY` functions are implemented in `crypto/x509/x_pubkey.c`???

**Comment by DDvO** [comment] 2020-05-20 10:09
@vt-alt, the static function `X509_PUBKEY_cmp()` is not to be confused with `EVP_PKEY_cmp()`.
The former is 'documented' only by the comment above it.
Its returns value behavior is different from the one of `EVP_PKEY_cmp()`.
This may be regarded as a design inconsistency, but this is not a bug.

**Comment by DDvO** [comment] 2020-05-20 10:22
> Okay, I looked at the original review of this function, and found one
> unresolved review comment:
> https://github.com/openssl/openssl/pull/7646/files#r234418540
> I said "X509_PUBKEY_get0 can return NULL, and EVP_PKEY_cmp does not check for NULL.
> That means you have to."

@bernd-edlinger, in your review you did not request that the return value behavior of `X509_PUBKEY_cmp()` should be analogous to `EVP_PKEY_cmp()`, so what you brought up above is a different topic.

AFAICS I had misunderstood your review comment. With my 'done' I confirmed that I added checks for `NULL` input of `X509_PUBKEY_cmp()`, but what I did not do (because of the misunderstanding) is to check the potential NULL input in the call of `EVP_PKEY_cmp()` within `X509_PUBKEY_cmp()`.

**Comment by DDvO** [comment] 2020-05-20 10:27
> _My_ first question is, why was `X509_PUBKEY_cmp()` implemented _in the CRMF sub-system_, when all other `X509_PUBKEY` functions are implemented in `crypto/x509/x_pubkey.c`???

@levitte, the local function `X509_PUBKEY_cmp()` so far was just needed for CRMF, and both reviewers were fine with having it in `crmf_lib.c`.

**Comment by DDvO** [comment] 2020-05-20 10:31
I'm going to 
* move `X509_PUBKEY_cmp()` to `crypto/x509/x_pubkey.c`
* add the further `NULL` checks
* make its return values analogous to `EVP_PKEY_cmp()`
* export and document it.

Or @vt-alt what do you think?

**Comment by levitte** [comment] 2020-05-20 10:40
> I'm going to 
> * move `X509_PUBKEY_cmp()` to `crypto/x509/x_pubkey.c`
> * add the further `NULL` checks
> * make its return values analogous to `EVP_PKEY_cmp()`
> * export and document it.

Yes!

**Comment by vt-alt** [comment] 2020-05-20 12:40
> @vt-alt, the static function X509_PUBKEY_cmp() is not to be confused with EVP_PKEY_cmp().

I believe I am not confusing them. And not requesting their return value to be the same. And not saying that difference in their return values is a bug. There is already inconsistency in return values in different _cmp functions which is normal design inconsistency. For example `X509_ALGOR_cmp` and `X509_cmp` returns 0 on match. `EVP_PKEY_cmp` returns 1 on match.

> The former is 'documented' only by the comment above it.
Its returns value behavior is different from the one of EVP_PKEY_cmp().
This may be regarded as a design inconsistency, but this is not a bug.

It doesn't follow 'document' indeed, but not just that.

```
    if (a == b)
        return 0;
```

If both keys match (because they are the same key) it returns 0.

```
    return EVP_PKEY_cmp(X509_PUBKEY_get0(a), X509_PUBKEY_get0(b));
```

If both keys match it returns 1.

In what way this is not a bug?

**Comment by DDvO** [comment] 2020-05-20 13:54
@vt-alt you are right!

I misunderstood your original remark, and it turns out that when implementing `X509_PUBKEY_cmp()` I had wrong assumptions about the return values of the `EVP_PKEY_cmp()` function called.

Sigh, the various `_cmp()` functions are pretty confusing, certainly not only to me.

Do you agree with the solution I proposed?

**Comment by vt-alt** [comment] 2020-05-20 14:21
@DDvO

> move X509_PUBKEY_cmp() to crypto/x509/x_pubkey.c

This sounds good.

> make its return values analogous to EVP_PKEY_cmp()

Probably, this is not needed. All other `X509_*_cmp` seems to return 0 for a match.

Man X509_cmp: `Like common memory comparison functions, the X509 comparison functions return an integer less than, equal to, or greater than zero if object a is found to be less than, to match, or be greater than object b, respectively.`

To change return value similar to `EVP_PKEY_cmp` would only increase confusion.

**Comment by petrovr** [comment] 2020-05-20 18:19
compare or equal ?

So compare is more for cases we would like "sort" results. In this case -1 , 0 or +1 are expected results and error return values does not make sense.
This is more like operators  < or >  .
Example is strcmp.

Request is more suitable for new function X509_PUBKEY_eq - as equal is another case. Function like operator = or !=.

I'm not sure that cmp or eq shout process error cases.
Just to be documented NIL(NULL)  in operations:
- NIL is lest then any value (or greater)
- NIL is equal to NIL



Vitalio wrote:
> @DDvO
>
>> move X509_PUBKEY_cmp() to crypto/x509/x_pubkey.c
> This sounds good.
>
>> make its return values analogous to EVP_PKEY_cmp()
> Probably, this is not needed. All other `X509_*_cmp` seems to return 0 for a match.
>
> Man X509_cmp: `Like common memory comparison functions, the X509 comparison functions return an integer less than, equal to, or greater than zero if object a is found to be less than, to match, or be greater than object b, respectively.`
>
> To change return value similar to `EVP_PKEY_cmp` would only increase confusion.
>
>

**Comment by DDvO** [comment] 2020-05-21 08:47
Good point @petrovr - it's a pity that `EVP_PKEY_cmp()` and `EVP_PKEY_cmp_parameters()` 
are not called  `EVP_PKEY_eq()` and `EVP_PKEY_eq_parameters()`, respectively.

This would avoid a lot confusion and would have .avoided the bug found by @vt-alt.

Fix is now in #11894.

**Comment by beldmit** [comment] 2020-05-21 09:25
> Good point @petrovr - it's a pity that `EVP_PKEY_cmp()` and `EVP_PKEY_cmp_parameters()`
> are not called `EVP_PKEY_eq()` and `EVP_PKEY_eq_parameters()`, respectively.
> 
> This would avoid a lot confusion and would have .avoided the bug found by @vt-alt.

Isn't it worth introducing these renaming here and now, altogether with deprecating the old ones as misleading?

**Comment by DDvO** [comment] 2020-05-24 16:45
> > Good point @petrovr - it's a pity that `EVP_PKEY_cmp()` and `EVP_PKEY_cmp_parameters()`
> > are not called `EVP_PKEY_eq()` and `EVP_PKEY_eq_parameters()`, respectively.
> > This would avoid a lot confusion and would have .avoided the bug found by @vt-alt.
> 
> Isn't it worth introducing these renaming here and now, altogether with deprecating the old ones as misleading?

I fully agree and am willing to do that. 
How to do this best?
Can I rename for instance `EVP_PKEY_cmp()` to `EVP_PKEY_eq()` and add a `#define for backward compatibility?

**Comment by t8m** [comment] 2020-05-25 09:56
> How to do this best?
> Can I rename for instance `EVP_PKEY_cmp()` to `EVP_PKEY_eq()` and add a `#define for backward compatibility?

If you do that the define should be within the `#ifndef OPENSSL_NO_DEPRECATED_3_0`. Or you can even do `EVP_PKEY_cmp()` as a thin wrapper function - that has an advantage of producing deprecated warnings if used in the code.

**Comment by bernd-edlinger** [comment] 2020-05-25 11:19
We do currently not have any exported XXX_eq functions, right?

**Comment by DDvO** [comment] 2020-05-25 11:21
@t8m, done on #11953

**Comment by DDvO** [comment] 2020-05-25 11:21
> We do currently not have any exported XXX_eq functions, right?

Correct.

**Comment by bernd-edlinger** [comment] 2020-05-25 11:22
And how many of the currently expoerted _cmp functions return
-1 for "less" and +1 for "greater" ?

**Comment by bernd-edlinger** [comment] 2020-05-25 11:31
for inatance,
EC_POINT_cmp returns 0 for equal +1 for non-equal -1 for error.
would you like everybody to rename that to EC_POINT_eq in their code?

**Comment by DDvO** [comment] 2020-05-25 11:43
The point of the above discussed rename of `EVP_PKEY_cmp{,_parameters}` to `*_eq()` was to avoid in the future the confusion that lead to this bug report because there have been two different semantics for `*_cmp` functions: equality and order comparison.
Likely more functions are affected, such as the `EC_POINT_eq()` you just mentioned.
We could/should rename those as well, both for consistency and for avoiding the same confusion.

The proposed change does not force anyone to rename their function uses because this is handled by backward compatibility declarations.

**Comment by t8m** [comment] 2020-05-25 11:57
The difference between EVP_PKEY_cmp and EC_POINT_cmp is that the first one returns 1 for equal where the second returns 0 for equal. So no, EC_POINT_cmp does not need to be renamed.

But there is also EVP_PKEY_cmp_parameters, which has the same semantics as EVP_PKEY_cmp and so it should be probably renamed as well.

**Comment by bernd-edlinger** [comment] 2020-05-25 11:57
But even X509_cmp is an exception, and in that case I made the mistake
to believe it is supposed to return -1, 0, +1 but instead it returns the result
of memcmp if it is non-zero, and that should be fixed as well.

**Comment by t8m** [comment] 2020-05-25 11:59
I do not think it makes sense to rename _cmp functions that return 0 for equality. And (hopefully) there are not many more than the EVP_PKEY_cmp* that return 1 for equality.

**Comment by DDvO** [comment] 2020-05-25 12:03
> But there is also EVP_PKEY_cmp_parameters, which has the same semantics as EVP_PKEY_cmp and so it should be probably renamed as well.

#11953 already does that.

**Closed** 2020-05-26 07:48 UTC
Labels: issue: bug report
