### ISSUE TITLE
DSA key generation does not work as expected

### ISSUE THREAD

**Issue by Hlipa** [openssl/openssl#19846] opened 2022-12-06 10:41 UTC
When DSA parameters P, Q and G are know following code for DSA generation does not work:

```
gctx = EVP_PKEY_CTX_new_from_name(NULL, "DSA", NULL);                    
EVP_PKEY_keygen_init(gctx);                                              

params[0] = OSSL_PARAM_construct_BN("p", P, sizeof (P));                 
params[1] = OSSL_PARAM_construct_BN("q", Q, sizeof (Q));                 
params[2] = OSSL_PARAM_construct_BN("g", G, sizeof (G));                          
params[3] = OSSL_PARAM_construct_end();                                  
EVP_PKEY_CTX_set_params(gctx, params);                                   
EVP_PKEY_generate(gctx, &key);
```
which is similar to RSA key generation.

From truss output of dsa_gen():
```
/1@1:           -> libcrypto:BN_GENCB_new(0x10016c6f0, 0x0, 0x0, 0x0)
/1@1:             -> libcrypto:__sparc_get_pc_thunk.l7(0x18, 0xffffffffffc57db0, 0x3c9, 0x0)
/1@1:             <- libcrypto:__sparc_get_pc_thunk.l7() = 24
/1@1:             -> libcrypto:CRYPTO_malloc(0x18, 0xfffffff9fae43db0, 0x3c9, 0x0)
/1@1:               -> libcrypto:__sparc_get_pc_thunk.l7(0x0, 0x0, 0x0, 0x0)
/1@1:               <- libcrypto:__sparc_get_pc_thunk.l7() = 0
/1@1:             <- libcrypto:CRYPTO_malloc() = 0x1001690d0
/1@1:           <- libcrypto:BN_GENCB_new() = 0x1001690d0
/1@1:           -> libcrypto:BN_GENCB_set(0x1001690d0, 0xfffffff9fb0c82e0, 0x100163ec0, 0x0)
/1@1:           <- libcrypto:BN_GENCB_set() = 0x1001690d0
/1@1:           -> libcrypto:ossl_dsa_get0_params(0x10016c6f0, 0xfffffff9fb0c82e0, 0x100163ec0, 0x0)
/1@1:           <- libcrypto:ossl_dsa_get0_params() = 0x10016c6f8
/1@1:           -> libcrypto:ossl_ffc_params_enable_flags(0x10016c6f8, 0x4, 0x1, 0x0)
/1@1:           <- libcrypto:ossl_ffc_params_enable_flags() = 0x10016c6f8
/1@1:           -> libcrypto:DSA_free(0x10016c6f0, 0x3, 0x1, 0x0)
```
It seems that `gctx->ffc_params` is not set and function finally fails without any reported error.

Only possible way which I found is to use param key to initialize context properly:
```
...
EVP_PKEY_fromdata(pctx, &param_key, EVP_PKEY_KEY_PARAMETERS, params);
gctx = EVP_PKEY_CTX_new_from_pkey(NULL, param_key, NULL);
EVP_PKEY_keygen_init(gctx);
EVP_PKEY_generate(gctx, &key);
```

I also created documentation bug #19845

**Comment by t8m** [comment] 2022-12-06 10:57
Actually the first way is not supposed to work. The correct way is the second one.

This makes it basically a duplicate of the documentation issues #19845.

**Comment by t8m** [comment] 2022-12-06 10:57
Duplicate of #19845

**Closed by t8m** 2022-12-06 10:57 UTC
Labels: issue: bug report

**Comment by Hlipa** [comment] 2022-12-06 12:04
It would be good to add at least some ERR_raise("DSA params are not set."... or something like that to dsa_gen().
