### ISSUE TITLE
Master fails to compile on Apple Silicon M2 (AARCH64)

### ISSUE THREAD

**Issue by mouse07410** [openssl/openssl#21876] opened 2023-08-28 15:36 UTC
Apple Silicon M2 computer running MacOS 13.5.1 with Xcode-14.3.1. OpenSSL - current master.

`perl configdata.pm --dump`:
[configdata.dump.txt](https://github.com/openssl/openssl/files/12455651/configdata.dump.txt)

Apparent error:
```text
clang  -Icrypto -I. -Iinclude -Iproviders/common/include -Iproviders/implementations/include  -DBSAES_ASM -DECP_NISTZ256_ASM -DECP_SM2P256_ASM -DKECCAK1600_ASM -DMD5_ASM -DOPENSSL_BN_ASM_MONT -DOPENSSL_CPUID_OBJ -DOPENSSL_SM3_ASM -DPOLY1305_ASM -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DSM4_ASM -DVPAES_ASM -DVPSM4_ASM -fPIC -arch arm64 -O3 -std=gnu18 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -I//Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include -g -DL_ENDIAN -DOPENSSL_PIC -DOPENSSLDIR="\"/Users/ur20980/openssl-3/etc\"" -DENGINESDIR="\"/Users/ur20980/openssl-3/lib/engines-3\"" -DMODULESDIR="\"/Users/ur20980/openssl-3/lib/ossl-modules\"" -D_REENTRANT -DOPENSSL_BUILDING_OPENSSL -DZLIB -DZLIB_SHARED  -c -o crypto/ec/libcrypto-lib-ecp_sm2p256-armv8.o crypto/ec/ecp_sm2p256-armv8.S
clang: error: no such file or directory: 'crypto/ec/ecp_sm2p256-armv8.S'
clang: error: no input files
make[1]: *** [crypto/ec/libcrypto-lib-ecp_sm2p256-armv8.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [tests] Error 2
```
In the build log there seems a problem with generating the appropriate .S file...

Complete build log: [make-out.txt](https://github.com/openssl/openssl/files/12455672/make-out.txt)
Log of failed "make test" (obviously fails because the build failed): [test-out.txt](https://github.com/openssl/openssl/files/12455979/test-out.txt)

**Comment by t8m** [comment] 2023-08-28 16:29
This is practically a duplicate of #21874 however the log is slightly different so I am keeping this.

However it is totally unclear to me why this would fail when the nistz assembler works fine.

@levitte any idea?

**Comment by tom-cosgrove-arm** [comment] 2023-08-28 18:38
I've not been able to replicate this on either M1 or M2 systems. I did do a `make clean` before re-running the `Configure` before `make`

**Comment by mouse07410** [comment] 2023-08-28 20:05
I confirm that #21877 fixes this problem. Let's hope it's merged soon.

**Closed** 2023-08-31 07:43 UTC
Labels: branch: master, help wanted, triaged: bug
