### ISSUE TITLE
Build issue with some perl versions

### ISSUE THREAD

**Issue by bernd-edlinger** [openssl/openssl#21172] opened 2023-06-10 17:37 UTC
Looks like due to #20935 the build process breaks
at least with some old perl versions:
```
$ ./config 
Configuring OpenSSL version 3.2.0-dev for target linux-x86_64
Using os-specific seed configuration
Created configdata.pm
Running configdata.pm
Created Makefile.in
Created Makefile
Created include/openssl/configuration.h

**********************************************************************
***                                                                ***
***   OpenSSL has been successfully configured                     ***
***                                                                ***
***   If you encounter a problem while building, please open an    ***
***   issue on GitHub <https://github.com/openssl/openssl/issues>  ***
***   and include the output from the following command:           ***
***                                                                ***
***       perl configdata.pm --dump                                ***
***                                                                ***
***   (If you are new to OpenSSL, you might want to consult the    ***
***   'Troubleshooting' section in the INSTALL.md file first)      ***
***                                                                ***
**********************************************************************
$ make
/usr/bin/perl "-I." "-Iutil/perl" "-Mconfigdata" "-MOpenSSL::paramnames" "util/dofile.pl" "-oMakefile" crypto/params_idx.c.in > crypto/params_idx.c
"my" variable $trieref masks earlier declaration in same scope at /home/ed/ossl/openssl/util/perl/OpenSSL/paramnames.pm line 640.
syntax error at /home/ed/ossl/openssl/util/perl/OpenSSL/paramnames.pm line 582, near "$cursor{"
Global symbol "$cursor" requires explicit package name at /home/ed/ossl/openssl/util/perl/OpenSSL/paramnames.pm line 584.
Global symbol "%trie" requires explicit package name at /home/ed/ossl/openssl/util/perl/OpenSSL/paramnames.pm line 588.
syntax error at /home/ed/ossl/openssl/util/perl/OpenSSL/paramnames.pm line 589, near "}"
syntax error at /home/ed/ossl/openssl/util/perl/OpenSSL/paramnames.pm line 636, near "}"
syntax error at /home/ed/ossl/openssl/util/perl/OpenSSL/paramnames.pm line 662, near "}"
syntax error at /home/ed/ossl/openssl/util/perl/OpenSSL/paramnames.pm line 673, near "}"
Compilation failed in require.
BEGIN failed--compilation aborted.
make: *** [crypto/params_idx.c] Error 255
$ perl -version

This is perl 5, version 18, subversion 2 (v5.18.2) built for x86_64-linux-gnu-thread-multi
(with 55 registered patches, see perl -V for more detail)

Copyright 1987-2013, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.
```

... but according to this statement
https://github.com/openssl/openssl/blob/8a2e74d0536c91585fbe789e0ab7b06cab0289c2/NOTES-PERL.md?plain=1#L28-L30
perl versions up to 5.10.0 should be supported

**Comment by h-vetinari** [comment] 2023-06-11 02:53
OTOH, the minimum perl version hasn't been raised since at least 7 years: https://github.com/openssl/openssl/commit/de8128203a5340db397dadaee91bc504c2a539bc. And Perl [5.10.0](https://github.com/Perl/perl5/releases/tag/perl-5.10.0) is over 15 years old. Even for an extremely generous 10 years of support, the minimum could already be [5.19.0](https://github.com/Perl/perl5/releases/tag/v5.19.0).

**Comment by XboxOneSogie720** [comment] 2023-06-11 04:22
@h-vetinari I'm on perl version 5.18.4 but still got the error.

**Comment by levitte** [comment] 2023-06-11 19:43
Duplicate of #21152

**Closed** 2023-06-12 06:03 UTC
Labels: issue: bug report
