### ISSUE TITLE
"perl Configure" fails due to folder names

### ISSUE THREAD

**Issue by ExeVirus** [openssl/openssl#13221] opened 2020-10-22 16:20 UTC
For the latest version of openssl 1.1.1x as of today:

Perl has a weird quirk that needs to be mentioned in Notes.win for future users. Perl, specifically strawberry perl, will fail to properly execute "perl Configure" when the folder structure to your openssl folder is something like:

> C:/project-master@74gf8/openssl

The **@** symbol above causes perl to fail to generate the makefile for nmake properly, and gives meaningless errors (i.e. they don't point you to the folder structure). 

**Please consider adding a line to Notes.Win** specifying that folder names mustn't include the @ symbol for perl to work properly (and likely other symbols, I did not test this out with others).

**Comment by levitte** [comment] 2020-10-23 00:53
Duplicate of #12743
Duplicate of #12078

**Comment by levitte** [comment] 2020-10-23 00:54
Thank you for pointing out Strawberry, that gave me something to test.

**Comment by levitte** [comment] 2020-10-23 01:09
I have a tentative fix in #13225, would you mind trying it?

**Closed** 2020-10-27 09:18 UTC
Labels: issue: documentation
