### ISSUE TITLE
s_client’s DANE output shall output ALL valid TLSA records

### ISSUE THREAD

**Issue by dilyanpalauzov** [openssl/openssl#10167] opened 2019-10-13 22:04 UTC
With openssl 1.1.1, calling `openssl s_client -connect mail.aegee.org:443 -dane_tlsa_domain mail.aegee.org -dane_tlsa_rrdata "3 0 1 8D0DCD94935ADB548FF9F8A925DF56B675DADF5747DC94EC6BA2717A 1BBAE6AA" -dane_tlsa_rrdata "3 0 2 D60882F6B5704C7C1060EA84133BD176F718EA029414C51BE2B683F3 D3693C3F069902719C555E5DF3D1945860344B4AE81A515D6B31BC65CBF6312AA7301AAF"  -dane_tlsa_rrdata "3 0 1 EFCA5A28E2471521AE355EE23FAA3C13A1285612BCEFE1B0653A296C 4F3AFDB9" -dane_tlsa_rrdata "3 0 2 27671DAD85AFA2C97656BFFA2D5F60457A9C376F60AD9ABD7896D5C4 CF645DC76F04454900867F330833BD06582 7B8F54A6FDC63A2BB34D6 7FBBF1778581A389"` prints:
```
Peer signature type: ECDSA
Server Temp Key: ECDH, P-384, 384 bits
---
SSL handshake has read 2932 bytes and written 777 bytes
Verification: OK
Verified peername: mail.aegee.org
DANE TLSA 3 0 2 ...a2bb34d67fbbf1778581a389 matched EE certificate at depth 0
---
```
When I remove from the command line the last 9 and execute again, the output is:
```
Peer signature type: ECDSA
Server Temp Key: ECDH, P-384, 384 bits
---
SSL handshake has read 2931 bytes and written 777 bytes
Verification error: No matching DANE TLSA records
```
If I remove both 3 0 2 records, and call
`openssl s_client -connect mail.aegee.org:443 -dane_tlsa_domain mail.aegee.org -dane_tlsa_rrdata "3 0 1 8D0DCD94935ADB548FF9F8A925DF56B675DADF5747DC94EC6BA2717A 1BBAE6AA"` then the output is:
```
Peer signature type: ECDSA
Server Temp Key: ECDH, P-384, 384 bits
---
SSL handshake has read 2932 bytes and written 777 bytes
Verification: OK
Verified peername: mail.aegee.org
DANE TLSA 3 0 1 ...47dc94ec6ba2717a1bbae6aa matched EE certificate at depth 0
```

Since the original call contained a valid 3 0 2 TLSA record and valid 3 0 1 TLSA record, `openssl s_client` shall report two valid records, so that its output can be feeded in monitoring tools.

So the output should have been:
```
Peer signature type: ECDSA
Server Temp Key: ECDH, P-384, 384 bits
---
SSL handshake has read 2932 bytes and written 777 bytes
Verification: OK
Verified peername: mail.aegee.org
DANE TLSA 3 0 2 ...a2bb34d67fbbf1778581a389 matched EE certificate at depth 0
DANE TLSA 3 0 1 ...47dc94ec6ba2717a1bbae6aa matched EE certificate at depth 0
```

**Comment by mattcaswell** [comment] 2019-12-05 15:09
Ping @vdukhovni.

**Comment by dilyanpalauzov** [comment] 2019-12-05 15:55
In the meantime I changed my mind.  If 3 0 1 and 3 0 2 are present, then only the SHA512 hash shall be verified.  But if 3 1 1 and 3 0 1 records are present, s_client shall evaluate both of them.

**Comment by vdukhovni** [comment] 2019-12-05 18:24
To test which TLSA records work, and which don't run the command with each TLSA record one at a time.  By design, on success the X.509 chain validation code records only one matching TLSA record, which is either for the EE certificate (3 X X) or the most proximate (least depth) issuing CA.

To report all matching TLSA records, the application would have to construct an unauthenticated TLS connection, and then iterate the TLSA records using each one in turn to validate the certificates provided by the client. That would be a major change for s_client. Testing each record in isolation is simpler also in terms of getting a machine-readable exit code, rather than attempting to parse the output format, which is not set in stone...

**Comment by vdukhovni** [comment] 2019-12-05 18:28
I'm inclined to close this issue, unless there's interest in restructuring s_client to do multiple post-handshake chain validation calls (perhaps only when there are multiple TLSA records provided and at least one succeeded).

**Comment by dilyanpalauzov** [comment] 2019-12-06 03:36
The rationale is for a site publishing different types of TLSA records, that monitoring software can validate more than one of them by a sungle call.

If a site has EC+RSA certificates and for each of them has 3 1 1 and 3 0 1 TLSA records, monitoring for the validity of all of these combinations is four calls.

I am not going to do restructuring in openssl.

**Comment by vdukhovni** [comment] 2019-12-06 04:55
> If a site has EC+RSA certificates and for each of them has 3 1 1 and 3 0 1 TLSA records, monitoring for the validity of all of these combinations is four calls.

* Firstly, you never need both `3 0 1` and `3 1 1` records, just DNS packet bloat that is always best to avoid.
* Secondly, when you do happen to have multiple `3 1 1` records to check, one call for each does not seem unreasonable to me.

Finally, there are projects outside of OpenSSL that are specifically intended to implement DANE monitoring, and you could try one of those.
https://github.com/baknu/DANE-for-SMTP/wiki/2.-Implementation-resources

**Comment by dilyanpalauzov** [comment] 2019-12-10 21:48
I agree that one TLSA record per certificate is sufficient.

I have not asked for one call be per each 3 1 1 record, but rather one call for all 3 1 1 records, one call with all 3 0 1 records and one call for all 3 0 2 records.

**Closed** 2019-12-10 21:49 UTC
Labels: resolved: not a bug
