### ISSUE TITLE
Can we have support for ARM64EC platform?

### ISSUE THREAD

**Issue by RashmiRamanna4** [openssl/openssl#25738] opened 2024-10-18 17:14 UTC
We would really appreciate if Openssl provides support for ARM64EC platform. We are adding support for ARM64EC platform in our product and we rely on Openssl and it would be great if we can get the support ARM64EC platform

**Comment by tom-cosgrove-arm** [comment] 2024-10-19 14:08
This looks like a duplicate of #16482

**Comment by paulidale** [comment] 2024-10-20 21:32
Closing this as a duplicate.  Making the original as not "inactive" since there is clearly still interest.

**Closed by paulidale** 2024-10-20 21:32 UTC
Labels: issue: feature request
