### ISSUE TITLE
EVP_DecryptUpdate overwrites my data (tested with 1.0.2)

### ISSUE THREAD

**Issue by sergworks** [openssl/openssl#6498] opened 2018-06-16 08:08 UTC
Tested with AES cipher in ECB mode with padding.

If `EVP_DecryptUpdate` is called "inplace" (`out` and `in` buffers are the same) 2 times, the second `EVP_DecryptUpdate` call overwrites the first block (16 bytes) of my `in` buffer _before_ decryption. As a result the decryption is incorrect. Here is the log of encrypting/decrypting 50-byte plaintext with 2 "inplace" `EVP_DecryptUpdate` calls:
```
Version: OpenSSL 1.0.2o  27 Mar 2018
Version number: 100020FF

Encrypted after 1st Update: 32
Encrypted after 2nd Update: 16
Encrypted after Final: 16
Encrypted Size: 64
Decrypted after 1st Update: 16
Decrypted after 2nd Update: 32
Decrypted after Final: 2
Decrypted Size: 50
Key:
01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F 10
PlainText:
00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F 10 11 12 13 14 15 16 17 18 19 1A 1B 1C 1D 1E 1F 20 21 22 23 24 25 26 27 28 29 2A 2B 2C 2D 2E 2F 30 31
Encrypted:
6F 0A 9F FF CB 98 DF 4F 74 25 F7 3D 09 BB DD FB 66 B4 06 9C B2 E5 3D B1 09 80 8B 31 D3 EE DE B5 21 69 48 11 ED 19 09 B8 21 FE D1 4C 1C 0C 9A C9 85 12 CA F0 CE 75 4C 75 49 31 A4 D5 A9 E0 34 F9
Decrypted:
00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F 10 11 12 13 14 15 16 17 18 19 1A 1B 1C 1D 1E 1F 86 60 B6 9A B4 72 17 41 97 C8 7D F2 EC A8 F8 B3 30 31
```
The erroneous `86 60 B6 9A B4 72 17 41 97 C8 7D F2 EC A8 F8 B3` decrypted block comes from decrypting `10, 11, 12, ..., 1F` block.

The test code is written in Delphi and included below. I was using 32-bit libeay32.dll downloaded from https://indy.fulgan.com/SSL/ , but the issue is 100% understandable and reproducible and unlikely related to the details.

I am encrypting 50-byte plaintext and then decrypting back the 64-byte ciphertext using 32-byte work buffer. The encryption is correct (checked with independent AES implementation) but the decryption is wrong (in one 16-byte block). The error is caused by the 2nd call of `EVP_DecryptUpdate` overwriting the first 16 bytes in my work buffer _before_ decryption. `EVP_DecryptUpdate` does not take into account that the output buffer is the same as the input buffer and should not be overwritten _before_ decryption.
```
program OSSLTest;

{$APPTYPE CONSOLE}

{$R *.res}

uses
  SysUtils, Windows;

const
  LibCryptoName = 'libeay32.dll';

var
  LibHandle: THandle;
  LibVersion: UInt32;

type
  PEVP_CIPHER_CTX = type Pointer;
  PEVP_CIPHER = type Pointer;

const
  _SSLEAY_VERSION = 0;

type
// OpenSSL version API
  TSSLeay = function: Cardinal; cdecl;
  TSSLeay_version = function(AType: Integer): PAnsiChar; cdecl;

// OpenSSL EVP API
  TEVP_CIPHER_CTX_new = function(): PEVP_CIPHER_CTX; cdecl;
  TEVP_CIPHER_CTX_reset = function(CTX: PEVP_CIPHER_CTX): Integer; cdecl;
  TEVP_CIPHER_CTX_free = procedure(CTX: PEVP_CIPHER_CTX); cdecl;

  TEVP_CipherInit = function(CTX: PEVP_CIPHER_CTX; EVP_CIPHER: PEVP_CIPHER;
         Impl: Pointer; Key, IV: PByte): Integer; cdecl;
  TEVP_CipherUpdate = function(CTX: PEVP_CIPHER_CTX; OutBuf: PByte;
         var OutBufLen: Integer; InBuf: PByte; InBufLen: Integer): Integer; cdecl;
  TEVP_CipherFinal = function(CTX: PEVP_CIPHER_CTX; OutBuf: PByte;
         var OutBufLen: Integer): Integer; cdecl;

  TEVP_CIPHER_CTX_set_padding = function(CTX: PEVP_CIPHER_CTX;
         Padding: Integer): Integer; cdecl;

  TGetEVPCipher = function(): PEVP_CIPHER; cdecl;

var
  SSLeay: TSSLeay;
  SSLeay_version: TSSLeay_version;

  EVP_CIPHER_CTX_new: TEVP_CIPHER_CTX_new;
  EVP_CIPHER_CTX_init: TEVP_CIPHER_CTX_reset;
  EVP_CIPHER_CTX_free: TEVP_CIPHER_CTX_free;

  EVP_EncryptInit_ex: TEVP_CipherInit;
  EVP_EncryptUpdate: TEVP_CipherUpdate;
  EVP_EncryptFinal_ex: TEVP_CipherFinal;

  EVP_DecryptInit_ex: TEVP_CipherInit;
  EVP_DecryptUpdate: TEVP_CipherUpdate;
  EVP_DecryptFinal_ex: TEVP_CipherFinal;

  EVP_CIPHER_CTX_set_padding: TEVP_CIPHER_CTX_set_padding;

  EVP_aes_128_ecb: TGetEVPCipher;

procedure LoadFunction(var Address: Pointer; const Name: string);
begin
  Address:= GetProcAddress(LibHandle, PChar(Name));
  if (Address = nil) then
    raise Exception.Create('Error Loading Function ' + Name);
end;

procedure LoadLibCrypto(const FolderName: string = '');
begin
  if (FolderName = '') then begin
    LibHandle:= LoadLibrary(PChar(libCryptoName));
  end
  else begin
    LibHandle:= LoadLibrary(PChar(IncludeTrailingPathDelimiter(FolderName) +  libCryptoName));
  end;

  if (LibHandle = 0) then
    raise Exception.Create('Error Loading ' + LibCryptoName);

  LoadFunction(@SSLeay, 'SSLeay');
  LoadFunction(@SSLeay_version, 'SSLeay_version');
  LoadFunction(@EVP_CIPHER_CTX_new, 'EVP_CIPHER_CTX_new');
//
// !! ver 1.1.0 replaced 'EVP_CIPHER_CTX_init' by 'EVP_CIPHER_CTX_reset'
//    from evp.h:
//  #  define EVP_CIPHER_CTX_init(c)      EVP_CIPHER_CTX_reset(c)
//  #  define EVP_CIPHER_CTX_cleanup(c)   EVP_CIPHER_CTX_reset(c)
//  but ver 1.1.0 libeay32.dll still exports
//     'EVP_CIPHER_CTX_init' and 'EVP_CIPHER_CTX_cleanup'
//  so no changes are needed
//
  LoadFunction(@EVP_CIPHER_CTX_init, 'EVP_CIPHER_CTX_init');
  LoadFunction(@EVP_CIPHER_CTX_free, 'EVP_CIPHER_CTX_free');
  LoadFunction(@EVP_EncryptInit_ex, 'EVP_EncryptInit_ex');
  LoadFunction(@EVP_EncryptUpdate, 'EVP_EncryptUpdate');
  LoadFunction(@EVP_EncryptFinal_ex, 'EVP_EncryptFinal_ex');
  LoadFunction(@EVP_DecryptInit_ex, 'EVP_DecryptInit_ex');
  LoadFunction(@EVP_DecryptUpdate, 'EVP_DecryptUpdate');
  LoadFunction(@EVP_DecryptFinal_ex, 'EVP_DecryptFinal_ex');
  LoadFunction(@EVP_CIPHER_CTX_set_padding, 'EVP_CIPHER_CTX_set_padding');
  LoadFunction(@EVP_aes_128_ecb, 'EVP_aes_128_ecb');

  Writeln('Version: ', string(SSLeay_version(_SSLEAY_VERSION)));
  Writeln('Version number: ',  IntToHex(SSLeay(), 8));
  Writeln;
end;

var
  Key: array[0..15] of Byte;
  IV: array[0..15] of Byte; // IV is not used in ECB
  PlainText: array of Byte;
  Encrypted: array of Byte;
  Decrypted: array of Byte;
  WorkBuffer: array of Byte;

procedure Prepare;
var
  I: Integer;

begin
  for I:= 0 to 15 do
    Key[I]:= I + 1;
  SetLength(PlainText, 50);
  for I:= 0 to Length(PlainText) - 1 do
    PlainText[I]:= I;
  SetLength(Encrypted, 64);
  SetLength(Decrypted, 64);
  SetLength(WorkBuffer, 32 + 16);
end;

procedure TestEncryption;
var
  Ctx: PEVP_CIPHER_CTX;
  L1, L2, L3: Integer;

begin

// create encryption context
  Ctx:= EVP_CIPHER_CTX_new();

// initialize encryption context with AES cipher, ecb, 128 bit key
  if EVP_EncryptInit_ex(Ctx, EVP_aes_128_ecb(), nil, @Key[0], @IV[0]) <> 1 then
    raise Exception.Create('EVP_EncryptInit_ex Error');

// encrypt first 32 bytes of plaintext
  Move(Plaintext[0], WorkBuffer[0], 32);
  if EVP_EncryptUpdate(Ctx, @WorkBuffer[0], L1, @WorkBuffer[0], 32) <> 1 then
    raise Exception.Create('EVP_EncryptUpdate Error');

  Writeln('Encrypted after 1st Update: ', L1);
  Move(WorkBuffer[0], Encrypted[0], L1);

// encrypt last 18 bytes of plaintext
  Move(Plaintext[32], WorkBuffer[0], 18);
  if EVP_EncryptUpdate(Ctx, @WorkBuffer[0], L2, @WorkBuffer[0], 18) <> 1 then
    raise Exception.Create('EVP_EncryptUpdate Error');

  Writeln('Encrypted after 2nd Update: ', L2);
  Move(WorkBuffer[0], Encrypted[L1], L2);

  if EVP_EncryptFinal_ex(Ctx, @WorkBuffer[L2], L3) <> 1 then
    raise Exception.Create('EVP_EncryptFinal_ex Error');

  Writeln('Encrypted after Final: ', L3);
  Move(WorkBuffer[L2], Encrypted[L1 + L2], L3);

  Writeln('Encrypted Size: ', L1 + L2 + L3);

// release encryption context
  EVP_CIPHER_CTX_free(Ctx);
end;

procedure TestDecryption;
var
  Ctx: PEVP_CIPHER_CTX;
  L1, L2, L3: Integer;

begin

// create decryption context
  Ctx:= EVP_CIPHER_CTX_new();

// initialize decryption context with AES cipher, 128 bit key
  if EVP_DecryptInit_ex(Ctx, EVP_aes_128_ecb(), nil, @Key[0], @IV[0]) <> 1 then
    raise Exception.Create('EVP_DecryptInit_ex Error');

// decrypt first 32 bytes of ciphertext
  Move(Encrypted[0], WorkBuffer[0], 32);
  if EVP_DecryptUpdate(Ctx, @WorkBuffer[0], L1, @WorkBuffer[0], 32) <> 1 then
    raise Exception.Create('EVP_DecryptUpdate Error');

  Writeln('Decrypted after 1st Update: ', L1);
  Move(WorkBuffer[0], Decrypted[0], L1);

// decrypt last 32 bytes of ciphertext
  Move(Encrypted[32], WorkBuffer[0], 32);
  if EVP_DecryptUpdate(Ctx, @WorkBuffer[0], L2, @WorkBuffer[0], 32) <> 1 then
    raise Exception.Create('EVP_EncryptUpdate Error');

  Writeln('Decrypted after 2nd Update: ', L2);
  Move(WorkBuffer[0], Decrypted[L1], L2);

  if EVP_DecryptFinal_ex(Ctx, @WorkBuffer[L2], L3) <> 1 then
    raise Exception.Create('EVP_EncryptFinal_ex Error');

  Writeln('Decrypted after Final: ', L3);
  Move(WorkBuffer[L2], Decrypted[L1 + L2], L3);

  Writeln('Decrypted Size: ', L1 + L2 + L3);

// release encryption context
  EVP_CIPHER_CTX_free(Ctx);
end;

procedure PrintResults;
var
  I: Integer;

begin
  Writeln('Key: ');
  for I:= 0 to 15 do
    Write(IntToHex(Key[I], 2), ' ');
  Writeln;
  Writeln('PlainText: ');
  for I:= 0 to Length(PlainText) - 1 do
    Write(IntToHex(PlainText[I], 2), ' ');
  Writeln;
  Writeln('Encrypted: ');
  for I:= 0 to Length(Encrypted) - 1 do
    Write(IntToHex(Encrypted[I], 2), ' ');
  Writeln;
  Writeln('Decrypted: ');
  for I:= 0 to 50 - 1 do
    Write(IntToHex(Decrypted[I], 2), ' ');
  Writeln;
end;

begin
  try
    LoadLibCrypto;
    Prepare;
    TestEncryption;
    TestDecryption;
    PrintResults;
  except
    on E: Exception do
      Writeln(E.ClassName, ': ', E.Message);
  end;
  Readln;
end.
```

**Comment by kroeckx** [comment] 2018-06-16 09:19
I guess this is sort of expected behaviour in case the previous
call had outlen != inlen.

I think your call to EVP_DecryptFinal_ex() with @WorkBuffer[L2] is
probably also wrong, L2 being 32, you seem to ask to write after
the end of your buffer. You should probably change that to
@WorkBuffer[0].

You probably shouldn't be using ECB mode, and you probably should
use an IV.

**Comment by sergworks** [comment] 2018-06-16 13:41
@kroeckx Writing after the end of buffer in EVP_DecryptFinal_ex() is indeed a bug;  debugging memory manager has shown that the problem is not solved by using @WorkBuffer[0] but is solved by allocating additional 16 bytes for the WorkBuffer (used for decryption only; mentioned in EVP_DecryptUpdate manual https://www.openssl.org/docs/man1.0.2/crypto/EVP_DecryptUpdate.html ). I have updated the code to make it free from memory errors.

Unfortunately this not related to the issue.

**Comment by sergworks** [comment] 2018-06-16 23:09
Got it finally. The 2nd `EVP_DecryptUpdate` call in the example should be
```
// decrypt last 32 bytes of ciphertext
  Move(Encrypted[32], WorkBuffer[16], 32);
  if EVP_DecryptUpdate(Ctx, @WorkBuffer[0], L2, @WorkBuffer[16], 32) <> 1 then
    raise Exception.Create('EVP_DecryptUpdate Error');
```
so that `WorkBuffer[0..15]` can be written by `EVP_DecryptUpdate` without overwriting my data. Yet another reason why `WorkBuffer` size should be `32+16`.

It was not easy to guess, but there is some logic in the workaround. Still need to meditate more on `EVP_DecryptUpdate` and test the workaround in the real code.

**Comment by mspncp** [comment] 2018-06-17 07:55
> EVP_DecryptUpdate does not take into account that the output buffer is the same as the input buffer

You bring it to the point at the very beginning: the EVP functions are _not_ intended to be used inplace. There is no indication in the manual page that inplace encryption is supported, so why do you think this should work? Your final "workaround" only fixes your problem because now the input and output area of the WorkBuffer are far enough apart  (32 bytes).

```
// decrypt last 32 bytes of ciphertext
  Move(Encrypted[32], WorkBuffer[16], 32);
  if EVP_DecryptUpdate(Ctx, @WorkBuffer[0], L2, @WorkBuffer[16], 32) <> 1 then
    raise Exception.Create('EVP_DecryptUpdate Error');
```

The correct solution to your problem is to use different input and output buffers. Also, there is no need for you to split the buffer in chunks. You can pass the entire buffer in one call, because `EVP_DecryptUpdate()` handles splitting internally. Only if you encrypt a large file which you don't want to read into memory in one chunk you will be using the feature that you can call `EVP_DecryptUpdate()` in a loop.

> You probably shouldn't be using ECB mode, and you probably should use an IV.

To make @kroeckx's statement even more clear: **don't use ECB mode in production code. This mode is unsafe**, it exists solely for the didactical reason to explain [why you shouldn't use ECB mode](https://en.wikipedia.org/wiki/Block_cipher_mode_of_operation#Electronic_Codebook_(ECB)).


Closing this, because it's not an OpenSSL issue. If you need further assistence please consider posting your questions to the [openssl-users](https://mta.openssl.org/mailman/listinfo/openssl-users) mailing list.

**Closed by mspncp** 2018-06-17 07:55 UTC

**Comment by mspncp** [comment] 2018-06-17 08:14
Postscript: I just found out that in version 1.1.0 an explicit check was added to forbid overlapping buffers, see c3a73daf0acc1272905db954b92a23146aad82f0.

**Comment by sergworks** [comment] 2018-06-17 08:51
Partially overlapped buffers **must** be supported in `EVP_DecryptUpdate`, otherwise you will loose important functionality - inplace decryption. As for `EVP_EncryptUpdate`, probably identical buffers are enough for inplace encryption.

Please don't tell about ECB mode, I learned cryptography. ECB mode is used in the code because it is 'a must'  for testing.

**Comment by kroeckx** [comment] 2018-06-17 09:03
As far as I know, it should support identical buffer, but does not
support partially overlapping buffers. But I guess there are some
other rules you need follow for it to really work, which really
should be documented. For instance, only if you decrypt the whole
thing in 1 call.

I expect that it will always keep the last block cached, because
it doesn't know if it's the final block or not, and so needs to
process padding or not.

**Comment by dot-asm** [comment] 2018-06-17 10:20
> EVP_EncryptUpdate(ctx, out, &outl, inp++, 1);

Just in case, it's not like it has to be 1, any number would do. 1 is chosen exclusively to make example as simple as possible.

**Comment by ceztko** [comment] 2020-10-07 10:25
In my opinion, the whole problem with `EVP_DecryptUpdate` and people trying to use it with overlapped in/out buffers is that this API is problematic and ignores how modern programming works nowadays: the requirement of having `outlen` to be `inlen + cipher block size` (where cipher block size is poor 16 bytes most of the times) is basically forcing people to add buffer bloat in all the cases where they have no control over size of the output buffer, example where they have to implement interfaces like `read(buffer, buffersize)` and they can't force consumers of this interface to have enough big buffer, also because externally there could be further buffering, and licit cases where buffersize is less than cipher block size.

A clean API would would **not** require the user to allocate the poor 16 bytes, which is an  implementation detail of the cipher algorithm, as part of an **user** data output buffer. A clean API would instead require first to allocate an instance specific cipher context with the implementation specific 16 bytes there, and let the size of user data output buffer to be free, with the requirement of using the instanced context and not global objects.

Since openssl is often criticized because of API quality I will consider this as an API defect. Also because the `EVP_DecryptUpdate` API is ubiquitous and openssl devs seems to be happy with that I am not expecting this defect to be addressed any time soon.

**Comment by ceztko** [comment] 2020-10-07 10:35
To be fair: it's possible of course that the requirement of `outlen` to be `inlen + cipher block size` allows for some optimizations in the cipher algorithm. But if this forces the API user to add buffer bloat externally then the advantage of the optimizations is somehow lost.
