### ISSUE TITLE
Install fail OS X El Capitan

### ISSUE THREAD

**Issue by ChrisCalderon** [openssl/openssl#486] opened 2015-11-26 00:23 UTC
Configured with `./Configure darwin64-x86_64-cc` . `make` runs without issue, as does `make test`.
Running `sudo make install` fails here:
```
cp: include/openssl/asn1_mac.h: No such file or directory
make: *** [install_sw] Error 1
```

This is on the master branch using commit 6938c954b072c1ddddeb0ec9f6a151df0d2cd925.

**Comment by mattcaswell** [comment] 2015-11-26 12:13
This is caused by having previously built an older release version of OpenSSL in the same directory as master. The older releases created links in "include/openssl" (and also in the test sub-dir), whilst master actually stores the files in those locations. If a file is additionally deleted from master (as in the case of asn1_mac.h) then the link doesn't get overwritten with the file and a bad link remains which confuses "make install".

You can reset the files back to a "pristine" condition by running "git clean -x -d -f" (warning this will delete any non committed work-in-progress files that git doesn't already know about). Alternatively you can just delete the links manually.

**Closed by mattcaswell** 2015-11-26 12:13 UTC
