### ISSUE TITLE
Uninitalization considered harmful

### ISSUE THREAD

**Issue by nicowilliams** [openssl/openssl#654] opened 2016-02-10 21:50 UTC
Viktor prods me to comment on this in relation to rt 3824 https://rt.openssl.org/Ticket/Display.html?id=3824.  This is also related to #653.

Explicit finalization is dangerous (if it does anything at all anyways).

The problem that arises is this: when one calls something like `C_Finalize()` (from PKCS#11), but unbeknownst to the caller there are other users of the library in the same process using the same library, the result is surely undefined or similar.  Since OpenSSL is a library that is used by libraries (not just programs), and we have applications that load many libraries, this problem really does arise.

One could count initializations and finalize only when the count drops to zero.  But this would have to be thread-safe: a last finalization racing with a new initialization must not fail.

The simplest thing to do is to just not have an explicit finalizer.  Finalization on unload would be nice, but as discussed in #653, that's not really possible.  Finalization on process exit time via `atexit()` is much more feasible.

As to valgrind, Dr. Memory, and similar memory debuggers, perhaps OpenSSL should include a suppressions file if it must leak.  But first investigate using `atexit()`.

**Comment by mattcaswell** [comment] 2016-02-10 22:03
FYI, the new auto deinit code already uses atexit().

**Comment by mattcaswell** [comment] 2016-02-10 22:15
What happens to the atexit() handler if the shared object providing the handler gets unloaded (or is that sufficient to ensure that it doesn't get unloaded?) Or do we need to do the trick you outline in #653 to make sure we don't get unloaded?

**Comment by nicowilliams** [comment] 2016-02-10 22:16
@mattcaswell Good.  But is there an explicit deinit function?  I believe such a thing should be documented as only safe to use from monolythic (non-layered) programs, and preferably not at all -- preferably there should be no such function!

**Comment by nicowilliams** [comment] 2016-02-10 22:24
@mattcaswell Well, a sufficiently smart C library could remove `atexit()` handlers when the objects providing them get unloaded.  But there's no guarantee of this.  I don't know that any C library is that smart, though we could check -- but I'm very pessimistic, and if it's just not documented, we can't rely on it anyways.

The same is much harder to do for thread-specific destructors because `libdl` and `libpthread` may be quite separate.  (This really is a mistake.  Both, `libdl` and `libpthread` should be part of the C library, either because that's how it is or because they can rendez-vous and cooperate with each other.  Solaris' and Illumos' C library integrates both.)  In any case, POSIX does not say that the two must cooperate.

**Comment by nicowilliams** [comment] 2016-02-10 22:25
I.e., I think we must do the `dladdr()` + `dlopen()` + leak the object handle.

**Comment by mattcaswell** [comment] 2016-02-10 22:40
There is an explicit deinit - OPENSSL_cleanup(). Documented here:
https://www.openssl.org/docs/manmaster/crypto/OPENSSL_init_crypto.html

The current documentation says this:

The OPENSSL_cleanup() function deinitialises OpenSSL (both libcrypto and libssl). All resources allocated by OpenSSL are freed. Typically there should be no need to call this function directly as it is initiated automatically on application exit. This is done via the standard C library atexit function. In the event that the application will close in a manner that will not call the registered atexit() handlers then the application should call OPENSSL_cleanup() directly. Developers of libraries using OpenSSL are discouraged from calling this function and should instead, typically, rely on auto-deinitialisation. This is to avoid error conditions where both an application and a library it depends on both use OpenSSL, and the library deinitialises it before the application has finished using it.

**Comment by nicowilliams** [comment] 2016-02-10 22:50
Process termination that elides `atexit` handlers probably shouldn't involve calling deinit functions either...  I mean, if you're calling `_exit()` (or `kill(getpid(), <signal that will kill>)`), there's probably a reason, and you might not be happy to first call functions that aren't async-signal-safe, which OPENSSL_cleanup() might not be (I've not looked).  Of course, that's up to the caller, but if one wants to valgrind a test that involves abnormal termination then the best thing to do _IMO_ is to just suppress those leaks that are of no interest, or even to not check for leaks in that particular case.

Zero leaks on exit seems to me to be a bit of a fetish.  Don't get me wrong, I work towards zero-leaks-at-exit in projects I maintain (e.g., https://github.com/stedolan/jq, https://github.com/heimdal/heimdal), but there's a limit to how hard one ought to push that.

For something like OpenSSL, the first-order bit is to cleanup sensitive memory, but that probably should happen well before exit-time on long-running processes anyways, so it shouldn't be something that happens by calling a global deinit function.

**Comment by nicowilliams** [comment] 2016-02-10 22:57
I.e., s/should/might/ in the doc you quoted.  And whether `OPENSSL_cleanup()` is async-signal-safe ought to be documented.

**Comment by richsalz** [comment] 2016-02-24 21:52
so can we close this now?

**Comment by noloader** [comment] 2016-03-11 23:05
> As to valgrind, Dr. Memory, and similar memory debuggers, perhaps OpenSSL should include a suppressions file if it must leak. But first investigate using atexit().

Part of the problem is Java, .Net and similar. They load and unload the OpenSSL library multiple times, and it creates a unbounded memory leak that grows larger over time.

**Comment by kroeckx** [comment] 2016-03-11 23:29
On Fri, Mar 11, 2016 at 03:05:17PM -0800, Jeffrey Walton wrote:
> Part of the problem is Java, .Net and similar. They load and unload the OpenSSL library multiple times, and it creates a unbounded memory leak that grows larger over time.

What is leaking in that case and why?

**Comment by drbo** [comment] 2016-05-10 04:56
I think that the answer is to not allow OpenSSL to be unloaded.  The only way unloading would be practical would be if OpenSSL did not establish thread-local variables with destructors.

**Comment by mattcaswell** [comment] 2016-05-31 21:23
My testing indicated that the atexit() handlers get called on unload (see https://github.com/openssl/openssl/issues/653#issuecomment-206343347). We have discouraged explicit deinit in the docs. I'm thinking this should be closed now.

**Closed by mattcaswell** 2016-05-31 21:23 UTC
