### ISSUE TITLE
openssl creates empty private key file, overwriting existing file, when no file should be created

### ISSUE THREAD

**Issue by davidedelvento** [openssl/openssl#904] opened 2016-03-21 16:59 UTC
I'm running `OpenSSL 1.0.1f 6 Jan 2014` (sorry that's what my freshly installed latest and greatest Linux distro provides), and I've stumbled on this issue. I think a much saner behavior would be to not touch the privateKey.pem file until the import password is verified:

```
davide@somewhere /tmp/openssl $ ls
xxx.p12
davide@somewhere /tmp/openssl $ openssl pkcs12 -in xxx.p12 -nocerts -out privateKey.pem
Enter Import Password: <wrong password typed here>
Mac verify error: invalid password?
davide@somewhere /tmp/openssl $ ls -l
total 4
-rw-r--r-- 1 ddvento ddvento    0 Mar 21 10:50 privateKey.pem
-rw-r--r-- 1 ddvento ddvento 3272 Mar 21 10:49 xxx.p12
davide@somewhere /tmp/openssl $ echo somedata > privateKey.pem 
davide@somewhere /tmp/openssl $ ls -l
total 8
-rw-r--r-- 1 ddvento ddvento    9 Mar 21 10:50 privateKey.pem
-rw-r--r-- 1 ddvento ddvento 3272 Mar 21 10:49 xxx.p12
davide@somewhere /tmp/openssl $ openssl pkcs12 -in xxx.p12 -nocerts -out privateKey.pem
Enter Import Password:  <wrong password typed here>
Mac verify error: invalid password?
davide@somewhere /tmp/openssl $ ls -l
total 4
-rw-r--r-- 1 ddvento ddvento    0 Mar 21 10:50 privateKey.pem
-rw-r--r-- 1 ddvento ddvento 3272 Mar 21 10:49 xxx.p12
```

**Comment by mattcaswell** [comment] 2016-08-26 17:26
Verified that this impacts 1.1.0 and 1.0.2

**Comment by richsalz** [comment] 2016-08-26 19:31
And if it left the old file alone, wouldn't the user be confused thinking that it worked and try to use that file, which exists but is now wrong?

**Comment by mattcaswell** [comment] 2016-08-26 19:34
I don't understand your point? Do you mean the input file? That is always left untouched. This is about the output file, i.e. it shouldn't create an empty output file if the command fails. It just shouldn't create anything.

**Comment by richsalz** [comment] 2016-08-26 21:36
No, I mean the output file.  I think creating a zero-length output file on error is not necessarily wrong for the reasons I wrote above.

**Comment by vdukhovni** [comment] 2016-08-26 22:34
No, the problem is not clobbering the output file, that's mostly. That is I would not be surprised by similar behaviour of "openssl cmd ... > outfile" and "openssl cmd -out outfile".

Rather the main problem is not noticing and reporting an error.

Indeed delaying the file truncation with "-out" makes no sense for just some specific command, when all the others also clobber the file before failing to process the input:
```
    $ echo Test > foo
    $ echo foo | openssl x509 -out foo
    unable to load certificate
    140735268352000:error:0906D06C:PEM routines:PEM_read_bio:no start line:../openssl/crypto/pem/pem_lib.c:691:Expect
ing: TRUSTED CERTIFICATE
    $ cat foo
    $
```
If we're going to do "just-in-time" file overwrites, it should be done across the board.

**Comment by zapstar** [comment] 2017-09-26 18:57
I agree with @mattcaswell on this. It is usually a good practice not to touch the output file until we have the result and the only job left is to write to the disk. For ex: tcpdump does not overwrite the capture file if the interface name is wrong.

I got bit by this bug recently. As @vdukhovni says this needs to be fixed across the board.

Seeing that this thread hasn't been updated for more than a year, I'm assuming that nobody's working on this. I can attempt to fix this, if you folks think this is a relatively small change. It would be my first time digging into OpenSSL source code, so fingers crossed.

**Comment by mattcaswell** [comment] 2017-09-27 08:12
@zapstar, not looked at the source for this so I don't know how big or otherwise the change is. But feel free to give it a go (please include "Fixes #904" in the commit message).

**Comment by zapstar** [comment] 2017-09-27 17:38
@mattcaswell , I'm suspecting that we'll need a lot changes (see grep output below - contains read opens as well). Would you folks be open for changes in so many places? From what I noticed in the source code, the changes would only be needed in the `apps` folder.

I have two approaches in mind, haven't yet decided what will fit in nicely:

1. Open the file at the last minute, that would involve moving the `bio_open_*` as close to the writing part as possible.
2. Open the file with `r+` or `rb+` and just before the first write do a truncate.

Do suggest if you have any other ideas.

Also, it would be good if you can point me to the committer(s) who usually deal with command line apps, we can pull them into this discussion as well.

```
$ grep bio_open *
apps.c:    in = bio_open_default(filename, 'r', FORMAT_TEXT);
apps.c:    in = bio_open_default_quiet(filename, 'r', FORMAT_TEXT);
apps.c:        cert = bio_open_default(file, 'r', format);
apps.c:    in = bio_open_default(infile, 'r', format);
apps.c:        key = bio_open_default(file, 'r', format);
apps.c:        key = bio_open_default(file, 'r', format);
apps.c:    bio = bio_open_default(file, 'r', FORMAT_PEM);
apps.c:BIO *bio_open_owner(const char *filename, int format, int private)
apps.c:        return bio_open_default(filename, 'w', format);
apps.c:static BIO *bio_open_default_(const char *filename, char mode, int format,
apps.c:BIO *bio_open_default(const char *filename, char mode, int format)
apps.c:    return bio_open_default_(filename, mode, format, 0);
apps.c:BIO *bio_open_default_quiet(const char *filename, char mode, int format)
apps.c:    return bio_open_default_(filename, mode, format, 1);
apps.h:BIO *bio_open_owner(const char *filename, int format, int private);
apps.h:BIO *bio_open_default(const char *filename, char mode, int format);
apps.h:BIO *bio_open_default_quiet(const char *filename, char mode, int format);
asn1pars.c:        in = bio_open_default(oidfile, 'r', FORMAT_TEXT);
asn1pars.c:    if ((in = bio_open_default(infile, 'r', informat)) == NULL)
asn1pars.c:    if (derfile && (derout = bio_open_default(derfile, 'w', FORMAT_ASN1)) == NULL)
ca.c:        Sout = bio_open_default(outfile, 'w', FORMAT_TEXT);
cms.c:    in = bio_open_default(infile, 'r', informat);
cms.c:    out = bio_open_default(outfile, 'w', outformat);
crl.c:    out = bio_open_default(outfile, 'w', outformat);
crl2p7.c:        in = bio_open_default(infile, 'r', informat);
crl2p7.c:    out = bio_open_default(outfile, 'w', outformat);
dgst.c:    out = bio_open_default(outfile, 'w', out_bin ? FORMAT_BINARY : FORMAT_TEXT);
dhparam.c:        in = bio_open_default(infile, 'r', informat);
dhparam.c:    out = bio_open_default(outfile, 'w', outformat);
dsa.c:    out = bio_open_owner(outfile, outformat, private);
dsaparam.c:    in = bio_open_default(infile, 'r', informat);
dsaparam.c:    out = bio_open_owner(outfile, outformat, private);
ec.c:        in = bio_open_default(infile, 'r', informat);
ec.c:    out = bio_open_owner(outfile, outformat, private);
ecparam.c:    in = bio_open_default(infile, 'r', informat);
ecparam.c:    out = bio_open_owner(outfile, outformat, private);
enc.c:            in = bio_open_default(opt_arg(), 'r', FORMAT_TEXT);
enc.c:        in = bio_open_default(infile, 'r', informat);
enc.c:    out = bio_open_default(outfile, 'w', outformat);
gendsa.c:    in = bio_open_default(dsaparams, 'r', FORMAT_PEM);
gendsa.c:    out = bio_open_owner(outfile, FORMAT_PEM, private);
genpkey.c:    out = bio_open_owner(outfile, outformat, private);
genrsa.c:    out = bio_open_owner(outfile, FORMAT_PEM, private);
nseq.c:    in = bio_open_default(infile, 'r', FORMAT_PEM);
nseq.c:    out = bio_open_default(outfile, 'w', FORMAT_PEM);
ocsp.c:    out = bio_open_default(outfile, 'w', FORMAT_TEXT);
ocsp.c:        derbio = bio_open_default(reqin, 'r', FORMAT_ASN1);
ocsp.c:        derbio = bio_open_default(reqout, 'w', FORMAT_ASN1);
ocsp.c:        derbio = bio_open_default(respin, 'r', FORMAT_ASN1);
ocsp.c:        derbio = bio_open_default(respout, 'w', FORMAT_ASN1);
passwd.c:         * bio_open_default() will give us back an alias for stdin.
passwd.c:        in = bio_open_default(infile, 'r', FORMAT_TEXT);
pkcs12.c:        out = bio_open_owner(outfile, FORMAT_PKCS12, private);
pkcs12.c:    in = bio_open_default(infile, 'r', FORMAT_PKCS12);
pkcs12.c:    out = bio_open_owner(outfile, FORMAT_PEM, private);
pkcs7.c:    in = bio_open_default(infile, 'r', informat);
pkcs7.c:    out = bio_open_default(outfile, 'w', outformat);
pkcs8.c:    in = bio_open_default(infile, 'r', informat);
pkcs8.c:    out = bio_open_owner(outfile, outformat, private);
pkey.c:    out = bio_open_owner(outfile, outformat, private);
pkeyparam.c:    in = bio_open_default(infile, 'r', FORMAT_PEM);
pkeyparam.c:    out = bio_open_default(outfile, 'w', FORMAT_PEM);
pkeyutl.c:        in = bio_open_default(infile, 'r', FORMAT_BINARY);
pkeyutl.c:    out = bio_open_default(outfile, 'w', FORMAT_BINARY);
rand.c:    out = bio_open_default(outfile, 'w', format);
req.c:        out = bio_open_owner(keyout, outformat, private);
req.c:        in = bio_open_default(infile, 'r', informat);
req.c:    out = bio_open_default(outfile,
rsa.c:    out = bio_open_owner(outfile, outformat, private);
rsautl.c:    in = bio_open_default(infile, 'r', FORMAT_BINARY);
rsautl.c:    out = bio_open_default(outfile, 'w', FORMAT_BINARY);
s_server.c:        BIO *derbio = bio_open_default(srctx->respin, 'r', FORMAT_ASN1);
sess_id.c:        out = bio_open_default(outfile, 'w', outformat);
sess_id.c:    in = bio_open_default(infile, 'r', format);
smime.c:    in = bio_open_default(infile, 'r', informat);
smime.c:    out = bio_open_default(outfile, 'w', outformat);
spkac.c:        out = bio_open_default(outfile, 'w', FORMAT_TEXT);
spkac.c:    out = bio_open_default(outfile, 'w', FORMAT_TEXT);
storeutl.c:    out = bio_open_default(outfile, 'w', FORMAT_TEXT);
ts.c:        if ((in_bio = bio_open_default(in, 'r', FORMAT_ASN1)) == NULL)
ts.c:            && (data_bio = bio_open_default(data, 'r', FORMAT_ASN1)) == NULL)
ts.c:        if ((out_bio = bio_open_default(out, 'w', FORMAT_TEXT)) == NULL)
ts.c:        if ((out_bio = bio_open_default(out, 'w', FORMAT_ASN1)) == NULL)
ts.c:        if ((out_bio = bio_open_default(out, 'w', FORMAT_TEXT)) == NULL)
ts.c:        if ((out_bio = bio_open_default(out, 'w', FORMAT_ASN1)) == NULL)
x509.c:    out = bio_open_default(outfile, 'w', outformat);
x509.c:        in = bio_open_default(infile, 'r', informat);
```

**Comment by mattcaswell** [comment] 2017-09-27 18:45
All the committers deal with the apps - we don't tend to specialise along those lines.

**Comment by paulidale** [comment] 2017-09-28 23:08
Using a temporary file might make it easier to support AEAD ciphers in the `enc` command.  It becomes possible to discard output on failure without the recipient ever seeing any of it.

**Comment by levitte** [comment] 2017-09-29 08:22
Temporary files might be a good idea...  unless the output goes to stdout.

Second best would be to move the openings for write further down the code, I think.

Re-opening with `r+` or `rb+` would be last resort, methinks...  I fear their functionality may be platform dependent...

**Comment by zapstar** [comment] 2017-09-29 10:46
I was browsing the apps code, @paulidale there are not just `bio_open_default`, but some `BIO_new_file` calls with `w` as well. I agree with @levitte, rewriting them to open them with 'r+' should be our last resort, even I had portability concerns.

From the comments above folks are leaning towards the temporary file approach. Here are the ones I would consider implementing:

**Approach 1:** As BIOs just wrap the `FILE` pointers, we could open a `tmpfile` and do a `BIO_new_fp` instead of actually opening the file with `w` in `bio_open_default`. The one dirty thing about this is we'll have to store the file name passed in some global variable. By introducing a new close function we can check if this global variable is not NULL and then copy the contents of the temporary file onto the actual file before closing. Note that this approach assumes that apps are single threaded.

**Approach 2:** Introduce a new mode of opening BIOs for apps, let's say `write on close`. We do the same thing above, but the information for the temporary file is stored on the BIO itself. This will need changing the BIO structure (probably add a field for temporary files in the BIO or a wrapper on top of the BIO structure with an extra field to hold the temporary filename). But keeping track whether it was a close after success/failure is a challenge (maybe look at the SSL error stack?).

Any other approaches?

**Comment by levitte** [comment] 2017-09-29 11:53
We should probably review the calls of `BIO_new_file`, it's quite possible they can be made into `bio_open_default`.  Doesn't have to be all of them, I believe a majority of them are fairly pecial cases...

Re the proposed approaches: it wouldn't be too hard to make a specialised apps specific filter BIO that stores away the file name and mode on "open" and only really opens it on the first read or write.  This would then be used on top of the usual `BIO_s_file`.  Or this filter BIO could write to a temporary file and then rename / copy that file on the real destination when it gets freed.

**Comment by paulidale** [comment] 2017-10-02 22:52
Could we get away with a rename on close option for BIO file's?
Write to a temporary and replace what was there on close.
Delete the temporary on error (when told to rather).

**Comment by richsalz** [comment] 2017-10-02 23:32
oooh, rename on close seems like a neat idea!

**Comment by paulidale** [comment] 2017-10-04 01:46
I'll see if I can think up with a clean way to allow file BIO's to use a temporary file with a rename on write.
For AEAD cipher support in enc, we'll need a buffer to temporary file BIO even if the output is going to a pipe or similar.

**Comment by levitte** [comment] 2017-10-04 08:43
Implement it as a filter BIO, is my recommendation

**Comment by richsalz** [comment] 2017-10-04 12:10
Or perhaps a new API, since I think it will make the use easier (only have to do it in one place)
```
BIO *BIO_new_file_temp(const char *name);
```
and then this passes everything to the FILE bio, except on close it does the rename.

**Comment by zapstar** [comment] 2017-10-04 12:56
@richsalz I agree with you about creating a new API, that would clearly let reader know that this is not the exact BIO call as `BIO_new_file`.

@levitte, can you please expand on filter BIO? I'm a bit new and the only place I notice the word you mention is when folks are using BIO as a linked list. Maybe I'm missing something fundamental here?

There's another super-hacky way of extending a BIO. Any thoughts?
```
/* Only for apps */
typedef struct bio_st_app {
    BIO bio_int;
    char *tempname;
} BIO_app;

...
#define flags bio_int.flags
...

/* Finally */
#define BIO_app BIO
```
This will work only if you don't have name clashes. Let's say we have another structure which also declares `flags`, then this is going to mess things up. This would not need much code changes. This could have been much cleaner if compilers supported the anonymous structure composition which came in C11.

Both the temporary file and the rename and close approach have their drawbacks. We should take the below in consideration before making a move on either.

If let's say the user is encrypting a large file, then writing into a temporary file and then copying the contents again onto the actual file in the end can cause space problems + we'll be taking a performance hit.

With rename on close, the only drawback I see is if we developers muck something up and the binary crashes, we cannot clean it up nicely. Notice that the temporary file does not suffer from this problem as the file would get deleted as soon as the OS cleans up the process (i.d.k if this is true for Windows as well, *nix delete the file as soon as they create a temp file). What kind of security implications are we talking about if we don't clean up properly?

**Comment by levitte** [comment] 2017-10-04 13:56
I disagree with adding to the BIO API for something that can be made as a filter BIO. That's an already existing, and very flexible mechanism.

For examples, have a look at `crypto/bio/bf_*.c`

**Comment by richsalz** [comment] 2017-10-04 14:03
I am confused -- doesn't adding a new filter add a new BIO API?  I must be missing something.  Are you saying write a filter only in the apps, so we don't need to document it?

**Comment by mattcaswell** [comment] 2017-10-04 14:11
> I am confused -- doesn't adding a new filter add a new BIO API?

Nope. It can be entirely contained within and local to the apps. E.g see:

https://github.com/openssl/openssl/blob/master/apps/s_server.c#L307

**Comment by richsalz** [comment] 2017-10-04 14:18
Aha, thanks.  I think the concept would be generally useful, tho, and worth adding the API.

**Comment by paulidale** [comment] 2017-10-04 21:29
BIO filter was the way I was thinking.  A clog and cache everything bio with release of data/rename of file when completed.

Another item for the list.

**Comment by paulidale** [comment] 2017-10-10 04:57
I'm wondering if a sink BIO might be more appropriate for this?

It would be possible to have a filter BIO that buffers to a temporary file and have a file BIO as the sink in the chain.  Delaying the set file name call (on the file BIO) will prevent overwrite but it will involve a complete copy not a rename.  I guess the filter could be given the final file name so it can use a rename but then it's not a filter really.

Forgetting to delay the set file name will also be painful because the output file will be truncated early even with a filter to file buffer in the chain.

**Comment by levitte** [comment] 2017-10-10 07:15
You don't quite know how powerful the BIO API is, I believe.  Consider this code:

```
    BIO *sink = BIO_new(BIO_s_file());
    BIO *filter = BIO_new(BIO_f_temp());  /* example name */
    BIO *out = BIO_push(sink, filter);

    /*
     * In this call, the filter gets the filename first, with the BIO_C_SET_FILENAME control.  At this point
     * it can do whatever it wants with it, its only obligation is to call BIO_ctrl for the next BIO in the stack
     * when it's done.  In our case, that's presumably with another, temporary, file name.
     */
    BIO_write_filename(out, "whatever.pem");

    /* ... work work work work work ... */

    /*
     * So here, the filter's destroy function should first call BIO_free(b->next_bio), and then rename the
     * temproary file name to the original one before freeing itself.  Done deal.
     * The unusual thing is making this an internal BIO_free_all().  That's ok, though...
     */
    BIO_free(out);
```

This could be coded in two functions, one to open the output file and one to close it.  This is *much* easier work than essentially duplicating an existing sink.  Remember that we're talking about an apps specific filter, not something we're aiming at making public.

**Comment by paulidale** [comment] 2017-10-11 00:39
Thanks for the clarification, I see what I'd missed now.  I was overthinking the problem as usual.

**Comment by paulidale** [comment] 2018-03-20 03:53
Apologies @kaduk I missed the question.  Given how long files have been obliterated on failure, I don't see that it is urgent.

The work required amounts to a bio filter that outputs to a file bio using a temporary name.  On close (flush), the file bio is first closed and then rename called (it is either a system call or macro that's defined in apps/apps.c).  @levitte gave a good description above - there might be some fiddling when the chain is destroyed.

**Comment by InfoHunter** [comment] 2018-03-20 14:11
I am confused with this example given by @levitte : 

```
    BIO *sink = BIO_new(BIO_s_file());
    BIO *filter = BIO_new(BIO_f_temp());  /* example name */
    BIO *out = BIO_push(sink, filter);
```

Should it be: `BIO *out = BIO_push(filter, sink);` to let the filter have the data for writing first instead of  data reaching sink first?

**Comment by paulidale** [comment] 2018-03-20 22:28
I suspect this will depend on how it is set up.  The filter could be content never seeing any data and by placing it after the sink, it gets to rename after close.  It still has to fudge the filename.  It isn't how I'd have ordered things...

**Comment by InfoHunter** [comment] 2018-03-21 02:31
You mean someone needs to call BIO_free_all() to trigger the "destroyer" of the filter BIO? Because from my understandings, this is the only way to involve the filter BIO if it's placed after the sink, or do I misunderstand something about BIO mechanism?

**Comment by paulidale** [comment] 2018-03-21 03:11
The command line program calls _bio_free_all_ on the chain and I think @levitte had the intention of using this to trigger the rename.  I'm not sure if the intention was for the filter to be first and for it to tell the sink to finish and then rename or if the filter was last, doing the rename after the sink was closed.

**Comment by levitte** [comment] 2018-03-26 15:45
> I am confused with this example given by @levitte : 
> 
> ```
>     BIO *sink = BIO_new(BIO_s_file());
>     BIO *filter = BIO_new(BIO_f_temp());  /* example name */
>     BIO *out = BIO_push(sink, filter);
> ```
> 
> Should it be: `BIO *out = BIO_push(filter, sink);` to let the filter have the data for writing first instead of  data reaching sink first?

You're right.  I always seem to mix up the order.  Between BIO and perl's `push`, it's easy to get mixed up (plus I use the perl function daily, while `BIO_push` is more like once in an eternity).

In other words, good catch

**Comment by levitte** [comment] 2018-03-26 15:49
@paulidale:
> The command line program calls _bio_free_all_ on the chain and I think @levitte had the intention of using this to trigger the rename.  I'm not sure if the intention was for the filter to be first and for it to tell the sink to finish and then rename or if the filter was last, doing the rename after the sink was closed.

The intention was to have the filter "on top" of the sink.  Whenever the filter receives a file name, it stores it in a structure of its own, and then feeds the sink another, temporary file name.  Then, as part of the freeing call, the filter will finish up with renaming the temporary file name to the real one.

**Comment by levitte** [comment] 2018-04-23 08:42
As I've said elsewhere, I've had a change of heart lately, and am siding with @vdukhovni on this.

*However*, we could try and accomodate both sides if desirable, with a simple principle:

1. treat all human input, be it command line options or prompting or input files.
2. open output files (fail if unwritable *before* calculations, see #3404)
3. do the heavy lifting (calculations, see #3404)
4. output result.

does that seem like a workable strategy?  I'd say that most commands already abide to this, but some (like pkcs12) might need a small bit of reorganisation.

**Comment by InfoHunter** [comment] 2018-04-23 13:29
So, if empty output files (and related issues) are acceptable, for instance something goes wrong in step 3, then this is a workable strategy.

**Comment by InfoHunter** [comment] 2018-04-23 13:30
And I just realized that this issues was opened for reporting the 'empty file' problem, so it seems the 'open-file-first-then-heaving-lifting-then-output' strategy doesn't help a lot to resolve that problem... (But that could address #3404)

**Comment by levitte** [comment] 2018-04-23 15:29
Well, note that this issue is about the fallacy of opening it *before the import password is prompted for*. My strategy would change that. Considering parsing a p12 isn't what I would call "heavy lifting" (compared to slow dhparams generation), that makes for a middle ground.

**Comment by levitte** [comment] 2018-04-26 05:47
I'm not about to try and guarantee atomicity.  However, I think that *consistency* between commands is worthy some attention, as this does impact how easy or difficult the user experience will be.

That being said, I'm unsure if prompting (for example for password) should happen before or after trying to open the output file.  That strategy I wrote down above has prompting first, which is what this issue asks for, but I'm having second thoughts about that strategy.  It's really a kind of catch 22, 'cause I can understand those who feel a bit miffed that an empty output file was created when the import password was incorrect, but I would also understand those who feel a bit miffed if opening the output file fails *after* they spent time typing in a password (like "*NOW* you tell me???").  There's no win-win solution, there's just a choice of what seems the most sane.  But I think that whatever we end up choosing, that should be done consistently across all commands where this is a possible issue.

At this point, I think that trying to open any output file *before* prompting is the saner move.  Anyone agree / disagree (3rd option is to tell me to drop this, of course)

**Comment by t8m** [comment] 2018-04-26 09:27
I'd prefer if no output file was created if I abort the password prompt entry - that looks like more user friendly behavior to me as it gives me a possibility to abort the command without any side-effects. I do not think typing the password and then failing to output the file is such a big problem.

**Comment by mattcaswell** [comment] 2018-07-02 16:02
Since this impacts older versions of OpenSSL it is not 1.1.1 specific, so removing that milestone.

**Comment by NeonCandy** [comment] 2020-07-01 18:19
Was this issue fixed? I think I had something similar happen to me because I had my website running for a while but suddenly I got this error:
`nginx: [emerg] PEM_read_bio_X509_AUX("/shared/ssl/my.domain.com.crt") failed (SSL: error:0909006C:PEM routines:get_name:no start line:Expecting: TRUSTED CERTIFICATE)`
The file "/shared/ssl/my.domain.com.crt" is empty and I don't know how because I never touched openssl after I set it up and got it working. The only thing I did to my server is rebooted it two times, nothing else.
Im new to github so im not sure if I should be posting under this issue but this is the closest thing I found and im not really sure what happend with my .crt file.

**Comment by PotatoMasherGUI** [comment] 2023-04-09 18:53
The OpenSSL codebase would need to be modified to implement the suggested behavior of not writing the privateKey.pem file until the import password is verified. Here is a general process that could be followed to implement this fix:

    1. Locate the code in the OpenSSL codebase that handles the openssl pkcs12 command and the creation of the privateKey.pem file.

    2. Modify the code to add a step that verifies the import password before writing the privateKey.pem file. This could involve prompting the user for the import password and then using it to decrypt the private key in the P12 file. If the decryption fails, the user should be informed and the privateKey.pem file should not be written.

    3. If the import password is verified successfully, proceed with writing the privateKey.pem file as before.

    4. Test the modified code thoroughly to ensure that it works as expected and does not introduce any new issues.

    5. Submit the changes as a patch or pull request to the OpenSSL development team for review and integration into the codebase.

**Closed** 2024-05-14 13:38 UTC
Labels: branch: master, help wanted, triaged: feature
