### ISSUE TITLE
TLSv1.2 SNI hostname works in 1.1.0h, not in 1.1.1 master (as of 18-Aug)

### ISSUE THREAD

**Issue by MSP-Greg** [openssl/openssl#7014] opened 2018-08-20 18:20 UTC
I've been building & testing 1.1.1 as a MSYS2/MinGW package for use/testing in Ruby, both in Ruby's OpenSSL & Digest and also with two popular Ruby gems, Puma & EventMachine.

Current EventMachine has an SNI hostname test using TLSv1.2, which passes with 1.1.0h.  That test fails using both TLSv1.2 & TLSv1.3 when building with 1.1.1.

I'm not a strong c type, and I've seen the [wiki info](https://wiki.openssl.org/index.php/TLS1.3#Server_Name_Indication), so I'm not sure if this is intentional.

All the OpenSSL tests pass, and all of Ruby's OpenSSL tests pass.  I've also got the build logs if they would be helpful (I could post just the warnings), as MSYS2/MinGW is currently using gcc 8.2.0.

Thanks again, Greg

**Comment by mattcaswell** [comment] 2018-08-20 20:07
It's not intentional. We would expect SNI to work the same in both 1.1.0 and 1.1.1.

I know nothing about Ruby or the Ruby OpenSSL bindings. We might need a Ruby person to help identify where the problem lies.

**Comment by MSP-Greg** [comment] 2018-08-20 20:55
@mattcaswell

> We would expect SNI to work the same in both 1.1.0 and 1.1.1.

Thanks, as that was the main thing I wanted to verify.  I suspected as much, but didn't know.  I'm a Ruby person, and I seem to be able to build things, but I'm not not a serious c type.

Ruby's OpenSSL tests have the following two asserts:
```
def test_verify_hostname
  assert_equal(true,  OpenSSL::SSL.verify_ ("www.example.com", "*.example.com"))
  assert_equal(false, OpenSSL::SSL.verify_hostname("www.subdomain.example.com", "*.example.com"))
end
```

Both are passing with 1.1.0 & 1.1.1, but I'm not sure if they're client side or server side.  The EM tests appear to be server side, as in 'whom are you asking for?' calls.

For now, I'll assume this is a problem with the gem/repo [EventMachine](https://github.com/eventmachine/eventmachine) (EM).  It has it's own OpenSSL bindings, and does not use Ruby's (another popular gem [Puma](https://github.com/puma/puma) does the same).  I believe the EM file with all the OpenSSL calls is [ssl.cpp](https://github.com/eventmachine/eventmachine/blob/master/ext/ssl.cpp).

I can ask one of the c types from EM to help.  Conversely, I don't know if they have access to 1.1.1, and I don't know if they're a windows user.  Hence they may not be able to repo the issue.

I'll check with them, and close this if they can't help...

**Comment by kaduk** [comment] 2018-08-27 02:14
https://github.com/eventmachine/eventmachine/blob/master/ext/ssl.cpp#L584 implies that this code might be called both during and post-handshake, in which case the changes in 1c4aa31d79821dee9be98e915159d52cc30d8403 may be relevant.  Are you in a position to try reverting that commit (and a75be9fd34b5d66f349186f21cd8d063d2fa87a4, which will need to be reverted first)?

**Comment by MSP-Greg** [comment] 2018-08-27 02:50
@kaduk

Thanks for the reply.   I'll have a look tomorrow.

> implies that this code might be called both during and post-handshake

I believe the test is calling it post handshake.  I've never worked with SNI, but what I've found about it implied that the more normal use would be to call it during the handshake.  But that's just my newbie  guess...

> Are you in a position to...

I'll either revert the two, or build from just before the earlier commit.  And also review your notes in the two commits...

**Comment by MSP-Greg** [comment] 2018-08-28 15:05
@kaduk

Well, not sure if it's good or bad news, but I tested with the two commits reverted on top of the current master (7d38ca3f), and SNI works in EventMachine as it does with 1.1.0.  Tested with both TLSv1.2 & TLSv1.3.

FYI - it is a Windows MSYS2/MinGW 64 bit build, gcc 8.2.0.

Thanks, Greg

**Comment by kaduk** [comment] 2018-09-01 00:05
@openssl/omc I think we need to come to consensus on what the post-handshake behavior of ```SSL_get_servername()``` should be.  That is, whether it reflects whether SNI was negotiated in the handshake, or whether it blindly reports what the client sent (and thus requiring the application to track whether SNI was successfully negotiated).  The current docs in master say only:

> SSL_get_servername() returns a servername extension value of the specified
type if provided in the Client Hello or NULL.

which seems to support the latter version.

**Comment by mattcaswell** [comment] 2018-09-03 10:51
It seems fairly pointless to have a function that returns what the client asked for if we didn't then negotiate it?

**Comment by lukastribus** [comment] 2018-09-03 11:27
Please to don't introduce a breaking change in SSL_get_servername().

SSL_get_servername may be called before the certificate is actually created, so before any negotiation (when intercepting TLS), for example.

**Comment by kroeckx** [comment] 2018-09-03 21:28
We expect the use case of it to be selecting the correct
certificate. That would be during the negotation. The current
change in behaviour is after the negotation, where we didn't
expect it to be used.

**Comment by MSP-Greg** [comment] 2018-09-03 21:47
@kaduk

Sorry, been busy with some (failing) CI issues elsewhere.  Thank you for looking at the EventMachine code.

I reported this simply as a change in behavior I noticed in testing another app that passed with 1.1.0, and failed one test with 1.1.1.  I've never set up a server with SNI hostname requirements, but I did try to read what I could on the subject.

Re 'after negotiation' use, if one had a single cert covering sub-domains via a wildcard, one wouldn't need to select a cert during negotiation, but might want the hostname afterward?

Again, I probably have this all wrong, so please don't go to the trouble of writing a response, a simple "it doesn't quite work that way" will suffice...

Thanks, Greg

**Comment by lukastribus** [comment] 2018-09-03 23:31
> It seems fairly pointless to have a function that returns what the client asked for if we didn't then negotiate it?

I disagree. Why would we hide the client data, regardless of the negotiation?

The client provided SNI may be used further up the chain, just like a source ip address, port or other client provided data. For routing/ACL'ing/logging/statistical purposes.

It is my understanding that haproxy can access SSL_get_servername() anytime, to provide that information in the proxy protocol (V2), to put it into a HTTP header, to log or ACL' it:
https://github.com/haproxy/haproxy/blob/master/src/ssl_sock.c#L5790


The SNI value the client asked for is not in our control, the negotiation of it on the other hand IS in our control. So my conclusion would be that the information we need from the library is what is not in our control, as opposed to the result of a negotiation.

I have never herd of a webserver logging the "negotiated" Host header as opposed to the Host header received from the client.


Note that I'm not saying I have a specific testcase which broke haproxy, I'm merely explaining why we would need to client provided SNI value as opposed to other things.

**Comment by tmshort** [comment] 2018-09-04 16:32
Even though the expectation was that it be used for certificate selection, and not after negotiation, the reality is that it _was_ available after negotiation in prior releases (1.1.0 specifically). Which means that this is a behavior change between ABI-compatible releases. Undefined behavior becomes defined once released.

**Comment by kaduk** [comment] 2018-09-04 16:56
@MSP-Greg can you please test https://github.com/openssl/openssl/pull/7115 (and undo the previous reverts you did, if applicable)?

**Comment by vdukhovni** [comment] 2018-09-04 17:04
I have a few thoughts on this topic:
1. The function's behaviour should not be tied to implementation details of what we do or don't store in sessions. If the client sent an SNI hint, it should be available whether or not it was "negotiated".
2. IMHO when a server provides no SNI callback (effectively ignoring the client's SNI for certificate selection), it may still legitimately use the SNI value for other purposes.
3. One might even take the view that ignoring the SNI and returning a fixed certificate is a legitimate form of "negotiation". In which case perhaps the default when no callbacks are defined should not be `SL_TLSEXT_ERR_NOACK`, but that's for another day.
4. Why aren't we always returning the SNI value from the current handshake? The one in the session is relevant for determining whether the session can/can't be resumed, but does not otherwise seem relevant. When do we expect to find SNI set in the session but not in the current handshake?

**Comment by kaduk** [comment] 2018-09-04 17:17
> Why aren't we always returning the SNI value from the current handshake? The one in the session is relevant for determining whether the session can/can't be resumed, but does not otherwise seem relevant. When do we expect to find SNI set in the session but not in the current handshake?

I started with this topic because we "originally" (i.e., before I started looking) were writing the received SNI value in the ClientHello directly into the SSL_SESSION, and then doing subsequent conditional adjustment in final_server_name().  This behavior was thread-unsafe, and I wanted to switch to putting the value from the wire in the SSL object only, and only writing to the SSL_SESSION when (1) SNI was actually negotiated for that session, and (2) the SSL_SESSION was safe to write to (i.e., being created for the current connection).  Remaining references to the SSL_SESSION in SSL_get_servername() are due to an attempt to minimize behavior changes as a result of the implementation change to behave in a thread-safe manner.

**Comment by kaduk** [comment] 2018-09-04 17:27
> I think the correct solution is to always and only return the SNI value from the current handshake, and session book-keeping is an internal matter. Users who want the SNI value for the session can call an appropriate session accessor (if/when available).

Something like that is probably the best option, though I note that we had to apply  a75be9f to use the session's value for resumptions, to fix observed breakage.  That is, we cannot always only return the value from the SSL, if we want to avoid breaking existing applications.

**Comment by vdukhovni** [comment] 2018-09-04 17:33
> @kaduk Something like that is probably the best option, though I note that we had to apply a75be9f to use the session's value for resumptions, to fix observed breakage. That is, we cannot always only return the value from the SSL, if we want to avoid breaking existing applications.

Why exactly would one expect resumption to work with the original SNI left out?  The server is free to ignore resumption at any time, and do a full handshake instead, and if the SNI is missing, the handshake may not lead to the same logical peer being established.  So a client that drops the SNI extension should not expect to be able to re-establish a previous session where SNI was used.  What am I missing?

What breaks if we don't "restore" missing SNI from resumed sessions?

**Comment by vdukhovni** [comment] 2018-09-04 17:37
Are we addressing client-side or server-side behaviour here?  On the client, the server name is originally set during the handshake, and then cleared if the server does not ACK. On the server I would not expect to find it set in the first place.

**Comment by kaduk** [comment] 2018-09-04 17:37
> What breaks if we don't "restore" missing SNI from resumed sessions?

The referenced commit explictily says "this fixes the boringssl tests"

**Comment by kaduk** [comment] 2018-09-04 17:38
> Are we addressing client-side or server-side behaviour here?

server-side behavior

**Comment by vdukhovni** [comment] 2018-09-04 17:42
> The referenced commit explictily says "this fixes the boringssl tests"

Perhaps the right reaction is to allow the test in question to "fail". The test may not be portable, or appropriate.  What's the real problem?

**Comment by kaduk** [comment] 2018-09-04 18:03
> Perhaps the right reaction is to allow the test in question to "fail". The test may not be portable, or appropriate. What's the real problem?

The failing tests are from the "ServerNameExtensionServer" case in ssl/test/runner/runner.go, which sets ```resumeSession: true``` to attempt the resumption.  I don't currently have great visibility into the underlying mechanics, but I do remember spending time thinking about whether it's correct to just disable this test when I did #6792 (and obviously I concluded that it was not correct to disable this test).

**Comment by MSP-Greg** [comment] 2018-09-04 19:45
@kaduk

I added the patch on top of ['openssl req: don't try to report bits'](https://github.com/openssl/openssl/commit/17147181bd3f97c53592e2a5c9319b854b954039).

Bad news is that both SNI tests (TLSv1.2 & TLSv1.3) failed.  null/nil was returned.

Thanks, Greg

**Comment by vdukhovni** [comment] 2018-09-04 20:16
> The failing tests are from the "ServerNameExtensionServer" case in ssl/test/runner/runner.go, which sets resumeSession: true to attempt the resumption. I don't currently have great visibility into the underlying mechanics, but I do remember spending time thinking about whether it's correct to just disable this test when I did #6792 (and obviously I concluded that it was not correct to disable this test).

Understood, but it may, at some point, be useful to have a record of that analysis, so we understand what we're really doing, beyond making some black-box test pass...

**Comment by MSP-Greg** [comment] 2018-09-04 20:53
@kaduk 

So much for multi-tasking.  I work with a few build systems, and the above message about the patch not working is incorrect.  I'll rebuild & test again.  Sorry for the mistake, Greg

**Comment by kaduk** [comment] 2018-09-04 21:02
@MSP-Greg thanks for the update, and don't worry about the delay -- the discussion on that PR is going to take some time to resolve anyway.
(When you do report back, please include the commit hash(es) that you used, as that PR did get multiple updates today.)

**Comment by mattcaswell** [comment] 2018-09-07 14:07
I've managed to recreate this issue. I ran tests with the patch from #7115 applied (I think that is necessary to fix the issue too). The problem is here:

https://github.com/openssl/openssl/blob/cd3b53b8f85ad66336936073d822b3315e0ddd4f/ssl/ssl_lib.c#L3553-L3570

This code was introduced by PR#3783 in an attempt to clear any SNI that was incorrectly set on the server at configuration time. Unfortunately doing it in SSL_do_handshake() is just the wrong place - it can get called multiple times during the course of the handshake, and therefore any SNI gets cleared mid-handshake.

**Comment by mattcaswell** [comment] 2018-09-07 14:57
@kaduk's original fix has been merged (which is needed). An additional fix for this is in #7149.

**Closed** 2018-09-07 17:29 UTC

**Comment by MSP-Greg** [comment] 2018-09-08 14:14
@kaduk @vdukhovni @mattcaswell

Thank you for your work on this.  The four main Ruby items building/compiling with OpenSSL (Ruby master/trunk, Ruby OpenSSL gem, EventMachine, & Puma) are building and passing all tests.

This was using a build from master done after:

[`f01344c`](https://github.com/openssl/openssl/commit/f01344cb5c6239af0d406f48d65362d0df9627b5)  Do not reset SNI data in SSL_do_handshake()

**Comment by mattcaswell** [comment] 2018-09-08 14:16
Fantastic!

**Comment by vivekpatra** [comment] 2019-08-16 08:02
We are facing an issue related with SSL_CTX_set_tlsext_servername_callback() API not getting fired for TLS1.3 client-hello even server_name extension present in client-hello message. 
Accoring Openssl man page https://www.openssl.org/docs/man1.1.1/man3/SSL_get_servername.html.
SSL_CTX_set_tlsext_servername_callback() should work for all versions(TLS1.3 also).
Please revert back if someone has any knowledge.

**Comment by vdukhovni** [comment] 2019-08-16 13:06
The callbacks work fine in Postfix:
https://github.com/vdukhovni/postfix/blob/master/postfix/src/tls/tls_misc.c#L1043-L1046
You'll need to look more closely at your application code.
