### ISSUE TITLE
ssl_write crash

### ISSUE THREAD

**Issue by dinesh1310** [openssl/openssl#20692] opened 2023-04-08 07:44 UTC
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
[Current thread is 1 (Thread 0x7f65c1f63700 (LWP 13041))]
(gdb) bt
#0  0x00007f6ce330e8eb in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007f6ce32f9535 in __GI_abort () at abort.c:79
#2  0x00007f6ce3350648 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7f6ce345a2a0 "%s\n") at ../sysdeps/posix/libc_fatal.c:181
#3  0x00007f6ce3356d6a in malloc_printerr (str=str@entry=0x7f6ce345844e "free(): invalid pointer") at malloc.c:5359
#4  0x00007f6ce335859c in _int_free (av=<optimized out>, p=<optimized out>, have_lock=<optimized out>) at malloc.c:4180
#5  0x00007f6ce3ef2d57 in  () at /lib/x86_64-linux-gnu/libssl.so.1.1
#6  0x00007f6ce3ef2e9a in  () at /lib/x86_64-linux-gnu/libssl.so.1.1
#7  0x00007f6ce3ef65d2 in  () at /lib/x86_64-linux-gnu/libssl.so.1.1
#8  0x00007f6ce3ef6a56 in  () at /lib/x86_64-linux-gnu/libssl.so.1.1
#9  0x00007f6ce3f09392 in  () at /lib/x86_64-linux-gnu/libssl.so.1.1
#10 0x00007f6ce3f094c3 in SSL_write () at /lib/x86_64-linux-gnu/libssl.so.1.1
#11 0x00007f6ccc48baa4 in ws_raw_write (wsh=wsh@entry=0x7f62c782c580, data=data@entry=0x7f6ac805c660, bytes=bytes@entry=203) at ws.c:674
#12 0x00007f6ccc48cc12 in ws_write_frame (wsh=0x7f62c782c580, oc=<optimized out>, data=0x7f6ac838f9f0, bytes=199) at ws.c:1322
#13 0x00007f6ccc3ebaaa in ws_write_json(jsock_t*, cJSON**, switch_bool_t) 
#14 0x00007f6ccc3f0461 in process_input(jsock_t*, uint8_t*, switch_ssize_t)
#15 0x00007f6ccc3f4e00 in ws_read_operation(jsock_t*, int, uint8_t*, conference*)
#16 0x00007f6ccc3f7287 in client_run(jsock_t*) (jsock=0x7f62c782c568) at mod_ws.cpp:4087
#17 0x00007f6ccc3ffcdc in g_client_thread(void*, void*) (data=0x7f62c782c568, user_data=0x0) at mod_ws.cpp:6008
#18 0x00007f6ce3018e73 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#19 0x00007f6ce30184d5 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#20 0x00007f6ce349efa3 in start_thread (arg=<optimized out>) at pthread_create.c:486
#21 0x00007f6ce33d006f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

we are getting these types of ssl_write crash in our server frequently.. any idea how to resolve this issue?

**Comment by paulidale** [comment] 2023-04-11 03:53
Duplicate of #20696.
Please don't raise the same thing multiple times.

**Closed by paulidale** 2023-04-11 03:53 UTC
Labels: issue: question
