### ISSUE TITLE
File::Glob::glob() will disappear in perl 5.30.

### ISSUE THREAD

**Issue by kroeckx** [openssl/openssl#4663] opened 2017-11-03 13:18 UTC
I'm getting this with the 1.1.0g version:

    File::Glob::glob() will disappear in perl 5.30. Use File::Glob::bsd_glob() instead. at ./Configure line 270.

**Comment by mattcaswell** [comment] 2017-11-03 13:40
Dupe of #4636

**Closed by mattcaswell** 2017-11-03 13:40 UTC
