### ISSUE TITLE
[extended tests] are broken currently (BoringSSL fails)

### ISSUE THREAD

**Issue by slontis** [openssl/openssl#8636] opened 2019-04-02 02:15 UTC
Did a dummy commit test using https://github.com/openssl/openssl/pull/8634

**Comment by mspncp** [comment] 2019-04-02 06:31
_(FWIW: you can sign into [travis-ci](https://travis-ci.org) and [AppVeyor](https://ci.appveyor.com/login) with your GitHub account and then you will automatically get ci jobs triggered for all branches which you push to your clone, even without having to create a pull request.)_

**Comment by mattcaswell** [comment] 2019-04-19 13:10
Partially addressed by #8793. That fixes the boringssl test failure. krb5 and pyca are also currently failing though.

**Comment by mattcaswell** [comment] 2019-04-19 14:04
Hmm. Actually it only seems to be pyca that is failing in travis not krb5 (I had a local failure of krb5 which was due to an environmental issue).

I also seem to have an environmental issue with pyca which is preventing me from investigating the travis issue. When I attempt to run the pyca tests using this:

````
./config shared enable-external-tests
make
make TESTS=test_external_pyca V=1 test
```` 
I get this:
````
  generating cffi module 'build/temp.linux-x86_64-2.7/_constant_time.c'
  generating cffi module 'build/temp.linux-x86_64-2.7/_openssl.c'
  building '_openssl' extension
  creating build/temp.linux-x86_64-2.7/build
  creating build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-3hk45v/python2.7-2.7.15~rc1=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c build/temp.linux-x86_64-2.7/_openssl.c -o build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7/_openssl.o -Wconversion -Wno-error=sign-conversion
  build/temp.linux-x86_64-2.7/_openssl.c:498:10: fatal error: openssl/opensslv.h: No such file or directory
   #include <openssl/opensslv.h>
            ^~~~~~~~~~~~~~~~~~~~
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for cryptography
  Running setup.py clean for cryptography
Failed to build cryptography
Could not build wheels for cryptography which use PEP 517 and cannot be installed directly
../../util/shlib_wrap.sh sh ../../test/recipes/95-test_external_pyca_data/cryptography.sh => 1
not ok 1 - running Python Cryptography tests
#   Failed test 'running Python Cryptography tests'
#   at ../test/recipes/95-test_external_pyca.t line 27.
# Looks like you failed 1 test of 1.
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/1 subtests 

Test Summary Report
-------------------
../test/recipes/95-test_external_pyca.t (Wstat: 256 Tests: 1 Failed: 1)
  Failed test:  1
  Non-zero exit status: 1
Files=1, Tests=1, 10 wallclock secs ( 0.03 usr  0.00 sys +  6.98 cusr  0.73 csys =  7.74 CPU)
Result: FAIL
Makefile:205: recipe for target '_tests' failed
make[1]: *** [_tests] Error 1
make[1]: Leaving directory '/home/matt/dev/openssl-write'
Makefile:203: recipe for target 'tests' failed
make: *** [tests] Error 2
````
I never used to have this problem, so I don't know what changed.

Perhaps @reaperhulk or @tiran might be able to help me?

**Comment by reaperhulk** [comment] 2019-04-19 14:20
I can look at the problem this weekend. CI appears to be failing with a variety of errors related to the error stack, but your local issue looks like it just can't find your include directory so `CFLAGS` may resolve that (and replicate the travis issue). Either way I'll try to replicate locally and figure out what's going on.

**Comment by mattcaswell** [comment] 2019-04-19 14:42
> but your local issue looks like it just can't find your include directory

Right...but why not? Since I invoked this via `make TESTS=test_external_pyca V=1 test` from the root of the openssl dir I expect all required flags etc to be setup automatically by the test suite....but for some reason that hasn't happened?

**Comment by reaperhulk** [comment] 2019-04-21 08:07
Not sure on that front, but I replicated this by building from master and linking cryptography directly against it in my own env. Here's a C reproducer (adapted from `demos/evp/aesccm.c`) that produces the expected tag output on OpenSSL 1.1.1 but fails on 3.0.0-dev

```c
#include <stdio.h>
#include <openssl/bio.h>
#include <openssl/evp.h>

/* AES-CCM test data from NIST public test vectors */

/* [Alen = 32, Plen = 0, Nlen = 13, Tlen = 16] */

/* Key = f9fdca4ac64fe7f014de0f43039c7571 */

/* Count = 165 */
/* Nonce = 5a8aa485c316e9403aff859fbb */
/* Adata = a16a2e741f1cd9717285b6d882c1fc53655e9773761ad697a7ee6410184c7982 */
/* CT = 1859ac36a40a6b28b34266253627797a */
/* Result = Pass */
/* Payload = 00 */

static const unsigned char ccm_key[] = {
    0xf9, 0xfd, 0xca, 0x4a, 0xc6, 0x4f, 0xe7, 0xf0, 0x14, 0xde, 0x0f, 0x43,
    0x03, 0x9c, 0x75, 0x71
};

static const unsigned char ccm_nonce[] = {
    0x5a, 0x8a, 0xa4, 0x85, 0xc3, 0x16, 0xe9, 0x40, 0x3a, 0xff, 0x85, 0x9f,
    0xbb
};

static const unsigned char ccm_adata[] = {
    0xa1, 0x6a, 0x2e, 0x74, 0x1f, 0x1c, 0xd9, 0x71, 0x72, 0x85, 0xb6, 0xd8,
    0x82, 0xc1, 0xfc, 0x53, 0x65, 0x5e, 0x97, 0x73, 0x76, 0x1a, 0xd6, 0x97,
    0xa7, 0xee, 0x64, 0x10, 0x18, 0x4c, 0x79, 0x82
};

static const unsigned char ccm_pt[] = {
};

static const unsigned char ccm_ct[] = {
};

static const unsigned char ccm_tag[] = {
    0x18, 0x59, 0xac, 0x36, 0xa4, 0x0a, 0x6b, 0x28, 0xb3, 0x42, 0x66, 0x25,
    0x36, 0x27, 0x79, 0x7a
};

int main(int argc, char **argv)
{
    EVP_CIPHER_CTX *ctx;
    int outlen, res;
    unsigned char outbuf[1024];
    printf("AES CCM Encrypt:\n");
    ctx = EVP_CIPHER_CTX_new();
    /* Set cipher type and mode */
    EVP_EncryptInit_ex(ctx, EVP_aes_128_ccm(), NULL, NULL, NULL);
    EVP_CIPHER_CTX_ctrl(ctx, EVP_CTRL_AEAD_SET_IVLEN, sizeof(ccm_nonce),
                        NULL);
    /* Set tag length */
    EVP_CIPHER_CTX_ctrl(ctx, EVP_CTRL_AEAD_SET_TAG, sizeof(ccm_tag), NULL);
    /* Initialise key and IV */
    EVP_EncryptInit_ex(ctx, NULL, NULL, ccm_key, ccm_nonce);
    /* Set plaintext length: only needed if AAD is used */
    EVP_EncryptUpdate(ctx, NULL, &outlen, NULL, sizeof(ccm_pt));
    /* Zero or one call to specify any AAD */
    EVP_EncryptUpdate(ctx, NULL, &outlen, ccm_adata, sizeof(ccm_adata));
    /* Encrypt plaintext: can only be called once */
    EVP_EncryptUpdate(ctx, outbuf, &outlen, ccm_pt, sizeof(ccm_pt));
    EVP_EncryptFinal_ex(ctx, outbuf, &outlen);
    /* Get tag */
    EVP_CIPHER_CTX_ctrl(ctx, EVP_CTRL_AEAD_GET_TAG, 16, outbuf);
    /* Output tag */
    printf("Tag:\n");
    BIO_dump_fp(stdout, outbuf, 16);
    printf("Expected Tag:\n");
    BIO_dump_fp(stdout, ccm_tag, 16);
    EVP_CIPHER_CTX_free(ctx);
}
```

Most of (maybe all, haven't checked yet) of the failing tests are because current master doesn't appear to properly handle empty plaintext for CCM.

**Comment by mattcaswell** [comment] 2019-04-23 10:45
Ah - perfect - thanks. I can reproduce the problem. The culprit seems to be #8676.

**Comment by levitte** [comment] 2019-04-23 13:49
The big issue here is how out == NULL and in == NULL are interpreted in the backend's do_cipher() function.

Some backends (notably chacha20/poly1305) interpret `in == NULL` as a "final" call, while others (such as aes_ccm) interpret `in == NULL && out != NULL` as a "final" call.

The essence of this is that sometimes, it's simply a real bad idea to call `EVP_EncryptUpdate` with `in = NULL`, while it's tolerated in other cases.

#8676 catered for the way chacha20/poly1305 handled it.  We obviously have to fine tune this a bit better...

**Comment by mattcaswell** [comment] 2019-04-30 12:56
@levitte any thoughts on how best to fine tune this?

**Comment by mattcaswell** [comment] 2019-05-07 14:37
@levitte

**Comment by t8m** [comment] 2019-05-22 17:17
In Fedora I've added out == NULL to the in == NULL condition which fixes the Python issue and should not break the #8675. Not sure it is the right thing though.

**Comment by levitte** [comment] 2020-02-12 07:12
I lost track of this...

Is this still an issue?

**Comment by mattcaswell** [comment] 2020-02-12 09:12
Travis is currently broken due to an unrelated issue, but the external tests build has been passing in travis:

https://travis-ci.org/openssl/openssl/jobs/649179363

However, we "solved" the issue by disabling the pyca external test (20e6631c73cf). So the pyca external tests are still broken.

**Comment by mspncp** [comment] 2020-02-12 10:30
> However, we "solved" the issue by disabling the pyca external test ([20e6631](https://github.com/openssl/openssl/commit/20e6631c73cfc643f57c3219a9c7acf4678e9b84)). So the pyca external tests are still broken.

I created issue #11068 as a reminder.

**Closed** 2020-08-10 00:24 UTC
Labels: branch: master, triaged: bug
