### ISSUE TITLE
Ctrl-d twice?

### ISSUE THREAD

**Issue by levitte** [openssl/openssl#9355] opened 2019-07-12 18:58 UTC
While looking at other issues, I kinda stumbled on this one:

```
$ openssl dgst -rmd160
hahaha
^D^D
(stdin)= 0ffd3c2d34431d8b8923a15200e3bd1815765f0a
```

The strangeness here is having to press ^D (i.e. signal EOF) twice.

**Comment by rudolfolah** [comment] 2019-07-12 19:36
@levitte it looks like Ctrl+D is an EOF signal and only works in two ways based on [this stackoverflow answer](https://stackoverflow.com/a/1516177/9903). I think it's safe to close this as not a bug based on that? Up to the maintainers of course.

**Comment by mspncp** [comment] 2019-07-12 19:46
Thanks for the link @rudolfolah. Looks like it works as designed. :-) Following your hint, I found another [excellent explanation](https://unix.stackexchange.com/questions/110240/why-does-ctrl-d-eof-exit-the-shell)  on unix.stackexchange.com.

**Comment by levitte** [comment] 2019-07-12 20:13
Those links explain absolutely nothing relevant.

The key sequence after starting the program was:

h a h a h a RET C-d C-d

One C-d should have been enough to tell the application that I was ending the stream. I suspect a corner case in our BIO implementation.

**Comment by rudolfolah** [comment] 2019-07-12 20:20
@levitte good point. thought I'd take a look at mentions of [EOF](https://github.com/openssl/openssl/search?l=C&p=3&q=EOF) in the code base and there's quite a few mentions. If it's a real issue, looks like the easiest thing is stepping through `gdb` or some other debugger. Sorry I couldn't be more helpful here!

**Comment by mspncp** [comment] 2019-07-12 21:46
> Those links explain absolutely nothing relevant.

For _me_ it was relevant, because I always thought that a CTRL-D has no effect if you're not at the beginning of the line. (In fact, bash behaves this way, I can press CTRL-D as often as I like and nothing happens if the cursor is not at the beginning of the line. So it seems like bash does something special to prevent the terminal from sending it an EOF.)

> The key sequence after starting the program was:
> h a h a h a _RET_ C-d C-d

Ok, the _RET_ changes everything. Unfortunately it was easy to overlook it in your initial description.

**Comment by levitte** [comment] 2019-07-12 21:47
> Ok, the *RET* changes everything. Unfortunately it was easy to overlook it in your initial description.

Cool, I'm glad we found a common point.

**Comment by beldmit** [comment] 2019-07-13 14:24
Reproduced with 1.1.1c (debian buster)

**Comment by beldmit** [comment] 2019-07-13 14:28
Without RET it took me to press Ctrl+D trice.

**Comment by petrovr** [comment] 2019-07-13 15:07
As Rudolf  ( @rudolfolah ) point is normal to press once or two time ^D. In the link you could see sample with cat command. Once is at begining of line. 
May be issue is that openssl input requires one more?

**Comment by petrovr** [comment] 2019-07-13 15:09
P.S. "cat" samples:
1) <h><a><h><a><Enter><Ctrl+D>
2) <h><a><h><a><Ctrl+D><Ctrl+D>

**Comment by mspncp** [comment] 2019-07-13 15:17
> P.S. "cat" samples:
> 
> 1. [h][a][h][a][Enter][Ctrl+D]
> 2. [h][a][h][a][Ctrl+D][Ctrl+D]

IIUC, 1. and 2. are documented behaviour, but OpenSSL deviates from that behaviour:

3. [h][a][h][a][Enter][Ctrl+D][Ctrl+D]

That's the issue @levitte is talking about.

**Comment by mspncp** [comment] 2019-07-13 15:21
@levitte how about changing the issue title to something like
```
openssl dgst requires one extra Ctrl+D keystroke
```
and make the description a little bit more clear to prevent further questions?

**Comment by levitte** [comment] 2019-07-13 16:29
I doubt it's just dgst. Feel free to try a cipher

**Comment by beldmit** [comment] 2019-07-13 16:33
beldmit@manul$ openssl enc -base64
asdf[RET ^D ^D]
YXNkZgo=
beldmit@manul$ openssl enc -base64
asdf[^D ^D ^D]YXNkZg==

**Comment by petrovr** [comment] 2019-07-15 17:47
Usually  read from file stream is in loop like:
while not eof of file
  read and process data

In reported case, for instance dgst , in method do_fp is used loop:
    for (;;) {
        i = BIO_read(bp, (char *)buf, BUFSIZE);
Checking for eof should resolve issue, i.e. s/for (;;) {/while (!BIO_eof(bp))/ .

**Comment by rudolfolah** [comment] 2019-07-15 20:11
> Usually read from file stream is in loop like:
> while not eof of file
> read and process data
> 
> In reported case, for instance dgst , in method do_fp is used loop:
> for (;;) {
> i = BIO_read(bp, (char *)buf, BUFSIZE);
> Checking for eof should resolve issue, i.e. s/for (;;) {/while (!BIO_eof(bp))/ .

For anyone looking for this in the code base:

https://github.com/openssl/openssl/blob/f3448f5481a8d1f6fbf5fd05caaca229af0b87f7/apps/dgst.c#L464-L473

Here's an example of BIO_eof being used:

https://github.com/openssl/openssl/blob/4e7991b497b65145ec5d570485020e1658208866/test/params_conversion_test.c#L308-L318

**Comment by lzsiga** [comment] 2019-07-18 16:28
Well, `fread(3)` calls `read(2)` in loop; when `read(2)` returns 0, `fread(3)` sets the `eof`-bit in `FILE`-structure, but it still returns the already collected bytes, and if the caller doesn't check for `feof(3)`, the next `fread(3)` will continue reading.

A possible correction for `crypto/bio/bss_file.c`:

    --- bss_file.b	2019-05-28 15:12:21.000000000 +0200
    +++ bss_file.c	2019-07-18 18:05:47.350770045 +0200
    @@ -145,7 +145,8 @@
             if (b->flags & BIO_FLAGS_UPLINK)
                 ret = UP_fread(out, 1, (int)outl, b->ptr);
             else
    -            ret = fread(out, 1, (int)outl, (FILE *)b->ptr);
    +            if (! feof((FILE *)b->ptr) && ! ferror((FILE *)b->ptr))
    +                ret = fread(out, 1, (int)outl, (FILE *)b->ptr);
             if (ret == 0
                 && (b->flags & BIO_FLAGS_UPLINK) ? UP_ferror((FILE *)b->ptr) :
                                                    ferror((FILE *)b->ptr)) {

**Comment by mspncp** [comment] 2019-07-18 18:25
Don’t you want to earn the merits for your investigation yourself? Pull request welcome! :-)

**Comment by petrovr** [comment] 2019-07-19 07:17
Lőrinczy, Zsigmond wrote:
>      -            ret = fread(out, 1, (int)outl, (FILE *)b->ptr);
>      +            if (! feof((FILE *)b->ptr) && ! ferror((FILE *)b->ptr))
>      +                ret = fread(out, 1, (int)outl, (FILE *)b->ptr);

else  block ?

Perhaps BIO documentation could be reviewed as well.

Roumen

**Comment by levitte** [comment] 2019-07-19 10:04
Just a quick note: the application is in error if it doesn't check `BIO_eof()` value.  It's basically the same with `fread()`, if you do that call after EOF has been reached, you will get the same effect, i.e. have to press ^D again, because terminal driver...

The only reason I didn't have to press ^D indefinitely is that the second time around, `fread()` sets the error flag, so `ferror()` returns 1, and finally the application will get the -1 indicating that error.

Correct the application, don't "correct" the library to mitigate for application authoring mistakes.  Doing the latter often create corner cases that can become messy.

**Comment by lzsiga** [comment] 2019-07-19 10:30
@levitte I don't think ferror is affected in this context; in your example the first fread(3) calls read(2) twice; the second fread(3) calls read(2) once:

    'fread' 1 is called
    'read' 1 returns 'Hahaha\n' len=7
    'read' 1 returns '' len= 0 (beacuse of first ^D)
    'fread' 1 sets feof-flag then returns 'Hahaha\n' len=7
    'fread' 2 is called
    'read' 3 returns '' len= 0 (beacuse of second^D)
    'fread' 2 sets feof-flag (again) then returns '' len=0
    caller detects eof

**Comment by petrovr** [comment] 2019-07-19 20:30
Lőrinczy, Zsigmond wrote:
> @levitte I don't think ferror is affected in this context; in your example the first fread(3) calls read(2) twice; the second fread(3) calls read(2) once:
> 
>      'fread' 1 is called
>      'read' 1 returns 'Hahaha\n' len=7
>      'read' 1 returns '' len= 0 (beacuse of first ^D)
>      'fread' 1 sets feof-flag then returns 'Hahaha\n' len=7
>      'fread' 2 is called
>      'read' 3 returns '' len= 0 (beacuse of second^D)
>      'fread' 2 sets feof-flag (again) then returns '' len=0
>      caller detects eof
> 
> 

If I understand properly Richard's remark correction must be in apps/*.c 
code not in crypto/.... .

**Comment by levitte** [comment] 2019-07-20 05:20
> Edit: Now I think this should be fixed in dgst.c, something like this:

Yes

**Closed** 2019-08-22 12:47 UTC
Labels: 1.1.1, bug, master
