### ISSUE TITLE
Speck Cipher support for Apache

### ISSUE THREAD

**Issue by m2mi** [openssl/openssl#4959] opened 2017-12-19 16:29 UTC
We have an Github open source project provides an implementation of OpenSSL with the Speck block cipher that can be used by IoT developers. We would like to make it available to the OpenSSL project as your team/users sees fit. We followed the coding standard and it is an option to be compiled in. We could also look at including it as a patch. It can be currently be found here:

https://github.com/m2mi/openssl_speck

We are currently under an Apache 2.0 license but we are in the processing of moving to the OpenSSL license.

**Comment by mattcaswell** [comment] 2018-01-23 17:00
Is this standardised? If not this is unlikely to make it into mainline OpenSSL.

**Comment by noloader** [comment] 2018-02-16 12:36
The kernel just cut-in Speck for Android and low resource devices. The cipher is intended to be used opportunistically, like x86 tablets that lack AESNI (Intel sells chips to OEMs with SSE2-SSE4.1, but they are special order). Also see [[PATCH v2 0/5] crypto: Speck support](https://www.mail-archive.com/linux-crypto@vger.kernel.org/msg30925.html).

A ***very*** intuitive result is... if your implementation consumes the test vectors from [The Simon and Speck Families of Lightweight Block Ciphers, Appendix C](https://eprint.iacr.org/2013/404.pdf), then it is probably wrong. Crypto++ had such an implementation and it [had to be removed recently](https://github.com/weidai11/cryptopp/issues/585).

Be certain you are passing the tests from in `testmgr.h` and `testmgr.c` in the kernel patches. According to the Simon and Speck team they are correct.

**Comment by richsalz** [comment] 2018-02-16 12:44
Thanks for the update.  Simon and speck are controversial; the fact that ISO "turned them down" is indicative.  I don't know that anything has changed on the standards front yet; has it?

**Comment by noloader** [comment] 2018-02-16 12:55
@richsalz,

> Simon and speck are controversial

Yeah, I think they will always have controversy surrounding them. The US made its bed, now it has to lie in it.

> I don't know that anything has changed on the standards front yet; has it?

Sorry, I don't know about standardization. I can make introductions with Louis and Bryan from the team, if you are interested.

Speck is kind of taking off because of its performance. On a SSE4 machine it hits 2.1 cpb (Speck-64) and 2.3 cpb (Speck-128). In contrast AES will run around 25 cpb if AESNI is not available.

I know the kernel has taken it in. Eric Biggers from Google cut it in. It is nice work, and includes a NEON implementation. I just worked a job for a DoD contractor that PoC'd  Speck for unmanned aerial vehicle comms over satellite channels. I expect to see a lot of it in US Federal and US DoD uses when accelerated AES is not available.

**Comment by richsalz** [comment] 2018-02-16 13:01
Thanks for the offer, but I've got other things that are higher on my priority list. We have a policy on crypto now, https://www.openssl.org/blog/blog/2018/01/18/f2f-london/, and I don't see them being acceptable (yet).

**Comment by richsalz** [comment] 2018-05-06 18:44
ISO recently confirmed that they are NOT accepting simon and speck.  Closing this.  Please re-open or open a new issue once a standards body has approved them.

**Closed by richsalz** 2018-05-06 18:44 UTC
Labels: feature
