### ISSUE TITLE
Ninja output support for Configure (e.g. for Windows)

### ISSUE THREAD

**Issue by hlandau** [openssl/openssl#22635] opened 2023-11-06 08:03 UTC
nmake doesn't even support parallel execution. This slows down Windows builds a lot.

"ninja" is quite a popular make replacement which we could consider supporting here, as well as on *nix. The syntax is quite similar to that of Make. It's available as a Windows binary and a single compact EXE.

This could speed up our own Windows CI jobs a fair bit.

**Comment by paulidale** [comment] 2023-11-06 09:44
Good idea.

**Comment by levitte** [comment] 2023-11-06 09:56
This has been mentioned a long time ago, when the current build system was constructed.  It should be "as simple as" adding `Configurations/build.ninja.tmpl` and either having config targets that specify `build_file => 'build.ninja'`, or setting `BUILDFILE=build.ninja` before calling `Configure`.

My take on this is PR welcome.

**Comment by jamuir** [comment] 2023-11-06 17:02
https://ninja-build.org/

**Comment by vtorri** [comment] 2023-11-16 14:53
and using meson + ninja would be quite nice and fast too. meson syntax is really nice (compared to shell, perl or cmake).

**Comment by nhorman** [comment] 2024-08-13 11:41
closing as a duplicate of https://github.com/openssl/openssl/issues/16812

**Closed by nhorman** 2024-08-13 11:41 UTC
Labels: help wanted, triaged: feature

**Comment by voltflake** [comment] 2025-09-21 12:22
This issue was not related to meson at all, only single comment at end mentioned it...
