### ISSUE TITLE
SSL_get_peer_tmp_key - Session Resumption with Session ID - IPv6

### ISSUE THREAD

**Issue by SmallLars** [openssl/openssl#14954] opened 2021-04-21 06:23 UTC
SSL_get_peer_tmp_key works great for me even when Session Resumption is used with a Session ID on IPv4.

Even if [tls_process_ske_ecdhe](https://github.com/openssl/openssl/blob/4e030ed45dbf56be2f09d86f76f697ae6a0c567f/ssl/statem/statem_clnt.c#L2117) is not called again, when Session Resumption is used, s3->peer_tmp has the right value.

Currently I am searching for the lines of code where it is restored when Session Resumption is used, because it is not working when IPv6 is used. Hopefully this is not expected behavior and you can help me to find the problem.

I  am using OpenSSL 1.1.1k.

**Comment by SmallLars** [comment] 2021-04-29 06:16
Current State: It looks like SSL_get_peer_tmp_key is never working when Session Resumption is used.
IP v4 only works for me, because there is a caching mechanism in Qt. This seems to fail with IP v6.

So this is expected behavior of OpenSSL or a general Bug?

**Comment by mattcaswell** [comment] 2021-04-29 07:59
> So this is expected behavior of OpenSSL or a general Bug?

Assuming you are talking about TLSv1.2 then this is expected behaviour. In a TLSv1.2 session resumption there is no new key exchange so the tmp key isn't used.

**Comment by SmallLars** [comment] 2021-04-29 12:02
I am talking about TLSv1.2 right.
Technically I fully agree with you.
But even if there is no new key exchange, the session is based on the first tmp key.
In our software we have strict rules and need to check, if the length of the tmp key is  sufficient.

**Comment by mattcaswell** [comment] 2021-04-29 13:27
> But even if there is no new key exchange, the session is based on the first tmp key.

The "tmp" key is exactly that. Temporary. It is used as an input to derive the master key. Once the master key is derived the temporary key is no longer needed. When resuming a session the resumption is based on the master key. The tmp key is not used in any way at this stage.

> In our software we have strict rules and need to check, if the length of the tmp key is sufficient.

There is no tmp key to check. If the tmp key was considered of sufficient length in the original session such that the derived master key is acceptable, then presumably the master key must still be acceptable in any resumption. Since you can't do a resumption without having completed an initial connection it seems that just checking the tmp key in the original connection should be enough.

**Comment by SmallLars** [comment] 2021-04-29 15:02
So it is ok to accept a missing tmp key when a cipher algorithm with forward secrecy was used?
I try to find an API call to check if the session was resumed, but I can not finde one.

**Comment by mattcaswell** [comment] 2021-04-29 15:13
> So it is ok to accept a missing tmp key when a cipher algorithm with forward secrecy was used?

If a <= TLSv1.2 session is resumed then, yes.

> I try to find an API call to check if the session was resumed, but I can not finde one.

SSL_session_reused()

See:
https://www.openssl.org/docs/man1.1.1/man3/SSL_session_reused.html

**Comment by paulidale** [comment] 2021-05-05 08:51
Question has been answered, closing.

**Closed by paulidale** 2021-05-05 08:51 UTC
Labels: resolved: answered

**Comment by SmallLars** [comment] 2021-05-12 10:38
Thank you very much for your support. Problem was solved in https://bugreports.qt.io/browse/QTBUG-93295.
