### ISSUE TITLE
My application dumps core on AIX 7.1 when openssl library is upgraded from 1.0.2m to 1.1.1k

### ISSUE THREAD

**Issue by aakgandhi** [openssl/openssl#16829] opened 2021-10-13 13:39 UTC
Our application uses third-party openssl library for ssl connections.
We recently upgraded the openssl library version in our source code from 1.0.2m to 1.1.1k.
Our application statically links to the openssl library.
But we have observed core dumps on AIX 7.1 system after the openssl upgrade.

stack trace we got is :

evp_EncryptDecryptUpdate(??, ??, ??, ??, ??) at 0x100094d30
EVP_DecryptUpdate[DS](??, ??, ??, ??, ??) at 0x1000954b8
EVP_CipherUpdate(??, ??, ??, ??, ??) at 0x1000948a4
ctr_BCC_block(??, ??, ??, ??) at 0x1000ae394
ctr_BCC_blocks(??, ??) at 0x1000ae464
ctr_BCC_update(??, ??, ??) at 0x1000ae5c8
ctr_df(??, ??, ??, ??, ??, ??, ??) at 0x1000ae868
ctr_update(??, ??, ??, ??, ??, ??, ??) at 0x1000aeb20
drbg_ctr_generate(??, ??, ??, ??, ??) at 0x1000aeedc
RAND_DRBG_generate(??, ??, ??, ??, ??, ??) at 0x1000ad2b8
RAND_DRBG_bytes(??, ??, ??) at 0x1000ad418
RAND_priv_bytes(??, ??) at 0x1000abe20
bnrand(??, ??, ??, ??, ??) at 0x1000c5db0
bnrand_range(??, ??, ??) at 0x1000c62cc
BN_priv_rand_range(??, ??) at 0x1000c63bc
ec_GFp_simple_ladder_pre[DS](??, ??, ??, ??, ??) at 0x1000e72b4
ec_scalar_mul_ladder(??, ??, ??, ??, ??) at 0x1000d5fb4
ec_wNAF_mul(??, ??, ??, ??, ??, ??, ??) at 0x1000d648c
EC_POINTs_mul(??, ??, ??, ??, ??, ??, ??) at 0x1000d5038
EC_POINT_mul(??, ??, ??, ??, ??, ??) at 0x1000d50d8
ecdh_simple_compute_key(??, ??, ??, ??) at 0x1000d1cb8
ossl_ecdh_compute_key(??, ??, ??, ??) at 0x1000d1ad0
ECDH_compute_key(??, ??, ??, ??, ??) at 0x1000d154c
pkey_ec_derive(??, ??, ??) at 0x10018ba80
pkey_ec_kdf_derive(??, ??, ??) at 0x10018bb24
EVP_PKEY_derive(??, ??, ??) at 0x10011ac60
ssl_derive(??, ??, ??, ??) at 0x1001ebaf4
tls_construct_cke_ecdhe(??, ??) at 0x100235fe4
tls_construct_client_key_exchange[DS](??, ??) at 0x1002366c8
write_state_machine(??) at 0x1001fa454
state_machine(??, ??) at 0x1001f98bc
ossl_statem_connect(??) at 0x1001f9404
SSL_do_handshake[DS](??) at 0x1001dc0cc
SSL_connect(??) at 0x1001d7b30
openSSLConnectionPbVC(0x11049a358, 0x110650010, 0x1bb000001bb, 30, 0x11049a2d8, 0x11006cf90, 0x110499160, 0x0) at 0x10024ba04
open_ssl_connection(??, ??, ??) at 0x1000165c8
ProcessPage(??) at 0x100015194
FetchPageThread(??) at 0x10001eb84

Any pointers on this?

thanks in advance!!

**Comment by t8m** [comment] 2022-03-11 16:04
This seems to be a duplicate of  #16876 Closing

**Closed by t8m** 2022-03-11 16:04 UTC
Labels: branch: 1.1.1, triaged: bug
