### ISSUE TITLE
ASN1_item_verify() does not call item_verify() from the AMETH.

### ISSUE THREAD

**Issue by opencrypto** [openssl/openssl#20955] opened 2023-05-12 22:23 UTC
OpenSSL Version: 1.1.1+ (and earlier)

There is a potential issue that prevents algorithms to be able to process signature parameters when verifying signatures (ASN1). Specifically, the issue is present in the ASN1_item_verify() function. In there, the item_verify() from the ASN1 method is only invoked ONLY when the MD from the signing algorithm is NULL. 

I do not know why this choice was made - there does not seem a clear reason for that (besides checking for the results of the OBJ_find_sig_algs(), which could be done after that or if the ASN1 method or its item_verify do not exist.

You can see this behavior in [crypto/asn1/a_verify.c (lines 113-135)](https://github.com/openssl/openssl/blob/8ddacec11481a37302c19f4454e23299af399f83/crypto/asn1/a_verify.c#L118):
```
    /* Convert signature OID into digest and public key OIDs */
    if (!OBJ_find_sigid_algs(OBJ_obj2nid(a->algorithm), &mdnid, &pknid)) {
        ASN1err(ASN1_F_ASN1_ITEM_VERIFY, ASN1_R_UNKNOWN_SIGNATURE_ALGORITHM);
        goto err;
    }
    if (mdnid == NID_undef) {
        if (!pkey->ameth || !pkey->ameth->item_verify) {
            ASN1err(ASN1_F_ASN1_ITEM_VERIFY,
                    ASN1_R_UNKNOWN_SIGNATURE_ALGORITHM);
            goto err;
        }
        ret = pkey->ameth->item_verify(ctx, it, asn, a, signature, pkey);
        /*
         * Return value of 2 means carry on, anything else means we exit
         * straight away: either a fatal error of the underlying verification
         * routine handles all verification.
         */
        if (ret != 2)
            goto err;
        ret = -1;
    } else {
        const EVP_MD *type = EVP_get_digestbynid(mdnid);
```
The line that seems problematic to me is the one at line ~118:
```
if (mdnid == NID_undef) {
```
That line restricts the execution of the item_verify() function from the ASN1 method only if the returned digest is NID_undef, which does not seem correct.

If we remove this restriction and use the item_verify(), if it exists, it will be possible to correctly process signature parameters which, with the current flow, it is not possible to process.

This is especially important to allow for not having to have 'ad-hoc' solutions for different algorithms (such as RSA-PSS) and dynamically added ones (that must get around this limitation... somehow...)

An possible resolution for this issue is to move the OBJ_find_sigid_algs() only when you want to initialize the digest calculation and change the checks to verify that the item_verify() exists, for example:

```
    if (pkey->ameth && pkey->ameth->item_verify) {

        ret = pkey->ameth->item_verify(ctx, it, asn, a, signature, pkey);
        /*
         * Return value of 2 means carry on, anything else means we exit
         * straight away: either a fatal error of the underlying verification
         * routine handles all verification.
         */
        if (ret != 2)
            goto err;
        ret = -1;
    } else {

        /* Convert signature OID into digest and public key OIDs */
    	if (!OBJ_find_sigid_algs(OBJ_obj2nid(a->algorithm), &mdnid, &pknid)) {
        	ASN1err(ASN1_F_ASN1_ITEM_VERIFY, ASN1_R_UNKNOWN_SIGNATURE_ALGORITHM);
        	goto err;
    	}

        if (md) {

           const EVP_MD *type = EVP_get_digestbynid(mdnid);
           ...
        }
     }


     inl = ASN1_item_i2d(asn, &buf_in, it);
     ...
```

The above flow allows for the ASN1 method's item_verify() to be executed, not only when the MD is NULL, thus providing a consistent way to process signature's parameters in the ASN1 method verify.

**Comment by t8m** [comment] 2023-05-15 09:46
This is IMO not going to be changed. The EVP_PKEY asn1 methods are legacy (unfortunately they weren't deprecated in 3.0). New applications should use the provider interface to provide signature verification.

**Comment by levitte** [comment] 2023-05-15 10:09
`item_verify` was designed to be last resort helpers for when `ASN1_item_verify` can't figure it out on its own from the given `X509_ALGOR`.  If `mdnid != NID_undef`, then libcrypto has figured out on its own how the verification should be done, and therefore proceeds with doing so; no helper needed in that case.

**Comment by mattcaswell** [comment] 2024-01-31 11:14
Closing since this is marked as resolved.

**Closed by mattcaswell** 2024-01-31 11:14 UTC
Labels: resolved: wont fix, triaged: feature
