### ISSUE TITLE
TLS 1.3: SSL_ERROR_WANT_READ after the first SSL_read after handshake, but no more data available

### ISSUE THREAD

**Issue by therth** [openssl/openssl#7327] opened 2018-09-28 09:38 UTC
Hi,

I have an application which handles multiple connections within one thread by using non-blocking sockets and select/epoll. The application uses OpenSSL 1.1.1.

After a successful socket connect to the destination host and after a successful TLS 1.3 handshake the application wants to write an HTTP request and is signalled by epoll that it can read and write. The return value of SSL_read is -1 and SSL_get_error returns SSL_ERROR_WANT_READ; I think is because of the exchange of session information after the handshake.

As required by the OpenSSL manual the application waits now for data to read and to repeat the SSL_read after data has arrived - but there is no more data to read and the application *blocks* because it wants to send an HTTP requests first and the HTTP server does not send any data before it has got the request. The application does not do SSL_write the HTTP request because it has to repeat SSL_read before.

I think the first SSL_read has to return 0 or -1 and SSL_get_error has to return SSL_ERROR_NONE, if there is no more protocol data to read. SSL_ERROR_WANT_READ may only be returned if we are expecting more protocol data sent by the peer.

Thomas

**Comment by mattcaswell** [comment] 2018-09-28 10:04
TLSv1.3 can send protocol messages at any time after the handshake. Usually this happens fairly soon after the handshake is complete. This isn't actually any different to TLSv1.2 (a TLSv1.2 server could send a HelloRequest at any time), but it happens far more often in TLSv1.3.

After the handshake is complete your application is expecting to write application data and is not expecting the server to have sent any application data yet. Nonetheless, you have detected that data has been received on the socket. There is nothing *requiring* you to read that data yet (at this stage OpenSSL has not indicated to you that it wants to read). You could choose to ignore it and write your application data anyway.

Alternatively, you can choose to clear the data that has been received on the socket. However at this stage in your application protocol (HTTP) you're really not expecting to receive *application* data yet. If you call `SSL_read()` with a non-zero buffer length, then OpenSSL is going to keep trying to read until it has received at least one byte of application data to put in that buffer. Since we know that's not going to happen you are stuck and no further progress can be made. You can cause OpenSSL to process the data by calling `SSL_read()` with a zero length buffer. That will cause it to read a record from the underlying socket. If it gets application data (which we're not expecting at this point) then it will buffer it internally until you call `SSL_read()` with a non-zero length buffer. Alternatively if it gets a protocol message it will process it.

**Comment by therth** [comment] 2018-09-28 10:30
Thank you for the quick answer. My application is working fine for several years using TLS1.2 and OpenSSL 1.0.2 and 1.1.0.
You are right I'm not required to read the data - but the HTTP request/response is just a special case. And in general: when should I read data after its availablity has been signalled? There is no criteria, especially because I do not know which data is available before I have read it. So this is no option.
I've tried to do an additional SSL_read() with a zero buffer length, but this does no change anything.
I still think: SSL_get_error() after SSL_read() may only return SSL_ERROR_WANT_READ if we expect more protocol data sent by the peer immediately. Is this correct or wrong?

Thomas

**Comment by mattcaswell** [comment] 2018-09-28 10:47
> I've tried to do an additional SSL_read() with a zero buffer length, but this does no change anything.

You're right - I forgot that this still keeps trying to read application data even after processing the protocol message - even thought the buffer length is zero.

> I still think: SSL_get_error() after SSL_read() may only return SSL_ERROR_WANT_READ if we expect more protocol data sent by the peer immediately. Is this correct or wrong?

Calling `SSL_read()` means: "I'd like to read some application data". SSL_read() will return `SSL_ERROR_WANT_READ` if it was unable to provide you with any because there isn't any available. It will read and process any protocol messages it receives, but will only return a successful response when it has received an application data record. I think it is safe to ignore the SSL_ERROR_WANT_READ in this scenario. The underlying socket is no longer showing as readable, and you are no longer interested in reading application data.

**Comment by therth** [comment] 2018-09-28 11:06
Ok, it's easy to ignore the SSL_ERROR_WANT_READ in this scenario because it happens just after the handshake.

> It will read and process any protocol messages it receives, but will only return a successful response when it has received an application data record.

For me it sounds we have a principal problem I haven't realised before: After getting SSL_ERROR_WANT_READ I must wait for more data on the socket and then call SSL_read() again. But if the peer does not send any application data in this sitaution - for whatever reason - the application blocks.

**Comment by mattcaswell** [comment] 2018-09-28 11:14
Right. Perhaps there should be a documentation update around this. I think it is safe to call SSL_write() even after SSL_read() has returned `SSL_ERROR_WANT_READ`. At least, I can't think of a scenario where this would cause a problem. OTOH, I don't think it is safe to call SSL_read() after SSL_write() has returned `SSL_ERROR_WANT_WRITE`. In other words, writes must be completed, but reads could be aborted.

I wonder if @kroeckx has a view on this.

**Comment by kroeckx** [comment] 2018-09-28 17:54
We recently added this to the documentation for
SSL_ERROR_WANT_READ and SSL_ERROR_WANT_WRITE:

    It is safe to call SSL_read() or SSL_read_ex() when more data
    is available even when the call that set this error was an
    SSL_write() or SSL_write_ex().  However if the call was an
    SSL_write() or SSL_write_ex(), it should be called again to
    continue sending the application data.

I don't see a problem with calling either SSL_read() or
SSL_write() after an SSL_ERROR_WANT_READ or SSL_ERROR_WANT_WRITE
is returned. As long as you don't misuse the API, I think it
shouldn't be a problem.

The reason the above quoted paragraph was added is that it's
always safe to call SSL_read() when select()/poll() say there is
data that can be read.

Anyway, regarding the reported issue. I've spend some time
updating the documentation related to all of this. I hope it's at
least more clear than it used to be. Did you read the
documentation that comes with 1.1.1? (There was also an
SSL_shutdown() documentation change commited after the 1.1.1
release.)

I think there is at least a misunderstanding of what
SSL_ERROR_WANT_READ means. By default you should only get this
from SSL_read() if it's unable to give you application data at
this time. It tried to read from the socket, but there is not
enough data so that something can be returned. You can then wait
with select()/poll() until data is available.

With other options turned on/off, it can also mean other things.

Note that not all data is application data, or that you might not
have received a full record yet.

If you use something like select()/poll(), and it says there is
data available, I recommend that you call SSL_read() until it
returns SSL_ERROR_WANT_READ (or an error). But it's only needed
when SSL_CTX_set_read_ahead() is turned on. If it's off,
select()/poll() will just return directly again if you didn't
process all the data.

Returning SSL_ERROR_ZERO_RETURN is the wrong answer, it means that
the other side will not send any data at all anymore, it has
closed the write side.

**Comment by therth** [comment] 2018-09-29 13:57
Documentation until 1.1.0: "The operation did not complete; the same TLS/SSL I/O function should be called again later."

I assumed I have to call the same TLS/SSL I/O function before I call any other TLS/SSL I/O function which will lead to the issue.

Thank you for clarification and changing the documentation in 1.1.1.

Thomas

**Comment by suxb201** [comment] 2021-07-06 09:46
@kroeckx The document is still unclear. Look at this link：https://github.com/openssl/openssl/issues/8419

**Comment by t8m** [comment] 2021-07-19 14:21
Closing as duplicate of #8419

**Closed by t8m** 2021-07-19 14:21 UTC
