### ISSUE TITLE
Symbolic links in dist tarball seem broken

### ISSUE THREAD

**Issue by brucestephens** [openssl/openssl#491] opened 2015-12-03 17:16 UTC
For example in openssl-1.0.2e.tar.gz, `openssl-1.0.2e/include/openssl/aes.h -> openssl-1.0.2e/../../crypto/aes/aes.h`.

Probably this can be resolved by appending `S` to the `--transform` expression when forming the tarball.

**Comment by glensc** [comment] 2015-12-03 17:58
same error is also in 0.9.8zh release:

```
$ tar tvfs openssl-0.9.8zh.tar.gz|grep test/jpaketest.c
lrwxrwxrwx openssl/openssl      0 2015-12-03 17:00 openssl-0.9.8zh/test/jpaketest.c -> openssl-0.9.8zh/dummytest.c
```

**Comment by glensc** [comment] 2015-12-03 18:18
workaround for now:

```
ln -s . test/openssl-1.0.2e
```

**Comment by quanah** [comment] 2015-12-03 19:19
STILL BROKEN IN LATEST RELEASE

**Comment by glensc** [comment] 2015-12-03 19:22
@quanah i don't  think they follow github tracker

i sent mail to rt@openssl.org as per http://openssl.org/community/, but the ticket haven't appeared in rt.openssl.org

**Comment by mattcaswell** [comment] 2015-12-03 19:25
We do follow. What exactly is still broken? What problems are incorrect links causing?

**Comment by richsalz** [comment] 2015-12-03 19:25
We do follow tracker.  RT posts are moderated and the moderator(s) are busy re-packing the release.

**Comment by glensc** [comment] 2015-12-03 19:28
@mattcaswell @richsalz symlinks in tarball point to in-existent files:

https://github.com/openssl/openssl/issues/491#issuecomment-161731937

**Comment by glensc** [comment] 2015-12-03 19:29
also, these files are missing in last tarball, but were present in previous version. i'm not sure is that intentional:

```
cp: cannot stat 'doc/openssl_button.gif': No such file or directory
cp: cannot stat 'doc/openssl_button.html': No such file or directory
```

**Comment by glensc** [comment] 2015-12-03 19:31
broken symlinks make build failure of test files (make tests):

http://buildlogs.pld-linux.org//index.php?dist=th&arch=x86_64&ok=0&name=openssl&id=099b95db-969a-4d18-a32e-d0520ba189ed&action=tail#error-1

**Comment by richsalz** [comment] 2015-12-03 19:31
The files were removed on purpose, but the script that refers them was apparently not fixed; a bug.

**Comment by glensc** [comment] 2015-12-03 19:33
@richsalz the doc files are then okay.

we copy them to docdir in rpm packaging: https://github.com/pld-linux/openssl/blob/edee8d76233cfbf2c42a744721d2d522b29c44cb/openssl.spec#L413

so no bug there if removed intentionally

**Comment by mattcaswell** [comment] 2015-12-03 19:34
The invalid symlinks should not be a problem. They get recreated during Configure. Is the rpm packaging recalling Configure?

**Comment by brucestephens** [comment] 2015-12-03 19:36
There are still broken links, though now the `include/openssl` ones have gone presumably ordinary builds will work. It messes up our use: we unpack and import the files to our VCS and apply our local modifications. We also set modification times on all files according to the times on the commits, which'll break.

Probably not a showstopper: we can just remove the broken symlinks. It just feels icky.

**Comment by glensc** [comment] 2015-12-03 19:37
yes, [Configure is called](https://github.com/pld-linux/openssl/blob/474266d55b2c00ed0019c7defe132406b4b0d1df/openssl.spec#L293), but it worked in previous version, some makefile dependency broken?

what make rule is to be called to fix symlinks, i could try to execute that explicitly to see if that solves

**Comment by glensc** [comment] 2015-12-03 19:41
if i check my build tree, then yes, symlinks are recreated in test/ except for `test/jpaketest.c`

**Comment by glensc** [comment] 2015-12-03 19:52
`make depend` does not help for jpaketest here, but something converts the broken symlink to man(1) link:

```
[glen@carme-pld openssl-1.0.2e]$ l test/jpaketest.c
-rw-r--r-- 1 glen users 16  3. dets  21:45 test/jpaketest.c
[glen@carme-pld openssl-1.0.2e]$ cat test/jpaketest.c
.so dummytest.c
```

and that is obviously valid C source.

**Comment by glensc** [comment] 2015-12-03 19:58
that `.so ` link is created by `util/point.sh`:

```sh
[glen@carme-pld openssl-1.0.2e]$ cat util/point.sh 
#!/bin/sh

rm -f "$2"
if true; then
    echo ".so $1" > "$2"
elif test "$OSTYPE" = msdosdjgpp || test "x$PLATFORM" = xmingw ; then
    cp "$1" "$2"
else
    ln -s "$1" "$2"
fi
echo "$2 => $1"
```

but in git, i don't see such code:
https://github.com/openssl/openssl/blob/OpenSSL_1_0_2-stable/util/point.sh

**Comment by glensc** [comment] 2015-12-03 20:01
ok, the `.so ` man link issue is pld specific, caused by this patch:
https://github.com/pld-linux/openssl/blob/0d29cf4fb019281d6a2fda895ed7e8130c0d9be0/openssl-man-namespace.patch#L26-L38

so i guess there isn't upstream issue with the broken symlinks afterall.

thanks for listening!

**Comment by richsalz** [comment] 2015-12-03 20:06
Thanks for looking into it!  Closing this.

**Closed by richsalz** 2015-12-03 20:06 UTC

**Comment by sebastian-philipp** [comment] 2015-12-04 14:56
Do you plan to fix the packages on https://www.openssl.org/source/ ? the 1.0.1q  package is still broken in this regard.

**Comment by mattcaswell** [comment] 2015-12-04 14:58
There are no plans to reissue the packages at the moment. There shouldn't be any problems with building the packages. The broken links can be ignored.
