### ISSUE TITLE
self-signed certificate with CA:FALSE is verified since 1.1.1h

### ISSUE THREAD

**Issue by duritong** [openssl/openssl#15146] opened 2021-05-04 22:02 UTC
The following certificate does not verify with 1.1.1g but with 1.1.1h although the basic constraint says CA:FALSE:

It is my understanding (and was what openssl did until 1.1.1h) that a self-signed certificate with basic constraint CA:FALSE cannot be used to verify itself.

```
$ openssl x509 -text -in test.pem 
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            ae:2a:f7:8f:2f:d7:3d:53:14:c3
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: CN = This is my self-signed certificate
        Validity
            Not Before: May  4 20:04:24 2021 GMT
            Not After : May  4 20:04:24 2022 GMT
        Subject: CN = This is my self-signed certificate
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                RSA Public-Key: (4096 bit)
                Modulus:
                    00:e5:f6:20:bb:b2:32:34:66:08:08:38:58:11:ab:
                    cf:f6:56:b4:e9:06:30:4f:4c:35:e0:0d:d0:1e:1b:
                    ad:27:b0:f8:44:f7:97:cf:76:d6:c5:45:39:ff:1f:
                    b0:17:9c:af:52:cf:7a:dd:9e:cb:c0:42:a9:32:e9:
                    47:50:fc:a6:ab:5f:c8:6c:2a:14:47:e6:8f:d4:06:
                    3d:6a:e9:f8:dc:ca:ca:fb:19:5f:42:4c:dc:e1:91:
                    5c:e6:c3:2f:99:a7:53:18:98:65:21:be:07:6a:2c:
                    17:91:40:ae:0c:67:f2:20:90:18:e0:8a:84:eb:9a:
                    05:65:d9:d1:c4:23:c5:74:74:21:88:97:2e:d2:57:
                    4d:50:d6:68:68:8a:77:e9:48:4b:11:47:16:06:47:
                    5b:16:97:9b:ee:58:37:f8:ed:3c:68:c4:17:13:78:
                    ff:67:84:d0:05:e4:13:6c:05:72:ab:90:3b:63:61:
                    24:9a:fe:05:6c:b2:d8:83:8b:02:09:9d:fc:c5:b5:
                    66:67:6e:0a:cd:84:20:32:60:f6:aa:5b:d5:08:23:
                    b0:c3:9e:12:44:63:3c:fc:f6:b5:0b:5b:bc:a4:03:
                    7b:28:5c:07:fb:3d:07:2d:2e:96:6a:6d:fe:ed:c5:
                    7d:ea:73:2b:e5:f4:e3:9c:b6:e9:6f:b2:95:0f:6e:
                    28:35:e7:bd:4a:ee:03:71:30:c6:d7:d6:21:d9:1c:
                    6b:75:97:71:bd:be:51:c5:3f:04:7c:35:61:72:a7:
                    9b:7a:dd:ba:78:99:63:4c:81:bb:5a:c9:40:16:2d:
                    4a:85:cd:2e:1a:7a:eb:48:cb:8a:a9:6b:01:9b:a3:
                    af:f9:32:eb:b0:d9:4b:ac:55:2b:51:c8:a5:b6:cf:
                    2d:ae:e7:09:4d:24:4c:59:0c:53:7d:01:57:a6:c9:
                    4c:d7:c5:6d:5c:34:84:75:0f:08:9c:59:a4:df:b9:
                    89:35:cb:50:fd:f9:8f:b5:c3:19:fc:2c:58:64:37:
                    dd:44:34:e1:de:85:ed:46:95:40:ff:00:4e:5c:0b:
                    d2:3f:6a:51:1f:e9:ae:68:ad:93:a3:f0:31:7f:ce:
                    71:7c:99:c9:08:0f:e6:cc:2d:72:93:84:ff:e1:d7:
                    62:0e:83:29:22:dc:b7:7a:c0:a6:ad:3f:f4:c6:dd:
                    cc:e8:66:1f:a9:cd:ed:fc:69:c0:8b:0a:28:7a:51:
                    81:94:ca:8e:1d:4e:ea:be:97:d3:f1:59:63:42:9a:
                    b9:d0:51:02:fc:c3:8a:29:ee:2e:1c:f6:19:3f:4c:
                    cb:d8:7a:10:46:61:80:93:b4:1d:54:d1:b1:d5:69:
                    96:7f:6f:b2:19:0d:0d:a7:3b:90:45:55:8a:04:75:
                    e2:6e:33
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Subject Key Identifier: 
                F8:0F:39:96:A6:DF:9F:67:10:A0:04:AC:B3:59:E6:E2:16:8C:24:56
            X509v3 Basic Constraints: critical
                CA:FALSE
            X509v3 Key Usage: critical
                Digital Signature, Non Repudiation, Key Encipherment
            X509v3 Authority Key Identifier: 
                keyid:F8:0F:39:96:A6:DF:9F:67:10:A0:04:AC:B3:59:E6:E2:16:8C:24:56
                DirName:/CN=This is my self-signed certificate
                serial:AE:2A:F7:8F:2F:D7:3D:53:14:C3

    Signature Algorithm: sha256WithRSAEncryption
         52:a3:24:2c:51:29:96:c4:fa:1d:7c:ba:46:c7:64:ae:98:a6:
         5c:1d:4d:6e:5e:45:6a:33:66:dc:69:7a:06:e6:2f:a2:1b:2b:
         bb:c9:a6:d4:8d:b8:86:cc:2d:2d:ef:e6:fd:f3:ec:5e:fa:2c:
         27:7b:74:2f:44:a9:ee:c2:09:c0:c1:f3:98:42:bd:0e:54:94:
         d8:de:9c:0b:99:33:81:82:41:59:1d:4a:f5:4c:53:88:f7:6d:
         ff:3a:60:8d:4c:c4:60:70:5e:cd:20:c6:e1:87:4a:a8:b9:77:
         4e:a0:64:8b:db:12:3c:99:26:42:8b:bb:86:52:2b:2a:71:e0:
         36:82:6b:df:c8:e3:8d:f0:1c:58:ea:8a:c3:6e:ad:77:bf:20:
         6e:05:f6:26:3e:08:65:1a:50:06:56:c2:2a:ed:47:64:b6:43:
         3f:db:9c:25:e0:3f:1a:9b:ab:1c:4d:49:97:0b:93:ae:47:5e:
         d9:fa:d6:c4:33:be:06:f9:41:bc:99:18:98:f9:b6:e3:cd:ea:
         1d:1b:36:bc:5f:04:f6:9f:4e:bd:e0:11:44:8c:79:07:6c:72:
         8c:1d:a4:62:73:b2:37:fb:4e:e4:9f:ad:36:ea:34:49:b0:74:
         b8:46:7d:e3:ba:48:14:d4:b6:dd:15:de:c8:83:8d:9d:8c:83:
         a7:6b:e4:11:dd:fc:ee:86:f6:57:b5:d2:91:93:1d:70:80:c4:
         2d:0f:a3:33:d2:fb:04:6c:7c:00:e8:95:91:0f:24:66:42:f9:
         45:1c:c7:7d:14:5e:ac:4e:d0:00:6d:0e:14:24:b8:a8:2d:45:
         95:0b:7f:d1:5e:a8:8f:e9:f5:28:3a:76:d3:00:a1:20:37:89:
         d5:c8:2d:b8:cf:e3:17:6e:d0:36:9c:71:6e:46:c1:29:20:95:
         22:87:b2:34:f4:54:75:f3:ce:b4:0a:ff:98:43:28:f7:07:38:
         dd:1e:af:46:18:c8:06:27:b0:67:35:6e:59:90:c1:28:60:4f:
         41:ac:af:16:dd:9d:34:fa:0a:ab:b0:64:c0:3a:8c:12:17:69:
         8a:34:b8:67:a0:a5:90:49:bc:a6:c9:57:e0:ad:85:1d:90:5c:
         9b:90:6d:35:22:b1:b9:1e:5b:91:7a:97:93:a7:0a:c4:24:6c:
         08:4e:19:06:b0:30:c6:bb:bb:16:b8:47:35:fa:c7:e5:b2:bf:
         a9:b5:e1:9c:41:d8:fa:c9:d4:83:a4:c5:e7:0e:e6:79:47:de:
         de:f1:fb:e0:40:4c:41:c0:91:f7:06:f2:95:81:56:79:6e:a1:
         9a:e7:95:81:d9:35:5c:d9:07:27:03:ca:b7:28:f9:e6:58:ab:
         43:fb:0f:91:3c:42:58:8a
-----BEGIN CERTIFICATE-----
MIIFgTCCA2mgAwIBAgILAK4q948v1z1TFMMwDQYJKoZIhvcNAQELBQAwLTErMCkG
A1UEAwwiVGhpcyBpcyBteSBzZWxmLXNpZ25lZCBjZXJ0aWZpY2F0ZTAeFw0yMTA1
MDQyMDA0MjRaFw0yMjA1MDQyMDA0MjRaMC0xKzApBgNVBAMMIlRoaXMgaXMgbXkg
c2VsZi1zaWduZWQgY2VydGlmaWNhdGUwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAw
ggIKAoICAQDl9iC7sjI0ZggIOFgRq8/2VrTpBjBPTDXgDdAeG60nsPhE95fPdtbF
RTn/H7AXnK9Sz3rdnsvAQqky6UdQ/KarX8hsKhRH5o/UBj1q6fjcysr7GV9CTNzh
kVzmwy+Zp1MYmGUhvgdqLBeRQK4MZ/IgkBjgioTrmgVl2dHEI8V0dCGIly7SV01Q
1mhoinfpSEsRRxYGR1sWl5vuWDf47TxoxBcTeP9nhNAF5BNsBXKrkDtjYSSa/gVs
stiDiwIJnfzFtWZnbgrNhCAyYPaqW9UII7DDnhJEYzz89rULW7ykA3soXAf7PQct
LpZqbf7txX3qcyvl9OOctulvspUPbig1571K7gNxMMbX1iHZHGt1l3G9vlHFPwR8
NWFyp5t63bp4mWNMgbtayUAWLUqFzS4aeutIy4qpawGbo6/5Muuw2UusVStRyKW2
zy2u5wlNJExZDFN9AVemyUzXxW1cNIR1DwicWaTfuYk1y1D9+Y+1wxn8LFhkN91E
NOHehe1GlUD/AE5cC9I/alEf6a5orZOj8DF/znF8mckID+bMLXKThP/h12IOgyki
3Ld6wKatP/TG3czoZh+pze38acCLCih6UYGUyo4dTuq+l9PxWWNCmrnQUQL8w4op
7i4c9hk/TMvYehBGYYCTtB1U0bHVaZZ/b7IZDQ2nO5BFVYoEdeJuMwIDAQABo4Gh
MIGeMB0GA1UdDgQWBBT4DzmWpt+fZxCgBKyzWebiFowkVjAMBgNVHRMBAf8EAjAA
MA4GA1UdDwEB/wQEAwIF4DBfBgNVHSMEWDBWgBT4DzmWpt+fZxCgBKyzWebiFowk
VqExpC8wLTErMCkGA1UEAwwiVGhpcyBpcyBteSBzZWxmLXNpZ25lZCBjZXJ0aWZp
Y2F0ZYILAK4q948v1z1TFMMwDQYJKoZIhvcNAQELBQADggIBAFKjJCxRKZbE+h18
ukbHZK6YplwdTW5eRWozZtxpegbmL6IbK7vJptSNuIbMLS3v5v3z7F76LCd7dC9E
qe7CCcDB85hCvQ5UlNjenAuZM4GCQVkdSvVMU4j3bf86YI1MxGBwXs0gxuGHSqi5
d06gZIvbEjyZJkKLu4ZSKypx4DaCa9/I443wHFjqisNurXe/IG4F9iY+CGUaUAZW
wirtR2S2Qz/bnCXgPxqbqxxNSZcLk65HXtn61sQzvgb5QbyZGJj5tuPN6h0bNrxf
BPafTr3gEUSMeQdscowdpGJzsjf7TuSfrTbqNEmwdLhGfeO6SBTUtt0V3siDjZ2M
g6dr5BHd/O6G9le10pGTHXCAxC0PozPS+wRsfADolZEPJGZC+UUcx30UXqxO0ABt
DhQkuKgtRZULf9FeqI/p9Sg6dtMAoSA3idXILbjP4xdu0DaccW5GwSkglSKHsjT0
VHXzzrQK/5hDKPcHON0er0YYyAYnsGc1blmQwShgT0GsrxbdnTT6CquwZMA6jBIX
aYo0uGegpZBJvKbJV+CthR2QXJuQbTUisbkeW5F6l5OnCsQkbAhOGQawMMa7uxa4
RzX6x+Wyv6m14ZxB2PrJ1IOkxecO5nlH3t7x++BATEHAkfcG8pWBVnluoZrnlYHZ
NVzZBycDyrco+eZYq0P7D5E8QliK
-----END CERTIFICATE-----
```

Fails to verify (expected):
```
$ podman run -i -v $(pwd)/test.pem:/tmp/test.pem:Z shamelesscookie/openssl:1.1.1g  verify -CAfile /tmp/test.pem /tmp/test.pem
CN = This is my self-signed certificate
error 20 at 0 depth lookup: unable to get local issuer certificate
error /tmp/test.pem: verification failed
```

Verifies (not expected):
```
$podman run -i -v $(pwd)/test.pem:/tmp/test.pem:Z shamelesscookie/openssl:1.1.1h  verify -CAfile /tmp/test.pem /tmp/test.pem
/tmp/test.pem: OK
```

Looking through the changes between [g and h](https://github.com/openssl/openssl/compare/OpenSSL_1_1_1g...OpenSSL_1_1_1h) I see https://github.com/openssl/openssl/commit/42bb51e59308b3ebc5cc1c35ff4822fba6b52d79 that might be the cause for that change of behavior. Thus CC @DDvO / @t8m / @kroeckx 

I do not have a strong opinion about the old behavior if I can learn why the new behavior is correct.

**Comment by t8m** [comment] 2021-05-05 07:59
IMO this is not a bug. If a self signed certificate is in the trust store it can verify itself.

A different question would be if the certificate was able to verify other certificates. That would IMO be a bug.

**Comment by DDvO** [comment] 2021-05-05 09:27
According to RFC 5280 (see https://tools.ietf.org/html/rfc5280#section-6.1 for details) both are fine.
When a certificate is used as a trust anchor, only its public key and its subject name are relevant.
So it does not matter whether such a trusted cert is self-signed, which validity period it has, or which extensions it has.
Of course, the validating entity may impose/implement further restrictions due to local policies etc.

So IMO it is good that OpenSSL itself does not (anymore) check the basicConstraints extension of a trust anchor cert.

**Comment by t8m** [comment] 2021-05-05 10:30
Closing this.

**Closed by t8m** 2021-05-05 10:30 UTC
Labels: issue: bug report, resolved: not a bug

**Comment by duritong** [comment] 2021-05-06 14:25
Ok, thank you all for the clarification.
