### ISSUE TITLE
secp112r2 gives different bit length

### ISSUE THREAD

**Issue by misery** [openssl/openssl#23996] opened 2024-03-28 13:06 UTC
We found in our unit tests that the deprecated API with "EC_GROUP_get_degree" returns expected 112 bits but the "new" API "EVP_PKEY_get_bits" returns 110 bit.

Shouldn't **secp112r2** be 112 bit instead of 110?

```
#include <openssl/ec.h>
#include <openssl/evp.h>
#include <openssl/pem.h>
#include <iostream>

int main()
{
	// openssl ecparam -name secp112r2 -out secp112r2_param.pem
	// openssl ecparam -in secp112r2_param.pem -genkey -noout -out secp112r2_key.pem
	// openssl ec -in secp112r2_key.pem -pubout -out secp112r2_pubkey.pem
	const char* pem = "-----BEGIN PUBLIC KEY-----\n"
			"MDIwEAYHKoZIzj0CAQYFK4EEAAcDHgAEDYc2sdM6NKJA+6zBJItc11xBbpw7yWXu\n"
			"ojrUFA==\n"
			"-----END PUBLIC KEY-----";

	BIO* bio = BIO_new_mem_buf(pem, strlen(pem));
	EVP_PKEY* pkey = PEM_read_bio_PUBKEY(bio, nullptr, nullptr, nullptr);
	std::cout << EVP_PKEY_get_bits(pkey) << std::endl;;

	BIO* bio2 = BIO_new_mem_buf(pem, strlen(pem));
	EC_KEY* ec = PEM_read_bio_EC_PUBKEY(bio2, nullptr, nullptr, nullptr);
	std::cout << EC_GROUP_get_degree(EC_KEY_get0_group(ec)) << std::endl;

	return 0;
}
```

**Output**
```
110
112
```

**openssl cmdline**
```
$ openssl ec -in key.pem -noout -text
read EC key
Private-Key: (110 bit)
priv:
    0c:10:fb:77:18:3f:a0:83:28:9b:31:bb:7d:eb
pub:
    04:05:a5:98:7a:7d:42:b5:60:23:ab:e6:11:76:81:
    b1:ce:89:0c:79:ec:28:07:39:90:b4:fa:03:03
ASN1 OID: secp112r2
```

**Comment by t8m** [comment] 2024-04-02 16:20
EC_GROUP_get_degree() returns for prime field curves the number of bits of the field prime. Where the EVP_PKEY_get_bits() returns the EVP_PKEY_PARAM_BITS param value which is the number of bits of the group's order. IMO the latter value more precisely gives the number of bits relevant for the security of the curve.

**Comment by nhorman** [comment] 2024-06-05 18:13
Closing as this is labeled not a bug

**Closed by nhorman** 2024-06-05 18:13 UTC
Labels: resolved: not a bug, triaged: bug
