### ISSUE TITLE
Cannot connect via TLS 1.2 when one of server and client is on PPC64LE (OpenSSL 1.0.2k)

### ISSUE THREAD

**Issue by rojerrell** [openssl/openssl#3235] opened 2017-04-17 15:09 UTC
```
s_server -tls1_2 -cert ~/test-ssl/cert.pem -key ~/test-ssl/key.pem  -accept 9999 -verify 4 
WARNING: can't open config file: /usr/local/ssl/openssl.cnf
verify depth is 4
Using default temp DH parameters
ACCEPT
ERROR
70367312297728:error:1409441B:SSL routines:ssl3_read_bytes:tlsv1 alert decrypt error:s3_pkt.c:1493:SSL alert number 51
shutting down SSL
CONNECTION CLOSED
ACCEPT
```

```
s_client  -cert ~/test-ssl/cert.pem -key ~/test-ssl/key.pem -connect rh7le64m:9999 
WARNING: can't open config file: /usr/local/ssl/openssl.cnf
CONNECTED(00000003)
depth=0 C = XX, L = Default City, O = Default Company Ltd
verify error:num=18:self signed certificate
verify return:1
depth=0 C = XX, L = Default City, O = Default Company Ltd
verify return:1
140011851228840:error:04091068:rsa routines:INT_RSA_VERIFY:bad signature:rsa_sign.c:278:
140011851228840:error:1408D07B:SSL routines:ssl3_get_key_exchange:bad signature:s3_clnt.c:2032:
---
Certificate chain
 0 s:/C=XX/L=Default City/O=Default Company Ltd
   i:/C=XX/L=Default City/O=Default Company Ltd
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIFVzCCAz+gAwIBAgIJAKrFnEdZSFEYMA0GCSqGSIb3DQEBBQUAMEIxCzAJBgNV
BAYTAlhYMRUwEwYDVQQHDAxEZWZhdWx0IENpdHkxHDAaBgNVBAoME0RlZmF1bHQg
Q29tcGFueSBMdGQwHhcNMTcwNDE3MTUwNTM5WhcNMTgwNDE3MTUwNTM5WjBCMQsw
CQYDVQQGEwJYWDEVMBMGA1UEBwwMRGVmYXVsdCBDaXR5MRwwGgYDVQQKDBNEZWZh
dWx0IENvbXBhbnkgTHRkMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA
u2euPppHNpRcCY60Ws3I1mo+4mfcAgLHYiKQ8jf+Si60fMwvAMYwyDu96CBEOlS8
8VeJzoxlbrVJu3qpv7pVFki/nxpx5XA/1OvaOzDXJ61LUhCpW7AfSKjsaih5Bw47
ZqXSk+KcQPUwwP3cNFBJz4KWjabo6shRuTUtMheQRWMYfymk5F3VdPZ2oY700EvH
j7B+306PTcXyk3ucgxlVQO6+Qy5z4Viwv148OIqtoB1P7ZqQ+oRjPsP5ZP2IT70g
aa2ishNag0DERGimk7S44iwtlp4p5ZFk6j/oz6U5oGEV8Euz/n73KsKsNzq7JMDp
HpgVJSa/egLa1hVrh1IwhV0x8BpJVgGTK6Z/AEE0UmbYP5YmMln8KNb5gF1L/2mn
lJ7LTScXRjWtWWqa8v8UdX4tf8zYbz1xYSaTediy+devlec5SkrkFTWhqF3CGD/B
jfR9JnO9TdOpoDY5B+xri8XOZo4bZg75R/k7s/APRDKIMHkJXM/BOT2vaj8HMnn7
eBzHRFn0O30+hvNPS8ZwrzO3iD+QgCJc7xWCRd0H4zpOsL4+2Us3pbxyn0TDQ4X8
hhxMwfqqPu88VqORk5Zn9r78owADszlpDiVwqy3/FZs7RQEbgFwSmNbBDByfxwzz
YGmEb/dXAmWowsn3ozEdyRHsVPrB1bd5B04qujwe4vsCAwEAAaNQME4wHQYDVR0O
BBYEFOq0QGaksiMadyoUlhQ0SdiCc+ihMB8GA1UdIwQYMBaAFOq0QGaksiMadyoU
lhQ0SdiCc+ihMAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQEFBQADggIBAGJGYPj7
aX+ZFVhvV4oAAlltD/7IcOda3hwtDakhKYPNEdeC6cVCTVrknOvcCYJ3NskTDaB0
XpfNgL8dzQG7PwJLKLzj6XP98znyy+YOLrNqsEAX0S+WQHYliFu93zOrVRY4MGP6
iu6QCkUP3dUdRtfrMJD5spH9/bUF/zhKuUL0T1wEH6qHW+I1SaKejUOXuRhpZSU3
mUaV2AuIxhhyFBONsfLK51UnIPECjj6gdutvzumTneODGQ0whpXCJsvv8v0OXjWj
6R6jCX+fbym1+sknth1rmi+7CE2VwvPck9fjOYkTLOFPNOmjTeHJ/LTpx4udjSWl
WkTGm1MxDX1c1q67YuJvAsaecYzNKs0koTKWGWqkyxt/FaNjRW5Gc5o+X4EOwZLw
0u7KEIDmAcOKojmP+9xjMsDsOneo+IOymWtmN2wHA3wItOiofigSENRMEzFXZRBH
GaIXNwZegTEOzbaML4885gt0UYy5T/6t4kaJ7YccIFlKFjtxnHW5wA0QurZSbClj
YTdWSVsjpynzLpNKxAKP9raePbi6gnxf8Y8wWE5oyqzdrLAxIp7oIkSkmXxJy4IG
h++UJWBQqarD00b/hbKW3D8SzCCdipxYm+O9qKwCBRkgEIACnX+Z2hEz6p7oljjx
1B2ZEbwCoRhacAlJo5xR67PcTOA9tRmgPozZ
-----END CERTIFICATE-----
subject=/C=XX/L=Default City/O=Default Company Ltd
issuer=/C=XX/L=Default City/O=Default Company Ltd
---
No client certificate CA names sent
Peer signing digest: SHA512
Server Temp Key: ECDH, P-256, 256 bits
---
SSL handshake has read 2051 bytes and written 7 bytes
---
New, (NONE), Cipher is (NONE)
Server public key is 4096 bit
Secure Renegotiation IS supported
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : 0000
    Session-ID: 
    Session-ID-ctx: 
    Master-Key: 
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    Start Time: 1492441558
    Timeout   : 300 (sec)
    Verify return code: 18 (self signed certificate)
---
```

If both the server and the client are on PPC64LE, then it works fine.  It also doesn't appear to be a problem is the server is started with '-tls1_1'.

**Comment by dot-asm** [comment] 2017-04-24 20:20
I can't reproduce this with default test apps/server.pem. Can you confirm if even apps/server.pem fails for you?

**Comment by rojerrell** [comment] 2017-04-24 21:02
Yes, it doesn't seem to be related to the certificate used.  If I had to guess, it would appear that there is an endian issue on PPC64LE platforms in the signature calculation that prevents cross-platform verification.

(Server is RHEL 7 PPC64LE)
openssl s_server -tls1_2 -cert /tmp/roj/src/openssl-1.0.2k/apps/server.pem -accept 9999
WARNING: can't open config file: /usr/local/ssl/openssl.cnf
Using default temp DH parameters
ACCEPT
ERROR
70366756159232:error:1409441B:SSL routines:ssl3_read_bytes:tlsv1 alert decrypt error:s3_pkt.c:1493:SSL alert number 51
shutting down SSL
CONNECTION CLOSED
ACCEPT

(Client is RHEL 6 x86_64)
openssl s_client   -connect rh7le64m:9999 
WARNING: can't open config file: /usr/local/ssl/openssl.cnf
CONNECTED(00000003)
depth=0 C = UK, O = OpenSSL Group, OU = FOR TESTING PURPOSES ONLY, CN = Test Server Cert
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 C = UK, O = OpenSSL Group, OU = FOR TESTING PURPOSES ONLY, CN = Test Server Cert
verify error:num=21:unable to verify the first certificate
verify return:1
140521848829608:error:04091068:rsa routines:INT_RSA_VERIFY:bad signature:rsa_sign.c:278:
140521848829608:error:1408D07B:SSL routines:ssl3_get_key_exchange:bad signature:s3_clnt.c:2032:
---
Certificate chain
 0 s:/C=UK/O=OpenSSL Group/OU=FOR TESTING PURPOSES ONLY/CN=Test Server Cert
   i:/C=UK/O=OpenSSL Group/OU=FOR TESTING PURPOSES ONLY/CN=OpenSSL Test Intermediate CA
---
Server certificate
-----BEGIN CERTIFICATE-----
MIID5zCCAs+gAwIBAgIJALnu1NlVpZ6zMA0GCSqGSIb3DQEBBQUAMHAxCzAJBgNV
BAYTAlVLMRYwFAYDVQQKDA1PcGVuU1NMIEdyb3VwMSIwIAYDVQQLDBlGT1IgVEVT
VElORyBQVVJQT1NFUyBPTkxZMSUwIwYDVQQDDBxPcGVuU1NMIFRlc3QgSW50ZXJt
ZWRpYXRlIENBMB4XDTExMTIwODE0MDE0OFoXDTIxMTAxNjE0MDE0OFowZDELMAkG
A1UEBhMCVUsxFjAUBgNVBAoMDU9wZW5TU0wgR3JvdXAxIjAgBgNVBAsMGUZPUiBU
RVNUSU5HIFBVUlBPU0VTIE9OTFkxGTAXBgNVBAMMEFRlc3QgU2VydmVyIENlcnQw
ggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDzhPOSNtyyRspmeuUpxfNJ
KCLTuf7g3uQ4zu4iHOmRO5TQci+HhVlLZrHF9XqFXcIP0y4pWDbMSGuiorUmzmfi
R7bfSdI/+qIQt8KXRH6HNG1t8ou0VSvWId5TS5Dq/er5ODUr9OaaDva7EquHIcMv
vPQGuI+OEAcnleVCy9HVEIySrO4P3CNIicnGkwwiAud05yUAq/gPXBC1hTtmlPD7
TVcGVSEiJdvzqqlgv02qedGrkki6GY4S7GjZxrrf7Foc2EP+51LJzwLQx3/JfrCU
41NEWAsu/Sl0tQabXESN+zJ1pDqoZ3uHMgpQjeGiE0olr+YcsSW/tJmiU9OiAr8R
AgMBAAGjgY8wgYwwDAYDVR0TAQH/BAIwADAOBgNVHQ8BAf8EBAMCBeAwLAYJYIZI
AYb4QgENBB8WHU9wZW5TU0wgR2VuZXJhdGVkIENlcnRpZmljYXRlMB0GA1UdDgQW
BBSCvM8AABPR9zklmifnr9LvIBturDAfBgNVHSMEGDAWgBQ2w2yI55X+sL3szj49
hqshgYfa2jANBgkqhkiG9w0BAQUFAAOCAQEAqb1NV0B0/pbpK9Z4/bNjzPQLTRLK
WnSNm/Jh5v0GEUOE/Beg7GNjNrmeNmqxAlpqWz9qoeoFZax+QBpIZYjROU3TS3fp
yLsrnlr0CDQ5R7kCCDGa8dkXxemmpZZLbUCpW2Uoy8sAA4JjN9OtsZY7dvUXFgJ7
vVNTRnI01ghknbtD+2SxSQd3CWF6QhcRMAzZJ1z1cbbwGDDzfvGFPzJ+Sq+zEPds
xoVLLSetCiBc+40ZcDS5dV98h9XD7JMTQfxzA7mNGv73JoZJA6nFgj+ADSlJsY/t
JBv+z1iQRueoh9Qeee+ZbRifPouCB8FDx+AltvHTANdAq0t/K3o+pplMVA==
-----END CERTIFICATE-----
subject=/C=UK/O=OpenSSL Group/OU=FOR TESTING PURPOSES ONLY/CN=Test Server Cert
issuer=/C=UK/O=OpenSSL Group/OU=FOR TESTING PURPOSES ONLY/CN=OpenSSL Test Intermediate CA
---
No client certificate CA names sent
Peer signing digest: SHA512
Server Temp Key: ECDH, P-256, 256 bits
---
SSL handshake has read 1427 bytes and written 7 bytes
---
New, (NONE), Cipher is (NONE)
Server public key is 2048 bit
Secure Renegotiation IS supported
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : 0000
    Session-ID: 
    Session-ID-ctx: 
    Master-Key: 
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    Start Time: 1493067337
    Timeout   : 300 (sec)
    Verify return code: 21 (unable to verify the first certificate)
---

**Comment by dot-asm** [comment] 2017-04-24 21:26
> If I had to guess, it would appear that there is an endian issue on PPC64LE platforms in the signature calculation that prevents cross-platform verification.

But another side is little-endian too. And when I said I can't reproduce it was also from x86_64 client to Linux/ppc64le server. What's your compiler? What happens if you drop optimization level?

**Comment by rojerrell** [comment] 2017-04-25 17:22
I get the same signature issue with -O0 and with removing the -O option entirely.
gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/ppc64le-redhat-linux/4.8.3/lto-wrapper
Target: ppc64le-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.3-20140911/obj-ppc64le-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.3-20140911/obj-ppc64le-redhat-linux/cloog-install --enable-gnu-indirect-function --enable-secureplt --with-long-double-128 --disable-multilib --with-cpu-64=power7 --with-tune-64=power8 --build=ppc64le-redhat-linux
Thread model: posix
gcc version 4.8.3 20140911 (Red Hat 4.8.3-9) (GCC)

**Comment by snhenson** [comment] 2017-04-25 19:28
Do  you get any problems with "make test"?

**Comment by snhenson** [comment] 2017-04-25 20:33
My guess is that there is an SHA512 issue because that is used for TLS 1.2 by default but not for TLS 1.1

Try the option _-sigalgs RSA+SHA1_ to s_client or s_server and see if you get a connection. Then try the same with _-sigalgs RSA+SHA256_

**Comment by rojerrell** [comment] 2017-04-25 20:38
With SHA1 and SHA256 I get a slightly different error.

140024061195944:error:140943FC:SSL routines:ssl3_read_bytes:sslv3 alert bad record mac:s3_pkt.c:1493:SSL alert number 20

**Comment by snhenson** [comment] 2017-04-25 21:19
That suggests a digest issue and not RSA. What about "make test" do you get any errors?

**Comment by snhenson** [comment] 2017-04-25 21:49
Also try _-sigalgs RSA+SHA256 -cipher AES128_ which I suspect will work. I think there's a problem with SHA384/SHA512.

**Comment by dot-asm** [comment] 2017-04-26 10:35
> gcc version 4.8.3

Fair enough, I had 4.8.5. Straightforward ./config, no extra args.

> -sigalgs ...

For reference I can confirm that it does work for me with SHA512 (from x86_64 Linux s_client to PPC64LE Linux s_server, as well as from big-endian PPC Linux s_client), as well as SHA256 and SHA1.

**Comment by rojerrell** [comment] 2017-04-26 10:53
With -sigalgs RSA+SHA256 -cipher AES128 it does work fine.

**Comment by snhenson** [comment] 2017-04-26 21:35
Those options were designed to remove use of SHA384/SHA512 from all aspects of the handshake. Since that works that seems to be where the problem is on your setup though I've no idea where. Are you able to run "make test" and see if it also fails? if not just run: _test/sha512t_

**Comment by snhenson** [comment] 2017-04-27 19:58
Oh and you have tried configuring with _no-asm_ haven't you?

**Comment by rojerrell** [comment] 2017-05-01 18:04
Doing cbcm
Doing ecb
Doing ede ecb
Doing cbc
Doing desx cbc
Doing ede cbc
Doing pcbc
Doing cfb8 cfb16 cfb32 cfb48 cfb64 cfb64() ede_cfb64() done
Doing ofb
Doing ofb64
Doing ede_ofb64
Doing cbc_cksum
Doing quad_cksum
input word alignment test 0 1 2 3
output word alignment test 0 1 2 3
fast crypt test 
../util/shlib_wrap.sh ./ideatest
No IDEA support
../util/shlib_wrap.sh ./shatest
test 1 ok
test 2 ok
test 3 ok
../util/shlib_wrap.sh ./sha1test
test 1 ok
test 2 ok
test 3 ok
../util/shlib_wrap.sh ./sha256t
Testing SHA-256 ... passed.
Testing SHA-224 ... passed.
../util/shlib_wrap.sh ./sha512t
Testing SHA-512 
TEST 1 of 3 failed.

Options from the Makefile
OPTIONS=enable-threads no-asm no-bf no-camellia no-cast no-dso no-ec_nistp_64_gcc_128 no-gmp no-idea no-jpake no-krb5 no-libunbound no-md2 no-mdc2 no-rc2 no-rc4 no-rc5 no-rfc3779 no-ripemd no-sctp no-seed no-shared no-srp no-ssl-trace no-ssl2 no-store no-unit-test no-weak-ssl-ciphers no-zlib no-zlib-dynamic static-engine
CONFIGURE_ARGS=no-bf no-camellia no-cast no-ec_nistp_64_gcc_128 no-gmp no-idea no-jpake no-krb5 no-md2 no-mdc2 no-rc2 no-rc4 no-rc5 no-rfc3779 no-ripemd no-seed no-srp no-ssl2 no-store no-zlib no-zlib-dynamic no-dso no-shared no-sctp enable-threads no-asm linux-ppc64
SHLIB_TARGET=linux-shared

**Comment by rojerrell** [comment] 2017-05-01 18:05
Specifically, that little bit saying linux-ppc64 is concerning me at the moment.

**Comment by dot-asm** [comment] 2017-05-01 18:16
> linux-ppc64

This is totally wrong for little-endian PPC. I'm surprised that SHA-512 is first one to fail... Anyway, it should have been linux-ppc64le, and ./config should have detected it. When we see report "s_server this-n-that doesn't work", we assume that README and INSTALL were examine and followed, i.e. `make test` has succeeded. Closing.

**Comment by rojerrell** [comment] 2017-05-01 18:16
Sure enough, looks the the root cause of the issue is in my config scripts.  Somewhat surprised this thing even built.

**Closed by dot-asm** 2017-05-01 18:16 UTC

**Comment by rojerrell** [comment] 2017-05-01 18:30
thanks for the help, sorry it was a bit of a waste of time.
