### ISSUE TITLE
minor flaws in OpenSSL-1.1.0 build system [MSVC]

### ISSUE THREAD

**Issue by sav-ix** [openssl/openssl#1072] opened 2016-05-15 15:07 UTC
Hi, Everyone,

There is a small feedback about OpenSSL-1.1.0 builds using MSVC:

- in file `\Configurations\10-main.conf` compiler options `/Ox /O2 /Ob2` could be reduced to `/O2`, since it include all of them (see [/O2](https://msdn.microsoft.com/en-us/library/8f8h5cxt.aspx) and [/Ox](https://msdn.microsoft.com/en-us/library/59a3b321.aspx)),

- there is a message:
```
It looks like you don't have either nmake.exe or dmake.exe on your PATH,
so you will not be able to execute the commands from a Makefile.  You can
install dmake.exe with the Perl Package Manager by running:

    ppm install dmake
```
during OpenSSL configuration, regardless, that `nmake.exe` available in PATH and further build using MSVC run successfully.
But even in opposite case, it's weird. Since `nmake.exe` exists in the same directory as `cl.exe`. Thus if `nmake` not available, it mean that `cl` not available too and `dmake` won't help much,

- there is some noise in stderr:
```
Could Not Find c:\libOPENSSL-1.1.0-dev\src\apps\libcrypto-1_1-x64.dll
Could Not Find c:\libOPENSSL-1.1.0-dev\src\test\libcrypto-1_1-x64.dll
Could Not Find c:\libOPENSSL-1.1.0-dev\src\apps\libssl-1_1-x64.dll
Could Not Find c:\libOPENSSL-1.1.0-dev\src\test\libssl-1_1-x64.dll
```
in the end of `nmake` run. Inherent to shared builds only, and have any consequences in practice,

- file `apps\openssl.cnf` not copied into `--openssldir=...` specified directory during installation, unlike of Mingw-w64 builds,

- OpenSSL MSVC builds doesn't generate html documentation, unlike of Mingw-w64 builds. Wherein ActivePerl, a recommended PERL package for OpenSSL MSVC builds, contain some "adopted" version of `pod2html` package,

All above relate to OpenSSL builds using MSVC, thus was reported as a single issue. But let me know, if some of paragraphs worth to be submitted as a separate issue.

Regards,
Alexander

**Comment by levitte** [comment] 2016-05-16 07:20
> - in file `\Configurations\10-main.conf` compiler options `/Ox /O2 /Ob2` could be reduced to `/O2`, since it include all of them (see [/O2](https://msdn.microsoft.com/en-us/library/8f8h5cxt.aspx) and [/Ox](https://msdn.microsoft.com/en-us/library/59a3b321.aspx)),

Good point.

> - there is a message:
> ```
> It looks like you don't have either nmake.exe or dmake.exe on your PATH,
> so you will not be able to execute the commands from a Makefile.  You can
> install dmake.exe with the Perl Package Manager by running:
> 
>     ppm install dmake
> ```
> during OpenSSL configuration, regardless, that `nmake.exe` available in PATH and further build using MSVC run successfully.

That message isn't generated by us.  What perl distribution and version did you use?

> - there is some noise in stderr:
> ```
> Could Not Find c:\libOPENSSL-1.1.0-dev\src\apps\libcrypto-1_1-x64.dll
> Could Not Find c:\libOPENSSL-1.1.0-dev\src\test\libcrypto-1_1-x64.dll
> Could Not Find c:\libOPENSSL-1.1.0-dev\src\apps\libssl-1_1-x64.dll
> Could Not Find c:\libOPENSSL-1.1.0-dev\src\test\libssl-1_1-x64.dll
> ```
> in the end of `nmake` run. Inherent to shared builds only, and have any consequences in practice,

Weird...  How did you configure?

> - file `apps\openssl.cnf` not copied into `--openssldir=...` specified directory during installation, unlike of Mingw-w64 builds,

Right you are!  Will fix.

> - OpenSSL MSVC builds doesn't generate html documentation, unlike of Mingw-w64 builds. Wherein ActivePerl, a recommended PERL package for OpenSSL MSVC builds, contain some "adopted" version of `pod2html` package,

Yeah, and the same goes on VMS.  I've been meaning to fix that...

> All above relate to OpenSSL builds using MSVC, thus was reported as a single issue. But let me know, if some of paragraphs worth to be submitted as a separate issue.

Nah, but might become more than one PR ;-)

**Comment by sav-ix** [comment] 2016-05-16 07:58
> That message isn't generated by us. What perl distribution and version did you use?

Used ActivePerl 5.22, as recommended in OpenSSL manual for MSVC builds. Configure output looks like:
```
    no-zlib         [default] 
    no-zlib-dynamic [default] 
Configuring for VC-WIN64A

It looks like you don't have either nmake.exe or dmake.exe on your PATH,
so you will not be able to execute the commands from a Makefile.  You can
install dmake.exe with the Perl Package Manager by running:

    ppm install dmake

CC            =cl
CFLAG         =-W3 -wd4090 -Gs0 -GF -Gy -nologo -DOPENSSL_SYS_WIN32 -DWIN32_LEAN_AND_MEAN -DL_ENDIAN -D_CRT_SECURE_NO_DEPRECATE -DUNICODE -D_UNICODE /MD /Ox /O2 /Ob2 
```



>>        there is some noise in stderr:
>>
>>    Could Not Find c:\libOPENSSL-1.1.0-dev\src\apps\libcrypto-1_1-x64.dll
>>    Could Not Find c:\libOPENSSL-1.1.0-dev\src\test\libcrypto-1_1-x64.dll
>>    Could Not Find c:\libOPENSSL-1.1.0-dev\src\apps\libssl-1_1-x64.dll
>>    Could Not Find c:\libOPENSSL-1.1.0-dev\src\test\libssl-1_1-x64.dll
>>
>>    in the end of nmake run. Inherent to shared builds only, and have any consequences in practice,

>Weird... How did you configure?

Command
`perl Configure shared VC-WIN64A && nmake`
allow to reproduce it. If you're interested to figure out, on what stage of build this happen, here part of log:
```
dllmain.c
	C:\ProgramData\Perl64\bin\perl.exe util\mkdef.pl "crypto" 32 > libcrypto-1_1-x64.def
	C:\ProgramData\Perl64\bin\perl.exe -i.tmp -pe "s|^LIBRARY\s+crypto32|LIBRARY libcrypto-1_1-x64|;" libcrypto-1_1-x64.def
	DEL libcrypto-1_1-x64.def.tmp
	C:\ProgramData\Perl64\bin\perl.exe util\mkrc.pl libcrypto-1_1-x64.dll > libcrypto-1_1-x64.rc
	rc /folibcrypto-1_1-x64.res libcrypto-1_1-x64.rc
Microsoft (R) Windows (R) Resource Compiler Version 10.0.10011.16384

Copyright (C) Microsoft Corporation.  All rights reserved.


	link /nologo /debug /dll  /implib:libcrypto.lib /out:libcrypto-1_1-x64.dll /def:libcrypto-1_1-x64.def @C:\Users\user\AppData\Local\Temp\nmFA81.tmp || (DEL /Q libcrypto.* libcrypto-1_1-x64.* && EXIT 1)
   Creating library libcrypto.lib and object libcrypto.exp
	DEL /F apps\libcrypto-1_1-x64.dll
Could Not Find c:\libOPENSSL-1.1.0-dev\src\apps\libcrypto-1_1-x64.dll
	DEL /F test\libcrypto-1_1-x64.dll
Could Not Find c:\libOPENSSL-1.1.0-dev\src\test\libcrypto-1_1-x64.dll
	COPY libcrypto-1_1-x64.dll apps
        1 file(s) copied.
	COPY libcrypto-1_1-x64.dll test
        1 file(s) copied.
	cl -DOPENSSL_USE_APPLINK -DDSO_WIN32 -DNDEBUG -DOPENSSL_THREADS -DOPENSSL_NO_STATIC_ENGINE -DOPENSSL_PIC -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPOLY1305_ASM "-DENGINESDIR=\"C:\\Program Files\\OpenSSL\\lib\\engines\"" "-DOPENSSLDIR=\"C:\\Program Files\\Common Files\\SSL\"" -W3 -wd4090 -Gs0 -GF -Gy -nologo -DOPENSSL_SYS_WIN32 -DWIN32_LEAN_AND_MEAN -DL_ENDIAN -D_CRT_SECURE_NO_DEPRECATE -DUNICODE -D_UNICODE /MD /Ox /O2 /Ob2 /Zi /Fdossl_static /I include /I . -c /Fossl\bio_ssl.obj ssl\bio_ssl.c

[snip]

tls_srp.c
	C:\ProgramData\Perl64\bin\perl.exe util\mkdef.pl "ssl" 32 > libssl-1_1-x64.def
	C:\ProgramData\Perl64\bin\perl.exe -i.tmp -pe "s|^LIBRARY\s+ssl32|LIBRARY libssl-1_1-x64|;" libssl-1_1-x64.def
	DEL libssl-1_1-x64.def.tmp
	C:\ProgramData\Perl64\bin\perl.exe util\mkrc.pl libssl-1_1-x64.dll > libssl-1_1-x64.rc
	rc /folibssl-1_1-x64.res libssl-1_1-x64.rc
Microsoft (R) Windows (R) Resource Compiler Version 10.0.10011.16384

Copyright (C) Microsoft Corporation.  All rights reserved.


	link /nologo /debug /dll  /implib:libssl.lib /out:libssl-1_1-x64.dll /def:libssl-1_1-x64.def @C:\Users\user\AppData\Local\Temp\nm4BDE.tmp || (DEL /Q libssl.* libssl-1_1-x64.* && EXIT 1)
   Creating library libssl.lib and object libssl.exp
	DEL /F apps\libssl-1_1-x64.dll
Could Not Find c:\libOPENSSL-1.1.0-dev\src\apps\libssl-1_1-x64.dll
	DEL /F test\libssl-1_1-x64.dll
Could Not Find c:\libOPENSSL-1.1.0-dev\src\test\libssl-1_1-x64.dll
	COPY libssl-1_1-x64.dll apps
        1 file(s) copied.
	COPY libssl-1_1-x64.dll test
        1 file(s) copied.
	cl -DOPENSSL_USE_APPLINK -DDSO_WIN32 -DNDEBUG -DOPENSSL_THREADS -DOPENSSL_NO_STATIC_ENGINE -DOPENSSL_PIC -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPOLY1305_ASM "-DENGINESDIR=\"C:\\Program Files\\OpenSSL\\lib\\engines\"" "-DOPENSSLDIR=\"C:\\Program Files\\Common Files\\SSL\"" -W3 -wd4090 -Gs0 -GF -Gy -nologo -DOPENSSL_SYS_WIN32 -DWIN32_LEAN_AND_MEAN -DL_ENDIAN -D_CRT_SECURE_NO_DEPRECATE -DUNICODE -D_UNICODE /MD /Ox /O2 /Ob2 /Zi /Fddso /I include -c /Foengines\e_capi.obj engines\e_capi.c
```

**Comment by levitte** [comment] 2016-05-16 08:15
So I've one PR for the little stuff, #1075.

[x] "/Ox /O2 /Ob2" => "/O2"
[x] Install `apps\openssl.cnf`
[x] Silence the noisy DELs
[ ] Check why Configure complains about nmake.exe and dmake.exe
[ ] Install HTML docs

**Comment by sav-ix** [comment] 2016-05-16 08:33
Tested PR: https://github.com/openssl/openssl/pull/1075 for shared MSVC build.
- all tests passed successfully,
- `openssl.cnf` successfully installed to `-openssldir=...` specified directory,
- no `Could Not Find...` noise in stderr.

**Comment by levitte** [comment] 2016-05-16 09:17
Okie, so only two more items, are we agreed?

- Check why Configure complains about nmake.exe and dmake.exe
- Install HTML docs

**Comment by FdaSilvaYY** [comment] 2016-05-16 09:28
There one more to add .
nmake clean is deleting a versionned file:
File removed - F:\crypto\x86cpuid.asm
File removed - F:\crypto\aes\aes-586.asm
File removed - F:\crypto\aes\aesni-x86.asm
File removed - F:\crypto\aes\vpaes-x86.asm
File removed - F:\crypto\bn\bn-586.asm
File removed - F:\crypto\bn\co-586.asm
File removed - F:\crypto\bn\x86-gf2m.asm
File removed - F:\crypto\bn\x86-mont.asm
File removed - F:\crypto\bn\asm\bn-c64xplus.asm
File removed - F:\crypto\camellia\cmll-x86.asm
File removed - F:\crypto\chacha\chacha-x86.asm
File removed - F:\crypto\des\crypt586.asm
File removed - F:\crypto\des\des-586.asm
File removed - F:\crypto\ec\ecp_nistz256-x86.asm
File removed - F:\crypto\md5\md5-586.asm
File removed - F:\crypto\modes\ghash-x86.asm
File removed - F:\crypto\poly1305\poly1305-x86.asm
File removed - F:\crypto\rc4\rc4-586.asm
File removed - F:\crypto\ripemd\rmd-586.asm
File removed - F:\crypto\sha\sha1-586.asm
File removed - F:\crypto\sha\sha256-586.asm
File removed - F:\crypto\sha\sha512-586.asm
File removed - F:\crypto\whrlpool\wp-mmx.asm
File removed - F:\engines\e_padlock-x86.asm
=> F:\crypto\bn\asm\bn-c64xplus.asm is versionned.

**Comment by sav-ix** [comment] 2016-05-16 09:31
> so only two more items, are we agreed?

Yes. And is it possible to make PERL utilize all CPU cores during documentation build?

**Comment by levitte** [comment] 2016-05-16 09:50
@FdaSilvaYY writes:

>There one more to add .
nmake clean is deleting a versionned file:
File removed - F:\crypto\x86cpuid.asm
...
=> F:\crypto\bn\asm\bn-c64xplus.asm is versionned.

Thanks.  I'll fix that in the same manner as for Unix.

-----

@sav-ix writes:

> And is it possible to make PERL utilize all CPU cores during documentation build?

I'm not sure how I'd do that, quite frankly, at least with the current structure...  I *do* have an idea, but that's a fairly gruesome change, not sure that's fit for 1.1.0 at this point.  I'll ponder it over the day.

**Comment by sav-ix** [comment] 2016-05-16 10:01
> quite frankly, at least with the current structure...

[Parallel execution](https://www.gnu.org/software/make/manual/html_node/Parallel.html) greatly increases speed of building OpenSLL binaries. Would be nice, if same became implemented for building documentation.

**Comment by levitte** [comment] 2016-05-16 10:13
> > quite frankly, at least with the current structure...
> 
> [Parallel execution](https://www.gnu.org/software/make/manual/html_node/Parallel.html) greatly increases speed of building OpenSLL binaries. Would be nice, if same became implemented for building documentation.

I'm well aware of the concept...  making such a change would be quite invasive, though, and considering we're tight on time...

... but like I said, I'll ponder it over the say.

**Comment by dot-asm** [comment] 2016-05-16 10:34
> /Ox /O2 /Ob2 could be reduced to /O2

No, it couldn't. Original reason for this look was that some older compilers defined /Ox as something without /O2 and /O2 amended that. And /Ob2 has nothing to do with /O2 in sense that it's not combination of b and 2. The option is /Ob<n> and controls inline expansion. If anything /O2 can be omitted (because we don't support that old compiler), but /Ox /O2 /Ob2 is *not* reducible to /O2. One can argue that /Ob2 can be omitted too... Once again, one can argue in favour of /Ox alone, one can argue in favour of /Ox /Ob2, but one can't argue in favour of replacing everything with /O2.

**Comment by dot-asm** [comment] 2016-05-16 10:45
What I'm saying is that one shouldn't look at current version alone, but even at past version [which is the reason for why it looks the way it does].

**Comment by levitte** [comment] 2016-05-16 10:47
> > /Ox /O2 /Ob2 could be reduced to /O2
> 
> No, it couldn't. Original reason for this look was that some older compilers defined /Ox as something without /O2 and /O2 amended that. And /Ob2 has nothing to do with /O2 in sense that it's not combination of b and 2. The option is /Ob<n> and controls inline expansion. If anything /O2 can be omitted (because we don't support that old compiler), but /Ox /O2 /Ob2 is *not* reducible to /O2. One can argue that /Ob2 can be omitted too... Once again, one can argue in favour of /Ox alone, one can argue in favour of /Ox /Ob2, but one can't argue in favour of replacing everything with /O2.

Hmmm...  The [list of options](https://msdn.microsoft.com/en-us/library/fwkeyyhe.aspx) indicates that `/Ox` is equivalent to `/Ob2gity /Gs` (although it's [own page](https://msdn.microsoft.com/en-us/library/59a3b321.aspx) doesn't, which is weird)), and the [`/O2` page](https://msdn.microsoft.com/en-us/library/8f8h5cxt.aspx) indicates that it's equivalent to `/Og /Oi /Ot /Oy /Ob2 /Gs /GF /Gy`, which does contain all the options from `/Ob2gity /Gs`, so color me confused.

How old compilers do we support?

**Comment by levitte** [comment] 2016-05-16 10:49
Still, btw, according to the [`/Ox` page](https://msdn.microsoft.com/en-us/library/59a3b321.aspx), it's still equivalent to `/Ob2 /Og /Oi /Ot /Oy`, which is still all part of `/O2`.

So I dunno...

**Comment by levitte** [comment] 2016-05-16 10:54
I'm currently looking at the VS2005 manual, where it basically says the same, and also explicitely that:

> In general, /O2 should be preferred over /Ox and /O1 over /Oxs.

as well as:

> /Ox is mutually exclusive from: ... /O2

Ref: https://msdn.microsoft.com/en-us/library/59a3b321(v=vs.80).aspx

**Comment by dot-asm** [comment] 2016-05-16 11:02
I might have overreacted, but point that it's not really appropriate to look at single compiler version still stands. Which old versions exactly I don't know (whichever that works), but in either case options should work for multiple versions. If I was to choose between /O2 and /Ox I'd go for /Ox, because it used to appear more sensible.

**Comment by levitte** [comment] 2016-05-16 11:24
Wellllll, if the *oldest* I could find a manual for (for VS2005, on msdn) matches the newest (also on msdn) in this regard, I'm going to assume that all the versions between are essentially saying the same.

If we support compilers older than VS2005, then of course, that might be different, and I'd love to check the manuals for them if reachable.

In any case, if we've been using `/Ox /O2 /Ob2` (that was the exact sequence before I changed it) and `/Ox` and `/O2` are mutually exclusive, then I assume the last one wins, so we've essentially been using `/O2 /Ob2` for a while already (and since `/Ob2` is part of both `/Ox` and `/O2`, it's a no-op)...  *Note: for VS2005 and newer*

**Comment by levitte** [comment] 2016-05-16 11:25
Basically, it seems the currently reachable manuals and you do not say the same thing.

**Comment by dot-asm** [comment] 2016-05-16 12:01
> the currently reachable manuals and you do not say the same thing.

Totally possible. Actually at it turns out the combination of flags originate from pre-OpenSSL era. So that what I likely to recall is looking and trying to make sense of it and at least noting that /Ob2 is amendment for /Ox, as it was originally b1. As for reachability of documentation. One has to recognize that we are talking about time when it was available to only MSDN subscribers (which I was not) on CD-ROM (which are all thrown away by now). But all right, I'm convinced that one can argue that /O2 can serve as replacement for all of them, sorry about noise. One can also say that even though /Ox *might* be preferable we should stick with whatever we used for that long. Once again, sorry about noise.

**Comment by richsalz** [comment] 2016-05-16 12:15
Nice feature, not going to happen in this release we still have too many real bugs to fix.

**Comment by dot-asm** [comment] 2016-05-16 12:21
By "we should stick with whatever we used for that long" I meant /O2, as I for one don't see problem with omitting some options  even in upcoming release...

**Comment by levitte** [comment] 2016-05-16 12:40
> Once again, sorry about noise.

No need for appologies, it's good that we hammer these things out, so we get on the same page.

**Comment by levitte** [comment] 2016-05-16 12:41
> Nice feature, not going to happen in this release we still have too many real bugs to fix.

I have *no* idea what you're talking about...

**Comment by richsalz** [comment] 2016-05-16 12:55
Parallel doc builds

**Comment by levitte** [comment] 2016-05-16 13:05
Ok, @FdaSilvaYY's point fixed in #1076, along with completion of cleanup.

**Comment by levitte** [comment] 2016-05-16 17:08
This item seems to be an innocuous bug in ActiveState Perl 5.22:

- Check why Configure complains about nmake.exe and dmake.exe

This is caused by our use of `IPC::Cmd::can_run`, and somewhere deep down, ends up having `Config` interacting with `ExtUtils::MakeMaker` in some off manner, print that string and then just return to whatever level up.

Like I said, innocuous.  Complain to ActiveState.

**Comment by levitte** [comment] 2016-05-20 14:23
This last point was addressed yesterday:

* Install HTML docs

That completes resolving the issues presented here.  Time to close.

**Closed by levitte** 2016-05-20 14:23 UTC

**Comment by sav-ix** [comment] 2016-05-20 17:42
Compared recent OpenSSL builds using Mings-64 and MSVC and here feedback on PRs: https://github.com/openssl/openssl/commit/e990ec5234d9daad66359833c40e4536d7fce499 , https://github.com/openssl/openssl/commit/2bc57c88d852d83ee31f68f5b84b36d54b4c3dc4

- Mingw-w64 installation contain files:
```
bin/c_rehash
ssl/misc/c_hash
ssl/misc/c_info
ssl/misc/c_issuer
ssl/misc/c_name
ssl/misc/CA.pl
ssl/misc/tsget
```
which are missing in MSVC installation,

- Html docs in Mingw-w64 installation contain files:
```
share\doc\openssl\html\man1\c_rehash.html
share\doc\openssl\html\man3\CRYPTO_malloc.html
share\doc\openssl\html\man3\OPENSSL_cleanse.html
```
which are missing in MSVC html docs,

- Html docs in MSVC installation contain files:
```
html\man1\contributedundertheOpenSSLlicense.c_rehash.html
html\man1\OriginaltextbyJamesWestby.html
html\man3\OCSP_RESPONSE_free.html
html\man3\OCSP_response_create.html
html\man3\OCSP_request_sign.html
html\man3\OCSP_request_onereq_get0.html
html\man3\OCSP_REQUEST_free.html
html\man3\OCSP_request_onereq_count.html
html\man3\OCSP_request_add1_cert.html
html\man3\OCSP_request_add0_id.html
html\man3\OCSP_id_issuer_cmp.html
html\man3\OCSP_id_get0_info.html
html\man3\OCSP_id_cmp.html
html\man3\OCSP_copy_nonce.html
html\man3\OCSP_check_validity.html
html\man3\OCSP_check_nonce.html
html\man3\OCSP_cert_id_new.html
html\man3\OCSP_CERTID_free.html
html\man3\OPENSSL_cleanseCRYPTO_malloc.html
html\man3\OCSP_resp_get0.html
html\man3\OCSP_response_get1_basic.html
html\man3\OCSP_single_get0_status.html
html\man3\OCSP_resp_find.html
html\man3\OCSP_resp_count.html
html\man3\OCSP_resp_find_status.html
html\man3\OCSP_basic_add1_nonce.html
```
which are missing in Mingw-w64 html docs,

- All files in html docs directory of Mingw-w64 installation contain empty tags:
```
<title></title>
```

while all files in html docs directory of MSVC installation contain appropriate text inside that tags,

- Some files in html docs directory of Mingw-w64 installation contain simple text, eg:
```
<pre><code> #include &lt;openssl/evp.h&gt;

 EVP_CIPHER_CTX *EVP_CIPHER_CTX_new(void);
```

while the same text in html docs directory of MSVC installation would be:
```
<pre><code> <span class="comment">#include &lt;openssl/evp.h&gt;</span>
 
 <span class="variable">EVP_CIPHER_CTX</span> <span class="variable">*EVP_CIPHER_CTX_new</span><span class="operator">(</span><span class="variable">void</span><span class="operator">);</span>
```

- MSVC builds doesn't utilize all CPU cores during documentation build, unlike during binaries build using MSVC, or documentation build using Mingw-w64,

- Noise in stderr still exists:
```
 	link /nologo /debug /dll  /implib:libcrypto.lib /out:libcrypto-1_1-x64.dll /def:libcrypto-1_1-x64.def @C:\Users\user\AppData\Local\Temp\nm8719.tmp || (DEL /Q libcrypto.* libcrypto-1_1-x64.* && EXIT 1)
   Creating library libcrypto.lib and object libcrypto.exp
	DEL /Q /F apps\libcrypto-1_1-x64.dll
Could Not Find c:\libOPENSSL-1.1.0-dev\src\apps\libcrypto-1_1-x64.dll
	DEL /Q /F test\libcrypto-1_1-x64.dll
Could Not Find c:\libOPENSSL-1.1.0-dev\src\test\libcrypto-1_1-x64.dll
	COPY libcrypto-1_1-x64.dll apps
        1 file(s) copied.

[snip]

   Creating library libssl.lib and object libssl.exp
	DEL /Q /F apps\libssl-1_1-x64.dll
Could Not Find c:\libOPENSSL-1.1.0-dev\src\apps\libssl-1_1-x64.dll
	DEL /Q /F test\libssl-1_1-x64.dll
Could Not Find c:\libOPENSSL-1.1.0-dev\src\test\libssl-1_1-x64.dll
	COPY libssl-1_1-x64.dll apps
        1 file(s) copied.
```

Dunno whether I was wrong, when reported above, that it was fixed, or it re-appeared because of some reason. Since `/Q` switch is not enough to silence errors, could be different solutions for this flaw:
- send `DEL` errors to `nul`,
- replace `DEL` commands with condition `if exist apps\libssl-1_1-x64.dll (DEL ...)`, etc.

Some of issues above could describe expected behavior. In such case no need to reply on them.

**Comment by levitte** [comment] 2016-05-20 18:56
I would appreciate it if a new issue was created instead of continuing on one that's closed. Please?
