### ISSUE TITLE
Support for Intel SHA extensions (Goldmont PCUs) possibly broken

### ISSUE THREAD

**Issue by Posolsvetla** [openssl/openssl#2975] opened 2017-03-17 13:09 UTC
Verification of signature of EC DH server parameters in Server Key Exchange fails for some servers (server certificates) for no obvious reason on Goldmont PCUs.
I was able to track down the issue until this line of source code:
https://github.com/openssl/openssl/blob/OpenSSL_1_0_2-stable/crypto/evp/p_verify.c#L90
The pcapng capture example: [tcp_stream_135_cut.zip](https://github.com/openssl/openssl/files/850560/tcp_stream_135_cut.zip)
Please note log reports in there in these packet comments:
- frame 10: Alert to be sent to the server (not actually sent)
- frame 11: error:140EC07B:SSL routines:SSL2_READ_INTERNAL:bad signature
- frame 12: error:0606C0B0:digital envelope routines:EVP_VerifyFinal:reason(176); custom added after abovementioned line if (i <= 0)

The workaround which helped with this issue was to disable the use of Intel SHA extensions via OPENSSL_ia32cap environment variable.

Additional info:
- HW: ACER Aspire ES1-533
- OS: Windows 10 Pro 64bit
- OpenSSL 1.0.2 as a client

Please let me know if additional info is needed. I can provide several more pcapng captures if necessary.

**Comment by dot-asm** [comment] 2017-03-20 10:57
Please clarify what exact version was used, i.e. even the letter after 1.0.2. Trouble is that there was Windows-specific fix in July, so that you need at least 1.0.2i. Is it custom application or openssl s_client? If latter, what was the command line? Thing is that judging from server_name extension from Client Hello, you tried to communicate with y3.ggpht.com, but I failed to reproduce the problem with s_client with -connect option alone (though it might depend on geographic location). However, I managed to identify a bug in AES-NI-SHA stitches, so that you should also test #2992.

**Comment by Posolsvetla** [comment] 2017-03-21 06:58
Hi,
it was 1.0.2k tag statically built into a custom application;
as for test of #2992, it is a little problematic, as the issue manifested itself only at the user of the application, I did not reproduced it myself. I will see what I can do here, it will definitelly take some time to get the test result (if any).

**Comment by dot-asm** [comment] 2017-03-22 10:07
Basically question is if there is any other problem *besides* #2992. Just in case #2992 is closed, because it's committed.

**Comment by dot-asm** [comment] 2017-03-27 08:43
I'm inclined to close this with suggestion that if there is another problem, then a new report can be submitted.

**Closed** 2017-03-29 10:02 UTC
