### ISSUE TITLE
Spurious s_server warning

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#15607] opened 2021-06-03 10:06 UTC
s_server seems to be confused over its certificate and appears to try and parse it as DH params. There is a strange warning message appearing. It seems to just ignore it and carry on anyway:

````
$ openssl s_server -cert server.pem
Could not read params of DH parameters from server.pem
C0D70FB5687F0000:error:1608010C:STORE routines:ossl_store_handle_load_result:unsupported:crypto/store/store_result.c:151:
Using default temp DH parameters
ACCEPT
````

**Comment by beldmit** [comment] 2021-06-03 10:13
See also #15071

**Comment by t8m** [comment] 2021-06-03 15:12
Yes, this is just duplicate of #15071. Closing as such.

**Closed by t8m** 2021-06-03 15:12 UTC
Labels: triaged: bug
