### ISSUE TITLE
QUIC Server branch - leaks detected in Fuzz-checker CI

### ISSUE THREAD

**Issue by t8m** [openssl/openssl#25387] opened 2024-09-05 07:13 UTC
See: https://github.com/openssl/openssl/actions/runs/10715419021/job/29710840444

**Comment by nhorman** [comment] 2024-09-05 20:54
Attempted to reproduce on an ubuntu 22.04 VM and was not able to do so with the config from the CI run.

I did however notice that its always happening down a path from qtest_create_quic_connection_ex, rather than from SSL_connect.  I'm wondering if ossl_quic_tserver_free isn't freeing up the init_buf the way SSL_free does

**Comment by nhorman** [comment] 2024-10-03 08:32
@t8m did you manage to get any more insight on whats going on here?

**Comment by t8m** [comment] 2024-10-04 08:08
Nope, unfortunately not.

**Comment by nhorman** [comment] 2024-10-04 08:13
yeah, nor I

**Comment by vavroch2010** [comment] 2024-10-21 12:16
@Sashan please have a look and tell us what needs to be done

**Comment by nhorman** [comment] 2024-11-07 19:45
so, I've looked back through our CI history, and this has only happened once, and not again in the intervening 2 months since it was noted.  Given that we can't reproduce, and the error isn't appearing again, I'm closing this until such time as we get a reliable error

**Closed by nhorman** 2024-11-07 19:45 UTC
Labels: triaged: bug, severity: regression, spike
