### ISSUE TITLE
Remove unnecessary racially offensive terms from code

### ISSUE THREAD

**Issue by rita-anderson** [openssl/openssl#12148] opened 2020-06-14 19:33 UTC
Trigger warning: discussion about racism below.

In [multiple](https://github.com/openssl/openssl/blob/33388b44b67145af2181b1e9528c381c8ea0d1b6/crypto/sha/asm/sha256-mb-x86_64.pl#L545) [points](https://github.com/openssl/openssl/blob/33388b44b67145af2181b1e9528c381c8ea0d1b6/crypto/aes/asm/aesni-sha256-x86_64.pl#L1552) [in](https://github.com/openssl/openssl/blob/33388b44b67145af2181b1e9528c381c8ea0d1b6/crypto/aes/asm/aesni-sha1-x86_64.pl#L1820) [the](https://github.com/openssl/openssl/blob/33388b44b67145af2181b1e9528c381c8ea0d1b6/crypto/aes/asm/aesni-sha1-x86_64.pl#L1824) [code](https://github.com/openssl/openssl/blob/33388b44b67145af2181b1e9528c381c8ea0d1b6/crypto/sha/asm/sha256-mb-x86_64.pl#L561) the term "black magic" is mentioned in the comments. Much like the terms "blacklist", "whitelist", and "master", which have [recently been proven to be offensive](https://twitter.com/mislav/status/1270388510684598272), we should remove mentions of this term as well. "Black magic" refers to magic used for evil purposes, and is based off the arbitrary connection between black and evil. This sends the wrong message to people and can be downright offensive. That's why I propose we remove all mentions of it from the codebase.

Disclaimer: I am not claiming that I am offended by the term, however I am sure there are many people who would be, which is why it's important to remove this term.

**Comment by YovanoOrman** [comment] 2020-06-14 19:36
This gets an easy +1 from me. I think that the entire concept of "black is bad" is just another type of racism, still in use since it was [first conceptualized](https://www.patheos.com/blogs/starandsnake/2018/05/is-the-term-black-magic-racist/) in the Enlightenment Era. This doesn't trigger me personally but I feel like it might offend other people.

**Comment by richsalz** [comment] 2020-06-14 21:03
Please see #12089 which does all of the above.  There is discussion going on there, and the OpenSSL project team is deciding whether to approve this or not.

**Comment by LevitatingBusinessMan** [comment] 2020-06-15 13:16
@rita-anderson @YovanoOrman you two litterally aren't even developers. @rita-anderson the first thing you did after making your account was writing this issue, after that you forked some repositories and uploaded a "hello world" html page. Both of your accounts are a day old and only have forks on them.

**Comment by amine322** [comment] 2020-06-15 13:21
@rita-anderson Thank you for being offended on behalf of people. I am sure the community will be grateful of your (and other 1 day old accounts) work trying to change something that has no racist connotation, and will have no impact on the current climate upon changing it.

**Comment by Burday** [comment] 2020-06-15 13:21
Who would've thought that people that don't have a clue about shit in IT are telling us how we are racist...

**Comment by mattcaswell** [comment] 2020-06-15 13:23
Closing this as a dupe of #12089

**Closed by mattcaswell** 2020-06-15 13:23 UTC
Labels: issue: bug report
