### ISSUE TITLE
openssl pkcs7 to pkcs12 issue

### ISSUE THREAD

**Issue by sljesra** [openssl/openssl#7148] opened 2018-09-07 08:20 UTC
Hi,

I am trying to convert pkcs7 certificate (*.p7b) format to pkcs12 using following commands.
After the conversion, when try to import it shows 0 entries imported.

openssl pkcs7 -print_certs -in certifcate.p7b -out certificate.cer
openssl pkcs12 -export -in certificate.cer -nokeys -out certificate.pfx
--> not using any private key so used "-nokeys".

keytool -importkeystore -destkeystore 123.jks -deststoretype jks -srckeystore certificate.pfx -srcstoretype pkcs12
Enter destination keystore password:
Re-enter new password:
Enter source keystore password:
Import command completed:  0 entries successfully imported, 0 entries failed or cancelled

OS is RHEL 5.

**Comment by levitte** [comment] 2018-09-09 00:12
I have no idea what `keytool` demands, but you can verify the contents of `certificate.pfx` like this:

```
openssl pkcs12 -in certificate.pfx -info
```

If the output corresponds to what you're expecting (i.e. a single certificate), then it's possible the issue is with `keytool`.  In that case, we cannot help you, you'll have to turn whoever made it.

**Comment by t8m** [comment] 2021-05-18 10:13
I am just closing this as there was no follow up response from the reporter.

**Closed by t8m** 2021-05-18 10:13 UTC
Labels: triaged: question
