### ISSUE TITLE
openssl s_client shows "Server did acknowledge servername extension" even if server didn't

### ISSUE THREAD

**Issue by tatsuhiro-t** [openssl/openssl#3332] opened 2017-04-27 12:23 UTC
When I send a server name which server does not recognize (in OpenSSL programming, SSL_TLSEXT_ERR_NOACK is returned from callback set by SSL_CTX_set_tlsext_servername_callback in server side) using `openssl s_client`, it still shows "Server did acknowledge servername extension."

**Comment by tatsuhiro-t** [comment] 2017-04-27 12:38
It seems that [ssl_servername_cb](https://github.com/openssl/openssl/blob/b12ae4a912a19cbab8d993e61114e65fce0d1834/apps/s_client.c#L205) gets called even if server_name extension is not present in SH.
SSL_get_servername() just echos back the hostname s_client set, so unless it is resumed session, it always thinks that server recognized sni.

I think that the possible fix is that checking |sent| parameter in final_server_name, and if it is zero, don't call callback.

**Comment by mattcaswell** [comment] 2017-04-27 13:41
The code that displays that message shouldn't be there at all. This is what it looks like in 1.0.2:

    #if 0                           /* This test doesn't really work as intended
                                     * (needs to be fixed) */
    # ifndef OPENSSL_NO_TLSEXT
                    if (servername != NULL && !SSL_session_reused(con)) {
                        BIO_printf(bio_c_out,
                                   "Server did %sacknowledge servername extension.\n",
                                   tlsextcbp.ack ? "" : "not ");
                    }
    # endif
    #endif

Note that comment at the start and the fact that it is "'if 0'd" out.

In the 1.1.0 branch that code got completely deleted in 75d0ebe. It then made a comeback in "the mega commit" 7e1b7485. I think it was a merge error.

**Comment by richsalz** [comment] 2017-04-27 13:48
So @mattcaswell you want a PR that fixes that merge error?

**Comment by mattcaswell** [comment] 2017-04-27 13:49
Yes, I'd like to see a PR that does that (for master and 1.1.0)

**Comment by mattcaswell** [comment] 2017-04-27 16:01
This is fixed via f2150cd.

**Closed by mattcaswell** 2017-04-27 16:01 UTC
