### ISSUE TITLE
OpenSSL 1.1.1r does not build on Windows for Android

### ISSUE THREAD

**Issue by dmitriano** [openssl/openssl#19425] opened 2022-10-17 16:30 UTC
Tried to [build OpenSSL 1.1.1r on Windows for Android](https://developernote.com/2022/10/my-attempt-to-build-openssl-for-android-on-windows/) with the following commands:

    ```
cd C:\dev\repos\openssl-1.1.1r
 
set MY_NDK_DIR=C:\Users\dmitr\AppData\Local\Android\Sdk\ndk\20.1.5948944
 
set MY_CLANG_DIR=%MY_NDK_DIR%\toolchains\llvm\prebuilt\windows-x86_64\bin
set MY_CMAKE=%MY_NDK_DIR%\prebuilt\windows-x86_64\bin\make.exe
set MY_PERL_DIR=C:\dev\PFiles\Strawberry\perl\bin
 
set PATH=%MY_CLANG_DIR%;%MY_PERL_DIR%;%PATH%
 
set "MY_ANDROID_BUILD_ABI=x86_64"
rem set "MY_ANDROID_BUILD_ABI=x86"
rem set "MY_ANDROID_BUILD_ABI=arm64"
rem set "MY_ANDROID_BUILD_ABI=arm"
 
set MY_INSTALL_ROOT_DIR=C:/dev/libs/OpenSSL-android
set MY_INSTALL_DIR=%MY_INSTALL_ROOT_DIR%/%MY_ANDROID_BUILD_ABI%
 
set ANDROID_NDK_HOME=%MY_NDK_DIR%
 
set CC=clang
 
perl Configure android-%MY_ANDROID_BUILD_ABI% -D__ANDROID_API__=23 --prefix="%MY_INSTALL_DIR%" --openssldir="%MY_INSTALL_DIR%" no-shared
    ```

bug got:

    ```
Configuring OpenSSL version 1.1.1r (0x1010112fL) for android-x86_64
Using os-specific seed configuration
no NDK clang on $PATH at (eval 11) line 139.
    ```

added `print $ENV{PATH};` to `openssl-1.1.1r\Configurations\15-android.conf` and surprisingly noticed that it displays something strange:

`C:\Users\dmitr\AppData\Local\Android\Sdk\ndk\201~1.594\TOOLCH~1\llvm\prebuilt\WINDOW~1\bin\clang.EXEC:\Users\dmitr\AppData\Local\Android\Sdk\ndk\20.1.5948944\toolchains\llvm\prebuilt\windows-x86_64\bin;C:\dev\PFiles\Strawberry\perl\bin`

while my PATH in Windows Command Prompt is:

`C:\Users\dmitr\AppData\Local\Android\Sdk\ndk\20.1.5948944\toolchains\llvm\prebuilt\windows-x86_64\bin;C:\dev\PFiles\Strawberry\perl\bin`

so `which("clang")` is in 8.3 format while `$ndk` is not and the condition `if (which("clang") =~ m|^$ndk/.*/prebuilt/([^/]+)/|)` is always false.
`

**Comment by t8m** [comment] 2022-10-17 17:04
Does 1.1.1q build for you, i.e. is this a regression?

**Comment by dmitriano** [comment] 2022-10-17 17:18
> Does 1.1.1q build for you, i.e. is this a regression?

No, I did not try 1.1.1q.

Smart people say that it can be [something related to IPC::Cmd](https://stackoverflow.com/a/74100775/9261322).

**Comment by bernd-edlinger** [comment] 2022-10-18 09:59
can you change  this path name ...\20.1.5948944\toolchains\ to some 8.3 - names?
or alternatively `set ANDROID_NDK_HOME=C:\Users\dmitr\AppData\Local\Android\Sdk\ndk\201~1.594\TOOLCH~1`

**Comment by t8m** [comment] 2023-04-04 10:32
The configure for android IMO does not support backslashes in paths and that makes building OpenSSL for android on Windows unsupported.

**Comment by mattcaswell** [comment] 2024-01-31 11:30
Closing since this is marked as resolved.

**Closed by mattcaswell** 2024-01-31 11:30 UTC
Labels: triaged: question, resolved: answered
