### ISSUE TITLE
Substracting/rejecting CHACHA20 from cipher suite list is not supported

### ISSUE THREAD

**Issue by mvorisek** [openssl/openssl#9690] opened 2019-08-24 23:30 UTC
Current behaviour:

```
root@debian:~# openssl version
OpenSSL 1.1.1c  28 May 2019
root@debian:~# openssl ciphers -V 'CHACHA20'
          0x13,0x02 - TLS_AES_256_GCM_SHA384  TLSv1.3 Kx=any      Au=any  Enc=AESGCM(256) Mac=AEAD
          0x13,0x03 - TLS_CHACHA20_POLY1305_SHA256 TLSv1.3 Kx=any      Au=any  Enc=CHACHA20/POLY1305(256) Mac=AEAD
          0x13,0x01 - TLS_AES_128_GCM_SHA256  TLSv1.3 Kx=any      Au=any  Enc=AESGCM(128) Mac=AEAD
          0xCC,0xA9 - ECDHE-ECDSA-CHACHA20-POLY1305 TLSv1.2 Kx=ECDH     Au=ECDSA Enc=CHACHA20/POLY1305(256) Mac=AEAD
          0xCC,0xA8 - ECDHE-RSA-CHACHA20-POLY1305 TLSv1.2 Kx=ECDH     Au=RSA  Enc=CHACHA20/POLY1305(256) Mac=AEAD
          0xCC,0xAA - DHE-RSA-CHACHA20-POLY1305 TLSv1.2 Kx=DH       Au=RSA  Enc=CHACHA20/POLY1305(256) Mac=AEAD
          0xCC,0xAE - RSA-PSK-CHACHA20-POLY1305 TLSv1.2 Kx=RSAPSK   Au=RSA  Enc=CHACHA20/POLY1305(256) Mac=AEAD
          0xCC,0xAD - DHE-PSK-CHACHA20-POLY1305 TLSv1.2 Kx=DHEPSK   Au=PSK  Enc=CHACHA20/POLY1305(256) Mac=AEAD
          0xCC,0xAC - ECDHE-PSK-CHACHA20-POLY1305 TLSv1.2 Kx=ECDHEPSK Au=PSK  Enc=CHACHA20/POLY1305(256) Mac=AEAD
          0xCC,0xAB - PSK-CHACHA20-POLY1305   TLSv1.2 Kx=PSK      Au=PSK  Enc=CHACHA20/POLY1305(256) Mac=AEAD
root@debian:~# openssl ciphers -V '!CHACHA20'
Error in cipher list
140593009325184:error:1410D0B9:SSL routines:SSL_CTX_set_cipher_list:no cipher match:../ssl/ssl_lib.c:2549:
root@debian:~# openssl ciphers -V 'ECDH+AESGCM'
          0x13,0x02 - TLS_AES_256_GCM_SHA384  TLSv1.3 Kx=any      Au=any  Enc=AESGCM(256) Mac=AEAD
          0x13,0x03 - TLS_CHACHA20_POLY1305_SHA256 TLSv1.3 Kx=any      Au=any  Enc=CHACHA20/POLY1305(256) Mac=AEAD
          0x13,0x01 - TLS_AES_128_GCM_SHA256  TLSv1.3 Kx=any      Au=any  Enc=AESGCM(128) Mac=AEAD
          0xC0,0x2C - ECDHE-ECDSA-AES256-GCM-SHA384 TLSv1.2 Kx=ECDH     Au=ECDSA Enc=AESGCM(256) Mac=AEAD
          0xC0,0x30 - ECDHE-RSA-AES256-GCM-SHA384 TLSv1.2 Kx=ECDH     Au=RSA  Enc=AESGCM(256) Mac=AEAD
          0xC0,0x2B - ECDHE-ECDSA-AES128-GCM-SHA256 TLSv1.2 Kx=ECDH     Au=ECDSA Enc=AESGCM(128) Mac=AEAD
          0xC0,0x2F - ECDHE-RSA-AES128-GCM-SHA256 TLSv1.2 Kx=ECDH     Au=RSA  Enc=AESGCM(128) Mac=AEAD
root@debian:~# openssl ciphers -V 'ECDH+AESGCM:!CHACHA20'
          0x13,0x02 - TLS_AES_256_GCM_SHA384  TLSv1.3 Kx=any      Au=any  Enc=AESGCM(256) Mac=AEAD
          0x13,0x03 - TLS_CHACHA20_POLY1305_SHA256 TLSv1.3 Kx=any      Au=any  Enc=CHACHA20/POLY1305(256) Mac=AEAD
          0x13,0x01 - TLS_AES_128_GCM_SHA256  TLSv1.3 Kx=any      Au=any  Enc=AESGCM(128) Mac=AEAD
          0xC0,0x2C - ECDHE-ECDSA-AES256-GCM-SHA384 TLSv1.2 Kx=ECDH     Au=ECDSA Enc=AESGCM(256) Mac=AEAD
          0xC0,0x30 - ECDHE-RSA-AES256-GCM-SHA384 TLSv1.2 Kx=ECDH     Au=RSA  Enc=AESGCM(256) Mac=AEAD
          0xC0,0x2B - ECDHE-ECDSA-AES128-GCM-SHA256 TLSv1.2 Kx=ECDH     Au=ECDSA Enc=AESGCM(128) Mac=AEAD
          0xC0,0x2F - ECDHE-RSA-AES128-GCM-SHA256 TLSv1.2 Kx=ECDH     Au=RSA  Enc=AESGCM(128) Mac=AEAD
```

Expected behaviour:

The last command is expected to produce a list with cipher suites without the `0x13,0x03 - TLS_CHACHA20_POLY1305_SHA256 TLSv1.3` line.

Additional issue observations:

- As can be seen in the first two commands, the `CHACHA20` keyword works only to include the ChaCha20, but exclude with `!` or `-` does not work.
- `-ciphersuites` switch can be used to set TLS 1.3 cipher suites, but this option can not be set from many softwares like nginx which has only `ssl_ciphers` option, see http://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_ciphers . Exclude from the standard cipher list needs to be supported for every cipher list keyword.

**Comment by richsalz** [comment] 2019-08-24 23:45
This is not a bug.  The TLS 1.3 cipher suites are VERY VERY different from earlier versions of the protocol, and OpenSSL made a conscious decision to keep them separate.  Sorry, but nginx and others will have to support the new keyword/setting.

**Comment by mattcaswell** [comment] 2019-08-27 13:37
As per @richsalz's comment this is expected behaviour. You must configure the TLSv1.3 ciphersuites separately to the TLSv1.2 (and below) ones. There was much debate about this issue, and the various alternatives to it, and this route was decided as the least bad option.

Closing this issue.

**Closed by mattcaswell** 2019-08-27 13:37 UTC
Labels: bug

**Comment by niya3** [comment] 2021-07-21 12:52
jfyi future readers: `openssl ciphers -ciphersuites` now accepts `:`-separated list of TLSv1.3 ciphers fullnames only and doesn't allow any kind of magic like `+` or `!` or anything like that

https://wiki.openssl.org/index.php/TLS1.3#Ciphersuites
