### ISSUE TITLE
compilation error in android-ndk-r19c

### ISSUE THREAD

**Issue by Miteshmakwana73** [openssl/openssl#8841] opened 2019-04-29 10:16 UTC
I am getting this error while compiling project

```
ui_openssl.c:(.text+0x68): undefined reference to `stdin'
ui_openssl.c:(.text+0x6c): undefined reference to `stdin'
ui_openssl.c:(.text+0x9c): undefined reference to `stderr'
ui_openssl.c:(.text+0xa0): undefined reference to `stderr'
/home/jenya1/Downloads/baresip-studio-master/app/src/main/cpp/../../../../distribution/openssl/lib/arm64-v8a/libcrypto.a(libcrypto-lib-ui_openssl.o): In function `close_console':
ui_openssl.c:(.text+0x374): undefined reference to `stdin'
ui_openssl.c:(.text+0x378): undefined reference to `stdin'
ui_openssl.c:(.text+0x3a0): undefined reference to `stderr'
ui_openssl.c:(.text+0x3a4): undefined reference to `stderr'
```

full Log error
[error.txt](https://github.com/juha-h/baresip-studio/files/3126255/error.txt)

**Comment by vilvarajintel** [comment] 2019-04-30 09:44
from you error log I see that the issue is from the NDK side, (the NDK is recent but the compiler version is for an older API level)
some issues that are related to these are documented in the following issues
https://github.com/android-ndk/ndk/issues/410
https://github.com/android-ndk/ndk/issues/272

knowing the build environment will help triage the issue. AFAIK this is related to the libc version present in the NDK

**Comment by vilvarajintel** [comment] 2019-04-30 11:41
please update and close this issue if the solution is not from the OPENSSL project.

**Comment by Miteshmakwana73** [comment] 2019-04-30 12:03
I don't find any solution still, it's okay it's not the OpenSSL issue

**Closed** 2019-04-30 12:02 UTC
