### ISSUE TITLE
87bea6550ae0dda7c40937cff2e86cc2b0b09491 (Stable 1.1.1) breaks compilation

### ISSUE THREAD

**Issue by LordOfDragons** [openssl/openssl#9839] opened 2019-09-10 07:02 UTC
The commit 87bea6550ae0dda7c40937cff2e86cc2b0b09491 in the Stable 1.1.1 branch breaks compiling (in this case static compiling OpenSSL):

```
/build/contrib/build/openssl/unix64/../../../openssl/crypto/evp/e_aes.c:276: undefined reference to `aesni_set_decrypt_key'
/usr/bin/ld: /build/contrib/build/openssl/unix64/../../../openssl/crypto/evp/e_aes.c:278: undefined reference to `aesni_decrypt'
/usr/bin/ld: /build/contrib/build/openssl/unix64/../../../openssl/crypto/evp/e_aes.c:280: undefined reference to `aesni_cbc_encrypt'
/usr/bin/ld: /build/contrib/build/openssl/unix64/../../../openssl/crypto/evp/e_aes.c:282: undefined reference to `aesni_set_encrypt_key'
/usr/bin/ld: /build/contrib/build/openssl/unix64/../../../openssl/crypto/evp/e_aes.c:284: undefined reference to `aesni_encrypt'
/usr/bin/ld: /build/contrib/build/openssl/unix64/../../../openssl/crypto/evp/e_aes.c:286: undefined reference to `aesni_cbc_encrypt'
/usr/bin/ld: /build/contrib/build/openssl/unix64/../../../openssl/crypto/evp/e_aes.c:288: undefined reference to `aesni_ctr32_encrypt_blocks'
/usr/bin/ld: ./libcrypto.a(e_aes.o): in function `aesni_cbc_cipher':
/build/contrib/build/openssl/unix64/../../../openssl/crypto/evp/e_aes.c:304: undefined reference to `aesni_cbc_encrypt'
/usr/bin/ld: ./libcrypto.a(e_aes.o): in function `aesni_ecb_cipher':
/build/contrib/build/openssl/unix64/../../../openssl/crypto/evp/e_aes.c:319: undefined reference to `aesni_ecb_encrypt'
/usr/bin/ld: ./libcrypto.a(e_aes.o): in function `aesni_gcm_init_key':
/build/contrib/build/openssl/unix64/../../../openssl/crypto/evp/e_aes.c:352: undefined reference to `aesni_set_encrypt_key'
/usr/bin/ld: /build/contrib/build/openssl/unix64/../../../openssl/crypto/evp/e_aes.c:354: undefined reference to `aesni_encrypt'
/usr/bin/ld: /build/contrib/build/openssl/unix64/../../../openssl/crypto/evp/e_aes.c:355: undefined reference to `aesni_ctr32_encrypt_blocks'
/usr/bin/ld: ./libcrypto.a(e_aes.o): in function `aesni_xts_init_key':
/build/contrib/build/openssl/unix64/../../../openssl/crypto/evp/e_aes.c:407: undefined reference to `aesni_set_encrypt_key'
/usr/bin/ld: /build/contrib/build/openssl/unix64/../../../openssl/crypto/evp/e_aes.c:409: undefined reference to `aesni_encrypt'
/usr/bin/ld: /build/contrib/build/openssl/unix64/../../../openssl/crypto/evp/e_aes.c:410: undefined reference to `aesni_xts_encrypt'
/usr/bin/ld: /build/contrib/build/openssl/unix64/../../../openssl/crypto/evp/e_aes.c:412: undefined reference to `aesni_set_decrypt_key'
/usr/bin/ld: /build/contrib/build/openssl/unix64/../../../openssl/crypto/evp/e_aes.c:414: undefined reference to `aesni_decrypt'
/usr/bin/ld: /build/contrib/build/openssl/unix64/../../../openssl/crypto/evp/e_aes.c:415: undefined reference to `aesni_xts_decrypt'
/usr/bin/ld: /build/contrib/build/openssl/unix64/../../../openssl/crypto/evp/e_aes.c:418: undefined reference to `aesni_set_encrypt_key'
/usr/bin/ld: /build/contrib/build/openssl/unix64/../../../openssl/crypto/evp/e_aes.c:421: undefined reference to `aesni_encrypt'
/usr/bin/ld: ./libcrypto.a(e_aes.o): in function `aesni_ccm_init_key':
/build/contrib/build/openssl/unix64/../../../openssl/crypto/evp/e_aes.c:445: undefined reference to `aesni_set_encrypt_key'
/usr/bin/ld: /build/contrib/build/openssl/unix64/../../../openssl/crypto/evp/e_aes.c:447: undefined reference to `aesni_encrypt'
/usr/bin/ld: /build/contrib/build/openssl/unix64/../../../openssl/crypto/evp/e_aes.c:449: undefined reference to `aesni_ccm64_encrypt_blocks'
/usr/bin/ld: /build/contrib/build/openssl/unix64/../../../openssl/crypto/evp/e_aes.c:449: undefined reference to `aesni_ccm64_decrypt_blocks'
/usr/bin/ld: ./libcrypto.a(e_aes.o): in function `aesni_ocb_init_key':
/build/contrib/build/openssl/unix64/../../../openssl/crypto/evp/e_aes.c:491: undefined reference to `aesni_set_encrypt_key'
/usr/bin/ld: /build/contrib/build/openssl/unix64/../../../openssl/crypto/evp/e_aes.c:493: undefined reference to `aesni_set_decrypt_key'
/usr/bin/ld: /build/contrib/build/openssl/unix64/../../../openssl/crypto/evp/e_aes.c:495: undefined reference to `aesni_ocb_encrypt'
/usr/bin/ld: /build/contrib/build/openssl/unix64/../../../openssl/crypto/evp/e_aes.c:495: undefined reference to `aesni_ocb_decrypt'
/usr/bin/ld: /build/contrib/build/openssl/unix64/../../../openssl/crypto/evp/e_aes.c:495: undefined reference to `aesni_decrypt'
/usr/bin/ld: /build/contrib/build/openssl/unix64/../../../openssl/crypto/evp/e_aes.c:495: undefined reference to `aesni_encrypt'
/usr/bin/ld: ./libcrypto.a(e_aes.o): in function `aes_gcm_tls_cipher':
/build/contrib/build/openssl/unix64/../../../openssl/crypto/evp/e_aes.c:3101: undefined reference to `aesni_ctr32_encrypt_blocks'
/usr/bin/ld: /build/contrib/build/openssl/unix64/../../../openssl/crypto/evp/e_aes.c:3101: undefined reference to `gcm_ghash_avx'
/usr/bin/ld: /build/contrib/build/openssl/unix64/../../../openssl/crypto/evp/e_aes.c:3105: undefined reference to `aesni_gcm_encrypt'
/usr/bin/ld: /build/contrib/build/openssl/unix64/../../../openssl/crypto/evp/e_aes.c:3142: undefined reference to `aesni_ctr32_encrypt_blocks'
/usr/bin/ld: /build/contrib/build/openssl/unix64/../../../openssl/crypto/evp/e_aes.c:3142: undefined reference to `gcm_ghash_avx'
/usr/bin/ld: /build/contrib/build/openssl/unix64/../../../openssl/crypto/evp/e_aes.c:3146: undefined reference to `aesni_gcm_decrypt'
/usr/bin/ld: ./libcrypto.a(e_aes.o): in function `aes_gcm_cipher':
/build/contrib/build/openssl/unix64/../../../openssl/crypto/evp/e_aes.c:3211: undefined reference to `aesni_ctr32_encrypt_blocks'
/usr/bin/ld: /build/contrib/build/openssl/unix64/../../../openssl/crypto/evp/e_aes.c:3211: undefined reference to `gcm_ghash_avx'
/usr/bin/ld: /build/contrib/build/openssl/unix64/../../../openssl/crypto/evp/e_aes.c:3217: undefined reference to `aesni_gcm_encrypt'
/usr/bin/ld: /build/contrib/build/openssl/unix64/../../../openssl/crypto/evp/e_aes.c:3255: undefined reference to `aesni_ctr32_encrypt_blocks'
/usr/bin/ld: /build/contrib/build/openssl/unix64/../../../openssl/crypto/evp/e_aes.c:3255: undefined reference to `gcm_ghash_avx'
/usr/bin/ld: /build/contrib/build/openssl/unix64/../../../openssl/crypto/evp/e_aes.c:3261: undefined reference to `aesni_gcm_decrypt'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:6300: apps/openssl] Error 1
```

Reverting right before this commit fixes the issue. Any commit after this commit breaks compiling.

_(Edit by mspncp: replaced single backquotes by triple backquotes)_

**Comment by levitte** [comment] 2019-09-10 07:18
Please run this and tell me the result:

```
perl configdata.pm -c -e
```

**Comment by levitte** [comment] 2019-09-10 08:05
I have tried configuring with `no-shared`, and had no issue.  This is on Linux x86_64.

So unless I get a little more details, @LordOfDragons, I simply cannot reproduce your issue.

**Comment by LordOfDragons** [comment] 2019-09-11 07:06
> Please run this and tell me the result:
> 
> ```
> perl configdata.pm -c -e
> ```

Here it is:
```
Command line (with current working directory = .):

    /usr/bin/perl ./Configure --debug no-dso no-shared no-threads no-ui no-zlib no-afalgeng --api=1.0.0 linux-generic64

Perl information:

    /usr/bin/perl
    5.28.1 for x86_64-linux-gnu-thread-multi

Recorded environment:

    AR = 
    ARFLAGS = 
    AS = 
    ASFLAGS = 
    BUILDFILE = 
    CC = 
    CFLAGS = 
    CPP = 
    CPPDEFINES = 
    CPPFLAGS = 
    CPPINCLUDES = 
    CROSS_COMPILE = 
    CXX = 
    CXXFLAGS = 
    HASHBANGPERL = 
    LD = 
    LDFLAGS = 
    LDLIBS = 
    MT = 
    MTFLAGS = 
    OPENSSL_LOCAL_CONFIG_DIR = 
    PERL = 
    RANLIB = 
    RC = 
    RCFLAGS = 
    RM = 
    WINDRES = 
    __CNF_CFLAGS = 
    __CNF_CPPDEFINES = 
    __CNF_CPPFLAGS = 
    __CNF_CPPINCLUDES = 
    __CNF_CXXFLAGS = 
    __CNF_LDFLAGS = 
    __CNF_LDLIBS = 
```

The config options mostly resulted from getting around compilation problems because this build is done for multiple OS, including the notorious trouble maker windows (cross mingw compiler).

**Comment by levitte** [comment] 2019-09-11 10:04
The mistake you're doing is to configure with `linux-generic64`, with which you must include `no-asm` (yeah, I know, one might argue that this should happen automatically, but it doesn't).

You would make your life easier if you configured like this:

```
$ ./config --debug no-dso no-shared no-threads no-ui no-zlib no-afalgeng --api=1.0.0
```

Or if you *must* use `./Configure` directly, use a more appropriate target, such as `linux-x86_64` or what have you...  or lastly, if you *insist* on `linux-generic64`, add `no-asm` as well.

**Comment by LordOfDragons** [comment] 2019-09-11 16:32
The problem is two-fold. First OpenSSL seems to not support "out of tree" building and we need to build for various targets at the same time. The Configure had been the only solution so far I found which worked. The same for linux-generic64. All other linux targets fail to compile. This had been the only configuration which worked at all. If you have a working configuration which allows building OpenSSL sanely out-of-tree with unix-64, unix-32, windows-64, windows-32 and arm platforms statically then I'm all ears. So far that's the best I could find.

**Comment by mattcaswell** [comment] 2019-09-11 16:39
OpenSSL absolutely supports "out of tree" building. See:

https://github.com/openssl/openssl/blob/7f0a8dc7f9c5c35af0f66aca553304737931d55f/INSTALL#L823-L859

**Comment by LordOfDragons** [comment] 2019-09-11 16:43
So far this did not work (configure fails with missing files in the source directory). That though had been on an openssl version some month ago. Did this change? I'll give this a try tomorrow.

**Comment by mattcaswell** [comment] 2019-09-11 16:45
> So far this did not work (configure fails with missing files in the source directory). That though had been on an openssl version some month ago. Did this change? I'll give this a try tomorrow.

I'm not aware of any problems in this area, and I've just tried it and it worked fine for me.

**Comment by petrovr** [comment] 2019-09-11 16:47
mattcaswell wrote:
> OpenSSL absolutely supports "out of tree" building. See:
Hmm, sure on system without links ;)

**Comment by levitte** [comment] 2019-09-11 17:13
If there are cases where out-of-source-tree configuration / build does not work, *we want to know*.
(we know that it doesn't work for 1.0.2, that support was added with the so called "unified" build for 1.1.0)

**Comment by petrovr** [comment] 2019-09-11 17:40
Richard Levitte wrote:
> If there are cases where out-of-source-tree configuration / build does not work, *we want to know*.
> (we know that it doesn't work for 1.0.2, that support was added with the so called "unified" build for 1.1.0)
> 
Let use following terminology :
(1) canonical path - path with dereferenced all links , aka realparh
(2) absolute path - path without references to current or parent 
directory, aka pwd

Program that fail on system with links:
- moc : QT Meta-Object Compiler (unless is fixed in recent releases , 
not used in last 5 years)
- libtool : 2.N(?), still fail and is not usable is some cases.

Relative path calculation based on canonical path usually produces wrong 
result.
Work-around - to add parasite symbolic links.

Roumen

**Comment by levitte** [comment] 2019-09-11 17:51
I did mean cases where *OpenSSL* configuration / build goes wrong.

**Comment by LordOfDragons** [comment] 2019-09-13 12:39
/contrib/openssl/config --debug no-dso no-shared no-threads no-zlib no-afalgeng no-asm --api=1.0.0 linux-x86_64

**Comment by levitte** [comment] 2019-09-13 12:47
Ok, so how about trying this:

```
/contrib/openssl/config --debug no-dso no-shared no-threads no-zlib no-afalgeng no-asm --api=1.0.0
```

See, there's a difference between the `config` and the `Configure` scripts.  `config` *doesn't* take a target platform argument, it figures it out from the machine you run it on, while `Configure` *requires* a target platform argument.  (as a matter of fact, when `config` has figured out the target platform, it simply calls `Configure` with that plus all its command line arguments)

**Comment by levitte** [comment] 2019-09-13 12:48
Yes, we know this is confusing, and an effort to merge the two scripts is underway

**Comment by LordOfDragons** [comment] 2019-09-13 15:01
I see. Then I need to stick with Configure since we are cross-compiling for different targets on the same machine for the same final build.

**Comment by levitte** [comment] 2019-09-13 15:50
Sure...  but if you use the generic target platform targets, you usually have to add `no-asm`, as they usually do not have assembler support.  That's the issue you had to start with.  If you want assembler support, you need to make more specific with your choices (and assembler support may still be shaky, depending on your toolchain)

**Comment by mattcaswell** [comment] 2019-12-05 11:32
This question seems to have been answered. Closing.

**Closed by mattcaswell** 2019-12-05 11:32 UTC
Labels: resolved: answered
