### ISSUE TITLE
EVP_CIPHER_CTX_copy in OSSL 3.0 not functioning as expected?

### ISSUE THREAD

**Issue by rapier1** [openssl/openssl#20978] opened 2023-05-16 20:59 UTC
I'm using OpenSSL 3.0.2 and I'm copying an EVP ctx (chacha20) to a new context with EVP_CIPHER_CTX_copy() but I'm getting an error of 
```40C7A7B06B7F0000:error:030000BE:digital envelope routines:EVP_CIPHER_CTX_copy:not able to copy ctx:../crypto/evp/evp_enc.c:1363:```

Which, I think, is indicating that the following block in evp_enc.c is raising the error:
```   
    if (in->cipher->dupctx == NULL) {
        ERR_raise(ERR_LIB_EVP, EVP_R_NOT_ABLE_TO_COPY_CTX);
        return 0;
    }
```
The code calling EVP_CIPHER_CTX_copy is called from 
```int
initialize_threadData(struct threadData * td, struct chachapoly_ctx * ctx)
{
	memset(td,0,sizeof(*td));
	if ((td->main_evp = EVP_CIPHER_CTX_new()) == NULL ||
	    (td->header_evp = EVP_CIPHER_CTX_new()) == NULL)
		goto fail;
	if (!EVP_CIPHER_CTX_copy(td->main_evp, ctx->main_evp)) {
		ERR_print_errors_fp (stderr);
		goto fail;
	}
	if (!EVP_CIPHER_CTX_copy(td->header_evp, ctx->header_evp))
		goto fail;
	if (EVP_CIPHER_CTX_iv_length(td->header_evp) != 16)
		goto fail;
	return 0;
 fail:
	free_threadData(td);
	return -1;
}
```

This function does work under OpenSSL 1.1. Has there been some change in functionality or methodology to copy the ctx? I should point out that the ctx does have additional data attached to it via EVP_CIPHER_CTX_set_app_data().

Any ideas would be helpful. 

Thanks!

**Comment by paulidale** [comment] 2023-05-16 22:06
chacha20 doesn't support the dupctx call, it ought to.

**Comment by rapier1** [comment] 2023-05-16 23:54
Crap. I was hoping that wouldn't be the case. Is it possible to extend the default provider to add the functionality? I wrote a custom provider (multi threaded AES ctr) once but I don't know the limitations.

**Comment by paulidale** [comment] 2023-05-16 23:56
It should be possible to add it.  I suspect fairly easily.

**Comment by rapier1** [comment] 2023-05-17 00:12
So being that I've not extended a provider before can you point me some place? I'm feeling it's different than writing a new one.

**Comment by paulidale** [comment] 2023-05-17 00:34
What's needed is an implementation of the `OSSL_FUNC_CIPHER_DUPCTX` entry for chacha20.

The relevant file source is: `providers/implementations/ciphers/cipher_chacha20.c`.
The PROV_CHACHA20_CTX structure will need duplication, there are pointers in the base so some uprefs etc.
Also an entry added to `ossl_chacha20_functions`.

There is hardware support on some platforms which is probably the trickiest part (because it's hard to test).

**Comment by rapier1** [comment] 2023-05-17 14:20
Is it possible to do that without actually touching the OpenSSL code? Sort of like EVP_CIPHER_meth_set to override the defined functions in providers/implementations/ciphers/cipher_chacha20.c? Now that I think about that I'm guessing opacity will make that impossible. We'd need it to be something like a settable parameter and there isn't anything like that I can see. So for an application we are distributing via binary packages we'd actually need to statically links against a custom implementation of OpenSSL. Which isn't going to be feasible in this case. If I'm mistaken about that please let me know. 

If that's the case may I make this a feature request? In the meantime, my team is going to need to look how to deal with this. As an aside - what we are doing is making a parallelized implementation of Chachapoly1305 for a high performance version of OpenSSH called HPN-SSH. We precompute the keystream data on a seperate thread and drop it into an array like struct. When we need to run a en/decipher data we can simply xor against the existing keystream. This is getting us a 15 to 25% improvement in throughput by reducing the load on the main thread. We only really need one additional thread to do this on most systems but we do need to copy the main ctx to the thread ctx.

**Comment by mattcaswell** [comment] 2023-05-17 14:23
> If that's the case may I make this a feature request? 

IMO this is really a bug that should be fixed (it is a regression). I personally think this would be ok to backport to the 3.1/3.0 branches.

Adding "help wanted" label

**Comment by alex** [comment] 2023-08-28 18:21
FWIW this issue also impacts AES-GCM

**Comment by nhorman** [comment] 2023-08-28 18:22
if you open a separate issue for that, I can take a look at it

**Comment by alex** [comment] 2023-08-28 18:24
I wasn't sure if that was desired, it was also discussedon https://github.com/openssl/openssl/issues/21853#issuecomment-1694752983 but losed as a dupe of this one.

If the OpenSSL maintainers prefer, I'm happy to open a fresh ticket though!

**Comment by t8m** [comment] 2023-08-28 18:51
I think we do not need a separate ticket - I see that all AEAD ciphers are missing dupctx.

**Comment by rapier1** [comment] 2023-08-28 18:59
I appreciate you working on this. I'm not sure when I'll have to test it out as we changed our code base to not depend on it. That said, any estimation on when this might make release status?

**Comment by alex** [comment] 2023-08-28 19:00
(For myself, I'll test it this evening)

**Closed** 2023-09-04 00:18 UTC
Labels: branch: master, help wanted, triaged: bug, branch: 3.0, severity: regression, branch: 3.1
