### ISSUE TITLE
Unable to make OCSP responder listen on IPv6, still broken in 3.4?

### ISSUE THREAD

**Issue by eap-nutanix** [openssl/openssl#25855] opened 2024-11-03 17:22 UTC
I see a couple others complaining about this years ago, but is it now expected to work in 3.4?  The documentation certainly says that it does...I've demonstrated that all the desired functionality is working with IPv4.  Now just trying to move to IPv6.

I've tried the "-port" option like this: "-port [2604:b641:1504:3103::bebe]:8888", but that yields:

    ocsp: Can't parse "[2604:b641:1504:3103::bebe]:8888" as a number

I've tried the "-url" option like this: "-url http://[2604:b641:1504:3103::bebe]:8888", and that happily starts listening on the IPv4 loopback instead of giving an error message!

Just wondering if this works for others using version 3.4 + IPv6

**Comment by t8m** [comment] 2024-11-04 10:18
Duplicate of #16204

**Closed by t8m** 2024-11-04 10:18 UTC
Labels: issue: bug report
