### ISSUE TITLE
Memory leaks on vcpkg when compiling statically

### ISSUE THREAD

**Issue by angelmixu** [openssl/openssl#5448] opened 2018-02-23 12:04 UTC
Hi people! 

I was using curl from vcpkg and found a memory leak, I created an issue on vcpkg issues ( https://github.com/Microsoft/vcpkg/issues/2851 ) and was redirected to curl repo ( https://github.com/curl/curl/issues/2323 ).
And after some testing it looks like it's a leak in OpenSSL.

After some testing (which you can see on the aforementioned issues) looks like compiling version 1.0.2n statically on Visual Studio produces a bunch of leaks which are not produced with dynamic libraries.

It happens with the compiled version with vcpkg and also with the already compiled binaries from http://slproweb.com/products/Win32OpenSSL.html

Could you take a look at it?
Tell me anything if you need any more info or test, happy to help :)

EDIT:
The test code when using slproweb's binaries was this one, as there are some link errors, and also linked against legacy_stdio_definitions.lib as suggested in https://stackoverflow.com/questions/30412951/unresolved-external-symbol-imp-fprintf-and-imp-iob-func-sdl2

```
#include <vld.h>
#include <curl/curl.h>

FILE _iob[] = { *stdin, *stdout, *stderr };

extern "C" FILE * __cdecl __iob_func(void)
{
	return _iob;
}

int main()
{
	bool testGlobal = false; 

	if (testGlobal)
	{
		curl_global_init(CURL_GLOBAL_ALL);
		curl_global_cleanup();
	}
	else
	{
		CURL* curl = curl_easy_init();
		curl_easy_cleanup(curl);
	}

    return 0;
}
```

**Comment by richsalz** [comment] 2018-02-23 16:56
Sorry you have to run around all over the place.  I read the other two issues.  We can't really comment on what a third-party binary build of OpenSSL is doing.  But it looks like one is compiled with memory debug, which introduces some overhead that isn't freed, and the other isn't.

Can you reproduce this yourself with libraries that you build?

**Comment by angelmixu** [comment] 2018-02-26 10:41
I downloaded the official source for OpenSSL 1.0.2n and I statically built using NASM as with the instructions on INSTALL.W32 file and the leaks are nearly the same.

Using the first test code I get 118 leaks using global init, and 3645 leaks on the easy case.

**Comment by bernd-edlinger** [comment] 2018-03-02 07:59
Could it be that `ENGINE_cleanup` is never called?

**Comment by angelmixu** [comment] 2018-03-02 09:20
Hi @bernd-edlinger !
ENGINE_cleanup was not called, so I called it in my application before crtdbug_exit() and there's still lots of leaks :(

**Comment by bernd-edlinger** [comment] 2018-03-02 09:29
Could check if any of the following cleanup functions are missing as well:
```
SSL_COMP_free_compression_methods();
EVP_cleanup();
CRYPTO_cleanup_all_ex_data();
ERR_remove_state(0);
ERR_free_strings();
```

**Comment by angelmixu** [comment] 2018-03-02 10:06
It's the same as before, none of those functions are called.
And if I call them there are still leaks.

**Comment by bernd-edlinger** [comment] 2018-03-02 10:14
Is curl also built statically?

**Comment by angelmixu** [comment] 2018-03-02 10:41
Yes, all is built statically.

**Comment by bernd-edlinger** [comment] 2018-03-17 20:27
You could try to call  `OPENSSL_cleanup()`

**Comment by angelmixu** [comment] 2018-03-19 12:01
@bernd-edlinger I can't find that function, looks like it doesn't exist.

**Comment by t-j-h** [comment] 2018-03-19 12:16
find . -name '*.h' |xargs grep OPENSSL_cleanup    
./include/openssl/crypto.h:void OPENSSL_cleanup(void);

The function is there ...

**Comment by bernd-edlinger** [comment] 2018-03-19 12:16
ah, sorry, that is an 1.1.0 function.
you have 1.0.2

**Comment by bernd-edlinger** [comment] 2018-03-19 12:22
so, my best guess is that you have the crypto library somehow twice in your process.
which can happen in windows, when a static library is linked to a DLL and the EXE
at the same time.

**Comment by angelmixu** [comment] 2018-03-19 12:47
Yes, I'm on 1.0.2n.
If you need any more testing just tell me, I'll be glad to try anything :)

**Comment by mattcaswell** [comment] 2018-04-30 09:34
Appears to be a 1.0.2 specific issue so moving to 1.0.2 milestone.

**Comment by fawdlstty** [comment] 2020-07-08 06:35
The problem still exists. Can it be fixed?

**Comment by t8m** [comment] 2021-06-21 12:01
1.0.2 is out of regular support. Closing.

**Closed by t8m** 2021-06-21 12:01 UTC

**Comment by paresy** [comment] 2022-06-16 08:05
You are probably impacted by this:
https://github.com/curl/curl/issues/5282
https://github.com/openssl/openssl/issues/6081
