### ISSUE TITLE
OpenSSL-3.0.0-beta1: Failed to build to powerpc, powerpc64

### ISSUE THREAD

**Issue by sebastianas** [openssl/openssl#15923] opened 2021-06-25 21:10 UTC
beta1 failed to build on powerpc and powerpc64:
Powerpc: [buildlog](https://buildd.debian.org/status/fetch.php?pkg=openssl&arch=powerpc&ver=3.0.0%7E%7Ebeta1-1&stamp=1624477540&raw=0)

```
${LDCMD:-gcc} -pthread -Wa,--noexecstack -Wall -Wa,--noexecstack -g -O2 -ffile-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -Wformat -Werror=format-security -L.  -Wl,-z,relro -Wl,-z,now \
	-o test/bad_dtls_test \
	test/bad_dtls_test-bin-bad_dtls_test.o \
	-lssl test/libtestutil.a -lcrypto -ldl -pthread -latomic 
/usr/bin/ld: ./libcrypto.a(libcrypto-lib-ppccap.o): in function `bn_mul_mont':
./build_static/../crypto/ppccap.c:73: undefined reference to `bn_mul_mont_300_fixed_n6'
/usr/bin/ld: ./build_static/../crypto/ppccap.c:75: undefined reference to `bn_mul_mont_fixed_n6'
/usr/bin/ld: ./libcrypto.a(libcrypto-lib-ppccap.o): in function `bn_mul_mont':
./build_static/../crypto/ppccap.c:73: undefined reference to `bn_mul_mont_300_fixed_n6'
/usr/bin/ld: ./build_static/../crypto/ppccap.c:75: undefined reference to `bn_mul_mont_fixed_n6'
/usr/bin/ld: ./libcrypto.a(libcrypto-lib-ppccap.o): in function `bn_mul_mont':

```
Powerpc64: [buildlog](https://buildd.debian.org/status/fetch.php?pkg=openssl&arch=ppc64&ver=3.0.0%7E%7Ebeta1-1&stamp=1624477258&raw=0)

```
gcc -fPIC -pthread -Wa,--noexecstack -Wall -DB_ENDIAN -Wa,--noexecstack -g -O2 -ffile-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -Wformat -Werror=format-security -DOPENSSL_USE_NODELETE -DOPENSSL_PIC -DOPENSSLDIR="\"/usr/lib/ssl\"" -DENGINESDIR="\"/usr/lib/powerpc64-linux-gnu/engines-3\"" -DMODULESDIR="\"/usr/lib/powerpc64-linux-gnu/ossl-modules\"" -DOPENSSL_BUILDING_OPENSSL -DNDEBUG -Wdate-time -D_FORTIFY_SOURCE=2 -c -o crypto/bn/liblegacy-lib-ppc64-mont-fixed.o crypto/bn/ppc64-mont-fixed.s
crypto/bn/ppc64-mont-fixed.s: Assembler messages:
crypto/bn/ppc64-mont-fixed.s: Error: .size expression for bn_mul_mont_fixed_n6 does not evaluate to a constant
crypto/bn/ppc64-mont-fixed.s: Error: .size expression for bn_mul_mont_300_fixed_n6 does not evaluate to a constant
gcc  -I. -Icrypto -Iinclude -Iproviders/implementations/include -Iproviders/common/include -I.. -I../crypto -I../include -I../providers/implementations/include -I../providers/common/include  -DOPENSSL_BN_ASM_MONT -fPIC -pthread -Wa,--noexecstack -Wall -DB_ENDIAN -Wa,--noexecstack -g -O2 -ffile-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -Wformat -Werror=format-security -DOPENSSL_USE_NODELETE -DOPENSSL_PIC -DOPENSSLDIR="\"/usr/lib/ssl\"" -DENGINESDIR="\"/usr/lib/powerpc64-linux-gnu/engines-3\"" -DMODULESDIR="\"/usr/lib/powerpc64-linux-gnu/ossl-modules\"" -DOPENSSL_BUILDING_OPENSSL -DNDEBUG -Wdate-time -D_FORTIFY_SOURCE=2 -MMD -MF crypto/des/liblegacy-lib-des_enc.d.tmp -MT crypto/des/liblegacy-lib-des_enc.o -c -o crypto/des/liblegacy-lib-des_enc.o ../crypto/des/des_enc.c
make[3]: *** [Makefile:12209: crypto/bn/liblegacy-lib-ppc64-mont-fixed.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: Leaving directory '/<<PKGBUILDDIR>>/build_static'

```
The last succcessfull build I have is alpha16. The build on powerpc64le passed so it seems to affect only BE.

It still happens on HEAD as of today (now).
According to git bisect, the ppc64 issue was introduced in commit 0d40ca47bd86e74a95c3a2f5fb6c67cdbee93c79. 
This is "gcc version 10.2.1 20210110 (Debian 10.2.1-6)" in both cases.

Sebastian

**Comment by t8m** [comment] 2021-06-28 08:36
Is it still happening with master as of today? (52f5407dc1ed67d0baace3c39b69bc9f07f4454a) there was a substantial PPC related change merged in.

**Comment by sebastianas** [comment] 2021-06-30 06:02
On 2021-06-28 01:36:35 [-0700], Tomáš Mráz wrote:
> Is it still happening with master as of today? (52f5407dc1ed67d0baace3c39b69bc9f07f4454a) there was a substantial PPC related change merged in.

Both issues still exist on linux-ppc/ppc64 as of today
(5e56f4587de2f2e06c079272fa4d6712d56dbcf0).

Sebastian

**Comment by slontis** [comment] 2021-07-01 02:46
Are we going to have to revert the changes to before the assembler updates were made?

**Comment by slontis** [comment] 2021-07-01 02:49
@martin-schwenke - any chance you can have a look at this?

**Comment by martin-schwenke** [comment] 2021-07-01 03:48
Looking at it now...

**Comment by martin-schwenke** [comment] 2021-07-01 06:12
For the  `ppc64` build, can you please try the fixes in [this branch](https://github.com/martin-schwenke/openssl/tree/master-fixes)?

The `powerpc` fix looks simple.  I'm checking to see if I have a machine/VM to test that build.  Either way, I'll add a potential patch to the above branch within about an hour.

Depending on the release date, are you considering OpenSSL 3.0.0 for Debian bullseye?  I'm just trying to determine the urgency.  If this is only currently for experimental then I'll stop and breathe...  ;-)

Those of us working OpenSSL optimisations for Power are experienced Open Source developers (and I'm typing this from a laptop running Debian bullseye).  However, we're tripping over issues with the different variations of Power platforms... and learning quickly...  ;-)

**Comment by paulidale** [comment] 2021-07-01 06:17
OpenSSL 3.0 and Debian bullseye is a decision for the Debian developers not the OpenSSL project.  My guess would be that it won't make it.

Odd platforms are a way of life for OpenSSL :smiley_cat:

**Comment by kroeckx** [comment] 2021-07-01 06:22
There is no way to get 3.0 in bullseye. We're current frozen. If
we wanted to get it in bullseye, 3.0 really had to be released
in January or earlier.

**Comment by paulidale** [comment] 2021-07-01 06:27
Thanks @kroeckx

**Comment by martin-schwenke** [comment] 2021-07-01 06:56
> There is no way to get 3.0 in bullseye. We're current frozen. If we wanted to get it in bullseye, 3.0 really had to be released in January or earlier.

I was pretty sure that was the case, just making sure I'm not blocking something urgent...  thanks!

**Comment by martin-schwenke** [comment] 2021-07-01 08:07
> OpenSSL 3.0 and Debian bullseye is a decision for the Debian developers not the OpenSSL project. My guess would be that it won't make it.

Sorry, should have made it clear that I was asking the issue reporters...  :-)
 
> Odd platforms are a way of life for OpenSSL smiley_cat

Yeah, I'm learning that.  We should have access to all these platforms.  It is just a matter of learning what quirks exist so that I/we know the mix of platforms to test on...  ;-)

**Comment by gv74** [comment] 2021-07-01 08:59
>Perhaps @gv74 is able to test build on AIX if time permits?

I see no issues during make/make test with the latest version from git.openssl.org.

**Comment by martin-schwenke** [comment] 2021-07-01 09:04
> > Perhaps @gv74 is able to test build on AIX if time permits?
> 
> I see no issues during make/make test with the latest version from git.openssl.org.

@gv74 I have some fixes for Linux big-endian at https://github.com/martin-schwenke/openssl/tree/master-fixes but my AIX test environment has gone a little bit crazy.  I don't think the fixes will break AIX, but if you're able to test them then I would be very grateful...

**Comment by t8m** [comment] 2021-07-01 09:04
> OK, I believe that my `master-fixes` branch fixes both problems.

Could you please submit a PR?

**Comment by martin-schwenke** [comment] 2021-07-01 09:12
> > OK, I believe that my `master-fixes` branch fixes both problems.
> 
> Could you please submit a PR?

Sure, I was going to wait for more testing, but it makes sense to discuss testing and results in a PR...

**Comment by gv74** [comment] 2021-07-01 09:56
> @gv74 I have some fixes for Linux big-endian at https://github.com/martin-schwenke/openssl/tree/master-fixes but my AIX test environment has gone a little bit crazy. I don't think the fixes will break AIX, but if you're able to test them then I would be very grateful...

Sure.

**Comment by gv74** [comment] 2021-07-01 10:33
[openssl-martin-configure.log.gz](https://github.com/openssl/openssl/files/6747482/openssl-martin-configure.log.gz)
[openssl-martin-build.log.gz](https://github.com/openssl/openssl/files/6747484/openssl-martin-build.log.gz)
[openssl-martin-test.log.gz](https://github.com/openssl/openssl/files/6747485/openssl-martin-test.log.gz)

I think some of the failing tests are fixed in master.

**Comment by martin-schwenke** [comment] 2021-07-01 10:55
> [openssl-martin-configure.log.gz](https://github.com/openssl/openssl/files/6747482/openssl-martin-configure.log.gz)
> [openssl-martin-build.log.gz](https://github.com/openssl/openssl/files/6747484/openssl-martin-build.log.gz)
> [openssl-martin-test.log.gz](https://github.com/openssl/openssl/files/6747485/openssl-martin-test.log.gz)
> 
> I think some of the failing tests are fixed in master.

Thanks!  We know it builds and these tests pass:
```
15-test_ec.t ....................... ok
15-test_ecdsa.t .................... ok
15-test_ecparam.t .................. ok
```
None of the test failures look like they should be my fault... but others will be able to make a more educate guess.

Thanks again!

**Comment by gv74** [comment] 2021-07-01 11:16
> We know it builds and these tests pass:
> 
> ```
> 15-test_ec.t ....................... ok
> 15-test_ecdsa.t .................... ok
> 15-test_ecparam.t .................. ok
> ```

OK.

> None of the test failures look like they should be my fault... but others will be able to make a more educate guess.

Your repository is out of date. All tests pass in master.

> Thanks again!
You're welcome.

**Comment by martin-schwenke** [comment] 2021-07-01 12:04
> Your repository is out of date. All tests pass in master.

This worries me.  My current branch is only missing one commit from `master`, which is a documentation fix.  I'm concerned that I've pushed the wrong branch somewhere.  Did you test the `master-fixes` branch?  Sorry for any confusion...

**Comment by gv74** [comment] 2021-07-01 12:24
1. git clone git://git.openssl.org/openssl.git
make: no errors
make test: no errors

2. git clone https://github.com/martin-schwenke/openssl/tree/master-fixes 
make: no errors
make test: errors
(you have log files).

**Comment by t8m** [comment] 2021-07-01 14:01
@gv74 Did you do make clean when building the master-fixes checkout?

I cannot reproduce this issue this time - this looks like reinstaintiation of #13336.

What does the `dump -Tv -X64 legacy.so` print?

**Comment by gv74** [comment] 2021-07-01 14:05
I did "git clone https://github.com/martin-schwenke/openssl/tree/master-fixes". Why running make clean?
[legacy.dump.txt](https://github.com/openssl/openssl/files/6748714/legacy.dump.txt)

**Comment by gv74** [comment] 2021-07-01 14:18
Again, when cloning git://git.openssl.org/openssl.git, everything works _fine_. Since this is the official repo, I see no issue here.

**Comment by t8m** [comment] 2021-07-01 14:21
Ah, now I get it. You cloned the master branch from the martin-schwenke repository but did not check out the master-fixes branch. `git checkout master-fixes` in the clone please and then try the build (after make clean).

**Comment by gv74** [comment] 2021-07-01 14:23
Sure. But I have to go now. I will do this tomorrow. I'm sorry about that.

**Comment by gv74** [comment] 2021-07-02 06:54
[openssl-martin-configure.log.gz](https://github.com/openssl/openssl/files/6752676/openssl-martin-configure.log.gz)
[openssl-martin-build.log.gz](https://github.com/openssl/openssl/files/6752678/openssl-martin-build.log.gz)
[openssl-martin-test.log.gz](https://github.com/openssl/openssl/files/6752679/openssl-martin-test.log.gz)

No errors with master-fixes branch.

**Comment by martin-schwenke** [comment] 2021-07-02 10:06
> No errors with master-fixes branch.

Yay!  Thanks for double-checking!

**Closed** 2021-07-06 00:50 UTC
Labels: branch: master, triaged: OTC evaluated, triaged: bug
