### ISSUE TITLE
error in store file loader after use of store functionality

### ISSUE THREAD

**Issue by petrovr** [openssl/openssl#4089] opened 2017-08-05 08:13 UTC
NSS engine command LIST_CERTS is based on STORE2 API if supported by crypto library.

Issue is that after "success" engine command reports error in store file loader:
$ openssl engine e_nss -pre LIST_CERTS:1
(e_nss) NSS engine (1.1)
nickname='...'
...
nickname='...'
[Success]: LIST_CERTS:1
139707599804160:error:02016002:system library:stat:No such file or directory:crypto/store/loader_file.c:812:nss:list=user

Command storeutl does not reports error for same query:
$ openssl storeutl -engine e_nss 'nss:list=user'

**Comment by levitte** [comment] 2017-08-05 08:34
The OSSL_STORE (that's what it ended up being called) implementation in e_nss should implement two functions, one to indicate "end of file" (i.e. there's no more data) and one to indicate an error status.  When `storeutl` receives a `NULL` from `OSSL_STORE_load`, it will check the "end of file" status *first*, and if that one is not set, it will check the error status.  If the "end of file" status is true, `storeutl` simply breaks out of the loop and prints nothing.  Otherwise, if the error status is true, it does print the error stack.

So if I may guess, I would guess that the `eof` function in `e_nss` returns 1 after this error has occured...

(side note: I'm going mainly off line starting some time today, and won't be back before the 15th, so you may have to show some patience)

**Comment by petrovr** [comment] 2017-08-05 11:59
Richard Levitte wrote:
> The OSSL_STORE (that's what it ended up being called) implementation in e_nss should implement two functions, one to indicate "end of file" (i.e. there's no more data) and one to indicate an error status.  When `storeutl` receives a `NULL` from `OSSL_STORE_load`, it will check the "end of file" status *first*, and if that one is not set, it will check the error status.  If the "end of file" status is true, `storeutl` simply breaks out of the loop and prints nothing.  Otherwise, if the error status is true, it does print the error stack.
I note that now error is required method and current repository code 
implement it.

> So if I may guess, I would guess that the `eof` function in `e_nss` returns 1 after this error has occured...

I cannot see in trace build error invocation:
....
...TRACE_E_NSS nss_init()^ ok
(e_nss) NSS engine (1.1)
...TRACE_E_NSS nss_ctrl() cmd=220/LIST_CERTS: i=1, p=(nil), f=(nil)
...TRACE_E_NSS nss_ctrl() ctx=0x80d7c0
...TRACE_E_NSS nss_cmd_list_cert: 1
...TRACE_E_NSS nss_store_open(uri="nss:list=user"):  ...
...TRACE_E_NSS nss_store_open():  query="list=user"
...TRACE_E_NSS nss_store_open():  return 0x841ff0
...TRACE_E_NSS nss_store_eof(ctx=0x841ff0, ...):  ...
...TRACE_E_NSS nss_store_eof():  return 0
...TRACE_E_NSS nss_store_eof(ctx=0x841ff0, ...):  ...
...TRACE_E_NSS nss_store_eof():  return 0
...TRACE_E_NSS nss_store_load(ctx=0x841ff0, ...):  ...
...TRACE_E_NSS nss_store_load():  return 0x841fd0
nickname='SSH ECDSA(nistp521) test certificate(dsa) - SSH Test Team 
cyrillic-АБВ-Яабв-я greek-ΑΒΓ-Ωαβγ-ω'
...TRACE_E_NSS nss_store_eof(ctx=0x841ff0, ...):  ...
...TRACE_E_NSS nss_store_eof():  return 0
...TRACE_E_NSS nss_store_eof(ctx=0x841ff0, ...):  ...
...TRACE_E_NSS nss_store_eof():  return 0
...TRACE_E_NSS nss_store_load(ctx=0x841ff0, ...):  ...
...TRACE_E_NSS nss_store_load():  return 0x841fd0
nickname='SSH ECDSA(nistp384) test certificate(dsa) - SSH Test Team 
cyrillic-АБВ-Яабв-я greek-ΑΒΓ-Ωαβγ-ω'
...TRACE_E_NSS nss_store_eof(ctx=0x841ff0, ...):  ...
...TRACE_E_NSS nss_store_eof():  return 0
...TRACE_E_NSS nss_store_eof(ctx=0x841ff0, ...):  ...
...TRACE_E_NSS nss_store_eof():  return 0
...TRACE_E_NSS nss_store_load(ctx=0x841ff0, ...):  ...
...TRACE_E_NSS nss_store_load():  return 0x841fd0
nickname='SSH ECDSA(nistp256) test certificate(dsa) - SSH Test Team 
cyrillic-АБВ-Яабв-я greek-ΑΒΓ-Ωαβγ-ω'
...TRACE_E_NSS nss_store_eof(ctx=0x841ff0, ...):  ...
...TRACE_E_NSS nss_store_eof():  return 0
...TRACE_E_NSS nss_store_eof(ctx=0x841ff0, ...):  ...
...TRACE_E_NSS nss_store_eof():  return 0
...TRACE_E_NSS nss_store_load(ctx=0x841ff0, ...):  ...
...TRACE_E_NSS nss_store_load():  return 0x841fd0
nickname='SSH DSA test certificate(dsa) - SSH Test Team 
cyrillic-АБВ-Яабв-я greek-ΑΒΓ-Ωαβγ-ω'
...TRACE_E_NSS nss_store_eof(ctx=0x841ff0, ...):  ...
...TRACE_E_NSS nss_store_eof():  return 0
...TRACE_E_NSS nss_store_eof(ctx=0x841ff0, ...):  ...
...TRACE_E_NSS nss_store_eof():  return 0
...TRACE_E_NSS nss_store_load(ctx=0x841ff0, ...):  ...
...TRACE_E_NSS nss_store_load():  return 0x841fd0
nickname='SSH RSA test certificate(dsa) - SSH Test Team 
cyrillic-АБВ-Яабв-я greek-ΑΒΓ-Ωαβγ-ω'
...TRACE_E_NSS nss_store_eof(ctx=0x841ff0, ...):  ...
...TRACE_E_NSS nss_store_eof():  return 1
...TRACE_E_NSS nss_store_close(ctx=0x841ff0):  ...
[Success]: LIST_CERTS:1
140330551133952:error:02016002:system library:stat:No such file or 
directory:crypto/store/loader_file.c:812:nss:list=user
...TRACE_E_NSS nss_finish()
....

Now I note that eof is called twice . For sure one if invocation should 
be  from engine code. It look like this:
OSSL_STORE_open
while !OSSL_STORE_eof
    OSSL_STORE_load
OSSL_STORE_close

> (side note: I'm going mainly off line starting some time today, and won't be back before the 15th, so you may have to show some patience)

Issue is with low priority but I cannot see a way to mark it like that.


Roumen

**Comment by levitte** [comment] 2017-08-05 12:20
Ahhhh, no I understand the issue!  The issue isn't with `openssl storeutl` (as far as I can tell, it does things exactly right), but in `openssl engine` (or, well, possible the way `e_nss` handles things).

As for the many calls of the eof function, know that `OSSL_STORE_load()` itself calls `OSSL_STORE_eof()` to make sure not to load anything more if "end of file" has been reached.

Now, for this part:

```
[Success]: LIST_CERTS:1
140330551133952:error:02016002:system library:stat:No such file or
directory:crypto/store/loader_file.c:812:nss:list=user
...TRACE_E_NSS nss_finish()
```

It seems like *something* tries to open the URI again, using the file scheme loader.  I'm not sure I understand how that happens, but I think I would need to have a look at the current `e_nss` code to understand what's happening.  Is there a repo I can look at after I get back from vacation?

> Issue is with low priority but I cannot see a way to mark it like that.

Just don't close it.  I'll assign it to myself.

**Comment by petrovr** [comment] 2017-08-05 12:30
Richard Levitte wrote:
> [snip]   I'm not sure I understand how that happens, but I think I would need 
to have a look at the current `e_nss` code to understand what's 
happening.  Is there a repo I can look at after I get back from vacation?

Code is available  in master branch: https://gitlab.com/e_nss/e_nss.git

Trace is activated explicitelly with preprocessor flags 
-DENABLE_CALL_TRACE (to trace  function invocation) and 
-DENABLE_NSS_TRACE (to trace engine logic)

Roumen

**Comment by levitte** [comment] 2017-08-05 12:59
Ok, I think I got it!  Please check #4094 to see if that resolves your issue.

**Comment by petrovr** [comment] 2017-08-05 15:37
Richard Levitte wrote:
> Ok, I think I got it!  Please check #4094 to see if that resolves your issue.

First enjoy the vacation!

Clear of all errors resolve issue, but in some cases may be partial 
clear is more expected (ERR_set_mark  .... ERR_pop_to_mark).

Roumen

**Comment by levitte** [comment] 2017-08-05 19:19
I think that may be a separate issue...  we should probably review how `ERR_clear_error` interacts with `ERR_set_mark`...  or oh!  Are you thinking that `OSSL_LOAD_open` should use `ERR_set_mark` and `ERR_pop_to_mark` rather than `ERR_clear_error`?  Actually, that's a good idea!

**Closed** 2017-08-15 12:29 UTC
