### ISSUE TITLE
Inconsistency between OpenSSL versions 1.1.0 and 1.0.2 over the way of handling specific certificates.

### ISSUE THREAD

**Issue by zborac** [openssl/openssl#6285] opened 2018-05-17 13:36 UTC
Inconsistency between OpenSSL versions 1.1.0 and 1.0.2 over the way of handling of the specific certificates hashes.

During my work on the end-entity certificates checking application I have stumble on the problem with root and intermediate certificates issued by the local CA. Those certificates are:  
http://ca.mup.gov.rs/MUPCARoot.crt
http://ca.mup.gov.rs/MUPCAGradjani.crt

There is no problems with another root and intermediate certificates from the same CA.
http://ca.mup.gov.rs/MUPCARoot3.crt
http://ca.mup.gov.rs/MUPCAGradjani3.crt

The problem is in the following:

>ver
Microsoft Windows [Version 10.0.17134.48]

>openssl version
OpenSSL 1.1.0e  16 Feb 2017

>openssl x509 -noout -hash -inform DER -in MUPCARoot.crt
unable to load certificate
6792:error:0D0E20DD:asn1 encoding routines:c2i_ibuf:illegal padding::0:
6792:error:0D08303A:asn1 encoding routines:asn1_template_noexp_d2i:nested asn1 error::0:Field=serialNumber, Type=X509_CINF
6792:error:0D08303A:asn1 encoding routines:asn1_template_noexp_d2i:nested asn1 error::0:Field=cert_info, Type=X509

>openssl x509 -hash -noout -inform DER -in MUPCAGradjani.crt
unable to load certificate
8912:error:0D0E20DD:asn1 encoding routines:c2i_ibuf:illegal padding::0:
8912:error:0D08303A:asn1 encoding routines:asn1_template_noexp_d2i:nested asn1 error::0:Field=serialNumber, Type=X509_CINF
8912:error:0D08303A:asn1 encoding routines:asn1_template_noexp_d2i:nested asn1 error::0:Field=cert_info, Type=X509

Another root and intermediate certificates:

>openssl x509 -hash -noout -inform DER -in MUPCARoot3.crt
919d603b

>openssl x509 -hash -noout -inform DER -in MUPCAGradjani3.crt
51d90770

All is the same with OpenSSL versions: 1.1.0a, 1.1.0d and 1.1.0f.

But with OpenSSL 1.0.2g MUPCARoot.crt and MUPCAGradjani.crt everything works well:

>openssl version
OpenSSL 1.0.2g  1 Mar 2016

>C:\dt\openssl>openssl x509 -hash -noout -inform DER -in MUPCARoot.crt
0a7dc35a

>C:\dt\openssl>openssl x509 -hash -noout -inform DER -in MUPCAGradjani.crt
8fb7ed97

I have used OpenSSL bianries downloaded from https://bintray.com/vszakats/generic/openssl and from http://wiki.overbyte.eu/wiki/index.php/ICS_Download (referenced on https://wiki.openssl.org/index.php/Binaries).

**Comment by beldmit** [comment] 2018-06-22 11:45
The Serial Number field in the http://ca.mup.gov.rs/MUPCARoot.crt file contains octets "00000064". This is not valid DER-encoded value. There were no checks in older version of OpenSSL in this part of code.

**Comment by richsalz** [comment] 2018-06-27 17:01
This is also a bug in 1.1.0, so removing the 1.1.1 milestone.

**Comment by kroeckx** [comment] 2018-06-27 17:07
I'm not sure what bug there would be in 1.1.0. As far as I
understand there was a bug in 1.0.2 that it allowed processing such
certificates.

**Comment by richsalz** [comment] 2018-06-27 17:10
So the issue is that in 1.0.2 these certs were parsed and in 1.1.0 we rejected the wrongly-encoded certs.  It is probably a bug that they used to work. Either 1.0.2 should be fixed, or 1.1.0 and later should be relaxed to accept them.   But either way, it's not a just-1.1.1 issue.

**Comment by nmbro** [comment] 2019-12-10 08:32
@richsalz did anything ever come out of this?

**Comment by richsalz** [comment] 2019-12-10 16:34
As far as I know, nothing was done.  1.0.2 goes out of support (end of life) at the end of this year, so I guess that's the answer.

**Comment by t8m** [comment] 2021-06-07 15:13
1.0.2 is out of support and 1.1.x behavior is correct. Closing.

**Closed by t8m** 2021-06-07 15:13 UTC
