### ISSUE TITLE
md[24] cannot be run in speed or digest

### ISSUE THREAD

**Issue by richsalz** [openssl/openssl#10435] opened 2019-11-13 14:20 UTC
```
; ./apps/openssl speed
Doing md2 for 3s on 16 size blocks: EVP error!
; ./apps/openssl md4
Error setting digest
C0:F5:8A:10:01:00:00:00:error:digital envelope routines:EVP_DigestInit_ex:initialization error:crypto/evp/digest.c:175:
```

**Comment by levitte** [comment] 2019-11-26 16:06
Duplicate of #9349

**Closed** 2019-11-26 16:55 UTC
Labels: issue: bug report
