### ISSUE TITLE
Incorrect types in struct rand_meth_st 

### ISSUE THREAD

**Issue by nrbrook** [openssl/openssl#10571] opened 2019-12-04 14:26 UTC
In the documentation [here](https://www.openssl.org/docs/man1.1.1/man3/RAND_OpenSSL.html) the `rand_meth_st` struct documentation is incorrect. The `seed` and `add` functions have a return type `int`.

**Comment by mattcaswell** [comment] 2019-12-05 15:32
Duplicate of #10199

**Closed by mattcaswell** 2019-12-05 15:32 UTC
Labels: issue: documentation
