### ISSUE TITLE
Tests fail on OpenBSD

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#6960] opened 2018-08-14 16:25 UTC
Both master and 1.1.0 seem to be failing the `test_ssl_old` test on OpenBSD:

````
$ uname -a
OpenBSD openbsd.home 5.9 GENERIC#1761 amd64
````

The master failure looks like this:
````
30144032635200:error:0200E016:system library:setsockopt:Invalid argument:crypto/bio/b_sock2.c:253:
30144032635200:error:2008B088:BIO routines:BIO_listen:listen v6 only:crypto/bio/b_sock2.c:254:
30144032635200:error:2008F002:BIO routines:BIO_lookup_ex:system lib:crypto/bio/b_addr.c:704:service not supported for ai_socktype
Doing handshakes=1 bytes=256
TLSv1.3, cipher (NONE) (NONE)
../../util/shlib_wrap.sh ../../test/ssltest_old -s_key keyU.ss -s_cert certU.ss -c_key keyU.ss -c_cert certU.ss -ipv6 => 1
    not ok 13 - test TLS via IPv6
    
    #   Failed test 'test TLS via IPv6'
    #   at ../test/recipes/80-test_ssl_old.t line 390.
    # Looks like you failed 1 test of 13.
not ok 2 - standard SSL tests
````

The 1.1.0 failure looks very similar:
````
1835242301760:error:0200E016:system library:setsockopt:Invalid argument:crypto/bio/b_sock2.c:212:
1835242301760:error:2008B088:BIO routines:BIO_listen:listen v6 only:crypto/bio/b_sock2.c:213:
1835242301760:error:20087002:BIO routines:BIO_lookup:system lib:crypto/bio/b_addr.c:694:service not supported for ai_socktype
Doing handshakes=1 bytes=256
TLSv1.2, cipher (NONE) (NONE)
../../util/shlib_wrap.sh ../../test/ssltest_old -s_key keyU.ss -s_cert certU.ss -c_key keyU.ss -c_cert certU.ss -ipv6 => 1
    not ok 21 - test TLS via IPv6
    
    #   Failed test 'test TLS via IPv6'
    #   at ../test/recipes/80-test_ssl_old.t line 418.
    # Looks like you failed 1 test of 21.
not ok 2 - standard SSL tests
````
This is the failing code:
https://github.com/openssl/openssl/blob/80162ad645f8982102d6994b9ea9ca6c371e933d/crypto/bio/b_sock2.c#L244-L258

**Comment by t-j-h** [comment] 2018-08-21 11:45
Are you running on a system with IPv6 enabled or disabled during installation?

**Comment by Sp1l** [comment] 2018-08-24 19:49
FWIW That's a pretty old OpenBSD version, which is no longer supported. They're in 6.4-BETA stage currently so only 6.3 and 6.2 are currently supported.

**Comment by kroeckx** [comment] 2018-08-24 20:32
IPV6_V6ONLY is the default on OpenBSD, and there is no way to
turning it off.

**Comment by richsalz** [comment] 2019-12-30 19:37
time to close this?

**Comment by kaduk** [comment] 2019-12-31 16:02
My reading of the comment history is that OpenBSD defines ```IPV6_V6ONLY``` but attempting to use setsockopt to turn it off will always fail, and I don't see anything in the git history to indicate that we've worked around that by skipping that test on OpenBSD.  If true, that would make this still an issue, though only affecting OpenBSD systems.

**Comment by t8m** [comment] 2021-05-18 13:49
The current master has `# if defined(IPV6_V6ONLY) && !defined(__OpenBSD__)` so it is supposedly fixed. Closing. Please reopen if the issue is still present for you when compiling the current master.

**Closed by t8m** 2021-05-18 13:49 UTC
