### ISSUE TITLE
ed25519 is not supported by this version of OpenSSL

### ISSUE THREAD

**Issue by nick2525** [openssl/openssl#13974] opened 2021-01-26 17:31 UTC
ed25519 is not supported by this version of OpenSSL in OpenSSL 1.1.1f
My docker container is
===============================================================================================
lsb_release -a
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal
===============================================================================================
uname -a
Linux raspberrypi 5.4.83-v7+ armv7l armv7l armv7l GNU/Linux
===============================================================================================
Debug in Python, Python is in virtualenv

Python 3.9.0 (default, Oct 28 2020, 23:50:03)
[GCC 7.4.0] on linux

from cryptography.hazmat.backends import default_backend
default_backend().openssl_version_text()
'OpenSSL 1.1.1f 31 Mar 2020'

So, I have version 1.1.1f 
when I try

from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey
Ed25519PrivateKey.generate()

Traceback (most recent call last):
File "", line 1, in
File "/home/nick252/homeassistant/lib/python3.9/site-packages/cryptography/hazmat/primitives/asymmetric/ed25519.py", line 52, in generate
raise UnsupportedAlgorithm(
cryptography.exceptions.UnsupportedAlgorithm: ed25519 is not supported by this version of OpenSSL.

===============================================================================================
More info in https://github.com/home-assistant/core/issues/45363

**Comment by dony71** [comment] 2021-01-26 21:14
I have same issue like nick2525 
Use python 3.87 and OpenSSL 1.1.1i in virtualenv
OS Linux bananapim2plus 4.14.78-sunxi armv7l (Armbian Stretch)

**Comment by mattcaswell** [comment] 2021-01-27 09:18
Looks like this question would be better asked of the python guys:

https://github.com/pyca/cryptography

**Comment by nick2525** [comment] 2021-01-27 09:36
@mattcaswell ok, I will also post bug in cryptography, but very strange, that Python confirms, that used version is OpenSSL 1.1.1f
 from cryptography.hazmat.backends import default_backend
default_backend().openssl_version_text()
'OpenSSL 1.1.1f 31 Mar 2020'

**Comment by nick2525** [comment] 2021-01-27 20:19
May close, remove python cache ./.cache/pip/wheels/ everywhere works

**Comment by mattcaswell** [comment] 2021-01-28 08:09
Thanks for the confirmation. Closing.

**Closed by mattcaswell** 2021-01-28 08:09 UTC
Labels: resolved: answered

**Comment by Vale-sail** [comment] 2022-03-03 03:47
cryptography has bug . 

Write error OpenSSL 1.1.1b version number，The problem was with Ed25519 support.

ref https://github.com/pyca/cryptography/pull/5452

**Comment by paulidale** [comment] 2022-03-03 05:50
@reaperhulk ... FYI

**Comment by reaperhulk** [comment] 2022-03-03 06:05
Thanks for the ping. `cryptography` allows ed25519 in 1.1.1b+; anyone who is seeing a problem should file an issue on the [pyca/cryptography](https://github.com/pyca/cryptography/issues) tracker and not OpenSSL 😄 Please be sure to provide instructions on how to reproduce the behavior so we can debug the environment.

**Comment by Vale-sail** [comment] 2022-03-03 06:12
> 
Don't be nervous。the bug has fixed。I write this comment  only to notice anyone who has same problem。

https://github.com/pyca/cryptography/pull/5452
