### ISSUE TITLE
OpenSSL Server sends nonsense OCSP data in TLSv1.3 Certificate Request message, causing handshake failures with Go clients

### ISSUE THREAD

**Issue by GermanCoding** [openssl/openssl#10007] opened 2019-09-25 02:15 UTC
```
$ openssl version
OpenSSL 1.1.1c  28 May 2019
```

### Overall problem
I've experienced connectivity problems when [Go](https://golang.org/) clients attempt to connect to an OpenSSL server, which has TLSv1.3 enabled, OCSP stapling enabled and requires client authentication.

### Diagnosed issue
Given an OpenSSL server configured as above (TLS 1.3, OCSP stapling, client auth), the OpenSSL server sends the following TLS messages during the handshake:

`Server Hello, Change Cipher Spec, Encrypted Extensions, Certificate Request, Certificate, Certificate Verify, Finished`

upon receiving the Finished message, a TLS client based on Go 1.12 OR Go 1.13 [TLS 1.3 enabled] replies with the following messages:

`Change Cipher Spec, ALERT [Fatal, Unexpected Message]`

-> The Go client immediatly fails the handshake when talking to an OpenSSL server which is in the above configuration.

This seems to be because of the `Certificate Request` message send by the OpenSSL server. This message contains anomalies:

### Anomalies in Certificate Request

In the above configuration, the `Certificate Request`  message contains three extensions, those are:

`status_request, signature_algorithms, certificate_authorities`. The two last extension seem to be ok, but the `status_request` extension is faulty, because:

**The status_request extension contains a full OCSP Response which is IDENTICAL to those send in the `Certificate` message. From my understanding, it makes zero sense to include a OCSP response in this context, because this extension is merely meant to tell clients, that an OCSP response may be send by the client during client authentication**.

Instead, this `status_request` extension should be **empty**, which is also backed up by RFC 8446:

> A server MAY request that a client present an OCSP response with its
>    certificate by sending an **empty** "status_request" extension in its
>    CertificateRequest message.  If the client opts to send an OCSP
>    response, the body of its "status_request" extension MUST be a
>    CertificateStatus structure as defined in [RFC6066].

(Cited from https://tools.ietf.org/html/rfc8446#section-4.4.2.1)

Note: The OCSP response itself is fine. It's also fine to send the OCSP response inside the `Certificate` message (the response is meant for the server-certificate). But it makes no sense to send this data in a context where we request a `client certificate` ("hey client, please send me a certificate and by the way here's totally unrelated OCSP data").

### Affected clients

OpenSSL clients have zero problems with this nonsense data inside the Certificate Request message - the handshake finished normally. Clients based on the Go programming language however, throw up entirely and fail the handshake (see above).

### Additional data (Wireshark capture file showing the problem)

A Wireshark capture file which shows an example of such a faulty handshake is attached below.

_Note: You need to rename the file, because I'm not allowed to upload .pcapng files. The true file extension is .pcapng, it's a Wireshark Capture file._
[Go_to_openssl_test2.pcapng.txt](https://github.com/openssl/openssl/files/3650188/Go_to_openssl_test2.pcapng.txt)

_Since this is TLS, the handshake in the capture file above is partly encrypted. In order to decrypt it, the encryption secret is required and needs to be imported into WireShark (as "(Pre)-Master-Secret log filename). The required decryption secret is attached below._
[Go_to_openssl_test2.secret.txt](https://github.com/openssl/openssl/files/3650193/Go_to_openssl_test2.secret.txt)

### Reproducing the issue

First, setup an OpenSSL server in the correct configuration (as above):

```
$ openssl s_server -tls1_3 -status -www -verify 0 -CAfile <CA_cert> -cert <server_cert> -key <server_key>
```

Next, simply use any Go TLS client supporting TLS 1.3 (Go 1.12 with _GODEBUG_ or Go 1.13) and connect it to the OpenSSL server. Example code for a minimalistic Go TLS client is [here](https://github.com/denji/golang-tls#tls-transport-layer-security--client).

**Comment by mattcaswell** [comment] 2019-09-25 08:51
This is a dupe of #9767 which was fixed by #9780 in commit debb64a0. That commit is available in OpenSSL 1.1.1d, so please upgrade to the latest version.

**Closed by mattcaswell** 2019-09-25 08:51 UTC
Labels: bug
