### ISSUE TITLE
chacha20 seems to be broken in OpenSSL 3.0.0alpha6

### ISSUE THREAD

**Issue by berolinux** [openssl/openssl#13064] opened 2020-10-02 23:44 UTC
When using OpenSSL 3.0.0alpha6, OpenSSH versions > 8.2p1 fail to connect anywhere, usually resulting in a "protocol error" while establishing the connection.

Bisecting OpenSSH shows this commit is what triggers the breakage:
https://github.com/openssh/openssh-portable/commit/abe2b245b3ac6c4801e99bc0f13289cd28211e22

Defining HAVE_BROKEN_CHACHA20 in openbsd-compat/openssl-compat.h (like the openssh commit does for some versions of LibreSSL) "fixes" the problem.

Looks like EVP_chacha20 doesn't work as expected by OpenSSH.

**Comment by kaduk** [comment] 2020-10-02 23:54
Are you in a position to attempt to bisect on openssl versions?
It would be particularly interesting to know if 1.1.1 releases (e.g., 1.1.1h) are functional for this usage.

**Comment by kroeckx** [comment] 2020-10-03 08:28
You might want to read the commits: https://github.com/libressl-portable/openbsd/commit/1a068026c3e1e9cd67a2941795421a8fe38f8401, https://github.com/libressl-portable/openbsd/commit/0f67aa39232d057952bb726a0d8f9db49d0fdec4, https://github.com/libressl-portable/openbsd/commit/61c1088900c0b029354d99ac53a24c39d0105576 and the release notes for libressl 3.1.0: https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-3.1.0-relnotes.txt

They introduced EVP_chacha20 before RFC7539 was published, while we waited for the RFC. The RFC says it's a 32 bit counter followed by a 96 bit nonce, which is what we do. They did something else.

So libressl in 3.1.0 switched to have the same EVP_chacha20 behaviour as OpenSSL. And the commit you point to seems to suggest that that requires to have HAVE_BROKEN_CHACHA20 defined.

**Comment by berolinux** [comment] 2020-10-03 13:07
@kroeckx This issue has nothing to do with the LibreSSL commits you're mentioning. LibreSSL is not involved here. The problem occurs with OpenSSL 3.0.0a6.
The only connection to those LibreSSL commits is that - because of its initial broken implementation - OpenSSH already has a builtin workaround for SSL implementations with broken chacha20, and activating that makes it work with OpenSSL 3.0.0a6 too.

**Comment by kroeckx** [comment] 2020-10-03 14:39
In a later commit, they fixed it to say LIBRESSL_VERSION_NUMBER < 0x3010000fL

I can confirm that openssh 8.3p1 works with openssl 1.1.1g but not with master. Running a bisect.

**Comment by kroeckx** [comment] 2020-10-03 15:01
3d5a7578e09a984c6475b1c008f5c76f850328cb is the first bad commit
commit 3d5a7578e09a984c6475b1c008f5c76f850328cb
Author: Shane Lontis <shane.lontis@oracle.com>
Date:   Wed Oct 16 16:18:42 2019 +1000

    Add ChaCha related ciphers to default provider

    Reviewed-by: Richard Levitte <levitte@openssl.org>
    (Merged from https://github.com/openssl/openssl/pull/10081)

**Comment by beldmit** [comment] 2020-10-04 10:05
@kroeckx, would you mind to submit a test?

**Comment by slontis** [comment] 2020-11-12 01:36
@kroeckx, what are the steps to test this?

**Comment by kroeckx** [comment] 2020-11-12 17:50
What I did was compile openssh against 3.0, and then use the ssh
binary to connect to an sshd that's build against 1.1.1.

chacha20-poly1305@openssh.com seems to be the default cipher it
uses, at least talking to 7.9p1 server.

**Comment by kroeckx** [comment] 2020-11-12 20:42
#9524 might be related

**Comment by levitte** [comment] 2020-11-13 15:35
I just tried the current openssh-portable development with my 3.0 installation, and it fails in `make tests`...  seems to be `regress/connect.sh` failing, and I found this in the end of `regress/failed-ssh.log`:

```
debug1: kex_input_ext_info: server-sig-algs=<ssh-ed25519,sk-ssh-ed25519@openssh.com,ssh-rsa,rsa-sha2-256,rsa-sha2-512,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,sk-ecdsa-sha2-nistp256@openssh.com,webauthn-sk-ecdsa-sha2-nistp256@openssh.com>
Bad packet length 3619053086.
debug3: send packet: type 1
ssh_dispatch_run_fatal: Connection to UNKNOWN port 65535: Connection corrupted
FAIL: ssh proxycommand connect failed
```

Considering #9524, I did a similar build with pkixssh, where a `make tests` ends like this:

```
test_sshbuf: ....................................................................................................... 103 tests ok
test_sshkey: .......................................................................................... 90 tests ok
test_bitmap: .. 2 tests ok
test_conversion: ... 3 tests ok
test_kex: .....Bad packet length 3083080349.
ssh_packet_next: Connection corrupted

regress/unittests/kex/test_kex.c:73 test #6 "rekeying client"
ASSERT_INT_EQ(r, 0) failed:
           r = -54
           0 = 0
```

That's worryingly similar...  I haven't dived into the pkixssh logs yet

**Comment by t8m** [comment] 2021-01-11 18:01
This is caused by the provider conversion breaking the sequence of multiple EVP_CipherInit() calls where first one sets the EVP_CIPHER and the key and then there are multiple calls to EVP_CipherInit with just an iv set, NULL EVP_CIPHER and NULL key followed by EVP_Cipher call. We need to preserve the previous key set on the EVP_CipherInit call in this circumstance.

**Closed** 2021-01-13 17:05 UTC
Labels: branch: master, triaged: OTC evaluated, triaged: bug
