### ISSUE TITLE
DTLS handshake fails if ClientKeyExchange and ChangeCipherSpec recieved out of order

### ISSUE THREAD

**Issue by yfaker** [openssl/openssl#15478] opened 2021-05-26 09:35 UTC
![image](https://user-images.githubusercontent.com/23066914/119637157-f35f5a00-be47-11eb-9f82-c74eaffaf11f.png)

![image](https://user-images.githubusercontent.com/23066914/119637712-87c9bc80-be48-11eb-98e9-a02bac39e6a8.png)

DTLS connection establishment fails when ClientKeyExchange and ChangeCipherSpec messages are received out of order，
so the ChangeCipherSpec message should be buffered if received out of order?

**Comment by yfaker** [comment] 2021-05-26 10:07
version:openssl-1.1.1k

**Comment by davidben** [comment] 2021-05-26 13:50
Is it failing or is it just waiting for a (re)transmit? Based on the WANT_READ and this logic, it looks like OpenSSL just drops the out-of-order ChangeCipherSpec.
https://github.com/openssl/openssl/blob/master/ssl/statem/statem_clnt.c#L383

This isn't fatal, since the other side should retransmit the ChangeCipherSpec when retransmitting the flight. Nonetheless, it's true that this makes OpenSSL's DTLS implementation perform worse on reordered CCS compared to other reordered messages. CCS is completely informationless in DTLS, so we just set a flag on receipt and tolerate arbitrary reordering: https://boringssl-review.googlesource.com/c/boringssl/+/18724

**Comment by yfaker** [comment] 2021-05-31 12:16
ok thanks! it worked after i optimized the client handshake

**Comment by paulidale** [comment] 2021-06-14 12:14
Answered, closing.

**Closed by paulidale** 2021-06-14 12:14 UTC
Labels: branch: 1.1.1, resolved: answered, triaged: question

**Comment by davidben** [comment] 2021-06-14 15:25
This isn't quite a question. It's also a bug report that OpenSSL's DTLS implementation doesn't perform as well as it could in the presence of reordered packets. OpenSSL could chose not to act on that, especially since a good DTLS sender will pack CCS in order with the handshake messages.

However, there are bad DTLS senders out there, including OpenSSL itself. At least in OpenSSL 1.0.2 (1.1.1 appears to have the same behavior, but I haven't confirmed), retransmits of the final handshake flight are not properly packed together because the `bbio` write buffer has been detached at that point.

Our WebRTC folks reported connection establishment performance problems relating to these two issues, which is why we chose to fix them in BoringSSL. (Both the unpacked retransmits and not tolerating reordered ChangeCipherSpec.)
