### ISSUE TITLE
OpenSSL-1.1.1t RSASSA-PKCS1-V1 5-VERIFY fails

### ISSUE THREAD

**Issue by yanshichao0226** [openssl/openssl#20578] opened 2023-03-22 10:50 UTC
Validation fails when the certificate is signed with pkcs1.5 and the digestAlgorithm member in the DigestInfo structure omits parameters; Validation passes when parameters is NULL.

And I notice that this field can be omitted：
![image](https://user-images.githubusercontent.com/78535322/226878142-db51c8a8-b5b5-4b6a-94fa-7464b54b2ba8.png)

In addition, versions earlier than OpenSSL-1.1.0b can be compatible with both cases(paramters is NULL or be ommitted).

Here are the test versions and certificates:
![image](https://user-images.githubusercontent.com/78535322/226876714-5c0d9b25-139d-4019-a949-fad569d2d48a.png)

<root.crt>
-----BEGIN CERTIFICATE-----
MIIDAzCCAeugAwIBAgIJAIRcl+nfagmnMA0GCSqGSIb3DQEBCwUAMBgxFjAUBgNV
BAMMDVRlc3QgQ0EgKFJTQSkwHhcNMjMwMzIyMDkxMjU3WhcNMjcwNDMwMDkxMjU3
WjAYMRYwFAYDVQQDDA1UZXN0IENBIChSU0EpMIIBIjANBgkqhkiG9w0BAQEFAAOC
AQ8AMIIBCgKCAQEA90XQpVWhye7RauRzrpL8zUt/PTsLhQ/tqPcFPMipMue6VjVq
B/+UzL34bfL329ydeyr1V21G5+LmTDjTQfUpzzLaVEODBjftHe5BcyhyqwCJmBoI
gg3mIJDT2uGgbYakbqvwdDanJeK56Kc9GE2GnnwN3ztQdeRU/ytHYIbn6707a+Hk
uny8kS1rtQGEmOJQKsJ1vggRUzMfGjviyFRJDvXtHIhMOgYrGmweTdVbtKRB8Ua5
+fhUQtc+uT1zE06ifr1/43sk1lhOJ3xjgHB+v75oIP30/fejHwgi2UvTeIskZPih
BUcbylV1uSSIJ8EO5ZrPPEL3CiuEkRyYSZ1Y2wIDAQABo1AwTjAdBgNVHQ4EFgQU
tqlFFJpBemz2Sxcivzv7xGPSfJUwHwYDVR0jBBgwFoAUtqlFFJpBemz2Sxcivzv7
xGPSfJUwDAYDVR0TBAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAQEA1bTzn0C+jbg4
n2/2CM8+ta0IJBU+dc3BO1FwAPJIYxl8zUrU/Qmk1ppmf9MB3/q2Oy0dsE+oH38M
sXm08T7sfW5swW0RcTMo7ykefUV5S4l/PDYqbZqjQwbZfuWAkdF6bxFXQVOjtU9r
3BSGAAqyj1aM5tGCFlmgBQsgNTZ2pcJPO/USRZofeB6WL6OZY81Znr7xAnpXRtKA
VXCxXbgAYO3abWW1itmnQDV7jhdZrHHKwlobmE68ifmO0ReyRUmBvaIaBWlXAhDX
ND3pYZLeXwIVPq4GLcl20W705Y+Aut42d0vtDTdxSMZzqdcVhNZ7m4fWsys7tYI+
XhtqNtdHtg==
-----END CERTIFICATE-----

<server.crt>
-----BEGIN CERTIFICATE-----
MIIC0TCCAbmgAwIBAgIJAMDasO4+7dyKMA0GCSqGSIb3DQEBCwUAMBgxFjAUBgNV
BAMMDVRlc3QgQ0EgKFJTQSkwHhcNMjMwMzIyMDkxMjU4WhcNMjcwNDMwMDkxMjU4
WjAcMRowGAYDVQQDDBFUZXN0IFNlcnZlciAoUlNBKTCCASIwDQYJKoZIhvcNAQEB
BQADggEPADCCAQoCggEBALG4G1ykYO5Eg30/ZRNKQMtxSJh0gys+6AWBpMsJjYn8
tUyUnnBaLAHggNajtjNwjKpICftVYcyH0LwWMxKQy7Yymt07OXw/FXrrHmeJ8p5i
0tFN0z24ahCemA1tUCqWsfFPPi6h5+2bvqN9zhFv/DR2Zzsm5bEYAKu5PSYctMk8
KysJOSRc6QMi76UMj6Ra0gMOK62Nc6P5BPqsYx+mK8V5gq3jL3AMeeh6wOccwcDo
xZAlXCulTb96UwWh9Rj8UJhVuDsqMxu2Hp/rt+Ks1hEQjz0T0AvTdbpac4HIOozI
ZgbfUjE4/w+Kv1cFmZ/MFuh1WO7s+6LDw5ED0fOBnWUCAwEAAaMaMBgwCQYDVR0T
BAIwADALBgNVHQ8EBAMCBeAwDQYJKoZIhvcNAQELBQADggEBADJTPoXrptyW+GVE
+jc8t2kHi03VYBm1K7rMZPsuaCGnsOQMVVnfrJC+oXHh7r9JeXhYmrRCRn8WZdNf
i8+iaxH71dqwiSo51kX9gwjstyw7wm8akfww1PuKsmHMGfM8N2WhLt5t9H0S4EBM
VSQ1xv/a/NFFiRT3i3tYRbtNEAdY7B026Ixbu544/twWdf6rRcFJlNQptafwK8vA
rh4fAbJ8ZzAe2c2goeO2qJ5ajza/DHIg9oBQg15vDXDhKw3PQAqqUU1EYWRrDpeL
jWux+wH8L0jVSTIW34T0ROFgKG/wum66IMY4ScOhzCZvdR3duHkwUUT6XWCmHISR
+npNZvw=
-----END CERTIFICATE-----

**Comment by t8m** [comment] 2023-03-22 11:15
This is duplicate of https://github.com/openssl/openssl/issues/17130

**Comment by t8m** [comment] 2023-03-22 11:16
So no, this is not a bug and the signature is incorrect.

**Comment by yanshichao0226** [comment] 2023-03-23 02:58
> Also see the Exception paragraph further down in the RFC

I missed this part

![1679538847837](https://user-images.githubusercontent.com/78535322/227085450-71cc2c44-6bf1-4226-a710-5a42f124ed42.jpg)
![image](https://user-images.githubusercontent.com/78535322/227086034-3d512f03-9f2d-43a2-9d97-0cd01d12d9c3.png)

And it's important the DER encoding T of the DigestInfo value is given in the RFC. 

Thank you for the help.

**Closed** 2023-03-24 08:43 UTC
Labels: triaged: question, resolved: answered
