### ISSUE TITLE
openssl s_server utility doesn't respond to TLS clients when it accepts a plain TCP connection.

### ISSUE THREAD

**Issue by saran-saran007** [openssl/openssl#17246] opened 2021-12-09 11:43 UTC
When s_Server utility accepts a plain TCP connection from a remote endpoint, until that plain TCP connection gets closed, the server doesn't respond to other TLS handshakes initiated from some other end point.
Noticed the issue in both of these versions:- "3.0.0" and "0.9.8g".  I know version below 1.1 are not supported, so, please help by fixing the issue in "3.0.0" and other supported versions.
```
luser@h005056952223:~$ /usr/local/ssl/bin/openssl version -a
OpenSSL 3.0.0 7 sep 2021 (Library: OpenSSL 3.0.0 7 sep 2021)
built on: Thu Dec  9 07:51:59 2021 UTC
platform: linux-x86_64
options:  bn(64,64)
compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -Wall -O3 -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_BUILDING_OPENSSL -DNDEBUG
OPENSSLDIR: "/usr/local/ssl"
ENGINESDIR: "/usr/local/ssl/lib64/engines-3"
MODULESDIR: "/usr/local/ssl/lib64/ossl-modules"
Seeding source: os-specific
CPUINFO: OPENSSL_ia32cap=0x9ed832034f8bffff:0x40
```
**Scenario to reproduce the issue:-** 
Make s_server listen on a port say (0.0.0.0:4433). Then initiate a plain TCP connection from one remote end-point(say 30.30.30.1:35356) and then initiate the TLS 1.2 handshake(session) from same remote node but with a different source port (say 30.30.30.1:45107).
Now, the server doesn't respond with a Server-hello to the TLS client(30.30.30.1:45107). In fact, it doesn't even start processing the client hello, because, I don't see the client-hello dump on the server(s_server ran with options -msg -debug -state -trace):-

```
luser@h005056952223:~$ /usr/local/ssl/bin/openssl s_server -key private.key -cert certificate.crt -accept 4433 -msg -debug -state -trace
Using default temp DH parameters
ACCEPT
```
After the plain TCP connection is closed ,I see the server  processing the client-hello and responding with a Server hello.

**The issue is consistently reproducible.**

**Comment by mattcaswell** [comment] 2021-12-09 11:45
This is by design. OpenSSL s_server is designed as a single threaded test tool. It is not intended for multi-client usage.

**Comment by mattcaswell** [comment] 2024-01-31 10:58
Closing since this is marked as resolved.

**Closed by mattcaswell** 2024-01-31 10:58 UTC
Labels: resolved: not a bug, triaged: question
