### ISSUE TITLE
Encoding of EC Public keys is broken

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#16977] opened 2021-11-05 10:19 UTC
Using the new Encoder APIs to encode EC public keys seems to be broken.

Here is a reproducer:
```` C
#include <openssl/encoder.h>
#include <openssl/evp.h>
#include <openssl/ec.h>
#include <string.h>
#include <openssl/bio.h>

int main(void) {
    EVP_PKEY *key = EVP_EC_gen("P-256");
    unsigned char *publicKey = NULL;
    size_t publicLen = 0;
    BIO *out;
    OSSL_ENCODER_CTX *ctx
        = OSSL_ENCODER_CTX_new_for_pkey(key, EVP_PKEY_PUBLIC_KEY, "DER", NULL,
                                        NULL);
    if (ctx == NULL)
        abort();
    if (!OSSL_ENCODER_to_data(ctx, &publicKey, &publicLen))
        abort();
    OSSL_ENCODER_CTX_free(ctx);

    BIO_dump_fp(stdout, publicKey, publicLen);
    out = BIO_new_file("ecpubkey.der", "wb");
    BIO_write(out, publicKey, publicLen);

    printf("Success\n");

    return 0;
}
````
Running this gives output like this:

````
0000 - 04 da 56 4c 0c 45 48 88-eb 4b ee a6 2a c1 47 61   ..VL.EH..K..*.Ga
0010 - f5 f9 9d 84 4e a2 42 59-0d c6 77 94 e2 2b 5a 8c   ....N.BY..w..+Z.
0020 - 31 8a 42 fc 4a a2 76 5c-99 64 5d 5b bb c5 00 8c   1.B.J.v\.d][....
0030 - fb 94 f0 06 7a d3 dc 1e-06 76 46 d7 00 d1 42 09   ....z....vF...B.
0040 - 08                                                .
Success
````
With the output in a file "ecpubkey.der". Trying to use that output file fails:

````
$ openssl ec -in ecpubkey.der -pubin -inform DER
read EC key
Could not read public key from ecpubkey.der
unable to load Key
````
Inspecting the DER is also interesting:
````
$ openssl asn1parse -in ecpubkey.der -inform DER
Error in encoding
4007080A647F0000:error:0680007B:asn1 encoding routines:ASN1_get_object:header too long:crypto/asn1/asn1_lib.c:105:
````

Modifying the above reproducer to change the string "DER" to "PEM", gives out an output file like this:
````
-----BEGIN EC PUBLIC KEY-----
BMzAylbS4lDBJFEMSMf6ZnnBqcHyP6ERRK1jwlJ6/3he0XP0QDPyOb981WxU3BcZ
4/m9TUWdk7TN/P8d6o8khak=
-----END EC PUBLIC KEY-----
````

Which has a PEM header of "EC PUBLIC KEY" so this means it contains a .....wait......what??????? Is there such a thing as an "EC PUBLIC KEY" file???? Don't we just use SPKI format for EC public keys???

**Comment by mattcaswell** [comment] 2021-11-05 10:23
I came across this looking at [this](https://stackoverflow.com/questions/69844316/how-to-create-an-evp-pkey-from-a-public-key-ec-stored-in-der-format-openssl-3) SO question.

**Comment by mattcaswell** [comment] 2021-11-05 10:23
@levitte

**Comment by broken-bytes** [comment] 2021-11-05 15:30
@mattcaswell 
I am the original author of that question on stack. 
While I do get the PEM and DER formats right seemingly, I cannot import a public key at all. Whenever I try doing it with the new decoder APIs, I get routine unsupported errors.
This is a long time project which will be maintained for several years to come, we cannot build on deprecated APIs. 

We need this issue fixed ASAP

**Comment by mattcaswell** [comment] 2021-11-05 16:10
> While I do get the PEM and DER formats right seemingly, I cannot import a public key at all.

I think this is the problem. Although the encoding appears to work, it doesn't actually work because the encoded public key is faulty. That is why the subsequent decoding step does not work.

A possible workaround is to explicitly specify an output structure when encoding the public key, i.e. in the fourth argument to `OSSL_ENCODER_CTX_new_for_pkey` pass the string "SubjectPublicKeyInfo" instead of NULL:

````
    OSSL_ENCODER_CTX *ctx
        = OSSL_ENCODER_CTX_new_for_pkey(key, EVP_PKEY_PUBLIC_KEY, "DER", "SubjectPublicKeyInfo",
                                        NULL);
````

I've not tried it but I suspect this might avoid the issue.

Another possible work around is to encode the EC public key using the older APIs, e.g. `d2i_PUBKEY()` or `PEM_write_bio_PUBKEY()`.

**Comment by broken-bytes** [comment] 2021-11-05 16:14
@mattcaswell Are these deprecated APIs, or are the still safe to be used ?

**Comment by mattcaswell** [comment] 2021-11-05 16:25
They are not deprecated and are safe to use. They are not as flexible as the new encoding API but they should work just fine.

**Comment by broken-bytes** [comment] 2021-11-05 16:30
@mattcaswell I will test providing an output structure argument first, I'll let you know if that solves the issue.

**Comment by kaduk** [comment] 2021-11-05 16:31
I think there might be a regression here, since around the time of #14258 and #14291 I am pretty sure that I had a version our application working with the ENCODER API.  It looks like we are still using `i2d_PublicKey()` for our production code, though, so we wouldn't have noticed a regression.

**Comment by broken-bytes** [comment] 2021-11-05 16:32
I don't know how much of a difference this actually makes, but I am on macOS Big Sur, just in case.

**Comment by mattcaswell** [comment] 2021-11-05 16:34
> Another possible work around is to encode the EC public key using the older APIs, e.g. d2i_PUBKEY()

I of course meant `i2d_PUBKEY()`

**Comment by broken-bytes** [comment] 2021-11-05 16:35
@mattcaswell I haven't tested the full flow yet, but providing an argument for the output_structure at least made `OSSL_DECODER_from_data` return 1.

**Comment by broken-bytes** [comment] 2021-11-05 16:41
Just for clearance, can we expect this to get fixed in OpenSSL 3.1, e.g. when can we expect this issue to be fixed. 
A workaround is fine for now of course, but just for the future.

**Comment by kaduk** [comment] 2021-11-05 16:41
>  we are still using i2d_PublicKey()

It seems I made a similar braino; we have `d2i_PUBKEY_ex()` and `i2d_PublicKey()` both.

**Comment by mattcaswell** [comment] 2021-11-05 22:53
> Just for clearance, can we expect this to get fixed in OpenSSL 3.1 ?

I'm hopeful we will have a fix for 3.0.1

**Comment by broken-bytes** [comment] 2021-11-05 23:24
@mattcaswell Thanks for that information.
I am struggling with something else now, I have basically copied the wiki example for ECDH https://wiki.openssl.org/index.php/Elliptic_Curve_Diffie_Hellman but both parties don't generate the same secret key. Even if I supply the same key and do the derivation, the secrets don't match. Is the code not working in OpenSSL3 anymore ? 
If so, are there any alternative APIs or is this a bug as well ?

**Comment by levitte** [comment] 2021-11-06 06:48
Something to be noted is that in 1.1.1, `i2d_PublicKey()` on an EC key is perfectly valid, and will give you the same kind of garbage (it calls `i2o_ECPublicKey`). It appears that this is what you get when you don't specify what output structure you want (the PEM encoder simply wraps whatever it gets from the DER encoder, so that output wasn't exactly surprising, apart from the fact that there is no corresponding PEM function).

Another thing to be noted is that `d2i_PublicKey()` (even in 1.1.1) can decode that "garbage" (in 1.1.1, it calls `o2i_ECPublicKey()`).

Not sure where this gets us. Considering that this is new functionality, and used in a way that doesn't correspond to anything in older versions (specifically, giving NULL as an output structure doesn't correspond to anything), I have a hard time seeing this surprise as a regression.

The `openssl ec` command only handles SubjectPublicKeyInfo (i.e. it calls the PUBKEY functions in 1.1.1, not the PublicKey functions). 

Side note: I haven't explored what the "type-specific" output structure would result in.

I think that the question is what is expected to happen with a NULL output structure. While thinking about that, we also want to think about how we still support this "garbage", considering that it is supported in 1.1.1...

**Comment by levitte** [comment] 2021-11-06 07:27
It dawned on me that there's an inherent red herring here, which is kinda sorta already there in 1.1.1... The output in the reproducer isn't even DER, it's just a raw big number with no other marking whatsoever. So strictly speaking, `i2d_PublicKey()` should never have supported it ('cause "i2d" means "internal to DER").

That's probably part of what comes off as surprising, since the reproducer explicitly asks for DER.

So the question is, should we have another output type for this sort of thing? "OCTET" (inspired from the o in `i2o_ECPublicKey()`? "RAW"?

Meanwhile, the question is how to handle this in 3.0...

**Comment by mattcaswell** [comment] 2021-11-06 09:16
For 3.0, should we just not have any support for type-specific encoding of public EC keys? It doesn't really make any sense. Presumably the "NULL" output structure means "any", and so I would have expected to get SubjectPublicKeyInfo as the output.

Perhaps just leave the i2d_PublicKey() behaviour with EC keys alone. Its weird and wrong, but people might be relying on it.

**Comment by broken-bytes** [comment] 2021-11-06 10:37
@levitte Does that mean it has been broken like this in 1.1.1 since ever ? How did this not come up earlier. Kinda surprising.

Anyways, I think for the time being it would be best to have the docs updated regarding this

**Comment by levitte** [comment] 2021-11-06 11:11
@broken-bytes, there's the question of what support you're talking about, more specifically how you even get to calling i2d_PublicKey(). Like I said, `openssl ec` doesn't, it uses i2d_PUBKEY().

I'll do some research next week. Right now is weekend, I plan on enjoying it with non-openssl stuff 😉

**Comment by levitte** [comment] 2021-11-06 11:31
@mattcaswell, the meaning of "any" might not be well defined when multiple encoding implementations match the rest of the encoding parameters. The way it currently works is "whatever comes first", not "what the implementation deems to be a sane default".

It's actually possible, now that I think of it, that if the encoders were sorted differently in the provider's OSSL_ALGORITHM array, we'd get a different result. (being more careful with the order might be a way to define saner defaults.... that's not how I would solve it, thought, as the order should not matter, conceptually speaking)

**Comment by broken-bytes** [comment] 2021-11-06 22:50
@levitte Of course! Let me know if I can help out and test fixes. I am happy to help.

**Comment by levitte** [comment] 2021-11-07 05:11
It's early morning and this is on my mind...  so I did some quick research.

It turns out that there is a bug in our encoder implementation.  We have an EC encoder implementation with "type-specific" output structure which correctly doesn't output public keys.  However, we do have other type specific output structure names that are supposedly the same...  they're called "EC" and "X9.62", and they were specified to output a public key in some type specific form, which turns out to be a call to `i2o_ECPublicKey()`.

I've a quick fix for this...  however, this uncovers a bit of a design flaw in the encoder implementations, which I'll have a separate PR for.

**Comment by levitte** [comment] 2021-11-07 05:16
Side note: we do have support for encoding an EC public key using i2o_ECPublicKey.  We invented the output type "BLOB" (to be used instead of "DER") for that very purpose.  Implementation in this file: https://github.com/openssl/openssl/blob/openssl-3.0/providers/implementations/encode_decode/encode_key2blob.c

**Comment by levitte** [comment] 2021-11-07 05:25
Fix in #16983.  With that, the reproducer above will output a proper SubjecPublicKeyInfo.

**Comment by broken-bytes** [comment] 2021-11-07 12:37
@levitte Shall I pull and test that ?

**Comment by levitte** [comment] 2021-11-07 14:08
Please do!

**Comment by broken-bytes** [comment] 2021-11-07 20:43
@levitte Unless I did something wrong I can validate that this works

**Closed** 2021-11-09 04:42 UTC
Labels: branch: master, triaged: bug, branch: 3.0
