### ISSUE TITLE
Test test_cmp_http failed with icc build

### ISSUE THREAD

**Issue by Cassielcc** [openssl/openssl#15557] opened 2021-06-01 07:33 UTC
I tried to build openSSL with icc compiler. It could be built successfully, but when ran 'make -j4 -s test TESTS="test_cmp_http"' , it was failed. And the error information was attched

To reproduce,

> CC=icc ./config

> make

> make -j4 -s test TESTS="test_cmp_http"

[error.txt](https://github.com/openssl/openssl/files/6574287/error.txt)

I thought this issue was similar with #15386, but the workaround in #15386 didn't work for me. So I created a new bug. 
Anyone could help this ? I really appreciate your help.

**Comment by rsbeckerca** [comment] 2021-06-01 12:45
I think it may actually be the same as #15386. There is a fix (more complicated that the suggested workaround) that is in the pipeline for beta1, AFAIK. Check the PRs associated with that bug and try them instead of the workaround.

**Comment by t8m** [comment] 2021-06-01 13:04
What code are you trying to test? Current master branch or some alpha release?

**Comment by Cassielcc** [comment] 2021-06-01 15:20
I tested with the current master branch.

**Comment by rsbeckerca** [comment] 2021-06-01 15:23
Fix is not yet on master AFIAK

**Comment by t8m** [comment] 2021-06-01 15:35
There were #15417 and #15402 and both are merged already. Is there another related PR that I've missed?

**Comment by rsbeckerca** [comment] 2021-06-01 15:49
I'll check my build ASAP

**Comment by rsbeckerca** [comment] 2021-06-01 16:52
Well, my build on NonStop now is broken. So I can't verify anything anymore.
```
**** ERROR **** [1210]:
   crypto/evp/libcrypto-shlib-e_seed.o: In function `seed_cbc_cipher':
   crypto/evp/libcrypto-shlib-e_seed.o(.text+0x90): unresolved reference to
   EVP_CIPHER_CTX_encrypting.
**** ERROR **** [1210]:
   crypto/evp/libcrypto-shlib-e_seed.o: In function `seed_cfb128_cipher':
   crypto/evp/libcrypto-shlib-e_seed.o(.text+0x184): unresolved reference to
   EVP_CIPHER_CTX_num.
**** ERROR **** [1210]:
   crypto/evp/libcrypto-shlib-legacy_blake2.o: In function `blake2b_int_init':
   crypto/evp/libcrypto-shlib-legacy_blake2.o(.text+0x9): unresolved reference
   to EVP_MD_CTX_md_data.

No output file created.
```

**Comment by rsbeckerca** [comment] 2021-06-01 20:55
No, the fixes that were merged did not include everything. I am not sure what is missing, but something sure is.

```
/home/git/openssl-3.0: _RLD_LIB_PATH=`pwd` make -j4 -s test TESTS="test_cmp_http"
80-test_cmp_http.t ..
Warning: certificate from 'trusted.crt' with subject '/O=openssl_cmp' is not a CA cert
# cmp_main:/home/git/openssl-3.0/apps/cmp.c:2680:CMP info: using section(s) 'Mock connection' of OpenSSL configuration file '../Mock/test.cnf'
# opt_str:/home/git/openssl-3.0/apps/cmp.c:2203:CMP warning: -proxy option argument is empty string, resetting option
# setup_client_ctx:/home/git/openssl-3.0/apps/cmp.c:1903:CMP info: will contact http://127.0.0.1:80/pkix/
# CMP info: sending IR
# CMP error: connect timeout:
# CMP error: transfer error:request sent: IR, expected response: IP
../../../../util/wrap.pl ../../../../apps/openssl cmp -server '127.0.0.1:0' -config ../Mock/test.cnf -section 'Mock connection' -certout ../../../../test-runs/test_cmp_http/test.cert.pem -proxy '' -no_proxy 127.0.0.1 => 255
    not ok 1 - default config
# ------------------------------------------------------------------------------
    #   Failed test 'default config'
    #   at test/recipes/80-test_cmp_http.t line 147.
Warning: certificate from 'trusted.crt' with subject '/O=openssl_cmp' is not a CA cert
# cmp_main:/home/git/openssl-3.0/apps/cmp.c:2680:CMP info: using section(s) 'Mock connection' of OpenSSL configuration file '../Mock/test.cnf'
# opt_str:/home/git/openssl-3.0/apps/cmp.c:2203:CMP warning: -proxy option argument is empty string, resetting option
# setup_client_ctx:/home/git/openssl-3.0/apps/cmp.c:1903:CMP info: will contact http://example.com:80/pkix/
```
There is a lot more. I am going to reopen the original case.

**Comment by rsbeckerca** [comment] 2021-06-01 23:19
> 
> 
> There were #15417 and #15402 and both are merged already. Is there another related PR that I've missed?

Something was definitely missed. Please bring @DDvO into the discussion.

**Comment by levitte** [comment] 2021-06-02 06:02
That test recipe is quite a bit over-worked...  I can attempt to make something that's a bit more flexible.

**Comment by levitte** [comment] 2021-06-02 06:17
Please try #15580

**Comment by Cassielcc** [comment] 2021-06-02 08:01
I tried #15580, but still got different errors.
[error2.txt](https://github.com/openssl/openssl/files/6583018/error2.txt)

**Comment by levitte** [comment] 2021-06-02 08:48
I just pushed a small fix to #15580, please try again?

**Comment by levitte** [comment] 2021-06-02 09:39
Hmmm, github misbehaved an hour or so ago, so maybe that push was lost...

**Comment by DDvO** [comment] 2021-06-02 12:03
Hmm, the first of the test cases should succeed but it does not:
```
# setup_client_ctx:apps/cmp.c:1903:CMP info: will contact http://127.0.0.1:80/pkix/
# CMP error: unsupported:No supported data to decode.
# CMP info: sending IR
# CMP error: connect timeout:
# CMP error: transfer error:request sent: IR, expected response: IP
../../../../util/wrap.pl ../../../../apps/openssl cmp -server '127.0.0.1:0' -config ../Mock/test.cnf -section 'Mock connection' -certout ../../../../test-runs/test_cmp_http/test.cert.pem -proxy '' -no_proxy 127.0.0.1 => 1
    not ok 1 - default config
```
and this certainly not an issue with `80_test_cmp.t`.

The first of the two errors
```
# CMP error: unsupported:No supported data to decode.
```
gets ignored, and most likely is a spurious error raised in `crypto/encode_decode/decoder_lib.c`; it should be suppressed.

The second error is a real one:
```
# CMP info: sending IR
# CMP error: connect timeout:
# CMP error: transfer error:request sent: IR, expected response: IP
```
and this is likely due to an issue with the BIO IP layer, OS, or compiler.

**Comment by DDvO** [comment] 2021-06-02 12:05
We should have independent HTTP/TCP client-server tests,
such that not every issue at that level shows as a CMP issue.

**Comment by DDvO** [comment] 2021-06-02 12:15
> I tried to build openSSL with icc compiler.

@Cassielcc, which OS do you use?
How to install `icc` on Debian Linux, if possible in a simple non-invasive way?

**Comment by DDvO** [comment] 2021-06-02 13:24
Meanwhile I noticed that
```
# setup_client_ctx:apps/cmp.c:1903:CMP info: will contact http://127.0.0.1:80/pkix/

```
indicates the issue - the client connects not to the port where the server listens, but to the default port: 80.
This implies some issue with `80-test_cmp_http.t` detecting the server port to use for the client.

**Comment by levitte** [comment] 2021-06-02 18:24
> the client connects not to the port where the server listens, but to the default port: 80.

I have a local server answering on port 80, so no wonder this never became an issue for me

**Comment by rsbeckerca** [comment] 2021-06-02 18:31
> 
> 
> > the client connects not to the port where the server listens, but to the default port: 80.
> 
> I have a local server answering on port 80, so no wonder this never became an issue for me

And for us, port `80` is specifically locked away out of prudent paranoia. You'd need root to listen on it and we don't run tests under `sudo`.

**Comment by levitte** [comment] 2021-06-02 18:47
> Meanwhile I noticed that
> ```
> # setup_client_ctx:apps/cmp.c:1903:CMP info: will contact http://127.0.0.1:80/pkix/
> 
> ```
> indicates the issue - the client connects not to the port where the server listens, but to the default port: 80.
> This implies some issue with `80-test_cmp_http.t` detecting the server port to use for the client.

Uhmmmmm what?  No, that's not it.  Why would the port become 80 if that's the case?

Rather, I think this comes down to:

https://github.com/openssl/openssl/blob/ea8215810319722cf76f777f812688eb3d632678/crypto/http/http_lib.c#L109-L112

and:

https://github.com/openssl/openssl/blob/ea8215810319722cf76f777f812688eb3d632678/crypto/http/http_lib.c#L213-L216

It seems you don't have a way to detect if a port was given at all or not

**Comment by DDvO** [comment] 2021-06-02 20:07
> > the client connects not to the port where the server listens, but to the default port: 80.
> 
> I have a local server answering on port 80, so no wonder this never became an issue for me

This would not help - your server will most likely not speak CMP :wink:

**Comment by DDvO** [comment] 2021-06-02 20:08
> [deleted]
> 
> Never mind, I was looking at the wrong spot

As I wrote, what goes wrong is that the client does not learn the right port number, just the pseudo-value "0" which indicates 80 for HTTP.

**Comment by rsbeckerca** [comment] 2021-06-02 20:37
> 
> 
> > [deleted]
> > Never mind, I was looking at the wrong spot
> 
> As I wrote, what goes wrong is that the client does not learn the right port number, just the pseudo-value "0" which indicates 80 for HTTP.

When I pass `-port 0` to `cmp`, I do get a reasonable value that is not `80`.

**Comment by DDvO** [comment] 2021-06-03 06:34
> > As I wrote, what goes wrong is that the client does not learn the right port number, just the pseudo-value "0" which indicates 80 for HTTP.
> 
> When I pass `-port 0` to `cmp`, I do get a reasonable value that is not `80`.

I was talking here about the client side of things.
For the HTTP client, giving "0" (or no port) means 80 for HTTP and 443 for HTTPS.
For the HTTP server, giving "0" means to choose any available (non-privileged) local port.

**Comment by rsbeckerca** [comment] 2021-06-03 11:47
> > > As I wrote, what goes wrong is that the client does not learn the right port number, just the pseudo-value "0" which indicates 80 for HTTP.
> > 
> > When I pass `-port 0` to `cmp`, I do get a reasonable value that is not `80`.
> 
> I was talking here about the client side of things.
> For the HTTP client, giving "0" (or no port) means 80 for HTTP and 443 for HTTPS.
> For the HTTP server, giving "0" means to choose any available (non-privileged) local port.

Sorry. I misunderstood. :(

**Comment by Cassielcc** [comment] 2021-06-03 13:33
> @Cassielcc, which OS do you use?
How to install icc on Debian Linux, if possible in a simple non-invasive way?

I used Ubuntu 18.04.  Which version of Debian you use? It seems only Debian* 9.x, 10.x are supported.

**Comment by Cassielcc** [comment] 2021-06-03 13:46
> and this is likely due to an issue with the BIO IP layer, OS, or compiler.

Actually, I tested successfully with gcc on the same system.  But failed with icc, I'm not sure if  it is a problem with the icc compiler.   

How to see what command is executed by ‘ make -j4 -s test TESTS="test_cmp_http" ’？

**Comment by rsbeckerca** [comment] 2021-06-03 13:58
> 
> 
> > and this is likely due to an issue with the BIO IP layer, OS, or compiler.
> 
> Actually, I tested successfully with gcc on the same system. But failed with icc, I'm not sure if it is a problem with the icc compiler.
> 
> How to see what command is executed by ‘ make -j4 -s test TESTS="test_cmp_http" ’？

Try `make V=1 -j4 -s test TESTS="test_cmp_http"`

**Comment by DDvO** [comment] 2021-06-03 14:05
> > and this is likely due to an issue with the BIO IP layer, OS, or compiler.
> 
> Actually, I tested successfully with gcc on the same system. But failed with icc, I'm not sure if it is a problem with the icc compiler.

So this does sound like a compiler issue.

> How to see what command is executed by ‘ make -j4 -s test TESTS="test_cmp_http" ’？

If you add `V=1` to the call, you can see the commands it executes. 
They are all `openssl cmp` in many variations in the parameters.

**Comment by Cassielcc** [comment] 2021-06-03 14:30
Thanks @rsbeckerca and @DDvO , I will try.

> I typically use vanilla Debian 10 (buster). How to install and use icc there?

To install icc compiler only that I used, you can download it from https://software.intel.com/content/www/us/en/develop/articles/oneapi-standalone-components.html, in the ' Intel® C++ Compiler Classic ' section.

>  Is is officially supported by OpenSSL? I cannot find anything about that.
I'm not sure. But I saw some old issues about icc built, for example #4248.  So, I think icc is supported by openssl.

**Comment by Cassielcc** [comment] 2021-06-03 14:31
Thanks @rsbeckerca and @DDvO , I will try.

> I typically use vanilla Debian 10 (buster). How to install and use icc there?

To install icc compiler only that I used, you can download it from https://software.intel.com/content/www/us/en/develop/articles/oneapi-standalone-components.html, in the ' Intel® C++ Compiler Classic ' section.

> Is is officially supported by OpenSSL? I cannot find anything about that.

I'm not sure. But I saw some old issues about icc built, for example #4248. So, I think icc is supported by openssl.

**Comment by DDvO** [comment] 2021-06-03 14:59
> To install icc compiler only that I used, you can download it from https://software.intel.com/content/www/us/en/develop/articles/oneapi-standalone-components.html, in the ' Intel® C++ Compiler Classic ' section.

Goodness, this asks for downloading 1.1 GB and installing 4.5 GB. 
Cannot afford that since my SSD only has some 3 GB left free.
Shame that they do not support installing just the C compiler portion.

**Comment by DDvO** [comment] 2021-06-03 15:02
Anyway, does the current state of #15580 solve the issue for you?

**Comment by DDvO** [comment] 2021-06-04 05:03
> Anyway, does the current state of #15580 solve the issue for you?

It would be surprising if so, because your issue seems compiler-dependent, and #15580 does not change any C code.
Let us know.

**Comment by DDvO** [comment] 2021-06-04 18:26
@Cassielcc, does the current state of #15580 fix the issue?

**Closed** 2021-06-06 05:36 UTC
Labels: triaged: bug

**Comment by DDvO** [comment] 2021-06-06 17:59
@Cassielcc, if the malfunction is still present with your `icc` build you can re-open this issue.

**Comment by Cassielcc** [comment] 2021-06-07 03:55
> @Cassielcc, does the current state of #15580 fix the issue?

I tested, but failed due to lack of some libs in icc. And I tried to figure out.

> @Cassielcc, if the malfunction is still present with your icc build you can re-open this issue.

 If I confirm that it is not a problem in icc, I will re-open this issue.   Thanks all of you.

**Comment by Cassielcc** [comment] 2021-06-07 08:56
Hi all,  good news, I tested successfully with  #15580.  😊

Thanks all of you again.

**Comment by DDvO** [comment] 2021-06-07 09:58
Pleased to hear!

Yet strange that you cannot reproduce the issue anymore, since #15580 did not change any C code and you mentioned that you had the issue only with `icc`, not when using `gcc`.
Looks like there was some inconsistency in the branches you used, and #15580 fixed the rest of the issue.
