### ISSUE TITLE
openssl-3 API clash with libressl: EVP_CIPHER_CTX_get_iv()

### ISSUE THREAD

**Issue by marckleinebudde** [openssl/openssl#13631] opened 2020-12-07 16:09 UTC
During the development of openssl-3 in https://github.com/openssl/openssl/pull/12233 the functions `EVP_CIPHER_CTX_get_iv_state()` and `EVP_CIPHER_CTX_get_iv()` were introduced.

However, in libressl for almost two years, a function with the same name `EVP_CIPHER_CTX_get_iv()` already exists (https://github.com/libressl-portable/openbsd/commit/db321d7792). This function is used in openssh since commit https://github.com/openssh/openssh-portable/commit/482d23bcacdd3664f21cc82a5135f66fc598275f.

This breaks openssh, when compiling with openssl-3. I've raised this issue on the openssh ML (https://lists.mindrot.org/pipermail/openssh-unix-dev/2020-December/039003.html) and @daztucker asked to rename the functions: 

> Maybe OpenSSL could change it before 3.0 instead of shipping an incompatible API?  EVP_CIPHER_CTX_get_original_iv would be consistent with the function they deprecated. ie:
> ```
> EVP_CIPHER_CTX_get_iv -> EVP_CIPHER_CTX_get_original_iv
> EVP_CIPHER_CTX_get_iv_state -> EVP_CIPHER_CTX_get_iv
> ```

**Comment by kroeckx** [comment] 2020-12-07 16:21
This is a duplicate of #9524 and #13411

**Comment by paulidale** [comment] 2020-12-08 10:04
We will rename these APIs because the current names are confusing.

**Comment by paulidale** [comment] 2020-12-08 10:05
Confirming that this is a duplicate of #13411.  Closing this one.

**Closed by paulidale** 2020-12-08 10:05 UTC
Labels: issue: bug report

**Comment by kaduk** [comment] 2020-12-09 20:13
>  EVP_CIPHER_CTX_get_original_iv would be consistent with the function they deprecated

Just to note it here: the whole point of picking a new name was to not be consistent with the function that was deprecated, since we concluded (at least at the time) that it was a bad name.
