### ISSUE TITLE
SHA performance test

### ISSUE THREAD

**Issue by yxungh** [openssl/openssl#13578] opened 2020-12-01 03:42 UTC
When I compared openssl 3.0 and openssl 1.1.1f, I found that the performance of alpha9 was lower than that of alpha5.
I am also comparing with OpenSSL 1.1.1f. I wonder if this can explain the problem.

All numbers are Percentage Diff (%)(alpha5-1.1.1f/1.1.1f)
alpha5 | 16 bytes | 64 bytes | 256 bytes | 1024 bytes | 8192 bytes | 16384 bytes
-- | -- | -- | -- | -- | -- | --
sha1 | -74.24694646 | -67.83789878 | -56.77331253 | -20.98058948 | -4.089929654 |-2.746844537
sha256 |  -68.18784269 | -59.0421308 | -42.57797189 | -20.2773497 | 2.462470535 | -14.52529967
sha512 |  -56.98251239 | -56.75811124 | -44.69438411 | -19.60932482 | 2.45562681 | -33.7214586

All numbers are Percentage Diff (%)(alpha9-1.1.1f/1.1.1f)
alpha9 | 16 bytes | 64 bytes | 256 bytes | 1024 bytes | 8192 bytes | 16384 bytes
-- | -- | -- | -- | -- | -- | --
sha1 |  -74.93675632 | -68.51181924 |  -55.35508324 |  -35.25122672 | -5.811513632 |  -2.937482437
sha256 | -93.95017321 |  -93.97662812 |  -88.74451967 |  -77.98002727 | -51.3641645 |  -46.51934182
sha512 |  -89.04846118 |  -93.23677374 | -84.93249856 | -76.25703978 |  -24.29898999 |  -37.92422949

using `openssl speed -evp` ,Five tests, and the results are almost the same.

**Comment by beldmit** [comment] 2020-12-16 10:10
Running the `speed -evp sha256` with 16 and 16384 bytes under valgrind show that for 16-bytes blocks it spends approx. 30% in the `evp_generic_fetch` function (with descendants). For 16384-bytes block this time is about 4%.

So reducing the number of calls of the `evp_generic_fetch` function will significantly improve the difference but I still have questions about how relevant this benchmark is.

**Comment by levitte** [comment] 2020-12-16 11:14
Thanks for confirming my suspicions, @beldmit.  In my view, fetching shouldn't be part of the measurement at all, as that's overhead, and because there's a definite "cold" and "hot" state for every algorithm being fetched.

This calls for a bit of refactoring in `apps/speed.c`

**Comment by richsalz** [comment] 2020-12-16 14:54
Have an option to "prewarm" the fetch or not.  Being able to see the overhead added by the dynamic lookups is useful. And arguably, if you're testing the "EVP" API you want to know all of it :)

**Comment by levitte** [comment] 2020-12-16 15:02
> if you're testing the "EVP" API you want to know all of it :)

`openssl speed` is, as far as I know, designed to measure the performance of the algorithms proper.  If you look, you'll find measureing sections formed by `Time_F(START)` and `Time_F(STOP)` timer calls, and will hopefully notice that overhead is outside of the measuring sections.  I can only conclude that some of the overhead has slipped inside those measuring sections.

**Comment by richsalz** [comment] 2020-12-16 15:04
I am sure it will not be difficult to have the 'speed' program measure how long EVP takes.  I am confident that will be useful, to the project as well.  There is currently no way to understand the overhead right now.

**Comment by beldmit** [comment] 2020-12-16 15:22
I dived into the `speed` program second time in my life and the impression did not get better since the 1st time.

I think it's worth writing a brand new `speedevp` utility with EVP-only interface inside and deprecate the current `speed` one but don't believe it's realistic for 3.0.

**Comment by beldmit** [comment] 2020-12-16 15:23
> > if you're testing the "EVP" API you want to know all of it :)
> 
> `openssl speed` is, as far as I know, designed to measure the performance of the algorithms proper. If you look, you'll find measureing sections formed by `Time_F(START)` and `Time_F(STOP)` timer calls, and will hopefully notice that overhead is outside of the measuring sections. I can only conclude that some of the overhead has slipped inside those measuring sections.

We measure speed calling `EVP_Digest` calling `EVP_MD_fetch` calling `evp_generic_fetch`

**Comment by levitte** [comment] 2020-12-16 16:04
> We measure speed calling `EVP_Digest` calling `EVP_MD_fetch` calling `evp_generic_fetch`

Ah, yeah, `EVP_Digest()` doesn't lend itself very well for these measurements.  It should probably be divided up in clearer Init/Update/Final steps with appropriate timer start and stop in between.

**Comment by t8m** [comment] 2020-12-16 18:00
Wouldn't it be just sufficient to replace EVP_xyz() with an explicit EVP_MD_fetch() outside of the loops?

**Comment by t8m** [comment] 2020-12-16 18:01
At least as a dirty hack type of solution.

**Comment by beldmit** [comment] 2020-12-16 18:44
I've tried it but no, it still invokes EVP_MD_fetch from EVP_DigetInit_ex

**Comment by t8m** [comment] 2020-12-17 08:20
Did you really try doing EVP_MD_fetch outside of the loops and not just put the const EVP_shaxyz() call outside of the loops? Because if you use the placeholder EVP_shaxyz() it will cause the implicit EVP_MD_fetch in EVP_DigestIniit_ex to be invoked.  But with an explicitly fetched EVP_MD there should be no implicit fetch in the EVP_DigestInit_ex.

**Comment by beldmit** [comment] 2020-12-17 08:39
I tried to explicitly call `EVP_MD_fetch` if evp_md (passed to EVP_Digest) is NULL.

The very dirty patch I hoped to work (no, it did not) was looking like
```
diff --git a/apps/speed.c b/apps/speed.c
index 07c2238ab2..d98f5a59f0 100644
--- a/apps/speed.c
+++ b/apps/speed.c
@@ -1010,6 +1010,9 @@ static int EVP_Digest_loop(void *args)
     unsigned char md[EVP_MAX_MD_SIZE];
     int count;
 
+    if (evp_md == NULL)
+           evp_md = EVP_MD_fetch(NULL, "sha256", "");
+
     for (count = 0; COND(c[D_EVP][testnum]); count++) {
         if (!EVP_Digest(buf, lengths[testnum], md, NULL, evp_md, NULL))
             return -1;
```

**Comment by levitte** [comment] 2020-12-17 08:45
Hmmmmm, I thought that the intention was to detect if the passed md was already fetched (which is easy, there's a `prov` attribute that is non-NULL in that case)...  don't we do that?  That could be worth a dig.

However, hacking inside EVP_Digest_loop doesn't help at all, because this:

https://github.com/openssl/openssl/blob/master/apps/speed.c#L2925-L2927

The preparations must happen *outside* of the `Time_F(START)`..`Time_F(STOP)` section!!!

**Comment by beldmit** [comment] 2020-12-17 09:03
I had an idea that if we provide an explicitly fetched EVP_MD object to EVP_Digest we will not fetch it again and again. If we do it once on the first call instead of once per block, it is not ideal from the benchmark point of view but will give us some clues.

**Comment by t8m** [comment] 2020-12-17 09:10
> 
> ```
> diff --git a/apps/speed.c b/apps/speed.c
> index 07c2238ab2..d98f5a59f0 100644
> --- a/apps/speed.c
> +++ b/apps/speed.c
> @@ -1010,6 +1010,9 @@ static int EVP_Digest_loop(void *args)
>      unsigned char md[EVP_MAX_MD_SIZE];
>      int count;
>  
> +    if (evp_md == NULL)
> +           evp_md = EVP_MD_fetch(NULL, "sha256", "");
> +
>      for (count = 0; COND(c[D_EVP][testnum]); count++) {
>          if (!EVP_Digest(buf, lengths[testnum], md, NULL, evp_md, NULL))
>              return -1;
> ```

This cannot work because `evp_md != NULL` here but it points at the const, placeholder EVP_MD object for an algorithm.
You would always have to do the explicit fetch here.
```
real_md = EVP_MD_fetch(NULL, OBJ_nid2sn(EVP_MD_type(evp_md)), NULL);
... loop here with real_md ...
EVP_MD_free(real_md);
```

**Comment by t8m** [comment] 2020-12-17 09:14
But for quick fix of the -evp option it should be possible to replace the EVP_getdigestbyname() when handling the -evp option with an explicit fetch. Of course it will require changing the evp_md to nonconst and freeing it after the benchmark.

**Comment by beldmit** [comment] 2020-12-17 09:20
> This cannot work because `evp_md != NULL` here but it points at the const, placeholder EVP_MD object for an algorithm.
> You would always have to do the explicit fetch here.
> 
> ```
> real_md = EVP_MD_fetch(NULL, OBJ_nid2sn(EVP_MD_type(evp_md)), NULL);
> ... loop here with real_md ...
> EVP_MD_free(real_md);
> ```

Yes, it works this way (still with some performance degradation).

**Comment by beldmit** [comment] 2020-12-17 09:29
For short blocks I suppose that smth from 7% per EVP_MD_size, 7% per EVP_MD_CTX_reset, 7% per EVP_MD_CTX_free, and 7% per ENGINE_get_digest_engine should be eliminated some way.

**Comment by beldmit** [comment] 2020-12-23 10:14
There are some more issues so reopening.

**Comment by kroeckx** [comment] 2020-12-23 21:08
Results for sha256 with current master (38f7931429859a3bd07725dbc451c0b4cac26a10) and 1.1.1-stable:

What | 16 bytes | 64 bytes | 256 bytes | 1024 bytes | 8192 bytes | 16384 bytes
-- | -- | -- | -- | -- | -- | --
1.1.1-stable |  39534 | 103747 | 208087 | 276831 | 304770 | 308235
master | 35956 | 97962| 201557 | 274477 | 303744 | 307301
difference |  -9.0% | -5.6% | -3.1% | -0.9% | -0.3% | -0.3%

**Comment by beldmit** [comment] 2020-12-23 21:11
There are at least 2 PRs to be reviewed and merged.

**Comment by kroeckx** [comment] 2020-12-23 21:13
What I don't understand is why @yxungh  always sees much larger differences.

**Comment by beldmit** [comment] 2020-12-23 21:16
There was a significant slowdown before #13721 was merged

**Comment by richsalz** [comment] 2020-12-29 18:01
Isn't this a dup of #13407?

**Comment by beldmit** [comment] 2020-12-30 08:46
@richsalz, I think it is not because cipher and digest slowdowns are caused by different reasons.

@yxungh, I suppose it can be closed now?

**Comment by yxungh** [comment] 2020-12-30 08:51
Thanks!

**Closed** 2020-12-30 08:50 UTC
Labels: branch: master, triaged: OTC evaluated, triaged: bug
