### ISSUE TITLE
Error reporting and reason table generation for providers

### ISSUE THREAD

**Issue by levitte** [openssl/openssl#9003] opened 2019-05-25 07:25 UTC
*NOTE: this is an age old issue that has existed since the beginning of ENGINEs*

Providers will have to be able to report errors, and we already have the mechanisms for doing so "the OpenSSL way" via `put_error` and `add_error_vdata` upcalls.  However, is that sufficient?

As everyone (or well, some at least), our error codes contain quite a lot of information:

1. 8-bit "library" code (in terms we tend to use today, that's sub-system code)
2. 12-bit function code
3. 12-bit reason code

How much of this is needed for a provider?  Logically, the "library" code should be the same for a whole provider, and the value function codes have been questioned before...
Reason codes and associated printable strings are another matter, they are fairly universally accepted error reporting tools (see `errno` and `strerror` on Unix, or corresponding on other platforms).

Furthermore, reason strings in OpenSSL is a fairly complicated matter, and is done by using `util/mkerr.pl`, which scans the source for function code macros and reason code macros, and generates header files to define those macros (give them numbers) and source files for the associated strings.  However, that script is internal and is never made publicly available (which has always been a problem for any ENGINE author).

So the question is, how can we make it simpler for provider authors?  Can we make it in such a way that they just need to provide reason codes and strings as a simple array of \< number, string \> tuples, and then report the reason numbers as they see fit?  As an alternative, should providers offer a `strerror` like function for libcrypto to call when it needs a string?

**Comment by levitte** [comment] 2019-05-25 07:31
A few notes on this matter:

1. We currently cheat enormously in the providers we're building.  We do generate provider specific error codes and strings, but they end up in libcrypto.  We cannot expect other provider authors to use this methods, and I would argue that if we should eat our own dog food, i.e. whatever we ask external providers authors to do, we should also do ourselves, at the very least in dynamically loadable provider modules.
2. If we want others to generate reason codes and strings the way we do internally, we should also create a public tool to do so.
3. The alternative idea with having providers offer a `strerror` like function is contrary to how the ERR sub-system currently works (it relies on pre-loaded string tables), so may be more difficult to implement.

**Comment by levitte** [comment] 2019-05-25 07:33
On reason codes, it's been suggested to me that providers should report errors back to libcrypto in string form only.  I'm not sure I'm keen on the idea, but will not deny it either.

**Comment by levitte** [comment] 2019-05-25 07:39
One last note: considering that we're coding to allow an "unlimited" amount of providers at the same time, there has to be a way to distinguish which one an error came from.  This is where the "library" code comes in.

This problem has already been solved in the form of `ERR_get_next_error_library()`, which could be called in libcrypto, for example when an OSSL_PROVIDER structure is created.  In other words, the provider doesn't really need to know.

**Comment by beldmit** [comment] 2019-05-25 10:23
Maintaining an engine, I used the script ```util/mkerr.pl```.
I think it should be used for this purpose.

Btw, another problem that occurs is that if errors are printed after the library (engine) is unloaded, the engine name is missed from the error strings.

**Comment by levitte** [comment] 2019-05-25 14:00
> Maintaining an engine, I used the script `util/mkerr.pl`.

I suppose you have the OpenSSL source somewhere to do so.  I think that's an awkward demand to make on anyone writing an external module, we should have an installable script that everyone can use.  Also, the `.ec` format is not documented (at least not publicly as far as I know), and for something that typically is just one line (just as a casual example, see [`engines/e_capi.ec`](https://github.com/openssl/openssl/blob/master/engines/e_capi.ec)), it feels a bit over-engineered.

**Comment by richsalz** [comment] 2019-05-25 15:09
Thank you for writing this up.  Another thing to consider: if you have the function name, do you also need the file/line-number, or vice-versa? Can that kind of simplification reduce the problem that needs to be solved?

For this release, I like a "report internal error" API, which could take a string (or varargs0 as you mentioned above.

**Comment by levitte** [comment] 2019-05-25 15:15
@richsalz, I do recall a discussion we had a few years ago, where you wanted to get rid of the function codes and I didn't. Since then, I have had the time to rethink that, and I don't really see a need for them any more.

**Comment by mattcaswell** [comment] 2019-05-27 09:10
The biggest problem I see with function codes is that people sometimes have logic that checks the error code and does different things based on what the error is. Generally speaking we've discouraged such practice - we make no guarantees about stability of error codes from one version to the next. If code gets refactored then the function that generates an error could change. This means that an error code can change (this could happen even in a "patch" release).

OTOH when people raise issues with us we don't always have the file/line-number information available so all we've go to go on is the reason code/function code - which is usually enough (when we know a specific openssl version) to figure out which bit of code raised the error. If we didn't have the function code then this would make such diagnosis almost impossible.

Another problem I see with our existing error system is that it just doesn't provide enough information a lot of the time for people to figure out what actually went wrong. When performing some high level function (e.g. SSL_read) this has a lot of complex code behind it and a lot of processing goes on. There are huge number of ways that that can go wrong - but the errors we give back are very short and not very informative.

I'm not sure how useful it is to compare our error system with a libc type error system. A Linux/Unix type system has a relatively short list of error codes and associated error strings. I guess Windows is similar. But most libc calls are not doing complex processing. In most cases there are only a limited number of things that could go wrong, so just knowing "file not found", or "out of memory" is enough to go on. Compare that with SSL_read which does a huge amount of complex processing and invokes complex sub-processes such as X509 validation etc. If something goes wrong in any of those steps you need more descriptive errors to figure out exactly what the problem is.

An ideal error system would have the following properties IMO:
- Provides a detailed descriptive error text to enable human interpretation and diagnosis - potentially with different text for each individual error site.
- Conflicting with the property above is the need to not be a memory hog and keep vast numbers of strings in memory
- Provides some machine readable error code to enable some automated processing of specific classes of errors
- Error codes remain stable across versions
- Providers should have a simple error interface and not be required to import lots of OpenSSL specific error processing tools

**Comment by levitte** [comment] 2019-05-27 09:46
@mattcaswell says:
> The biggest problem I see with function codes is that people sometimes have logic that checks the error code and does different things based on what the error is.

This is common practice, isn't it?  Don't we do that ourselves with diverse `errno` codes (for example `EAGAIN`)?

Not sure that has much to do with function codes per se...  except that with the current construct, where each sub-system has its own set of reason codes, that has to be checked.  I would rather see one single set of reason codes per entity (entity being a library or a module).

> If we didn't have the function code then this would make such diagnosis almost impossible.

How do others do it?  Our function code encoding is fairly unique as far as I know...

> Another problem I see with our existing error system is that it just doesn't provide enough information a lot of the time for people to figure out what actually went wrong.

I agree.  We are not very good at using things like `ERR_add_error_data`...  on the other hand, that's a fairly clumsy function in our day and age (let's remember that this function is from the 90's, when the conditions for making this kind of thing were hugely different from what we have today).  I would imagine that something that combines the codes that we want (entity and reason at least) with a printf-like set of parameters would be ideal.  Say, something like this?

``` C
/* fmt can be NULL for no added text */
int ERR_raise_error(int lib, int reason, const char *fmt, ...);
```

> [re short set of error codes] I guess Windows is similar. 

Uhmm, no, definitely not.

> I'm not sure how useful it is to compare our error system with a libc type error system. A Linux/Unix type system has a relatively short list of error codes and associated error strings. I guess Windows is similar. But most libc calls are not doing complex processing. In most cases there are only a limited number of things that could go wrong, so just knowing "file not found", or "out of memory" is enough to go on. Compare that with SSL_read which does a huge amount of complex processing and invokes complex sub-processes such as X509 validation etc. If something goes wrong in any of those steps you need more descriptive errors to figure out exactly what the problem is.

I can't pull one out of my hat right now, but I have seen descriptions of some functionalities that list their own set of errno codes, and then mention that other codes may be returned as well, from underlying functionality.

Either way, the complexity leads to a stack of errors, not just SSL level errors, no?

> - Error codes remain stable across versions

This is ambiguous...  the error macros *are* stable, we go to quite some length to ensure it.  However, what error codes are generated by specific functions isn't quite as stable.  I assume you mean the latter.

> - Providers should have a simple error interface and not be required to import lots of OpenSSL specific error processing tools.

I agree.  I'd say that the minimum functionality required should be a way to translate a reason code to a string (either by letting the provider specify an array of \< int, string \> tuples, or a `strerror` like function), and a function to raise an error, like the one I proposed higher up?

**Comment by mattcaswell** [comment] 2019-05-27 10:31
>> The biggest problem I see with function codes is that people sometimes have logic that checks the error code and does different things based on what the error is.
>
> This is common practice, isn't it? Don't we do that ourselves with diverse errno codes (for example EAGAIN)?

Yes it is common practice for applications to check our errors codes and have different logic based on it. Unfortunately this just doesn't work properly for us because these errors codes are not stable - primarily because of the use of function codes. We frequently refactor things and move them around. Hence the same error is suddenly being detected in a different function to where it was before, and you get a different error code back, e.g.

````
int FOO_stuff(void)
{
    /* do stuff */
    if (error) {
        FOOerr(FOO_F_FOO_STUFF, FOO_R_BLAH);
        return 0;
    }
    return 1;
}
````
If this gets refactored to
````
static int stuff_sub_func(void)
{
    /* do stuff */
    if (error) {
        FOOerr(FOO_F_STUFF_SUB_FUNC, FOO_R_BLAH);
        return 0;
    }
    return 1;
}
int FOO_stuff(void)
{
    if (!stuff_sub_func())
        return 0;
    return 1;
}
````
Then, the implementation is equivalent. We haven't changed any of the implementation details, and all the same error conditions and reason codes are returned. But the *function* code has changed, even though it is the same error. Any application checking the full error code (rather than just the reason code) - which as you say is common practice -  will suddenly get a different error code back and their code is broken. This instability of error codes can happen even in patch releases. The result is no one can currently rely on our error codes.

> Either way, the complexity leads to a stack of errors, not just SSL level errors, no?

Right - in theory - but we are hugely inconsistent about this. Not everywhere that an error occurs do we add an error to the stack. This means either you just end up with the low level error which is often not very informative, or just a very high level "something failed" type error which also doesn't help too much. Often the resulting stacks are very cryptic and incomprehensible to end users.

> This is ambiguous... the error macros are stable, we go to quite some length to ensure it. However, what error codes are generated by specific functions isn't quite as stable. I assume you mean the latter.

Right. I'm mostly worried about the "function code" instability I mention above.

**Comment by levitte** [comment] 2019-05-27 11:07
@mattcaswell says:
> Yes it is common practice for applications to check our errors codes and have different logic based on it. Unfortunately this just doesn't work properly for us because these errors codes are not stable - primarily because of the use of function codes. We frequently refactor things and move them around. Hence the same error is suddenly being detected in a different function to where it was before, and you get a different error code back, e.g.

Yes, and this is a good reason to ditch function codes...  it seems we agree?

I did a quick check of what we do check ourselves, and it looks like we use don't check the function codes very much ourselves:

```
: ; git grep ERR_GET_LIB apps crypto ssl | grep -v ^crypto/err/
apps/rsa.c:                   ERR_GET_LIB(err) == ERR_LIB_RSA &&
apps/speed.c:                    ERR_GET_LIB(error) == ERR_LIB_EVP &&
crypto/ec/ec2_oct.c:            if (ERR_GET_LIB(err) == ERR_LIB_BN
crypto/ec/ecp_oct.c:        if (ERR_GET_LIB(err) == ERR_LIB_BN
crypto/rsa/rsa_gen.c:            if (ERR_GET_LIB(error) == ERR_LIB_BN
ssl/ssl_lib.c:        if (ERR_GET_LIB(l) == ERR_LIB_SYS)
ssl/ssl_rsa.c:        if (ERR_GET_LIB(err) == ERR_LIB_PEM
: levitte@lapdog:~/gitwrk/openssl.net/official/master
: ; git grep ERR_GET_FUNC apps crypto ssl | grep -v ^crypto/err/
apps/rsa.c:                   ERR_GET_FUNC(err) == RSA_F_RSA_CHECK_KEY_EX &&
apps/speed.c:                    ERR_GET_FUNC(error) == EVP_F_INT_CTX_NEW &&
```

In both cases that we do, I'll assume that we could as well use `ERR_GET_LIB`

> > Either way, the complexity leads to a stack of errors, not just SSL level errors, no?
> 
> Right - in theory - but we are hugely inconsistent about this.

Yes, we need to get better...

> Right. I'm mostly worried about the "function code" instability I mention above.

Let's ditch'em!

**Comment by paulidale** [comment] 2019-05-28 01:59
+1 for ditching function codes.  I've wondered several times why they exist.

`__FUNCTION__` (gcc) or `__func__` (c99) would be a possible partial substitute that is more readable.

I like the `ERR_raise_error` suggestion with a format argument.  This might enable a reduction in the number of reason codes and still provide better feedback to our users.

**Comment by richsalz** [comment] 2019-05-30 16:30
If you want a PR to remove function codes, I am willing to help with that.

**Comment by richsalz** [comment] 2019-05-31 20:29
See #9058

**Comment by DDvO** [comment] 2019-07-18 09:37
On the one hand I'm very glad that the hard-to-maintain function codes are being eliminated,
on the other hand seeing function names in error reports can be very helpful so I do hope they will still be inserted automatically by some other means.

> `__FUNCTION__` (gcc) or `__func__` (c99) would be a possible partial substitute that is more readable.

Yeah, why not use this very convenient automatic support by the compiler?
I'm aware that this is not always possible due to backward compatibility with C90 and potentially pedantic compiler settings. What I've been using so far as a pragmatic solution is something like the following:
```
# if defined(__STDC_VERSION__) && (__STDC_VERSION__ >= 199901)
#  define OPENSSL_FUNC __func__
# elif defined(__STDC__) && defined(PEDANTIC)
#  define OPENSSL_FUNC "(PEDANTIC disallows function name)"
# elif defined(WIN32) || defined(__GNUC__) || defined(__GNUG__)
#  define OPENSSL_FUNC __FUNCTION__
# elif defined(__FUNCSIG__)
#  define OPENSSL_FUNC __FUNCSIG__
# else
#  define OPENSSL_FUNC "(unknown function)"
# endif
```

**Comment by levitte** [comment] 2019-07-18 10:39
> on the other hand seeing function names in error reports can be very helpful so I do hope they will still be inserted automatically by some other means.

I have some unpublished work going on that does this.  Also, see [this discussion on openssl-project](https://mta.openssl.org/pipermail/openssl-project/2019-June/001426.html) where this was discussed, mostly in terms of a new couple of functions, `ERR_raise_error` and `ERR_raise_error_debug`.

Thanks for your suggestion re `OPENSSL_FUNC`, it expands on the variants that have already been mentioned in the mailing thread I linked to.

**Comment by levitte** [comment] 2019-07-18 10:47
Note that for providers, the support is already in place, see #9174

**Comment by paulidale** [comment] 2020-10-07 09:44
This has been resolved by the error replumbing.  Closing.

**Closed by paulidale** 2020-10-07 09:44 UTC
Labels: branch: master, triaged: feature
