### ISSUE TITLE
Build Warning under GCC48 and VS2010

### ISSUE THREAD

**Issue by qloong** [openssl/openssl#3135] opened 2017-04-06 08:07 UTC
When building OpenSSL-1.1.0e source under UEFI environment with different toolchains, some build warnings were found, including:

Under GCC48: 
-----------------
build warning:
  OpensslLib/openssl/ssl/statem/statem_clnt.c:2543:9: error: "len" may be used uninitialized in this function [-Werror=maybe-uninitialized]
       len += pskhdrlen;
           ^
This happens in the tls_construct_client_key_exchange() function. And this is not a bug which looks more like GCC's mis-report. but the existent "len = 0" assignment in tls_construct_client_key_exchange() function can be moved to the unconditional part of the code, or initialize this when declaring "len":
    int len = 0;

Under VS2010
-----------------
The following VS2010 build warning was found:
  openssl\crypto\asn1\tasn_dec.c(795) : warning C4306: 'type cast' :   conversion from 'int' to 'ASN1_VALUE *' of greater size

    case V_ASN1_NULL:
        if (len) {
            ASN1err(ASN1_F_ASN1_EX_C2I, ASN1_R_NULL_IS_WRONG_LENGTH);
            goto err;
        }
        *pval = (ASN1_VALUE *)1;
        break;
This seems like a valid warning, the C standard doesn't guarantee that (int) can be converted to a pointer type and vice versa. The code should be using intptr_t or uintptr_t, for example:
        *pval = (ASN1_VALUE *)(uintptr_t)1;

**Comment by dot-asm** [comment] 2017-04-06 10:44
> This seems like a valid warning,

But later versions of VS compiler don't complain. Keep in mind that warning subsystem can also have bugs. Relevant question also is if they should be treated any differently from any other compiler bug...

> the C standard doesn't guarantee that (int) can be converted to a pointer type and vice versa.

Does it actually say "*no* integer *can* be converted to a pointer type"? No, it only says that there is no guarantee that result of conversion will yield *usable* pointer. Note that in this case result is not usable pointer...

**Comment by dot-asm** [comment] 2017-04-07 09:06
I'm closing this without resolution with following rationale. Even though this project had history of working around compiler bugs, it's obvious that it wouldn't really be a sustainable practice if we aimed to work around every one we run into. Probably the only case when doing so would [still] be justified is when user has no alternative, but to use some specific compiler. And failure would have to be fatal. Neither is case here. BTW, I can't even reproduce problem with 4.8.5, so that *both* are clearly compiler bugs in warning systems, since both were apparently fixed. Well, one can argue "come on, it's so bloody trivial to fix". But then, where would one draw the line at all?

**Closed by dot-asm** 2017-04-07 09:06 UTC

**Comment by qloong** [comment] 2017-04-07 13:30
Understanding. Thanks.
And it's workable to apply the "warning-disable" option to suppress these warning messages.
