### ISSUE TITLE
EC_KEY_can_sign() must check eckey for determining can sign or not.

### ISSUE THREAD

**Issue by umedoblock** [openssl/openssl#21729] opened 2023-08-14 04:12 UTC
# must output can not sign

This bug_report_EC_KEY_can_sign.c output below two lines.

```
$ ./bug_report_EC_KEY_can_sign
eckey can sign
only_verify_eckey can sign
```

But **only_verify_eckey** must out put

```
can not sign
```

Therefore I give bug_report_EC_KEY_can_sign.patch.

### my environment
```
$ openssl version -v
OpenSSL 1.1.1s  1 Nov 2022
```

**Comment by umedoblock** [comment] 2023-08-14 04:15
Sorry, ...
I forget to attach a bug_report_EC_KEY_can_sign.zip.
[bug_report_EC_KEY_can_sign.zip](https://github.com/openssl/openssl/files/12331434/bug_report_EC_KEY_can_sign.zip)

**Comment by mattcaswell** [comment] 2023-08-14 09:56
The `EC_KEY_can_sign()` function is undocumented and is deprecated since 3.0. Since it is undocumented it is unclear exactly what it should do. However our 3.x migration guide does mention it:

https://www.openssl.org/docs/man3.1/man7/migration_guide.html

> Applications should use [EVP_PKEY_can_sign(3)](https://www.openssl.org/docs/man3.1/man3/EVP_PKEY_can_sign.html) instead.

So, app developers are encourage to use `EVP_PKEY_can_sign()` as a direct replacement. That function is documented as follows:

> EVP_PKEY_can_sign() checks if the functionality for the key type of pkey supports signing. No other check is done, such as whether pkey contains a private key.

i.e. the function tells you whether the *key type* (not this specific key) supports signing. It explicitly does *not* check for the presence of a private key.

So, IMO, `EC_KEY_can_sign()` is supposed to do the equivalent thing and is operating as intended, i.e. this is not a bug. It checks whether the curve supports signing, but does not tell you whether this specific key does.

**Comment by mattcaswell** [comment] 2024-01-31 11:08
Closing since this is marked as resolved.

**Closed by mattcaswell** 2024-01-31 11:08 UTC
Labels: resolved: not a bug, triaged: bug
