### ISSUE TITLE
CAPI_RSA_SIGN:cant create hash object

### ISSUE THREAD

**Issue by kxjhcs** [openssl/openssl#1497] opened 2016-08-26 08:37 UTC
i use libcurl with openssl, so i build openssl: 
 perl configure VC-WIN32 no-asm -DOPENSSL_SSL_CLIENT_ENGINE_AUTO=capi -DOPENSSL_CAPIENG_DIALOG

when curl https://**.com ,show the error：
error:89070063:lib(137):CAPI_RSA_SIGN:cant create hash object

**Comment by mattcaswell** [comment] 2016-08-26 12:28
Which version of OpenSSL are you using?

**Comment by kxjhcs** [comment] 2016-08-30 12:34
openssl-1.0.2h

My website is a two-way authentication. need client certificate, but i dot upload it

**Comment by levitte** [comment] 2017-01-20 14:02
The issue is that the CAPI API returned an error.  The error you're showing is also incomplete, OpenSSL's capi engine also adds the CAPI error code as extra error details.  It's possible, though, that curl doesn't show those extra details (which is unfortunate in this case).

There are a bit too many layers (curl, OpenSSL, the capi API implementation) involved here and too little information to figure this out.

Closing this.

**Closed by levitte** 2017-01-20 14:02 UTC
