### ISSUE TITLE
The time stamp in util/mkbuildinf.pl makes the project can't support reproucible builds

### ISSUE THREAD

**Issue by waylandzhong** [openssl/openssl#3589] opened 2017-05-31 14:59 UTC
I tried to compile OpenSSL 1.0.1t for several times, and I found that binariy file "libcrypto.so" is different everytime. And then I find out that there is a time stamp in util/mkbuildinf.pl:

$date = localtime();

"Reproducible builds counter malicious attacks that generate malicious executables, by making it easy to recreate the executable to determine if the result is correct."
The time stamp makes the compile results different---that can't support reproducible builds. 
And I found that the problem exists in every version later than 1.0.1t. Could we delete it or find another way to replace it( e.g. use a fixed time instead of it)?

**Comment by mattcaswell** [comment] 2017-05-31 15:03
I think we did make some changes for this in later versions, but I don't recall the details. Perhaps @kroeckx  knows. In any case 1.0.1 is out of support so is not receiving any fixes.

**Comment by levitte** [comment] 2017-05-31 15:11
> I think we did make some changes for this in later versions

Yeah, we created the script 3 years ago to replace the Makefile specific stuff, and ultimately made this script common for all platforms, not just the Unix family.  However, `crypto/buildinf.h` still gets generated every time the configuration is updated, just like before (it depends on `configdata.pm` in 1.1.0 and on, and on the top `Makefile` in pre-1.1.0 versions).

**Comment by levitte** [comment] 2017-05-31 15:14
(I re-opened since this is still an issue.  Closing this issue should be done with reasoning around currently supported OpenSSL versions, not just because the OP mentioned 1.0.1)

**Comment by mattcaswell** [comment] 2017-05-31 15:18
Ah, right I start to remember more. In master at least, although buildinf.h has the date in it, it isn't used by anything unless you also define OPENSSL_USE_BUILD_DATE. You can see this by running openssl version (see the "built on" line):
````
$ ../util/shlib_wrap.sh ./openssl version -a
OpenSSL 1.1.1-dev  xx XXX xxxx
built on: reproducible build, date unspecified
platform: linux-x86_64-clang
compiler: clang -DDSO_DLFCN -DHAVE_DLFCN_H -DOPENSSL_THREADS -DOPENSSL_NO_STATIC_ENGINE -DOPENSSL_PIC -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPADLOCK_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/usr/local/ssl\"" -DENGINESDIR="\"/usr/local/lib/engines-1.1\"" -fsanitize=undefined -fno-sanitize-recover=all -fno-omit-frame-pointer -g  -fno-sanitize=alignment
OPENSSLDIR: "/usr/local/ssl"
ENGINESDIR: "/usr/local/lib/engines-1.1"
````

**Comment by mattcaswell** [comment] 2017-05-31 15:21
And, I've confirmed that by default we do reproducible builds in 1.1.0 and 1.0.2. So I really think this can be closed. Ok @levitte?

**Comment by levitte** [comment] 2017-05-31 15:23
That's good enough for me.  Thanks for taking the time.

**Closed by levitte** 2017-05-31 15:23 UTC
