### ISSUE TITLE
Question about CMS_Sign():  when set flags =CMS_DETACHED|CMS_STREAM , why still get CMS result with origin data?

### ISSUE THREAD

**Issue by Lucy0418s** [openssl/openssl#26186] opened 2024-12-16 03:39 UTC
### Discussed in https://github.com/openssl/openssl/discussions/26116

<div type='discussions-op-text'>

<sup>Originally posted by **Lucy0418s** December  5, 2024</sup>
Hello, friends,
I have a question about CMS_ContentInfo *CMS_sign(X509 *signcert, EVP_PKEY *pkey, STACK_OF(X509) *certs, BIO *data, unsigned int flags) and int SMIME_write_CMS(BIO *bio, CMS_ContentInfo *cms, BIO *data, int flags);
I set flags in CMS_Sign()  is CMS_DETACHED|CMS_STREAM , why still get CMS result with origin data?

I want to get a CMS signed result that without origin plain data.
I also want to use CMS_STREAM mode to read data. 
My code like below:

CMS_ContentInfo* cms = nullptr;
cms = CMS_sign(signerCert, pvtKey, certChain, data, CMS_DETACHED|CMS_STREAM);
if (cms != nullptr)
{
      out_bio = BIO_new(BIO_s_mem());
      if (!SMIME_write_CMS(out_bio, cms, data,  CMS_DETACHED|CMS_STREAM)) { 
          goto err;
      }
  }

but cms result still exist origin plain data like below:
![image](https://github.com/user-attachments/assets/7a4753ca-c4a5-4970-ba80-2c6efa9d00cb)

</div>

**Comment by tom-cosgrove-arm** [comment] 2024-12-16 08:38
This really should be a discussion - and this issue looks like a duplicate of discussion #26116

**Closed** 2024-12-16 10:30 UTC
