### ISSUE TITLE
Cannot negotiate TLS_DHE_RSA_WITH_AES_128_CBC_SHA when the server is TLS 1.0

### ISSUE THREAD

**Issue by nmav** [openssl/openssl#236] opened 2015-03-07 12:02 UTC
While checking interoperation between openssl and gnutls, I noticed that openssl (in master but also 1.0.1k) would not negotiate TLS_DHE_RSA_WITH_AES_128_CBC_SHA if the server only supports TLS 1.0. If the server enables TLS 1.2, negotiation with openssl client is successful.

How to verify:
$ gnutls-serv --port 5555 --priority "NONE:+CIPHER-ALL:+SIGN-ALL:+COMP-NULL:+MAC-ALL:+VERS-TLS1.0:+DHE-RSA" --x509certfile cert-rsa.pem --x509keyfile key-rsa.pem --dhparams params.pem

$ openssl s_client -host via -port 5555 -CAfile ca.pem

Output:
SSL_connect:before/connect initialization
SSL_connect:SSLv2/v3 write client hello A
SSL3 alert write:fatal:illegal parameter
SSL_connect:error in SSLv3 read server hello B
SSL_connect:error in SSLv3 read server hello B
140528280028816:error:14092105:SSL routines:ssl3_get_server_hello:wrong cipher returned:s3_clnt.c:1011:

Note that "openssl s_client -host via -port 5555 -CAfile ca.pem -tls1" works.

I could not reproduce the issue with openssl as server because the command:
openssl s_server -key key-rsa.pem -cert cert-rsa.pem -port 5555 -cipher DHE-RSA-AES256-SHA256 -dhparam params.pem -tls1
did not create a working server.

**Comment by mattcaswell** [comment] 2017-05-02 09:49
I am unable to reproduce this with current versions, so I assume this has been fixed. Closing.

**Closed by mattcaswell** 2017-05-02 09:49 UTC
