### ISSUE TITLE
s_client doesn't report used hybrid PQC group used in the connection

### ISSUE THREAD

**Issue by tomato42** [openssl/openssl#25888] opened 2024-11-06 13:55 UTC
Using openssl-3.2.2 on RHEL-10 and current master (e899361b982651df) when connection is negotiated with a hybrid key exchange (`SecP256r1MLKEM768` or `X25519MLKEM768`) then the s_client doesn't report the used key exchange group.

When the connection uses X25519 I see:
```
---                                                                          
No client certificate CA names sent                                          
Peer signing digest: SHA256                                                  
Peer signature type: RSA-PSS                                                                                                                               
Server Temp Key: X25519, 253 bits                                                                                                                          
--- 
```

But when either of the hybrid groups is negotiated, this section of the output is missing the `Server Temp Key:`:
```
---                                                                                                                                                        
No client certificate CA names sent                                                                                                                        
Peer signing digest: SHA256                                                                                                                                
Peer signature type: RSA-PSS                                                                                                                               
---   
```

I'm using oqsprovider-0.7.0 and liboqs-0.11.0 for the test

**Comment by baentsch** [comment] 2024-11-13 06:37
This should be already resolved by https://github.com/openssl/openssl/pull/25808 -- but only for "master" branch. Please check that this is what you'd envision @tomato42 .

**Comment by t8m** [comment] 2024-11-13 11:06
**OTC: Should this be considered a bug and #25808 backported to older branches?**

**Comment by tomato42** [comment] 2024-11-13 11:36
@baentsch :
> This should be already resolved by #25808 -- but only for "master" branch. Please check that this is what you'd envision @tomato42 .

no, #25808 is commit 280c1d0, that's earlier (i.e. included) in https://github.com/openssl/openssl/commit/e899361b982651dfa2316e06e56637bc21624ce2...

Tried again, compiled openssl statically (`./configure no-shared && make -j 4`) with commit 21f6c3b4fb35af03e1fedb3:

```
# apps/openssl list -provider-path /usr/lib64/ossl-modules/ -provider oqsprovider -provider default -kem-algorithms
  { 1.2.840.113549.1.1.1, 2.5.8.1.1, RSA, rsaEncryption } @ default
  { 1.2.840.10045.2.1, EC, id-ecPublicKey } @ default
  { 1.3.101.110, X25519 } @ default
  { 1.3.101.111, X448 } @ default
  mlkem512 @ oqsprovider
  p256_mlkem512 @ oqsprovider
  x25519_mlkem512 @ oqsprovider
  mlkem768 @ oqsprovider
  p384_mlkem768 @ oqsprovider
  x448_mlkem768 @ oqsprovider
  X25519MLKEM768 @ oqsprovider
  SecP256r1MLKEM768 @ oqsprovider
  mlkem1024 @ oqsprovider
  p521_mlkem1024 @ oqsprovider
  p384_mlkem1024 @ oqsprovider
```

Running s_client:
```
# apps/openssl s_client -provider-path /usr/lib64/ossl-modules/ -provider oqsprovider -provider default -connect pq.cloudflareresearch.com:443 -groups SecP256r1MLKEM768:X25519MLKEM768:X25519
Connecting to 162.159.137.85
CONNECTED(00000003)
depth=2 C=US, O=Google Trust Services LLC, CN=GTS Root R4
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=1 C=US, O=Google Trust Services, CN=WE1
verify return:1
depth=0 CN=pq.cloudflareresearch.com
verify return:1
---
Certificate chain
 0 s:CN=pq.cloudflareresearch.com
   i:C=US, O=Google Trust Services, CN=WE1
   a:PKEY: id-ecPublicKey, 256 (bit); sigalg: ecdsa-with-SHA256
   v:NotBefore: Oct 16 04:08:43 2024 GMT; NotAfter: Jan 14 04:08:42 2025 GMT
 1 s:C=US, O=Google Trust Services, CN=WE1
   i:C=US, O=Google Trust Services LLC, CN=GTS Root R4
   a:PKEY: id-ecPublicKey, 256 (bit); sigalg: ecdsa-with-SHA384
   v:NotBefore: Dec 13 09:00:00 2023 GMT; NotAfter: Feb 20 14:00:00 2029 GMT
 2 s:C=US, O=Google Trust Services LLC, CN=GTS Root R4
   i:C=BE, O=GlobalSign nv-sa, OU=Root CA, CN=GlobalSign Root CA
   a:PKEY: id-ecPublicKey, 384 (bit); sigalg: RSA-SHA256
   v:NotBefore: Nov 15 03:43:21 2023 GMT; NotAfter: Jan 28 00:00:42 2028 GMT
---
Server certificate
-----BEGIN CERTIFICATE-----
MIID0DCCA3agAwIBAgIRALyQgzXylGbMDdoK/w2wi/IwCgYIKoZIzj0EAwIwOzEL
MAkGA1UEBhMCVVMxHjAcBgNVBAoTFUdvb2dsZSBUcnVzdCBTZXJ2aWNlczEMMAoG
A1UEAxMDV0UxMB4XDTI0MTAxNjA0MDg0M1oXDTI1MDExNDA0MDg0MlowJDEiMCAG
A1UEAxMZcHEuY2xvdWRmbGFyZXJlc2VhcmNoLmNvbTBZMBMGByqGSM49AgEGCCqG
SM49AwEHA0IABNIXk4mt93eELHLjsVRIUzGehuDlG3eJKOykBwqkMzrFd/VlY+1x
0KU0g3PK0kYGszz5lxvlZ1CyVrEmE4Wtd1WjggJwMIICbDAOBgNVHQ8BAf8EBAMC
B4AwEwYDVR0lBAwwCgYIKwYBBQUHAwEwDAYDVR0TAQH/BAIwADAdBgNVHQ4EFgQU
D+2Xe5aKn4qA1DRXGxXnrYtlzCIwHwYDVR0jBBgwFoAUkHeSNWfE/6jMqeZ72YB5
e8yT+TgwXgYIKwYBBQUHAQEEUjBQMCcGCCsGAQUFBzABhhtodHRwOi8vby5wa2ku
Z29vZy9zL3dlMS92SkEwJQYIKwYBBQUHMAKGGWh0dHA6Ly9pLnBraS5nb29nL3dl
MS5jcnQwQQYDVR0RBDowOIIZcHEuY2xvdWRmbGFyZXJlc2VhcmNoLmNvbYIbKi5w
cS5jbG91ZGZsYXJlcmVzZWFyY2guY29tMBMGA1UdIAQMMAowCAYGZ4EMAQIBMDYG
A1UdHwQvMC0wK6ApoCeGJWh0dHA6Ly9jLnBraS5nb29nL3dlMS9yZ2Vva1JBX24t
Zy5jcmwwggEFBgorBgEEAdZ5AgQCBIH2BIHzAPEAdgDPEVbu1S58r/OHW9lpLpvp
GnFnSrAX7KwB0lt3zsw7CAAAAZKTunkLAAAEAwBHMEUCIGPK9aL0ODKQw4BSoo2W
XdD1Zs04erkrIJmP+hXIRtShAiEA0ClEZQmp24MV2MEZzxry7SzXw2Zi4ftyyLEv
LLPhFMAAdwDM+w9qhXEJZf6Vm1PO6bJ8IumFXA2XjbapflTA/kwNsAAAAZKTunz3
AAAEAwBIMEYCIQDO/RBbTM9oVjoks0/cECxVHBMG4YmXUDUJ+7JgpGqNBgIhAN07
nZeVbOSW5X7apgmT2cxVLbypI1jPq0ZXZTgfve9xMAoGCCqGSM49BAMCA0gAMEUC
IG50HFU752k/sHk9Vtn2JVZbiutHvwADqPZO1jEI+yyiAiEAjfB+Ts4rJSGPJDBE
bw1As2g7dsdwcnVxl0pv5NCPXBc=
-----END CERTIFICATE-----
subject=CN=pq.cloudflareresearch.com
issuer=C=US, O=Google Trust Services, CN=WE1
---
No client certificate CA names sent
Peer signing digest: SHA256
Peer signature type: ECDSA
---
SSL handshake has read 4049 bytes and written 3249 bytes
Verification error: unable to get local issuer certificate
---
New, TLSv1.3, Cipher is TLS_AES_256_GCM_SHA384
Protocol: TLSv1.3
Server public key is 256 bit
This TLS version forbids renegotiation.
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 20 (unable to get local issuer certificate)
---
---
Post-Handshake New Session Ticket arrived:
SSL-Session:
    Protocol  : TLSv1.3
    Cipher    : TLS_AES_256_GCM_SHA384
    Session-ID: F458A5ECB205C561D65B62AA69E22CFE59555AFE88F44FA8F0CCC503EF1DEAED
    Session-ID-ctx: 
    Resumption PSK: 792501E4589F1F5F6286C73C19359081F8BD7F7829DD989486B7D0EC2986CBDA6A3F39B31B77516A26AA14B52514CB56
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 64800 (seconds)
    TLS session ticket:
    0000 - de a8 ec fc a0 b6 22 6b-78 33 ff d9 94 df c5 54   ......"kx3.....T
    0010 - 35 b8 91 4f 9f c6 6d 44-59 7a 1a d7 31 c4 3f fe   5..O..mDYz..1.?.
    0020 - bc 2e a7 91 0e da 9e 84-f3 ae 90 0b 79 07 2c ab   ............y.,.
    0030 - 8a 8f 59 92 2b b1 22 39-e4 70 80 a5 47 20 f7 3e   ..Y.+."9.p..G .>
    0040 - 6c 6e 7a 0e 04 87 fe 91-7f 9a 25 cf 97 e9 06 31   lnz.......%....1
    0050 - fa 99 2f 1d d7 82 a3 ec-63 57 9d 04 50 e7 a6 ab   ../.....cW..P...
    0060 - e9 18 32 11 8c a0 03 21-ac b5 d8 16 5f 78 4b 22   ..2....!...._xK"
    0070 - 01 71 26 cf 7b 03 ba 96-0c ac cf ed 2c 68 52 e5   .q&.{.......,hR.
    0080 - 74 04 91 eb 00 a8 a6 58-ae 48 26 a9 b8 fb 40 73   t......X.H&...@s
    0090 - 66 1c f5 b4 78 31 77 a3-90 6b 53 fc bf 12 3f bd   f...x1w..kS...?.
    00a0 - 79 7c 45 5b 0a 6c 4d 16-8f 0e eb 63 0f ac ab 5b   y|E[.lM....c...[
    00b0 - d2 c9 20 55 33 ac 0b e0-66 fe 0c c2 e8 b2 40 92   .. U3...f.....@.

    Start Time: 1731497592
    Timeout   : 7200 (sec)
    Verify return code: 20 (unable to get local issuer certificate)
    Extended master secret: no
    Max Early Data: 0
---
read R BLOCK
---
Post-Handshake New Session Ticket arrived:
SSL-Session:
    Protocol  : TLSv1.3
    Cipher    : TLS_AES_256_GCM_SHA384
    Session-ID: C206BC98912B7C6123C1B367BD3F7C4FD49374EF7E6D27E2BD268E2B105F2426
    Session-ID-ctx: 
    Resumption PSK: 21E182802E995328A789351CE3791222D3481C35E515AE982FECBE3648C58962C3B508E8629518A9E2D616631DC6225E
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 64800 (seconds)
    TLS session ticket:
    0000 - de a8 ec fc a0 b6 22 6b-78 33 ff d9 94 df c5 54   ......"kx3.....T
    0010 - e2 e8 e9 03 65 cd 09 d5-e4 7d 6b 6f 9a 13 95 06   ....e....}ko....
    0020 - 4a 07 54 8a 42 16 17 be-20 97 0e 2d 42 7a d1 26   J.T.B... ..-Bz.&
    0030 - 19 21 d9 2d 7e e4 74 cc-7f 12 6d ee 0d 8f 4b cf   .!.-~.t...m...K.
    0040 - a8 bd b0 fa ae bc 8e 71-d5 72 b7 08 a9 a9 51 ed   .......q.r....Q.
    0050 - ad 23 1a a2 1e 28 3a 8c-60 a6 5c b4 e7 f2 f2 91   .#...(:.`.\.....
    0060 - 54 92 95 f7 e0 7e e4 af-75 eb 57 15 19 d8 b8 a9   T....~..u.W.....
    0070 - ad 64 7d ba 35 da 27 9d-56 fc f5 c6 77 0a 17 b3   .d}.5.'.V...w...
    0080 - f1 09 ae d1 66 bd 80 72-2b 0f d4 3f e7 1c 27 ab   ....f..r+..?..'.
    0090 - 88 a5 b9 df 57 8f 01 73-d5 4f c4 9d 82 f8 33 bd   ....W..s.O....3.
    00a0 - 4d 11 03 5d 03 f2 5d 65-2d 6c 98 4b 6e a6 1f ac   M..]..]e-l.Kn...
    00b0 - c4 f8 46 cb 46 41 8e 32-06 53 93 cd 95 ec 5e 35   ..F.FA.2.S....^5

    Start Time: 1731497592
    Timeout   : 7200 (sec)
    Verify return code: 20 (unable to get local issuer certificate)
    Extended master secret: no
    Max Early Data: 0
---
read R BLOCK
closed
```

I don't see `Negotiated TLS1.3 group` anywhere there...

this is with 0.7.1-dev version of oqsprovider:
```
[root@vm-10-0-187-119 openssl]# apps/openssl list -provider-path /usr/lib64/ossl-modules/ -provider oqsprovider -provider default -providers
Providers:
  default
    name: OpenSSL Default Provider
    version: 3.5.0
    status: active
  oqsprovider
    name: OpenSSL OQS Provider
    version: 0.7.1-dev
    status: active
```

**Comment by baentsch** [comment] 2024-11-13 15:04
Well, it's only output in "print_ssl_summary" -- and that is only triggered if you pass the `-brief` parameter.

**Comment by t8m** [comment] 2024-11-13 16:06
> Well, it's only output in "print_ssl_summary" -- and that is only triggered if you pass the `-brief` parameter.

Hm... that doesn't sound right. The output of s_client without `-brief` should also include all the information that is output with `-brief`. So it seems we need an additional fix.

**Comment by baentsch** [comment] 2024-11-13 16:34
> The output of s_client without -brief should also include all the information that is output with -brief

That seems it could easily be facilitated by calling `print_ssl_summary` within `print_stuff`... Or is there some "exclusivity" between the two functions, i.e., would one have to scour `print_stuff` for contents also output by `print_ssl_summary` to avoid duplicate output?

**Comment by t8m** [comment] 2024-11-13 16:37
IMO we should avoid the duplication.

**Comment by baentsch** [comment] 2024-11-13 17:03
> IMO we should avoid the duplication.

Agree -- will require some code archeology: This happened between 8 and 12 years ago... Good I like digging :)

**Comment by baentsch** [comment] 2024-11-14 13:52
OK, digging is "interesting": There's even more SSL session output functions at play here, one set in "apps", one in "apps/lib" and one in "ssl", all outputting similar "stuff" but I fail to find a common logic how (whether) they build on each other. The only way to avoid duplication of information (protocol, Cipher, peer cert, Hash, sig type) would be to pass options around all those functions -- or to completely restructure the output. The latter doesn't sound like users would appreciate that and the former like an unwarranted change of APIs for just the avoidance of information duplication -- that may actually be achieved already by way of setting the option `-quiet` together with `-brief`.

All told, I'd rather not touch the output logic but rather duplicate outputting the one new information (negotiated group) to where the other output duplicates (compared to `print_ssl_summary`) occur, namely to `SSL_SESSION_print` (in ssl/ssl_txt.c): Would that be OK @t8m?

**Comment by tomato42** [comment] 2024-11-14 13:55
Isn't SSL_SESSION_print not used when the session ticket isn't sent by server? (I may be mixing up the functions, I haven't double checked)

**Comment by baentsch** [comment] 2024-11-14 14:10
> Isn't SSL_SESSION_print not used when the session ticket isn't sent by server? (I may be mixing up the functions, I haven't double checked)

Might be -- I may very well not have dived deep enough yet. Do you have other proposals where to put the output?

**Comment by tomato42** [comment] 2024-11-14 15:08
what I'd like the most is for the `Server Temp Key:` to remain, just report MLKEM based hybrids when they're negotiated

**Comment by mattcaswell** [comment] 2024-11-14 15:21
> what I'd like the most is for the Server Temp Key: to remain, just report MLKEM based hybrids when they're negotiated

"Server Temp Key" implies that there is a server key to print information about. Under the covers it relies on the `SSL_get_peer_tmp_key` function. But in the case of a KEM there *isn't* a server key at all, i.e. there is no associated `EVP_PKEY` for us to query.

**Comment by mattcaswell** [comment] 2024-11-14 15:27
Plausibly we could print out something like "Server Temp Key: None (ML-KEM-768)", but that might be a bit confusing (if technically accurate).
Or perhaps we print out a different label entirely if we detect there is no temp key, e.g. "KEM negotiated: ML-KEM-768"

**Comment by baentsch** [comment] 2024-11-15 07:29
> what I'd like the most is for the Server Temp Key: to remain, just report MLKEM based hybrids when they're negotiated

OK, that seems easy enough to change (output the negotiated TLS 1.3 group in the `ssl_print_tmp_key` function instead). Would that be OK for you all?

**Comment by baentsch** [comment] 2024-11-18 16:33
Backporting decision needed for #25959

**Comment by t8m** [comment] 2024-11-19 09:25
**OTC: This is not a bug and thus not eligible for backport.**

**Comment by t8m** [comment] 2024-11-20 16:13
#25959 was merged. Closing.

**Closed by t8m** 2024-11-20 16:13 UTC
Labels: branch: master, triaged: feature
