### ISSUE TITLE
AppVeyor failure

### ISSUE THREAD

**Issue by paulidale** [openssl/openssl#15690] opened 2021-06-10 06:25 UTC
[Logfile](https://ci.appveyor.com/project/openssl/openssl/builds/39540371/job/62x53h4iksm9up8i).

```
# The results of this test will end up in test-runs\prep_fipsmodule
..\test\recipes\00-prep_fipsmodule_cnf_data: No such file or directory at C:\projects\openssl\util\perl/OpenSSL/Test.pm line 1154.
BEGIN failed--compilation aborted at ..\test\recipes\00-prep_fipsmodule_cnf.t line 17.00-prep_fipsmodule_cnf.t .. 
Dubious, test returned 2 (wstat 512, 0x200)
No subtests run 
Test Summary Report
-------------------
00-prep_fipsmodule_cnf.t (Wstat: 512 Tests: 0 Failed: 0)
  Non-zero exit status: 2
  Parse errors: No plan found in TAP output
Files=1, Tests=0,  0 wallclock secs ( 0.02 usr +  0.00 sys =  0.02 CPU)
Result: FAIL
Died at ..\test\run_tests.pl line 312.
NMAKE : fatal error U1077: 'cmd' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\nmake.exe"' : return code '0x2'
Stop.
```

The places mentioned are:
- line 1154 here:
https://github.com/openssl/openssl/blob/b6298a7f8de45b287bfbad5de282fbceb68abb02/util/perl/OpenSSL/Test.pm#L1143-L1168

- and line 17 here:
https://github.com/openssl/openssl/blob/b6298a7f8de45b287bfbad5de282fbceb68abb02/test/recipes/00-prep_fipsmodule_cnf.t#L12-L21

**Comment by levitte** [comment] 2021-06-10 06:30
Duplicate of #15679

**Closed** 2021-06-10 06:41 UTC
Labels: branch: master, severity: urgent, triaged: bug
