### ISSUE TITLE
X.509 certificate extended key usage (EKU) is checked very loosely

### ISSUE THREAD

**Issue by DDvO** [openssl/openssl#13965] opened 2021-01-26 08:25 UTC
When opening for instance a TLS connection, one would expect that 
the EKU extension (if present) of the server cert allows for `X509_PURPOSE_SSL_SERVER` and 
the EKU extension (if present) of the client cert (if present) allows for `X509_PURPOSE_SSL_CLIENT`, 
but barely any such checks are done by OpenSSL.

Its this just for compatibility with broken certs or 
because people don't care much about (extended) key usage restrictions?

There are very few uses of `X509_check_purpose()`, 
and this function even has been undocumented for long time until October 2019.

**Update:** I meanwhile found that `ssl_verify_cert_chain()` in `ssl/ssl_cert.c`, 
which is called for both the client and server side during TLS connection, 
does set up a default purpose ` X509_PURPOSE_SSL_{SERVER,CLIENT}` to be checked:
```
    /*
     * We need to inherit the verify parameters. These can be determined by
     * the context: if its a server it will verify SSL client certificates or
     * vice versa.
     */

    X509_STORE_CTX_set_default(ctx, s->server ? "ssl_client" : "ssl_server");
    /*
     * Anything non-default in "s->param" should overwrite anything in the ctx.
     */
    X509_VERIFY_PARAM_set1(param, s->param);
 ```
 
~I wonder why apparently there is not at least some strictness option (`-x509_strict` and `-strict` come to mind) that would lead to 
`X509_check_purpose(cert, X509_PURPOSE_SSL_SERVER, 0)` or
`X509_check_purpose(cert, X509_PURPOSE_SSL_CLIENT, 0)` 
being called during TLS handshake.~

BTW, the documentation of `-strict` (`SSL_CERT_FLAG_TLS_STRICT`) is ridiculous:
```
enables strict mode protocol handling. 
Equivalent to setting B<SSL_CERT_FLAG_TLS_STRICT>.
```

**Comment by richsalz** [comment] 2021-01-26 13:26
From a real-world pragmatic viewpoint, it's not clear, even with strict, what the proper handling of EKU is. The main issue, as I understand it, is this: can an intermediary CA sign end-entity certs with EKU "a" if it does not have that EKU itself?

I believe the CA/Browser forum has an answer, but there are other PKI's and certs and trust stores out there that have different answers.

I wouldn't necessarily ask him, but Ryan Sleevi of Google probably knows the situation completely.

**Comment by DDvO** [comment] 2021-01-26 13:47
> From a real-world pragmatic viewpoint, it's not clear, even with strict, what the proper handling of EKU is. The main issue, as I understand it, is this: can an intermediary CA sign end-entity certs with EKU "a" if it does not have that EKU itself?

As long as the CA cert itself does not include an EKU extension (would would not make much sense to me at least if we assume only those listed in RFC 5280),
I would answer this with clear a "yes" because a CA (of course depending on its policy) should in general be able/allowed to issue certs for any purpose, while the CA itself only needs the authority to sign certs, which is stated by the "cA" flag in its cert in conjunction with the keyUsage extension including keyCertSign.
I am not aware of any other RFC 5280 requirements regarding (extended) key usage of CA certs.

**Comment by DDvO** [comment] 2021-01-26 14:11
RFC 5280 https://tools.ietf.org/html/rfc5280#section-4.2.1.12 is crystal clear.

> 4.2.1.12.  Extended Key Usage

>   This extension indicates one or more purposes for which the certified
   public key may be used, in addition to or in place of the basic
   purposes indicated in the key usage extension.  **In general, this
   extension will appear only in end entity certificates.**
   
So we can ignore EKUs of CA certs as side topic.
   
> [...]

>   **If the extension is present, then the certificate MUST only be used
   for one of the purposes indicated**. 
   
   
So why is OpenSSL so lax on checking this?
If there is good reason, it should be prominently documented.

**Comment by richsalz** [comment] 2021-01-26 14:19
The real world isn't just 5280 which is why I did not quote from that RFC alone.

**Comment by DDvO** [comment] 2021-01-26 14:33
True, but RFC 5280 is the main source of requirements on X.509 certs typically used.
And `-x509_strict` meanwhile does lead to various checks required by it taking effect.
Yet I cannot find any documented and easily usable option for enforcement of EKUs
in the most typical application contexts such as TLS (and only a little for CMS, CMP, and TS).

**Comment by richsalz** [comment] 2021-01-26 14:44
David, what do you want me to say? I told you that 5280 is not the only source of information here, and in particular the real world is different and sometimes conflicted.

OpenSSL is used in a variety of contexts, including the WebPKI (which is mostly driven by the CA/Browser documents, and has been for years), as well as enterprise-private/embedded PKI's. Taking just the "main source of requirements" as the only thing to use, will break stuff.

We've already seen that almost every recent change to improve or make certificate-checking more strict (or even just key usages) breaks things. Some of that comes from only adherence to 5280, sometimes it comes from mis-reading RFC's (OCSP checking), and sometimes it comes from not appreciating the larger context (private-only keys).

**Comment by DDvO** [comment] 2021-01-26 15:03
So your answer to my question(s)

> So why is OpenSSL so lax on checking this?
> Its this just for compatibility with broken certs or
because people don't care much about (extended) key usage restrictions?

is:

-> It's because OpenSSL needs to cover also non-RFC 5280 scenarios.

Certainly a good reason.

Note that I do not ask for _compulsory_ adherence to 5820.

But still, many (if not most) applications do care about RFC 5280 requirements.
As mentioned, easy-to-use optional EKU etc. adherence appears missing in particular for TLS,
as well as proper documentation clarifying the situation.

**Comment by DDvO** [comment] 2021-01-26 15:07
Here is a simple example. 

After digging for a while(!) in the documentation, one may find that the `s_client` app has options that are promising in this regard: `-purpose` and `-strict`.

Yet even using them:
```
openssl s_client -connect www.google.com:443 -purpose smimeencrypt -strict
```
one does get connected with just a little warning saying
```
Verify return code: 26 (unsupported certificate purpose)
```

**Comment by richsalz** [comment] 2021-01-26 15:12
> So you answer ... is

No, that is not the only thing I said; perhaps re-read what I wrote above at https://github.com/openssl/openssl/issues/13965#issuecomment-767539502

The TLS RFC's do not talk about certificate requirements. You need to read and understand the CA/Browser forum documents to get *the public WebPKI* requirements.

The `strict` flag is wrong in what it does.  The right thing to do is enforce CABForum requirements.

**Comment by DDvO** [comment] 2021-01-26 15:28
> > So you answer ... is
> 
> No, that is not the only thing I said; perhaps re-read what I wrote above at [#13965 (comment)](https://github.com/openssl/openssl/issues/13965#issuecomment-767539502)

I already responded to the more concrete portion of that, 
while not asking Ryan Sleevi nor CABForum and friends :wink:

> The TLS RFC's do not talk about certificate requirements. You need to read and understand the CA/Browser forum documents to get _the public WebPKI_ requirements.

Right, RFC 8446 etc. do not, but if one takes RFC 5280 serious, it applies to _any_ uses of such certs.

> The `strict` flag is wrong in what it does.

This is what I suspected, too, but note how useless its "documentation" is.

But certainly an explicitly requested `-purpose` that is not fulfilled by the server cert should lead to connection abort, at least when combining it with `-x509_strict`.

**Comment by richsalz** [comment] 2021-01-26 16:09
> but if one takes RFC 5280 serious, it applies to any uses of such certs.

Not quite.  You have to read all the errata and all the RFC's that update it.

**Comment by t8m** [comment] 2021-01-26 16:32
> Yet even using them:
> 
> ```
> openssl s_client -connect www.google.com:443 -purpose smimeencrypt -strict
> ```
> 
> one does get connected with just a little warning saying
> 
> ```
> Verify return code: 26 (unsupported certificate purpose)
> ```
> 
> I consider this a bug, not a feature.

This is NOT a bug. You have to use -verify_return_error for any certificate verification error to abort the connection.

**Comment by t8m** [comment] 2021-01-26 16:34
And the -strict option is irrelevant. The relevant thing here is the -purpose. Which we do not set automatically and I am not sure we should do that by default as that has a potential of huge breakages.

**Comment by DDvO** [comment] 2021-01-26 17:17
> This is NOT a bug. You have to use -verify_return_error for any certificate verification error to abort the connection.

Oh, I missed that option, thanks for pointing this out!
Indeed, on using it as follows:
```
openssl s_client -connect www.google.com:443 -verifyCAfile GlobalSignRootCA-r2.crt \
-verify_return_error -purpose sslclient || echo failed
```
I get
```
[...]
Verify return code: 26 (unsupported certificate purpose)
---
failed
```

**Comment by DDvO** [comment] 2021-01-26 17:30
> And the -strict option is irrelevant.

This option needs to be properly documented.

> The relevant thing here is the `-purpose`. Which we do not set automatically and I am not sure we should do that by default as that has a potential of huge breakages.

Well, since without the `-verify_return_error` it will result in just a warning,
I do not see a problem in making `-purpose sslserver` the default for `s_client` 
and analogously making `-purpose sslclient` the default for `s_server`.

Moreover, I request making the documentation of inhowfar EKUs ares (not) checked by default 
and how to change this more clear and prominent. In particular, 
the API doc should point out that for enabling EKU checks for TLS, one should use something like
`X509_check_purpose(cert, X509_PURPOSE_SSL_SERVER, 0)` or
`X509_check_purpose(cert, X509_PURPOSE_SSL_CLIENT, 0)`, respectively.

**Comment by DDvO** [comment] 2021-01-26 17:30
So to conclude for now, my question(s) and my 'bug' report have been answered sufficiently,
but for the things just mentioned I'm leaving this open as a reminder and feature request.

**Comment by richsalz** [comment] 2021-01-26 17:45
> I do not see a problem in making -purpose sslserver the default for s_client

And how do you turn it off? Yet another flag?

**Comment by t8m** [comment] 2021-01-26 18:28
I have no problem with documentation enhancements that you mention, but changing the default to set the -purpose would be really bad idea IMO.

**Comment by DDvO** [comment] 2021-01-26 20:14
> > I do not see a problem in making -purpose sslserver the default for s_client

> And how do you turn it off? Yet another flag?

Since any default `-purpose` value would at most cause a line of warning (among lots of other output) I'd see no need for turning it off. And of course it could be overridden by any other desired value.

> I have no problem with documentation enhancements that you mention, 
but changing the default to set the -purpose would be really bad idea IMO.

Even if you don't agree to my point that it would be natural and not harmful to default to `serverAuth`/`clientAuth` (also for the API level) since non-strictness is the default anyway,
having the situation and the options clearly documented will already be a helpful improvement.

**Comment by DDvO** [comment] 2021-01-28 08:33
> You need to read and understand the CA/Browser forum documents to get _the public WebPKI_ requirements.

@richsalz, which documents of the CA/Browser forum do you mean here?
If you refer to the "Baseline Requirements Documents (SSL/TLS Server Certificates)"
https://cabforum.org/baseline-requirements-documents/
then they do not really apply to _the (EKU etc.) checks required during cert verification_
but to _which contents publicly trusted certificates should have_.

As already their title says:
"Baseline Requirements for the **Issuance and Management** of Publicly-Trusted Certificates"
so this does not govern the use of such certs, which is the turf of RFC 5280 and friends.

**Comment by kaduk** [comment] 2021-02-09 21:16
Sorry for the slow response.  It would absolutely be harmful to default to `serverAuth`/`clientAuth`, because TLS is used in so many more places than just the Web!

This is true even if we constrain ourselves to RFC 5280:

```
   The following key usage purposes are defined:

   anyExtendedKeyUsage OBJECT IDENTIFIER ::= { id-ce-extKeyUsage 0 }

   id-kp OBJECT IDENTIFIER ::= { id-pkix 3 }

   id-kp-serverAuth             OBJECT IDENTIFIER ::= { id-kp 1 }
   -- TLS WWW server authentication
   -- Key usage bits that may be consistent: digitalSignature,
   -- keyEncipherment or keyAgreement
```

The id-kp-serverAuth extended key usage, which corresponds to our `X509_PURPOSE_SSL_SERVER`, is for **Web** TLS server authentication.

The fact that OpenSSL includes built-in logic for checking id-kp-serverAuth/id-kp-clientAuth but makes the user jump through several hoops to use a different extendedKeyUsage makes it harder for me as IETF Security Area Director to help direct (non-Web) TLS-using protocols towards allocating a dedicated extendedKeyUsage for their certificates, since it's so much easier to just reuse the builtin ones.  This, in turn, ends up negating a lot of the value that extendedKeyUsage itself was supposed to provide!  To make the Web extended key usage values the default in OpenSSL would just make it even harder for non-Web protocols to operate properly.  OpenSSL does not and cannot know a priori what context a TLS connection is being established in, and guessing will be harmful.  We make it fairly easy for applications to request verification of the Web key usages, but IMO that is as far as we should go towards default policy.  I would even say that we should make it easier to request enforcement of an extendedKeyUsage value just by OID, without needing to (e.g.) specify an `app_verify_callback" or the more-correct-but-more-complicated `X509_PURPOSE_add()` approach, as described at https://mailarchive.ietf.org/arch/msg/dtn/G2qi9Qwz09kkuzRbdEWrDqoHLwc/

**Comment by DDvO** [comment] 2021-02-10 16:46
> Sorry for the slow response.

Thanks anyway for your very interesting reply!

> This is true even if we constrain ourselves to RFC 5280:
> ```
>    id-kp-serverAuth             OBJECT IDENTIFIER ::= { id-kp 1 }
>    -- TLS WWW server authentication

> The id-kp-serverAuth extended key usage, which corresponds to our `X509_PURPOSE_SSL_SERVER`, is for **Web** TLS server authentication.

Oh my goodnees! :astonished:

The restriction to WWW (i.e., essentially only HTTP over TLS) is so **easy to overlook or ignore**,
in particular since the OIDs `id-kp-serverAuth` and `id-kp-clientAuth` do not include it in their names,
and neither do the OpenSSL identifiers like `X509_PURPOSE_SSL_SERVER`, `X509_TRUST_SSL_SERVER` and `XKU_SSL_SERVER`- this is **very misleading** :frowning_face: 
I wonder why they were not called more adequately, e.g., `X509_PURPOSE_HTTPS_SERVER`.

I suppose the vast majority of TLS users/developers are not aware of this restriction.

>  to help direct (non-Web) TLS-using protocols towards allocating a dedicated extendedKeyUsage for their certificates

I find the restriction of `id-kp-{client,server}Auth` to WWW use by RFC 5280 very unfortunate.

> OpenSSL does not and cannot know a priori what context a TLS connection is being established in,

In the light of the above clarification, 
of course it is understood that no TLS library can require `id-kp-{client,server}Auth` by default.

**Comment by DDvO** [comment] 2021-02-10 17:07
Even the NIST Guidelines for the Selection, Configuration, and Use of Transport Layer Security (TLS) Implementations: https://csrc.nist.gov/publications/detail/sp/800-52/rev-2/final
do not mention the restriction of `id-kp-{client,server}Auth` to WWW (HTTPS) - 
I wonder if this was by mistake or if they implicitly but purposefully broadened the interpretation to general TLS use.

**Comment by richsalz** [comment] 2021-02-10 17:18
I know David he is a really bright guy (and 5280 co-author) so I am positive he did not want to limit things to just the Web.

**Comment by DDvO** [comment] 2021-02-10 17:23
Well, but according to what is stated in RFC 5280 and what Benjamin wrote above they are restricted to web use.
I find this very hard to take, but what else should one conclude?

**Comment by DDvO** [comment] 2021-02-10 17:25
Apparently most users do not really care and take those EKUs for any TLS client/server use.

**Comment by richsalz** [comment] 2021-02-10 17:26
> Apparently most users do not really care and take those EKUs for any TLS client/server use.

Welcome to the real world. :)

Full and strict RFC compliance rarely exists, and limiting what OpenSSL does to do that would be a really bad idea.

**Comment by DDvO** [comment] 2021-02-10 17:38
So what OpenSSL simply does - for good reasons - is to support those EKUs without assuming any meaning for them.
This of course shifts the responsibility how to use them and when to check them to the users - which makes sense.

**Comment by DDvO** [comment] 2021-02-11 14:28
@kaduk,

> We make it fairly easy for applications to request verification of the Web key usages, but IMO that is as far as we should go towards default policy.

I meanwhile agree to this, in particular since there is no universal clarity/agreement on whether `id-kp-{client,server}Auth` are for Web use only or for general TLS use. 

> OpenSSL does not and cannot know a priori what context a TLS connection is being established in, and guessing will be harmful.

Hmm, well, but then apparently we do have a bug in the libssl checks, but just the other way round than I had expected!
In the email thread that you mention above you quote the following call in `ssl/ssl_cert.c`:
```
X509_STORE_CTX_set_default(ctx, s->server ? "ssl_client" : "ssl_server");
```
This does require checking for `X509_PURPOSE_SSL_{SERVER,CLIENT}`,
although you correctly wrote above that OpenSSL cannot know if this is part of a WWW use.

I think this usually does not surface just because usually the certs do allow `id-kp-{client,server}Auth`
or apps like `s_client` apparently ignore/overrule verification errors unless `-verify_return_error` is given.

**Comment by DDvO** [comment] 2021-02-11 14:57
> The relevant thing here is the -purpose. Which we do not set automatically and I am not sure we should do that by default as that has a potential of huge breakages.

@t8m, as I meanwhile found, the SSL server/client purpose to be checked does get set automatically, at least for `s_client`.
Conflicting cert EKU contents apparently just get ignored by default.

**Comment by DDvO** [comment] 2021-02-12 07:09
I just found that RFC 5280 has the - so far unhandled - following errata entry: https://www.rfc-editor.org/errata/eid5802

 Errata ID: 5802
Status: Reported
Type: Technical
Publication Format(s) : TEXT
Reported By: Nikos Mavrogiannopoulos
Date Reported: 2019-08-06

Section 4.2.1.12 says:

   id-kp-serverAuth             OBJECT IDENTIFIER ::= { id-kp 1 }
   -- TLS WWW server authentication
   -- Key usage bits that may be consistent: digitalSignature,
   -- keyEncipherment or keyAgreement

   id-kp-clientAuth             OBJECT IDENTIFIER ::= { id-kp 2 }
   -- TLS WWW client authentication
   -- Key usage bits that may be consistent: digitalSignature
   -- and/or keyAgreement

It should say:

   id-kp-serverAuth             OBJECT IDENTIFIER ::= { id-kp 1 }
   -- TLS server authentication
   -- Key usage bits that may be consistent: digitalSignature,
   -- keyEncipherment or keyAgreement

   id-kp-clientAuth             OBJECT IDENTIFIER ::= { id-kp 2 }
   -- TLS client authentication
   -- Key usage bits that may be consistent: digitalSignature
   -- and/or keyAgreement

Notes:

The proposed change removes the WWW part of the description. In practice these object identifiers are used for server and client applications, but not necessarily web applications. In particular:
- openssl verification considers them unconditionally even if the server is not a web server or the client a web client
- There is no object identifier that can be used for protocols like SMTP, IMAP, POP3, LDAP, radius, ...; in practice all these protocols are deployed with the identifiers for WWW
- Standards like common criteria assume that these object identifiers are for generic server and clients [0].

[0]. https://www.niap-ccevs.org/MMO/PP/-442-/#FCS_TLSC_EXT.1.1

**Comment by DDvO** [comment] 2021-02-12 07:26
@kaduk, I wonder why https://www.rfc-editor.org/errata/eid5802 is still not handled/accepted?
This would be a great rectification and also take much pressure out of what you mentioned above:

> for me as IETF Security Area Director to help direct (non-Web) TLS-using protocols towards allocating a dedicated extendedKeyUsage for their certificates

**Comment by DDvO** [comment] 2021-02-12 07:28
I've meanwhile removed the `bug report` label from this issue because I now believe the bug is in RFC 5280 :wink:

**Comment by DDvO** [comment] 2021-02-12 08:11
The `feature request` label here from my perspective meanwhile means essentially that the OpenSSL documentation should be extended to clarify the intended/implemented behavior including the - pragmatically very reaonsonable - deviation from the (silly/short-sighted/anachronistic) restriction of `id-kp-{client,server}Auth` to WWW use.

**Comment by richsalz** [comment] 2021-02-12 15:15
The errata set there because the IETF was loathe to open up 5280 for anything for a very long time.  Until something is done, an errata is just one person's opinion.

Note that there is the LAMPS working group (https://datatracker.ietf.org/wg/lamps/documents/) is undergoing a re-charter, and one of the items being considered is updating 5280 (https://mailarchive.ietf.org/arch/msg/spasm/wf148GFEMZlM-1M2AYaM8AFnEig/ starts the thread; there's several messages about 5280 in particular).

If 5280 gets revised it will be, my estimate, at least two years.  Perhaps it would be worthwhile to close this and open a generic issue "track 5280bis"  Shrug.

**Comment by kaduk** [comment] 2021-02-14 23:31
> @kaduk, I wonder why https://www.rfc-editor.org/errata/eid5802 is still not handled/accepted?

It's basically what Rich described -- it's far from clear that there's consensus on what was originally intended, and thus what the proper status to assign to the errata report would be.

**Comment by DDvO** [comment] 2021-02-16 06:32
So the whole situation whether `id-kp-{client,server}Auth` is restricted to WWW use only
has been unclear since many years and this will not change before RFC 5280 is updated.

**Comment by kroeckx** [comment] 2021-02-17 07:48
I think setting a default in ssl_cert.c is wrong. I think we actually want to have an extended key usage for each protocol for security reasons. As in, a different extended key usage for HTTP and SMTP, and the certificate should only have 1 of them.

And since we're talking about it here anyway, I think for SMTP there should be no distinction between client and server, but for HTTP there should. Most certificates you get now allow both client and server (WWW/HTTP) authentication, while it really should only allow server.

**Comment by t8m** [comment] 2021-02-17 09:41
> I think setting a default in ssl_cert.c is wrong. I think we actually want to have an extended key usage for each protocol for security reasons. As in, a different extended key usage for HTTP and SMTP, and the certificate should only have 1 of them.

I think that ship has sailed long time ago and to try to revert it does not make any sense.

And those security reasons are actually quite weak IMO.

**Comment by DDvO** [comment] 2021-02-17 16:49
If differentiating various flavors of TLS client/servers certs was important
there should have been specific EKU OIDs for those since long.
Yet this has not happened, at least not in any public, standardized way.

**Comment by DDvO** [comment] 2021-02-17 20:41
> The fact that OpenSSL includes built-in logic for checking id-kp-serverAuth/id-kp-clientAuth but makes the user jump through several hoops to use a different extendedKeyUsage makes it harder for me as IETF Security Area Director to help direct (non-Web) TLS-using protocols towards allocating a dedicated extendedKeyUsage for their certificates, since it's so much easier to just reuse the builtin ones.

@kaduk, this problem could be gone soon - see #14218.

**Comment by kaduk** [comment] 2021-02-26 19:57
> If differentiating various flavors of TLS client/servers certs was deemed important
there should have been specific EKU OIDs for those since long.

Well, anybody can mint an EKU value -- it's just an OID.  What's perhaps relevant is getting a CA you want to use to start issuing certificate using that EKU OID, and that's up to their own policy and purpose as a CA.  For the Web PKI, there is no reason to use other EKU OIDs, since the existing WWW/Web OIDs are exactly what is correct.  This gets into the point that Rich mentioned (maybe on #14199 vs here) about there being many PKIs and Ryan Sleevi's remarks thereto.  At present, people are (ab)using the Web PKI for SMTP usage and in that sense are stuck inheriting the policy (including on EKU OID issuance) of the Web PKI CAs.  Should there be a separate PKI for SMTP usage? Arguably -- there's a lot different about the ways they use TLS, and Viktor can (and has) share details of the differences.  Those even extend to what name you use to validate the certificate against, namely the email address domain name vs. the DNS name of the actual SMTP server.

> Yet this has not happened, at least not in any public, standardized way.

It depends on what protocols you are considering.  https://www.iana.org/assignments/smi-numbers/smi-numbers.xhtml#smi-numbers-1.3.6.1.5.5.7.3 lists a number of public, standard, EKU assignments in an IANA-controlled arc, but there is no requirement that EKU values are only obtained in this OID arc.

**Comment by DDvO** [comment] 2021-02-26 20:24
Thanks @kaduk for your interesting remarks.
I was aware of the list in https://www.iana.org/assignments/smi-numbers/smi-numbers.xhtml#smi-numbers-1.3.6.1.5.5.7.3 -
so far unfortunately it does not include a systematic treatment of various flavors of TLS uses.

BTW, what do you think about #14218?

**Comment by kaduk** [comment] 2021-02-26 20:55
> BTW, what do you think about #14218?

I'm happy to see work in this space, and thank you for putting it together!
I haven't had an opportunity yet to actually review it carefully, though.

**Comment by t8m** [comment] 2021-07-22 14:53
Closing. Please open a new issue if there is any clear feature request here but I do not see any actionable items here.

**Closed by t8m** 2021-07-22 14:53 UTC
Labels: resolved: answered

**Comment by DDvO** [comment] 2021-07-22 19:02
> Closing. Please open a new issue if there is any clear feature request here but I do not see any actionable items here.

The main outcome of this issue was the documentation improvements I did in #14199.
The only actionable item I found open is minor, now filed separately in #16140.
So I'm fine with this issue being closed.
