### ISSUE TITLE
OpenSSL 1.1.0b doesn't send RFC mandated parameters for SRP key exchange

### ISSUE THREAD

**Issue by tomato42** [openssl/openssl#1907] opened 2016-11-11 17:52 UTC
I've received a bug report, that tlslite-ng doesn't interoperate with SRP with OpenSSL 1.1.0b: https://github.com/tomato42/tlslite-ng/issues/145

Upon examination of the Server Key Exchange provided by @bwintcig, it looks like OpenSSL doesn't provide a correct generator (the g value) for SRP key exchange, while the prime matches the 4096 bit prime from [RFC 5054](https://tools.ietf.org/html/rfc5054), the generator defined for it is 5, OpenSSL sends 19.

**Comment by mattcaswell** [comment] 2018-04-18 09:26
I could not reproduce this issue (either in master or in 1.1.0b). On looking at the trace in the linked issue it seems to me that OpenSSL is actually sending the 8192 bit prime from RFC5054. The generator defined for that group is 19. So this behaviour looks correct to me.

Closing.

**Closed by mattcaswell** 2018-04-18 09:26 UTC
