### ISSUE TITLE
foolscap problem with openssl 1.1.1-dev

### ISSUE THREAD

**Issue by kroeckx** [openssl/openssl#6228] opened 2018-05-11 14:36 UTC
@sebastianas did a rebuild test against the 1.1.1-pre6 version in Debian experimental and the only new regression we can find in that caused by the TLS 1.3 changes is foolscap.

A log of that build test can be found at:
https://breakpoint.cc/openssl-rebuild/2018-05-03-rebuild-openssl1.1.1-pre6/attempted/foolscap_0.13.1-1_amd64-2018-05-02T00%3A10%3A30Z

A git bisect shows 30f05b19d3ba (Create the NewSessionTicket message in TLSv1.3 ) as the commit introducing the problem.

cc @warner

**Comment by mattcaswell** [comment] 2018-05-11 14:42
Possibly something to do with the post-handshake arrival of the session?? e.g. possible causes:
- it has its own new_session callback and is confused by being invoked after then end of the handshake
- or it attempts to get the session immediately at the end of the handshake before the NewSessionTicket has arrived.

All just speculation (and assumes it is using OpenSSL as a client).

**Comment by kroeckx** [comment] 2018-05-11 14:50
@warner: https://wiki.openssl.org/index.php/TLS1.3 contains some information about this. Can you look at it?

**Comment by kroeckx** [comment] 2018-05-11 16:44
It's available in experimental, just add it to your sources.list file and install libssl1.1/experimental

**Comment by warner** [comment] 2018-05-11 18:15
Is there a way to get the `_trial_tmp/test.log` from the failed build?

I think I installed the experimental libssl, but the bug isn't happening here yet. I might not be rebuilding the right things to pick up the new SSL, the dependency chain is not direct (it uses `cryptography`, which uses `pyopenssl`).

I'm at PyCon today, if I can track down @reaperhulk then I'll see if he can help me reproduce this one.

**Comment by kroeckx** [comment] 2018-05-11 18:34
There is also a libssl-dev package, but I don't think that's going to make a difference, specially if you're not using it directly. The log file should mention all the versions that were installed on the "Package versions:" line.

**Comment by warner** [comment] 2018-05-11 19:05
Ok, we're reproducing it now, looking into gdb traces.

**Comment by warner** [comment] 2018-05-12 19:18
We've confirmed that this is the case, by hacking twisted to wait for *two* `WantReadError`s before giving up and waiting for more ciphertext to arrive on the socket, and seeing that a basic foolscap example starts working again. So the fix is going to probably live in OpenSSL, to not return `SSL_ERROR_WANT_READ` until the BIO layer actually needs more data from the socket.

**Comment by levitte** [comment] 2018-05-14 07:09
To that last comment, I'm giving you the manual for `SSL_get_error()`:

> ```
>        SSL_ERROR_WANT_READ, SSL_ERROR_WANT_WRITE
>            The operation did not complete; the same TLS/SSL I/O function
>            should be called again later.  If, by then, the underlying BIO has
>            data available for reading (if the result code is
>            SSL_ERROR_WANT_READ) or allows writing data (SSL_ERROR_WANT_WRITE),
>            then some TLS/SSL protocol progress will take place, i.e. at least
>            part of an TLS/SSL record will be read or written.  Note that the
>            retry may again lead to a SSL_ERROR_WANT_READ or
>            SSL_ERROR_WANT_WRITE condition.  There is no fixed upper limit for
>            the number of iterations that may be necessary until progress
>            becomes visible at application protocol level.
> 
>            For socket BIOs (e.g. when SSL_set_fd() was used), select() or
>            poll() on the underlying socket can be used to find out when the
>            TLS/SSL I/O function should be retried.
> 
>            Caveat: Any TLS/SSL I/O function can lead to either of
>            SSL_ERROR_WANT_READ and SSL_ERROR_WANT_WRITE.  In particular,
>            SSL_read() or SSL_peek() may want to write data and SSL_write() may
>            want to read data.  This is mainly because TLS/SSL handshakes may
>            occur at any time during the protocol (initiated by either the
>            client or the server); SSL_read(), SSL_peek(), and SSL_write() will
>            handle any pending handshakes.
> ```

Especially, note "There is no fixed upper limit for the number of iterations that may be necessary until progress becomes visible at application protocol level."

**Comment by richsalz** [comment] 2018-06-27 17:04
It sounds like this is not an OpenSSL bug.

**Comment by levitte** [comment] 2018-07-02 17:37
I agree with @richsalz, but it would be nice if there was some external confirmation...

**Comment by mattcaswell** [comment] 2018-07-03 08:39
According to this [comment](https://github.com/openssl/openssl/issues/6234#issuecomment-388834024) setting SSL_MODE_AUTO_RETRY to on fixes the foolscap problem. Since that is now on by default, I'm closing this.

**Closed by mattcaswell** 2018-07-03 08:39 UTC

**Comment by sebastianas** [comment] 2018-07-06 21:57
I rebuilt foolscap against pre8. It still fails however with less errors [full log](https://breakpoint.cc/openssl-rebuild/2018-07-06-rebuild-openssl1.1.1-pre8/attempted/foolscap_0.13.1-1_amd64-2018-07-05T18%3A55%3A14Z).

puma failed, too and I assumed the AUTO_RETRY would fix things but it sill timeout [full log](https://breakpoint.cc/openssl-rebuild/2018-07-06-rebuild-openssl1.1.1-pre8/attempted/puma_3.11.3-1_amd64-2018-07-05T21%3A24%3A41Z)

**Comment by kroeckx** [comment] 2018-07-07 09:02
Maybe it also needs the changes from #6340
