### ISSUE TITLE
Upgrading openssl from 1.1.1 to openssl 3.0.9 causes problems with application services

### ISSUE THREAD

**Issue by Wormhole-design** [openssl/openssl#22610] opened 2023-11-03 10:07 UTC
**Background：** When we try to upgrade openssl from 1.1.1 to openssl3.0.9, the LDAP application service cannot be used normally.
**Version description：**

- LDAP client： linux openssl3.0.9
- LDAP server（AD domain）：windows2008 openssl1.0.2

**Details of the problem：**
As an LDAP client, our backend will initiate a request to the LDAP server and establish a connection. We found through packet capture that after our backend sends Client Hello to the LDAP server, the LDAP server will generate an RST response to let the client to reset the link.

**Comment by t8m** [comment] 2023-11-03 10:26
Duplicate of https://github.com/openssl/openssl/discussions/22608

**Closed by t8m** 2023-11-03 10:26 UTC
Labels: issue: bug report
