### ISSUE TITLE
`make test` failures for OpenSSL-1.1.0-dev builds using Mingw-w64

### ISSUE THREAD

**Issue by sav-ix** [openssl/openssl#1144] opened 2016-05-30 09:10 UTC
Hi, Everyone,

Built OpenSSL-1.1.0 from master branch using command:
```
./Configure --prefix="$PWD/../GCC64r" -std=gnu11 -mtune=native -march=native threads no-deprecated shared mingw64 && make
```

then ran tests using:
```
make test
```
and it launched all tests, thought some of them failed; then ran tests using:
```
HARNESS_VERBOSE=yes make test
```
and it stop respond on some `../test/recipes/70-x` test, so I have to terminate it manually ([logs](https://github.com/openssl/openssl/files/289223/openssl_test_logs.zip) added in attachment).

Do `make test` failures reproduce on other systems?

Does it mean, that PR: https://github.com/openssl/openssl/commit/cb2e10f257a464c6b475b321dd9e4769df84dbf6 not work with `HARNESS_VERBOSE=yes` option?

CC: @mattcaswell @levitte since this report could relate to [issue 4255](https://rt.openssl.org/Ticket/Display.html?id=4255).

Regards,
Alexander

**Comment by mattcaswell** [comment] 2016-05-30 18:42
I cannot reproduce this either with plain `make test` or with the `HARNESS_VERBOSE=yes` option. Looking at the log files you sent me this looks like a perl error to me. What does `perl --version` report?

**Comment by sav-ix** [comment] 2016-05-30 18:48
Perl 5.22.1. It's a recent version from MSYS2 package.

**Comment by mattcaswell** [comment] 2016-05-30 20:15
The line that is failing is trying to create a socket listening on "localhost" on port 4453. Is there any reason you can think of why that might fail on your setup? e.g. something already listening on port 4453. The test code isn't massively intelligent and will just fail if that is the case.

I've attached a patch to print a bit more error info on the failing line to see if that might give us a clue as to what is going wrong. Please can you apply, rerun the tests and send me the output?

[proxy-debug.txt](https://github.com/openssl/openssl/files/290045/proxy-debug.txt)

**Comment by sav-ix** [comment] 2016-05-31 07:57
Built OpenSSL with your patch applied and re-run tests. [Logs](https://github.com/openssl/openssl/files/290542/openssl_mingw-w64_test_logs.zip) added in attachment.

As before, process:
```
C:\libOPENSSL-1.1.0-dev\src\apps\openssl.exe s_server -no_comp -rev -engine ossltest -accept 4443 -cert ../apps/server.pem -naccept 1 -cipher AES128-SHA
```
stop respond during run `HARNESS_VERBOSE=yes make test` and have to be terminated manually.

The output of `telnet` command before and during run of that `../test/recipes/70-x` test is the same:
```
telnet localhost 4453
Connecting To localhost...Could not open connection to the host, on port 4453: Connect failed
```

I propose pause work on this issue until someone else reproduce this error. This could be troubles with my system.

**Comment by levitte** [comment] 2016-05-31 08:08
```
Failed creating proxy socket (localhost,4453): Invalid argument
 No address associated with hostname
 Invalid argument
```

so the perl module (and bottom line, `gethostbyname` or `getaddrinfo`) can't figure out an IP address for `localhost`...

**Comment by sav-ix** [comment] 2016-05-31 08:17
`ping localhost` works fine. but, in case that help, it pinging address `::1` (not `127.0.0.1`), which is mentioned in `%WINDIR%\System32\drivers\etc\hosts`.

**Comment by mattcaswell** [comment] 2016-05-31 08:21
Hmmmm...so I wonder if we are always trying to bind to an IPv4 address - which will fail on your system because `localhost` is not defined for IPv4.

**Comment by sav-ix** [comment] 2016-05-31 09:18
Replaced strings:
```
proxy_addr => "localhost",
server_addr => "localhost",
```
with
```
proxy_addr => "127.0.0.1",
server_addr => "127.0.0.1",
```
in file `util/TLSProxy/Proxy.pm`.
Test output changed to:
![make_test_cmp](https://cloud.githubusercontent.com/assets/3617101/15669571/9f490688-2729-11e6-995d-35ff83c4719d.png)

Thought it stop respond on next test
```
C:\libOPENSSL-1.1.0-dev\src\apps\openssl.exe s_server -no_comp -rev -engine ossltest -accept 4443 -cert ../apps/server.pem -naccept 1 -cipher AES128-SHA
```

**Comment by levitte** [comment] 2016-05-31 12:11
When `getaddrinfo` is used with `node` being `NULL` (which is what happens in `s_server`), the list of returned addresses will contain both `127.0.0.1` an `::1`.  We can't know in which order they come, though, and `s_server` picks the first of them.

**Comment by levitte** [comment] 2016-05-31 12:16
...  however, that has nothing to do with this issue, as this issue is about creating the listening socket for the proxy.

**Comment by levitte** [comment] 2016-05-31 12:19
@sav-ix, when the test has frozen, it would be good if you could could find out what's actually up.  I believe something like this would give an answer:

```
netstat -an | grep '44.3'
```

**Comment by sav-ix** [comment] 2016-05-31 12:22
Me already tested `netstat -a -o` when test frozen. The result was that any binary from OpenSSL build, including `openssl.exe`, doesn't listen any port.

**Comment by sav-ix** [comment] 2016-05-31 12:30
Here the frozen process:
```
C:\libOPENSSL-1.1.0-dev\src\apps\openssl.exe s_server -no_comp -rev -engine ossltest -accept 4443 -cert ../apps/server.pem -naccept 1 -cipher AES128-SHA
```
with PID == 2856, and `netstat -ano` output:
```
Active Connections

  Proto  Local Address          Foreign Address        State           PID

[snip]
 
  TCP    [::]:4443              [::]:0                 LISTENING       2856
```

**Comment by mattcaswell** [comment] 2016-05-31 12:51
The `-naccept 1` argument to s_server above causes the process to wait for exactly one connection and then close down immediately afterwards. In this case the proxy has failed to start and so that connection is never going to come, so s_server will wait indefinitely. We could perhaps fix that somehow, but by the time that has happened its all gone wrong anyway, so I'm not too worried about it. I'm more concerned with handling the localhost isn't defined issue

**Comment by mattcaswell** [comment] 2016-06-08 09:38
I wonder what `$IP_Factory` is being used in util/TLSProxy/Proxy.pm? If we use `IO::Socket::INET` and `$have_IPv6` ends up being 0, then this could explain the failure, i.e. the perl only knows how to create IPv4 sockets but `localhost` is only defined for `IPv6` - hence it fails.

**Comment by levitte** [comment] 2016-06-08 10:35
With that perl version, IO::Socket::IP should be available, no? It's to wonder why it doesn't kick in in that case...

**Comment by mattcaswell** [comment] 2016-06-14 14:05
@sav-ix, can you try out the attached patch against latest master? It doesn't solve the underlying issue as such. I believe that is most likely due to environmental problems on your machine. However it attempts to detect these issues and skip the TLSProxy tests if it encounters them (as opposed to reporting them as a test failure).

[skip-proxy-env-problems.txt](https://github.com/openssl/openssl/files/314103/skip-proxy-env-problems.txt)

**Comment by sav-ix** [comment] 2016-06-14 15:41
Applied your patch to recent OpenSSL master and made build using Mingw-w64. OpenSSL test suite freezes on same stage:
```
HARNESS_VERBOSE=yes make test

[snip]

../test/recipes/70-test_packet.t ...........
1..1
PASS
ok 1 - running packettest
../util/shlib_wrap.sh ./packettest.exe => 0
ok
../test/recipes/70-test_sslcertstatus.t ....
Failed creating proxy socket (localhost,4453): Invalid argument
1..0 # SKIP Unable to start up Proxy for tests
Using default temp DH parameters
ACCEPT
```
and should be terminated manually.

**Comment by mattcaswell** [comment] 2016-06-14 15:43
What happens with a non-verbose make test?

**Comment by sav-ix** [comment] 2016-06-14 15:55
output changed for some `70-test*`, and test suite finished without errors (see [log](https://github.com/openssl/openssl/files/314361/openssl_patched_mingw-w64_make_test.log.zip)).

**Comment by mattcaswell** [comment] 2016-06-14 15:59
Ok. I think that's an ok result. I'm not sure why it hangs on verbose output...but I'm putting it down to environmental issues on this machine. I will get this patch reviewed and applied and then close this issue.

**Comment by sav-ix** [comment] 2016-06-14 16:03
Thank you!
Any chance, that TLS tests would be fixed for Mingw-w64 and MSVC in future?

**Comment by mattcaswell** [comment] 2016-06-14 16:08
The TLS tests do work already on mingw-w64 (they work perfectly for me on that platform). I believe the specific issue you are encountering is environmental on your machine (i.e. not an OpenSSL problem). My patch just detects the fact that we can't open the socket and skips the test. On mingw-64 platforms that are able to create the socket (like on mine) the tests complete normally. WRT MSVC, I'd really like to get to the bottom of those issues but haven't been successful so far. I'm still hopeful.

**Comment by mattcaswell** [comment] 2016-06-16 15:38
This patch has now been applied in b02b5743. Closing this.

**Closed by mattcaswell** 2016-06-16 15:38 UTC

**Comment by sav-ix** [comment] 2016-06-16 17:56
Found a small drawback of this patch: OpenSSL test suite finishes successfully for Mingw-w64 builds, but `openssl.exe` instance remain in memory and should be terminated manually.
But since this issue reproduces only on my system (which obviously should be reinstalled), it doesn't worth any more attention.

**Comment by sav-ix** [comment] 2016-06-21 19:08
FYI, Windows reinstall didn't solve the issue on my system (TLS tests remain disabled and `openssl.exe` instance exists after all tests finished).
It doesn't mean, that anything should be done with it. But there is a possibility that this issue would be reproduced on other systems too.

**Comment by mattcaswell** [comment] 2016-06-21 19:38
Maybe it is my system that is unusual in that it works. I wonder what is different?

**Comment by sav-ix** [comment] 2017-04-19 10:34
Tested `HARNESS_VERBOSE=yes make test` on recent OpenSSL-1.1.1-dev build using mingw-w64. Now it finishes, instead of stop respond. This in itself is progress. Though `80-test_ssl_new.t` test fails with the same errors, as `70-test_sslcertstatus.t` did before.

Added [updated logs](https://github.com/openssl/openssl/files/933475/openssl_mingw-w64_make_test.zip), in case they contain any new/useful information.

Could you tell, how to disable test `80-test_ssl_new.t` execution during `make test` run? (share a code sample or patch)

**Comment by sav-ix** [comment] 2017-04-24 06:40
@levitte , could you take a look on my previous post. It shouldn't take a long.
Thank you.

**Comment by sav-ix** [comment] 2018-06-04 13:42
After some pause made check for builds using mingw-w64. In addition to `80-test_ssl_new.t` failures, new errors appeared:
```
Test Summary Report
-------------------
../test/recipes/20-test_enc.t                    (Wstat: 512 Tests: 172 Failed: 2)
  Failed tests:  171-172
  Non-zero exit status: 2
../test/recipes/80-test_cms.t                    (Wstat: 256 Tests: 4 Failed: 1)
  Failed test:  4
  Non-zero exit status: 1
../test/recipes/80-test_ssl_new.t                (Wstat: 256 Tests: 27 Failed: 1)
  Failed test:  22
  Non-zero exit status: 1
../test/recipes/90-test_shlibload.t              (Wstat: 512 Tests: 4 Failed: 2)
  Failed tests:  1-2
  Non-zero exit status: 2
Files=148, Tests=1330, 932 wallclock secs ( 3.47 usr  0.30 sys + 137.52 cusr 271.04 csys = 412.33 CPU)
Result: FAIL
make[1]: *** [Makefile:205: _tests] Error 1
make[1]: Leaving directory '/c/libOPENSSL-1.1.1-dev/build'
make: *** [Makefile:202: tests] Error 2
```
(see [openssl_mingw-w64_release-shared_check.zip](https://github.com/openssl/openssl/files/2068452/openssl_mingw-w64_release-shared_check.zip)).
Are they known / reproducible?

Environment:
- Windows 10 x64,
- mingw-w64 x86_64 posix seh 8.1.0,
- MSYS2 x86_64 20180531 (with recent updates),
- OpenSSL-1.1.1-dev (6da34cfbddede5e46f9c9183b724c99999dcfb41).
