### ISSUE TITLE
DTLS Handshake failure due to GCM Encrypt/Decrypt error 

### ISSUE THREAD

**Issue by NaveenShivanna86** [openssl/openssl#10638] opened 2019-12-17 15:00 UTC
Hi,

Previous related question: https://www.mail-archive.com/openssl-users@openssl.org/msg87354.html

I am using 'DTLS over SCTP' and the OpenSSL version is 1.1.1c.

I compiled OpenSSL with target 'linux-arm64ilp32' on armv8. GCC used is aarch64_be_linux-gnuilp32-gcc. So it is ILP32 and Big-end.

I compiled two sets of OpenSSL libraries:
1) OpenSSL with no-asm present
2) OpenSSL with no-asm absent (means, opened the assembler instruction support)

I observed that the DTLS handshake fails when the client with lib 1) and server with lib 2) are run.
When client sends the CCS, encrypted_handshake_finish_message, the server sends back the ALERT (Fatal, Illegal parameter).
At the server side, when SSL_accept() fails, the error code is 244 (SSL_R_UNEXPECTED_MESSAGE). This happens when processing the FINISHED message. CCS message processing is successful.

Failure source code location: dtls_get_reassembled_message(), line 805

    /*
     * We must have at least frag_len bytes left in the record to be read.
     * Fragments must not span records.
     */
    if (frag_len > RECORD_LAYER_get_rrec_length(&s->rlayer)) {
        SSLfatal(s, SSL_AD_ILLEGAL_PARAMETER,
                 SSL_F_DTLS_GET_REASSEMBLED_MESSAGE, SSL_R_BAD_LENGTH);
        goto f_err;
    }

Added a log at above failure path, the frag_len is incorrect and more than 16Kb.

Cipher used is TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384

**However, the handshake is success when both client and server use the same lib type, either 1) or 2).**

I did a sample test to confirm this issue, For a given plaintext input, when ASM is opened, the GCM encrypt and decrypt do not match. However when ASM is disabled, the encrypt and decrypt matches. 
Attached below picture:

![image](https://user-images.githubusercontent.com/20736089/71006683-ba2ba200-210b-11ea-807d-6d9c503f943f.png)

Test is done using the demo file https://github.com/openssl/openssl/blob/master/demos/evp/aesgcm.c

Please guide and also please let me know if need any further information.

**Comment by simplelins** [comment] 2019-12-17 19:49
for  NaveenShivanna86's  question, now I get further informations , at function CRYPTO_gcm128_decrypt_ctr32 , when calling  (*stream) (in, out, j, key, ctx->Yi.c) make something wrong;   the function point should be aes_v8_ctr32_encrypt_blocks.
I add some printf,as below:
        if(g_CRY_ulDebugPrintfSwitch ) {  
            printf("before CRYPTO_gcm128_decrypt_ctr32:%d bytes, j=%d\n", (int)i ,(int)j);
            {
                size_t z;
                for (z = 0; z < i; z++)
                    printf("%02X%c", in[z], ((z + 1) % 16) ? ' ' : '\n');
            }
            printf("key\n");
            {
                size_t z;
                for (z = 0; z < 32; z++)
                    printf("%02X%c", ((unsigned char*)key)[z], ((z + 1) % 16) ? ' ' : '\n');
            }
            printf("(char *)ctx->Yi.c\n");
            {
                size_t z;
                for (z = 0; z < 16; z++)
                    printf("%02X%c", ((unsigned char*)ctx->Yi.c)[z], ((z + 1) % 16) ? ' ' : '\n');
            }
            printf("\n");
        }
        (*stream) (in, out, j, key, ctx->Yi.c);
        if(g_CRY_ulDebugPrintfSwitch ) {  
            printf("after CRYPTO_gcm128_decrypt_ctr32:%d bytes, bulk=%d\n", (int)i ,(int)j);
            {
                size_t z;
                for (z = 0; z < i; z++)
                    printf("%02X%c", out[z], ((z + 1) % 16) ? ' ' : '\n');
            }
            printf("\n");
        }
and the log showed as this:
before CRYPTO_gcm128_decrypt_ctr32:16 bytes, j=1
64 D9 2E B4 DB B9 8A 45 6F 9E FB A9 F5 D4 99 5F
key
B4 B9 94 46 82 49 DF E9 82 3F E2 6A E3 18 92 2F
B2 02 43 5A 3F A3 19 9B 76 8D E6 B4 B2 CB 2D 9F
(char *)ctx->Yi.c
01 21 D8 D9 D0 71 9D 7C EE 41 3E 2F 00 00 00 02
after CRYPTO_gcm128_decrypt_ctr32:16 bytes, bulk=1
81 18 EE 43 26 46 52 9E B1 26 DA F3 BC FD 68 FC

----------------------------------------------------------------------------------------------
and then,I do a test at x86,the log show as below:
cm128_encrypt_ctr32:16 bytes, j=1
64 D9 2E B4 DB B9 8A 45 6F 9E FB A9 F5 D4 99 5F
key
46 94 B9 B4 E9 DF 49 82 6A E2 3F 82 2F 92 18 E3
5A 43 02 B2 9B 19 A3 3F B4 E6 8D 76 9F 2D CB B2
(char *)ctx->Yi.c
01 21 D8 D9 D0 71 9D 7C EE 41 3E 2F 00 00 00 02

after CRYPTO_gcm128_encrypt_ctr32:16 bytes, bulk=1
14 00 00 0C 00 04 00 00 00 00 00 0C 88 8E 29 F2

------------------------------------------------------------------------------
all the bytes come from a dtls handshake message,when server decrypt this message get a  wrong,
mac key=which = 0012
key=46 94 B9 B4 E9 DF 49 82 6A E2 3F 82 2F 92 18 E3
5A 43 02 B2 9B 19 A3 3F B4 E6 8D 76 9F 2D CB B2
IV:
01 21 D8 D9 D0 71 9D 7C EE 41 3E 2F
client tls1_enc AAD 13:
00 01 00 00 00 00 00 00 16 FE FD 00 20
client encrypt handshake message show as below
plain:
01 00 01 04 00 03 00 00 14 00 00 0C 00 04 00 00
00 00 00 0C 88 8E 29 F2 8C 91 FE 80 7A 04 4C ED
C3 6A 03 4B 07 8C 94 FF 63 1D 1A B5 CB 01 E2 48
cipher:
D0 71 9D 7C EE 41 3E 2F 64 D9 2E B4 DB B9 8A 45
6F 9E FB A9 F5 D4 99 5F 8A 04 C9 16 26 B9 E9 45
5C 92 68 E9 C0 68 5F 95 66 E5 8B C3 92 FC 11 B5

**Comment by simplelins** [comment] 2019-12-18 01:39
before aes_v8_ctr32_encrypt_blocks,The endianness of the key is different 
we set key as :46 94 B9 B4 E9 DF 49 82 6A E2 3F 82 2F 92 18 E3
5A 43 02 B2 9B 19 A3 3F B4 E6 8D 76 9F 2D CB B2
but for  ctr decrypt:
key is :
B4 B9 94 46 82 49 DF E9 82 3F E2 6A E3 18 92 2F
B2 02 43 5A 3F A3 19 9B 76 8D E6 B4 B2 CB 2D 9F

**Comment by kaduk** [comment] 2019-12-31 19:26
@tuexen I assume this is SCTP-specific since we haven't seen other reports.  Do you have any insight about how to approach further diagnosis?

**Comment by tuexen** [comment] 2019-12-31 22:03
Can you provide a way to reproduce this?

**Comment by simplelins** [comment] 2020-01-01 00:06
> @tuexen I assume this is SCTP-specific since we haven't seen other reports. Do you have any insight about how to approach further diagnosis?

please check #10692 ，we have solved it.

**Comment by simplelins** [comment] 2020-01-01 00:09
> @tuexen I assume this is SCTP-specific since we haven't seen other reports. Do you have any insight about how to approach further diagnosis?

It donot care of SCTP,the reason is some bug for bigendian of aarch64 with AESGCM.Please check #10692

**Comment by kaduk** [comment] 2020-01-01 00:15
Shall we close this issue then?
Sorry to have bothered you, Michael.

**Comment by tuexen** [comment] 2020-01-01 14:30
@kaduk No problem. Glad you figured out what is going wrong and can fix it.

**Comment by simplelins** [comment] 2020-01-01 15:17
> @kaduk No problem. Glad you figured out what is going wrong and can fix it.

1.It is still not fixed at openssl master.
2.Are there other bugs for  aarch64 bigendian that require your further analysis？ 
thanks！

**Comment by t8m** [comment] 2020-10-21 13:35
This should be now fixed on both master and 1.1.1.

**Closed by t8m** 2020-10-21 13:35 UTC
Labels: issue: bug report
