### ISSUE TITLE
Crash in BIO_test_flags

### ISSUE THREAD

**Issue by QinLongFei** [openssl/openssl#8075] opened 2019-01-23 10:01 UTC
I'm use openssl-1.0.2k and run into a crash in BIO_test_flags. Following is the crash info and stack trace.

Exception Info:
vector number    2
error id         61166
epc              0x81dbe8d8
access address   0x14
status register  0x50008ca1
cause register   0x8
error address register 0xeeeeeeee
fatal kernel task-level exception!Saving exception info to 0x8fcfbb80
01/23 14:33:58.656: 
cause: tlb load/fetch
******************************************************************
 r0 ($00): 0x0000000000000000     s0 ($16): 0xfffffffffe9c5490
 at ($01): 0xffffffff853b0000     s1 ($17): 0x0000000064a4bc30
 v0 ($02): 0x00000000000005f2     s2 ($18): 0xfffffffffe9c5490
 v1 ($03): 0xffffffff853b0000     s3 ($19): 0x0000000000000000
 a0 ($04): 0x0000000000000000     s4 ($20): 0x0000000000000000
 a1 ($05): 0x000000000000000f     s5 ($21): 0x000000000000000b
 a2 ($06): 0xffffffffe5a228d0     s6 ($22): 0xfffffffffe996aa0
 a3 ($07): 0xffffffff86918090     s7 ($23): 0xffffffffe590b814
 t0 ($08): 0x0000000050008ca1     t8 ($24): 0x0000000000000080
 t1 ($09): 0x00000000000005f2     t9 ($25): 0xffffffff82027578
 t2 ($10): 0x0000000002000000     k0 ($26): 0x0000000000000000
 t3 ($11): 0xffffffffe590b960     k1 ($27): 0x0000000000000000
 t4 ($12): 0x0000000000000190     gp ($28): 0xffffffff84f5d250
 t5 ($13): 0xffffffffcc4b22f8     sp ($29): 0xffffffffe590b580
 t6 ($14): 0x0000000000000008     s8 ($30): 0x0000000000000085
 t7 ($15): 0xfffffffffffffffc     ra ($31): 0xffffffff81dbea44
******************************************************************

Stack trace of tWebMain01 (tid e590b920):
  0x81f818dc vxTaskEntry            + 0x0014 -> (t5)
  0x8168ddc0 webSrvrThread          + 0x0728 -> httpsDoHandshake
  0x8166e810 httpsDoHandshake       + 0x0178 -> SSL_accept
  0x81e83d98 ssl23_accept           + 0x00b8 -> ssl23_get_client_hello
  0x81e83588 ssl23_get_client_hello + 0x00a0 -> SSL_accept
  0x81ea7fe0 ssl3_accept            + 0x0b58 -> BIO_ctrl
  0x81e41590 BIO_f_buffer           + 0x0458 -> BIO_copy_next_retry
  0x81dbea44 BIO_copy_next_retry    + 0x001c -> BIO_test_flags
  0x81dbe8d8 BIO_test_flags         + 0x0000

0x81dbe8c4  00052827    nor             a1,zero,a1
0x81dbe8c8  00451024    and             v0,v0,a1
0x81dbe8cc  03e00008    jr              ra
0x81dbe8d0  ac820014    sw              v0,20(a0)
0x81dbe8d4  00000000    nop     
                        BIO_test_flags:
0x81dbe8d8  8c820014    lw              v0,20(a0)
0x81dbe8dc  03e00008    jr              ra
0x81dbe8e0  00a21024    and             v0,a1,v0
0x81dbe8e4  00000000    nop     
                        BIO_set_flags:
0x81dbe8e8  8c820014    lw              v0,20(a0)

task tWebMain01 is suspended
Stack trace of tWebMain01 (tid e590b920):
  0x81f818dc vxTaskEntry            + 0x0014 -> (t5)
  0x8168ddc0 webSrvrThread          + 0x0728 -> httpsDoHandshake
  0x8166e810 httpsDoHandshake       + 0x0178 -> SSL_accept
  0x81e83d98 ssl23_accept           + 0x00b8 -> ssl23_get_client_hello
  0x81e83588 ssl23_get_client_hello + 0x00a0 -> SSL_accept
  0x81ea7fe0 ssl3_accept            + 0x0b58 -> BIO_ctrl
  0x81e41590 BIO_f_buffer           + 0x0458 -> BIO_copy_next_retry
  0x81dbea44 BIO_copy_next_retry    + 0x001c -> BIO_test_flags
  0x81dbe8d8 BIO_test_flags         + 0x0000

By simple checking the code,  In BIO_copy_next_retry, b->next_bio maybe NULL. So, we need add a check in BIO_test_flags.

**Comment by mattcaswell** [comment] 2019-01-24 15:55
This suggests the write BIO for the connection has somehow been set to NULL (or perhaps some other invalid value). Putting a test for NULL in BIO_copy_next_retry might avoid this crash but it wouldn't solve the underlying issue - why is the write BIO invalid?

**Comment by mattcaswell** [comment] 2019-11-05 11:22
This question seems to have been answered. Closing.

**Closed by mattcaswell** 2019-11-05 11:22 UTC
Labels: resolved: answered, triaged: question

**Comment by httpstorm** [comment] 2021-08-09 17:33
@QinLongFei @mattcaswell 
I just struggled on this after adding OpenSSL support to my web server `httpstorm.com` and also my network benchmark tool. In my environment the client is affected by the crash. The affected design uses dedicated read and write threads for each connection. Documentation states OpenSSL is thread safe, but then a simple thing as having dedicated read and write threads breaks it. This should be revised!


Steps to reproduce:
The TLS server is configured to receive client's data, and does not send anything.
The client sample code below allows reproducing the issue with 90% change.
No issues when communicating with localhost. In order to reproduce reliably, either forward a port on a router back to the host, or use two separate machines.
There are two possible failures:
1. Crash in BIO_test_flags
2. Connection gets dropped (send or recv return a failure)

As a workaround, delay the first send. 50 ms seems enough, I used 100 as a good measure. If we delay the recv call, the issue is more likely to happen. 250 ms is a good starting point. It is very easy to reproduce on Windows 10, and harder on Ubuntu 20.04. I'm on gigabit LAN. Windows 10 is the host, Ubuntu is a Hyper-V guest. Each have dedicated gigabit interface.
```
connect_client();
tasks[i].resume_r();
// Sleep(100); // workaround: delay the first send
while (1)
{
	ssize_t size = tasks[i].ws.tls.send(tasks[i].pSND, tasks[i].page_size_w);

	if (size <= 0)
	{
		break;
	}
}

// read task: wait for event and start receiving data
e_read.wait();
while (1)
{
	ssize_t size = tasks[i].ws.tls.recv(tasks[i].pRAM, tasks[i].page_size_r);
...
}

```


Bellow is a trace on OpenSSL 1.1.1k
I used Visual Studio 2019 on Windows 10 to debug. Surprisingly, the BIO pointer is initially valid, then a becomes corrupted and points to invalid memory.
```
s = 0x0000024aaf564270 {version=0x00000304 method=0x00007ff794821280 {gns.exe!ssl_method_st tlsv1_3_client_method_data} {...} ...}
statem = {state=MSG_FLOW_FINISHED (0x00000004) write_state=WRITE_STATE_PRE_WORK (0x00000001) write_state_work=WORK_FINISHED_STOP (0x00000001), read_state=READ_STATE_BODY (0x00000001), ...}
buf=0x0000024aac0d0000, num=0x6b0
SSL_write(s, buf, num);

ssl_lib.c
1974  s=?, bug=?, num=?, written=0x6b0
ret = ssl_write_internal(s, buf, (size_t)num, &written);

1960  s=0x0000024aaf564270, buf=0x0000024aac0d0000, num=0x6b0
return s->method->ssl_write(s, buf, num, written);

4451  s=0x0000024aaf564270, buf=0x0000024aac0d0000, len=0x6b0
4452  written=0x0000007e1821f978 (0x6b0)
return s->method->ssl_write_bytes(s, SSL3_RT_APPLICATION_DATA, buf, len,
                                      written);

rec_layer_s3.c
620   s=0x0000024aaf564270, type=0x17, buf=?, tot=0,
pipelens = 0x0000007e1821f700 {0x00000000000006b0, 0x0000000000000000, 0x0000000000000000, 0x0000000000000002, ...}
numpipes=?, tmpwrit=0x6b0
i = do_ssl3_write(s, type, &(buf[tot]), pipelens, numpipes, 0,
                          &tmpwrit);

1115  s=0x0000024aaf564270, type=0x17, buf=0x0000024aac0d0000, totlen=0x0000007e1821ed60, written=0x6b0
return ssl3_write_pending(s, type, buf, totlen, written);

1154  s=0x0000024aaf564270
s->wbio = 0x0000024aaf2eba00 {method=0x00007ff7947a84f0 {gns.exe!bio_method_st methods_sockp} {type=0x00000505 ...}, next_bio = 0x0000000000000000 <NULL>, prev_bio = 0x0000000000000000 <NULL>, num_read = 0x0000000000000707, num_write = 0x0000000000001175 ...}
wb=?, currbuf=0
i = BIO_write(s->wbio, (char *)
                          &(SSL3_BUFFER_get_buf(&wb[currbuf])
                            [SSL3_BUFFER_get_offset(&wb[currbuf])]),
                          (unsigned int)SSL3_BUFFER_get_left(&wb[currbuf]));

bio_lib.c
363   b=?, data=?, dlen=?, written=0x8000
ret = bio_write_intern(b, data, (size_t)dlen, &written);

343   b = 0x0000024aaf2eb4c0 {method=0xdddddddddddddddd {type=??? name=??? bwrite=??? ...} callback=0xdddddddddddddddd, next_bio = 0xdddddddddddddddd {method=??? callback=??? callback_ex=??? ...}, prev_bio = 0xdddddddddddddddd {method=??? callback=??? callback_ex=??? ...} ...}
data=0x0000024aaf558443, dlen=0x00000000000006c6, written=0x0000007e1821e648 (0x8000)
ret = b->method->bwrite(b, data, dlen, written);

bio_meth.c
77    bio=?, bio->method=?, bio->method->bwrite_old=?, data=?, datal=?
ret = bio->method->bwrite_old(bio, data, (int)datal);

bf_buff.c
218   b = 0x0000024aaf2eb4c0 {method=0xdddddddddddddddd {type=??? name=??? bwrite=??? ...} callback=0xdddddddddddddddd ...}
BIO_copy_next_retry(b);

bio_lib.c
744   b = 0x0000024aaf2eb4c0 {method=0xdddddddddddddddd {type=??? name=??? bwrite=??? ...} callback=0xdddddddddddddddd ...}
b->next_bio = 0xdddddddddddddddd {method=??? callback=??? callback_ex=??? ...}
BIO_set_flags(b, BIO_get_retry_flags(b->next_bio));

197   b = 0x0000024aaf2eb4c0 {method=0xdddddddddddddddd {type=??? name=??? bwrite=??? ...} callback=0xdddddddddddddddd ...}
flags=?
Exception thrown: read access violation.
b->next_bio was 0xFFFFFFFFFFFFFFD7
return (b->flags & flags);
```

**Comment by t8m** [comment] 2021-08-10 07:06
You cannot simultaneously use a single SSL object from two separate threads without locking the access to the SSL object. This is by design.

**Comment by httpstorm** [comment] 2021-08-11 21:13
@t8m 
I understand this makes OpenSSL a half-duplex transport, which conflicts with the idea that sockets are full-duplex. Any high performance server should be able to receive new requests while sending data back to the client. My recommendation to the OpenSSL developers is to consider this and enable safe full-duplex operation. Since this mostly works it shouldn't be that hard. The crash only affects clients during the first few packets with app data. As a reference, GnuTLS and Microsoft SSPI did not experience any crash, but OpenSSL is faster.

Can I use OpenSSL only to encrypt and decrypt data, and then use my own code to communicate with the client? Any examples?

**Comment by richsalz** [comment] 2021-08-11 23:29
Your understanding is not correct.  It is possible to do simultaneous read/write, but you can't do it with separate threads. You have to use non-blocking I/O and polling.

**Comment by httpstorm** [comment] 2021-08-12 04:27
@richsalz 
Thank you for clarifying! That would however require major redesigns on my web server and several other apps. Currently blocking IO is used, because it results in linear code which is more simple and easy to follow. Is there any reason why the OpenSSL developers are not implementing simultaneous IO from separate threads?
Can I overcome this limitation by using OpenSSL only to encrypt and decrypt data? This would also solve the `SIGPIPE` issue. I can't find a way to pass flags such as `MSG_NOSIGPIPE` to `send` when using `SSL_write`.

**Comment by richsalz** [comment] 2021-08-12 13:42
> Is there any reason why the OpenSSL developers are not implementing simultaneous IO from separate threads?

Someone from the project (I'm just a bystander) will have to answer that.

>Can I overcome this limitation by using OpenSSL only to encrypt and decrypt data?

There used to be a demo, "tunala", in earlier OpenSSL releases that showed how to do that. It wasn't production-ready but might be a useful base for you to start from.

**Comment by t8m** [comment] 2021-08-13 08:44
Allowing full-duplex operation without non-blocking sockets, i.e., simultaneous operation with separate threads for reading and writing application data would require seriously non-trivial synchronization operations performed inside the SSL API calls. Please note that the underlying data transfers have to be both ways even if you're just reading from or just writing to a SSL BIO. If you want separate threads for simultaneous input and output data transfers and do not want to use non-blocking IO I'd recommend using two separate connections for these threads.

Anyway, making this magically work with SSL API is not going to happen, IMO.

**Comment by httpstorm** [comment] 2021-08-19 18:30
@richsalz Thank you for the hint! Indeed tunala was helpful as a guide that I should use memory BIO.
@t8m I implemented memory BIOs. Since `send` is now called by my applications, I can add the `MSG_NO_SIGNAL` flag, to avoid `SIGPIPE`, without blocking it for the whole application, which is not desirable. It would be nice if OpenSSL provides an API to control the send flags.
Thanks, Tomáš! Is it safe to use separate threads when a memory BIO is involved? Now that the socket IO is separate, I can use a mutex to isolate `SSL_read` from `SSL_write`. Though I have not observed any crash once I started waiting for message 4 during the client handshake. I assume from the perspective of the SSL object, the socket access is now non-blocking?

My send function looks like this: `SSL_write, BIO_get_mem_ptr, ::send, bm->length=0, BIO_set_shutdown(b, BIO_NOCLOSE), BIO_set_mem_buf(b, bm, BIO_CLOSE)`.
Usually `BIO_read` marks all read data as free, however I don't have any storage to make a copy, because I receive a `const char *`, and `malloc` is slow, so I get the pointer to BIO's data directly, but then I couldn't find a good way to mark all data as free. I always send all data. `BIO_reset` does that, but internally also uses `memset`, which is a performance hit with a 2MB buffer. On the receiving side I loop this until I get at least one byte: `::recv, BIO_write, SSL_read`. In theory I should be able to use `BIO_set_mem_buf` to provide the data directly, instead of using `BIO_write` to copy it, but this fails. What is the approach to using `BIO_set_mem_buf` with the input BIO? I'm also looking for a way to set the buffers manually so that BIOs don't have to allocate and free memory.
Full implementation: [https://pastebin.com/4UrStN13](url)

I figured a way to avoid the crash: the original materials I read showed that the handshake consists of 3 steps, so at first I implemented the memory BIO handshake that way. It worked with Chrome and OpenSSL clients, but iPhones hang waiting for something and do not send any data. During testing, I observed the same crash as when OpenSSL is used directly. Then I found the following article, and learned that there is a finished message from the server as step 4: [https://www.roxlu.com/2014/042/using-openssl-with-memory-bios](url). So I added code for the server to send the finished message, and the client to receive it. This fixed both the crash and iPhones not able to connect. Everything seems to work great now! Thank you all for the guidance!

Original observations when using OpenSSL with a socket, point that the crash only occurred during the first few messages. After that the app happily runs overnight without any issues. Only clients are affected and iPhones are able to connect. This means that on the server side `SSL_accept` sends the 4th message, but on the client side `SSL_connect` does not wait for it. Instead it relays on calling `SSL_read` to process it later. So if the timing is right and we call `SSL_write`, before `SSL_read`, it is likely that the object is not fully initialised, and this could lead to a crash. Is this a bug in OpenSSL? IMO adding a wait for the 4th message inside `SSL_connect` will make OpenSSL way more reliable for anyone trying to use separate threads for send and receive.

With HTTP, the client expects to receive a response on the same socket. I'm actually working on my web-server [https://httpstorm.com/](url) and I'm trying to be the fastest in the world. So far successfully. ⚡️

**Comment by richsalz** [comment] 2021-08-19 18:36
Glad you got things working (more or less) and congrats on the speed.

As a former project member, I'll point out that a lengthy comment on a closed issue isn't going to get much attention. If you want the project to look at things, I suggest you open a separate new issue for each item (set the flags, fourth message, etc)

**Comment by httpstorm** [comment] 2021-08-19 19:47
@richsalz Thanks!

**Comment by httpstorm** [comment] 2021-08-24 13:07
SIGPIPE when OpenSSL is used with a socket
https://github.com/openssl/openssl/issues/16399

Bug in SSL_connect results in a crash
https://github.com/openssl/openssl/issues/16400
