### ISSUE TITLE
question on tls handshake failure scenario due to version incompactability 

### ISSUE THREAD

**Issue by Anusha-Pai95** [openssl/openssl#13908] opened 2021-01-20 05:24 UTC
on a tls client, which api can help us to get the tls version enabled in server . In order to detect and capture a failure handshake scenario in tls client when version mismatched between client and server. For example  client running on tls1.2 and openssl server supporting tls1 which results in version mismatch between syslog tls client and server. Inorder to capture this scenario in tls client do we have any predetermined api that helps us to get the version enabled on server from the client.
wanted to capture the this error condition in tls client by inserting a log in the client during this handshake failure case.
there is a function SSL_get_version which return the protocol version and it requires ssl object. is there any way to get the server ssl object while running in the client. So server's ssl object can be passed to the above mentioned function to get the server openssl protocol version and it if is unsupported in the client then adding a log to capture this failure condition could actually solve this problem.
intent was to get a log indicating the reason for  tls handshake failure. In case of version incompatibility between the client and server, how can this case be detected from  openssl client.

**Comment by mattcaswell** [comment] 2021-01-20 10:45
> on a tls client, which api can help us to get the tls version enabled in server 

It is not possible to directly query the protocols enabled on the server from the client side. What you *can* do is attempt a handshake and detect a protocol version mismatch at that point.

If the server selects a version that the client does not support, then the client will raise an error. The reason code `SSL_R_UNSUPPORTED_PROTOCOL` will be put on the OpenSSL error stack (see the `ERR_*` functions for getting error data off the error stack). This might happen (for example) if the server's maximum supported protocol version is less than the client's minimum supported protocol version.

The server might also detect a protocol mismatch. For example this might occur if the server's minimum supported protocol version is higher than the client's maximum support protocol version. In that case the server will send a protocol version alert to the client. When the client receives this alert the handshake will fail and the client will raise an error. The reason code `SSL_R_TLSV1_ALERT_PROTOCOL_VERSION` will be put on the OpenSSL error stack.

**Comment by t8m** [comment] 2021-07-22 14:51
Closing as duplicate of #14570

**Closed by t8m** 2021-07-22 14:51 UTC
Labels: resolved: answered
