### ISSUE TITLE
Mac Build of Legacy Provider

### ISSUE THREAD

**Issue by anhu** [openssl/openssl#14794] opened 2021-04-07 20:48 UTC
When the legacy provider gets built, it comes out as legacy.dylib.  From what I understand, .dylib signifies it should be linked against. Would it be more appropriate if it was legacy.so or even legacy.bundle?

**Comment by mattcaswell** [comment] 2021-04-07 21:26
This is a dupe of #14602.

**Closed** 2021-04-07 21:26 UTC
Labels: issue: bug report
