### ISSUE TITLE
get.adobe.com results in wrong signature type

### ISSUE THREAD

**Issue by kroeckx** [openssl/openssl#7126] opened 2018-09-05 16:44 UTC
Using pre9: openssl s_client -connect get.adobe.com:443

Usually results in:
139921395720640:error:1414D172:SSL routines:tls12_check_peer_sigalg:wrong signature type:../ssl/t1_lib.c:1073:

Sometimes it works. Is this a bug on our end?

**Comment by mattcaswell** [comment] 2018-09-05 16:49
Hmm. I can't replicate this. It works every time for me. What was your Configure line?

**Comment by richsalz** [comment] 2018-09-05 16:54
You might be running afoul of the CDN Adobe is using.  What does "host get.adobe.com" show for both of you?

**Comment by mattcaswell** [comment] 2018-09-05 17:03
```
$ host get.adobe.com
get.adobe.com is an alias for get.wip4.adobe.com.
get.wip4.adobe.com has address 192.147.130.63
```

**Comment by kroeckx** [comment] 2018-09-05 17:04
I currently have the same reply, and it currently also always works. Just try again in a minute.

**Comment by kroeckx** [comment] 2018-09-05 17:04
I now get:
get.adobe.com is an alias for get.wip4.adobe.com.
get.wip4.adobe.com has address 193.104.215.66

And it fails

**Comment by mattcaswell** [comment] 2018-09-05 17:07
I'm now also getting the same reply as you. But it still always works for me.

**Comment by kroeckx** [comment] 2018-09-05 17:11
It seems to be related to setting the security level to 2

**Comment by kroeckx** [comment] 2018-09-05 17:12
So that's with: openssl s_client -connect get.adobe.com:443 -cipher DEFAULT@SECLEVEL=2

**Comment by mattcaswell** [comment] 2018-09-05 17:26
I have replicated the issue. When SECLEVEL=2 our offered signature algorithms don't include any based on SHA1 (although apparently we're perfectly happy with DSA at that security level!):

````
        extension_type=signature_algorithms(13), length=42
          ecdsa_secp256r1_sha256 (0x0403)
          ecdsa_secp384r1_sha384 (0x0503)
          ecdsa_secp521r1_sha512 (0x0603)
          ed25519 (0x0807)
          ed448 (0x0808)
          rsa_pss_pss_sha256 (0x0809)
          rsa_pss_pss_sha384 (0x080a)
          rsa_pss_pss_sha512 (0x080b)
          rsa_pss_rsae_sha256 (0x0804)
          rsa_pss_rsae_sha384 (0x0805)
          rsa_pss_rsae_sha512 (0x0806)
          rsa_pkcs1_sha256 (0x0401)
          rsa_pkcs1_sha384 (0x0501)
          rsa_pkcs1_sha512 (0x0601)
          ecdsa_sha224 (0x0303)
          rsa_pkcs1_sha224 (0x0301)
          dsa_sha224 (0x0302)
          dsa_sha256 (0x0402)
          dsa_sha384 (0x0502)
          dsa_sha512 (0x0602)
````

However, in spite of not offering a SHA1 based sig alg, the ServerKeyExchange we get back is signed using rsa_pkcs1_sha1

````
Received Record
Header:
  Version = TLS 1.2 (0x303)
  Content Type = Handshake (22)
  Length = 333
    ServerKeyExchange, Length=329
      KeyExchangeAlgorithm=ECDHE
        named_curve: secp256r1 (P-256) (23)
        point (len=65): 0421D0E0895DB46863CF62B9094705D2703AB8BCBAC349A2873EF8EE7B042D37F0F0997712CD165E09512BC49409CEDEBE4536BC83784E0AE645B278B39A695846
      Signature Algorithm: rsa_pkcs1_sha1 (0x0201)
      Signature (len=256): BD61649AE4A2F8A8F5C69D5C501A8BA9166C1F1748FBDB64FEC31EC4851F8D2C26BBB85A58710E52C496306A2969A3FAE69B3382B26CB7F12017FE0F6FABCB69846216C3CF08C505312FF6E6B653899CBD41BB0E73A38E20E96684842B845F86CD8988D657E1678062493E19F2684625C9C4C1177C5206A8293B60B6FEEE8A93524C2F7E3EA7608D89B57FB5547D9F1EED29D4C4087A5A4D2A0458BF03FE9CEF338F89282611345001570F712A5765C14743B87DAC3720A4DF6887933BB1B9E5433E6C05C0E1D8E6EB751549B6AF9E004993AA9807DF2DF6E4DF95A47F797CC3B3E919C15AA79E74058D2D36B9D4987FC3444A86F435B8B69026ED24DC4938B5

````

I'll need to double check the spec to see if honouring the sig algs is a MUST or not.

**Comment by davidben** [comment] 2018-09-05 17:29
There's two IPs for that server, 193.104.215.66 and 192.147.130.63. 63 is fine. 66 is one of those servers that, despite implementing TLS 1.2, only sign SHA-1.

There are frustratingly many of these, which is why everyone is stuck accepting SHA-1 right now. It would be good to find out what they're running and get this fixed. Historically OpenSSL had some bugs around here with `SSL_set_SSL_CTX`, but that was fixed with 1ce95f19601bbc6bfd24092c76c8f8105124e857 and a92ca561bc91f4ebd2f53578e82058efcde61aed. I believe other load balancer products also failed to implement secure signature algorithms in TLS 1.2.

**Comment by mattcaswell** [comment] 2018-09-05 17:32
The spec says this about the signature in the ServerKeyExchange

> If the client has offered the "signature_algorithms" extension, the
>    signature algorithm and hash algorithm MUST be a pair listed in that
>    extension.

So this definitely looks like a case of a non-compliant server.

**Comment by davidben** [comment] 2018-09-05 17:37
Seems @mattcaswell and I crossed mid-air.

Many of the SHA-1-only servers I've seen just ignore the extension and blindly sign SHA-1. This includes the buggy versions of OpenSSL. Others actually honor the signature algorithms extension but require rsa_pkcs1_sha1. Yet others (Schannel) actually can sign SHA-2, but will preferentially sign SHA-1 if available.

I've seen one that was particularly bizarre (old F5s). It pays attention to sigalgs for purposes of deciding whether to use a plain RSA or ECDHE_RSA cipher and *thinks* it supports rsa_pkcs1_sha{1,256,384}, but having selected an ECDHE_RSA cipher, it then ignores the list and unconditionally signs rsa_pkcs1_sha1! Note, in particular, rsa_pkcs1_sha512 is absent from the above. So if you offer just rsa_pkcs1_sha512, it "correctly" picks plain RSA since ECDHE_RSA would require signing something it doesn't support. If you offer rsa_pkcs1_sha256 alongside that, then it picks ECDHE_RSA and signs rsa_pkcs1_sha1 anyway.

This server is exhibiting that behavior, so it seems 66 is an F5 missing updates, while 63 has the fix.

**Comment by richsalz** [comment] 2018-09-05 17:41
So should SHA1 be moved into SECLEVEL=2, with the rationale that we accept DSA at that level? Or should this just be fixed in the documentation; I'm not sure where.

**Comment by kroeckx** [comment] 2018-09-05 17:52
I don't see a problem with DSA at that level. DSA supports 2048 bit keys.

**Comment by davidben** [comment] 2018-09-05 18:08
Depends on what SECLEVEL=2 is meant to be I suppose. There are obvious downsides to accepting SHA-1 online signatures, but the ecosystem is also full of bad servers. I'll see if I can dig up a contact at Adobe to get this one fixed.

**Comment by tomato42** [comment] 2018-09-05 18:11
> I've seen one that was particularly bizarre (old F5s).

yes, it does look like an F5 BIG-IP system. Running https://github.com/WestpointLtd/tls_prober/pull/36 against it produces:
```
                        F5 BIG-IP 11.5.1 Build 6.0.159 Hotfix HF6: 100.00%
                        F5 BIG-IP 11.5.1 Build 8.0.175 Hotfix HF8: 100.00%
                          F5 BIG-IP 11.4.1 Build 675.0 Hotfix HF7:  90.00%
                              openssl-1.0.1h default source build:  50.00%
                              openssl-1.0.1c default source build:  50.00%
                              openssl-1.0.1f default source build:  50.00%
                              openssl-1.0.1a default source build:  50.00%
                              openssl-1.0.1d default source build:  50.00%
                               openssl-1.0.1 default source build:  50.00%
                              openssl-1.0.1e default source build:  50.00%
                                   OpenSSL 1.0.1k Debian 8 Apache:  50.00%
                              openssl-1.0.1b default source build:  50.00%
                              openssl-1.0.1g default source build:  50.00%
                                                      axTLS-1.5.2:  40.00%
                                                    ...
```

full run isn't much different:
```
$ ./prober.py -n get.wip4.adobe.com
                        F5 BIG-IP 11.5.1 Build 8.0.175 Hotfix HF8: 100.00%
                        F5 BIG-IP 11.5.1 Build 6.0.159 Hotfix HF6: 100.00%
                          F5 BIG-IP 11.4.1 Build 675.0 Hotfix HF7:  87.50%
                              openssl-1.0.1h default source build:  45.83%
                              openssl-1.0.1d default source build:  45.83%
                                            ...
```

**Comment by davidben** [comment] 2018-09-05 22:27
Yup, that looks like the broken version of OpenSSL. You can additionally tell because it signs a sensible algorithm if you omit SNI, but it only signs SHA-1 if you send SNI. (OpenSSL's bug triggered if you used `SSL_set_SSL_CTX`. This is primilarly used with SNI.)

**Comment by davidben** [comment] 2018-09-05 22:28
I hear you're a Debian developer. Want to get that site fixed? ;-)

**Comment by kroeckx** [comment] 2018-09-16 12:27
As far as I can see, in the 1.0.1 branch this was fixed in commit 4e05aedbcab7f7f83a887e952ebdcc5d4f2291e4. I can reproduce the error with Debian's 1.0.1e-2+deb7u20, but not with 1.0.1t-1+deb7u4. That commit is part of 1.0.1j. 1.0.1 was the first release to support TLS 1.2, so I think this got fixed in all branches.

**Comment by pavelsr** [comment] 2019-10-15 10:48
Same problem:

```
# curl -L https://tbankrot.ru
curl: (35) error:1414D172:SSL routines:tls12_check_peer_sigalg:wrong signature type
```

With `OpenSSL 1.1.1c  28 May 2019` error will appear, but `OpenSSL 1.1.1  11 Sep 2018` produces no error.

So I'm understanding right, that each site uses SHA1 will produce `tls12_check_peer_sigalg:wrong signature type` error with openssl version >1.1.1 ?

**Comment by mattcaswell** [comment] 2019-10-15 11:01
I can't replicate it using s_client, with 1.1.1 latest (from git) or 1.1.1c. Most likely its a server farm with some buggy servers in it. Depending on which one you hit depends on whether you get the error or not.

**Comment by armansa** [comment] 2020-11-03 06:10
I have same issue with **g2g.abr.gov.au** . using curl i get this error:
curl: (35) error:1414D172:SSL routines:tls12_check_peer_sigalg:wrong signature type

But I can connect using firefox and this is screenshot from network pane:
![image](https://user-images.githubusercontent.com/1998008/97954383-757a2980-1df7-11eb-9318-cebfe5e07caf.png)

**Comment by tomato42** [comment] 2020-11-03 11:55
@armansa the bug is on the server side, as soon as Firefox deprecates SHA-1 signatures it will fail to connect too

**Comment by t8m** [comment] 2021-05-18 10:16
There is no bug on current OpenSSL releases. The problem is with non-compliant servers. Closing.

**Closed by t8m** 2021-05-18 10:16 UTC
