### ISSUE TITLE
" BIO *BIO_new_mem_buf" failing in ubuntu 14.04

### ISSUE THREAD

**Issue by debdipta** [openssl/openssl#1405] opened 2016-08-05 11:47 UTC
```
    building '_openssl' extension
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c build/temp.linux-x86_64-2.7/_openssl.c -o build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7/_openssl.o
    build/temp.linux-x86_64-2.7/_openssl.c:697:6: error: conflicting types for 'BIO_new_mem_buf'
     BIO *BIO_new_mem_buf(void *, int);
          ^
    In file included from /usr/include/openssl/asn1.h:65:0,
                     from build/temp.linux-x86_64-2.7/_openssl.c:413:
    /usr/include/openssl/bio.h:692:6: note: previous declaration of 'BIO_new_mem_buf' was here
     BIO *BIO_new_mem_buf(const void *buf, int len);
          ^
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    ----------------------------------------
  Rolling back uninstall of cryptography
Command "/usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-PZInrx/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-xZqJkR-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-PZInrx/cryptography

```
While "creating build/lib.linux-x86_64-2.7/cryptography" in Linux 14.04 LTS, it is failing here.

**Comment by levitte** [comment] 2016-08-05 11:55
The issue is with your `_openssl.c`. Just remove that declaration from there. 

Closing, as this is not an issue in our code.

**Closed by levitte** 2016-08-05 11:55 UTC
