### ISSUE TITLE
configure script fails if path contains "@" symbol

### ISSUE THREAD

**Issue by jeroen** [openssl/openssl#12743] opened 2020-08-28 20:51 UTC
In Homebrew, the formula will be called "openssl@3" and get installed in `/usr/local/Cellar/openssl@3`. I noticed that the @ symbol in the path seems to break the configure script as below. This did not happen for `openssl@1.1`.

```sh
perl ./Configure --prefix=/usr/local/Cellar/openssl@3/3.0.0-alpha6 --openssldir=/usr/local/etc/openssl3 no-ssl3 no-ssl3-method no-zlib darwin64-x86_64-cc enable-ec_nistp_64_gcc_128
make
#Last 15 lines from /Users/jeroen/Library/Logs/Homebrew/openssl@3/02.make:
#2020-08-28 22:43:13 +0200
#
#make
#
#Makefile:2: *** missing separator.  Stop.
```

**Comment by levitte** [comment] 2020-08-29 04:01
mind giving us the output of `head -5 Makefile`?

**Comment by jeroen** [comment] 2020-08-29 07:46
```
Program fragment delivered error ``Can't locate platform.pm in @INC (you may need to install the platform module) (@INC contains: . /private/tmp/openssl-20200829-19268-1d88s2b/openssl-3.0.0-alpha6/Configurations /private/tmp/openssl-20200829-19268-1d88s2b/openssl-3.0.0-alpha6/util/perl /private/tmp/openssl@3-20200829-19268-1d88s2b/openssl-3.0.0-alpha6/util/perl /Library/Perl/5.18/darwin-thread-multi-2level /Library/Perl/5.18 /Network/Library/Perl/5.18/darwin-thread-multi-2level /Network/Library/Perl/5.18 /Library/Perl/Updates/5.18.4 /System/Library/Perl/5.18/darwin-thread-multi-2level /System/Library/Perl/5.18 /System/Library/Perl/Extras/5.18/darwin-thread-multi-2level /System/Library/Perl/Extras/5.18 /private/tmp/openssl@3-20200829-19268-1d88s2b/openssl-3.0.0-alpha6/external/perl/Text-Template-1.56/lib) at (eval 6) line 5.
BEGIN failed--compilation aborted at (eval 6) line 5.''
##
## Makefile for OpenSSL
##
```

**Comment by kroeckx** [comment] 2020-10-04 14:47
Seems to be a duplicate of #12078

**Comment by levitte** [comment] 2020-10-23 01:10
Please try the fix in #13225

**Comment by jeroen** [comment] 2020-10-23 20:34
I don't think this fixed it. Now seeing this:

```
make

perl "-I." "-Idoc" -Mconfigdata -Mperlvars "util/dofile.pl" "-oMakefile" doc/man1/openssl-asn1parse.pod.in > doc/man1/openssl-asn1parse.pod
Can't locate platform.pm in @INC (you may need to install the platform module) (@INC contains: . /private/tmp/openssl.0-20201023-10411-hewbzl/openssl-3.0.0-alpha7/util/../Configurations /private/tmp/openssl@3.0-20201023-10411-hewbzl/openssl-3.0.0-alpha7/util/perl doc /Library/Perl/5.18/darwin-thread-multi-2level /Library/Perl/5.18 /Network/Library/Perl/5.18/darwin-thread-multi-2level /Network/Library/Perl/5.18 /Library/Perl/Updates/5.18.4 /System/Library/Perl/5.18/darwin-thread-multi-2level /System/Library/Perl/5.18 /System/Library/Perl/Extras/5.18/darwin-thread-multi-2level /System/Library/Perl/Extras/5.18 /private/tmp/openssl@3.0-20201023-10411-hewbzl/openssl-3.0.0-alpha7/external/perl/Text-Template-1.56/lib /private/tmp/openssl@3.0-20201023-10411-hewbzl/openssl-3.0.0-alpha7/util/../external/perl/Text-Template-1.56/lib) at (eval 6) line 4.
BEGIN failed--compilation aborted at (eval 6) line
```

**Comment by levitte** [comment] 2020-10-24 04:56
Please check if `/private/tmp/openssl.0-20201023-14132-zhzxv1/openssl-3.0.0-alpha7/util/../Configurations` contains `platform.pm`. It should...

**Comment by Croydon** [comment] 2020-10-25 19:51
I can confirm @jeroen's report 

Logs:
https://github.com/conan-io/conan-center-index/pull/2054#issuecomment-714911728

**Comment by levitte** [comment] 2020-10-25 20:02
Ah, found the culprit.  #13225 is updated, please try once more?

**Comment by jeroen** [comment] 2020-10-25 21:51
Thanks, it now works with the latest #13225 patch!

**Comment by Croydon** [comment] 2020-10-26 16:49
Works for Conan too. All 88 configurations build now again 👍

**Closed** 2020-10-27 09:18 UTC
Labels: branch: master, triaged: bug
