### ISSUE TITLE
openssl 1.1.0e reports X509_V_ERR_CA_MD_TOO_WEAK for rsassaPss

### ISSUE THREAD

**Issue by aaronp24** [openssl/openssl#3558] opened 2017-05-25 17:34 UTC
Our internal corporate SSL CA uses the rsassaPss signature algorithm. openssl 1.0 validates this just fine, as does openssl built from master. However, openssl 1.1.0e rejects it with "CA signature digest algorithm too weak".

I stepped through it and the problem is that check_sig_level calls OBJ_find_sigid_algs with an nid of 912, and it returns mdnid == NID_undef. That leaves secbits set to -1, so the call fails:

    return secbits >= minbits_table[level - 1];

(where minbits_table[level - 1] is 80).

What's extra weird is that `openssl s_client -connect internal-server:443` complains, but `openssl verify -show_chain -untrusted intermediate.pem server.pem` decides that everything is fine.

**Comment by aaronp24** [comment] 2017-05-25 18:01
Edit: Still a problem with openssl 1.1.0f.

**Comment by mattcaswell** [comment] 2018-04-19 13:32
Is this still an issue? I've not been able to recreate this problem. I created a CA with a PSS cert, and then created a "normal" RSA ee cert from it. s_client was able to verify the chain just fine. I tried with the latest 1.1.0 from git as well as with 1.1.0f with the same results.

**Comment by aaronp24** [comment] 2018-04-19 16:02
Yes.

**Comment by mattcaswell** [comment] 2018-04-20 16:44
I have been able to recreate this issue.

The reason this fails is that 1.1.0 introduced stricter checking of any intermediate CA digests according to the set "security level". This checking does not exist at all in 1.0.2, which is why this doesn't fail in 1.0.2. The only work around I can come up with for this is to reduce the security level to 0 (e.g. by adding `@SECLEVEL=0` onto the end of your cipher list).

The problem is that OpenSSL's support for PSS certificates has historically always been minimal to say the least. You cannot use them as an end entity cert in 1.1.0 or 1.0.2 (but you can in 1.1.1) at all. It was kind of luck that you could get away with it as a CA cert in 1.0.2 due to the looser checking that goes on in that version.

The way we check the message digest in 1.1.0 is to infer it from the OID for signature. This works for most certificate types but not PSS, where the digest details are stored as parameters in the SignatureAlgorithmIdentifier. In master (1.1.1) we have added full support for PSS certs, including as end entity certs or as intermediate certs.

PR #3301 added the necessary support for this into master. Unfortunately that is far too significant a change to back port to a stable branch. Therefore there is no easy fix for this for 1.1.0. The only options are to either (1) wait for 1.1.1 to come out, or (2) use the security level workaround.

**Comment by aaronp24** [comment] 2018-04-20 16:58
Would it be a reasonable compromise to relax the security check back to 1.0 behavior just for PSS?

I convinced my organization's IT department to switch to SHA-256 + RSA, but there are still a bunch of internal sites using the old CA that don't validate unless I extract all of the intermediate certificates from a Windows machine and install them locally.

**Comment by mattcaswell** [comment] 2018-04-23 08:38
Yes, that does seem fairly reasonable.

Fix in #6052.

**Comment by mattcaswell** [comment] 2018-04-24 08:26
Fixed by #6052. Closing.

**Closed by mattcaswell** 2018-04-24 08:26 UTC
