### ISSUE TITLE
Engine not initialized on 'load_pubkey'

### ISSUE THREAD

**Issue by nakedible-p** [openssl/openssl#10702] opened 2019-12-26 02:15 UTC
I am trying to use an engine for `openssl pkeyutl -verify`. If I load a private key from the engine, there are no problems, but if I try to load a public key from the engine, I get the following error:

```
cannot load Public Key from engine
140467335861440:error:26097075:engine routines:ENGINE_load_public_key:not initialised:../crypto/engine/eng_pkey.c:97:
unable to load Public Key
pkeyutl: Error initializing context
```

Looking at the source code, the `load_key` function calls `ENGINE_init`:

https://github.com/openssl/openssl/blob/51a7c4b5f2a0b2d0f6bc0c87ec2ee44b9697dc78/apps/lib/apps.c#L587-L596

But `load_pubkey` function does not:

https://github.com/openssl/openssl/blob/51a7c4b5f2a0b2d0f6bc0c87ec2ee44b9697dc78/apps/lib/apps.c#L657-L662

If there is some rationale behind this, I am not understanding it.

This bug might not be visible so often as most engines also export other functionality (such as random generation or rsa encryption), which when registered will cause the engine to be referenced during loading, which removes the error.

Patch is trivial - I can write it if desired.

**Comment by t8m** [comment] 2021-07-21 16:01
Closing as duplicate of #13797

**Closed by t8m** 2021-07-21 16:01 UTC
Labels: issue: bug report
