### ISSUE TITLE
cast discards ‘const’ warning from SSL_CTX_set1_groups_list() 

### ISSUE THREAD

**Issue by Hal-Murray** [openssl/openssl#22535] opened 2023-10-27 11:07 UTC
That's from 3.2.0-beta1 on Fedora 38
gcc (GCC) 13.2.1 20231011 (Red Hat 13.2.1-4)

```
In file included from ../../include/nts2.h:15,
                 from ../../ntpd/nts.c:30:
../../ntpd/nts.c: In function ‘nts_load_ecdhcurves’:
/usr/local/ssl/include/openssl/ssl.h:1519:53: warning: cast discards ‘const’ qualifier from pointer target type [-Wcast-qual]
 1519 |         SSL_CTX_ctrl(ctx,SSL_CTRL_SET_GROUPS_LIST,0,(char *)(s))
      |                                                     ^
../../ntpd/nts.c:212:26: note: in expansion of macro ‘SSL_CTX_set1_groups_list’
  212 |                 if (1 != SSL_CTX_set1_groups_list(ctx, ntsconfig.tlsecdhcurves)) {
      |                          ^~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by paulidale** [comment] 2023-10-28 03:30
The cast is required and the call doesn't modify what's passed, so it's a false positive in a sense.
Still, it should be fixed.

**Comment by t8m** [comment] 2023-10-30 10:14
I do not understand where the bug is.

The function (which is implemented as macro) is documented as: `int SSL_CTX_set1_groups_list(SSL_CTX *ctx, char *list);`

There was no change in the implementation since openssl-3.0 so this is no regression on master or 3.2.

This looks like a ntpd bug/problem if any at all?

**Comment by tom-cosgrove-arm** [comment] 2023-10-30 10:17
I guess the question is "does `char *list` need to NOT be `const`"? It's often a code smell (lack of const-correctness) when const-ness has to be cast away. If `SSL_CTX_set1_groups_list()` just takes a copy of it's `list` argument, it should have been `const`.

**Comment by t8m** [comment] 2023-10-30 10:38
But this function is actually macro that calls SSL_CTX_ctrl() and you need to cast away the const for the ctrl() call anyway.

**Comment by paulidale** [comment] 2023-10-30 10:41
I'm not sure if we can fix this in the code.  Disabling the warning seems like the best option.

**Comment by t8m** [comment] 2023-10-30 10:45
This is on building a third party application - we cannot do anything here.

**Comment by mattcaswell** [comment] 2024-01-31 11:11
Closing since this is marked as resolved.

**Closed by mattcaswell** 2024-01-31 11:11 UTC
Labels: branch: master, resolved: not a bug, triaged: bug, branch: 3.2
