### ISSUE TITLE
[rt.openssl.org #3970] openssl win64 "smime -encrypt" can not handle big files

### ISSUE THREAD

**Issue by richsalz** [openssl/openssl#2433] opened 2017-02-02 20:30 UTC
Migrated from [rt.openssl.org#3970](https://rt.openssl.org/Ticket/Display.html?id=3970) (status was 'open')

Requestors:
* hotguest1@hotmail.com

From hotguest1@hotmail.com on 2015-07-30 16:10:14:
```
This affects only openssl windows 64-bit binary, not openssl windows 32-bit binary.

OS: Windows 64-bit
OpenSSL Version: 1.0.2d 64 bit ( https://slproweb.com/products/Win32OpenSSL.html )

How to reproduce:
using command smime -encrypt with a big file, say 350 MB

openssl smime -encrypt -binary -in file.bin -aes-256-cbc -outform DER -out file.bin.encrypted cer.crt

The output file is decreased in size and, of course, broken.
Changing algorithms results exactly the same decreased output size.

Regards,
Suchyan.

 		 	   		  
```

From steve@openssl.org on 2015-07-30 17:59:09:
```
On Thu Jul 30 16:10:14 2015, hotguest1@hotmail.com wrote:
> This affects only openssl windows 64-bit binary, not openssl windows
> 32-bit binary.
>
> OS: Windows 64-bit
> OpenSSL Version: 1.0.2d 64 bit (
> https://slproweb.com/products/Win32OpenSSL.html )
>
> How to reproduce:
> using command smime -encrypt with a big file, say 350 MB
>
> openssl smime -encrypt -binary -in file.bin -aes-256-cbc -outform DER
> -out file.bin.encrypted cer.crt
>
> The output file is decreased in size and, of course, broken.
> Changing algorithms results exactly the same decreased output size.
>

Can't reproduce it here with latest 1.0.2 stable branch and Win64. Tried it on
a 600MB file and no problems.

Steve.
-- 
Dr Stephen N. Henson. OpenSSL project core developer.
Commercial tech support now available see: http://www.openssl.org
```

**Comment by mattcaswell** [comment] 2018-01-19 17:21
Steve was unable to reproduce. Closing.

**Closed by mattcaswell** 2018-01-19 17:21 UTC
