### ISSUE TITLE
Failed to 'perl Configure VC-WIN32' and 'nmake clean' after revision 3f4e8d6 on Windows

### ISSUE THREAD

**Issue by spacelg** [openssl/openssl#8478] opened 2019-03-14 07:24 UTC
Environment:
VS 2017 + Windows Server 2016

Issue description:
I tried to build openssl using VS2017 on Windows Server 2016. We found that openssl failed to 'perl Configure VC-WIN32' and 'nmake clean' after revision 3f4e8d6. Could you please help take a look at this? Thanks in advance!

Repro steps:
1. git clone https://github.com/openssl/openssl D:\openssl\src
2. cd D:\openssl\src
3. perl Configure VC-WIN32
4. nmake clean

Expected result:
'perl Configure VC-WIN32' and 'nmake clean' fine.

Actual result:
D:\OpenSSL\src>perl Configure VC-WIN32
Undefined subroutine &Text::Template::GEN0::catpath called at template line 190.
 in Configurations\common.tmpl, fragment starting at line 182
D:\OpenSSL\src>nmake clean
NMAKE : fatal error U1073: don't know how to make 'clean'
Stop.

[log_x86_build_1.log](https://github.com/openssl/openssl/files/2965120/log_x86_build_1.log)

**Comment by levitte** [comment] 2019-03-14 09:05
Duplicate of #8467

**Comment by levitte** [comment] 2019-03-14 09:06
Fix is in #8468

**Comment by mattcaswell** [comment] 2019-11-05 14:33
Fixed by #8468.

**Closed by mattcaswell** 2019-11-05 14:33 UTC
Labels: resolved: fixed, triaged: bug
