### ISSUE TITLE
The function OSSL_PROVIDER_unload() does not call the teardown function

### ISSUE THREAD

**Issue by Dinh-Cong-Trang-TRAN** [openssl/openssl#18991] opened 2022-08-12 17:33 UTC
This issue affected openssl 3.0.0 to openssl 3.0.5.

This is a simple provider which includes a teardown function to test the function `OSSL_PROVIDER_load()` and the function `OSSL_PROVIDER_unload()`

```
#include <stdio.h>
#include <openssl/core_dispatch.h>
#include <openssl/provider.h>
#include <openssl/crypto.h>

static void simple_teardown(void *ptr)
{
    fprintf(stdout, "%s was called\n", __func__);
    OSSL_LIB_CTX_free(ptr);
}

static const OSSL_DISPATCH simple_method[] = {
    { OSSL_FUNC_PROVIDER_TEARDOWN, (void (*)(void))simple_teardown},
    { 0, NULL }
};

int OSSL_provider_init(const OSSL_CORE_HANDLE *handle,
                                  const OSSL_DISPATCH *in,
                                  const OSSL_DISPATCH **out, void **provctx)
{
    if (!(*provctx = OSSL_LIB_CTX_new()))
        return 0;
    *out = simple_method;
    return 1;
}

OSSL_PROVIDER *simple_start(OSSL_LIB_CTX *libctx)
{
    OSSL_PROVIDER *p;

    if (!(p = OSSL_PROVIDER_load(libctx, "simple")))
        return NULL;
    return p;
}
```

When calling the function `OSSL_PROVIDER_load()`, a new provider will be created by the function `provider_new()`, it sets the value of `prov->refcnt` to `1`.

```
    prov->refcnt = 1; /* 1 One reference to be returned */
```

In the function `ossl_provider_add_to_store()`, the following code block increase the value of `prov->refcnt` to `2`.

```
    if (actualprov != NULL) {
        if (!ossl_provider_up_ref(actualtmp)) {
            ERR_raise(ERR_LIB_CRYPTO, ERR_R_MALLOC_FAILURE);
            actualtmp = NULL;
            return 0;
        }
        *actualprov = actualtmp;
    }
```

Now when calling the function `OSSL_PROVIDER_unload()`, the function `ossl_provider_teardown()` will not be called because the value of `prov->refcnt` is `1`.

```
        // value of prov->refcnt is 2 
        CRYPTO_DOWN_REF(&prov->refcnt, &ref, prov->refcnt_lock);

        /*
         * When the refcount drops to zero, we clean up the provider.
         * Note that this also does teardown, which may seem late,
         * considering that init happens on first activation.  However,
         * there may be other structures hanging on to the provider after
         * the last deactivation and may therefore need full access to the
         * provider's services.  Therefore, we deinit late.
         */
        // value of ref is 1
        if (ref == 0) {
            if (prov->flag_initialized) {
                ossl_provider_teardown(prov); // this function will not be called.
                // ... 
        }
```

**Comment by mattcaswell** [comment] 2022-08-15 08:20
This is correct. The `OSSL_PROVIDER_unload` function will make the provider unavailable for use in the sense that you will no longer be able to fetch algorithms from the provider. It does not run the teardown function (despite what the documentation says):

> OSSL_PROVIDER_unload() unloads the given provider. For a provider added with OSSL_PROVIDER_add_builtin(), this simply runs its teardown function.

However, algorithms that you have already fetched remain usable. As you point out the internal store also retains a reference to the algorithm.

It all works out fine in the end because when the libctx gets freed, the internal store gets freed and so any remaining references to the provider are removed and the provider teardown function does eventually get freed.

I don't consider this a bug (except I suppose in the documentation) although it is perhaps slightly surprising.

**Comment by levitte** [comment] 2022-08-15 11:00
We could document that the teardown call is delayed to the very end...  but otherwise, I agree with @mattcaswell, this is not a bug

**Comment by Dinh-Cong-Trang-TRAN** [comment] 2022-08-15 14:53
Thanks for your comments, I have tested it and the teardown function will be called when the libctx get freeed.

```
    OSSL_LIB_CTX *libctx = OSSL_LIB_CTX_new();
    OSSL_PROVIDER *prov = OSSL_PROVIDER_load(libctx, "legacy");
    OSSL_PROVIDER_unload(prov); // teardown function will not be called yet
    OSSL_LIB_CTX_free(libctx); // teardown function will be call here
```

For the providers that loaded with the function `OSSL_PROVIDER_add_builtin()`, the function `OSSL_PROVIDER_unload()` works as expected, it called the teardown function.

**Comment by paulidale** [comment] 2022-08-16 00:06
I find the current behaviour quite odd.  I've asked for a provider to be unloaded and it isn't, potentially for a long time.

**Comment by t8m** [comment] 2022-08-16 12:52
> I find the current behaviour quite odd. I've asked for a provider to be unloaded and it isn't, potentially for a long time.

If we made it the other way around, existing operations with that provider in progress would stop working at the point of unload. That would be IMO also confusing, but differently.

**Comment by paulidale** [comment] 2022-08-16 22:09
I disagree that that would be confusing.  I've deliberately unloaded the provider, why should operations it supplied continue to work?  That's the odd part IMO.

**Comment by mattcaswell** [comment] 2024-01-31 11:04
Closing since this is marked as resolved.

**Closed by mattcaswell** 2024-01-31 11:04 UTC
Labels: branch: master, resolved: not a bug, triaged: documentation, branch: 3.0, branch: 3.1, branch: 3.2
