### ISSUE TITLE
Build issue with llvm mingw for x86_64-w64-mingw32 target

### ISSUE THREAD

**Issue by Biswa96** [openssl/openssl#13414] opened 2020-11-15 05:35 UTC
* Build Platform: ArchLinux x86_64
* Compiler target: x86_64-w64-mingw32 i.e. Windows x86_64
* Command:

```sh
git clone --depth=1 https://github.com/openssl/openssl.git
cd openssl
git submodule update --init --recursive
./Configure \
mingw64 \
--cross-compile-prefix=x86_64-w64-mingw32-
make
```

* [mingw-w64-gcc] cross compiler builds openssl for x86_64-w64-mingw32 target
without compiler error (except some integer size and format specifier warnings).

* But the things get dark when compiled with [llvm mingw] toolchain. Here are
the two errors and my temporary fixes:

  - `llvm-rc: Error parsing file: expected ',', got PRODUCTVERSION`:
Add an extra comma & zero to the `FILEVERSION` and `PRODUCTVERSION` fields in
libcrypto.rc, libssl.rc, apps/openssl.rc files.
Because according to [VERSIONINFO], those values should be four 16-bit integers.

  - `lld-link: error: ./libcrypto.dll.a: unknown file type`:
The libcrypto.dll.a becomes a symbolic link to libcrypto-3-x64.dll. So, regenerate
dynamic export libraries from those DLLs with these commands:

```sh
rm libcrypto.dll.a; x86_64-w64-mingw32-dlltool -D libcrypto-3-x64.dll -d libcrypto.def -l libcrypto.dll.a
rm libssl.dll.a; x86_64-w64-mingw32-dlltool -D libssl-3-x64.dll -d libssl.def -l libssl.dll.a
```

There is no error in source code, maybe the issue in the build system. I would
be happy to provide any further information, if required.

[mingw-w64-gcc]: https://www.archlinux.org/packages/community/x86_64/mingw-w64-gcc/
[llvm mingw]: https://github.com/mstorsjo/llvm-mingw
[VERSIONINFO]: https://docs.microsoft.com/en-us/windows/win32/menurc/versioninfo-resource

**Comment by levitte** [comment] 2020-11-15 06:20
I had a quick look at llvm-mingw, and from the known issues in its description, it looks like it's still maturing. This might simply be a bit too early.

That being said, I'm curious. Could you tell us  how you configured openssl to build with llvm-mingw?

**Comment by Biswa96** [comment] 2020-11-15 06:24
> it looks like it's still maturing.

Maturing what? I am able to build some projects with it. VLC devs are using it for Windows AArch64 builds for many years.

> Could you tell us how you configured openssl to build with llvm-mingw?

1. Download llvm-mingw-*-ucrt-ubuntu-18.04.tar.xz file from [llvm mingw release page][1].
2. Exact it anywhere.
3. Add the directory in `$PATH`.

[1]: https://github.com/mstorsjo/llvm-mingw/releases

**Comment by levitte** [comment] 2020-11-15 06:34
> Could you tell us how you configured openssl to build with llvm-mingw?

With that, I was trying to ask what the configuration command line for openssl was, to build it using llvm-mingw. Please do `./configdata.pm -c` and paste the output here.

**Comment by Biswa96** [comment] 2020-11-15 06:54
`./configdata.pm -c` shows:

```
Command line (with current working directory = .):

    /usr/bin/perl ./Configure mingw64 --cross-compile-prefix=x86_64-w64-mingw32-

Perl information:

    /usr/bin/perl
    5.32.0 for x86_64-linux-thread-multi
```

**Comment by levitte** [comment] 2020-11-15 09:00
I at least have a fix for the VERSIONINFO problem, see #13415

**Comment by mstorsjo** [comment] 2020-11-15 10:20
(Llvm-mingw maintainer here)

> I had a quick look at llvm-mingw, and from the known issues in its description, it looks like it's still maturing. This might simply be a bit too early.

It's mature in the sense that it can build a great deal of existing projects, for a couple years now already. But there are clearly cases of missing features that some projects use. In some cases, it's easier to just adjust projects to use the features that llvm-mingw does support instead of relying on more complex features that are harder to implement, but time permitting, I also try to implement some of the missing features, at least the more doable ones.

For the rc file, this issue is already fixed in upstream llvm-rc in September, due to be released next year. But I guess making openssl produce the canonical format doesn't hurt either.

The fix for using dlltool seems a bit roundabout; the proper import library can usually be generated when linking the dll by just passing the `-Wl,--out-implib,libmylib.dll.a` option instead.

I might be able to try out making a patch for that later, if someone else doesn't beat me to it.

**Comment by levitte** [comment] 2020-11-15 21:26
> the proper import library can usually be generated when linking the dll by just passing the `-Wl,--out-implib,libmylib.dll.a` option instead.

Our builds should do that, but `-Wl,--out-implib=libmylib.dll.a`...  I trust that small syntax difference doesn't matter...

**Comment by mstorsjo** [comment] 2020-11-15 21:29
> > the proper import library can usually be generated when linking the dll by just passing the `-Wl,--out-implib,libmylib.dll.a` option instead.
> 
> Our builds should do that, but `-Wl,--out-implib=libmylib.dll.a`... I trust that small syntax difference doesn't matter...

Indeed, the difference between those shouldn't matter.

Ok, so then the question remains why @Biswa96 reported that "The libcrypto.dll.a becomes a symbolic link to libcrypto-3-x64.dll." - if the libcrypto.dll.a that this refers to would be the one produced by the `--out-implib` option, the dlltool invocation that he suggests shouldn't be needed.

**Comment by Biswa96** [comment] 2020-11-16 04:31
Some output related to that symlink:

```sh
$ ls libcrypto*
libcrypto-3-x64.dll libcrypto.a libcrypto.dll.a libcrypto-shlib-libcrypto.res.obj libcrypto-3-x64.dll.args libcrypto.def libcrypto.rc
$ file libcrypto.dll.a
libcrypto.dll.a: symbolic link to libcrypto-3-x64.dll
```

**Comment by levitte** [comment] 2020-11-17 12:20
Reopened, because #13415 was only a partial fix, github autoclosed too soon

**Comment by Biswa96** [comment] 2020-11-24 18:32
Speaking of llvm-mingw, I was testing some configuration for Windows ARM64 (aarch64-w64-mingw32) target with the following diff and it builds fine. Is is possible to add a target like the following in main configuration file?

```diff
diff --git a/Configurations/10-main.conf b/Configurations/10-main.conf
index d7580bf3..d205823e 100644
--- a/Configurations/10-main.conf
+++ b/Configurations/10-main.conf
@@ -1474,6 +1474,12 @@ my %targets = (
         shared_rcflag    => "--target=pe-x86-64",
         multilib         => "64",
     },
+    "mingw-arm64" => {
+        inherit_from     => [ "mingw-common" ],
+        asm_arch         => 'aarch64_asm',
+        bn_ops           => add("SIXTY_FOUR_BIT"),
+        perlasm_scheme   => "mingw64",
+    },
 
 #### UEFI
     "UEFI" => {
```

**Comment by levitte** [comment] 2020-11-26 18:55
Please don't pile up more stuff in the one and the same issue.
(that added config target looks fine to me, please make a PR for it)

**Comment by mstorsjo** [comment] 2021-01-14 15:49
I finally had a look at the remaining issue here - it looks like the case where the proper import library is replaced with a symlink to the actual DLL comes from the unix generic logic for `if ($simple ne $full)`, where they're symlinked.

This patch locally fixes the build with the supplied command line for me:
```diff
diff --git a/Configurations/unix-Makefile.tmpl b/Configurations/unix-Makefile.tmpl
index 342e46d2..445ec700 100644
--- a/Configurations/unix-Makefile.tmpl
+++ b/Configurations/unix-Makefile.tmpl
@@ -1495,6 +1495,12 @@ EOF
 $simple: $full
        rm -f $simple && \\
        \$(AR) r $simple $full
+EOF
+          } elsif (windowsdll()) {
+              # On windows, the import lib is created implicitly as a side
+              # effect when generating the actual shared library.
+              $recipe .= <<"EOF";
+$simple: $full
 EOF
           } else {
               $recipe .= <<"EOF";
```

If that looks sensible, I can make a PR with that change.

**Comment by levitte** [comment] 2021-01-15 11:04
I'm seeing that diff, and while functionally exactly right, it makes me realise that there's a lot of unclarity surrounding the "simple" shared library name (import libraries seem to be anything but...).  Inspired by this, I'm preparing a PR that separates "simple" from "import", and hopefully makes things generally clearer.

**Comment by levitte** [comment] 2021-01-15 11:27
My proposal for the remaining issue is in #13875, please try it out.

**Comment by mstorsjo** [comment] 2021-01-15 12:07
> My proposal for the remaining issue is in #13875, please try it out.

Thanks! I can confirm that it works with that PR.

**Closed** 2021-01-21 18:49 UTC
Labels: triaged: OTC evaluated, triaged: bug
