### ISSUE TITLE
boringssl tests failing

### ISSUE THREAD

**Issue by kroeckx** [openssl/openssl#13556] opened 2020-11-28 09:38 UTC
From the log: https://travis-ci.com/github/openssl/openssl/jobs/450013647
```
go test: PASSED (ECDSAKeyUsage-TLS12)
go test: 
go test: exit status 1
go test: FAIL	_/home/travis/build/openssl/openssl/boringssl/ssl/test/runner	30.836s
../../../../util/wrap.pl go test -shim-path ../../../../test/ossl_shim/ossl_shim -shim-config ../../../../test/ossl_shim/ossl_config.json -pipe -allow-unimplemented => 1
not ok 1 - running BoringSSL tests
# ------------------------------------------------------------------------------
#   Failed test 'running BoringSSL tests'
#   at test/recipes/95-test_external_boringssl.t line 24.
# Looks like you failed 1 test of 1.95-test_external_boringssl.t .... 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/1 subtests 
```

**Comment by kaduk** [comment] 2020-11-29 00:40
Again?  I though we "just" fixed them in #13251. Sigh.

**Comment by kaduk** [comment] 2020-11-29 00:43
Looks like it's unhappy about DH key shares:

```
go test: FAILED (VersionNegotiation-Server-SSL3-SSL3)
go test: unexpected failure: local error 'remote error: handshake failure', child error 'exit status 1', stdout:
go test: 
go test: stderr:
go test: resumption check failed
go test: Connection 1 failed.
go test: 804BB2BD3F7F0000:error:02800066:Diffie-Hellman routines:dh_buf2key:invalid public key:crypto/dh/dh_key.c:364:
go test: 804BB2BD3F7F0000:error:0A0C0103:SSL routines:tls_process_cke_dhe:internal error:ssl/statem/statem_srvr.c:2994:
go test: 
go test: 
```

(There's a few others also involving "invalid" DH public keys.)

**Comment by kaduk** [comment] 2020-11-29 02:27
bisect fingers 936d5657680bba3315aec6d7cdc04ea8cab9050e as the first bad version.
Perhaps we are no longer stripping padding from `data`?

**Comment by kroeckx** [comment] 2020-11-29 09:35
We seem to be enforcing that it is padded now, which the TLS 1.3 RFC says to do (without a MUST). I can't find such text in the TLS 1.2 RFC. I think the current code is applying that check to all SSL/TLS versions.

**Comment by kroeckx** [comment] 2020-11-29 09:38
Also see #12331 and #1320

**Comment by kaduk** [comment] 2020-11-30 00:31
> We seem to be enforcing that it is padded now, which the TLS 1.3 RFC says to do (without a MUST). I can't find such text in the TLS 1.2 RFC. I think the current code is applying that check to all SSL/TLS versions.

I'm pretty sure there is no such text in  RFC 5246, and this is an instance of TLS 1.3 trying to make things more consistent/simpler.  But, that does mean that when we support both versions we have to make the check conditional on the version.

I think that even without the MUST, RFC 8446 is quite clear that an un-padded key share is invalid and thus needs to be rejected.

**Comment by mattcaswell** [comment] 2020-11-30 10:09
> I'm pretty sure there is no such text in RFC 5246, and this is an instance of TLS 1.3 trying to make things more consistent/simpler. But, that does mean that when we support both versions we have to make the check conditional on the version.

Agreed.

**Comment by paveljanik** [comment] 2021-02-04 20:45
RFC 8446 explicitly says:

7.4. (EC)DHE Shared Secret Calculation

7.4.1. Finite Field Diffie-Hellman

For finite field groups, a conventional Diffie-Hellman [DH76] 
computation is performed. The negotiated key (Z) is converted to a 
byte string by encoding in big-endian form and left-padded with zeros 
up to the size of the prime. This byte string is used as the shared 
secret in the key schedule as specified above.

**Note that this construction differs from previous versions of TLS 
which removed leading zeros.**

The last sentence means that in TLSv1.2 leading zeros are removed and in TLSv1.3, leading zeros are left-padded.

**Comment by kaduk** [comment] 2021-02-22 17:45
Adding another data point/update; on current master (f16f363a85baa6338744e20671c5a227844f2847) I still see:

```
go test: FAILED (DHPublicValuePadded)
go test: unexpected failure: local error 'remote error: internal error', child error 'exit status 1', stdout:
go test: 
go test: stderr:
go test: resumption check failed
go test: Connection 1 failed.
go test: 802BAF469B7F0000:error:02800066:Diffie-Hellman routines:dh_buf2key:invalid public key:crypto/dh/dh_key.c:392:
go test: 802BAF469B7F0000:error:0A0C0103:SSL routines:tls_process_cke_dhe:internal error:ssl/statem/statem_srvr.c:2975:
go test: 
```

**Comment by t8m** [comment] 2021-03-24 08:56
Closing as duplicate of #14424

**Closed by t8m** 2021-03-24 08:56 UTC
Labels: branch: master, tmp: HIGH, triaged: OTC evaluated, triaged: bug
