### ISSUE TITLE
OpenSSL allows the client to present RSA certificates with the key usage keyAgreement only.

### ISSUE THREAD

**Issue by Immortalem** [openssl/openssl#12141] opened 2020-06-13 13:29 UTC
### Affected Versions
1.1.1g, 1.0.2u

### Setup
OpenSSL has been compiled from source in an alpine docker container. The following excerpt of the used docker file shows the build related commands:
```
RUN ./config --prefix=/build/ --openssldir=/build/ no-async 
RUN make -s && make install_sw -s
```
After building it the respective OpenSSL version and required libraries have been copied into an minimal docker container (from scratch).

The server is later started using the following command:
`openssl s_server -accept 4433 -Verify 100 -cert /cert/inputCerts/rootv3.pem -key /cert/keys/rootv3.pem -CAfile /cert/inputCerts/root.pem -verify_return_error`

All files mentioned in this report (certificates, keys, etc.) have been included in the attached zip archive.

### Issue
OpenSSL allows the client to present RSA certificates with the key usage set to keyAgreement only.
As there is no key agreement algorithm that uses RSA keys this certificate may not be used at all.

### Reproduction
Uses OpenSSL 1.1.1 client on Ubuntu 18.04.
Connect to the started server using the following command:
`openssl s_client -connect localhost:4433 -cert ROOTv3_CAv3_LEAF_RSAv3_KeyUsageKeyAgreement__leaf_certificate1.pem -key rsakey_2.pem -CAfile ROOTv3_CAv3_LEAF_RSAv3_KeyUsageKeyAgreement__ca_certificate1.pem`

### Expected Result
OpenSSL should reject the certificate since it may not be used to create/verify signatures.

### Actual Result
OpenSSL happily accepts the certificate and proceeds with the handshake.

### Attachment
[opensslRSAKeyAgreement.zip](https://github.com/openssl/openssl/files/4774658/opensslRSAKeyAgreement.zip)

**Comment by DDvO** [comment] 2020-08-26 07:11
Bug confirmed. OpenSSL is generally pretty sloppy on checking key usages, at least for SSL/TLS use.
See the new bug report #12721 covering this report and its duplicate #12140.

**Comment by nhorman** [comment] 2024-06-13 00:52
Marking as inactive, to be closed at the end of 3.4 dev, barring further input

**Comment by DDvO** [comment] 2024-06-14 05:54
This is a nice example for the generalized issue #12721.

**Comment by nhorman** [comment] 2024-06-14 11:30
Ok @DDvO thats a fair statement, but it seems to me to illustrate the fact that we have #12721 to cover this issue, and (regardless of its closure status), that issue links back here.  So is there any reason that this shouldn't be closed as a duplicate of that?

**Comment by DDvO** [comment] 2024-06-14 11:55
Well, it's not really a duplicate, but a small subset.
As I wrote, it's an example including a test case, so provides nice detail that should be helpful tackling https://github.com/openssl/openssl/issues/12721.

So in order to minimise the number of open issues. I'd suggest copying the OP there, including the attachment,
and then closing this one.

**Comment by nhorman** [comment] 2024-06-14 13:58
@DDvO copy that, good suggestion, thank you!

**Closed** 2024-06-14 13:59 UTC
Labels: branch: master, triaged: bug
