### ISSUE TITLE
Installing RBenv and Ruby on Mac with Apple M1 Machine

### ISSUE THREAD

**Issue by anasosadances** [openssl/openssl#18845] opened 2022-07-22 00:47 UTC
I saw this answered in another post but the answer did not help me unfortunately. I am trying to install on my terminal
a command-line tool called RBenv, for Ruby using the following command : 

```
RUBY_CFLAGS="-Wno-error=implicit-function-declaration" rbenv install 2.6.6
```
However I am getting the following error message: 

```
BUILD FAILED (macOS 12.4 using ruby-build 20220713)

Inspect or clean up the working tree at /var/folders/n6/1yg6j3z56r5_dqkq48d2gy0h0000gn/T/ruby-build.20220721174039.33183.vsvD3U
Results logged to /var/folders/n6/1yg6j3z56r5_dqkq48d2gy0h0000gn/T/ruby-build.20220721174039.33183.log

Last 10 log lines:
clang  -Iinclude -arch arm64 -O3 -Wall -D_REENTRANT -DZLIB -DZLIB_SHARED -DNDEBUG -I/Users/anasosa/.rbenv/versions/2.6.6/include  -MMD -MF test/wpackettest.d.tmp -MT test/wpackettest.o -c -o test/wpackettest.o test/wpackettest.c
clang  -Iinclude -arch arm64 -O3 -Wall -D_REENTRANT -DZLIB -DZLIB_SHARED -DNDEBUG -I/Users/anasosa/.rbenv/versions/2.6.6/include  -MMD -MF test/x509_check_cert_pkey_test.d.tmp -MT test/x509_check_cert_pkey_test.o -c -o test/x509_check_cert_pkey_test.o test/x509_check_cert_pkey_test.c
test/v3ext.c:201:24: error: implicitly declaring library function 'memcmp' with type 'int (const void *, const void *, unsigned long)' [-Werror,-Wimplicit-function-declaration]
        if (!TEST_true(memcmp(ip1->data, ip2->data, ip1->length) <= 0))
                       ^
test/v3ext.c:201:24: note: include the header <string.h> or explicitly provide a declaration for 'memcmp'
1 error generated.
make[1]: *** [test/v3ext.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [all] Error 2
xxxxx@xxx-MacBook-Pro ~ % 
````

Any idea how to fix this? I read this is a common issue however I am not sure what to do since I tried everything that I saw online. 

ps: This is my first post, thank you for your patience :)

**Comment by xtkoba** [comment] 2022-07-22 08:30
As the name suggests `RUBY_CFLAGS` is used for building Ruby, not for OpenSSL. You could use another env var, if any.

For OpenSSL's side, this issue is a duplicate of #18720.

**Comment by t8m** [comment] 2022-07-22 10:06
Duplicate of https://github.com/openssl/openssl/issues/18720

**Closed by t8m** 2022-07-22 10:06 UTC
Labels: issue: bug report
