### ISSUE TITLE
PEM_read_bio_X509 returns changes

### ISSUE THREAD

**Issue by timgeo4ever** [openssl/openssl#13779] opened 2021-01-05 06:19 UTC
Recently I updated my openssl version from 1.0.1e to 1.1.0d in my iOS project, when I read certificate and get pubkey as before, got a difference result, there is my code snippets
```
NSString *certStr = @"-----BEGIN CERTIFICATE-----
MIIDYjCCAkqgAwIBAgIBATANBgkqhkiG9w0BAQUFADCBhTEvMC0GA1UEAx4mTgpt
d1knZnphZ1nUYlhnDVKhVmhoOYvBTmYAKAAyADAANAA4ACkxCzAJBgNVBAYTAkNO
MQ8wDQYDVQQIHgZOCm13XgIxDzANBgNVBAceBk4KbXdeAjEjMCEGA1UECh4aTgpt
d1knZnphZ39RftxigGcvZwmWUFFsU/gwHhcNMTIwMjA4MDgwNzA5WhcNMjIwMjA1
MDgwNzA5WjBjMSEwHwYDVQQDHhhZJ2Z6YWdtS4vVWdRiWGcNUqFWaIvBTmYxCzAJ
BgNVBAYTAkNOMQ0wCwYDVQQIHgROCm13MQ0wCwYDVQQHHgROCm13MRMwEQYDVQQK
HgpZJ2Z6YWdtS4vVMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuv78
f+ztFy6zC5hFeGCH+b+/uDCS5HZdjGBVF+b6QnwuzdkooX1pCX+1Pt/60lt08a3b
PGLngh/VTVAaE70IjsqT7OL4ZgaNfDre6FJODxNBnqAHBjr005Fie1LpnVyrewqO
mtrHBsoDdQI6U93ck3jaL0eFrE2kCwKo0VnLrE7HRDPSokaIv96dUk3WoVQ7uoDi
ANVR4pelR9GHpFOc0n6ccCKbZ8fWqNx8NHdxnj1kOymDwKSyuKwyfyXy25Bp8KRr
jIRzt49hXhxYFAN/4kv5WYCwa7+HllfiYN/2K7TzsRSWTUeGov6/CmzwkVYeYBhN
l4nV8pgeO+pvCMC3wQIDAQABMA0GCSqGSIb3DQEBBQUAA4IBAQBJwDi10BZ1YXHk
FmGbyVVaueEVKV4CyP/li8dln1f2kJKy/6NA4N4CbLGJwiB9rrr5C5CINpel046L
NGlL0Bph8nvrnDGVq8ti9lZ91/aEhy1LexS/n8JFib5bhn/H6RK7kGGQCptYJYNj
XXxB+WHZiP3/JLHcqgKDi25kMgB0NOPOOJMQW+purrPOKjNrcFomeV70YIxlHHTS
EGtlDGZXGM1Jj3DkArFKMT34AOyGeU8VEO2zyPIHu9SFZeQ5yfgBMdYnhM5YiBsh
soF+1EswMDaaDscP5jD1ge924lUpPsosFZmE+8EAdzLB3cGtE8NDlNI9P68c4q5s
UeEzsbHK
-----END CERTIFICATE-----";

BIO *buffer = BIO_new(BIO_s_mem());
BIO_write(buffer, [certStr UTF8String], strlen([certStr UTF8String]));
    
X509 *cer = PEM_read_bio_X509(buffer, NULL, NULL, NULL);
EVP_PKEY *pubkey = X509_get_pubkey(cer);
```
It works on openssl version 1.0.1e and I can get the correct `pubkey`, but after updated openssl version to 1.1.0d, `pubkey` returns NULL.
Is there any code I should call but I missed?

**Comment by t8m** [comment] 2021-01-05 09:38
Most probably the issue is the missing EOL character at the end of the whole certificate string.
Also I'd recommend moving to openssl 1.1.1i as that is the latest release. The 1.1.0 branch is unsupported.

**Comment by timgeo4ever** [comment] 2021-01-06 01:27
Thanks for your reply.
So how can I fix that? If I want append a EOL character at the end of `certStr`, what character should I use?
And I still do not understand that how can it works on openssl version 1.0.1e

**Comment by t8m** [comment] 2021-01-06 10:32
The last line of the certificate should be:
```
-----END CERTIFICATE-----\n";
```
There were changes in the parsing routine which might be then fixed in later releases.

**Comment by timgeo4ever** [comment] 2021-01-07 02:26
It doesn't work after I append `\n` at the end of cert string.For some other reason, this project can not moving to openssl 1.1.1i.
Is there any other solution can fix that?

**Comment by t-j-h** [comment] 2021-01-07 02:38
Add it to the beginning as well - i.e. @"\n---" etc

**Comment by timgeo4ever** [comment] 2021-01-07 02:47
Add it to the beginning and end doesn't work too

**Closed** 2021-02-02 02:59 UTC
Labels: issue: question
