### ISSUE TITLE
1.1.1q test/v3ext.c fails to compile on MacOS (missing string.h include)

### ISSUE THREAD

**Issue by blackspherefollower** [openssl/openssl#18720] opened 2022-07-05 12:28 UTC
Building using: `./Configure no-shared no-gost darwin64-arm64-cc -g -fPIC -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX11.1.sdk -mmacosx-version-min=11.1` fails with:
```
clang  -Iinclude -arch arm64 -O3 -Wall -g -fPIC -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX11.1.sdk -mmacosx-version-min=11.1 -D_REENTRANT -DNDEBUG  -MMD -MF test/v3ext.d.tmp -MT test/v3ext.o -c -o test/v3ext.o test/v3ext.c
test/v3ext.c:201:24: error: implicitly declaring library function 'memcmp' with type 'int (const void *, const void *, unsigned long)' [-Werror,-Wimplicit-function-declaration]
        if (!TEST_true(memcmp(ip1->data, ip2->data, ip1->length) <= 0))
                       ^
test/v3ext.c:201:24: note: include the header <string.h> or explicitly provide a declaration for 'memcmp'
1 error generated.
make[1]: *** [test/v3ext.o] Error 1
```

Adding `#include <string.h>` to test/v3ext.c resolves the error (other tests already explicitly include string.h)

**Comment by baentsch** [comment] 2022-07-05 12:55
Also hit this bug. Further confirmed via CI: https://github.com/openssl/openssl/runs/7190875851?check_suite_focus=true

**Comment by rsbeckerca** [comment] 2022-07-06 12:35
I encountered this on NonStop also, but the case was open by the time I got to it. Worked around it in my case. Will deal with the conflict at 1.1.1r.

**Comment by skuskusku** [comment] 2022-07-08 18:59
I have stumbled across exactly this problem today as well. I am building openssl for iOS and its arm64 build (and I think the x64 build as well) fails with the exact same error. I am using XCode 12.5.1. The last version I have used before was 1.1.1.n and that worked without any problems.

**Comment by tom-cosgrove-arm** [comment] 2022-07-08 19:10
Yes, it is a genuine issue with `1.1.1q`. A fix has already been committed to the `OpenSSL_1_1_1-stable` branch and should be in the next version of `1.1.1`.

To fix is to add a line `#include <string.h>` at the top of `test/v3ext.c`, if you don't want to use the stable branch or wait for the next `1.1.1` release.

**Comment by Tioneb12** [comment] 2022-07-10 21:09
How can I do, to install this patch ?

**Comment by skuskusku** [comment] 2022-07-11 13:14
My patch looks like this and I apply it in my build script with `patch -u test/v3ext.c v3ext.c.patch` in case this helps anybody:

> diff -u bad/v3ext.c good/v3ext.c
> --- bad/v3ext.c	2022-07-05 11:08:33.000000000 +0200
> +++ good/v3ext.c	2022-07-09 13:04:28.449762000 +0200
> @@ -8,6 +8,7 @@
>   */
>  
>  #include <stdio.h>
> +#include <string.h>
>  #include <openssl/x509.h>
>  #include <openssl/x509v3.h>
>  #include <openssl/pem.h>

**Comment by nrjshka** [comment] 2022-07-11 13:44
Having this issue now:(

**Comment by MiralDesai** [comment] 2022-07-11 14:56
I think for rbenv users all we can do is wait, since it attempts to download a new version everytime you run a `install` command. Correct me if I'm wrong but that's what I've noticed at least.

Four downloads of the same version, once for each attempt.

```
ruby-build.20220711152759.90203.iUixfj/openssl-1.1.1q/test/v3ext.c
ruby-build.20220711152259.75171.IpsEZO/openssl-1.1.1q/test/v3ext.c
ruby-build.20220711151859.60116.1Coe7H/openssl-1.1.1q/test/v3ext.c
ruby-build.20220711151540.44657.nTmFzb/openssl-1.1.1q/test/v3ext.c
```

**Comment by mamadaev** [comment] 2022-07-11 15:40
Found a workaround [here](https://dev.to/yasuhiron777/install-2x-3x-version-of-ruby-via-rbenv-on-m1-mac-3okn), helped me

**Comment by MaxiUstria** [comment] 2022-07-11 16:09
> I was trying to install `rbenv install 2.7.6`. Having this issue now:(
> 
> ```
> rbenv install 2.7.6                        
> Downloading openssl-1.1.1q.tar.gz...
> -> https://dqw8nmjcqpjn7.cloudfront.net/d7939ce614029cdff0b6c20f0e2e5703158a489a72b2507b8bd51bf8c8fd10ca
> Installing openssl-1.1.1q...
> 
> BUILD FAILED (macOS 12.0.1 using ruby-build 20220710)
> ...
> 
> test/v3ext.c:201:24: error: implicitly declaring library function 'memcmp' with type 'int (const void *, const void *, unsigned long)' [-Werror,-Wimplicit-function-declaration]
>         if (!TEST_true(memcmp(ip1->data, ip2->data, ip1->length) <= 0))
> ```

I'm facing the same issue unfortunatelly, is there any workaround for rbenv? Or the only option is to wait until the release?

**Comment by eregon** [comment] 2022-07-11 17:58
`OPENSSL_CFLAGS=-Wno-error=implicit-function-declaration` should help for rbenv / ruby-build. (https://github.com/rbenv/ruby-build/issues/1998)

**Comment by austinsmithsprockets** [comment] 2022-07-11 19:49
> > I was trying to install `rbenv install 2.7.6`. Having this issue now:(
> > ```
> > rbenv install 2.7.6                        
> > Downloading openssl-1.1.1q.tar.gz...
> > -> https://dqw8nmjcqpjn7.cloudfront.net/d7939ce614029cdff0b6c20f0e2e5703158a489a72b2507b8bd51bf8c8fd10ca
> > Installing openssl-1.1.1q...
> > 
> > BUILD FAILED (macOS 12.0.1 using ruby-build 20220710)
> > ...
> > 
> > test/v3ext.c:201:24: error: implicitly declaring library function 'memcmp' with type 'int (const void *, const void *, unsigned long)' [-Werror,-Wimplicit-function-declaration]
> >         if (!TEST_true(memcmp(ip1->data, ip2->data, ip1->length) <= 0))
> > ```
> 
> I'm facing the same issue unfortunatelly, is there any workaround for rbenv? Or the only option is to wait until the release?

This tutorial helped me get past the issue, just add this at the end of your .zshrc file after installing openssl-1.1.1

export PATH="/opt/homebrew/opt/openssl@1.1/bin:$PATH"

**Comment by frozen92** [comment] 2022-07-12 10:14
> > I was trying to install `rbenv install 2.7.6`. Having this issue now:(
> > ```
> > rbenv install 2.7.6                        
> > Downloading openssl-1.1.1q.tar.gz...
> > -> https://dqw8nmjcqpjn7.cloudfront.net/d7939ce614029cdff0b6c20f0e2e5703158a489a72b2507b8bd51bf8c8fd10ca
> > Installing openssl-1.1.1q...
> > 
> > BUILD FAILED (macOS 12.0.1 using ruby-build 20220710)
> > ...
> > 
> > test/v3ext.c:201:24: error: implicitly declaring library function 'memcmp' with type 'int (const void *, const void *, unsigned long)' [-Werror,-Wimplicit-function-declaration]
> >         if (!TEST_true(memcmp(ip1->data, ip2->data, ip1->length) <= 0))
> > ```
> 
> I'm facing the same issue unfortunatelly, is there any workaround for rbenv? Or the only option is to wait until the release?

you can download older version from git (v20220630) or use asdf
ASDF_RUBY_BUILD_VERSION=v20220630 asdf install ruby 2.7.6

**Comment by rumnatsf** [comment] 2022-07-12 12:56
Installing previous version and linking it for ruby install helped me
https://github.com/rbenv/ruby-build/discussions/1940#discussioncomment-2663209

**Comment by filakhtov** [comment] 2022-07-14 01:34
Hit this issue as well. What I am also curious about is why is the `test/` code built during the `rbenv` build? Do we even care about test code? Do these tests actually run and check anything or are they just built and forgotten?..

**Comment by paulidale** [comment] 2022-07-14 01:41
`make test` runs them.  Doing this is recommended.

**Comment by rumnatsf** [comment] 2022-07-14 01:41
is there are a param to skip that step?

**Comment by paulidale** [comment] 2022-07-14 02:05
`make apps/openssl` might be enough.

**Comment by tawmoto** [comment] 2022-07-14 08:52
Sorry for a bit offtopic, I want to disable the unit tests compilation, I tried with `perl Configure no-unit-test` but this problematic file still compiles and I got error. Tried also `no-acvp-tests` and that option is not recognized.
Thanks

**Comment by t8m** [comment] 2022-07-14 11:57
> Sorry for a bit offtopic, I want to disable the unit tests compilation because of this problem, I tried with `perl Configure no-unit-test` but this problematic file still compiles and I got error. Tried also `no-acvp-tests` and that option is not recognized.
> Thanks

None of these would help. Does adding `-Wno-error=implicit-function-declaration` to the Configure line help you?

**Comment by tawmoto** [comment] 2022-07-14 12:31
> > Sorry for a bit offtopic, I want to disable the unit tests compilation because of this problem, I tried with `perl Configure no-unit-test` but this problematic file still compiles and I got error. Tried also `no-acvp-tests` and that option is not recognized.
> > Thanks
> 
> None of these would help. Does adding `-Wno-error=implicit-function-declaration` to the Configure line help you?

Seems that `no-tests` worked. :)
Thanks

**Comment by medhatnar** [comment] 2022-07-14 13:53
Where can you find test/v3ext.c ?

**Comment by edmangimelli** [comment] 2022-07-15 21:04
mac asdf peeps that have ended up in this thread: ([openssl 1.1.1q preventing install](https://github.com/asdf-vm/asdf-ruby/issues/285))

Intel:
```
ASDF_RUBY_BUILD_VERSION=v20220630 asdf install ruby SOME_VERSION
```

M1:
```
optflags=-Wno-error=implicit-function-declaration ASDF_RUBY_BUILD_VERSION=v20220630 asdf install ruby SOME_VERSION
```

([thank you](https://github.com/openssl/openssl/issues/18720#issuecomment-1181580006) @frozen92)

**Comment by ritajie** [comment] 2022-07-17 17:13
> To fix is to add a line #include <string.h> at the top of test/v3ext.c

I can't find this `test/v3ext.c` file :(

I encountered this problem when I was executing `asdf install ruby latest`. When I tried to find `test/v3ext.c`, I found that every time I executed `asdf install ruby latest`, a new `test/v3ext.c` was generated. So which file should I modify?

```shell
$ find / -name v3ext.c

/System/Volumes/Data/private/var/folders/tt/vmq4y_dj6xs_xjshzsf3m_j80000gn/T/ruby-build.20220718001148.15460.AmA9rw/openssl-1.1.1q/test/v3ext.c
/System/Volumes/Data/private/var/folders/tt/vmq4y_dj6xs_xjshzsf3m_j80000gn/T/ruby-build.20220718004135.73666.vGijBt/openssl-1.1.1q/test/v3ext.c
/System/Volumes/Data/private/var/folders/tt/vmq4y_dj6xs_xjshzsf3m_j80000gn/T/ruby-build.20220718001840.37943.XZ5EfP/openssl-1.1.1q/test/v3ext.c
/System/Volumes/Data/private/var/folders/tt/vmq4y_dj6xs_xjshzsf3m_j80000gn/T/ruby-build.20220718001821.25683.4OCQR2/openssl-1.1.1q/test/v3ext.c
/System/Volumes/Data/private/var/folders/tt/vmq4y_dj6xs_xjshzsf3m_j80000gn/T/ruby-build.20220718003012.48670.PgZXuW/openssl-1.1.1n/test/v3ext.c
/System/Volumes/Data/private/var/folders/tt/vmq4y_dj6xs_xjshzsf3m_j80000gn/T/ruby-build.20220718004457.85833.pX8QNh/openssl-1.1.1q/test/v3ext.c
/System/Volumes/Data/private/var/folders/tt/vmq4y_dj6xs_xjshzsf3m_j80000gn/T/ruby-build.20220718004740.849.o33pm9/openssl-1.1.1q/test/v3ext.c
/System/Volumes/Data/private/var/folders/tt/vmq4y_dj6xs_xjshzsf3m_j80000gn/T/ruby-build.20220718003043.60906.vlnOZS/openssl-1.1.1n/test/v3ext.c
/private/var/folders/tt/vmq4y_dj6xs_xjshzsf3m_j80000gn/T/ruby-build.20220718001148.15460.AmA9rw/openssl-1.1.1q/test/v3ext.c
/private/var/folders/tt/vmq4y_dj6xs_xjshzsf3m_j80000gn/T/ruby-build.20220718004135.73666.vGijBt/openssl-1.1.1q/test/v3ext.c
/private/var/folders/tt/vmq4y_dj6xs_xjshzsf3m_j80000gn/T/ruby-build.20220718001840.37943.XZ5EfP/openssl-1.1.1q/test/v3ext.c
/private/var/folders/tt/vmq4y_dj6xs_xjshzsf3m_j80000gn/T/ruby-build.20220718001821.25683.4OCQR2/openssl-1.1.1q/test/v3ext.c
/private/var/folders/tt/vmq4y_dj6xs_xjshzsf3m_j80000gn/T/ruby-build.20220718003012.48670.PgZXuW/openssl-1.1.1n/test/v3ext.c
/private/var/folders/tt/vmq4y_dj6xs_xjshzsf3m_j80000gn/T/ruby-build.20220718004457.85833.pX8QNh/openssl-1.1.1q/test/v3ext.c
/private/var/folders/tt/vmq4y_dj6xs_xjshzsf3m_j80000gn/T/ruby-build.20220718004740.849.o33pm9/openssl-1.1.1q/test/v3ext.c
/private/var/folders/tt/vmq4y_dj6xs_xjshzsf3m_j80000gn/T/ruby-build.20220718003043.60906.vlnOZS/openssl-1.1.1n/test/v3ext.c
```

**Comment by chille1987** [comment] 2022-07-21 07:13
`OPENSSL_CFLAGS=-Wno-error=implicit-function-declaration rbenv install 2.7.6` worked for me

**Comment by Teqshark** [comment] 2022-07-22 00:42
Hi I also kept running into this on 'Mac OS X 10.15.7 using ruby-build' I had to set both of the following variables at the same time before the rbenv install 3.0.1 command: 

`OPENSSL_CFLAGS=-Wno-error=implicit-function-declaration` RUBY_CONFIGURE_OPTS=--with-readline-dir="$(brew --prefix readline)" rbenv install 3.0.1`

**Comment by jasonacox** [comment] 2022-08-10 03:03
This is happening with a generic build on MacOS11 x86_64 (darwin64-x86_64-cc) architecture as well (not just arm64):

```
${LDCMD:-cc} -arch x86_64 -O3 -Wall -L. -Wl,-search_paths_first  \
		-o test/uitest test/uitest.o \
		 apps/libapps.a -lssl test/libtestutil.a -lcrypto  
cc  -Iinclude -arch x86_64 -O3 -Wall -D_REENTRANT -DNDEBUG  -MMD -MF test/v3ext.d.tmp -MT test/v3ext.o -c -o test/v3ext.o test/v3ext.c
test/v3ext.c:201:24: error: implicitly declaring library function 'memcmp' with type 'int (const void *, const void *, unsigned long)' [-Werror,-Wimplicit-function-declaration]
        if (!TEST_true(memcmp(ip1->data, ip2->data, ip1->length) <= 0))
                       ^
test/v3ext.c:201:24: note: include the header <string.h> or explicitly provide a declaration for 'memcmp'
1 error generated.
make[1]: *** [test/v3ext.o] Error 1
make: *** [all] Error 2
```

**Comment by tom-cosgrove-arm** [comment] 2022-08-10 07:39
@jasonacox Yes, it is a "generic" bug and not related to the architecture you build for. It causes a build error only on macOS because the clang on macOS implicitly adds `-Wimplicit-function-declaration` in `-Wall`, which it doesn't on Linux. The fix is in the `OpenSSL_1_1_1-stable` branch and will be in the next release of `1.1.1` - in the file `test/v3ext.c`, after the line `#include <stdio.h>` near the top, add a line that says

```
#include <string.h>
```

**Comment by t8m** [comment] 2022-08-24 07:54
This is fixed in git repo, keeping it open until next release to avoid duplicate reports.

**Comment by tom-cosgrove-arm** [comment] 2022-08-24 07:57
@t8m If you're changing the title, it might be an idea to update it to something like `v1.1.1q test/v3ext.c fails to compile on macOS (missing string.h include)` since it's specific to one version of OpenSSL and it also occurs on x86_64 macOS builds

**Comment by pplmx** [comment] 2022-09-05 09:47
Still encountered on openssl-OpenSSL_1_1_1q

**Comment by tom-cosgrove-arm** [comment] 2022-09-05 10:10
@pplmx Yes, the issue is present in the 1.1.1q release, and the 1.1.1q release won't be changed. It is fixed in the `OpenSSL_1_1_1-stable` branch, and the next 1.1.1 release won't have the issue.

**Comment by dktapps** [comment] 2022-11-25 20:52
Is this issue still present in 1.1.1s?

**Comment by tom-cosgrove-arm** [comment] 2022-11-25 21:06
No, this bug is fixed in openssl-1.1.1s.

**Comment by dktapps** [comment] 2022-11-25 21:32
I concur. Then this issue can be closed.

**Closed** 2022-11-26 01:05 UTC
Labels: branch: 1.1.1, triaged: bug, resolved: fixed

**Comment by wheakerd** [comment] 2025-01-07 02:53
This issue also occurs on Fedora 41:
![image](https://github.com/user-attachments/assets/6d15bf3d-fea4-4e4a-bd46-307f2ba34867)
