### ISSUE TITLE
Symlinks for manpages brake when staging

### ISSUE THREAD

**Issue by Sp1l** [openssl/openssl#15443] opened 2021-05-24 19:46 UTC
@9e7a6411708702dd4ad4657636ab346382234437 adds a new way of symlinking, this breaks building when the install is not in the final destination. FreeBSD ports build/install into $WRKDIR. This change symlinks to the absolute path in $WRKDIR rather than relative symlinks in the man3 dir.

**Comment by mattcaswell** [comment] 2021-05-24 21:43
Dupe of #15424. Will be fixed by #15437.

**Closed** 2021-05-25 08:59 UTC
Labels: resolved: duplicate, triaged: bug
