### ISSUE TITLE
Is there a way to disable AVX-512 in building from the source?

### ISSUE THREAD

**Issue by crazyi** [openssl/openssl#16800] opened 2021-10-11 01:01 UTC
I'm now running on Mac 10.13.6 High Sierra with Homebrew, when upgrading the OpenSSL, the following error come out:
`==> Upgrading openssl@3
  3.0.0 -> 3.0.0_1 

==> perl ./Configure --prefix=/usr/local/Cellar/openssl@3/3.0.0_1 --openssldir=/usr/local/etc/openssl@3 --libdir=/usr/lo
==> make
Last 15 lines from /Users/crazyi/Library/Logs/Homebrew/openssl@3/02.make:
crypto/bn/rsaz-avx512.s:857:2: error: instruction requires: AVX-512 ISA AVX-512 VL ISA
 vmovdqu64 %ymm1,32(%rdi)
 ^
crypto/bn/rsaz-avx512.s:858:2: error: instruction requires: AVX-512 ISA AVX-512 VL ISA
 vmovdqu64 %ymm2,64(%rdi)
 ^
crypto/bn/rsaz-avx512.s:859:2: error: instruction requires: AVX-512 ISA AVX-512 VL ISA
 vmovdqu64 %ymm3,96(%rdi)
 ^
crypto/bn/rsaz-avx512.s:860:2: error: instruction requires: AVX-512 ISA AVX-512 VL ISA
 vmovdqu64 %ymm4,128(%rdi)
 ^
make[1]: *** [crypto/bn/liblegacy-lib-rsaz-avx512.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [build_sw] Error 2` 

In the install.md I only found a building flag as **no-asm** , but it seems to disable the whole assembler codes and is not encouraged.
As my Xeon(R) CPU E5-2650 v4 is in Broadwell-EP series and doesn't support AVX-512, I want to know if there is a way to disable the AVX-512 during the building?

**Comment by lprimak** [comment] 2021-10-16 19:42
Yes, duplicate of #16670 Please close this issue

**Closed as completed** 2021-10-18 07:46 UTC
Labels: branch: master, triaged: bug, branch: 3.0
