### ISSUE TITLE
openssl s_client starttls smtp connect -- need to be able to customize the EHLO domain

### ISSUE THREAD

**Issue by ekangas1** [openssl/openssl#7555] opened 2018-11-02 16:42 UTC
When using openssl to connect using SMTP TLS to a target server, openssl always uses the domain:

openssl.client.net

as the domain in the SMTP EHLO command (as seen by adding the -debug flag to openssl).  We are seeing email providers (e.g. fusemail) starting to reject STARTTLS and, indeed, SMTP connections in general when the EHLO domain name does not match the reverse DNS of the server that is connecting to them.  This is clearly against spec, but for anti-spam reasons.

We really need a flag for openssl where we can specify a custom domain name to use in SMTP EHLO commands.  We can pass this along and have these connections work properly.

Since it is a best practice to use the server hostname in EHLO and mail providers are being more and more strict about this and other facets of the connection to determine valid connections, the ability to customize this setting is needed.  At the very least, a flag that would cause openssl to use the hostname of the server instead of openssl.client.net would be perfectly fine -- as the hostname of the server is what is used by sendmail and postfix and other MTAs when acting as SMTP clients, anyway.

**Comment by yscumc** [comment] 2019-05-09 18:49
I noticed the same thing when I enabled the `-debug` flag but the hardcoded domain for me is different though -- it's `mail.example.com`.

Seems like it's possible to change it using the `-name` flag though according to the documentation at https://www.openssl.org/docs/manmaster/man1/s_client.html

I can confirm this works for me on `OpenSSL 1.1.0g  2 Nov 2017` (distributed by Ubuntu 18.04.1 LTS as 1.1.0g-2ubuntu4.1)

**Comment by t8m** [comment] 2021-07-19 15:30
This is already implemented as noted above. Closing.

**Closed by t8m** 2021-07-19 15:30 UTC
