### ISSUE TITLE
undefined reference to `engine_load_afalg_internal'

### ISSUE THREAD

**Issue by jiapei100** [openssl/openssl#912] opened 2016-03-22 20:16 UTC
LD_LIBRARY_PATH=.:$LD_LIBRARY_PATH gcc -DDSO_DLFCN -DHAVE_DLFCN_H -DOPENSSL_THREADS -DOPENSSL_NO_DYNAMIC_ENGINE -DOPENSSL_PIC -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPOLY1305_ASM -DOPENSSLDIR="/usr/local/ssl" -DENGINESDIR="/usr/local/lib/engines" -Wall -O3 -pthread -m64 -DL_ENDIAN -Wa,--noexecstack -o apps/openssl apps/app_rand.o apps/apps.o apps/asn1pars.o apps/ca.o apps/ciphers.o apps/cms.o apps/crl.o apps/crl2p7.o apps/dgst.o apps/dhparam.o apps/dsa.o apps/dsaparam.o apps/ec.o apps/ecparam.o apps/enc.o apps/engine.o apps/errstr.o apps/gendsa.o apps/genpkey.o apps/genrsa.o apps/nseq.o apps/ocsp.o apps/openssl.o apps/opt.o apps/passwd.o apps/pkcs12.o apps/pkcs7.o apps/pkcs8.o apps/pkey.o apps/pkeyparam.o apps/pkeyutl.o apps/prime.o apps/rand.o apps/rehash.o apps/req.o apps/rsa.o apps/rsautl.o apps/s_cb.o apps/s_client.o apps/s_server.o apps/s_socket.o apps/s_time.o apps/sess_id.o apps/smime.o apps/speed.o apps/spkac.o apps/srp.o apps/ts.o apps/verify.o apps/version.o apps/x509.o -L. -lssl -L. -lcrypto -ldl
./libcrypto.a(init.o): In function `ossl_init_engine_afalg':
init.c:(.text+0x31): undefined reference to `engine_load_afalg_internal'
collect2: error: ld returned 1 exit status
make[1]: *** [link_app.] Error 1
make[1]: Leaving directory `/home/jiapei/Downloads/networks/openssl'
make: *** [apps/openssl] Error 2

**Comment by jiapei100** [comment] 2016-03-22 20:55
Is this the solution?
https://github.com/openssl/openssl/issues/890

**Comment by mattcaswell** [comment] 2016-04-14 11:03
Duplicate of #890 (fixed by 627537ddf379).

**Closed by mattcaswell** 2016-04-14 11:03 UTC
