### ISSUE TITLE
malformed HTTPS chunked output in 1.1.1c, but working in 1.0.2s in Linux

### ISSUE THREAD

**Issue by mbatle** [openssl/openssl#9360] opened 2019-07-13 15:09 UTC
I am getting malformed output from the openssl  when using 1.1.1c (probably with other 1.1.x too), but working fine with 1.0.2s (probably ok as well with 1.0.y). The use case is for HTTPS chunked, I am getting mal formed chunks, and like neverending stream of data (it looks like same data over and over).

Very important note: there is some randomness in the failure, sometimes it works OK even with 1.1.1c, but most times not. So if it worked for you in 1.1.1c, you get lucky, if you retry again after minutes / hours you may get a failure. I am not sure if this randomness is caused by server or client ... But it makes things harder to test and debug.

I build two docker images in the same host, one with 1.0.2s and one with 1.1.1c (latest stable versions to date).

```
openssl s_client -connect www.telecreditobcp.com:443 -servername www.telecreditobcp.com
```
and enter the following:

```
GET /tlcnp/index.do HTTP/1.1
Host: www.telecreditobcp.com
```

Another way to reproduce it is with the following python code:

```
import requests
requests.get('https://www.telecreditobcp.com/tlcnp/index.do')
```

You will get the following exception when it fails:

```
requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(17 bytes read)', IncompleteRead(17 bytes read))
```

Another way to reproduce it is:

```
curl -X GET https://www.telecreditobcp.com/tlcnp/index.do
```

Some additional insights:

* it seems to fail only for Linux. Someone told me it works on Windows, but not sure what version was tested, maybe it just happen to be 1.0.x version.

* I've been told sometimes using some kind of VPN makes things work.

Let me know if there is anything else I can provide to help with the debugging of this.

**Comment by lzsiga** [comment] 2019-07-18 11:29
Most likely unrelated, but wget says there is an invalid line in the reply-header:

    Syntax error in
    Set-Cookie: JSESSIONID=00001tix_WdW87QRIEpDckEaoX_:1askm240k; Path=/;HttpOnly;; HttpOnly
    at position 66.

**Comment by mbatle** [comment] 2019-07-18 14:42
> Edit: Anyways, which component is supposed to be at fault here? My tests suggest that the server is broken: it sends the HTTP header, then `1ab` as chunk-len, then sends 427 byte of HTML, then a CRLF, then goes back to sending the HTTP header.

The interesting thing is that happens with openssl 1.1.1, but not with 1.0.2 (with same server). So I think the problem is caused by a combination of things. Also keep in mind a browser like firefox / chrome always works (but I believe they use NSS, not openssl).

Important note: the bug is a bit random, in the sense, you may get it running ok with 1.1.1 for several  tries, but if you try some time later it fails again. But when 1.1.1 fails, if you try with 1.0.2 it is ok. I am tempted to do a git bisect between both versions to detect which commit introduced the issue but could be a bit time consuming, but probably someone with good knowledge of openssl can pinpoint the issue much faster.

**Comment by kroeckx** [comment] 2019-07-18 14:50
Looking at this with strace, I see the following lines repeated
all the time:
select(4, [0 3], [], NULL, NULL)        = 1 (in [3])
read(3, "\27\3\3\3\244", 5)             = 5
read(3, "I\362j\237\307\276m\236x\232\25\202m\224\36\352$\235\204s\346\217)}4\31\301G\2\21gU"..., 932) = 932
select(4, [0], [1], NULL, NULL)         = 1 (out [1])
write(1, "HTTP/1.1 200 OK\r\nDate: Thu, 18 J"..., 880) = 880


(The values in the 2nd read() are different.)

So I suspect this is a problem on the server side, not on the
client side.

**Comment by mbatle** [comment] 2019-07-18 17:29
My initial tests also lead me to think the issue was on the server indeed. But after checking openssl  client 1.0.2 is always working (also other clients), then I'm not so sure and it make methink there is something in the client as well.

**Comment by kroeckx** [comment] 2019-07-18 18:20
It's not because a client can make the server behave differently that
it's a bug in the client. I'm pretty sure it's a bug on the server
side.

I can reproduce this with 1.1.0k

**Comment by lzsiga** [comment] 2019-07-18 19:28
It seems working with s_client-1.0.2s. The only difference I've seen th output is this:

      SSL-Session:
    - Key-Arg   : None
    - Timeout   : 300 (sec)
    + Timeout   : 7200 (sec)

I still think it is a server-side problem; maybe something like an un-initalized variable.

**Comment by mbatle** [comment] 2019-07-18 21:18
You're right in that it could be a problem in the server. A different client could trigger a different path in the server that does not expose the bug.

**Comment by clbarnes** [comment] 2019-11-19 11:17
Any ideas as to what might need to change on the server to allow the new version of openssl to work like the old version of openssl did?

**Comment by mattcaswell** [comment] 2019-11-26 13:37
@mbatle has this issue been resolved?

**Comment by mbatle** [comment] 2019-12-04 21:34
Unfortunately, this is not solved, and it seems more people is having the issue. While there could be a problem in the server side as others suggest, I don't have control over the server implementation in this case, and the fact is an old vesion client (1.0) works while a new version client (1.1) does not.
I am trying to set it to work with 1.0 until 1.1 gets fixed.

**Comment by ramses132** [comment] 2019-12-04 21:47
I have the same problem with 1.1

**Comment by kaduk** [comment] 2019-12-04 23:47
I'm pretty sure I've seen a server implementation that reacts like this when receiving certain (unsupported) TLS extensions.  encrypt-then-mac and extended-master-secret are traditionally the "usual culprits" for this sort of thing, so I'd suggest trying with those disabled.

**Comment by mbatle** [comment] 2019-12-05 01:51
Thanks kaduk, that's a good tip. I will try to set up that, trying to find out if I can easily disable it using a highl level interface like python requests ...

**Comment by ramses132** [comment] 2019-12-18 19:47
@kaduk  it's not working with openssl > 1.1 but <1.1 is fine  it's strange

**Comment by kaduk** [comment] 2019-12-23 21:16
That corresponds to when libssl started sending the encrypt-then-mac and extended-master-secret extensions by default.
And indeed, if I patch ```s_client``` to call ```SSL_set_options(con, SSL_OP_NO_ENCRYPT_THEN_MAC)```  right after ```SSL_new()```, then the reproducer from the initial report produces a (lengthy) error page instead of looping through the same output.

So I think the resolution here is pretty clear: the server is buggy, and a workaround exists.  (Note that encrypt-then-mac is only relevant for non-AEAD ciphers, though I do not expect the server in question to support any.)
I'll set an appropriate tag so the issue will be closed after a waiting period.

**Comment by clbarnes** [comment] 2019-12-23 22:37
The workaround being "use an old version of openssl which doesn't break a bunch of downstream projects"? What's the right thing to do for users of very high-level libraries like python's `requests` and `django`?

**Comment by kaduk** [comment] 2019-12-23 23:03
The workaround is to implement the equivalent of ```SSL_set_options(.,SSL_OP_NO_ENCRYPT_THEN_MAC)``` for those libraries.  Which is work to be done, to be sure, but it is not a bug in the openssl software itself.

**Comment by kroeckx** [comment] 2019-12-23 23:44
Where the equivalent means that the libraries should have an
option for the application to set that. Libraries should not
set that option by default.

**Comment by richsalz** [comment] 2019-12-23 23:46
By "libraries should not set that option by default" do you also mean openssl?

**Comment by kaduk** [comment] 2019-12-24 00:30
> By "libraries should not set that option by default" do you also mean openssl?

Yes.  And openssl does not set it by default, so there is no issue.
The "it" in question is ```SSL_OP_NO_ENCRYPT_THEN_MAC``` -- allowing EtM is the default in libssl.

**Comment by kroeckx** [comment] 2019-12-24 00:38
> By "libraries should not set that option by default" do you also mean openssl?

Yes, I mean things like OpenSSL and python should not set that
option by default. The current OpenSSL default is the correct
default.

**Comment by clbarnes** [comment] 2019-12-24 09:37
Could this be added to some "common gotchas" documentation (along with examples of downstream packages affected) rather than silently closed? This conversation is unlikely to be the first thing people find if they hit the issue.

**Comment by richsalz** [comment] 2019-12-24 14:11
At a minimum, a FAQ entry seems reasonable.

**Comment by kaduk** [comment] 2019-12-24 17:49
What would such an FAQ entry say?  "Some deployed TLS servers are fatally buggy and do not implement extensibility in a standards-complaint manner; these servers may exhibit strange behavior such as repeating the HTTP headers in a loop after receiving a ClientHello that includes relatively new TLS extensions such as encrypt-then-mac and extended-master secret.  While these new TLS extensions provide significant security benefits to clients and are rightly enabled by default in openssl, if bringing the server into compliance is not possible, the extension(s) in question can be disabled on a per-connection basis when talking to the buggy server, by using ```SSL_set_options(3)```."?

**Comment by richsalz** [comment] 2019-12-24 18:21
Sure, something like that.  As well as the concrete advice to set the "no etm" option.

The world is nasty, and folks have to solve problems.  OpenSSL saying "not my fault" doesn't help a great deal, especially when we can advise on the work-around.

**Comment by mbatle** [comment] 2019-12-27 21:12
> @mbatle did you end up being able to make any progress here?

I was not able, since I didn't find a way to do the SSL_set_options(.,SSL_OP_NO_ENCRYPT_THEN_MAC) from the application level we are using. Just an idea for you to consider, but maybe a way to set this via an environment variable would avoid fixing all the libraries using openssl ?

**Comment by kaduk** [comment] 2019-12-27 21:33
I am not very enthusiastic about adding an environment variable to control this behavior, for several reasons: first, it's not a "fix", it's a workaround for broken servers; second, we are generally reluctant to add new environment variables at all; and third, for this particular case, adding the environment variable would add an easy way to inadvertently (and in a hard-to-diagnose manner) weaken the security properties afforded to TLS clients by openssl.
BTW, the ```-EncryptThenMac```  directive in the openssl configuration file has the same effect, if your application level allows a way to specify a configuration file to use.  (There is the system global config, which is not a great knob, and IIRC the ```OPENSSL_CONF``` environment variable is also consulted.)

**Comment by mbatle** [comment] 2020-01-06 18:29
thanks @kaduk for the tip, I will try that

**Comment by mbatle** [comment] 2020-01-07 09:37
I tried adding Options = -EncryptThenMac to system_default_sect of the system openssl configuration file (also with a separate config file via OPENSSL_CONF) without success. 

Then tried the following also without success:
Options = -EncryptThenMac,-ExtendedMasterSecret

Even tried Options=Bugs without success.

How do I know if configuration file is being loaded ?
Any ideas what I'm doing wrong ?

Thank you !

**Comment by mbatle** [comment] 2020-01-22 15:10
any luck with tweaking config or workaround without having to modify source and build anything ?

**Comment by kaduk** [comment] 2020-01-24 00:51
This seems to be working for me:

```
$ cat path/to/openssl.cnf
openssl_conf = default_conf

[default_conf]
ssl_conf = ssl_sect

[ssl_sect]
system_default = system_default_sect

[system_default_sect]
Options = -EncryptThenMac
```

**Comment by mbatle** [comment] 2020-03-10 00:23
thanks @kaduk , I really appreciate it, it worked like a charm !

**Comment by kaduk** [comment] 2020-03-13 14:11
The "FAQ entry" topic is now https://github.com/openssl/web/pull/157 so I think it is safe to close this.

**Closed by kaduk** 2020-03-13 14:11 UTC
Labels: resolved: answered, triaged: question
