### ISSUE TITLE
SSL_write fails with error message "error:0A00010F:SSL routines::bad length"

### ISSUE THREAD

**Issue by JaeyongYoo** [openssl/openssl#21002] opened 2023-05-19 14:45 UTC
I have an openSSL client that transmits heavy volume of data to openSSL server and occasionally SSL_write fails with error message "error:0A00010F:SSL routines::bad length". Here goes more details:

- I'm using OpenSSL 3.0.8 (I believe it is a custom built but unfortunately I don't have an exact configuration) 
- When transmitting around 1-2Gbps it works fine and it starts failing when it hits over 3-4Gbps. 
- This failure happens periodically like for 1-2 miuntes working fine and then happens 10-20 seconds and then it doesn't happen and so on.
- I'm using non-blocking socket as underlying BIO.
- My client is single-threaded. So for openSSL perspective, it is just a simple code that continuously calls SSL_write in a thread and upon returning "WANT_READ" or "WANT_WRITE" it waits epoll for EPOLLOUT. (Pretty standard) 

I tried to dig in the openSSL code and learned that the error code 0A00010F can be broken down to three parts
- 0A --> library, which is ERR_LIB_DSA
- 000 --> function
- 10F --> reason, which is SSL_R_BAD_LENGTH

And I wasn't able to find a code part that generates this error, just through the code-reading.  
I'd like to consult here in which direction I can further debug this?

Few more updates:
- When I search up, most "bad-length" error comes with error code of library "0x14" which is ERR_LIB_SSL and that makes sense when it comes from SSL_write. But this one with "0A" I can't find good material out there so hope here I can get some insights.

**Comment by JaeyongYoo** [comment] 2023-05-19 15:55
> 
Thanks for quick turnaround!

Here goes the content in openssl/err.h

# define ERR_LIB_DSA             10
# define ERR_LIB_X509            11
/* #define ERR_LIB_METH         12 */
# define ERR_LIB_ASN1            13
# define ERR_LIB_CONF            14
# define ERR_LIB_CRYPTO          15
# define ERR_LIB_EC              16
# define ERR_LIB_SSL             20

And ERR_LIB_DSA  being 10 and hex 0x0A. And ERR_LIB_SSL  being 20 and hex 0x14.
I think the library code is ERR_LIB_DSA unless there is other way to read the library code.

**Comment by mattcaswell** [comment] 2023-05-19 15:57
I think @t8m was looking at this ASCII art:

````
 * An OpenSSL error packs like this:
 *
 * <---------------------------- 32 bits -------------------------->
 *    <--- 8 bits ---><------------------ 23 bits ----------------->
 * +-+---------------+---------------------------------------------+
 * |0|    library    |                    reason                   |
 * +-+---------------+---------------------------------------------+
````
So the library code is *not* the top 8 bits. The first bit is always 0 and its the *next* 8 bits. Which makes the library code 20 not 10 (i.e. @t8m is correct it is `ERR_LIB_SSL`)

**Comment by mattcaswell** [comment] 2023-05-19 15:59
> "error:0A00010F:SSL routines::bad length"

How are you printing that error? You can normally get source line number information from OpenSSL errors which might help to pinpoint which specific instance this is.

**Comment by JaeyongYoo** [comment] 2023-05-19 16:32
ah, that was it! So it is from ERR_LIB_SSL. I think that would be a good starting point for me.
I'm using this line to get that error message:

ERR_error_string_n(ERR_get_error(), msg, sizeof(msg));

**Comment by JaeyongYoo** [comment] 2023-05-19 17:46
Also, I compiled openssl with default configuration (./Configure && make) and installed it. The same issue happens.

**Comment by JaeyongYoo** [comment] 2023-05-19 18:21
I checked that the error happens with positive message length so I can rule out the one from SSL_write and looks like it is coming from:

https://github.com/openssl/openssl/blob/openssl-3.0/ssl/record/rec_layer_s3.c#L368-L372

Which makes sense that in case of SSLfatal it gives 0 for function code.

**Comment by mattcaswell** [comment] 2023-05-22 08:38
> ERR_error_string_n(ERR_get_error(), msg, sizeof(msg));

If instead of `ERR_get_error()` here you call `ERR_get_error_all` you can additionally get hold of the source filename and line number where the error was raised. That would confirm for sure a specific instance.

https://www.openssl.org/docs/man3.0/man3/ERR_get_error_all.html

> in case of SSLfatal it gives 0 for function code.

Function codes are not used any more in OpenSSL 3.0, so this applies to all errors.

**Comment by JaeyongYoo** [comment] 2023-05-22 19:33
I verified that the error is coming from https://github.com/openssl/openssl/blob/openssl-3.0/ssl/record/rec_layer_s3.c#L368-L372

**Comment by mattcaswell** [comment] 2023-05-23 14:03
> I see wnum is set to zero at (https://github.com/openssl/openssl/blob/openssl-3.0/ssl/record/rec_layer_s3.c#L380) after storing its original value to total (https://github.com/openssl/openssl/blob/openssl-3.0/ssl/record/rec_layer_s3.c#L358). And it only writes to wnum only when there were errors happened. So to my understanding, wnum will be always zero unless there were error happened and wonder if I understand this correctly.

Correct. `wnum` is always reset back to zero, and only set again if we fail to successfully write out all our remaining data.

> If my understanding is correct and given the first SSL error is from https://github.com/openssl/openssl/blob/openssl-3.0/ssl/record/rec_layer_s3.c#L368, I guess the exception was triggered by second clause, ((wb->left != 0) && (len < (s->rlayer.wnum + s->rlayer.wpend_tot)) meaning that wpend_tot is larger than the original requested length. And this line (https://github.com/openssl/openssl/blob/openssl-3.0/ssl/record/rec_layer_s3.c#L1143) is most suspicious where it adds up the values coming from pipelines...

Well that actually would be quite interesting to confirm, i.e. exactly which of the two sub-expressions causes the failure and what are the various values that are causing it?

`len` here represents the length of the data that was originally asked to be written. This should remain the same value in subsequent calls to `ssl3_write_bytes` in the event of "retries".
`wnum` represents the number of bytes held in complete records that we have already successfully written out to the network.
`wpend_tot` represents the number of bytes we have packaged up inside a whole record and stored in the `wb` buffer to be written.
`wb->left` represents the number of bytes left in the buffer that are still to be written to the network. This could be a partial record if there were previous writes that only managed to send part of the record. So `wb->left` could be less than `wpend_tot`.

So the expression that is failing is: `((wb->left != 0) && (len < (s->rlayer.wnum + s->rlayer.wpend_tot))`

The first part says "only do this check if we have a full or partial record waiting to be written to the network". The second part says the total length of the data we are trying to write must not be less than the total amount held in full records that we have already written plus the amount of data held in the record that is currently pending to be written. If that fails then something strange has happened.

I wonder if you might be able to modify that chunk of code to log out the various values (`len`, `wnum`, `wpend_tot` `wb->left`) in the event that the check fails?

> BTW my application is a single-threaded application and wonder if the mis-use of openssl library can cause this behavior or if it is an openssl library side bug?

If you had said your application was multi-threaded then I would have thought the most likely reason was multi-threaded access to the SSL object (which would be an application error). But with a single threaded application this looks more like an OpenSSL bug (although it is curious that no-one else has encountered this).

**Comment by mattcaswell** [comment] 2023-05-23 14:26
> What about the requirement that in case SSL_write() fails because the socket write returns EAGAIN/EWOULDBLOCK you have to call it again with the same parameters once the socket is ready for writing?

Yes - you're right that could cause this. I was thinking there were earlier checks for that which would have caught it - but actually I was thinking of the checks at the beginning of `ssl3_write_pending` which isn't called until after this check. So, this probably could be caused by an application error.

**Comment by JaeyongYoo** [comment] 2023-05-23 14:36
Do you mean, if SSL_write fails with SSL_ERROR_WANT_READ or SSL_ERROR_WANT_WRITE from SSL_get_error, I have to retry with the exact same parameters? (same buffer/same length)?

Actually in my application, it discards the buffer and try with a new one.

**Comment by t8m** [comment] 2023-05-23 14:39
Yeah, https://www.openssl.org/docs/manmaster/man3/SSL_write.html the WARNINGS section.

**Comment by mattcaswell** [comment] 2023-05-23 14:39
> Do you mean, if SSL_write fails with SSL_ERROR_WANT_READ or SSL_ERROR_WANT_WRITE from SSL_get_error, I have to retry with the exact same parameters? (same buffer/same length)?

Yes! You must do this. That would explain this problem.

**Comment by JaeyongYoo** [comment] 2023-05-23 14:44
ah got it. Thank you so much for your answers! 
BTW I don't see the same warning in SSL_read case, so I assume this only applies to SSL_write?

And I don't set  SSL_MODE_ACCEPT_MOVING_WRITE_BUFFER, so it is by default turn off and I can just retry with the original buffer pointer?

**Comment by mattcaswell** [comment] 2023-05-23 14:50
> BTW I don't see the same warning in SSL_read case, so I assume this only applies to SSL_write?

Yes, SSL_write only.

> And I don't set SSL_MODE_ACCEPT_MOVING_WRITE_BUFFER, so it is by default turn off and I can just retry with the original buffer pointer?

Yes, SSL_MODE_ACCEPT_MOVING_WRITE_BUFFER is off by default so you must retry with the original buffer pointer.

**Comment by JaeyongYoo** [comment] 2023-05-23 14:56
Sorry one last question: Can I use a different buffer pointer but with exact same content/size?

I went over my application code and if I want to maintain the original buffer pointer might take some major surgery so wonder if I can use different buffer pointer with exact same content/size.

**Comment by mattcaswell** [comment] 2024-01-31 12:11
Closing since this is marked as resolved.

**Closed by mattcaswell** 2024-01-31 12:11 UTC
Labels: triaged: question, resolved: answered
