### ISSUE TITLE
Reuse of PSKs between TLS 1.2 and TLS 1.3 is questionable

### ISSUE THREAD

**Issue by davidben** [openssl/openssl#6490] opened 2018-06-14 21:11 UTC
I just posted this message to the TLS list:
https://www.ietf.org/mail-archive/web/tls/current/msg26413.html

Assuming the WG agrees with my understanding of things, it seems OpenSSL's compatibility path for TLS 1.2 PSKs with TLS 1.3 is a little questionable in terms of key separation. I've written a draft which should provide a more principled path to the same goal. It should additionally smooth over the awkwardness around the hash matching.

The timing with the 1.1.1 release is unfortunate, so my recommendation would be that, for 1.1.1, configuring a legacy PSK callback just disables 1.3 altogether. Then, for a later release, when the draft has stabilized, you all can implement the compatibility derivation in the draft.

**Comment by richsalz** [comment] 2018-06-15 00:31
I think "disable 1.3 if a legacy PSK callback is set" makes sense.  @mattcaswell what do you think?

**Comment by mattcaswell** [comment] 2018-06-15 08:43
Reluctantly I have to agree that this looks like the best way forward. It will mean reverting some PRs :-(

**Comment by richsalz** [comment] 2018-06-15 14:18
ifdef the changes?

**Comment by mattcaswell** [comment] 2018-06-15 14:22
> ifdef the changes?

You mean make it a configurable option? I had thought about that but the problem is this is likely to be incompatible with Universal PSKs if that draft goes ahead. Better for it not to be in the eco-system at all if that happens.

This is currently being discussed on the TLS WG list so I suggest we don't do anything immediately and see where the discussion leads.

**Comment by richsalz** [comment] 2018-06-15 14:34
No, not configurable.  Just uniformly ```#if 0``` it out.  Might be simpler.

**Comment by mattcaswell** [comment] 2018-06-15 14:36
Yes, I though of that too...but it's just horrible from a maintenance perspective (don't forget this will turn into an LTS release). I rather rip it out and re-implement it if we have too.

**Comment by davidben** [comment] 2018-06-15 15:02
At the very least, we should get the cryptographers to confirm on the WG that I'm not totally confused, or tell me I'm wrong. :-) I consulted with Karthik while writing the draft, but I certainly could have messed up along the way.

**Comment by mattcaswell** [comment] 2018-07-03 10:58
Discussion on the WG list seems to have died down on this - but I got a feeling that the preferred route for Universal PSKs would be via an extension. My understanding is that our current approach to PSKs is shared with at least one other implementation (GnuTLS). So I'm now thinking that perhaps we should just leave this as it is.

**Comment by davidben** [comment] 2018-07-03 17:16
Yeah, I need to go swap in that discussion (prepping for a big move right now, so I'm kind of all over the place). I don't think an extension would actually do any good, but we'll see how that discussion goes.

But that's orthogonal to the TLS 1.2 question. The TLS 1.2 question is: is it safe to use the same secret in the two contexts like this? The TLS 1.3 proof does *not* allow for that reuse.

**Comment by mattcaswell** [comment] 2018-07-13 17:30
I'd like some other committer/OMC opinion on this.

**Comment by richsalz** [comment] 2018-07-13 19:52
I still think my suggestion, or equivalent, is reasonable.  I think we should not mix PSK's across TLS 1.3 and 1.2 or earlier.

**Comment by t-j-h** [comment] 2018-07-13 21:11
If the user doesn't want to share a PSK across versions they can disable specific TLS versions themselves. If we provide separate mechanisms for PSK specification for then the user could configure the same PSK for both. Should that be blocked?

The TLS 1.3 spec does not explicitly prohibit use of values outside the protocol as I read it - and if that was what the authors intended then wording needs to change in the spec. That things are outside the consideration is not the same as being forbidden. The user can elect to not negotiate earlier versions and that seems like a cleaner "solution" to the "problem".

**Comment by t-j-h** [comment] 2018-07-15 02:51
If the spec changes to say SHALL NOT share then that makes for a decent argument to adjust. But if it is just a recommendation then the user can handle that as per now with jusr disabling the protocol versions they don't want used.

**Comment by richsalz** [comment] 2018-07-15 16:18
Disabling the protocol won't work if only *some* users of the server are doing PSK's.  We need to do it per-connection, and fallback to 1.2, not per-context.

**Comment by mattcaswell** [comment] 2018-08-02 09:41
This is the proposed text to be added to the final RFC:

https://github.com/tlswg/tls13-rfc/pull/13/files

So, it essentially says it might not be safe, but stops short of actually prohibiting PSK reuse.

Wherever possible we should be safe by default. The proposed RFC text suggests it might not be safe, so it doesn't seem sensible to me for libssl to reuse by default.

> But if it is just a recommendation then the user can handle that as per now with jusr disabling the protocol versions they don't want used.

This argument can be run the other way. If we don't reuse by default, the user can always do the reuse themselves if they really want to do it.

In PR #6836, I change things so that libssl does not reuse by default and instead disables TLSv1.3 where TLSv1.2 PSKs are present without a TLSv1.3 PSK.

In that PR `s_client`, as an application, does do reuse when using the `-psk` flag. I think that is an ok thing for s_client to do as a test application.

I think we should wait to see if the proposed text makes it into the RFC. But assuming it does, then we should go with PR #6836.

**Comment by t-j-h** [comment] 2018-08-02 09:46
The wording there reads to me a little differently - and I've been following the discussion to see if there would actually be a recommendation against reuse - "there is no known way in which reuse of the same PSK in TLS 1.3 and TLS 1.2 would produce related output" is a pretty strong statement. There is no known issue.

**Comment by mattcaswell** [comment] 2018-08-02 09:57
True. But I'd counter that by saying this is also quite a strong hint to us that we shouldn't reuse by default:

"Implementations can ensure safety from cross-protocol key collisions by not reusing PSKs between TLS 1.3 and TLS 1.2."

**Comment by t-j-h** [comment] 2018-08-02 10:42
I guess where I'm coming from is I see non-PSK reuse as a barrier to people in practical terms upgrading from TLS-1.2 to TLS-1.3. If you have PSK established and in place now you have to put in a new set of PSKs for TLS-1.3 usage.

i.e. we swap an unknown issue for a concrete known actual issue.

Staying back at TLS-1.2 is **definitely a bad idea** compared to moving forward to TLS-1.3.
Sharing PSKs **might perhaps maybe** have some as yet admittedly entirely unknown issue.

Now it would be completely different if there was a sense (shared) that this is an actual serious issue rather than simply being ultra cautious.  I'm not getting that reading on the discussions I've seen.

**Comment by mattcaswell** [comment] 2018-08-02 10:43
That is a very persuasive point.

**Comment by kaduk** [comment] 2018-08-06 00:00
So, the "there is no known way in which reuse of the same PSK in TLS 1.3 and TLS 1.2 would produce related output"  is actually a pretty weak statement, to me -- it reflects "Ilari did some back-of-the-envelope calculations" and nothing more.  Almost everything else in the document has actual formal analysis to back it up.  The intent behind the whole paragraph is roughly "you should probably wait until we have something baked, but if you can't wait, this is what we currently know".
While it's true that sharing PSKs "might perhaps maybe" be a bad idea, it's a risk that we don't know the measure of.  Staying at 1.2 vs. moving to 1.3 is something that we at least think we understand the properties of pretty well, so maybe @t-j-h could say a bit more about what makes staying with 1.2 "definitely a bad idea" to him?

**Comment by t-j-h** [comment] 2018-08-06 00:05
**Comparatively** speaking is the context of the statement - TLS 1.3 is designed and meant to be an improved security position over TLS 1.2 - and I don't think you are suggesting otherwise. We want to see rapid migration to TLS 1.3 - I assume that is the overall objective of everyone involved in the TLS 1.3 work. That leads to the logic that adding to the reasons to stay back at TLS 1.2 rather than moving forward to TLS 1.3 need to be evaluated in that context. Clearer?

**Comment by mattcaswell** [comment] 2018-08-06 14:33
> The assumption is that the PSK case can be sorted out in the next six-ish months to bring the benefits of 1.3 to everyone else. (Greenfield TLS 1.3+PSK is, of course, fine.)

That of course might translate to 12-ish months (or longer) by the time it gets into an OpenSSL release.

**Comment by mattcaswell** [comment] 2018-08-15 13:43
As per the OMC vote we will be retaining the existing TLSv1.2->TLSv1.3 compatibility. I'm leaving this issue open for now because, perhaps, we may want to make some note about it in the documentation.

**Closed** 2018-09-01 01:07 UTC
Labels: ready
