### ISSUE TITLE
Compile error on AIX and Linux RedHat

### ISSUE THREAD

**Issue by Syberia5910** [openssl/openssl#3583] opened 2017-05-30 15:05 UTC
Hi,

I have a problem for compiling openssl 1.0.2 in version j, k or l. When I try to launch the make command, I have this error :

```
        LDFLAGS="-DOPENSSL_THREADS -qthreaded -D_THREAD_SAFE -DDSO_DLFCN -DHAVE_DLFCN_H -q64 -O -DB_ENDIAN -qmaxmem=16384 -qro -qroconst -DOPENSSL_BN_ASM_MONT -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DAES_ASM -DVPAES_ASM -Wl,-brtl,-blibpath:/produits/composants/openssl-1.0.2l/lib:${LIBPATH:-/usr/lib:/lib}";  ( :;    LIBDEPS="${LIBDEPS:--L.. -lssl -L.. -lcrypto  }";  LDCMD="${LDCMD:-xlc_r}"; LDFLAGS="${LDFLAGS:--DOPENSSL_THREADS -qthreaded -D_THREAD_SAFE -DDSO_DLFCN -DHAVE_DLFCN_H -q64 -O -DB_ENDIAN -qmaxmem=16384 -qro -qroconst -DOPENSSL_BN_ASM_MONT -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DAES_ASM -DVPAES_ASM}";  LIBPATH=`for x in $LIBDEPS; do echo $x; done | sed -e 's/^ *-L//;t' -e d | uniq`;  LIBPATH=`echo $LIBPATH | sed -e 's/ /:/g'`;  LD_LIBRARY_PATH=$LIBPATH:$LD_LIBRARY_PATH  ${LDCMD} ${LDFLAGS} -o ${APPNAME:=sslv2conftest} sslv2conftest.o  ${LIBDEPS} )
Target "link_app.aix-shared" is up to date.
        xlc_r -I.. -I../include  -DOPENSSL_THREADS -qthreaded -D_THREAD_SAFE -DDSO_DLFCN -DHAVE_DLFCN_H -q64 -O -DB_ENDIAN -qmaxmem=16384 -qro -qroconst -DOPENSSL_BN_ASM_MONT -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DAES_ASM -DVPAES_ASM -c dtlstest.c
        xlc_r -I.. -I../include  -DOPENSSL_THREADS -qthreaded -D_THREAD_SAFE -DDSO_DLFCN -DHAVE_DLFCN_H -q64 -O -DB_ENDIAN -qmaxmem=16384 -qro -qroconst -DOPENSSL_BN_ASM_MONT -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DAES_ASM -DVPAES_ASM -c ssltestlib.c
        LDFLAGS="-DOPENSSL_THREADS -qthreaded -D_THREAD_SAFE -DDSO_DLFCN -DHAVE_DLFCN_H -q64 -O -DB_ENDIAN -qmaxmem=16384 -qro -qroconst -DOPENSSL_BN_ASM_MONT -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DAES_ASM -DVPAES_ASM -Wl,-brtl,-blibpath:/produits/composants/openssl-1.0.2l/lib:${LIBPATH:-/usr/lib:/lib}";  ( :;    LIBDEPS="${LIBDEPS:--L.. -lssl -L.. -lcrypto  }";  LDCMD="${LDCMD:-xlc_r}"; LDFLAGS="${LDFLAGS:--DOPENSSL_THREADS -qthreaded -D_THREAD_SAFE -DDSO_DLFCN -DHAVE_DLFCN_H -q64 -O -DB_ENDIAN -qmaxmem=16384 -qro -qroconst -DOPENSSL_BN_ASM_MONT -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DAES_ASM -DVPAES_ASM}";  LIBPATH=`for x in $LIBDEPS; do echo $x; done | sed -e 's/^ *-L//;t' -e d | uniq`;  LIBPATH=`echo $LIBPATH | sed -e 's/ /:/g'`;  LD_LIBRARY_PATH=$LIBPATH:$LD_LIBRARY_PATH  ${LDCMD} ${LDFLAGS} -o ${APPNAME:=dtlstest} dtlstest.o ssltestlib.o ${LIBDEPS} )
ld: 0711-224 WARNING: Duplicate symbol: .main
ld: 0711-345 Use the -bloadmap or -bnoquiet option to obtain more information.
ld: 0711-317 ERROR: Undefined symbol: .create_ssl_ctx_pair
ld: 0711-317 ERROR: Undefined symbol: .bio_f_tls_dump_filter
ld: 0711-317 ERROR: Undefined symbol: .create_ssl_objects
ld: 0711-317 ERROR: Undefined symbol: .mempacket_test_inject
ld: 0711-317 ERROR: Undefined symbol: .create_ssl_connection
make: The error code from the last command is 8.

```

This error is on AIX 6.1 but I can send the same on RedHat 5. Sometime, I compile this with success but I don't understand what it mean. Some idea ?

Thanks.

**Comment by dot-asm** [comment] 2017-06-07 16:33
I can't reproduce the problem. And provided that you say yourself that it's intermittent it has to be specific to your environment. And the latter is something we can't possibly help, especially not being prominent AIX users. Talk to people around you, your system administrator. Always start from clean directory, i.e. `to empty directory, or execute `make distclean`. If problem persists in fresh directory, do tell whole story, i.e. how exactly it was configured. [For example there is no reference to xlc_r in our config, how did it end up there.] But as it stands now I see no real reason to not close this... Sorry.

**Closed by dot-asm** 2017-06-07 16:33 UTC
