### ISSUE TITLE
X509_NAME already defined in wincrypt.h

### ISSUE THREAD

**Issue by wolftobias** [openssl/openssl#1093] opened 2016-05-18 15:56 UTC
Hi, 

I need to include the following line into ossl_typ.h, otherwise I get a bad compile result. 
```
_# ifdef OPENSSL_SYS_WIN32 
--> #include <windows.h> 
#  undef X509_NAME 
#  undef X509_EXTENSIONS 
#  undef PKCS7_ISSUER_AND_SERIAL 
#  undef OCSP_REQUEST 
#  undef OCSP_RESPONSE 
# endif_ 
```

**Comment by richsalz** [comment] 2016-05-18 15:59
can you maybe cut/paste again?  with three backticks before and after the clump of lines?
```
like this
```

**Comment by richsalz** [comment] 2016-05-24 15:18
I want to solve this, but I need some compiler output -- which file is failing to compile?  The issue is not ossl_types.h, but rather some other file including windows files first.

**Comment by wolftobias** [comment] 2016-05-25 07:01
I`d like to answer that, but with the trunk version I cannot compile on linux for windows. I`going to open a issue for that.

**Comment by wolftobias** [comment] 2016-05-25 07:12
sorry it was not ossl_typ.h, we made that change in x509.h

```
# ifdef OPENSSL_SYS_WIN32
/* Under Win32 these are defined in wincrypt.h */
# include <windows.h>
#  undef X509_NAME
#  undef X509_EXTENSIONS
# endif
```

**Comment by wolftobias** [comment] 2016-05-25 07:15
When I remove the include <windows.h> I get the following error:

```
g++ "-IC:\_Dev\\sourcecode\\branches\\NewOpenSSL_1_1\\src\\main\\include" -O0 -g3 -Wall -c -fmessage-length=0 -o "src\\main\\cpp\\openssl_stack.o" "..\\src\\main\\cpp\\openssl_stack.cpp" 
In file included from C:/TDM-GCC-64/x86_64-w64-mingw32/include/windows.h:95:0,
                 from C:\_Dev\sourcecode\branches\NewOpenSSL_1_1\src\main\include/openssl/async.h:59,
                 from C:\_Dev\sourcecode\branches\NewOpenSSL_1_1\src\main\include/openssl/ssl.h:157,
                 from C:\_Dev\sourcecode\branches\NewOpenSSL_1_1\src\main\include/openssl_stack.h:10,
                 from ..\src\main\cpp\openssl_stack.cpp:1:
C:\Daten\_projects\Gematik_Dev\sourcecode\branches\NewOpenSSL_1_1\src\main\include/openssl_stack.h:27:2: error: expected ')' before numeric constant
  X509_NAME* gk_sk_X509_NAME_value(STACK_OF(X509_NAME)* st, int i);
  ^
C:\Daten\_projects\Dev\sourcecode\branches\NewOpenSSL_1_1\src\main\include/openssl_stack.h:28:53: error: expected identifier before '(' token
  void gk_sk_X509_NAME_push(STACK_OF(X509_NAME)* st, X509_NAME* name);
                                                     ^
C:\Daten\_projects\Dev\sourcecode\branches\NewOpenSSL_1_1\src\main\include/openssl_stack.h:28:53: error: expected ')' before numeric constant
  void gk_sk_X509_NAME_push(STACK_OF(X509_NAME)* st, X509_NAME* name);
                                                     ^
C:\Daten\_projects\Dev\sourcecode\branches\NewOpenSSL_1_1\src\main\include/openssl_stack.h:28:53: error: expected ')' before numeric constant
C:\Daten\_projects\Dev\sourcecode\branches\NewOpenSSL_1_1\src\main\include/openssl_stack.h:28:53: error: expected initializer before numeric constant
..\src\main\cpp\openssl_stack.cpp:113:1: error: expected ')' before numeric constant
 X509_NAME* gk_sk_X509_NAME_value(STACK_OF(X509_NAME)* st, int i) {
```

**Comment by richsalz** [comment] 2016-05-25 12:45
What if you put windows.h in *your* file openssl_stack.cpp?

**Comment by richsalz** [comment] 2016-05-25 13:15
this doesn't seem to be an openssl issue, so i'm closing this.  reply and reopen if i'm wrong about that.

**Closed by richsalz** 2016-05-25 13:15 UTC
