### ISSUE TITLE
X509_ATTRIBUTE_free caused munmap_chunk()

### ISSUE THREAD

**Issue by 1185129439** [openssl/openssl#15698] opened 2021-06-10 09:12 UTC
My demo is as follows, but munmap_chunk() occurs when I free attr.
`int main() {
    int *value = NULL;

    value = (int *)malloc(sizeof(int));

    X509_ATTRIBUTE *attr = NULL;

    attr = X509_ATTRIBUTE_create(1, 0, &value); 

    if(attr != NULL) {
       X509_ATTRIBUTE_free(attr);
    }
        
    free(value);
    return 0;
}`
![image](https://user-images.githubusercontent.com/69578444/121497887-78cd3780-ca0e-11eb-934f-14a6de5788c6.png)
This may be caused by an incorrect interface to be released， but there are a lot of places in openssl that's used in this way.

**Comment by mattcaswell** [comment] 2021-06-10 09:15
This appears to be a dupe of #15696. Closing this in favour of that.

**Closed by mattcaswell** 2021-06-10 09:15 UTC
Labels: issue: question
