### ISSUE TITLE
[3.0.0] Concurrent namemap initialization races and often fails

### ISSUE THREAD

**Issue by sfackler** [openssl/openssl#12543] opened 2020-07-27 19:47 UTC
Here's a simple C program that spawns 10 threads, each of which create and initialize an EVP_MD_CTX to use SHA1:

```c
#include <openssl/evp.h>
#include <openssl/err.h>
#include <pthread.h>

#define THREADS 10

void *thread(void *arg) {
	EVP_MD_CTX *ctx = EVP_MD_CTX_create();

	int r = EVP_DigestInit_ex(ctx, EVP_sha1(), NULL);
	if (r != 1) {
		ERR_print_errors_fp(stdout);
	}
}

int main() {
	pthread_t threads[THREADS];

	for (int i = 0; i < THREADS; i++) {
		pthread_create(&threads[i], NULL, thread, NULL);
	}

	for (int i = 0; i < THREADS; i++) {
		pthread_join(threads[i], NULL);
	}
}
```

When run against OpenSSL 3.0.0-alpha5 on a Linux VM with 12 cores, many of the threads report errors initializing OpenSSL's internal namemap:

```
00B7FFB50C7F0000:error::common libcrypto routines:ossl_namemap_add_names:internal error:crypto/core_namemap.c:310:Got number 12 when expecting 70
00B7FFB50C7F0000:error::common libcrypto routines:ossl_namemap_add_names:internal error:crypto/core_namemap.c:310:Got number 78 when expecting 94
00B7FFB50C7F0000:error::digital envelope routines:evp_generic_fetch:fetch failed:crypto/evp/evp_fetch.c:318:Global default library context, Algorithm (SHA1), Properties ()
00B7FFB50C7F0000:error::digital envelope routines:EVP_DigestInit_ex:initialization error:crypto/evp/digest.c:178:
0097FFB40C7F0000:error::common libcrypto routines:ossl_namemap_add_names:internal error:crypto/core_namemap.c:310:Got number 12 when expecting 71
0097FFB40C7F0000:error::digital envelope routines:evp_generic_fetch:fetch failed:crypto/evp/evp_fetch.c:318:Global default library context, Algorithm (SHA1), Properties ()
0097FFB40C7F0000:error::digital envelope routines:EVP_DigestInit_ex:initialization error:crypto/evp/digest.c:178:
00A77FB50C7F0000:error::digital envelope routines:evp_generic_fetch:fetch failed:crypto/evp/evp_fetch.c:318:Global default library context, Algorithm (SHA1), Properties ()
00A77FB50C7F0000:error::digital envelope routines:EVP_DigestInit_ex:initialization error:crypto/evp/digest.c:178:
00F7FF9F0C7F0000:error::common libcrypto routines:ossl_namemap_add_names:internal error:crypto/core_namemap.c:310:Got number 12 when expecting 44
00F7FF9F0C7F0000:error::common libcrypto routines:ossl_namemap_add_names:internal error:crypto/core_namemap.c:310:Got number 78 when expecting 79
00F7FF9F0C7F0000:error::digital envelope routines:evp_generic_fetch:fetch failed:crypto/evp/evp_fetch.c:318:Global default library context, Algorithm (SHA1), Properties ()
00F7FF9F0C7F0000:error::digital envelope routines:EVP_DigestInit_ex:initialization error:crypto/evp/digest.c:178:
00F7FFB70C7F0000:error::common libcrypto routines:ossl_namemap_add_names:conflicting names:crypto/core_namemap.c:290:"SHA-1" has an existing different identity 12 (from "SHA1:SHA-1")
00F7FFB70C7F0000:error::common libcrypto routines:ossl_namemap_add_names:conflicting names:crypto/core_namemap.c:290:"SHA-512" has an existing different identity 78 (from "SHA2-512:SHA-512:SHA512")
00F7FFB70C7F0000:error::digital envelope routines:evp_generic_fetch:fetch failed:crypto/evp/evp_fetch.c:318:Global default library context, Algorithm (SHA1), Properties ()
00F7FFB70C7F0000:error::digital envelope routines:EVP_DigestInit_ex:initialization error:crypto/evp/digest.c:178:
00E77FB70C7F0000:error::common libcrypto routines:ossl_namemap_add_names:conflicting names:crypto/core_namemap.c:290:"SHA-1" has an existing different identity 12 (from "SHA1:SHA-1")
00C77FB60C7F0000:error::common libcrypto routines:ossl_namemap_add_names:conflicting names:crypto/core_namemap.c:290:"SHA-1" has an existing different identity 12 (from "SHA1:SHA-1")
00C77FB60C7F0000:error::common libcrypto routines:ossl_namemap_add_names:conflicting names:crypto/core_namemap.c:290:"SHA-512" has an existing different identity 78 (from "SHA2-512:SHA-512:SHA512")
00C77FB60C7F0000:error::digital envelope routines:evp_generic_fetch:fetch failed:crypto/evp/evp_fetch.c:318:Global default library context, Algorithm (SHA1), Properties ()
0027D1BC0C7F0000:error::common libcrypto routines:ossl_namemap_add_names:conflicting names:crypto/core_namemap.c:290:"SHA-1" has an existing different identity 12 (from "SHA1:SHA-1")
00C77FB60C7F0000:error::digital envelope routines:EVP_DigestInit_ex:initialization error:crypto/evp/digest.c:178:
0027D1BC0C7F0000:error::common libcrypto routines:ossl_namemap_add_names:conflicting names:crypto/core_namemap.c:290:"SHA-512" has an existing different identity 78 (from "SHA2-512:SHA-512:SHA512")
0027D1BC0C7F0000:error::digital envelope routines:evp_generic_fetch:fetch failed:crypto/evp/evp_fetch.c:318:Global default library context, Algorithm (SHA1), Properties ()
0027D1BC0C7F0000:error::digital envelope routines:EVP_DigestInit_ex:initialization error:crypto/evp/digest.c:178:
00E77FB70C7F0000:error::common libcrypto routines:ossl_namemap_add_names:conflicting names:crypto/core_namemap.c:290:"SHA-512" has an existing different identity 78 (from "SHA2-512:SHA-512:SHA512")
00E77FB70C7F0000:error::digital envelope routines:evp_generic_fetch:fetch failed:crypto/evp/evp_fetch.c:318:Global default library context, Algorithm (SHA1), Properties ()
00E77FB70C7F0000:error::digital envelope routines:EVP_DigestInit_ex:initialization error:crypto/evp/digest.c:178:
003751BD0C7F0000:error::common libcrypto routines:ossl_namemap_add_names:conflicting names:crypto/core_namemap.c:290:"SHA-1" has an existing different identity 12 (from "SHA1:SHA-1")
00D7FFB60C7F0000:error::common libcrypto routines:ossl_namemap_add_names:conflicting names:crypto/core_namemap.c:290:"SHA-1" has an existing different identity 12 (from "SHA1:SHA-1")
00D7FFB60C7F0000:error::common libcrypto routines:ossl_namemap_add_names:conflicting names:crypto/core_namemap.c:290:"SHA-512" has an existing different identity 78 (from "SHA2-512:SHA-512:SHA512")
00D7FFB60C7F0000:error::digital envelope routines:evp_generic_fetch:fetch failed:crypto/evp/evp_fetch.c:318:Global default library context, Algorithm (SHA1), Properties ()
00D7FFB60C7F0000:error::digital envelope routines:EVP_DigestInit_ex:initialization error:crypto/evp/digest.c:178:
003751BD0C7F0000:error::common libcrypto routines:ossl_namemap_add_names:conflicting names:crypto/core_namemap.c:290:"SHA-512" has an existing different identity 78 (from "SHA2-512:SHA-512:SHA512")
003751BD0C7F0000:error::digital envelope routines:evp_generic_fetch:fetch failed:crypto/evp/evp_fetch.c:318:Global default library context, Algorithm (SHA1), Properties ()
003751BD0C7F0000:error::digital envelope routines:EVP_DigestInit_ex:initialization error:crypto/evp/digest.c:178:
```

The program runs without errors when configured to spawn a single thread, so it seems like the namemap code has some concurrency bugs.

**Comment by paulidale** [comment] 2020-07-28 01:13
I can reproduce this locally.  Although not all that consistently.  Adding a `printf(3)` call in `thread()` helps a lot.

**Comment by paulidale** [comment] 2020-07-28 01:18
I've got a fix in #12545.

**Comment by link2xt** [comment] 2020-09-18 13:04
@paulidale Shouldn't this issue be closed since https://github.com/openssl/openssl/commit/79410c5f8b139c423be436810b4fe4de4637fc24 is merged?

**Comment by link2xt** [comment] 2020-09-18 13:05
@sfackler Maybe you can close the issue, looks like https://github.com/sfackler/rust-openssl/pull/1264 tests pass now.

**Closed** 2020-09-18 13:16 UTC
Labels: branch: master, triaged: bug
