### ISSUE TITLE
Test failure for test_ssl_new due to expired certificates

### ISSUE THREAD

**Issue by pepper-ankan** [openssl/openssl#18456] opened 2022-06-02 04:27 UTC
This had me scratching my head for a long time: we build openssl 1.1.1k daily for three different architectures, x86, aarch64 and darwin, and on June 1, 2022, they _all_ started to fail, with a test failure for `test_ssl_new`.

I know you'd like me to provide configuration details, etc., and I'll be happy to provide them if still necessary after the following analysis, which I think points to the root cause:

- Since the failure was _identical_ across all three platforms, and absolutely nothing in the build had changed on our side in ages, I started to suspect something to do with the date, and sure enough, setting the clock back to any time such that the test _finished running_ before June 1 2022 00:00:00 UTC resulted in passing tests/build.
- After learning about and using the verbosity flag for test runs, I isolated the failure to the sub-test using `test/ssl-tests/12-ct.conf`.  The error was significant: `... SSL routines:ssl3_read_bytes:sslv3 alert certificate expired`.
- I then discovered that `12-ct.conf.in` has six tests, out of which four use canned (test) certificates.  When I commented out these four (and adjusted the checked-in `12-ct.conf` accordingly), the entire suite started passing.
- This led me to believe that that the certs in question for these four tests, `test/certs/embeddedSCTs1.pem` and `test/certs/embeddedSCTs1_issuer.pem`, are probably set to _expire_ after June 1 2022 00:00:00 UTC.
- To verify, I tried the following:
```
$ openssl x509 -text < embeddedSCTs1.pem | grep 2022
            Not After : Jun  1 00:00:00 2022 GMT
$ openssl x509 -text < embeddedSCTs1_issuer.pem | grep 2022
            Not After : Jun  1 00:00:00 2022 GMT
```

Now, I can't be 100% certain that the expired certs are indeed what are causing the test failures, but it certainly looks that way.  If this is indeed the case, can we have valid replacement certs for these, so that the tests/builds pass?  Thank you.

**Comment by paulidale** [comment] 2022-06-02 04:34
Guess that this is fixed by #18446 and is a duplicate of #15179

**Comment by t8m** [comment] 2022-06-02 09:32
I'll keep this open for now so we do not get more duplicates.

**Comment by jxsl13** [comment] 2022-06-02 12:55
Thanks for the fast response.

**Comment by pepper-ankan** [comment] 2022-06-02 17:42
> Guessing that this is fixed by #18446 and is a duplicate of #15179

Yes, the fix works fine ... thanks for the very quick turnaround!

**Comment by sipatha** [comment] 2022-06-13 01:02
I have downloaded branch 1.1.1 with the merged fix and unfortunately run into more tests failures with the test summary below.

>         "../test/recipes/80-test_cmsapi.t ................... ok",
>         "../test/recipes/80-test_ct.t ....................... ",
>         "Dubious, test returned 1 (wstat 256, 0x100)",
>         "Failed 1/1 subtests ",
>         "../test/recipes/80-test_dane.t ..................... ok",

>         "../test/recipes/90-test_secmem.t ................... ok",
>         "../test/recipes/90-test_shlibload.t ................ ",
>         "Dubious, test returned 9 (wstat 2304, 0x900)",
>         "Failed 9/10 subtests ",
>         "../test/recipes/90-test_srp.t ...................... ok",

>         "",
>         "Test Summary Report",
>         "-------------------",
>         "../test/recipes/80-test_ct.t                     (Wstat: 256 Tests: 1 Failed: 1)",
>         "  Failed test:  1",
>         "  Non-zero exit status: 1",
>         "../test/recipes/90-test_shlibload.t              (Wstat: 2304 Tests: 10 Failed: 9)",
>         "  Failed tests:  1-9",
>         "  Non-zero exit status: 9",
>         "Files=158, Tests=2643, 71 wallclock secs ( 1.02 usr  0.12 sys + 61.67 cusr  8.46 csys = 71.27 CPU)",
>         "Result: FAIL",
>         "make[1]: Leaving directory '/u02/openssl/src'"

**Comment by mattcaswell** [comment] 2022-06-14 14:22
Release date for 3.0.4/1.1.1p has been set as 21st June 2022.

**Comment by jxsl13** [comment] 2022-07-14 07:37
@t8m has this been resolved and can this issue be closed?

**Comment by t8m** [comment] 2022-07-14 08:15
Yeah, now that there were releases where the certificates are renewed, I think we can close this.

**Closed by t8m** 2022-07-14 08:15 UTC
Labels: branch: master, branch: 1.1.1, triaged: bug, resolved: fixed, branch: 3.0
