### ISSUE TITLE
Is there a way to remove function name logging?

### ISSUE THREAD

**Issue by codetronik** [openssl/openssl#20258] opened 2023-02-10 05:05 UTC
I reverse engineered binary including openssl and found below.

```
__int64 __fastcall sub_34C094(__int64 a1, __int64 a2, __int64 a3, __int64 a4)
{
  if ( *(_QWORD *)(**(_QWORD **)(a4 + 24) + 368LL) )
  {
    return (unsigned int)(*(__int64 (__fastcall **)(__int64, __int64, __int64, __int64))(**(_QWORD **)(a4 + 24) + 368LL))(
                           a1,
                           a2,
                           a3,
                           a4);
  }
  else
  {
    sub_1E2C78();
    sub_1E2E20(&unk_78D910, 32LL, "ossl_ecdh_compute_key"); <--- found!
    sub_1E2FD4(16LL, 160LL, 0LL);
    return 0;
  }
}
```

This is the original code.
```
int ossl_ecdh_compute_key(unsigned char **psec, size_t *pseclen,
                          const EC_POINT *pub_key, const EC_KEY *ecdh)
{
    if (ecdh->group->meth->ecdh_compute_key == NULL) {
        ERR_raise(ERR_LIB_EC, EC_R_CURVE_DOES_NOT_SUPPORT_ECDH);
        return 0;
    }

    return ecdh->group->meth->ecdh_compute_key(psec, pseclen, pub_key, ecdh);
}
```

Build options were also found in the binary.
```
char *__fastcall sub_6A6C80(int a1)
{
  if ( a1 < 5 )
  {
    if ( a1 < 2 )
    {
      if ( a1 >= 1 )
      {
        return "compiler: aarch64-linux-android29-clang -fPIC -pthread -Wa,--noexecstack -Qunused-arguments -fdata-sectio"
               "ns -ffunction-sections -fno-rtti -g0 -mllvm -sub -mllvm -sub_loop=1 -mllvm -sobf -DOPENSSL_USE_NODELETE -"
               "DOPENSSL_PIC -DOPENSSL_BUILDING_OPENSSL -DNDEBUG -D__ANDROID_API__=29";
      }
      else
      {
        if ( a1 )
          return (char *)&unk_7BDD18;
        return (char *)&unk_7BDB80;
      }
    }
```

Logs appear to be added to the build process. 
I want to remove them in security. Can I remove it as an option?

**Comment by paulidale** [comment] 2023-02-10 06:46
Why?  Obscurity isn't security.

The answer is no.  These strings are always included.
Well, it is possible but you'd need to write a program that edited the binary and removed the strings.

**Comment by Amena35** [comment] 2023-02-10 07:14
@paulidale #19307

**Comment by paulidale** [comment] 2023-02-10 07:43
I'm not seeing the relationship.  That PR is talking about secrets being embedded (which would be very bad).  The report here is asking about function names (that wouldn't be difficult for a competent reverse engineer to reproduce if they were omitted) and the build options used which I also have difficulty thinking of as security relevant secret.

**Comment by t8m** [comment] 2023-02-12 07:36
I think in some OPENSSL_SMALL_FOOTPRINT build it might be useful to avoid the RO memory space occupied by those strings.

**Comment by t8m** [comment] 2023-02-12 07:37
So no, currently it is not possible.

**Comment by mattcaswell** [comment] 2024-01-31 11:46
Closing since this is marked as resolved.

**Closed by mattcaswell** 2024-01-31 11:46 UTC
Labels: triaged: question, resolved: answered
