### ISSUE TITLE
openssl-1.1.1 version, cipher suits dont match at server, the server sends the error message, the openssl client keeps retrying(resending client hello) message

### ISSUE THREAD

**Issue by mkaroshi** [openssl/openssl#12552] opened 2020-07-28 21:56 UTC
openssl client keeps retrying(resending client hello) when it receives ciphers dont match error from ssl server.

**Comment by kaduk** [comment] 2020-07-29 17:29
That sounds like expected behavior for DTLS, when a ServerHello or alert are totally unauthenticated, and the connection might succeed if retried.  If this is regular TLS, on the other hand, it would be weird.  Please clarify.

**Comment by mkaroshi** [comment] 2020-07-31 17:31
We are not using DTLS, we are using TLS only.

**Comment by kaduk** [comment] 2020-08-03 22:24
Are you in a position where you can obtain a packet capture (with, e.g., tcpdump or wireshark) of the behavior in question and post it publicly?  That would seem like the fastest path to understanding the issue.

**Comment by mkaroshi** [comment] 2020-08-06 02:22
i was able to reproduce the issue. The client side ssl version is
[mkaroshi@caxv-mkaroshi-2 thud]$ openssl version
OpenSSL 1.0.2k-fips  26 Jan 2017

server side openssl version is 
diag@8180:~$ openssl version
OpenSSL 1.1.1g  21 Apr 2020

the wireshark capture is attached.
[ha.txt](https://github.com/openssl/openssl/files/5032168/ha.txt)

**Comment by mattcaswell** [comment] 2020-08-06 08:45
> when it receives ciphers don't match error from ssl server.

In your wireshark trace it looks like this particular instance  is the result of a "certificate expired" alert.

What is the application here? Is this your own custom application or some third party software?

**Comment by mkaroshi** [comment] 2020-08-06 15:24
gnmi client sending request to ha proxy. Both are open source. Any error comes from the server, the client keeps retrying.
    On Thursday, August 6, 2020, 01:45:45 AM PDT, mattcaswell <notifications@github.com> wrote:  
 
 



when it receives ciphers don't match error from ssl server.


In your wireshark trace it looks like this particular instance is the result of a "certificate expired" alert.

What is the application here? Is this your own custom application or some third party software?

**Comment by mattcaswell** [comment] 2020-08-06 15:30
> gnmi client sending request to ha proxy. Both are open source. Any error comes from the server, the client keeps retrying.

This looks to me like a problem on the client side. I'd suggest contacting the developers of your client software.

**Comment by mattcaswell** [comment] 2020-09-24 15:31
Can this be closed now?

**Comment by mkaroshi** [comment] 2020-09-24 15:58
yes.
    On Thursday, September 24, 2020, 08:31:29 AM PDT, mattcaswell <notifications@github.com> wrote:  
 
 


Can this be closed now?

**Comment by mattcaswell** [comment] 2020-09-24 16:15
Great. Closing.

**Closed by mattcaswell** 2020-09-24 16:15 UTC
