### ISSUE TITLE
ECDSA failure in openssl speed ecdsa

### ISSUE THREAD

**Issue by AnnieYousar** [openssl/openssl#10225] opened 2019-10-20 13:36 UTC
My freshly build 
```
$ openssl-1.1.1d> openssl speed ecdsa
```
breaks with 
ECDSA failure 
139728780396288:error:100AE081:elliptic curve routines:EC_GROUP_new_by_curve_name:unknown group:crypto/ec/ec_curve.c:3132:
after doing the 571 bit verify.
The table at the end of the tests 
``` 
                             sign    verify    sign/s verify/s
 160 bit ecdsa (secp160r1)   0.0002s   0.0002s   4123.4   4590.7
 192 bit ecdsa (nistp192)   0.0003s   0.0003s   3368.7   3870.4
 224 bit ecdsa (nistp224)   0.0004s   0.0004s   2263.3   2760.1
....
 409 bit ecdsa (nistb409)   0.0013s   0.0026s    752.0    381.8
 571 bit ecdsa (nistb571)   0.0030s   0.0059s    335.0    170.8
 253 bit ecdsa (X25519)   0.0000s   0.0000s      inf      inf
```
suggests, that the Curve25519 test fails.
/Annie.

**Comment by kroeckx** [comment] 2019-10-20 14:36
I can not reproduce this. x25519 also isn't ecdsa.

**Comment by romen** [comment] 2019-10-25 14:26
I also can't reproduce this. @AnnieYousar can you give use more details or should we close this?

**Closed** 2020-07-28 23:07 UTC
Labels: unresolved
