### ISSUE TITLE
3.3.2 build test fail in homebrew on M1 macbook

### ISSUE THREAD

**Issue by noirchen** [openssl/openssl#25508] opened 2024-09-22 05:54 UTC
I am upgrading openssl from 3.3.1 to 3.3.2 in homebrew on M1 macbook, and the test fails
```
brew upgrade openssl
==> Upgrading 1 outdated package:
openssl 3.3.1 -> 3.3.2
==> Fetching openssl@3
Warning: Building openssl@3 from source as the bottle needs:
- HOMEBREW_CELLAR: /opt/homebrew/Cellar (yours is /Applications/homebrew/Cellar)
- HOMEBREW_PREFIX: /opt/homebrew (yours is /Applications/homebrew)
==> Downloading https://github.com/openssl/openssl/releases/download/openssl-3.3.2/openssl-3.3.2.tar.gz
==> Downloading from https://objects.githubusercontent.com/github-production-release-asset-2e65be/7634677/c1714487-6cf3-
################################################################################################################# 100.0%
==> Upgrading openssl
  3.3.1 -> 3.3.2
==> perl ./Configure --prefix=/Applications/homebrew/Cellar/openssl@3/3.3.2 --openssldir=/Applications/homebrew/etc/open
==> make
==> make install MANDIR=/Applications/homebrew/Cellar/openssl@3/3.3.2/share/man MANSUFFIX=ssl
==> make test TESTS=-test_afalg
Last 15 lines from /Users/aria/Library/Logs/Homebrew/openssl@3/04.make:
99-test_fuzz_x509.t ..................... ok

Test Summary Report
-------------------
80-test_cmp_http.t                    (Wstat: 1280 Tests: 6 Failed: 5)
  Failed tests:  1-5
  Non-zero exit status: 5
82-test_ocsp_cert_chain.t             (Wstat: 256 Tests: 3 Failed: 1)
  Failed test:  3
  Non-zero exit status: 1
Files=313, Tests=3641, 400 wallclock secs ( 3.44 usr  0.66 sys + 190.47 cusr 58.43 csys = 253.00 CPU)
Result: FAIL
make[2]: *** [run_tests] Error 1
make[1]: *** [_tests] Error 2
make: *** [tests] Error 2
```

**Comment by tom-cosgrove-arm** [comment] 2024-09-23 09:15
Is this the same issue as #22467?

**Comment by noirchen** [comment] 2024-09-23 09:19
> Is this the same issue as #22467?

what about `82-test_ocsp_cert_chain.t` failure?

**Comment by noirchen** [comment] 2024-09-24 01:17
@Sashan reminded me of the possible proxy setting, and after I unset http and https proxy, the build runs smoothly.

**Comment by Sashan** [comment] 2024-09-24 07:43
I'm going to close it as a duplicate of #22467

**Closed by Sashan** 2024-09-24 07:43 UTC
Labels: issue: bug report
