### ISSUE TITLE
OpenSSL 3.2.0 is broken for `powerpc-apple-darwin`: `aesp8-ppc.s: Invalid mnemonic 'xxlor'` etc.

### ISSUE THREAD

**Issue by barracuda156** [openssl/openssl#23039] opened 2023-12-13 23:29 UTC
```
/opt/local/bin/perl5 ./util/mkpod2html.pl -i "doc/man3/SSL_CTX_set_options.pod" -o doc/html/man3/SSL_CTX_set_options.html -t "SSL_CTX_set_options" -r "./doc"
/usr/bin/gcc-4.2 -fPIC -fno-common -arch ppc -std=gnu9x -Wa,-force_cpusubtype_ALL -pipe -Os -arch ppc -DB_ENDIAN -DOPENSSL_PIC -DOPENSSLDIR="\"/opt/local/libexec/openssl3/etc/openssl\"" -DENGINESDIR="\"/opt/local/libexec/openssl3/lib/engines-3\"" -DMODULESDIR="\"/opt/local/libexec/openssl3/lib/ossl-modules\"" -D_REENTRANT -DOPENSSL_BUILDING_OPENSSL -DZLIB -DNDEBUG -I/opt/local/include -c -o crypto/aes/libcrypto-shlib-aesp8-ppc.o crypto/aes/aesp8-ppc.s
crypto/aes/aesp8-ppc.s:2343:Invalid mnemonic 'xxlor'
crypto/aes/aesp8-ppc.s:2345:Invalid mnemonic 'xxlor'
crypto/aes/aesp8-ppc.s:2350:Invalid mnemonic 'lxvw4x'
crypto/aes/aesp8-ppc.s:2411:Invalid mnemonic 'xxlor'
crypto/aes/aesp8-ppc.s:2412:Invalid mnemonic 'vpermxor'
crypto/aes/aesp8-ppc.s:2421:Invalid mnemonic 'xxlor'
crypto/aes/aesp8-ppc.s:2422:Invalid mnemonic 'vpermxor'
crypto/aes/aesp8-ppc.s:2432:Invalid mnemonic 'xxlor'
crypto/aes/aesp8-ppc.s:2433:Invalid mnemonic 'vpermxor'
crypto/aes/aesp8-ppc.s:2443:Invalid mnemonic 'xxlor'
crypto/aes/aesp8-ppc.s:2444:Invalid mnemonic 'vpermxor'
crypto/aes/aesp8-ppc.s:2454:Invalid mnemonic 'xxlor'
crypto/aes/aesp8-ppc.s:2455:Invalid mnemonic 'vpermxor'
crypto/aes/aesp8-ppc.s:2465:Invalid mnemonic 'xxlor'
crypto/aes/aesp8-ppc.s:2466:Invalid mnemonic 'vpermxor'
crypto/aes/aesp8-ppc.s:2492:Invalid mnemonic 'xxlor'
crypto/aes/aesp8-ppc.s:2510:Invalid mnemonic 'xxlor'
crypto/aes/aesp8-ppc.s:2511:Invalid mnemonic 'vpermxor'
crypto/aes/aesp8-ppc.s:2527:Invalid mnemonic 'xxlor'
crypto/aes/aesp8-ppc.s:2528:Invalid mnemonic 'vpermxor'
crypto/aes/aesp8-ppc.s:2549:Invalid mnemonic 'xxlor'
crypto/aes/aesp8-ppc.s:2550:Invalid mnemonic 'vpermxor'
crypto/aes/aesp8-ppc.s:2566:Invalid mnemonic 'xxlor'
crypto/aes/aesp8-ppc.s:2567:Invalid mnemonic 'vpermxor'
crypto/aes/aesp8-ppc.s:2583:Invalid mnemonic 'xxlor'
crypto/aes/aesp8-ppc.s:2584:Invalid mnemonic 'vpermxor'
crypto/aes/aesp8-ppc.s:2606:Invalid mnemonic 'xxlor'
crypto/aes/aesp8-ppc.s:2607:Invalid mnemonic 'xxlor'
crypto/aes/aesp8-ppc.s:2608:Invalid mnemonic 'vpermxor'
crypto/aes/aesp8-ppc.s:2609:Invalid mnemonic 'xxlor'
crypto/aes/aesp8-ppc.s:2642:Invalid mnemonic 'xxlor'
crypto/aes/aesp8-ppc.s:3021:Invalid mnemonic 'xxlor'
crypto/aes/aesp8-ppc.s:3023:Invalid mnemonic 'xxlor'
crypto/aes/aesp8-ppc.s:3028:Invalid mnemonic 'lxvw4x'
crypto/aes/aesp8-ppc.s:3081:Invalid mnemonic 'xxlor'
crypto/aes/aesp8-ppc.s:3082:Invalid mnemonic 'vpermxor'
crypto/aes/aesp8-ppc.s:3091:Invalid mnemonic 'xxlor'
crypto/aes/aesp8-ppc.s:3092:Invalid mnemonic 'vpermxor'
crypto/aes/aesp8-ppc.s:3102:Invalid mnemonic 'xxlor'
crypto/aes/aesp8-ppc.s:3103:Invalid mnemonic 'vpermxor'
crypto/aes/aesp8-ppc.s:3113:Invalid mnemonic 'xxlor'
crypto/aes/aesp8-ppc.s:3114:Invalid mnemonic 'vpermxor'
crypto/aes/aesp8-ppc.s:3124:Invalid mnemonic 'xxlor'
crypto/aes/aesp8-ppc.s:3125:Invalid mnemonic 'vpermxor'
crypto/aes/aesp8-ppc.s:3135:Invalid mnemonic 'xxlor'
crypto/aes/aesp8-ppc.s:3136:Invalid mnemonic 'vpermxor'
crypto/aes/aesp8-ppc.s:3162:Invalid mnemonic 'xxlor'
crypto/aes/aesp8-ppc.s:3180:Invalid mnemonic 'xxlor'
crypto/aes/aesp8-ppc.s:3181:Invalid mnemonic 'vpermxor'
crypto/aes/aesp8-ppc.s:3197:Invalid mnemonic 'xxlor'
crypto/aes/aesp8-ppc.s:3198:Invalid mnemonic 'vpermxor'
crypto/aes/aesp8-ppc.s:3219:Invalid mnemonic 'xxlor'
crypto/aes/aesp8-ppc.s:3220:Invalid mnemonic 'vpermxor'
crypto/aes/aesp8-ppc.s:3236:Invalid mnemonic 'xxlor'
crypto/aes/aesp8-ppc.s:3237:Invalid mnemonic 'vpermxor'
crypto/aes/aesp8-ppc.s:3253:Invalid mnemonic 'xxlor'
crypto/aes/aesp8-ppc.s:3254:Invalid mnemonic 'vpermxor'
crypto/aes/aesp8-ppc.s:3276:Invalid mnemonic 'xxlor'
crypto/aes/aesp8-ppc.s:3277:Invalid mnemonic 'xxlor'
crypto/aes/aesp8-ppc.s:3278:Invalid mnemonic 'vpermxor'
crypto/aes/aesp8-ppc.s:3279:Invalid mnemonic 'xxlor'
crypto/aes/aesp8-ppc.s:3310:Invalid mnemonic 'xxlor'
make[1]: *** [crypto/aes/libcrypto-shlib-aesp8-ppc.o] Error 1
```

**Comment by barracuda156** [comment] 2023-12-13 23:40
@t8m 3d3a7ecd1ae5ab08d22041f7b3b035c34f12fa02 commit has broken PowerPC builds on Darwin. Could we please fix that?

**Comment by barracuda156** [comment] 2023-12-13 23:41
And we also have this unfixed for PowerPC: https://github.com/openssl/openssl/issues/21354

**Comment by t8m** [comment] 2023-12-14 09:29
This should be fixed by #22860

**Comment by tom-cosgrove-arm** [comment] 2023-12-14 10:15
So is this issue a duplicate of #22818?

**Comment by t8m** [comment] 2023-12-14 10:20
> So is this issue a duplicate of #22818?

Yes, duplicate of #22818

**Closed by t8m** 2023-12-14 10:20 UTC
Labels: issue: bug report

**Comment by barracuda156** [comment] 2023-12-14 16:47
> This should be fixed by #22860 

@t8m Thank you! I will test it tomorrow, but from comments it looks good.

Any chance of addressing #21354 or assigning someone to deal with it?

**Comment by t8m** [comment] 2023-12-14 17:37
Unfortunately that would have to be done by the PPC platform community maintainers.

**Comment by barracuda156** [comment] 2023-12-14 17:38
@t8m If you could tag them in the issue, it would be very helpful.
