### ISSUE TITLE
No need to link explicitly with libpthread on Solaris

### ISSUE THREAD

**Issue by darrenmoffat** [openssl/openssl#19607] opened 2022-11-04 12:11 UTC
Starting with Solaris 10 (released in Jan 2005) libpthread is a filter library over libc and all Solaris processes are always multi-threaded (even if they often only contain a single thread).  As such it has not been necessary to pass any information to the compiler or linker about libpthread via -lpthread or -pthreads.  This is independent of compiler (gcc, Studio or LLVM).

This means at any Illumos/OpenSolaris derived releases also don't need to explicitly link with libpthread.

Solaris 10 is the oldest release of Solaris still getting fixes from Oracle, Solaris 9 for example hasn't had any fixes since 2014 so there should be no need to support such an old OS release in OpenSSL 3.x

Oracle will be applying this patch to the OpenSSL 3.x builds included in Solaris 11.4

[050-lpthread.patch.txt](https://github.com/openssl/openssl/files/9938068/050-lpthread.patch.txt)

**Comment by t8m** [comment] 2022-11-04 12:36
Unless this breaks builds this is not a bug fix. But IMO should be safe to apply to the master branch.

**Comment by t8m** [comment] 2022-11-04 12:37
Would you submit a PR with the patch?

**Comment by darrenmoffat** [comment] 2022-11-04 16:43
It doesn't break builds of OpenSSL 3.x on Solaris.  It was found because the presence of the unneeded libpthread as a dependency causes our very strict linker checks to raise and error when core Oracle Solaris 11.4 components are converted over from OpenSSL 1.0.2 to OpenSSL 3.0.x.

PR #19611 submitted - I'm a first time contributor so it needs a maintainer to approve the workflow to run the build bots.

**Comment by vladak** [comment] 2023-01-18 13:33
Looks like the related PR was merged in so this issue can be closed.

**Closed** 2023-01-18 15:09 UTC
Labels: triaged: feature
