### ISSUE TITLE
OpenSSL "ca" - "error while loading serial number"

### ISSUE THREAD

**Issue by Lidiaaa** [openssl/openssl#8817] opened 2019-04-23 19:12 UTC
OpenSSL> ca -days 365 -policy policy_anything -keyfile c:\ec\CA\CAkhasanova.key -in c:\ec\CA\CAkhas.req -selfsign -out c:\ec\CA\CA.crt -outdir c:\ec\CA
Using configuration from C:\Program Files\OpenSSL-Win64\bin\openssl.cfg
Can't load ./.rnd into RNG
9208:error:2406F079:random number generator:RAND_load_file:Cannot open file:crypto\rand\randfile.c:98:Filename=./.rnd
Enter pass phrase for c:\ec\CA\CAkhasanova.key:
c:/ec/serial: No such file or directory
error while loading serial number
9208:error:02001002:system library:fopen:No such file or directory:crypto\bio\bss_file.c:72:fopen('c:/ec/serial','r')
9208:error:2006D080:BIO routines:BIO_new_file:no such file:crypto\bio\bss_file.c:79:
error in ca

**Comment by mattcaswell** [comment] 2019-04-24 10:58
Dupe of #8816

**Closed by mattcaswell** 2019-04-24 10:58 UTC
