### ISSUE TITLE
OCSP Request Response with NONCE validation fails

### ISSUE THREAD

**Issue by lucas75018** [openssl/openssl#1887] opened 2016-11-09 17:08 UTC
Trying to validate a OCSP response but I stumbled into a issue.
The NONCE may not be validated.

The context ...
Can you only OpenSSL since the the server is located in a company network behind a HTTP proxy
So I had to split the thing in three steps
1. request generation using OpenSSL
2. OCSP request using CURL
3. response validation using OpenSSL
that works perfectly except the validation of the NONCE.

In a nutshell I do 

    openssl ocsp -issuer %issuercert% -cert %certfile% -CAfile %cacert% -reqout %ocsp_req% -text
    curl.exe %curl_opt% --request POST --data-binary @%ocsp_req% %ocsp_responder% --header "Content-Type:application/ocsp-request" --proxy %proxy% --output %ocsp_rsp%
    openssl ocsp -issuer %issuercert% -cert %certfile% -CAfile %cacert% -reqin %ocsp_req% -respin %ocsp_rsp% -text

In detail...
The first command works perfectly and creates a request.
The second sends the request and receives the ocsp response. The response contains the request's NONCE.
The third fails because OpenSSL seems to create a new NONCE in the request when loading where as the response contains the NONCE generated in the first command.

    ########
    ######## Creating OCSP request
    ########
    OCSP Request Data:
        Version: 1 (0x0)
        Requestor List:
            Certificate ID:
              Hash Algorithm: sha1
              Issuer Name Hash: A3EC276D81A3B6B57311CA55D901FFB700061718
              Issuer Key Hash: 8B4B6DEDD329B90619EC3939A9F097846ACBEFDF
              Serial Number: 7BA9BF38FFC6C26B2B90747C333F0B26835E75F8
        Request Extensions:
            OCSP Nonce:
                041085856E74263DF5CF50EA04711FE9C085
    ########
    ######## Sending OCSP request
    ########
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
    100  1778  100  1654  100   124  15174   1137 --:--:-- --:--:-- --:--:-- 15174
    ########
    ######## Validating OCSP response
    ########
    OCSP Request Data:
        Version: 1 (0x0)
        Requestor List:
            Certificate ID:
              Hash Algorithm: sha1
              Issuer Name Hash: A3EC276D81A3B6B57311CA55D901FFB700061718
              Issuer Key Hash: 8B4B6DEDD329B90619EC3939A9F097846ACBEFDF
              Serial Number: 7BA9BF38FFC6C26B2B90747C333F0B26835E75F8
        Request Extensions:
            OCSP Nonce:
                04106C61AF5321946B97372C8366D758F792
    OCSP Response Data:
        OCSP Response Status: successful (0x0)
        Response Type: Basic OCSP Response
        Version: 1 (0x0)
        Responder Id: C = BM, O = QuoVadis Limited, OU = OCSP Responder, CN = QuoVadis OCSP Authority Signature
        Produced At: Nov  9 16:52:30 2016 GMT
        Responses:
        Certificate ID:
          Hash Algorithm: sha1
          Issuer Name Hash: A3EC276D81A3B6B57311CA55D901FFB700061718
          Issuer Key Hash: 8B4B6DEDD329B90619EC3939A9F097846ACBEFDF
          Serial Number: 7BA9BF38FFC6C26B2B90747C333F0B26835E75F8
        Cert Status: good
        This Update: Nov  9 16:52:30 2016 GMT
        Next Update: Nov 11 16:52:30 2016 GMT

        Response Extensions:
            OCSP Nonce:
                041085856E74263DF5CF50EA04711FE9C085
            valid:
                ..
        Signature Algorithm: sha256WithRSAEncryption
             56:cf:39:ff:5e:2b:59:df:ef:53:a3:2d:63:10:d0:c6:da:72:
             41:39:d3:b1:a4:91:75:10:61:ae:2f:0a:5f:24:e0:72:f1:ed:
             b3:af:9d:3c:a3:83:50:7b:e8:26:5e:b9:ab:cd:cd:84:fb:59:
             4d:e6:0e:b7:54:72:6a:3b:74:f6:4a:80:88:22:53:54:24:b6:
             79:4c:ea:4a:5c:2a:a2:cc:62:92:40:35:55:f4:a8:5d:fd:4b:
             fd:40:97:12:42:96:1a:b0:7b:11:db:12:ae:a5:b2:fa:82:41:
             aa:83:6d:28:88:ed:c8:c3:4e:27:e1:4f:99:30:4a:5d:94:e9:
             96:d3:31:14:c5:cc:73:f6:ed:c5:b4:fa:73:b8:5f:f5:45:f5:
             16:8a:64:38:c7:f8:7e:13:29:d5:aa:36:0a:44:a9:6b:80:01:
             1d:4e:4c:c7:9a:37:59:67:49:3e:d4:24:f4:eb:50:42:25:7c:
             95:f3:be:54:87:15:be:6e:bd:be:47:59:0a:c5:d6:c5:ad:f0:
             5e:31:7c:a9:8f:ea:a8:f1:2d:d0:35:44:f1:c0:f2:91:33:f5:
             a8:0a:ca:d3:66:7a:6a:89:51:c5:82:90:b3:f1:61:b7:d8:eb:
             77:cb:53:29:a9:ea:a8:ee:d2:59:6a:cd:33:b8:bc:2b:87:95:
             d7:6d:92:f1
    Certificate:
        Data:
            Version: 3 (0x2)
            Serial Number:
                2d:26:48:c0:31:f6:49:7e:48:0e:9d:9a:cb:59:b1:7f:8a:d3:fa:4e
        Signature Algorithm: sha256WithRSAEncryption
            Issuer: C=BM, O=QuoVadis Limited, OU=Root Certification Authority, CN=QuoVadis Root Certification Authority
            Validity
                Not Before: Apr 12 14:26:50 2016 GMT
                Not After : Apr 12 14:26:50 2019 GMT
            Subject: C=BM, O=QuoVadis Limited, OU=OCSP Responder, CN=QuoVadis OCSP Authority Signature
            Subject Public Key Info:
                Public Key Algorithm: rsaEncryption
                    Public-Key: (2048 bit)
                    Modulus:
                        00:bc:33:9d:30:95:d5:bb:da:25:ff:0e:6c:92:af:
                        e4:73:b1:57:d5:4e:5a:88:b0:e7:5f:ab:5c:a9:cd:
                        a3:46:63:6c:be:45:31:b9:ad:04:c6:0c:f8:0b:7c:
                        c1:5f:c7:6c:59:b8:63:9a:65:64:9a:77:16:14:a9:
                        7e:9c:fc:9e:10:4b:fd:da:0e:01:86:69:ea:c8:f6:
                        f3:dd:d5:81:28:45:56:ac:54:a3:7b:9f:81:c5:7c:
                        12:f6:e5:17:1e:81:e1:fc:4f:c6:aa:f0:e2:94:df:
                        9f:fb:6d:67:f5:03:30:e1:e5:a7:5f:58:2f:5f:34:
                        a0:51:f5:33:b4:60:4f:41:6e:a6:3c:f6:ed:e2:80:
                        5e:ea:13:3b:1f:4e:6a:04:fa:db:c0:73:90:af:8b:
                        ab:78:36:5c:be:89:02:41:a0:52:a1:14:2b:df:51:
                        1e:35:59:a0:0c:07:92:06:3a:95:9d:9b:cd:ed:d2:
                        f1:d7:37:db:d1:1e:11:41:52:a6:20:15:5a:c4:2f:
                        4e:41:da:bd:24:c9:20:f0:85:a6:26:5f:dd:c4:4d:
                        72:c1:0c:03:2b:95:d8:95:35:41:8c:7f:12:d1:c2:
                        d1:5a:14:2c:2b:6c:c9:b9:23:a3:ab:7e:38:68:29:
                        1d:0f:84:59:01:b7:74:3f:81:4e:cd:2b:78:b0:79:
                        dd:dd
                    Exponent: 65537 (0x10001)
            X509v3 extensions:
                X509v3 Basic Constraints:
                    CA:FALSE
                OCSP No Check:

                X509v3 Key Usage: critical
                    Digital Signature
                X509v3 Extended Key Usage:
                    OCSP Signing
                X509v3 Authority Key Identifier:
                    keyid:8B:4B:6D:ED:D3:29:B9:06:19:EC:39:39:A9:F0:97:84:6A:CB:EF:DF

                X509v3 Subject Key Identifier:
                    03:E2:CF:E2:88:9C:EB:FA:23:71:D5:52:FE:CE:4C:7A:7D:42:A7:98
        Signature Algorithm: sha256WithRSAEncryption
             bb:9a:b5:7d:2f:7c:02:b3:29:b3:a7:39:b3:12:e0:76:07:76:
             92:a4:ad:00:1a:f6:85:2c:19:63:7d:83:3c:c9:40:12:c8:f3:
             18:e6:4c:82:17:96:84:98:11:fe:16:c1:eb:ad:42:97:17:7f:
             d5:64:9f:0b:0a:14:75:87:a6:aa:76:2e:47:2e:80:1f:02:54:
             b6:2f:ad:99:bf:a6:0b:f1:e6:10:5b:96:cb:3f:63:ed:1b:1a:
             f5:4b:a6:9e:36:a5:38:fd:cc:9c:cd:69:da:22:11:5f:8d:a8:
             c5:00:3d:7d:26:3b:c7:43:7d:ae:22:e3:75:da:f2:78:5b:42:
             b6:ef:44:6b:d1:ca:63:4b:b3:1d:b6:9c:3c:52:d7:07:80:25:
             8b:96:4f:a4:41:36:1a:66:8f:e4:d7:f9:72:38:09:7d:20:30:
             25:06:b1:75:af:72:23:e9:6b:15:1e:3c:22:52:97:dd:43:0e:
             f5:5c:5d:7f:1d:7c:d3:ce:bc:3f:6a:5d:f8:f7:d2:8d:ee:4f:
             49:bb:8f:8c:3c:3f:ba:5c:cd:78:7f:cb:2b:95:3c:f5:1e:cc:
             f2:52:5a:7d:f3:34:3a:ed:43:97:4f:c7:59:98:be:a8:eb:56:
             83:76:65:0b:6a:27:71:41:ba:06:64:1d:6d:41:da:4e:ca:8f:
             ca:b4:d7:07
    -----BEGIN CERTIFICATE-----
    MIID/zCCAuegAwIBAgIULSZIwDH2SX5IDp2ay1mxf4rT+k4wDQYJKoZIhvcNAQEL
    BQAwfzELMAkGA1UEBhMCQk0xGTAXBgNVBAoTEFF1b1ZhZGlzIExpbWl0ZWQxJTAj
    BgNVBAsTHFJvb3QgQ2VydGlmaWNhdGlvbiBBdXRob3JpdHkxLjAsBgNVBAMTJVF1
    b1ZhZGlzIFJvb3QgQ2VydGlmaWNhdGlvbiBBdXRob3JpdHkwHhcNMTYwNDEyMTQy
    NjUwWhcNMTkwNDEyMTQyNjUwWjBtMQswCQYDVQQGEwJCTTEZMBcGA1UEChMQUXVv
    VmFkaXMgTGltaXRlZDEXMBUGA1UECxMOT0NTUCBSZXNwb25kZXIxKjAoBgNVBAMT
    IVF1b1ZhZGlzIE9DU1AgQXV0aG9yaXR5IFNpZ25hdHVyZTCCASIwDQYJKoZIhvcN
    AQEBBQADggEPADCCAQoCggEBALwznTCV1bvaJf8ObJKv5HOxV9VOWoiw51+rXKnN
    o0ZjbL5FMbmtBMYM+At8wV/HbFm4Y5plZJp3FhSpfpz8nhBL/doOAYZp6sj2893V
    gShFVqxUo3ufgcV8EvblFx6B4fxPxqrw4pTfn/ttZ/UDMOHlp19YL180oFH1M7Rg
    T0Fupjz27eKAXuoTOx9OagT628BzkK+Lq3g2XL6JAkGgUqEUK99RHjVZoAwHkgY6
    lZ2bze3S8dc329EeEUFSpiAVWsQvTkHavSTJIPCFpiZf3cRNcsEMAyuV2JU1QYx/
    EtHC0VoULCtsybkjo6t+OGgpHQ+EWQG3dD+BTs0reLB53d0CAwEAAaOBhDCBgTAJ
    BgNVHRMEAjAAMA8GCSsGAQUFBzABBQQCBQAwDgYDVR0PAQH/BAQDAgeAMBMGA1Ud
    JQQMMAoGCCsGAQUFBwMJMB8GA1UdIwQYMBaAFItLbe3TKbkGGew5Oanwl4Rqy+/f
    MB0GA1UdDgQWBBQD4s/iiJzr+iNx1VL+zkx6fUKnmDANBgkqhkiG9w0BAQsFAAOC
    AQEAu5q1fS98ArMps6c5sxLgdgd2kqStABr2hSwZY32DPMlAEsjzGOZMgheWhJgR
    /hbB661Clxd/1WSfCwoUdYemqnYuRy6AHwJUti+tmb+mC/HmEFuWyz9j7Rsa9Uum
    njalOP3MnM1p2iIRX42oxQA9fSY7x0N9riLjddryeFtCtu9Ea9HKY0uzHbacPFLX
    B4Ali5ZPpEE2GmaP5Nf5cjgJfSAwJQaxda9yI+lrFR48IlKX3UMO9Vxdfx180868
    P2pd+PfSje5PSbuPjDw/ulzNeH/LK5U89R7M8lJaffM0Ou1Dl0/HWZi+qOtWg3Zl
    C2oncUG6BmQdbUHaTsqPyrTXBw==
    -----END CERTIFICATE-----
    Nonce Verify error
    ######## VALIDATION FAILED ########

**Comment by mattcaswell** [comment] 2018-01-18 16:04
Linked issue indicates that there was an error in the original command line and this is working as intended and as documented. Closing.

**Closed by mattcaswell** 2018-01-18 16:04 UTC
