### ISSUE TITLE
SSL_CTX_set_keylog_callback not invoke after SSL_renegotiate_abbreviated and or SSL_key_update

### ISSUE THREAD

**Issue by jlamond** [openssl/openssl#18001] opened 2022-03-31 12:51 UTC
SSL_CTX_set_keylog_callback function function is not call / invoke after SSL_key_update and or SSL_renegotiate_abbreviated!
Is this a normal behavior or a bug?
I'm running under openssl-devel-1.1.1k-6.el8_5.x86_64
Thank you,
Jean-Marc

**Comment by hlandau** [comment] 2022-04-04 11:09
Worth noting that a TLS1.3 key update, caused by SSL_key_update, calculates new traffic secrets based on the old ones, so logging these events isn't necessary to decrypt the subsequent data transmitted.

For TLS1.0-1.2 the SSL_renegotiate_abbreviated function uses session resumption, so being privvy to the keylog data from the original session should enable you to decrypt the traffic, if I understand it correctly.

**Comment by jlamond** [comment] 2022-04-04 12:07
May be I wrongly exposed the situation.
Wireshark does not decrypt anymore the flow after a key renegociation.  Wireshark use what is produced from the callback function.
________________________________
De : Hugo Landau ***@***.***>
Envoyé : lundi 4 avril 2022 13:09
À : openssl/openssl ***@***.***>
Cc : jlamond ***@***.***>; Author ***@***.***>
Objet : Re: [openssl/openssl] SSL_CTX_set_keylog_callback not invoke after SSL_renegotiate_abbreviated and or SSL_key_update (Issue #18001)


Worth noting that a TLS1.3 key update, caused by SSL_key_update, calculates new traffic secrets based on the old ones, so logging these events isn't necessary to decrypt the subsequent data transmitted.

For TLS1.0-1.2 the SSL_renegotiate_abbreviated function uses session resumption, so being privvy to the keylog data from the original session should enable you to decrypt the traffic, if I understand it correctly.

**Comment by hlandau** [comment] 2022-04-04 12:35
My guess is that this is probably a limitation of Wireshark. Though it's possible we could log under these circumstances anyway to help it, even if not strictly necessary.

**Comment by jlamond** [comment] 2022-04-04 12:39
I don't know how much work this would require but I have to admit that this is very cool to look a decrypted application data frame with Wireshark.
Keep me posted and best regards,
Jean-Marc
________________________________
De : Hugo Landau ***@***.***>
Envoyé : lundi 4 avril 2022 14:35
À : openssl/openssl ***@***.***>
Cc : jlamond ***@***.***>; Author ***@***.***>
Objet : Re: [openssl/openssl] SSL_CTX_set_keylog_callback not invoke after SSL_renegotiate_abbreviated and or SSL_key_update (Issue #18001)


My guess is that this is probably a limitation of Wireshark. Though it's possible we could log under these circumstances anyway to help it, even if not strictly necessary.

**Comment by t8m** [comment] 2024-02-22 15:45
The version 1.1.1 is not supported anymore. Closing. If this is still an issue with currently supported releases, please open a new issue.

**Closed by t8m** 2024-02-22 15:45 UTC
Labels: branch: 1.1.1, triaged: question
