### ISSUE TITLE
[3.0 Provider question]: Using nested providers - provider that offloads some functionality to another provider 

### ISSUE THREAD

**Issue by alaakryeem** [openssl/openssl#20941] opened 2023-05-11 08:56 UTC
When implementing an OpenSSL 3.0 provider, is it valid to have one provider load another provider? For instance, I would like to implement specific functionality in my provider while offloading other functionality to the default OpenSSL provider. Do you foresee any potential issues with this design?
e.g. in myprov.c file:
```
// Example of how SIGNATURE_NEWCTX would be implemented
static void *myprov_sig_newctx(void *provctx, const char *propq)
{
    static OSSL_LIB_CTX *deflt_libctx;
    static OSSL_PROVIDER *deflt_prov;
    EVP_PKEY_CTX *RSActx = NULL;
    // user's provider loads the default provider to offload the actual context creation using 
    // standard OpenSSL functionality
    deflt_prov = OSSL_PROVIDER_load(deflt_libctx, "default");
    RSActx = EVP_PKEY_CTX_new_from_name(deflt_libctx, "RSA", "provider=default");
    ....
}

static const OSSL_DISPATCH myprov_sig_funcs[] = {
    { OSSL_FUNC_SIGNATURE_NEWCTX, (void (*)(void))myprov_sig_newctx},
    { 0, NULL }
};
static const OSSL_ALGORITHM myprov_sig_algs[] = {
    { "RSA:rsaEncryption", "provider=myprov", myprov_sig_funcs, "Custom provider" },
    { NULL, NULL, NULL, NULL }
};

```

**Comment by t8m** [comment] 2023-05-11 09:00
You need to ensure that your implementation is not fetched instead (that would be infinite recursion). If you use "provider=default" prop query for the fetch or if the libcontext used does not contain any other provider than default, it should be fine.

**Comment by alaakryeem** [comment] 2023-05-11 15:25
Thank you for the quick response! I appreciate your help. 
I have one more question to ensure that my intended usage is reasonable. Please let me know if you identify any potential issues with the following usage (this is just an example, but it can be expanded to cover other functionalities).
```
        int nocache = 0;
        // retrieve signature algorithms from default OpenSSL provider
        const OSSL_ALGORITHM * algs = OSSL_PROVIDER_query_operation(deflt_prov,
                                               OSSL_OP_SIGNATURE,
                                               &nocache);
        // get RSA algorithms pointers
        OSSL_DISPATCH *dflt_funcs = algs[1].implementation;
        // get a NEWCTX function pointer
        OSSL_FUNC_signature_newctx_fn* dflt_fp = (dflt_funcs[OSSL_FUNC_SIGNATURE_NEWCTX-1].function);
        (*dflt_fp)(provctx, propq);
```

**Comment by t8m** [comment] 2023-05-11 16:26
This is much more problematic. This usage pattern basically means all the operations above the context returned from the newctx_fn has to be also done by the default provider. You cannot assume anything about the returned context.  So this usage pattern is good only in case you do only some simple operations such as filtering calls, logging params, etc. Please also note that the key references are opaque inside a provider so you would have to use the default provider also for keymgmt, etc.

**Comment by alaakryeem** [comment] 2023-05-11 17:03
Indeed, my intention is to utilize the same approach of offloading operations to the default provider for key management and the majority of signing functions, except for possibly one or two specific signing functions. Since modifying the functionality of the default provider is not feasible, my plan is to create a "wrapper" provider that offloads most of the functionality and only focuses on implementing those specific functions.

**Comment by t8m** [comment] 2023-05-11 17:48
I am not sure the approach of simply forwarding the calls is viable for such kind of provider.

**Comment by alaakryeem** [comment] 2023-05-11 20:17
Could you please elaborate on the specific challenges or limitations you foresee with this approach? It would be helpful to understand your perspective in order to evaluate alternative strategies or address any potential issues.

**Comment by paulidale** [comment] 2023-05-11 21:54
The problem you will run into is that the default provider and your code could easily have different internal formats for key material etc.  You can't off load some of an algorithm's functionality -- the handle to its data is opaque and definitely subject to change.

You would need to include a conversion layer that takes your format and packages it up into OSSL_PARAMs to send to the default provider.  The cost would be prohibitive.

**Comment by alaakryeem** [comment] 2023-05-13 08:14
I understand the point you're making. However, as I mentioned previously, my intention is to offload all functionality, including key management, to the default provider. Therefore, the workflow will be similar to that of any app using the default provider, with the exception of a few additional pre/post operations that I will incorporate in some of the functions. These operations will not introduce any new formats or modify OpenSSL formats.

**Comment by t8m** [comment] 2023-05-15 10:17
The problem is the additional pre/post operations cannot have access to the key data or the context data inside the default provider. So it is unclear what these pre/post operations can be.

**Comment by levitte** [comment] 2023-05-15 12:52
I think we have repeated enough times that each provider's data is completely private to that provider.  I don't see that it should make it impossible to have the proxying provider have its own structures with a pointer to the other provider's data, plus extra fields that belong with the proxying provider, and I see no problem with the proxying provider "wrapping" a produced signature by copying it to a buffer and adding a few bytes before and/or after, completely depending on what the proxying provider is supposed to provide.

I assume that's the sort of thing that you intend on doing, @alaakryeem.  Beware, though, that there may be more details to catch on the fly than you might originally think.  You will probably want to keep a keen eye on the param setters and getters.

**Comment by alaakryeem** [comment] 2023-05-21 09:50
> I assume that's the sort of thing that you intend on doing, @alaakryeem.

Yes, kind of.

> @alaakryeem, what exactly is your provider intending to do? Without any access to key material, you will be quite limited.
> 
> Tracing prints would be possible but doing anything cryptographic wouldn't be.

My provider is not intended to interact with or modify any cryptographic functionality or internal key material directly. Its purpose is primarily to perform a few basic operations before or after the actual cryptographic operation, similar to what was mentioned by levitte. Therefore, the focus of my provider lies outside the cryptographic domain. 

I believe we have reached a clear understanding now. Thank you all for your input and assistance!

**Comment by mattcaswell** [comment] 2024-01-31 12:08
Closing since this is marked as resolved.

**Closed by mattcaswell** 2024-01-31 12:08 UTC
Labels: triaged: question, resolved: answered
