### ISSUE TITLE
Checkend returning wrong output

### ISSUE THREAD

**Issue by anuthamako** [openssl/openssl#18471] opened 2022-06-03 14:20 UTC
Checkend returning wrong output for one of the certificates.

<img width="555" alt="Screenshot 2022-06-03 at 19 45 29" src="https://user-images.githubusercontent.com/19716541/171872547-0d417133-e70f-493f-be73-f48b1feaface.png">

**Comment by t8m** [comment] 2022-06-03 14:28
I am afraid to investigate more we will need the offending certificate.

**Comment by anuthamako** [comment] 2022-06-06 07:56
Sure. Attached certificate in txt format:
[cert.txt](https://github.com/openssl/openssl/files/8842763/cert.txt)
t

**Comment by t8m** [comment] 2022-06-06 09:17
Unfortuntely I cannot reproduce the problem with your certificate.

`openssl x509 -checkend 2139264020 -in cert.txt` always prints: Certificate will expire

I've tested it with all the current branches - openssl-3.0, 1.1.1.

What is the openssl version you use?

**Comment by anuthamako** [comment] 2022-06-06 11:35
I am afraid that I raised the issue in a wrong place. I am using LibreSSL 2.8.3

**Comment by t8m** [comment] 2022-06-06 11:43
OK, closing then.

**Closed by t8m** 2022-06-06 11:43 UTC
Labels: triaged: bug
