### ISSUE TITLE
3.0.0-alpha8: "openssl x509" cannot read from pipe

### ISSUE THREAD

**Issue by rainerjung** [openssl/openssl#13352] opened 2020-11-09 08:59 UTC
Recently the code in "openssl x509" that reads from stdin got fixed. Unfortunately there's still a problem when reading from a pipe.

$ cat pem

-----BEGIN CERTIFICATE-----
MIIDdTCCAl2gAwIBAgILBAAAAAABFUtaw5QwDQYJKoZIhvcNAQEFBQAwVzELMAkGA1UEBhMCQkUx
GTAXBgNVBAoTEEdsb2JhbFNpZ24gbnYtc2ExEDAOBgNVBAsTB1Jvb3QgQ0ExGzAZBgNVBAMTEkds
b2JhbFNpZ24gUm9vdCBDQTAeFw05ODA5MDExMjAwMDBaFw0yODAxMjgxMjAwMDBaMFcxCzAJBgNV
BAYTAkJFMRkwFwYDVQQKExBHbG9iYWxTaWduIG52LXNhMRAwDgYDVQQLEwdSb290IENBMRswGQYD
VQQDExJHbG9iYWxTaWduIFJvb3QgQ0EwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDa
DuaZjc6j40+Kfvvxi4Mla+pIH/EqsLmVEQS98GPR4mdmzxzdzxtIK+6NiY6arymAZavpxy0Sy6sc
THAHoT0KMM0VjU/43dSMUBUc71DuxC73/OlS8pF94G3VNTCOXkNz8kHp1Wrjsok6Vjk4bwY8iGlb
Kk3Fp1S4bInMm/k8yuX9ifUSPJJ4ltbcdG6TRGHRjcdGsnUOhugZitVtbNV4FpWi6cgKOOvyJBNP
c1STE4U6G7weNLWLBYy5d4ux2x8gkasJU26Qzns3dLlwR5EiUWMWea6xrkEmCMgZK9FGqkjWZCrX
gzT/LCrBbBlDSgeF59N89iFo7+ryUp9/k5DPAgMBAAGjQjBAMA4GA1UdDwEB/wQEAwIBBjAPBgNV
HRMBAf8EBTADAQH/MB0GA1UdDgQWBBRge2YaRQ2XyolQL30EzTSo//z9SzANBgkqhkiG9w0BAQUF
AAOCAQEA1nPnfE920I2/7LqivjTFKDK1fPxsnCwrvQmeU79rXqoRSLblCKOzyj1hTdNGCbM+w6Dj
Y1Ub8rrvrTnhQ7k4o+YviiY776BQVvnGCv04zcQLcFGUl5gE38NflNUVyRRBnMRddWQVDf9VMOyG
j/8N7yy5Y0b2qvzfvGn9LhJIZJrglfCm7ymPAbEVtQwdpf5pLGkkeB6zpxxxYu7KyJesF12KwvhH
hm4qxFYxldBniYUr+WymXUadDKqC5JlR3XC321Y9YeRq4VzW9v493kHMB65jUr9TU/Qr6cf9tveC
X4XSQRjbgbMEHMUfpIBvFSDJ3gyICh3WZlXi/EjJKSZp4A==
-----END CERTIFICATE-----

$ /path/to/my/bin/openssl x509 -MD5 -fingerprint -noout -inform PEM < pem
MD5 Fingerprint=3E:45:52:15:09:51:92:E1:B7:5D:37:9F:B1:87:29:8A

OK, works. But now:

$ cat pem | /path/to/my/bin/openssl x509 -MD5 -fingerprint -noout -inform PEM
Could not read certificate from <stdin>
00000001:error::STORE routines:ossl_store_get0_loader_int:unregistered scheme:crypto/store/store_register.c:240:scheme=file
00000001:error::DECODER routines:decoder_process:BIO lib:crypto/encode_decode/decoder_lib.c:511:
Unable to load certificate

Doing a truss (on Solaris, but same problem on Linux) I can see in the broken case:

10150:  read(0, " C", 1)                                = 1
10150:  read(0, " E", 1)                                = 1
10150:  read(0, " R", 1)                                = 1
10150:  read(0, " T", 1)                                = 1
10150:  read(0, " I", 1)                                = 1
10150:  read(0, " F", 1)                                = 1
10150:  read(0, " I", 1)                                = 1
10150:  read(0, " C", 1)                                = 1
10150:  read(0, " A", 1)                                = 1
10150:  read(0, " T", 1)                                = 1
10150:  read(0, " E", 1)                                = 1
10150:  read(0, " -", 1)                                = 1
10150:  read(0, " -", 1)                                = 1
10150:  read(0, " -", 1)                                = 1
10150:  read(0, " -", 1)                                = 1
10150:  read(0, " -", 1)                                = 1
10150:  read(0, "\n", 1)                                = 1
10150:  read(0, 0xFF239CD0, 1)                          = 0
10150:  llseek(0, 0, SEEK_CUR)                          Err#29 ESPIPE
10150:  brk(0x00479AD0)                                 = 0
10150:  brk(0x0047DAD0)                                 = 0
10150:  brk(0x0047DAD0)                                 = 0
10150:  brk(0x00481AD0)                                 = 0
10150:  brk(0x00481AD0)                                 = 0
10150:  brk(0x00483AD0)                                 = 0
10150:  llseek(0, 0, SEEK_CUR)                          Err#29 ESPIPE
10150:  fstat64(2, 0xFFBFE7C8)                          = 0
10150:      d=0x05940000 i=12582928 m=0020620 l=1  u=51    g=7     rdev=0x00600006
10150:          at = Nov  9 09:55:25 CET 2020  [ 1604912125.000000000 ]
10150:          mt = Nov  9 09:55:25 CET 2020  [ 1604912125.000000000 ]
10150:          ct = Nov  1 01:07:24 CET 2020  [ 1604189244.000000000 ]
10150:      bsz=8192  blks=0     fs=devfs
10150:  write(2, 0xFFBFEC88, 14)                        = 14
10150:     C o u l d   n o t   r e a d
10150:  write(2, "   c e r t i f i c a t e", 12)        = 12
10150:  write(2, 0xFFBFEC88, 13)                        = 13
10150:       f r o m   < s t d i n >
10150:  write(2, "\n", 1)                               = 1

Whereas in the good case (stdin redirected):

10133:  read(0, " C", 1)                                = 1
10133:  read(0, " E", 1)                                = 1
10133:  read(0, " R", 1)                                = 1
10133:  read(0, " T", 1)                                = 1
10133:  read(0, " I", 1)                                = 1
10133:  read(0, " F", 1)                                = 1
10133:  read(0, " I", 1)                                = 1
10133:  read(0, " C", 1)                                = 1
10133:  read(0, " A", 1)                                = 1
10133:  read(0, " T", 1)                                = 1
10133:  read(0, " E", 1)                                = 1
10133:  read(0, " -", 1)                                = 1
10133:  read(0, " -", 1)                                = 1
10133:  read(0, " -", 1)                                = 1
10133:  read(0, " -", 1)                                = 1
10133:  read(0, " -", 1)                                = 1
10133:  read(0, "\n", 1)                                = 1
10133:  llseek(0, 0, SEEK_CUR)                          = 1258
10133:  lseek(0, 1258, SEEK_SET)                        = 1258
10133:  llseek(0, 0, SEEK_CUR)                          = 1258
10133:  read(0, 0xFF239CD0, 1)                          = 0
10133:  lseek(0, 1258, SEEK_SET)                        = 1258
10133:  llseek(0, 0, SEEK_CUR)                          = 1258
10133:  read(0, 0xFF239CD0, 1)                          = 0
...
10133:  lseek(0, 1258, SEEK_SET)                        = 1258
10133:  llseek(0, 0, SEEK_CUR)                          = 1258
10133:  read(0, 0xFF239CD0, 1)                          = 0
10133:  lseek(0, 1258, SEEK_SET)                        = 1258
10133:  llseek(0, 0, SEEK_CUR)                          = 1258
10133:  read(0, 0xFF239CD0, 1)                          = 0
10133:  brk(0x00481AD0)                                 = 0
10133:  brk(0x00485AD0)                                 = 0
10133:  brk(0x00485AD0)                                 = 0
10133:  brk(0x00489AD0)                                 = 0
10133:  brk(0x00489AD0)                                 = 0
10133:  brk(0x0048DAD0)                                 = 0
10133:  brk(0x0048DAD0)                                 = 0
10133:  brk(0x00491AD0)                                 = 0
10133:  brk(0x00491AD0)                                 = 0
10133:  brk(0x00495AD0)                                 = 0
10133:  brk(0x00495AD0)                                 = 0
10133:  brk(0x00499AD0)                                 = 0
10133:  brk(0x00499AD0)                                 = 0
10133:  brk(0x0049DAD0)                                 = 0
10133:  brk(0x0049DAD0)                                 = 0
10133:  brk(0x004A1AD0)                                 = 0
10133:  brk(0x004A1AD0)                                 = 0
10133:  brk(0x004A5AD0)                                 = 0
10133:  brk(0x004A5AD0)                                 = 0
10133:  brk(0x004A9AD0)                                 = 0
10133:  ioctl(1, TCGETA, 0xFFBFE9A4)                    = 0
10133:          iflag=0002402 oflag=0014005 cflag=0000277 lflag=0105073 line=0
10133:              cc:  003 034 177 025 004 000 000 000
10133:  fstat64(1, 0xFFBFE8C0)                          = 0
10133:      d=0x05940000 i=12582928 m=0020620 l=1  u=51    g=7     rdev=0x00600006
10133:          at = Nov  9 09:51:33 CET 2020  [ 1604911893.000000000 ]
10133:          mt = Nov  9 09:51:11 CET 2020  [ 1604911871.000000000 ]
10133:          ct = Nov  1 01:07:24 CET 2020  [ 1604189244.000000000 ]
10133:      bsz=8192  blks=0     fs=devfs
10133:  write(1, 0xFF23A0D8, 64)                        = 64
10133:     M D 5   F i n g e r p r i n t = 3 E : 4 5 : 5 2 : 1 5 : 0 9 : 5
10133:     1 : 9 2 : E 1 : B 7 : 5 D : 3 7 : 9 F : B 1 : 8 7 : 2 9 : 8 A\n

**Comment by rainerjung** [comment] 2020-11-10 11:52
Some more analysis:difference between reading from file redirection to stdin and from pipe is behavior of ftell(). It fails for pipe but works for a redirected file.

providers/implementations/storemgmt/file_store.c contains comments, that it will handle this situation by wrapping the file BIO in a 4K buffer. The code correctly detects the type PEM used in the failing example and uses the wrapper.

But then crypto/encode_decode/decoder_lib.c in decoder_process() unconditionally calls BIO_tell() on the wrapper buffer BIO. Since that doesn't implement the TELL ctrl on its own, it passes it along to the underlying file BIO which returns -1 as expected. At that point the decoder throws an error.

**Comment by t8m** [comment] 2020-11-10 12:27
Setting beta1 milestone as this is quite serious regression which might require bigger changes in decoders.

**Comment by rainerjung** [comment] 2020-11-10 12:45
This has the same root cause as #13185 but note that the behavior here differs between stdin taken from input redirection (command < file) and stdin via pipe (cat file | command).

**Comment by t8m** [comment] 2021-03-05 14:57
I cannot reproduce this neither with the current master nor with #14407 merged. So hopefully this is now fixed.

**Closed** 2021-03-10 22:13 UTC
Labels: branch: master, triaged: OTC evaluated, triaged: bug
