### ISSUE TITLE
Openssl 3.2.1 configuration fails on windows

### ISSUE THREAD

**Issue by tavrez** [openssl/openssl#23436] opened 2024-01-30 23:11 UTC
Hello, 
I've used the same environment I've build all my previous Openssl versions, it now fails for version 3.2.1
VS 14.28.29914.0
Nasm 2.16.01
Perl 5.24.3
```
c:\os\openssl>perl configure

It looks like you don't have either nmake.exe or dmake.exe on your PATH,
so you will not be able to execute the commands from a Makefile.  You can
install dmake.exe with the Perl Package Manager by running:

    ppm install dmake

Configuring OpenSSL version 3.2.1 for target VC-WIN64A
Using os-specific seed configuration

Failure!  makefile wasn't produced.
Please read INSTALL.md and associated NOTES-* files.  You may also have to
look over your available compiler tool chain or change your configuration.

C:\os\openssl\crypto\providers: No such file or directory at configure line 3500.

``` 
The part about not having nmake is wrong, it always appears.
I've also double checked version 3.2.0 and its fine.
I can provide any other information needed.

**Comment by nhorman** [comment] 2024-01-31 13:28
I would still fix the nmake/dmake issue as it seems odd that it not be found.  I presume the issue there is that its just not added to your %PATH% ?

As for the failed config, I guess the most direct first question is: Does C:\os\openssl\crypto\providers exist? 

I assume that the portion of the path c:\os\openssl is correct for your environment.  I also assume you obtained your source via a release tarball download rather than a git clone?

Looking at both, in git crypto/providers is an empty directory, and it appears to have not been included in the corresponding tarball.  I'm not sure where in the configure script this is getting searched for, but it seems odd that the directory exists in git, but not in the tarball.  I would first try creating the empty directory c:\os\openssl\crytpo\providers and rerun configure to see if you can work around the issue

@hlandau I think you and @levitte did the 3.2.1 release yesterday.  Any thoughts on how crypto/providers got excluded in the tarball?

**Comment by tavrez** [comment] 2024-01-31 13:39
> I would still fix the nmake/dmake issue as it seems odd that it not be found. I presume the issue there is that its just not added to your %PATH% ?

nmake is in my path, this line is always there regardless of nmake being in path or not, I've built openssl since version 1.0.0 on this pc without any problem. But I can't remember from which version this message started to falsely appear even though I have nmake.
maybe it's because %path% is checked from registry and not the current %path%, I don't know.
```
d:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise>where nmake
d:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.28.29910\bin\Hostx64\x64\nmake.exe
```
> As for the failed config, I guess the most direct first question is: Does C:\os\openssl\crypto\providers exist?

never existed, even in previous builds like openssl 3.2.0(which can be built successfully)
> I assume that the portion of the path c:\os\openssl is correct for your environment. I also assume you obtained your source via a release tarball download rather than a git clone?

downloaded from openssl.org site and verified with gpg.

> There is no such thing in the codebase. The providers subdir is at top level. This must be something weird with the reporter's environment. Otherwise we would see more issues reported.

Maybe on my side, but as I've noted, openssl 3.2.0 compiles fine here

**Comment by adamskiii** [comment] 2024-01-31 19:18
I am getting the exact same error after trying to compile to the latest version of OpenSSL ( both 3.2.1 and 1.3.5 ). Nothing has changed on my machine aside from the OpenSSL source code:

> Failure!  makefile wasn't produced.
Please read INSTALL.md and associated NOTES-* files.  You may also have to
look over your available compiler tool chain or change your configuration.

> C:\openssl\3.1.5\src\openssl-3.1\crypto\providers: No such file or directory at Configure line 3409.

**Comment by levitte** [comment] 2024-02-01 08:41
Ehhhh...  I'm finding `crypto/providers` in my source tree, just now.  I have *no* idea how it came to be, but will look.

**Comment by levitte** [comment] 2024-02-01 09:39
I think I found the cause of the regression, and it's partly about that rogue directory, and partly about a recent strictness.  Just let me look around a bit more, just to make sure I didn't miss something more.

**Comment by mattcaswell** [comment] 2024-02-01 09:41
Why didn't our CIs find this?

**Comment by levitte** [comment] 2024-02-01 09:46
> Why didn't our CIs find this?

Because we don't check for errors when calling `realpath` in Configure.  It looks like the Windows implementation calls `die` when it can't find the directory, while the Unix implementation is gentler and probably only returns `undef` (which we don't check for).

**Comment by mattcaswell** [comment] 2024-02-01 09:50
> Because we don't check for errors when calling realpath in Configure. It looks like the Windows implementation calls die when it can't find the directory,

??? But surely if the whole Configure script fails then nothing further can happen and all future stages fail?

**Comment by levitte** [comment] 2024-02-01 09:56
The cause of this regression can be taken to commit: 504ff2a4ef5f26990a48ca3d664ac1e5d9cb20b9

However, the fault really lies here:

``` console
$ grep -E '\[\.\./[^\.]' crypto/*/build.info
crypto/aes/build.info:  DEFINE[../providers/liblegacy.a]=$AESDEF
crypto/ec/build.info:  DEFINE[../providers/liblegacy.a]=$ECDEF
crypto/sha/build.info:  DEFINE[../providers/liblegacy.a]=$SHA1DEF $KECCAK1600DEF
crypto/sm4/build.info:  DEFINE[../providers/liblegacy.a]=$SM4DEF
```

i.e. it was a dormant bug that came to surface because we're recently a bit more strict where we let Configure make directories.

**Comment by levitte** [comment] 2024-02-01 10:08
The really annoying bit is that `realpath` from the Cwd perl module appears to be leaner on Unix.  Even with this patch, no error was produced:

``` diff
diff --git a/Configure b/Configure
index cca1ac8d16..40ae9890cf 100755
--- a/Configure
+++ b/Configure
@@ -3497,7 +3497,9 @@ sub absolutedir {
     # a directory spec.
     use Cwd qw/realpath/;
 
-    return realpath($dir);
+    my $abs_path = realpath($dir);
+    die "realpath failed: $!\n" unless defined $abs_path;
+    return $abs_path;
 }
 
 # Check if all paths are one and the same, using stat.  They must both exist
```

...  but that may be by design.  After all, it should be possible to figure out the "real path" of a file or directory that doesn't exist, as long as enough of its components do.

**Comment by t8m** [comment] 2024-02-01 11:33
@tavrez @adamskii Could you please try to update your perl version? That might be able to workaround the issue.

I do not see any error with perl 5.32.1

**Comment by levitte** [comment] 2024-02-01 12:12
I could replicate this issue with Strawberry perl 5.26.  I'll have a look if upgrading to 5.38 makes a difference.

**Comment by levitte** [comment] 2024-02-01 12:15
After upgrading perl to 5.38, this issue has disappeared.

So, we can see that perl 5.26 to 5.31 had this issue.

**Comment by mattcaswell** [comment] 2024-02-01 12:18
> So, we can see that perl 5.26 to 5.31 had this issue.

Well we know that it has gone by 5.32. Not sure we can say 5.31 has it! We also know it is present in 5.24 (as per @tavrez's report)

This at least explains why our CIs did not pick this up. I assume the CIs are using more recent perl versions.

**Comment by levitte** [comment] 2024-02-01 12:25
Right.  With `corelist -a Cwd` (that's the module where `realpath` lives), I found that it must have been fixed with perl v5.30, 'cause it contains the same Cwd version as perl 5.32.

So at least perl v5.24 to v5.29 are under suspicion.  Exactly how far this issue goes back before perl v5.24 is unknown.

**Comment by tavrez** [comment] 2024-02-01 12:29
I can confirm patch https://github.com/openssl/openssl/pull/23452 solved the issue with my outdated Perl. i Will update perl and test without patch.

Thanks

**Comment by levitte** [comment] 2024-02-01 12:32
Note that either way, #23452 fixes an actual issue...  it was just undiscovered, until now.  We are grateful that you found it, however annoying it may be.

**Comment by Jan-E** [comment] 2024-02-01 15:49
> Well we know that it has gone by 5.32. Not sure we can say 5.31 has it! We also know it is present in 5.24 (as per @tavrez's report)

FWIW: perl 5.24.1 had the same issue with OpenSSL 3.0.13. Patch https://github.com/openssl/openssl/pull/23452 solved the configure issue, but it did not apply cleanly. Patching of crypto/sm4/buiild.info failed, because it is only 3 lines in the openssl-3.0-branch:
https://github.com/openssl/openssl/blob/openssl-3.0/crypto/sm4/build.info

**Comment by adamskiii** [comment] 2024-02-01 16:42
I can confirm from my end that both solutions now work and I am able to successfully compile OpenSSL 3.1.5. Confirmed the following two scenarios worked :

**1**) Perl 5.26 **_WITH_** Pull 23452
**2**) Perl 5.32.1 **_WITHOUT_** Pull 23452

**Closed** 2024-02-02 13:15 UTC
Labels: branch: master, triaged: bug, branch: 3.0, branch: 3.1, branch: 3.2

**Comment by davecrighton** [comment] 2024-02-14 17:31
For completeness I hit the same thing on 5.20.1 leading to the raise of #22097
