### ISSUE TITLE
CAPI engine forcing use of MS Enhanced RSA/AES CSP in inappropriate cases

### ISSUE THREAD

**Issue by omnicognate** [openssl/openssl#2920] opened 2017-03-13 17:38 UTC
In 1.1.0 (commit 7b548d3f11adccc67123e1f6f5c118aef857a8d2), the CAPI engine was updated to use the newer "Microsoft Enhanced RSA and AES Cryptographic Provider" CSP, type 24, in place of any referenced CSP with type 1, regardless of the provider name. The intent appears to have been to force keys using the older "Microsoft Base Cryptographic Provider" CSP onto the newer one. However, since there is no check against the provider name this ends up using the newer CSP in inappropriate cases. In my case, I have client certs using 2 CSPs of type 1 (the MS base smart card CSP and a third party one) which were working fine with the CAPI engine before, but which fail with CryptAcquireContext errors in 1.1.0, because the RSA/AES CSP isn't a suitable replacement. With the code as is, I can't see any workaround.

**Comment by dot-asm** [comment] 2017-03-13 20:45
For reference, what's OS version? In case I fail to reproduce the problem that is...

**Comment by omnicognate** [comment] 2017-03-13 21:40
Windows 7

**Comment by dot-asm** [comment] 2017-03-26 16:27
See #3034.

**Comment by dot-asm** [comment] 2017-03-29 10:05
For reference, referred pull request closed, because they are applied. And I'm closing this issue too, as I'm quite confident that it addresses the problem even without explicit confirmation from reporter. In worst case it can be re-opened...

**Closed by dot-asm** 2017-03-29 10:05 UTC

**Comment by omnicognate** [comment] 2017-03-30 13:07
I haven't been able to test this yet - that's going to take a while as it requires builds of intermediate software. However, it certainly looks right. Many thanks for the swift fix!
