### ISSUE TITLE
Why is the name of the static library "libssl.a"?

### ISSUE THREAD

**Issue by maths644311798** [openssl/openssl#21072] opened 2023-05-28 03:43 UTC
Why is the name of the static library "libssl.a"? ssl is a famous protocol. I know that openssl implements ssl. But openssl uses the name "libssl.a" instead of "libopenssl.a". Is there any history about this naming?

**Comment by levitte** [comment] 2023-05-28 07:29
OpenSSL delivers two libraries, libcrypto and libssl. libcrypto delivers all the cryptographic functionality, while libssl delivers the security protocols. libssl depends on libcrypto.

So, as you can see, the name choice is symbolic, rather than project name based. This is a choice that was made in what now feels like the dawn of time, possibly even in the previous project that OpenSSL inherited from (I can't remember, but a look at the beginning of git history will tell)

**Comment by maths644311798** [comment] 2023-05-28 14:44
Thanks. I believe that the openssl organization has negotiated with the ssl organization on the naming of libraries.

**Comment by t8m** [comment] 2023-05-29 13:20
You also have to understand that changing the name would be seriously breaking  the build of applications that use the OpenSSL library - they all would have to change to use the new name. So, yes, the name is a historic artifact which is unfortunately not easily changed.

**Comment by levitte** [comment] 2023-05-29 20:26
I can confirm that `libcrypto.a` and `libssl.a` were there in what OpenSSL inherited.  This is visible in commit d02b48c63a58ea4367a0e905979f140b7d090f86, top `Makefile.ssl` (oh boy, have things changed since then, but not the names)

> Thanks. I believe that the openssl organization has negotiated with the ssl organization on the naming of libraries.

Er...  welcome to the historical lane.

So we're talking about something that happened in the later 1990's.  The "ssl organization" back then was Netscape (you can still find a reference in historical [RFC 6101](https://datatracker.ietf.org/doc/html/rfc6101)).  Was there a conversation with them?  Maybe...  but who cares at this point?  Point is, those library names have demonstrably been around since before late 1998.  It would be pointless, not to say a breaking change (as @t8m says), to change them now.

**Comment by mattcaswell** [comment] 2024-01-31 12:14
Closing since this is marked as resolved.

**Closed by mattcaswell** 2024-01-31 12:14 UTC
Labels: triaged: question, resolved: answered
