### ISSUE TITLE
Allow using EVP_CIPHER_CTX_copy on ChaCha20Poly1305 EVP_CIPHER_CTX

### ISSUE THREAD

**Issue by alex** [openssl/openssl#21853] opened 2023-08-27 16:09 UTC
With OpenSSL 3.1.2, if you create an `EVP_CIPHER_CTX` from a `ChaCha20Poly1305`, it cannot be copied with `EVP_CIPHER_CTX_copy`.

It us useful to be able to support creating a "base" context, with only a key, and then coping it and then providing the nonce (and performing the encryption/decryptiong). This pattern works with other ciphers (e.g., AES-SIV) but not ChaCha20Poly1305.

**Comment by alex** [comment] 2023-08-27 16:43
I hadn't noticed this when I filed the bug, but this appears to work fine with OpenSSL 1.1.1v.

**Comment by alex** [comment] 2023-08-27 17:03
Minimal reproducer. Works on 1.1.1, fails on 3:

```c
#include <stdbool.h>

#include <openssl/err.h>
#include <openssl/evp.h>


void openssl_assert(bool b, char *op) {
	if (!b) {
		printf("%s failed\n", op);
		ERR_print_errors_fp(stderr);
		exit(1);
	} else {
		printf("%s succeeded\n", op);
	}
}

const char *KEY = "abcdefghijklmnopqrstuvwxyz123456";

int main() {
	EVP_CIPHER_CTX *base_ctx = EVP_CIPHER_CTX_new();
	openssl_assert(base_ctx != NULL, "base_ctx = EVP_CIPHER_CTX_new");

	int res = EVP_EncryptInit_ex(base_ctx, EVP_chacha20_poly1305(), NULL, (const unsigned char *)KEY, NULL);
	openssl_assert(res == 1, "EVP_EncryptInit_ex");

	EVP_CIPHER_CTX *ctx = EVP_CIPHER_CTX_new();
	openssl_assert(ctx != NULL, "ctx = EVP_CIPHER_CTX_new");

	res = EVP_CIPHER_CTX_copy(ctx, base_ctx);
	openssl_assert(res == 1, "EVP_CIPHER_CTX_copy");
}
```

**Comment by alex** [comment] 2023-08-27 17:22
(I originally filed this as a feature request, but now that I've realized it's a regression, I think it's more accurately characterized as a bug.)

**Comment by alex** [comment] 2023-08-27 20:17
This also impacts `EVP_aes_128_gcm`

**Comment by t8m** [comment] 2023-08-28 10:02
Duplicate of #20978

**Closed by t8m** 2023-08-28 10:02 UTC
Labels: issue: feature request
