### ISSUE TITLE
Error 404 for master man1

### ISSUE THREAD

**Issue by beldmit** [openssl/openssl#11050] opened 2020-02-10 11:33 UTC
Trying to access s_client/s_server manuals for master, I came across 404 errors.

The page https://www.openssl.org/docs/manmaster/man1/s_client.html provides links to https://www.openssl.org/docs/manmaster/man1/openssl-s_client.html, https://www.openssl.org/docs/manmaster/man1/openssl-s_server.html, and many other commands, which lead to the page with 404 text:
```
Page Not Found
Sorry, but the link you gave does not exist.

To get the latest news about OpenSSL, download the source, and so on, please see the sidebar or the buttons at the top of every page. For more information about the team and community around the project, or to start making your own contributions, start with the community page.
```

**Comment by levitte** [comment] 2020-02-10 22:15
Oh srgh. Since som pod files are now generated, the current rendering is no longer feasible.
OK, I will have a look at that tomorrow...

**Comment by mattcaswell** [comment] 2020-02-12 10:12
Ping @levitte

**Comment by mspncp** [comment] 2020-09-29 15:07
Fixed by #13031

**Closed by mspncp** 2020-09-29 15:07 UTC
Labels: triaged: documentation

**Comment by mspncp** [comment] 2020-09-29 15:08
Oh, well. Didn't see that the issue is from 12 Feb. So it's probably unrelated. Nevertheless, it's fixed.

**Comment by levitte** [comment] 2020-09-29 15:21
> Oh, well. Didn't see that the issue is from 12 Feb. So it's probably unrelated. Nevertheless, it's fixed.

Yeah, I believe that openssl/web#175 fixed this.
