### ISSUE TITLE
Lack of performances compared to 1.1.0

### ISSUE THREAD

**Issue by EmericBr** [openssl/openssl#5559] opened 2018-03-08 16:21 UTC
Hi All,

Benchmark of my soft results in lack of performances upgrading to latest master commit.

Using openssl-v1.1.0 my soft handle 24k TPS.

Upgrading to latest master i observe only 14k TPS

A loss of 40% of performances.

I've started a bisect, what i see is that loss is progressiv.

I've currently identified one commit: 32bda2b2e4900308cb025020d8c8692e1d3c2ba9

It is responsible of 19k -> 15k TPS.

R,
Emeric

**Comment by mattcaswell** [comment] 2018-03-08 16:45
Ouch that's a big loss in one commit. @kroeckx, @mspncp perhaps we should rethink that change?

@EmericBr what happens if you disable TLSv1.3?

**Comment by mspncp** [comment] 2018-03-08 17:00
It seems like we are not ready for a AES-256-CTR DRBG yet. Since a security level of 128bit should be enough for most use cases, it's probably best to revert the commit for the moment.

BTW:  IIRC, the AES-256-CTR DRBG is implemented entirely in software. (The code was taken mostly unmodified from the FIPS 2.0 object module). There was an attempt by @p-steuer to use platform specific aes support (#4530). This would probably help improving performance in the future. The pr however is not ready yet, since it was requested that hardware support should be based on the EVP API.

**Comment by richsalz** [comment] 2018-03-08 17:01
+1 to revering the commit.

**Comment by kroeckx** [comment] 2018-03-08 17:30
I planned to write an other PR that switches it to EVP.

20928ff635772182fe8696d618a19f9101a5370f might be an other cause
of slowdowns by using the additional data.

**Comment by EmericBr** [comment] 2018-03-09 10:11
@mattcaswell , i've forced to tlsv1.2 using no-tls13. So my benchmark use tlsv1.2.

I continue to bissect to find if there is an over commit responsible of the lack of performances. Reverting the identified one it remains a loss of 20% of performances compared to 1.1.0.

**Comment by mattcaswell** [comment] 2018-03-09 10:25
>  it remains a loss of 20% of performances compared to 1.1.0.

Probably switching the DRBG to use EVP as suggested by @kroeckx will help.

**Comment by EmericBr** [comment] 2018-03-09 10:29
@mattcaswell I'm lauching a test reverting that one to. I keep you informed

**Comment by richsalz** [comment] 2018-03-09 12:48
Also look at OPENSSL_cleanse

**Comment by richsalz** [comment] 2018-03-09 13:06
Two clarifications.  Matt says that new code should be added to DRBG to use the EVP API.  (EVP gets hardware assist, the current code does not.)  So there's nothing to "revert" here, code has to be added.  Luckily that could be considered a bug-fix so there's no immediate deadline.

My comment was about looking to see calldata.  We find that OpenSSL_cleanse is used a lot.  A real lot.  Could it be made more efficient?  Perhaps @dot-asm can comment.  But should calls to it be removed?  They're adding more security by scrubbing key material so probably not.

**Comment by kroeckx** [comment] 2018-03-09 17:52
@EmericBr: Does your software use multiple threads? In that case #5547 might make a difference.

I really can't test the performance impact of things, and hoped that @richsalz would test such things.

**Comment by richsalz** [comment] 2018-03-09 20:24
I didn't know you were hoping me to do perf testing.

@dot-asm I mean that in our (work) server, we see cleanse close to the top for CPU time under normal workload.  I'll get you more info out-of-band.

**Comment by kroeckx** [comment] 2018-03-10 11:32
So the EVP changes are in #5580

**Comment by EmericBr** [comment] 2018-03-12 14:14
@kroeckx indeed my soft is using multithread but there is only few threads (only 4 in my test purpose). The soft is using the openssl API in non blocking mode (fd are event triggered) and each thread handles multiple sessions.

**Comment by kroeckx** [comment] 2018-03-21 20:34
Can you try with a current git master version, and see what the effect is?

**Comment by kroeckx** [comment] 2018-04-01 11:40
@EmericBr: Do you have time to test this again?

Can someone else run a test like this?

**Comment by mspncp** [comment] 2018-04-26 20:48
Hi @EmericBr, have you made any benchmarks for master recently? Would mind giving us an update? Or should this issue be closed?

**Comment by mattcaswell** [comment] 2018-05-02 10:16
No update from @EmericBr. I think we give it another couple of days and then close this.

**Comment by mspncp** [comment] 2018-05-12 22:17
@EmericBr there was no reaction within two months, so I assume this ticket can be closed. 

Thank you very much for sharing your results, you pointed out a significant performance regression which we had overlooked. If you still want to share some updated performance test results, feel free to reopen this issue.

**Closed by mspncp** 2018-05-12 22:17 UTC
