### ISSUE TITLE
Different addresses of P->meth of two different points on the same curve

### ISSUE THREAD

**Issue by Warchant** [openssl/openssl#2161] opened 2016-12-31 16:01 UTC
Hello.

I am using low level openssl API for elliptic curves and faced with strange behavior 
[at this line](https://github.com/openssl/openssl/blob/master/crypto/ec/ec_lib.c#L613). It performs address comparison of two objects. 

My code:
```C
EC_KEY *eckey1 = NULL; // private
EC_KEY *eckey2 = NULL; // public

// open input files. in1 - EC private key, in2 - EC public key
in1 = bio_open_default(path1, 'r', informat);
in2 = bio_open_default(path2, 'r', informat);

eckey1 = PEM_read_bio_ECPrivateKey(in1, NULL, NULL, passin);
eckey2 = PEM_read_bio_EC_PUBKEY(in2, NULL, NULL, NULL);

// create context
BN_CTX *ctx = NULL;
if ((ctx = BN_CTX_new()) == NULL) 
    perror("can't create ctx");

// compare groups. they should be in the same group
if(-1 == EC_GROUP_cmp(eckey1->group, eckey2->group, ctx)) 
    perror("keys are in different groups");

// create new point and copy public key there
EC_POINT* Z1  = EC_POINT_new(eckey1->group);
if(!EC_POINT_copy(Z1, eckey1->pub_key)) 
    perror("error at Z1=pub"); // this returns 0 and perror is invoked 
```

`EC_POINT_copy` returns `0`, because address of `Z1->meth` is different than address of `eckey1->pub_key->meth`, but every member of `Z1->meth` is the same as according member of `eckey1->pub_key->meth`, including addresses. 

I don't understand why addresses of `Z1->meth` and `eckey1->pub_key->meth` are different. It leads to `perror` in my code. Should I ignore it? I made a mistake somewhere? 

P.S. Thanks for great lib! And happy New year :)

**Comment by mattcaswell** [comment] 2017-05-02 14:00
Hey, Happy New Year! :-) It looks like filing issues while everyone is on holiday doesn't work too well!! Sorry this got lost.

Anyway, it looks to me like you are reaching inside OpenSSL internals here. The EC_KEY structure is opaque and its members (like pub_key) are not exposed via the public API (did you include the internal header file ec_lcl.h???). I suspect this is the cause of your issue. Closing.

**Closed by mattcaswell** 2017-05-02 14:00 UTC
