### ISSUE TITLE
Unexpected behaviour of genpkey

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#14145] opened 2021-02-10 12:11 UTC
The behaviour of genpkey has changed between 1.1.1 and master. Some of this behaviour change might be intentional (but if so it should be documented and there should be an explicit OTC decision for it). Other changes are probably bugs. Differences I've spotted so far:

The algorithm name "DH" and "X9.42 DH" were synonymous in 1.1.1 and the documentation continues to refer to them as synonyms:

> Note that the algorithm name X9.42 DH may be used as a synonym for the DH
algorithm. These are identical and do not indicate the type of parameters that
will be generated. Use the B<dh_paramgen_type> option to indicate whether PKCS#3
or X9.42 DH parameters are required.

However in master this is no longer the case. Requesting an algorithm name of "DH" will *always* given you PKCS3 DH parameters, but "X9.42 DH" will always give you X9.42 DH.

Additionally the "dh_paramgen_type" option no longer impacts the type of parameters that will be generated (contrary to what the documentation says above). So you can generate PKCS3 DH parameters using a generation method intended for use with X9.42 DH. This means that it is now possible to generate PKCS3 DH files that do not use safe primes and have no "q" parameter. Historically OpenSSL PKCS3 DH files have *always* used safe primes.

A similar case of this is the "dh_rfc5114" option. In 1.1.1 if you selected this option it would select an RFC5114 named group. These groups are intended for use with X9.42 DH. In master if you select an algorithm of "DH" then you will get this named group in a PKCS3 style PEM file. In 1.1.1, if you selected that option, then you would always get an X9.42 DH file.

A consequence of all of this is that we are now able to generate DH params files in master that will not pass the 1.1.1 version of `openssl dhparam -check` (because that checks that if you have PKCS3 DH then the primes are safe). In master running this command fails to notice this problem due to #13501. However fixing that (PR coming up), reveals that we actually have a few instances of these "bad" PKCS3 files in our tests:

https://github.com/openssl/openssl/blob/master/test/recipes/20-test_dhparam_check.t

Fixing #13501 causes test_dhparam_check to start failing because it is testing that some "bad" PKCS3 files pass `openssl dhparam -check` - which they don't.

**Comment by beldmit** [comment] 2021-02-10 13:11
Feel free to update the test files - I've generated them based on man examples and they really check just self-compatibility.

**Comment by mattcaswell** [comment] 2021-02-10 14:08
> Feel free to update the test files - I've generated them based on man examples and they really check just self-compatibility.

I have moved the invalid ones to the "invalid" directory in my forthcoming PR to fix #13501. We probably need to add some additional tests once this issue is also fixed.

**Comment by t8m** [comment] 2021-02-11 08:52
This is basically duplicate of #13956 and #13871

**Comment by t8m** [comment] 2021-02-16 09:17
OTC needs to decide how to treat the DH and DHX keys - should they be just aliases of each other or treated differently as in the current 3.0 code.

**Comment by slontis** [comment] 2021-04-16 03:48
The OTC decision was to treat them as different types.

**Closed** 2021-04-26 17:52 UTC
Labels: tmp: HIGH, triaged: OTC evaluated, triaged: bug
