### ISSUE TITLE
Documentation-Code Discrepancy in PKCS12_create()

### ISSUE THREAD

**Issue by msidoivry** [openssl/openssl#23151] opened 2023-12-26 12:10 UTC
## Issue Title

Inconsistency between PKCS12_create() Documentation and Code Implementation

### Description

Hello OpenSSL Team,

I have encountered an inconsistency between the documentation and the code implementation within the `PKCS12_create()` and related functions. The documentation suggests that: 

> "if a certificate contains an alias or keyid, it will be used for the corresponding friendlyName or localKeyID in the PKCS12 structure."

However, upon reviewing the code implementation in `PKCS12_create()`, specifically in `pkcs12_create_ex2()`, the code behaves differently than described in the documentation. The code implementation does not explicitly leverage the certificate's alias or keyid for friendlyName or localKeyID within the PKCS12 structure. The code prioritizes the 'name' parameter of the interface and the hash calculated for the key ID over the information existing on the certificate.

I have attached snippets from the documentation and the relevant code for your reference.

https://www.openssl.org/docs/man3.0/man3/PKCS12_create.html

[openssl/crypto/pkcs12/p12_crt.c at master · openssl/openssl (github.com)](https://github.com/openssl/openssl)

![pkcs12 error](https://github.com/openssl/openssl/assets/154733700/866585fe-2f93-4e64-8fcf-61861fc2837e)

This change was merged 3 months ago in the following commit: [Fix PKCS#12 creation error when certificate contains auxiliary data](link_to_commit)

### Request

Could the OpenSSL team kindly review this discrepancy and clarify the intended behavior? Additionally, I would like to understand whether the suggested resolution pertains to changes in the codebase or requires updates in the documentation.

**Comment by jamuir** [comment] 2023-12-26 21:26
> This change was merged 3 months ago in the following commit: [Fix PKCS#12 creation error when certificate contains auxiliary data](link_to_commit)

Here is a link to the merged PR:  https://github.com/openssl/openssl/pull/21675

**Comment by mattcaswell** [comment] 2024-01-03 11:06
This is a documentation issue. I have tried to clarify the intended behaviour in #23188.

**Closed** 2024-01-04 16:45 UTC
Labels: branch: master, triaged: documentation, branch: 3.0, branch: 3.1, branch: 3.2
