### ISSUE TITLE
1.1.1 breaks TLS-PSK in zabbix

### ISSUE THREAD

**Issue by Bluewind** [openssl/openssl#7241] opened 2018-09-17 12:12 UTC
I'm running zabbix 3.4.14 on Arch Linux and I'm seeing TLS authentication issues after upgrading openssl from 1.1.0.i-1 to 1.1.1-1 (the `-1` part is the Arch Linux package version). Downgrading openssl to 1.1.0.i-1 resolves the issue so I'm inclined to believe that this is a backwards incompatible API change in openssl, possibly due to TLS 1.3 support described here: https://wiki.openssl.org/index.php/TLS1.3#PSKs

The agent is configured to accept incoming connections from the server and also actively connect to the server. Both parts fail if the agent is using the the new openssl version.

I'll be opening the same bug on the zabbix bug tracker shortly in case they can provide some input about their usage of openssl here. I'll provide links in both bugs once I've opened the other one.

Below is a part of the log generated by zabbix-agent with the OLD openssl version, filtered with `grep -i -C8 -e tls -e psk`
```
Sep 17 14:03:16 karif zabbix_agentd[20174]: Starting Zabbix Agent [karif]. Zabbix 3.4.14 (revision 84877).
Sep 17 14:03:16 karif zabbix_agentd[20174]: **** Enabled features ****
Sep 17 14:03:16 karif zabbix_agentd[20174]: IPv6 support:          YES
Sep 17 14:03:16 karif zabbix_agentd[20174]: TLS support:           YES
Sep 17 14:03:16 karif zabbix_agentd[20174]: **************************
Sep 17 14:03:16 karif zabbix_agentd[20174]: Starting Zabbix Agent [karif]. Zabbix 3.4.14 (revision 84877).
Sep 17 14:03:16 karif zabbix_agentd[20174]: Press Ctrl+C to exit.
Sep 17 14:03:16 karif zabbix_agentd[20174]: using configuration file: /etc/zabbix/zabbix_agentd.conf
Sep 17 14:03:16 karif zabbix_agentd[20174]: In zbx_load_modules()
Sep 17 14:03:16 karif zabbix_agentd[20174]: End of zbx_load_modules():SUCCEED
Sep 17 14:03:16 karif zabbix_agentd[20174]: In init_collector_data()
Sep 17 14:03:16 karif zabbix_agentd[20174]: In zbx_dshm_create() size:0
--
Sep 17 14:03:16 karif zabbix_agentd[20174]: End of init_collector_data()
Sep 17 14:03:16 karif zabbix_agentd[20174]: agent #0 started [main process]
Sep 17 14:03:16 karif zabbix_agentd[20175]: agent #1 started [collector]
Sep 17 14:03:16 karif zabbix_agentd[20175]: In init_cpu_collector()
Sep 17 14:03:16 karif zabbix_agentd[20175]: End of init_cpu_collector():SUCCEED
Sep 17 14:03:16 karif zabbix_agentd[20175]: __zbx_zbx_setproctitle() title:'collector [processing data]'
Sep 17 14:03:16 karif zabbix_agentd[20175]: In update_cpustats()
Sep 17 14:03:16 karif zabbix_agentd[20176]: agent #2 started [listener #1]
Sep 17 14:03:16 karif zabbix_agentd[20176]: In zbx_tls_init_child()
Sep 17 14:03:16 karif zabbix_agentd[20175]: End of update_cpustats()
Sep 17 14:03:16 karif zabbix_agentd[20175]: __zbx_zbx_setproctitle() title:'collector [idle 1 sec]'
Sep 17 14:03:16 karif zabbix_agentd[20177]: agent #3 started [listener #2]
Sep 17 14:03:16 karif zabbix_agentd[20177]: In zbx_tls_init_child()
Sep 17 14:03:16 karif zabbix_agentd[20179]: agent #5 started [active checks #1]
Sep 17 14:03:16 karif zabbix_agentd[20179]: In zbx_tls_init_child()
Sep 17 14:03:16 karif zabbix_agentd[20178]: agent #4 started [listener #3]
Sep 17 14:03:16 karif zabbix_agentd[20178]: In zbx_tls_init_child()
Sep 17 14:03:16 karif zabbix_agentd[20177]: OpenSSL library (version OpenSSL 1.1.0i  14 Aug 2018) initialized
Sep 17 14:03:16 karif zabbix_agentd[20177]: zbx_tls_init_child() loaded PSK identity "PSKkarif"
Sep 17 14:03:16 karif zabbix_agentd[20177]: zbx_tls_init_child() loaded PSK from file "/etc/zabbix/zabbix_agentd.psk"
Sep 17 14:03:16 karif zabbix_agentd[20176]: OpenSSL library (version OpenSSL 1.1.0i  14 Aug 2018) initialized
Sep 17 14:03:16 karif zabbix_agentd[20177]: zbx_tls_init_child() PSK ciphersuites: ECDHE-PSK-AES128-CBC-SHA256 ECDHE-PSK-AES128-CBC-SHA PSK-AES128-GCM-SHA256 PSK-AES128-CCM8 PSK-AES128-CCM PSK-AES128-CBC-SHA256 PSK-AES128-CBC-SHA
Sep 17 14:03:16 karif zabbix_agentd[20177]: End of zbx_tls_init_child()
Sep 17 14:03:16 karif zabbix_agentd[20177]: __zbx_zbx_setproctitle() title:'listener #2 [waiting for connection]'
Sep 17 14:03:16 karif zabbix_agentd[20178]: OpenSSL library (version OpenSSL 1.1.0i  14 Aug 2018) initialized
Sep 17 14:03:16 karif zabbix_agentd[20178]: zbx_tls_init_child() loaded PSK identity "PSKkarif"
Sep 17 14:03:16 karif zabbix_agentd[20176]: zbx_tls_init_child() loaded PSK identity "PSKkarif"
Sep 17 14:03:16 karif zabbix_agentd[20178]: zbx_tls_init_child() loaded PSK from file "/etc/zabbix/zabbix_agentd.psk"
Sep 17 14:03:16 karif zabbix_agentd[20176]: zbx_tls_init_child() loaded PSK from file "/etc/zabbix/zabbix_agentd.psk"
Sep 17 14:03:16 karif zabbix_agentd[20178]: zbx_tls_init_child() PSK ciphersuites: ECDHE-PSK-AES128-CBC-SHA256 ECDHE-PSK-AES128-CBC-SHA PSK-AES128-GCM-SHA256 PSK-AES128-CCM8 PSK-AES128-CCM PSK-AES128-CBC-SHA256 PSK-AES128-CBC-SHA
Sep 17 14:03:16 karif zabbix_agentd[20178]: End of zbx_tls_init_child()
Sep 17 14:03:16 karif zabbix_agentd[20178]: __zbx_zbx_setproctitle() title:'listener #3 [waiting for connection]'
Sep 17 14:03:16 karif zabbix_agentd[20176]: zbx_tls_init_child() PSK ciphersuites: ECDHE-PSK-AES128-CBC-SHA256 ECDHE-PSK-AES128-CBC-SHA PSK-AES128-GCM-SHA256 PSK-AES128-CCM8 PSK-AES128-CCM PSK-AES128-CBC-SHA256 PSK-AES128-CBC-SHA
Sep 17 14:03:16 karif zabbix_agentd[20176]: End of zbx_tls_init_child()
Sep 17 14:03:16 karif zabbix_agentd[20176]: __zbx_zbx_setproctitle() title:'listener #1 [waiting for connection]'
Sep 17 14:03:16 karif zabbix_agentd[20179]: OpenSSL library (version OpenSSL 1.1.0i  14 Aug 2018) initialized
Sep 17 14:03:16 karif zabbix_agentd[20179]: zbx_tls_init_child() loaded PSK identity "PSKkarif"
Sep 17 14:03:16 karif zabbix_agentd[20179]: zbx_tls_init_child() loaded PSK from file "/etc/zabbix/zabbix_agentd.psk"
Sep 17 14:03:16 karif zabbix_agentd[20179]: zbx_tls_init_child() PSK ciphersuites: ECDHE-PSK-AES128-CBC-SHA256 ECDHE-PSK-AES128-CBC-SHA PSK-AES128-GCM-SHA256 PSK-AES128-CCM8 PSK-AES128-CCM PSK-AES128-CBC-SHA256 PSK-AES128-CBC-SHA
Sep 17 14:03:16 karif zabbix_agentd[20179]: End of zbx_tls_init_child()
Sep 17 14:03:16 karif zabbix_agentd[20179]: In init_active_metrics()
Sep 17 14:03:16 karif zabbix_agentd[20179]: buffer: first allocation for 100 elements
Sep 17 14:03:16 karif zabbix_agentd[20179]: End of init_active_metrics()
Sep 17 14:03:16 karif zabbix_agentd[20179]: In send_buffer() host:'127.0.0.1' port:10051 entries:0/100
Sep 17 14:03:16 karif zabbix_agentd[20179]: End of send_buffer():SUCCEED
Sep 17 14:03:16 karif zabbix_agentd[20179]: __zbx_zbx_setproctitle() title:'active checks #1 [getting list of active checks]'
Sep 17 14:03:16 karif zabbix_agentd[20179]: In refresh_active_checks() host:'127.0.0.1' port:10051
Sep 17 14:03:16 karif zabbix_agentd[20179]: In zbx_tls_connect(): psk_identity:"PSKkarif"
Sep 17 14:03:16 karif zabbix_agentd[20179]: zbx_psk_client_cb() requested PSK identity "PSKkarif"
Sep 17 14:03:16 karif zabbix_agentd[20179]: End of zbx_tls_connect():SUCCEED (established TLSv1.2 ECDHE-PSK-AES128-CBC-SHA256)
Sep 17 14:03:16 karif zabbix_agentd[20179]: sending [{"request":"active checks","host":"karif"}]
Sep 17 14:03:16 karif zabbix_agentd[20179]: before read
Sep 17 14:03:16 karif zabbix_agentd[20179]: got [{"response":"success","data":[]}]
Sep 17 14:03:16 karif zabbix_agentd[20179]: In parse_list_of_checks()
Sep 17 14:03:16 karif zabbix_agentd[20179]: End of parse_list_of_checks():SUCCEED
Sep 17 14:03:16 karif zabbix_agentd[20179]: End of refresh_active_checks():SUCCEED
Sep 17 14:03:16 karif zabbix_agentd[20179]: __zbx_zbx_setproctitle() title:'active checks #1 [processing active checks]'
Sep 17 14:03:16 karif zabbix_agentd[20179]: In process_active_checks() server:'127.0.0.1' port:10051
```

Here's the log with the NEW openssl version, again filtered with `grep -i -C8 -e tls -e psk`:
```
Sep 17 13:59:39 karif zabbix_agentd[18232]: Starting Zabbix Agent [karif]. Zabbix 3.4.14 (revision 84877).
Sep 17 13:59:39 karif zabbix_agentd[18232]: **** Enabled features ****
Sep 17 13:59:39 karif zabbix_agentd[18232]: IPv6 support:          YES
Sep 17 13:59:39 karif zabbix_agentd[18232]: TLS support:           YES
Sep 17 13:59:39 karif zabbix_agentd[18232]: **************************
Sep 17 13:59:39 karif zabbix_agentd[18232]: using configuration file: /etc/zabbix/zabbix_agentd.conf
Sep 17 13:59:39 karif zabbix_agentd[18232]: Starting Zabbix Agent [karif]. Zabbix 3.4.14 (revision 84877).
Sep 17 13:59:39 karif zabbix_agentd[18232]: Press Ctrl+C to exit.
Sep 17 13:59:39 karif zabbix_agentd[18232]: In zbx_load_modules()
Sep 17 13:59:39 karif zabbix_agentd[18232]: End of zbx_load_modules():SUCCEED
Sep 17 13:59:39 karif zabbix_agentd[18232]: In init_collector_data()
Sep 17 13:59:39 karif zabbix_agentd[18232]: In zbx_dshm_create() size:0
--
Sep 17 13:59:39 karif zabbix_agentd[18232]: End of init_collector_data()
Sep 17 13:59:39 karif zabbix_agentd[18232]: agent #0 started [main process]
Sep 17 13:59:39 karif zabbix_agentd[18233]: agent #1 started [collector]
Sep 17 13:59:39 karif zabbix_agentd[18233]: In init_cpu_collector()
Sep 17 13:59:39 karif zabbix_agentd[18233]: End of init_cpu_collector():SUCCEED
Sep 17 13:59:39 karif zabbix_agentd[18233]: __zbx_zbx_setproctitle() title:'collector [processing data]'
Sep 17 13:59:39 karif zabbix_agentd[18233]: In update_cpustats()
Sep 17 13:59:39 karif zabbix_agentd[18234]: agent #2 started [listener #1]
Sep 17 13:59:39 karif zabbix_agentd[18234]: In zbx_tls_init_child()
Sep 17 13:59:39 karif zabbix_agentd[18235]: agent #3 started [listener #2]
Sep 17 13:59:39 karif zabbix_agentd[18235]: In zbx_tls_init_child()
Sep 17 13:59:39 karif zabbix_agentd[18236]: agent #4 started [listener #3]
Sep 17 13:59:39 karif zabbix_agentd[18236]: In zbx_tls_init_child()
Sep 17 13:59:39 karif zabbix_agentd[18233]: End of update_cpustats()
Sep 17 13:59:39 karif zabbix_agentd[18233]: __zbx_zbx_setproctitle() title:'collector [idle 1 sec]'
Sep 17 13:59:39 karif zabbix_agentd[18237]: agent #5 started [active checks #1]
Sep 17 13:59:39 karif zabbix_agentd[18237]: In zbx_tls_init_child()
Sep 17 13:59:39 karif zabbix_agentd[18234]: OpenSSL library (version OpenSSL 1.1.1  11 Sep 2018) initialized
Sep 17 13:59:39 karif zabbix_agentd[18234]: zbx_tls_init_child() loaded PSK identity "PSKkarif"
Sep 17 13:59:39 karif zabbix_agentd[18235]: OpenSSL library (version OpenSSL 1.1.1  11 Sep 2018) initialized
Sep 17 13:59:39 karif zabbix_agentd[18237]: OpenSSL library (version OpenSSL 1.1.1  11 Sep 2018) initialized
Sep 17 13:59:39 karif zabbix_agentd[18236]: OpenSSL library (version OpenSSL 1.1.1  11 Sep 2018) initialized
Sep 17 13:59:39 karif zabbix_agentd[18235]: zbx_tls_init_child() loaded PSK identity "PSKkarif"
Sep 17 13:59:39 karif zabbix_agentd[18237]: zbx_tls_init_child() loaded PSK identity "PSKkarif"
Sep 17 13:59:39 karif zabbix_agentd[18236]: zbx_tls_init_child() loaded PSK identity "PSKkarif"
Sep 17 13:59:39 karif zabbix_agentd[18234]: zbx_tls_init_child() loaded PSK from file "/etc/zabbix/zabbix_agentd.psk"
Sep 17 13:59:39 karif zabbix_agentd[18235]: zbx_tls_init_child() loaded PSK from file "/etc/zabbix/zabbix_agentd.psk"
Sep 17 13:59:39 karif zabbix_agentd[18237]: zbx_tls_init_child() loaded PSK from file "/etc/zabbix/zabbix_agentd.psk"
Sep 17 13:59:39 karif zabbix_agentd[18236]: zbx_tls_init_child() loaded PSK from file "/etc/zabbix/zabbix_agentd.psk"
Sep 17 13:59:39 karif zabbix_agentd[18235]: zbx_tls_init_child() PSK ciphersuites: TLS_AES_256_GCM_SHA384 TLS_CHACHA20_POLY1305_SHA256 TLS_AES_128_GCM_SHA256 ECDHE-PSK-AES128-CBC-SHA256 ECDHE-PSK-AES128-CBC-SHA PSK-AES128-GCM-SHA256 PSK-AES128-CCM8 PSK-AES128-CCM PSK-AES128-CBC-SHA256 PSK-AES128-CBC-SHA
Sep 17 13:59:39 karif zabbix_agentd[18235]: End of zbx_tls_init_child()
Sep 17 13:59:39 karif zabbix_agentd[18234]: zbx_tls_init_child() PSK ciphersuites: TLS_AES_256_GCM_SHA384 TLS_CHACHA20_POLY1305_SHA256 TLS_AES_128_GCM_SHA256 ECDHE-PSK-AES128-CBC-SHA256 ECDHE-PSK-AES128-CBC-SHA PSK-AES128-GCM-SHA256 PSK-AES128-CCM8 PSK-AES128-CCM PSK-AES128-CBC-SHA256 PSK-AES128-CBC-SHA
Sep 17 13:59:39 karif zabbix_agentd[18235]: __zbx_zbx_setproctitle() title:'listener #2 [waiting for connection]'
Sep 17 13:59:39 karif zabbix_agentd[18236]: zbx_tls_init_child() PSK ciphersuites: TLS_AES_256_GCM_SHA384 TLS_CHACHA20_POLY1305_SHA256 TLS_AES_128_GCM_SHA256 ECDHE-PSK-AES128-CBC-SHA256 ECDHE-PSK-AES128-CBC-SHA PSK-AES128-GCM-SHA256 PSK-AES128-CCM8 PSK-AES128-CCM PSK-AES128-CBC-SHA256 PSK-AES128-CBC-SHA
Sep 17 13:59:39 karif zabbix_agentd[18237]: zbx_tls_init_child() PSK ciphersuites: TLS_AES_256_GCM_SHA384 TLS_CHACHA20_POLY1305_SHA256 TLS_AES_128_GCM_SHA256 ECDHE-PSK-AES128-CBC-SHA256 ECDHE-PSK-AES128-CBC-SHA PSK-AES128-GCM-SHA256 PSK-AES128-CCM8 PSK-AES128-CCM PSK-AES128-CBC-SHA256 PSK-AES128-CBC-SHA
Sep 17 13:59:39 karif zabbix_agentd[18234]: End of zbx_tls_init_child()
Sep 17 13:59:39 karif zabbix_agentd[18234]: __zbx_zbx_setproctitle() title:'listener #1 [waiting for connection]'
Sep 17 13:59:39 karif zabbix_agentd[18236]: End of zbx_tls_init_child()
Sep 17 13:59:39 karif zabbix_agentd[18237]: End of zbx_tls_init_child()
Sep 17 13:59:39 karif zabbix_agentd[18236]: __zbx_zbx_setproctitle() title:'listener #3 [waiting for connection]'
Sep 17 13:59:39 karif zabbix_agentd[18237]: In init_active_metrics()
Sep 17 13:59:39 karif zabbix_agentd[18237]: buffer: first allocation for 100 elements
Sep 17 13:59:39 karif zabbix_agentd[18237]: End of init_active_metrics()
Sep 17 13:59:39 karif zabbix_agentd[18237]: In send_buffer() host:'127.0.0.1' port:10051 entries:0/100
Sep 17 13:59:39 karif zabbix_agentd[18237]: End of send_buffer():SUCCEED
Sep 17 13:59:39 karif zabbix_agentd[18237]: __zbx_zbx_setproctitle() title:'active checks #1 [getting list of active checks]'
Sep 17 13:59:39 karif zabbix_agentd[18237]: In refresh_active_checks() host:'127.0.0.1' port:10051
Sep 17 13:59:39 karif zabbix_agentd[18237]: In zbx_tls_connect(): psk_identity:"PSKkarif"
Sep 17 13:59:39 karif zabbix_agentd[18237]: zbx_psk_client_cb() requested PSK identity "PSKkarif"
Sep 17 13:59:39 karif zabbix_agentd[18237]: End of zbx_tls_connect():SUCCEED (established TLSv1.3 TLS_CHACHA20_POLY1305_SHA256)
Sep 17 13:59:39 karif zabbix_agentd[18237]: sending [{"request":"active checks","host":"karif"}]
Sep 17 13:59:39 karif zabbix_agentd[18237]: before read
Sep 17 13:59:39 karif zabbix_agentd[18237]: Got signal [signal:13(SIGPIPE),sender_pid:18237]. Ignoring ...
Sep 17 13:59:39 karif zabbix_agentd[18237]: SSL_shutdown() with 127.0.0.1 set result code to 6:
Sep 17 13:59:39 karif zabbix_agentd[18237]: active check configuration update from [127.0.0.1:10051] started to fail (connection closed during read)
Sep 17 13:59:39 karif zabbix_agentd[18237]: End of refresh_active_checks():FAIL
Sep 17 13:59:39 karif zabbix_agentd[18237]: __zbx_zbx_setproctitle() title:'active checks #1 [processing active checks]'
Sep 17 13:59:39 karif zabbix_agentd[18237]: In process_active_checks() server:'127.0.0.1' port:10051
Sep 17 13:59:39 karif zabbix_agentd[18237]: End of process_active_checks()
Sep 17 13:59:39 karif zabbix_agentd[18237]: In get_min_nextcheck()
Sep 17 13:59:39 karif zabbix_agentd[18237]: End of get_min_nextcheck():-1
Sep 17 13:59:39 karif zabbix_agentd[18237]: __zbx_zbx_setproctitle() title:'active checks #1 [idle 1 sec]'
Sep 17 13:59:39 karif zabbix_agentd[18236]: In zbx_tls_accept()
Sep 17 13:59:39 karif zabbix_agentd[18236]: zbx_psk_server_cb() requested PSK identity "PSKkarif"
Sep 17 13:59:39 karif zabbix_agentd[18236]: zbx_tls_accept() cannot obtain peer certificate
Sep 17 13:59:39 karif zabbix_agentd[18236]: End of zbx_tls_accept():FAIL error:'unspecified certificate verification error'
Sep 17 13:59:39 karif zabbix_agentd[18236]: failed to accept an incoming connection: from 127.0.0.1: unspecified certificate verification error
Sep 17 13:59:40 karif zabbix_agentd[18233]: __zbx_zbx_setproctitle() title:'collector [processing data]'
Sep 17 13:59:40 karif zabbix_agentd[18233]: In update_cpustats()
Sep 17 13:59:40 karif zabbix_agentd[18233]: End of update_cpustats()
Sep 17 13:59:40 karif zabbix_agentd[18233]: __zbx_zbx_setproctitle() title:'collector [idle 1 sec]'
Sep 17 13:59:40 karif zabbix_agentd[18237]: In send_buffer() host:'127.0.0.1' port:10051 entries:0/100
Sep 17 13:59:40 karif zabbix_agentd[18237]: End of send_buffer():SUCCEED
Sep 17 13:59:40 karif zabbix_agentd[18237]: __zbx_zbx_setproctitle() title:'active checks #1 [idle 1 sec]'
--
Sep 17 13:59:57 karif zabbix_agentd[18237]: __zbx_zbx_setproctitle() title:'active checks #1 [idle 1 sec]'
Sep 17 13:59:58 karif zabbix_agentd[18233]: __zbx_zbx_setproctitle() title:'collector [processing data]'
Sep 17 13:59:58 karif zabbix_agentd[18233]: In update_cpustats()
Sep 17 13:59:58 karif zabbix_agentd[18233]: End of update_cpustats()
Sep 17 13:59:58 karif zabbix_agentd[18233]: __zbx_zbx_setproctitle() title:'collector [idle 1 sec]'
Sep 17 13:59:58 karif zabbix_agentd[18237]: In send_buffer() host:'127.0.0.1' port:10051 entries:0/100
Sep 17 13:59:58 karif zabbix_agentd[18237]: End of send_buffer():SUCCEED
Sep 17 13:59:58 karif zabbix_agentd[18237]: __zbx_zbx_setproctitle() title:'active checks #1 [idle 1 sec]'
Sep 17 13:59:58 karif zabbix_agentd[18234]: In zbx_tls_accept()
Sep 17 13:59:58 karif zabbix_agentd[18234]: zbx_psk_server_cb() requested PSK identity "PSKkarif"
Sep 17 13:59:58 karif zabbix_agentd[18234]: zbx_tls_accept() cannot obtain peer certificate
Sep 17 13:59:58 karif zabbix_agentd[18234]: End of zbx_tls_accept():FAIL error:'unspecified certificate verification error'
Sep 17 13:59:58 karif zabbix_agentd[18234]: failed to accept an incoming connection: from 127.0.0.1: unspecified certificate verification error
Sep 17 13:59:59 karif zabbix_agentd[18233]: __zbx_zbx_setproctitle() title:'collector [processing data]'
Sep 17 13:59:59 karif zabbix_agentd[18233]: In update_cpustats()
Sep 17 13:59:59 karif zabbix_agentd[18233]: End of update_cpustats()
Sep 17 13:59:59 karif zabbix_agentd[18233]: __zbx_zbx_setproctitle() title:'collector [idle 1 sec]'
Sep 17 13:59:59 karif zabbix_agentd[18237]: In send_buffer() host:'127.0.0.1' port:10051 entries:0/100
Sep 17 13:59:59 karif zabbix_agentd[18237]: End of send_buffer():SUCCEED
Sep 17 13:59:59 karif zabbix_agentd[18237]: __zbx_zbx_setproctitle() title:'active checks #1 [idle 1 sec]'
```

**Comment by kaduk** [comment] 2018-09-17 21:02
```SUCCEED (established TLSv1.3 TLS_CHACHA20_POLY1305_SHA256)``` does not look like a failure case.  
It looks like with some TLS 1.3 connections it's trying to use both a PSK and an (X509) certificate, which is unlikely to work in the setup you describe.  But perhaps not for all connections.  It would be good to know what the difference is, if there is some attribute of the different connections that you can ascertain.
Also, it seems likely that disabling TLS 1.3 by setting a smaller maximum protocol version would be a workaround.

The linked ZABBIX issue was closed as a duplicate, though the behavior described seems somewhat different than what it is supposedly a duplicate of (which itself seems to list two problems, one of which is just that a certificate with a weak hash function was attempted to be used).

**Comment by Bluewind** [comment] 2018-09-18 08:27
Sadly zabbix doesn't allow to select the protocol versions or ciphers via the configuration. I still kind of wonder if it is intentional that existing software breaks like this if you add new TLS versions. I tried taking a look at their code, but I don't have experience with openssl nor with zabbix code and they support other ssl implementations too so that file is rather long. In case you want to take a look: https://github.com/zabbix/zabbix/blob/bd849ec61b920dd4a0cfe2cdaa195e6545976d91/src/libs/zbxcrypto/tls.c

Having said that, they just updated their bug and it looks like they are working on resolving it so I guess, if things like this are expected to happen from your side (not judging), you can close this. At first I mostly thought that this was some unintentional API breakage as a side effect of TLS 1.3 refactoring, which might be interesting for you.

**Comment by kaduk** [comment] 2018-09-18 17:40
```
#if OPENSSL_VERSION_NUMBER >= 0x1010000fL	/* OpenSSL 1.1.0 or newer */
	if (0 == strncmp("ECDHE-PSK-", cipher_name, ZBX_CONST_STRLEN("ECDHE-PSK-")) ||
			0 == strncmp("PSK-", cipher_name, ZBX_CONST_STRLEN("PSK-")))
#else
	if (0 == strncmp("PSK-", cipher_name, ZBX_CONST_STRLEN("PSK-")))
#endif
```
Looks highly incompatible with TLS 1.3, which names ciphersuites differently.
(I did not look very hard; there may be other issues as well; etc.)

**Comment by t8m** [comment] 2021-07-19 13:41
Closing as this can be fixed only on the application side.

**Closed by t8m** 2021-07-19 13:41 UTC
