### ISSUE TITLE
Support CMake compilation for OpenSSL.

### ISSUE THREAD

**Issue by hwhsu1231** [openssl/openssl#18897] opened 2022-07-28 08:35 UTC
Although CMake already provides [`FindOpenSSL.cmake`](https://github.com/Kitware/CMake/blob/master/Modules/FindOpenSSL.cmake) module for using `find_package()` in **MODULE** mode, I hope OpenSSL can provide `CMakeLists.txt` to compile this project.

Therefore, we might be able to use `find_package()` in **CONFIG** mode if `openssl-config.cmake` file is generated.

**Comment by mattcaswell** [comment] 2022-07-28 08:57
Duplicate of #10902

**Closed by mattcaswell** 2022-07-28 08:57 UTC
Labels: triaged: feature

**Comment by levitte** [comment] 2022-07-28 14:37
It's not strictly necessary to go full blown `CMakeLists.txt` if all you really need is `openssl-config.cmake`...  the latter should be possible to generate properly anyway regardless.
