### ISSUE TITLE
FIPS seems to be broken in 3.1.6 and later

### ISSUE THREAD

**Issue by oxpa** [openssl/openssl#24826] opened 2024-07-09 15:36 UTC
Hello,

I'm running into an issue using EVP_PKEY_CTX_add1_hkdf_info() . This is related to #23448
I'm trying to run an application with FIPS module in openssl. I'm doing this on alpine linux as it has the freshest openssl.
This Dockerfile is used to build the FIPS module https://github.com/nginxinc/alpine-fips/blob/main/Dockerfile (it does what openssl manuals tell to do: build FIPS from certified, older sources and use that module with newer openssl).
This simple application is used for tests: https://gist.github.com/oxpa/4fb1619513d350250b4d4e363ad611fa . It quites silently if everything works, otherwise outputs a message for a failed stage.

The application works with openssl 3.1.4 with and without FIPS enabled. 
With openssl 3.1.6 without FIPS the test application works
With openssl 3.1.6 (and later) with FIPS enabled - the application fails with "add1 hkdf info failed" message.

I looked through commits between 3.1.4 and 3.1.6, found commit referenced in #23448 . Reverted that change and it fixed the issue for me.

I raised an issue for this problem in alpine linux: https://github.com/alpinelinux/docker-alpine/issues/406 but it seems that it's not Alpines fault FIPS fails.

Is it something wrong with my code or should anything be fixed in openssl?

Regards,

**Comment by nhorman** [comment] 2024-07-09 16:08
I believe you need the fix from https://github.com/openssl/openssl/pull/24661

The fix for your issue was merged shortly after 3.1.6 shipped, and will be available in the next patch release

**Closed** 2024-07-09 16:26 UTC
Labels: issue: bug report

**Comment by nhorman** [comment] 2024-07-09 16:57
Ack, sounds like the issue is solved. Closing, please reopen if you have subsequent issues on this

**Comment by vepatel** [comment] 2024-07-10 08:30
hi @nhorman , is there a date for the next patch release?

**Comment by nhorman** [comment] 2024-07-10 12:43
The next minor release (3.4.0) is planned for October 14th (see https://github.com/orgs/openssl/projects/12/views/5)

There will likely be new patch releases for the 3.1 series, but no fixed date is planned yet
