### ISSUE TITLE
OpenSSL 1.0.2u does not require basic constraints in intermediate CA certificates.

### ISSUE THREAD

**Issue by Immortalem** [openssl/openssl#12132] opened 2020-06-13 12:34 UTC
### Affected Versions
1.0.2u

### Setup
OpenSSL has been compiled from source in an alpine docker container. The following excerpt of the used docker file shows the build related commands:
```
RUN ./config --prefix=/build/ --openssldir=/build/ no-async 
RUN make -s && make install_sw -s
```
After building it the respective OpenSSL version and required libraries have been copied into an minimal docker container (from scratch).

The server is later started using the following command:
`openssl s_server -accept 4433 -Verify 100 -cert /cert/inputCerts/rootv3.pem -key /cert/keys/rootv3.pem -CAfile /cert/inputCerts/root.pem -verify_return_error`

All files mentioned in this report (certificates, keys, etc.) have been included in the attached zip archive.

### Issue
OpenSSL 1.0.2u does not require the Basic Constraints extension in intermediate CA certificates. 
[RFC 5280 Section 4.2.1.9](https://tools.ietf.org/html/rfc5280#section-4.2.1.9) states that "If the cA boolean is not asserted, then the keyCertSign bit in the key usage extension MUST NOT be asserted".

### Reproduction
Connect to the started server using the following command:
`openssl s_client -connect localhost:4433 -cert ROOTv3_CAv3_NoBasicConstraints_LEAF_RSAv3__leaf_certificate1.pem -key rsakey_2.pem -CAfile ROOTv3_CAv3_NoBasicConstraints_LEAF_RSAv3__ca_certificate1.pem`

### Expected Result
OpenSSL should reject the certificate chain since the CA certificate is invalid.

### Actual Result
OpenSSL happily accepts the certificate chain and proceeds with the handshake.

### Attachment
[opensslNoBasicConstraints.zip](https://github.com/openssl/openssl/files/4774574/opensslNoBasicConstraints.zip)

**Comment by FdaSilvaYY** [comment] 2020-06-13 13:00
1.0.2u is EOL, so there will be no fix.
https://www.openssl.org/blog/blog/2019/11/07/3.0-update/ and some other posts
Can it be reproduce on actual versions ?

**Comment by Immortalem** [comment] 2020-06-13 13:09
I couldn't reproduce it on OpenSSL 1.1.1g. I didn't test the 3.0 alpha or the FIPS versions. I chose to still report it since one theoretically can purchase support beyond the public EOL date.

**Comment by mattcaswell** [comment] 2020-09-24 14:54
Since this is 1.0.2 only it won't be fixed. Closing.

**Closed by mattcaswell** 2020-09-24 14:54 UTC
Labels: resolved: wont fix
