### ISSUE TITLE
OpenSSL allows certificate chains in which the intermediate CA certificate has no Key Usage extension.

### ISSUE THREAD

**Issue by Immortalem** [openssl/openssl#12135] opened 2020-06-13 12:54 UTC
### Affected Versions
1.1.1g, 1.0.2u

### Setup
OpenSSL has been compiled from source in an alpine docker container. The following excerpt of the used docker file shows the build related commands:
```
RUN ./config --prefix=/build/ --openssldir=/build/ no-async 
RUN make -s && make install_sw -s
```
After building it the respective OpenSSL version and required libraries have been copied into an minimal docker container (from scratch).

The server is later started using the following command:
`openssl s_server -accept 4433 -Verify 100 -cert /cert/inputCerts/rootv3.pem -key /cert/keys/rootv3.pem -CAfile /cert/inputCerts/root.pem -verify_return_error`

All files mentioned in this report (certificates, keys, etc.) have been included in the attached zip archive.

### Issue
Both OpenSSL versions allow certificate chains in which the intermediate CA certificate has not Key Usage extension. [RFC 5280 Section 4.2.1.3](https://tools.ietf.org/html/rfc5280#section-4.2.1.3) states that "Conforming CAs MUST include this extension in certificates that  contain public keys that are used to validate digital signatures on  other public key certificates or CRLs. When present, conforming CAs  SHOULD mark this extension as critical.". I think that this should be enforced by libraries to improve security.

### Reproduction
Uses OpenSSL 1.1.1 on Ubuntu 18.04.
Connect to the started server using the following command:
`openssl s_client -connect localhost:4433 -cert ROOTv3_CAv3_NoKeyUsage_LEAF_RSAv3__leaf_certificate1.pem -key rsakey_2.pem -CAfile ROOTv3_CAv3_NoKeyUsage_LEAF_RSAv3__ca_certificate1.pem`

### Expected Result
OpenSSL should reject the certificate chain.

### Actual Result
OpenSSL happily accepts the certificate and proceeds with the handshake.

### Attachment
[opensslCaNoKeyUsage.zip](https://github.com/openssl/openssl/files/4774604/opensslCaNoKeyUsage.zip)

**Comment by dcooper16** [comment] 2020-06-15 14:51
Hi @Immortalem,

I disagree with your conclusion that OpenSSL should reject a certificate chain just because an intermediate certificate does not have a keyUsage extension. While it is true that [RFC 5280 Section 4.2.1.3](https://tools.ietf.org/html/rfc5280#section-4.2.1.3) states that "Conforming CAs MUST...," that text specifically applies to Conforming CAs, not conforming applications.

Note that [RFC 5280 Section 6.1](https://tools.ietf.org/html/rfc5280#section-6.1), Basic Path Validation, says:
> While the certificate and CRL profiles specified in Sections [4](https://tools.ietf.org/html/rfc5280#section-4) and [5](https://tools.ietf.org/html/rfc5280#section-5) of this document specify values for certificate and CRL fields and extensions that are considered to be appropriate for the Internet PKI, the algorithm presented in this section is not limited to accepting certificates and CRLs that conform to these profiles.  Therefore, the algorithm only includes checks to verify that the certification path is valid according to X.509 and does not include checks to verify that the certificates and CRLs conform to this profile.  While the algorithm could be extended to include checks for conformance to the profiles in Sections [4](https://tools.ietf.org/html/rfc5280#section-4) and [5](https://tools.ietf.org/html/rfc5280#section-5), this profile RECOMMENDS against including such checks.

This is why the step (n) in [Section 6.1.4](https://tools.ietf.org/html/rfc5280#section-6.1.4), Preparation for Certificate i+1, says:
>       (n)  If a key usage extension is present, verify that the
>            keyCertSign bit is set.

and step (f) in [Section 6.3.3](https://tools.ietf.org/html/rfc5280#section-6.3.3),  CRL Processing, says:
>       (f)  Obtain and validate the certification path for the issuer of
>            the complete CRL.  The trust anchor for the certification
>            path MUST be the same as the trust anchor used to validate
>            the target certificate.  If a key usage extension is present
>            in the CRL issuer's certificate, verify that the cRLSign bit
>            is set.

These steps may be contrasted with step (k) in [Section 6.1.4](https://tools.ietf.org/html/rfc5280#section-6.1.4), which does call for rejecting a path if an intermediate v3 certificate does not have a basicConstraints extension:
>       (k)  If certificate i is a version 3 certificate, verify that the
>            basicConstraints extension is present and that cA is set to
>            TRUE.  (If certificate i is a version 1 or version 2
>            certificate, then the application MUST either verify that
>            certificate i is a CA certificate through out-of-band means
>            or reject the certificate.  Conforming implementations may
>            choose to reject all version 1 and version 2 intermediate
>            certificates.)

**Comment by richsalz** [comment] 2020-06-15 15:00
BTW, @dcooper16 is a co-author of the RFC and works at NIST :)

**Comment by Immortalem** [comment] 2020-06-15 15:49
Hi @dcooper16 ,
I totally agree that the standard itself does not require libraries to enforce the existence of the Key Usage extension in intermediate CA certificates. As you already stated it even recommends against doing so which is why I stated that I think OpenSSL should do so, not that it must do so. 

X.509v3, as opposed to v1 and v2, provides a stronger assurance in the correctness of the certification path. I think that implementations should try to improve upon this. This, in my opinion, includes to ensure that the certification path is secure as well as correct and that entities within that path behave in accordance with security and specification requirements. I think that a CA which fails to adhere to simply requirements in the RFC is not necessarily trustworthy and might weaken or compromise the chain of trust.

Regardless, I'm aware that others might not share my opinion that the security, potentially at the cost of compatibility, should be improved as much as possible.

**Comment by dcooper16** [comment] 2020-06-17 12:52
The general question you raise is always a difficult one. If one side of a protocol (CA, TLS client, TLS server) is not following the standard, should the other side work to tolerate the other side's bug in order to make things work, or should it reject what the other side is sending in the hopes that the other side will eventually be forced to fix its code.

I am not convinced that applies in this case, however. X.509 is the underlying standard, and [RFC 5280](https://tools.ietf.org/html/rfc5280) is just a profile of X.509. This is even stated in [RFC 5280 Section 2](https://tools.ietf.org/html/rfc5280#section-2) (note particularly the second paragraph quoted below):

> 
> The goal of this specification is to develop a profile to facilitate the use of X.509 certificates within Internet applications for those communities wishing to make use of X.509 technology.  Such applications may include WWW, electronic mail, user authentication, and IPsec.  In order to relieve some of the obstacles to using X.509 certificates, this document defines a profile to promote the development of certificate management systems, development of application tools, and interoperability determined by policy.
> 
> Some communities will need to supplement, or possibly replace, this profile in order to meet the requirements of specialized application domains or environments with additional authorization, assurance, or operational requirements.  However, for basic applications, common representations of frequently used attributes are defined so that application developers can obtain necessary information without regard to the issuer of a particular certificate or certificate revocation list (CRL).

So, I see no reason that OpenSSL should reject a certificate that complies with X.509, but not with the [RFC 5280](https://tools.ietf.org/html/rfc5280) profile of X.509. Granted I think it is a good idea for every certificate to include a keyUsage extension, but it is not an X.509 requirement.

**Comment by mattcaswell** [comment] 2020-09-24 14:55
Looks like this has been marked as "resolved: not a bug", so closing.

**Closed by mattcaswell** 2020-09-24 14:55 UTC
Labels: resolved: not a bug
