### ISSUE TITLE
Many functions in <openssl/evp.h> are undocumented

### ISSUE THREAD

**Issue by mspncp** [openssl/openssl#5193] opened 2018-01-29 16:51 UTC
I noticed that a lot of functions (and function-like macros) from the EVP API are undocumented. So I wrote a little script to test it systematically:

The file [evp-api.txt](https://github.com/openssl/openssl/files/1674366/evp-api.txt) contains the list of functions I checked. It was extracted manually from `<openssl/evp.h>`. Using the script

```
#!/bin/bash

for f in $(cat evp-api.txt); do
	(man $f |& awk '/No manual entry for/{print $5}')
done
```
I extracted the following list of undocumented functions (see [evp-api-undocumented.txt](https://github.com/openssl/openssl/files/1674367/evp-api-undocumented.txt)):

```
BIO_f_reliable
BIO_set_md_ctx
ERR_load_EVP_strings
EVP_CIPHER_CTX_buf_noconst
EVP_CIPHER_CTX_clear_flags
EVP_CIPHER_CTX_copy
EVP_CIPHER_CTX_encrypting
EVP_CIPHER_CTX_iv
EVP_CIPHER_CTX_iv_noconst
EVP_CIPHER_CTX_num
EVP_CIPHER_CTX_original_iv
EVP_CIPHER_CTX_rand_key
EVP_CIPHER_CTX_set_flags
EVP_CIPHER_CTX_set_num
EVP_CIPHER_CTX_test_flags
EVP_CIPHER_do_all
EVP_CIPHER_do_all_sorted
EVP_CIPHER_get_asn1_iv
EVP_CIPHER_impl_ctx_size
EVP_CIPHER_name
EVP_CIPHER_set_asn1_iv
EVP_Cipher
EVP_DECODE_LENGTH
EVP_Digest
EVP_ENCODE_LENGTH
EVP_MD_CTX_clear_flags
EVP_MD_CTX_pkey_ctx
EVP_MD_CTX_set_flags
EVP_MD_CTX_set_update_fn
EVP_MD_CTX_test_flags
EVP_MD_CTX_update_fn
EVP_MD_do_all
EVP_MD_do_all_sorted
EVP_MD_flags
EVP_MD_name
EVP_MD_nid
EVP_PBE_CipherInit
EVP_PBE_alg_add
EVP_PBE_alg_add_type
EVP_PBE_cleanup
EVP_PBE_find
EVP_PBE_get
EVP_PBE_scrypt
EVP_PKEY_CTX_ctrl_uint64
EVP_PKEY_CTX_get0_peerkey
EVP_PKEY_CTX_get0_pkey
EVP_PKEY_CTX_get_data
EVP_PKEY_CTX_get_operation
EVP_PKEY_CTX_get_signature_md
EVP_PKEY_CTX_hex2ctrl
EVP_PKEY_CTX_md
EVP_PKEY_CTX_set0_keygen_info
EVP_PKEY_CTX_set_data
EVP_PKEY_CTX_set_mac_key
EVP_PKEY_CTX_str2ctrl
EVP_PKEY_assign
EVP_PKEY_assign_POLY1305
EVP_PKEY_assign_SIPHASH
EVP_PKEY_bits
EVP_PKEY_decrypt_old
EVP_PKEY_encrypt_old
EVP_PKEY_get0
EVP_PKEY_get0_poly1305
EVP_PKEY_get0_siphash
EVP_PKEY_get1_tls_encodedpoint
EVP_PKEY_new_mac_key
EVP_PKEY_save_parameters
EVP_PKEY_set1_tls_encodedpoint
EVP_PKEY_set_type
EVP_PKEY_set_type_str
EVP_add_alg_module
EVP_add_cipher
EVP_add_cipher_alias
EVP_add_digest
EVP_add_digest_alias
EVP_aes_128_cfb128
EVP_aes_192_cfb128
EVP_aes_256_cfb128
EVP_aria_128_cfb128
EVP_aria_192_cfb128
EVP_aria_256_cfb128
EVP_bf_cfb64
EVP_camellia_128_cfb128
EVP_camellia_192_cfb128
EVP_camellia_256_cfb128
EVP_cast5_cfb64
EVP_delete_cipher_alias
EVP_delete_digest_alias
EVP_des_cfb64
EVP_des_ede3_cfb64
EVP_des_ede3_ecb
EVP_des_ede_cfb64
EVP_des_ede_ecb
EVP_get_pw_prompt
EVP_idea_cfb64
EVP_md5_sha1
EVP_rc2_cfb64
EVP_rc5_32_12_16_cfb64
EVP_read_pw_string
EVP_read_pw_string_min
EVP_seed_cfb128
EVP_set_pw_prompt
EVP_sm4_cfb128
PKCS5_PBE_add
PKCS5_PBE_keyivgen
PKCS5_v2_PBE_keyivgen
PKCS5_v2_scrypt_keyivgen
```

**Comment by mattcaswell** [comment] 2018-01-29 16:55
Try this:

`util/find-doc-nits -d`

**Comment by mspncp** [comment] 2018-01-29 16:56
Ok, I see ;-) Should I close this again?

**Comment by mattcaswell** [comment] 2018-01-29 17:06
Well, its a valid (and important) issue. We *know* there is a *lot* of missing documentation. The problem is how we address that. As a first step I'd like to see us tackle missing libssl documentation:

````
$ util/find-doc-nits -d | grep ":SSL" | wc -l
110
````

Now 110 missing functions/macros is a lot...but its an achievable amount to document compared to the huge number of libcrypto missing functions/macros.

Missing EVP functions are not beyond the realms of achievability either:

````
$ util/find-doc-nits -d | grep ":EVP" | wc -l
159
````
So, on reflection, I'd be tempted to keep this issue open as a placeholder for missing documentation in EVP. When we've fixed the 159 missing ones we can close this issue.

**Comment by paulidale** [comment] 2018-01-29 22:20
Some of these names are referenced by the current documentation.  E.g. `EVP_MD_CTX_set_flags` is mentioned in HMAC.pod:

> HMAC_CTX_set_flags() applies the specified flags to the internal EVP_MD_CTXs.
> These flags have the same meaning as for L<EVP_MD_CTX_set_flags(3)>.

There are others, I only checked a couple.

**Comment by mspncp** [comment] 2018-01-29 23:32
You are right, EVP_MD_CTX_set_flags is mentioned. But the link is broken, it's an undefined reference.

**Comment by mspncp** [comment] 2018-10-17 10:44
A lot of progress was made in #7345 by @evqna w.r.t. this issue. Thanks a lot!

**Comment by romen** [comment] 2018-10-17 11:44
Updated list from `master`:

```bash
$ util/find-doc-nits -d | grep ":EVP" | tee >(wc -l)
crypto:EVP_CIPHER_CTX_buf_noconst
crypto:EVP_CIPHER_CTX_clear_flags
crypto:EVP_CIPHER_CTX_copy
crypto:EVP_CIPHER_CTX_encrypting
crypto:EVP_CIPHER_CTX_iv
crypto:EVP_CIPHER_CTX_iv_noconst
crypto:EVP_CIPHER_CTX_num
crypto:EVP_CIPHER_CTX_original_iv
crypto:EVP_CIPHER_CTX_rand_key
crypto:EVP_CIPHER_CTX_set_flags
crypto:EVP_CIPHER_CTX_set_num
crypto:EVP_CIPHER_CTX_test_flags
crypto:EVP_CIPHER_do_all
crypto:EVP_CIPHER_do_all_sorted
crypto:EVP_CIPHER_get_asn1_iv
crypto:EVP_CIPHER_impl_ctx_size
crypto:EVP_CIPHER_set_asn1_iv
crypto:EVP_Cipher
crypto:EVP_Digest
crypto:EVP_MD_CTX_pkey_ctx
crypto:EVP_MD_CTX_set_update_fn
crypto:EVP_MD_CTX_update_fn
crypto:EVP_MD_do_all
crypto:EVP_MD_do_all_sorted
crypto:EVP_MD_flags
crypto:EVP_PBE_CipherInit
crypto:EVP_PBE_alg_add
crypto:EVP_PBE_alg_add_type
crypto:EVP_PBE_cleanup
crypto:EVP_PBE_find
crypto:EVP_PBE_get
crypto:EVP_PBE_scrypt
crypto:EVP_PKCS82PKEY
crypto:EVP_PKEY2PKCS8
crypto:EVP_PKEY_CTX_get0_peerkey
crypto:EVP_PKEY_CTX_get0_pkey
crypto:EVP_PKEY_CTX_get_data
crypto:EVP_PKEY_CTX_get_operation
crypto:EVP_PKEY_CTX_hex2ctrl
crypto:EVP_PKEY_CTX_set0_keygen_info
crypto:EVP_PKEY_CTX_set_data
crypto:EVP_PKEY_CTX_str2ctrl
crypto:EVP_PKEY_add1_attr
crypto:EVP_PKEY_add1_attr_by_NID
crypto:EVP_PKEY_add1_attr_by_OBJ
crypto:EVP_PKEY_add1_attr_by_txt
crypto:EVP_PKEY_assign
crypto:EVP_PKEY_bits
crypto:EVP_PKEY_decrypt_old
crypto:EVP_PKEY_delete_attr
crypto:EVP_PKEY_encrypt_old
crypto:EVP_PKEY_get0
crypto:EVP_PKEY_get1_tls_encodedpoint
crypto:EVP_PKEY_get_attr
crypto:EVP_PKEY_get_attr_by_NID
crypto:EVP_PKEY_get_attr_by_OBJ
crypto:EVP_PKEY_get_attr_count
crypto:EVP_PKEY_save_parameters
crypto:EVP_PKEY_set1_tls_encodedpoint
crypto:EVP_PKEY_set_type
crypto:EVP_PKEY_set_type_str
crypto:EVP_add_alg_module
crypto:EVP_add_cipher
crypto:EVP_add_digest
crypto:EVP_get_pw_prompt
crypto:EVP_read_pw_string
crypto:EVP_read_pw_string_min
crypto:EVP_set_pw_prompt
include/openssl/evp.h:EVP_MD_nid
include/openssl/evp.h:EVP_MD_name
include/openssl/evp.h:EVP_CIPHER_name
include/openssl/evp.h:EVP_ENCODE_LENGTH
include/openssl/evp.h:EVP_DECODE_LENGTH
include/openssl/evp.h:EVP_add_cipher_alias
include/openssl/evp.h:EVP_add_digest_alias
include/openssl/evp.h:EVP_delete_cipher_alias
include/openssl/evp.h:EVP_delete_digest_alias
include/openssl/evp.h:EVP_MD_CTX_create
include/openssl/evp.h:EVP_MD_CTX_init
include/openssl/evp.h:EVP_MD_CTX_destroy
include/openssl/evp.h:EVP_CIPHER_CTX_init
include/openssl/evp.h:EVP_CIPHER_CTX_cleanup
82
```

**Comment by t8m** [comment] 2021-05-12 11:05
I do not think we need this issue as we now track the functions missing documentation in missingcrypto.txt.

**Closed by t8m** 2021-05-12 11:05 UTC
