### ISSUE TITLE
Make pkg-config files relocatable

### ISSUE THREAD

**Issue by reddwarf69** [openssl/openssl#13080] opened 2020-10-06 07:49 UTC
As per https://cgit.freedesktop.org/pkg-config/tree/pkg-config.1 the pcfiledir variable can be used to make the pkg-config files relocatable. It would be nice if the openSSL ones would.
It's a relatively simple change. I'm not doing it myself mainly because I don't know perl and don't know how to get the path of one directory relative to another, which you need to handle the case when libdir isn't simply ${exec_prefix}/$(LIBDIR), given that pcfiledir is ${libdir}/pkgconfig.

**Comment by geoff-nixon** [comment] 2020-12-06 15:24
Is this behavior compatible with non-GPL [pkgconf](http://github.com/pkgconf/pkgconf) as well as the "original" [pkg-config](https://gitlab.freedesktop.org/pkg-config/pkg-config)? Also, what happens if an install is lib-only, and has no executables?

**Comment by RedDwarf69** [comment] 2020-12-06 17:17
After opening this I actually discovered it only works reliably well with pkgconf. With pkg-config, when used in combination with PKG_CONFIG_SYSROOT_DIR, the PKG_CONFIG_SYSROOT_DIR may end up duplicated in the cflags includedir.

So this would need to be done either:
- As a Configure option
- Dropping (full) support for the original pkg-config

**Comment by richsalz** [comment] 2020-12-06 19:39
Is there a a problem with a duplicate -I flag?

**Comment by RedDwarf69** [comment] 2020-12-06 19:51
If you install a relocatable openssl.pc in /lala/lib/pkgconfig/openssl.pc

`PKG_CONFIG_SYSROOT_DIR=/lala pkg-config --libs openssl` will output
- `-L/lala/lala/lib/pkgconfig/..` with pkg-config
- `-L/lala/lib/pkgconfig/..` with pkgconf

i.e. pkgconf is smart enough to understand the sysroot is already part of the path, pkg-config isn't.

**Comment by richsalz** [comment] 2020-12-06 19:54
Thanks for the explanation, @RedDwarf69 .  I mistakenly thought it was about ```-I``` flags, not ```-L``` flags.

**Comment by RedDwarf69** [comment] 2020-12-06 22:47
It's with both.

Anyway, I don't really need this any more. I do know for a fact that at least some people still use pkg-config, and they use it with PKG_CONFIG_SYSROOT_DIR, so... I guess a option in the Configure script would be nice. But if you would rather close it I don't mind.

**Comment by geoff-nixon** [comment] 2020-12-07 05:47
Its used pretty extensively with package managers like Homebrew, etc. Which also (for some reason) uses pkg-config. There are other issues on some platforms with a "portable" openssl—unless the whole thing is compiled statically and/or the library names are also properly relativized, i.e.,:

```
sh-3.2# otool -L /usr/lib/libssl.dylib
/usr/lib/libssl.dylib:
	/usr/lib/libssl.dylib (compatibility version 1.0.0, current version 47.140.1)
```

changed to
`@rpath/libssl.dylib` or `@loader_path/../libssl.dylib`, etc. Plus, yeah, PKG_CONFIG_PATH, etc., etc...

So, yeah, I concur. Good idea in theory.

**Comment by nhorman** [comment] 2024-06-12 01:42
closing as a duplicate of https://github.com/openssl/openssl/issues/24298

**Closed** 2024-06-12 01:42 UTC
Labels: triaged: feature
