### ISSUE TITLE
The s_client -reconnect option does not work with TLSv1.3

### ISSUE THREAD

**Issue by mattcaswell** [openssl/openssl#15979] opened 2021-07-02 09:37 UTC
The "-reconnect" option to s_client is supposed to attempt to reconnect to a server 5 times - each time reusing the session. This works fine in TLSv1.2 and below. However in TLSv1.3 the client fails to send the PSK from the session ticket when attempting to reconnect.

**Comment by kaduk** [comment] 2021-07-03 18:44
I wonder if it's related to #15951 .
I may be able to look at it next week, if I have time.

**Comment by mattcaswell** [comment] 2021-07-05 09:23
> I may be able to look at it next week, if I have time.

That would be great

**Comment by amithm7** [comment] 2021-12-18 08:45
Duplicate of #10714

**Closed** 2021-12-20 01:49 UTC
Labels: branch: master, branch: 1.1.1, resolved: duplicate, triaged: bug
