### ISSUE TITLE
Unknown OpenSSL error

### ISSUE THREAD

**Issue by SecUpwN** [openssl/openssl#774] opened 2016-03-01 23:16 UTC
Good evening @openssl developers, I am experiencing an Issue that nobody seems to be able to help me with. When installing [torbrowser-launcher](https://github.com/micahflee/torbrowser-launcher) on [openSUSE Tumbleweed](https://en.opensuse.org/Portal:Tumbleweed) and doing an upgrade, I'm getting the following `Unknown OpenSSL error` as can be seen in this [logfile](https://defuse.ca/b/tlOAU5dS). I already filed the Issue on https://github.com/pyca/cryptography/issues/2727 (closed due to "irrelevance") and of course on https://github.com/micahflee/torbrowser-launcher/issues/221. But maybe you can give me a clue what is causing this bug and how to maybe resolve it?

**Comment by mattcaswell** [comment] 2016-03-01 23:44
There are three OpenSSL error codes given in that dump:
235372546 (== E078002 hex)
537317378 (==2006D002 hex)
33558541 (==200100D hex)

Normally, if the application has initialised the OpenSSL error strings you get readable error messages. If the application has NOT initialised the error strings you get error codes like the above. You can use the `openssl errstr` command to give more helpful output:

````
$ openssl errstr E078002
error:0E078002:configuration file routines:def_load:system lib
$ openssl errstr 2006D002
error:2006D002:BIO routines:BIO_new_file:system lib
$ openssl errstr 200100D
error:0200100D:system library:fopen:Permission denied
````
The "def_load" function mentioned above is in the OpenSSL configuration file loading routines. It is attempting to open a config file for read, but is hitting a permission denied error. You need to figure out from the application what the path for the config file is that it is trying to load, and why it is getting permission denied.

**Comment by SecUpwN** [comment] 2016-03-02 16:15
>The "def_load" function mentioned above is in the OpenSSL configuration file loading routines. It is attempting to open a config file for read, but is hitting a permission denied error. You need to figure out from the application what the path for the config file is that it is trying to load, and why it is getting permission denied.

Huge thanks for analyzing these error codes and helping me to find the cause, @mattcaswell! I've been trying to find the a possible configuratiuon file for `torbrowser-launcher` by using `which torbrowser-launcher`, which tells me it would reside in `/usr/bin/torbrowser-launcher`. But having a look there, I cannot find it - even when unhiding hidden files. How to find the config file in question?

**Comment by mattcaswell** [comment] 2016-03-02 21:11
I dug a bit deeper into this. Based on the traceback you provided I tried to figure out what was happening in the calls to openssl by the application. The last bit of the traceback looks like this:
````
   File "/usr/lib64/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 156, in _ensure_ffi_initialized
     cls._register_osrandom_engine()
   File "/usr/lib64/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 121, in _register_osrandom_engine
     _openssl_assert(cls.lib, cls.lib.ERR_peek_error() == 0)
   File "/usr/lib64/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 43, in _openssl_assert
     errors
````
Google was my friend, and I found this code:
https://github.com/pyca/cryptography/blob/master/src/cryptography/hazmat/bindings/openssl/binding.py#L121

Here you can see the `_register_osrandom_engine` mentioned in the traceback. Also notice that the first thing it does is an assert to check that there are no errors on the OpenSSL error queue already. Apparently there are because it is that assert that fails.

Going back up the stack we see the function `_ensure_ffi_initialized` (on line 146). This is more interesting and you can see that what it is doing is calling the standard OpenSSL initialisation. Note that none of these are explicitly loading a config file as I had assumed. However, it is possible to implicitly load the default OpenSSL config file through the OpenSSL_add_all_algorithms() function. You have to compile the application with OPENSSL_LOAD_CONF defined for it to do this...but if you do then calling OpenSSL_add_all_algorithms() will call OPENSSL_config(NULL) automatically. Passing NULL to that function will use the default config file.

The default config file is called openssl.cnf and is located in the OPENSSLDIR directory. The value of OPENSSLDIR can vary and depends on the options selected at compile time. A custom compiled OpenSSL will, by default, have this set to "/usr/local/ssl", but this is often changed by distros. Running this command will tell you the value of OPENSSLDIR for your system:

`openssl version -d`

Alternatively the application or user may set the OPENSSL_CONF environment variable to override the default location.

**Comment by SecUpwN** [comment] 2016-03-02 21:58
Thanks @mattcaswell. So the error is indeed caused by `cryptography`? If so, I wonder what @pyca, @alex and @reaperhulk say abou the above since they closed https://github.com/pyca/cryptography/issues/2727 and said it would have nothing to do with their package.

**Comment by reaperhulk** [comment] 2016-03-02 23:15
Interesting, I did not know that `OpenSSL_add_all_algorithms` (which pyca/cryptography calls during initialization of course) could potentially trigger a conf load. As @mattcaswell noted we assert that the error stack is empty, so an error caused by a permissions problem during load would make us bail out.

The real question at this point is: why are you seeing this now and what changed? Was there a significantly older version of pyca/cryptography installed previously?

**Comment by mattcaswell** [comment] 2016-03-02 23:27
@reaperhulk's suggestion (in the 2727 ticket) that it could be caused by something else using OpenSSL in the same process space is also a plausible explanation. It all depends on whether OPENSSL_LOAD_CONF has been defined at *application* compile time. Either way it certainly caused by a permissions problem on an openssl config file somewhere, so it seems sensible to further investigate that. See if you can locate your system default config by looking in OPENSSLDIR and check what the permissions are.

**Comment by SecUpwN** [comment] 2016-03-03 05:33
>The real question at this point is: why are you seeing this now and what changed? Was there a significantly older version of pyca/cryptography installed previously?

@reaperhulk, that might be. As already said in every Issue, I am using [openSUSE Tumbleweed](https://en.opensuse.org/Portal:Tumbleweed), which is a rolling release - I update it to the very bleeding edge every single day.

>See if you can locate your system default config by looking in OPENSSLDIR and check what the permissions are.

```
SecUpwN@GLaDOS:~> ls -l /usr/bin/openssl
-rwxr-xr-x 1 root root 582936 13. Dez 11:27 /usr/bin/openssl
```

**Comment by mattcaswell** [comment] 2016-03-03 09:30
That's the openssl binary not the default config file. Run
````
openssl version -d
````
To get the OPENSSLDIR value. Then look in that directory at the config file permissions.

**Comment by SecUpwN** [comment] 2016-03-03 09:47
```
SecUpwN@GLaDOS:~> openssl version -d
OPENSSLDIR: "/etc/ssl"
```
```
SecUpwN@GLaDOS:~> ls -l /etc/ssl/openssl.cnf
-rw-r--r-- 1 root root 10835 13. Dez 11:27 /etc/ssl/openssl.cnf
```

**Comment by mattcaswell** [comment] 2016-03-03 10:02
Hmmm. Looks ok. You could try running the application through strace. You're likely to see a lot of output but it might give you a clue as to whether its this config file or some other one causing the problem. E.g.
````
strace myapp 2>strace.log
grep open strace.log
````

**Comment by SecUpwN** [comment] 2016-03-03 10:14
Thanks for being so patient with me, @mattcaswell. Can you make sens of [this stacktrace](https://defuse.ca/b/0FnZquS8)?

**Comment by levitte** [comment] 2016-03-03 10:19
> ```
SecUpwN@GLaDOS:~> ls -l /etc/ssl/openssl.cnf
-rw-r--r-- 1 root root 10835 13. Dez 11:27 /etc/ssl/openssl.cnf
```

May I suggest this as well?

```
ls -ld /etc /etc/ssl
```

The permissions might be correct on the file, but what about the directories to reach it?

**Comment by mattcaswell** [comment] 2016-03-03 10:27
This is your problem:
````
 open("/etc/ssl/openssl.cnf", O_RDONLY|O_CLOEXEC) = -1 EACCES (Permission denied)
````
That appears quite early in the output log (line 2032 of 7697) so it does appear that the problem is some earlier OpenSSL usage leaving a stale error on the error queue.

**Comment by SecUpwN** [comment] 2016-03-04 12:33
@mattcaswell, wonderful to finally know what's wrong. How to fix this? I'm doing a `sudo zypper dup` each day, so I guess it should be current. Right now I am on `OpenSSL 1.0.2e-fips 3 Dec 2015`.

Thanks for chiming in as well, @levitte! Here's the answer to your question:

```
SecUpwN@GLaDOS:~> ls -ld /etc /etc/ssl
drwxr-xr-x 1 root root 5278  4. Mär 13:25 /etc
drwxr-xr-x 1 root root   72 12. Feb 21:38 /etc/ssl
```

**Comment by mattcaswell** [comment] 2016-05-16 20:20
This is a permissions problem external to OpenSSL so closing this.

**Closed by mattcaswell** 2016-05-16 20:20 UTC

**Comment by ericoporto** [comment] 2020-06-02 12:15
what are the RIGHT permissions?
