### ISSUE TITLE
can't compile openssl 1.1.1b on x86_64-linux-musl

### ISSUE THREAD

**Issue by protonesso** [openssl/openssl#8800] opened 2019-04-20 14:06 UTC
Hi, I'm trying to compile openssl under my chroot environment. But it gives me this:
```
gcc  -Iinclude -fPIC -pthread -m64 -Wa,--noexecstack -Wall -O3 -Os -fexcess-precision=fast -fomit-frame-pointer -pipe -Wa,--noexecstack -DNDEBUG  -MMD -MF engines/e_ossltest.d.tmp -MT engines/e_ossltest.o -c -o engines/e_ossltest.o engines/e_ossltest.c
Invalid version number 1_1_1 is greater than 1_1_1b or is invalid
make[1]: *** [Makefile:762: libcrypto.map] Error 25
make[1]: *** Waiting for unfinished jobs....
Invalid version number 1_1_1 is greater than 1_1_1b or is invalid
make[1]: *** [Makefile:5929: libssl.map] Error 25
make[1]: Leaving directory '/var/cache/ports/packages/openssl/work/src/openssl-1.1.1b'
make: *** [Makefile:172: all] Error 2
```
Full log: https://pastebin.com/Hijcc1Qs

I use perl 5.28.2, musl libc 1.1.22 and gcc 8.3.0

**Comment by kroeckx** [comment] 2019-04-20 14:32
This seems to be a duplicate of #8032

**Comment by protonesso** [comment] 2019-04-20 14:58
idk I just have same problem

**Comment by levitte** [comment] 2019-04-20 15:12
Same as in #8032, it would be nice to know what makes musl different...

**Comment by xellworks** [comment] 2019-05-06 09:25
I have had the same problem.
It was solved by recompiling perl with -Accflags=-D_GNU_SOURCE
It was due to perl bug #133810
https://rt.perl.org/Public/Bug/Display.html?id=133810

**Comment by protonesso** [comment] 2019-05-12 12:24
@xellworks thanks!

**Closed** 2019-05-13 16:09 UTC
