### ISSUE TITLE
05-test_rand.t failing for debug builds

### ISSUE THREAD

**Issue by kimaluco17** [openssl/openssl#10086] opened 2019-10-03 14:37 UTC
Whenever I build with --debug or debug-VC-WIN32, one of the tests (looks like drbg_cavs_test) in 05-test_rand.t fails. This does not happen when building release version. I've attached a log file with the results of the build and the tests.

I'm using this configuration:
`perl Configure VC-WIN32 no-asm --prefix=%prefix_base%%prefix_ext% --debug`

[test_debug.log](https://github.com/openssl/openssl/files/3686594/test_debug.log)

Is there something that I'm missing to make it pass?

**Comment by mattcaswell** [comment] 2019-10-03 14:41
Please try running:

````
nmake TESTS=test_rand V=1 test
````
And then post the output

**Comment by kimaluco17** [comment] 2019-10-03 16:37
Thanks for the quick response, here's the output.

[test.log](https://github.com/openssl/openssl/files/3687136/test.log)

**Comment by mattcaswell** [comment] 2019-10-04 07:02
These two lines seem somewhat surprising:

````
OPENSSL_Uplink(5A962350,08): no OPENSSL_Applink
F:\development\OpenSSL\openssl-1.1.1d\test\drbg_cavs_test.exe => 1
````

@levitte - any thoughts?

**Comment by paulidale** [comment] 2019-10-04 07:53
@slontis ???

**Comment by mspncp** [comment] 2019-10-04 11:14
FWIW: I was not able to reproduce the issue with OpenSSL_1_1_1-stable (currently at a80de34b27) using Visual Studio 2019, neither with the x86 native tools command prompt and `perl Configure VC-WIN32 no-asm`, nor with the x64 native tools command prompt and `perl Configure VC-WIN64A no-asm`.

**Comment by kimaluco17** [comment] 2019-10-04 15:11
I forgot to mention that I'm using 1.1.1d.

As a sanity check, I will try building a fresh debug build again to see if I get the same result. But I still don't understand why the release configuration would pass.

**Comment by mspncp** [comment] 2019-10-04 15:36
> I forgot to mention that I'm using 1.1.1d.

I can retry with the tagged commit, but I doubt it will make a difference.

**Comment by mspncp** [comment] 2019-10-04 16:00
`nmake TESTS=test_rand V=1 test` succeeds also with OpenSSL_1_1_1d (commit 894da2fb7ed5d314ee5c2fc9fd2d9b8b74111596) with Visual Studio 2019, x86 native tools command prompt.

**Comment by kimaluco17** [comment] 2019-10-04 16:07
Still getting the same result, I am running it from a VS 2017 x86 developer command prompt.

I've also tried building with the latest version of NASM, no difference there.

**Comment by mspncp** [comment] 2019-10-04 18:43
I have two more ideas before I give up:

1. Please check using Process Monitor whether `drbg_cavs_test.exe` is picking up the correct shared library. In my case, the executable is in `C:\src\openssl-1.1.1\test` and the process monitor trace shows:

```
20:37:32,8201449	drbg_cavs_test.exe	4476	Load Image	C:\src\openssl-1.1.1\test\libcrypto-1_1.dll	Image Base: 0xf390000, Image Size: 0x227000	SUCCESS
```
If you see that the correct dll is loaded, proceed with step 2:

2. Run the program (in my case `C:\src\openssl-1.1.1\test\drbg_cavs_test.exe`) in the Visual Studio debugger and set a breakpoint at `OPENSSL_Uplink()`:

https://github.com/openssl/openssl/blob/894da2fb7ed5d314ee5c2fc9fd2d9b8b74111596/ms/uplink.c#L34

This is the function which produces the error message

https://github.com/openssl/openssl/blob/894da2fb7ed5d314ee5c2fc9fd2d9b8b74111596/ms/uplink.c#L79


In my case, the breakpoint was not hit, but in your case you should hit the breakpoint. Please send us the call stack and the log output until you hit the breakpoint. Maybe this will help us to find why your program behaves differently.

**Comment by kimaluco17** [comment] 2019-10-04 18:52
I recently noticed that my system path variable was pointing to Strawberry perl instead of Active State perl, could this be the cause?

I just tried to build 1.1.1d with AS perl, but it hung in one of the unit tests 70-test_comp.t (also referenced in #10066 ). 

Currently trying to build 1.1.1c now, I will give the suggestions a try if it doesn't work.

**Comment by levitte** [comment] 2019-10-05 04:09
I use strawberry perl as well. It should make no difference.

Is it possible to check that `test\drbg_cavs_test.exe` does have a symbol `OPENSSL_Applink`? Spelt like that, or similar? The thing I'm looking for is if, somehow, the symbol name got slightly modified in debug. It *shouldn't*, but since it doesn't seem to be present...

**Comment by mspncp** [comment] 2019-10-05 07:26
My drbg_cavs_test.exe doesn't have the symbol

```
C:\src\openssl-1.1.1>dumpbin /exports test\drbg_cavs_test.exe
Microsoft (R) COFF/PE Dumper Version 14.22.27905.0
Copyright (C) Microsoft Corporation.  All rights reserved.


Dump of file test\drbg_cavs_test.exe

File Type: EXECUTABLE IMAGE

  Summary

        A000 .data
      116000 .rdata
       15000 .reloc
        3000 .text
```

and the counter test shows that openssl.exe has it as expected. _(Yes, an exported symbol in a .exe file, that's possible)_.

```
C:\src\openssl-1.1.1>dumpbin /exports apps\openssl.exe
Microsoft (R) COFF/PE Dumper Version 14.22.27905.0
Copyright (C) Microsoft Corporation.  All rights reserved.


Dump of file apps\openssl.exe

File Type: EXECUTABLE IMAGE

  Section contains the following exports for openssl.exe

    00000000 characteristics
    FFFFFFFF time date stamp
        0.00 version
           1 ordinal base
           1 number of functions
           1 number of names

    ordinal hint RVA      name

          1    0 000356A0 OPENSSL_Applink = _OPENSSL_Applink

  Summary

        8000 .data
       28000 .rdata
        8000 .reloc
        1000 .rsrc
       41000 .text
```

So it seems @kimaluco17 that for some reason in your test case the  OPENSSL_Uplink() function gets called, but in my case it isn't. That's why I am so interested in your call stack.

**Comment by mspncp** [comment] 2019-10-05 07:44
Note: If I read the Makefile correctly, only two executables link to ms\applink.obj, it's apps/openssl.exe and test\uitest.exe .

**Comment by mspncp** [comment] 2019-10-05 12:48
I stumbled over an old issue which might be related.

- #2404 Wrong expectation of value of _IOB_ENTRIES with Visual Studio 2015 (formerly RT 4156)

This issue was fixed by @levitte who backported 800b299b0a53 (master, 1.1.1, 1.1.0) to 56fbd5cff879 (1.0.2). The essence of the following code snippet is to ensure that the uplink calls(*) are disabled for the standard streams stdin, stdout, and stderr.

https://github.com/openssl/openssl/blob/894da2fb7ed5d314ee5c2fc9fd2d9b8b74111596/crypto/bio/bss_file.c#L207-L225

_(*)A brief explanation about 'applink' vs. 'uplink': there are some api functions (in particular stream API calls) which need to be provided by the application, not by libcrypto itself. They are called the 'applink' callbacks. Inside libcrypto there is the corresponding code which acts as a proxy for those functions and calls 'upwards' into the application. This is the so-called 'uplink'._


@kimaluco17 can you please set a breakpoint at BIO_clear_flags and check whether the  BIO_FLAGS_UPLINK flag gets cleared for stdin and stdout? In my case it gets called, and this is the callstack:


```
>	libcrypto-1_1.dll!BIO_clear_flags(bio_st * b, int flags) Zeile 192	C
 	libcrypto-1_1.dll!file_ctrl(bio_st * b, int cmd, long num, void * ptr) Zeile 219	C
 	libcrypto-1_1.dll!BIO_ctrl(bio_st * b, int cmd, long larg, void * parg) Zeile 530	C
 	libcrypto-1_1.dll!BIO_new_fp(_iobuf * stream, int close_flag) Zeile 101	C
 	drbg_cavs_test.exe!test_open_streams() Zeile 22	C
 	drbg_cavs_test.exe!main(int argc, char * * argv) Zeile 40	C
```

If that is not the case, please debug the above code snippet (in function file_ctr()) and try to find out why it is not being called. I'm looking forward to your report ;-).

**Comment by levitte** [comment] 2019-10-07 16:08
Ah, the tests aren't built with ms\\applink.c, that does explain it.

Why we got away with that for so long, I'm currently unsure.

**Comment by kimaluco17** [comment] 2019-10-07 16:14
@mspncp The BIO_clear_flags function does not get called in my case. My _MSC_VER is 1915, the check on line 218 for `if (ptr == stdin || ptr == stdout || ptr == stderr)` returns false, and the line in 228 gets executed.

**Comment by mspncp** [comment] 2019-10-07 16:49
> Ah, the tests aren't built with ms\applink.c, that does explain it.
> 
> Why we got away with that for so long, I'm currently unsure.

No @levitte, that doesn't explain it, because in my case it works without applink.c. As I described in https://github.com/openssl/openssl/issues/10086#issuecomment-538646998, the BIO_FLAGS_UPLINK flag should get cleared for stdin, stdout and stderr, which doesn't happen in @kimaluco17's setup.

**Comment by mspncp** [comment] 2019-10-07 16:51
Please reread https://github.com/openssl/openssl/issues/2404#issuecomment-281241092 and ff.

**Comment by mspncp** [comment] 2019-10-07 16:59
> @mspncp The BIO_clear_flags function does not get called in my case. My _MSC_VER is 1915, the check on line 218 for `if (ptr == stdin || ptr == stdout || ptr == stderr)` returns false, and the line in 228 gets executed. The OPENSSL_Uplink function is then called from there.


How is it possible that this test fails? 

https://github.com/openssl/openssl/blob/894da2fb7ed5d314ee5c2fc9fd2d9b8b74111596/crypto/bio/bss_file.c#L217-L219

The FILE pointers 'stdout' and 'stderr'  should be the same as those in 'test_open_streams(), aren't they?

https://github.com/openssl/openssl/blob/894da2fb7ed5d314ee5c2fc9fd2d9b8b74111596/test/testutil/basic_output.c#L20-L23

**Comment by levitte** [comment] 2019-10-07 18:18
@mattcaswell, @mspncp, you did notice that the failure only happened when building with `--debug`, I hope?  I couldn't see in what you wrote that you had this...

I'm trying it out now, maybe I'll be more lucky...

**Comment by mspncp** [comment] 2019-10-07 18:37
> the failure only happened when building with --debug, I hope? I couldn't see in what you wrote that you had this...

He did mention —debug it at very beginning, but the configure command he posted didn’t contain it. So I‘m not sure whether I included it. Good luck with your investigations.

**Comment by mspncp** [comment] 2019-10-07 18:38
typo‘s are my smartphone‘s fault ;-)

**Comment by mspncp** [comment] 2019-10-07 18:41
Mixed crt‘s might explain the different FILE pointers.

**Comment by kimaluco17** [comment] 2019-10-07 18:43
@mspncp Sorry, I edited my first comment to include the --debug in the build configuration. I copied that line from a batch script we use to build OpenSSL, it builds both release and debug and I must've copied from the release portion rather than the debug portion. They are identical and only differ in the `--debug` flag being included.

**Comment by levitte** [comment] 2019-10-07 18:48
VC-WIN64A comes clean with `--debug`.  However, you found this with VC-WIN32, so trying that now.

**Comment by levitte** [comment] 2019-10-07 18:52
Essentially, if OpenSSL was built with UPLINK (`OPENSSL_NO_UPLINK` not defined), then the application *should* be built with `applink.c`.

That our tests have never failed because of this is either because we're extremely meticulous in how we build our apps (except, obviously, some times that we have no test for), or have been pure blind lucky (that the app and the library ran against the same CRT)

**Comment by levitte** [comment] 2019-10-07 18:53
(I've been wonder a couple of times, when I noticed we generally didn't use applinks with our test apps, but since I never ran into trouble, I didn't give it more thought...  in restrospect, I should have)

**Comment by levitte** [comment] 2019-10-07 19:10
Darn.  I couldn't reproduce.

The configs I tried are:

- `perl Configure VC-WIN64A no-am --debug`
- `perl Configure VC-WIN32 no-am --debug`

But either way, it cannot hurt to actually use applinks.c in all our test apps.  So a PR will be coming up soon.

**Comment by mspncp** [comment] 2019-10-07 19:17
> But either way, it cannot hurt to actually use applinks.c

Yes and no. In theory, the BIO_FLAGS_UPLINK should be cleared for stdin&friends. And I guess it has a good reason why they are treated specially. So I would still be interested to understand why the FILE pointers differ in the call stack, and if they do, what's the reason for it? So @kimaluco17, if you are interested to dig further, please go ahead :-).

**Comment by kimaluco17** [comment] 2019-10-07 20:08
@levitte Our application actually does not build with applink.c, is there a configuration option to disable building with UPLINK in 1.1.1d? I see the master branch has a `no-uplink` configuration, but I do not see that in 1.1.1d.

Also, I have not found OPENSSL_NO_UPLINK, but I do see a OPENSSL_USE_APPLINK; are those related?

**Comment by mspncp** [comment] 2019-10-07 23:35
> But either way, it cannot hurt to actually use applink.c in all our test apps. So a PR will be coming up soon.

I think that adding applink.c to our test apps is the wrong way to go. Even @dot-asm agreed at some time that this "DLL-exported" function table in the EXE file is a ["hellishly ugly hack"](https://github.com/openssl/openssl/issues/625#issuecomment-181356535), and @vszakats can tell a long story about it, too (*). Even I had my painful encounters with 'no applink' in my company.

(*) _See #625, which I recommend for reading. But be warned: it's a _very long_ thread. Just searching for 'applink' won't help to find the relevant parts of the discussion. You will have to open _a lot of hidden items_ before the search will find them)._


I've been following the discussions on openssl-users and GitHub closely, and @dot-asm's message has been clear all the time: developers should avoid certain 'dangerous' APIs (in particular those using FILE pointers and file descriptors) then they could dispense with adding applink.c to their application. The 'applink' hack was only meant for legacy applications.

Here some citations I found: 

> Well, the idea behind applink was to make life easier for old applications. Or in other words recommendation is to write new applications in manner that wouldn't require applink. And I think that we should insist on this and resist the suggestion. By asking why isn't applink-free operation option?

https://github.com/openssl/openssl/pull/1356#issuecomment-236368564


> With applink you can use any compiler, not even from same vendor. Once again, if you use interfaces that actually rely on applink. As correctly pointed out those accepting FILE * and Unix-like fd from application. And once again, recommendation is avoid those in new application code.
https://github.com/openssl/openssl/pull/1356#discussion_r72888747


> Basically goal/idea should be and actually is to make application developers abstain from this problematic interfaces, i.e. those that accept file pointers and descriptors. Developers should be encouraged to have libcrypto open files for them by name.

https://github.com/openssl/openssl/issues/625#issuecomment-181285542

> And as already mentioned, interfaces that rely on applink are something that should be discouraged. So that right response to "no OPENSSL_Applink" message should be "consider modifying application so that it's not required" rather than "do link applink.c". Linking should be last resort, not first.

https://github.com/openssl/openssl/issues/625#issuecomment-181356535

For that reason, we should not give up early and add applink.c, but instead try to find out why the special treatment of std{in,out,err} does not work for @kimaluco17, i.e., why the BIO_FLAGS_UPLINK flag does not get cleared. Since the library and the test application are built in one pass using the same toolchain, I see absolutely no reason why there should be a mixture of CRTs when running the test case. That's why I wouldn't expect two different instances of stdout (or stderr) which point to different locations in memory. This is the riddle we and @kimaluco17 need to solve.

**Comment by levitte** [comment] 2019-10-08 05:23
But @mspncp, your suggestion has a built in fragility that a CRT mixture may happen.

Look at what you quoted. The answer is to avoid FILE and POSIX fd in your application and rely entieely on BIO functionality for I/O. That's how you avoid having to use applink. Unfortunately, our test programs are riddled with usage that is contrary to the advices you quoted.

**Comment by kimaluco17** [comment] 2019-10-09 13:19
I am now running into a different error after making some changes. I disabled the OPENSSL_USE_APPLINK flag by editing the VC-WIN32 configuration to not include that flag, I did that by editing line 1315 of the 10-main.conf file shown below.

`    "VC-WIN32" => {
        inherit_from     => [ "VC-noCE-common", asm("x86_asm"),
                              sub { $disabled{shared} ? () : () } ],`

This got rid of the applink errors I was experiencing and the 05-test_rand.t was passing, but I had issues running my application with that build of OpenSSL. I figured it was due to the application compiling with MSVC 2013 build tools and OpenSSL being built with MSVC 2017 build tools, so I switched to building OpenSSL with MSVC 2013.

I am now getting an access violation exception when running drbg_cavs_test.exe, the call stack is shown below.

	libcrypto-1_1.dll!file_write(bio_st * b, const char * in, int inl) Line 165	C
 	libcrypto-1_1.dll!bwrite_conv(bio_st * bio, const char * data, unsigned int datal, unsigned int * written) Line 77	C
 	libcrypto-1_1.dll!bio_write_intern(bio_st * b, const void * data, unsigned int dlen, unsigned int * written) Line 343	C
 	libcrypto-1_1.dll!BIO_write(bio_st * b, const void * data, int dlen) Line 363	C
 	libcrypto-1_1.dll!BIO_vprintf(bio_st * bio, const char * format, char * args) Line 888	C
 	drbg_cavs_test.exe!test_vprintf_stdout(const char * fmt, char * ap) Line 42	C
 	drbg_cavs_test.exe!test_printf_stdout(const char * fmt, ...) Line 18	C
 	drbg_cavs_test.exe!run_tests(const char * test_prog_name) Line 185	C
 	drbg_cavs_test.exe!main(int argc, char * * argv) Line 51	C

**Comment by levitte** [comment] 2019-10-09 19:59
Ok, so `drbg_cavs_test.exe` thinks that `stdout == msvcr120.dll!0x6e35e020`...  The question is what `libcrypto-1_1.dll` thinks it is.  If they differ, you do have a problem.

In this case, listening to what @mspncp has quoted, the problem is here:

https://github.com/openssl/openssl/blob/12a765a5235f181c2f4992b615eb5f892c368e88/test/testutil/basic_output.c#L20-L32

That is code that becomes part of `drbg_cavs_test.exe`, not the libcrypto DLL, so if those two do not agree on what `stdout` and `stderr` are, this is the source of the problem...

...  or really, the source of the problem is that the BIO part of libcrypto has *no* counterpart to `stdin`, `stdout` or `stderr`...  If we had that, there would be no need for the code cited above, all that would be needed would be to use something like `bioin`, `bioout` and `bioerr`.  They should probably be coded something like this:

``` C
BIO *BIO_stdin(void);
BIO *BIO_stdout(void);
BIO *BIO_stderr(void);
#define bioin  BIO_stdin()
#define bioout BIO_stdout()
#define bioerr BIO_stderr()
```

**Comment by kimaluco17** [comment] 2019-10-09 21:20
Looking back at the call stack now, I noticed a discrepancy between `drbg_cavs_test.exe` and `libcrypto-1_1.dll` - the former is using `msvcr120.dll` and the latter is using `msvcr120d.dll`. Seems like they are not agreeing on which version of the .dll to use - is this due to some kind of incorrect configuration?

**Comment by mspncp** [comment] 2019-10-09 21:38
> the former is using `msvcr120.dll` and the latter is using `msvcr120d.dll`.

bingo! that's precisely the reason why the stdout (and stderr) pointers differ.

> is this due to some kind of incorrect configuration?

if you did a clean build then I would expect that the executable and the dll link against the same msvcr dll. If that's not the case, than this might be a problem of the build configuration.

**Comment by mspncp** [comment] 2019-10-09 21:47
> If we had that, there would be no need for the code cited above, all that would be needed would be to use something like `bioin`, `bioout` and `bioerr`.

Sounds like a good idea. It will prevent the application and the library from having different pointers (the library pointer is used always). But I think the clearing of the BIO_FLAGS_UPLINK flag will be necessary nevertheless. (Or what else did you mean with "the code cited above" which is not needed anymore?) 

The application could still wrap it's own (different) stdout pointer, but only if it provides the applink callbacks.

**Comment by mspncp** [comment] 2019-10-09 21:50
> (Or what else did you mean with "the code cited above" which is not needed anymore?)

Oh, I misunderstood you. You meant the creation of the wrappers `bio_out` and `bio_err`.

**Comment by kimaluco17** [comment] 2019-10-09 21:57
I just did a clean build, the debug version is still linking against the incorrect dll. I am building both the release and debug versions from within the same script, so I would expect the executable and dll to link against the same msvcr already?

I've also used dependency walker to confirm that libcrypto-1_1.dll is built with `msvcr120d.dll` while drbg_cavs_test.exe has `msvcr120.dll`. How else should I specify that this particular test should be built with the other dll?

**Comment by mspncp** [comment] 2019-10-09 22:01
> I've also used dependency walker to confirm that libcrypto-1_1.dll is built with `msvcr120d.dll` while drbg_cavs_test.exe has `msvcr120.dll`. How else should I specify that this particular test should be built with the other dll?

You probably can't do much about it kimaluco17. Seems to be an issue with the build configuration. I guess @levitte is already looking into it.

**Comment by kimaluco17** [comment] 2019-10-09 22:04
Ah okay, I misunderstood your previous answer. I will ignore that test for the time being then, thanks for all the help!

**Comment by levitte** [comment] 2019-10-10 03:58
Would you mind posting `configdata.pm` and `makefile`?  I would very much like to take a closer look.
(it's possible that you have to zip them to be able to post)

**Comment by kimaluco17** [comment] 2019-10-10 13:27
[configfiles.zip](https://github.com/openssl/openssl/files/3712783/configfiles.zip)

Here are the files, let me know if you need anything else.

**Comment by mattcaswell** [comment] 2021-02-23 17:28
I have been able to recreate this issue.

> I just did a clean build,

@kimaluco17 are you absolutely sure you did a *clean* build? By clean I mean either (1) you built in a new build tree that had not been used for a previous build or (2) you had run `nmake clean` between builds.

I was able to recreate this issue by configuring a non-debug build, running nmake, then immediately configuring a debug build and running nmake again. This ended up with a test executable with a different C runtime compared to the library and it failed in exactly the way described in this issue.

The answer is clearly to *always* make sure you have a clean environment between one build and the next.

**Comment by richsalz** [comment] 2021-05-04 14:35
This can be closed.

**Comment by lprimak** [comment] 2021-09-06 06:34
I am getting the same failure on a Mac (Big Sur) w/HomeBrew and OpenSSL 1.1.1l:
1.1.1k worked fine.

```
==> Upgrading 1 outdated package:
openssl 1.1.1k -> 1.1.1l
==> Downloading https://www.openssl.org/source/openssl-1.1.1l.tar.gz
Already downloaded: /Users/admin/Library/Caches/Homebrew/downloads/b6ccc5a2a602c2af3480bbcf1656bd9844595974ba60501871ac12504508e818--openssl-1.1.1l.tar.gz
==> Upgrading openssl
  1.1.1k -> 1.1.1l 

==> perl ./Configure --prefix=/usr/local/Cellar/openssl@1.1/1.1.1l --openssldir=/usr/local/etc/openssl@1.1 no-ssl3 no-ssl3-method no-zlib -I/Library/Developer/CommandLineTools/SDKs/MacOSX.
==> make
==> make install MANDIR=/usr/local/Cellar/openssl@1.1/1.1.1l/share/man MANSUFFIX=ssl
==> make test
Last 15 lines from /Users/admin/Library/Logs/Homebrew/openssl@1.1/04.make:
../test/recipes/95-test_external_boringssl.t ....... skipped: No external tests in this configuration
../test/recipes/95-test_external_krb5.t ............ skipped: No external tests in this configuration
../test/recipes/95-test_external_pyca.t ............ skipped: No external tests in this configuration
../test/recipes/99-test_ecstress.t ................. ok
../test/recipes/99-test_fuzz.t ..................... ok

Test Summary Report
-------------------
../test/recipes/05-test_rand.t                   (Wstat: 256 Tests: 2 Failed: 1)
  Failed test:  1
  Non-zero exit status: 1
Files=158, Tests=2630, 275 wallclock secs ( 3.82 usr  0.53 sys + 189.29 cusr 73.14 csys = 266.78 CPU)
Result: FAIL
make[1]: *** [_tests] Error 1
make: *** [tests] Error 2

Do not report this issue to Homebrew/brew or Homebrew/core!
```

**Comment by t8m** [comment] 2021-09-06 09:07
@lprimak I do not think this is related. Could you please open a new issue? Could you run `make test V=1 TESTS=test_rand` so we can see more details about the test_rand failure?

**Comment by lprimak** [comment] 2021-09-06 18:41
@t8m Thank you!

Issue created: #16517

**Comment by mattcaswell** [comment] 2024-02-02 14:28
Nothing further to be done. Closing.

**Closed by mattcaswell** 2024-02-02 14:28 UTC
Labels: triaged: bug, stalled: awaiting contributor response
