### ISSUE TITLE
Clobbers certificate file if certificate already exists

### ISSUE THREAD

**Issue by l0b0** [openssl/openssl#6544] opened 2018-06-20 22:13 UTC
How to reproduce:

1. Create a certificate using `openssl ca -batch -config openssl.cnf -in some.csr -out some.crt`
1. Re-run `openssl ca -batch -config openssl.cnf -in some.csr -out some.crt`

Expected behaviour: The command should either overwrite some.crt with a new valid certificate *or* fail and not modify some.crt at all.

Actual behaviour: The command prints the following message, returns a non-zero exit code and **overwrites some.crt with no content.**

```
ERROR:Serial number 1000 has already been issued,
      check the database/serial_file for corruption
The matching entry has the following details
Type          :Valid
Expires on    :190620220108Z
Serial Number :1000
File name     :unknown
Subject Name  […]
```

---

```
$ openssl version
OpenSSL 1.1.0g  2 Nov 2017
```

**Comment by paulidale** [comment] 2018-06-21 01:28
This is essentially a duplicate of #904 and has caused a lot of difficulties every time an attempt was made: see #6033 for the sordid history.  Something might happen post 1.1.1 but no promises.

**Comment by paulidale** [comment] 2018-06-21 04:41
Thanks.

**Closed** 2018-06-21 04:57 UTC
