### ISSUE TITLE
Strange behaviour of OpenSSL cms sign on large files

### ISSUE THREAD

**Issue by ealloradai** [openssl/openssl#1302] opened 2016-07-12 10:39 UTC
Hi All,
How is possible that the output of the signature a file bigger than 400MB using Openssl cms command is always 0 or some random size minor of 400MB?

Doing some debug, I discovered that the issue is in the function named 
SMIME_crlf_copy in ASN1 module which contains this simple cycle

while ((len = BIO_read(in, linebuf, MAX_SMLEN)) > 0)
          BIO_write(out, linebuf, len);

In my tests the number of reads is ok and match the file size, while the write operation are always lower. The result is a correctly signed CMS but the embedded signed content is truncated/partial.

This bug (?) happens only in Windows with Openssl from 2012 to 2016. Linux and MAC OSX are not affected.

Am I doing something wrong? What is the correct way to sign a 1GB file using CMS envelope?

**Comment by richsalz** [comment] 2016-07-12 14:22
If things do not fit into an "int" in those versions then it won't work.

**Comment by vdukhovni** [comment] 2016-07-12 14:54
Could there be some interaction here between "text mode" and "binary mode" files?
If the input is "text mode" (CRLF line endings) and the output is binary, the file
could shrink.  I don't think this is plausibly an issue with integer range, 400MB
is not large enough for that.

**Comment by ealloradai** [comment] 2016-07-12 15:52
Hi, 
i tried to sign an .iso file so the mode is binary. The problem in in the BIO copy, something get lost

**Comment by vdukhovni** [comment] 2016-07-12 17:14
That's a non sequitur.  Just because the file has "binary" content one cannot conclude that it was opened in "binary mode".  What specific cms(1) command-line did you use to create the signed file? What version of OpenSSL?

**Comment by levitte** [comment] 2016-07-12 18:03
That particular loop is only executed when the file is copied in binary mode, though...

**Comment by ealloradai** [comment] 2016-07-13 07:56
Hi,
as i said in the post, the problem is in the SMIME_crlf_copy used in the CMS routines in libcrypto. I mainly use the library but as long as the bug appeared i tried with command line tool using all version of openssl binary for windows from 2012 to 2016. Is certainly a memory management problem in BIO_* routines. I'm surprised no one has already reported it.

**Comment by richsalz** [comment] 2016-07-13 12:09
But are you copying a *binary* file?   I am confused by what you said you are doing.

**Comment by ealloradai** [comment] 2016-07-13 12:36
I apologize for my english. I'm trying to sign a large binary file (more than 400MB) using libcrypto CMS routine in Windows.

**Comment by richsalz** [comment] 2016-07-13 13:37
No problem.  Your English is better than my speaking your language!  If you are signing as binary file, do not call the CR/LF conversion.

**Comment by ealloradai** [comment] 2016-07-13 15:04
i do not call it, libcrypto calls it with binary flag so the copy is binary done by

while ((len = BIO_read(in, linebuf, MAX_SMLEN)) > 0)
BIO_write(out, linebuf, len);

But for large file this loop doesn't work in Windows

**Comment by vdukhovni** [comment] 2016-07-13 15:11
In a file with uniformly random data, the "CRLF" sequence will consitute ~1/65000 of the total file size.  With incorrect CRLF handling one would expect the file to shrink by one byte per 64k bytes of content, or 16 bytes per megabyte, with 400MB, that works out to about 6.4k.  Your ISO image is likely not uniformly random, and the reduction would be larger if it contained a lot of text files with CRLF line endings.

The loop you show is likely reading an input BIO opened in text mode, and writing an output BIO opened in binary mode.

**Comment by levitte** [comment] 2016-07-14 06:41
What we can deduce so far is the `SMIME_crlf_copy` thinks the content should be treated as binary (a few more lines surrounding that loop proves it):

``` C
    if (flags & SMIME_BINARY) {
        while ((len = BIO_read(in, linebuf, MAX_SMLEN)) > 0)
            BIO_write(out, linebuf, len);
    } else {
```

However, we have no idea how it got there, so @ealloradai, if you please, could you tell us a bit about the context?  Did you use the openssl application on the command line, or are you using your own program that's linked with libcrypto?  If the former, could you show us the *exact* command you used?

**Comment by ealloradai** [comment] 2016-07-14 09:06
Hi,
I am developing an application using libcrypto to generate digital signatures using the CMS format attached. Since I discovered this problem in Windows over files >=400MB, I switched to using the command-line tool (to see if I am misusing the library) but the output is the same.
i tried to sign centos7-64bit, ubuntu16-32bit iso usign the following command

`openssl.exe cms -sign -binary -in "ubuntu-16.04-desktop-i386 (1).iso" -inkey key.pem -signer cert.pem -out signed.p7m`

**Comment by vdukhovni** [comment] 2016-07-14 13:25
Please also report the OpenSSL version, i.e. the output of:

  openssl.exe version -a

**Comment by ealloradai** [comment] 2016-07-15 12:10
Hi,
This is the version i'm using
```
C:\OpenSSL-Win32\bin>openssl.exe version -a
OpenSSL 1.0.2h  3 May 2016
built on: reproducible build, date unspecified
VC-WIN32
options:  bn(64,32) rc4(8x,mmx) des(idx,cisc,2,long) idea(int) blowfish(idx)
compiler: cl -D_USE_32BIT_TIME_T -D_USING_V110_SDK71_ -D_WINSOCK_DEPRECATED_NO_WARNINGS  /MD /Ox /O2 /Ob2 -DOPENSSL_THREADS  -DDSO_WIN32 -D_USE_32BIT_TIME_T -D
USING_V110_SDK71_ -D_WINSOCK_DEPRECATED_NO_WARNINGS -W3 -Gs0 -GF -Gy -nologo -DOPENSSL_SYSNAME_WIN32 -DWIN32_LEAN_AND_MEAN -DL_ENDIAN -D_CRT_SECURE_NO_DEPRECAT
 -DOPENSSL_BN_ASM_PART_WORDS -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DRMD160_ASM -DAES_
SM -DVPAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM -DOPENSSL_USE_APPLINK -I. -DOPENSSL_NO_RC5 -DOPENSSL_NO_MD2 -DOPENSSL_NO_SSL2 -DOPENSSL_NO_KRB5 -DOPENSSL_NO_JPAKE -
OPENSSL_NO_WEAK_SSL_CIPHERS -DOPENSSL_NO_STATIC_ENGINE
OPENSSLDIR: "/usr/local/ssl"
```

Test #1 sign a small file using CMS in binary mode OK
`openssl cms -sign -binary -in openssl.cfg -out sss.p7m -signer pierino.crt -inkey pierino.key -nodetach -outform DER`
File in 11KB, File out 13 KB
`openssl cms -verify -binary -CAfile TEST_CA.crt -in sss.p7m -inform DER`
Verification successful

Test #2 sign a large file using CMS in binary mode nodetach outform DER KO
`openssl cms -sign -binary -in ubuntu-16.04-desktop-i386.iso -out sss.p7m -signer pierino.crt -inkey pierino.key -outform DER -nodetach`
File in 1.4GB, File out 464MB

Test #3 sign a large file using CMS in binary mode nodetach KO
`openssl cms -sign -binary -in ubuntu-16.04-desktop-i386.iso -out sss.p7m -signer pierino.crt -inkey pierino.key -nodetach`
File in 1.4GB, File out 629MB

Test #4 sign a large file using CMS in binary mode KO
`openssl cms -sign -binary -in ubuntu-16.04-desktop-i386.iso -out sss.p7m -signer pierino.crt -inkey pierino.key`
File in 1.4GB, File out 1.4GB + 3KB **<-----------SIZE IS OK** 

```
C:\OpenSSL-Win32\bin>openssl cms -verify -binary -CAfile TEST_CA.crt -in sss.p7m -inform DER
Error reading S/MIME message
2744:error:0D0680A8:asn1 encoding routines:ASN1_CHECK_TLEN:wrong tag:.\crypto\asn1\tasn_dec.c:1197:
2744:error:0D07803A:asn1 encoding routines:ASN1_ITEM_EX_D2I:nested asn1 error:.\crypto\asn1\tasn_dec.c:374:Type=CMS_ContentInfo

C:\OpenSSL-Win32\bin>openssl cms -verify -binary -CAfile TEST_CA.crt -in sss.p7m
Error reading S/MIME message
860:error:0D0D40D2:asn1 encoding routines:SMIME_read_ASN1:no multipart body failure:.\crypto\asn1\asn_mime.c:457:
```

Test #5 sign a large file using CMS in binary mode outform DER KO
`openssl cms -sign -binary -in ubuntu-16.04-desktop-i386.iso -out sss.p7m -signer pierino.crt -inkey pierino.key -outform DER`
File in 1.4GB, File out 2KB

**Comment by vdukhovni** [comment] 2016-07-17 12:45
OK, the issue is no CRLF -> LF conversion...

**Comment by vdukhovni** [comment] 2016-07-17 12:46
Perhaps the buffer for CMS encryption is not large enough for objects of this size.  Can your Windows OS allocate memory blocks larger than 1GB?

**Comment by ealloradai** [comment] 2016-07-18 05:55
Yes but as you can see, test 4 is successful in generating the right outputsize, so the bug is in the code.

**Comment by levitte** [comment] 2016-07-19 06:04
@ealloradai, what happens if you add the command option `-stream`?

Note from the manual:

```
       -stream -indef -noindef
           the -stream and -indef options are equivalent and enable streaming
           I/O for encoding operations. This permits single pass processing of
           data without the need to hold the entire contents in memory,
           potentially supporting very large files. Streaming is automatically
           set for S/MIME signing with detached data if the output format is
           SMIME it is currently off by default for all other operations.

```

**Comment by ealloradai** [comment] 2016-07-19 08:11
Hi,
So i tried 
```
C:\OpenSSL-Win32\bin>openssl cms -sign -binary -in ubuntu-16.04-desktop-i386.iso -out sss.p7m -signer pierino.crt -inkey pierino.key -stream -outform DER -nodetach
```
File in 1.468.800 KB, File out 1.470.237 KB <- **Size ok**

But i can't verify the signature...
```
C:\OpenSSL-Win32\bin>openssl cms -verify -binary -CAfile TEST_CA.crt -in sss.p7m -inform DER
Error reading S/MIME message
3872:error:07069041:memory buffer routines:BUF_MEM_grow_clean:malloc failure:.\crypto\buffer\buffer.c:159:
3872:error:0D06B041:asn1 encoding routines:ASN1_D2I_READ_BIO:malloc failure:.\crypto\asn1\a_d2i_fp.c:239:
```

```
C:\OpenSSL-Win32\bin>openssl cms -verify -binary -CAfile TEST_CA.crt -in sss.p7m -inform DER -stream
Error reading S/MIME message
2856:error:07069041:memory buffer routines:BUF_MEM_grow_clean:malloc failure:.\crypto\buffer\buffer.c:159:
2856:error:0D06B041:asn1 encoding routines:ASN1_D2I_READ_BIO:malloc failure:.\crypto\asn1\a_d2i_fp.c:239:
```

```
C:\OpenSSL-Win32\bin>openssl cms -verify -binary -CAfile TEST_CA.crt -in sss.p7m
Error reading S/MIME message
3968:error:0D0D40D1:asn1 encoding routines:SMIME_read_ASN1:no content type:.\crypto\asn1\asn_mime.c:440:

```
```
C:\OpenSSL-Win32\bin>openssl cms -verify -CAfile TEST_CA.crt -in sss.p7m
Error reading S/MIME message
2684:error:0D0D40D1:asn1 encoding routines:SMIME_read_ASN1:no content type:.\crypto\asn1\asn_mime.c:440:

```

**Comment by levitte** [comment] 2016-07-19 09:18
Yup, you have a memory problem there.  The first operation is the one you should use in this case (`-stream` is only supported when encoding).

So essentially, this comes down to adding support for streaming when verifying.

**Comment by levitte** [comment] 2016-07-19 09:19
(@mattcaswell, @richsalz, please feel welcome to help determine if this is to be regarded a feature request or a bugfix request)

**Comment by richsalz** [comment] 2016-07-19 09:21
A bugfix but not a stop-ship for 1.1 in my view.

**Comment by ealloradai** [comment] 2016-07-19 13:19
Hi,
can someone explain me how does the signature work using  CMS_STREAM? 
As i can see in openssl/cms.c, usign streams, the cms is build with 
`cms = CMS_sign(NULL, NULL, other, in, flags);`
which actually does't sign the data but is able to calculate the message digest right?

As long as CMS_STREAM is set, this is neve called

`if ((operation == SMIME_SIGN) && !(flags & CMS_STREAM)) {
            if (!CMS_final(cms, in, NULL, flags))`

So where the real signature happen? here?
` else if (outformat == FORMAT_ASN1)
            ret = i2d_CMS_bio_stream(out, cms, in, flags);`

How?

**Comment by mattcaswell** [comment] 2016-08-26 13:00
Ok, 1.1.0 out of the way....@levitte - how do we take this forward?

**Comment by kaduk** [comment] 2018-01-10 23:09
Let's put this bugfix on the 1.1.1 list for now.
Also added the 1.0.2 and 1.1.0 labels, since the bug is believed present there.

**Comment by mattcaswell** [comment] 2018-04-06 09:40
@levitte - you self assigned this. How do we take this forward? Should we change the milestone again?

**Comment by levitte** [comment] 2018-04-25 12:46
This close to the release target date, we unfortunately need to change the milestone again, yes.

**Comment by iOSleep** [comment] 2019-06-11 10:51
encrypt operating we can use `-steam` to  get a smime file

but for decrypt, `PEM_read_bio_CMS` and `SMIME_write_CMS` both load all content to RAM.

I use these functions in iPhone, so how should i reduce the raw peak when decrypt a file 🤣 except compression the file into small parts before encrypt

**Comment by DDvO** [comment] 2020-10-12 05:47
Shame that this issue has been neglected that long although at least a partial solution seems to have been identified.
Looks like it still has not been implemented and not even an `KNOWN BUGS` notice has been put in the CMS documentation.
So users keep falling in this trap, needless losing much time trying to re-analyze what the reason is for verification failing.
Likely #12959 will finally provide a solution.

**Comment by jamuir** [comment] 2023-11-08 03:19
@DDvO, your PR was merged to "master" (in May 2021).  What work is left to do here?  Can this issue be closed?

**Comment by DDvO** [comment] 2023-11-08 22:01
Thanks for asking. 
Unfortunately after that long time I cannot recall the details of my PR and of its relation with this issue.

I suggest better asking @ealloradai, the author of this issue, if he sees it fixed meanwhile.
Or just close due to the long period of inactivity, maybe after some grace period.

**Comment by nhorman** [comment] 2024-01-13 15:02
Given that its been 2 months without a response, and the age of this issue, I'm going to close this.  Please re-open if anyone has the cycles to pick this up again

**Closed by nhorman** 2024-01-13 15:02 UTC
Labels: branch: master, branch: 1.1.1, triaged: bug

**Comment by socketpair** [comment] 2024-12-27 07:15
```
$ openssl cms -decrypt -in qqqqq -inform DER  -recip ec_cert.pem -binary  -inkey ec_private_key.pem -out zzzzz -stream -x509_strict
Error reading SMIME Content Info
80022D1E207F0000:error:03880106:memory buffer routines:BUF_MEM_grow_clean:passed invalid argument:crypto/buffer/buffer.c:125:
80022D1E207F0000:error:06880007:asn1 encoding routines:asn1_d2i_read_bio:BUF lib:crypto/asn1/a_d2i_fp.c:209:
```

file size is about 4GB

encrypt is OK. Impossible to decrypt.
