### ISSUE TITLE
GET request issue in s_client

### ISSUE THREAD

**Issue by muschem** [openssl/openssl#2058] opened 2016-12-09 16:32 UTC
It appears that when s_client attempts a GET request to s_server using any request header information beyond the initial request line (where Request-Line = Method SP Request-URI SP HTTP-Version CRLF), the response and any application data packets from s_server cannot be decrypted using typical method of key import in Wireshark. Using the same connection methods (cipher suite, OpenSSL flags, version, etc.), but passing only the initial GET request line without any further header information, results in a successful packet decryption. Tested using version 1.1.0c of OpenSSL. Using the same s_server settings, but connecting with a different client-side application (such as cURL) also results in successful packet decryption with a full-request including header information. So, the issue seems to be limited to s_client.

**Comment by richsalz** [comment] 2016-12-12 21:04
how did you test this.

**Comment by muschem** [comment] 2016-12-12 23:42
Server and client are both hardware (as opposed to virtual devices) on the same subnet, using RFC1918 addresses.

Server device starts the OpenSSL s_server process with minimal options:
openssl s_server -cipher <multiple suites tested here> -cert <cert signed by local CA> -key <path to key> -accept <port> -HTTP (-WWW also tested)

tcpdump started on client:
tcpdump -i <interface> -vvv port <filter on port that s_server is accepting> -s 65535 -w <name of output file.pcap>

Client device connects with s_client:
openssl s_client -cipher <same cipher as s_server specifies> -connect <ip:port of s_server>

This results in a successful connection opened. Now, client attempts GET request for a file residing on the server:
GET </path to file, which is a subdirectory of the path where s_server was initialized> HTTP/1.0

Now, if that is the only information passed from s_client, I can decrypt the pcap file that was captured via tcpdump on the client during this process - I import the key used by s_server into my Wireshark preferences, and follow the SSL stream with no issues. 

However, if in addition to that GET request line I add header information, such as "agent: <something here>" and/or "accept: */*", etc. - the file I request still transfers ok to the client, but the pcap file shows a blank SSL stream. I have tried issuing the header information on the same line as well as on successive lines separated by CRLF (via copy/paste) - both methods suffer the same end-result.

Please advise if additional information or testing is required. Thank you for looking into this.

**Comment by richsalz** [comment] 2016-12-13 00:05
I can't reproduce this.  Perhaps a tcpdump issue?  Does the size of the capture file look right?

**Comment by muschem** [comment] 2016-12-13 00:09
Hmm. Capture size looks correct - same number of packets and relative size whether I include GET request headers or not. I can follow the TCP stream on both captures, and the non-encrypted information looks correct - I just cannot decrypt the application data when the request headers are included. I will try a few more test cases to see if I can narrow it down further. Thanks.

**Comment by mattcaswell** [comment] 2017-05-02 13:42
No further progress. Closing.

**Closed by mattcaswell** 2017-05-02 13:42 UTC
