### ISSUE TITLE
OpenSSL 1.1.1 win32 VC 9.0 build fails [fix included]

### ISSUE THREAD

**Issue by mike805** [openssl/openssl#7211] opened 2018-09-13 07:13 UTC
OpenSSL 1.1.1 win32 VC 9.0 for Python
Build fails on crypto\sm2\sm2_sign.c
Missing definition of UINT16_MAX
This can be fixed by adding: #include "internal/numbers.h"

#include "internal/sm2.h"
#include "internal/sm2err.h"
#include "internal/ec_int.h" /* ec_group_do_inverse_ord() */
#include "internal/numbers.h" /* ADD THIS ONE TO FIX - MIKE */
#include <openssl/err.h>
#include <openssl/evp.h>
#include <openssl/err.h>
#include <openssl/bn.h>
#include <string.h>

**Comment by mattcaswell** [comment] 2018-09-13 07:30
Dupe of #7186. Closing.

**Closed by mattcaswell** 2018-09-13 07:30 UTC
