### ISSUE TITLE
OpenSSL doesn't properly encode NewSessionTicket when using SSL_CTX_set_tlsext_ticket_key_cb callback that returns 0

### ISSUE THREAD

**Issue by sotodel** [openssl/openssl#18977] opened 2022-08-10 15:11 UTC
I'm working with OpenSSL 1.1.1q.

We have our own build of OpenSSL.

We have custom session ticket handling logic that's configured through [`SSL_CTX_set_tlsext_ticket_key_cb`](https://www.openssl.org/docs/man1.1.1/man3/SSL_CTX_set_tlsext_ticket_key_cb.html). On the server, this callback logic can sometimes return 0 which

> indicates that it was not possible to set/retrieve a session ticket and the SSL/TLS session will continue by negotiating a set of cryptographic parameters or using the alternate SSL/TLS resumption mechanism, session ids.

We recently enabled TLS 1.3 on this service. Clients, also on TLS 1.3, started seeing new session ticket processing errors like

> error:1416E09F:SSL routines:tls_process_new_session_ticket:length mismatch

This only occurs when the callback from `SSL_CTX_set_tlsext_ticket_key_cb` returns 0.

Here's a server repro (that I've adapted from https://wiki.openssl.org/index.php/Simple_TLS_Server). You'll need to plug in your own cert/key paths.

```
#include <arpa/inet.h>
#include <openssl/err.h>
#include <openssl/ssl.h>
#include <stdio.h>
#include <string.h>
#include <sys/socket.h>
#include <unistd.h>

int create_socket(int port) {
  int s;
  struct sockaddr_in6 addr;
  addr.sin6_family = AF_INET6;
  addr.sin6_port = htons(port);
  addr.sin6_addr = in6addr_any;
  s = socket(AF_INET6, SOCK_STREAM, 0);
  if (s < 0) {
    perror("Unable to create socket");
    exit(EXIT_FAILURE);
  }
  if (bind(s, (struct sockaddr*)&addr, sizeof(addr)) < 0) {
    perror("Unable to bind");
    exit(EXIT_FAILURE);
  }
  if (listen(s, 1) < 0) {
    perror("Unable to listen");
    exit(EXIT_FAILURE);
  }
  return s;
}

SSL_CTX* create_context() {
  const SSL_METHOD* method;
  SSL_CTX* ctx;
  method = TLS_server_method();
  ctx = SSL_CTX_new(method);
  if (!ctx) {
    perror("Unable to create SSL context");
    ERR_print_errors_fp(stderr);
    exit(EXIT_FAILURE);
  }
  return ctx;
}

int handle_session_ticket(
    SSL* s,
    unsigned char key_name[16],
    unsigned char iv[EVP_MAX_IV_LENGTH],
    EVP_CIPHER_CTX* ctx,
    HMAC_CTX* hctx,
    int enc /* when set to 1 */) {
  return 0;
}

void configure_context(SSL_CTX* ctx) {
  if (SSL_CTX_use_certificate_file(ctx, "cert.pem", SSL_FILETYPE_PEM) <= 0) {
    ERR_print_errors_fp(stderr);
    exit(EXIT_FAILURE);
  }
  if (SSL_CTX_use_PrivateKey_file(ctx, "key.pem", SSL_FILETYPE_PEM) <= 0) {
    ERR_print_errors_fp(stderr);
    exit(EXIT_FAILURE);
  }
  SSL_CTX_set_session_cache_mode(
      ctx,
      SSL_SESS_CACHE_SERVER | SSL_SESS_CACHE_NO_INTERNAL |
          SSL_SESS_CACHE_NO_AUTO_CLEAR);
  SSL_CTX_set_tlsext_ticket_key_cb(ctx, handle_session_ticket);
}

int main(int argc, char** argv) {
  int sock;
  SSL_CTX* ctx;
  ctx = create_context();
  configure_context(ctx);
  sock = create_socket(4433);
  while (1) {
    struct sockaddr_in addr;
    unsigned int len = sizeof(addr);
    SSL* ssl;
    const char reply[] = "test\n";
    int client = accept(sock, (struct sockaddr*)&addr, &len);
    if (client < 0) {
      perror("Unable to accept");
      exit(EXIT_FAILURE);
    }
    ssl = SSL_new(ctx);
    SSL_set_fd(ssl, client);

    if (SSL_accept(ssl) <= 0) {
      ERR_print_errors_fp(stderr);
    } else {
      SSL_write(ssl, reply, strlen(reply));
    }

    SSL_shutdown(ssl);
    SSL_free(ssl);
    close(client);
  }

  close(sock);
  SSL_CTX_free(ctx);
}
```
Once this is running, we can use `openssl s_client` to repro the client side:

```
> openssl version
OpenSSL 1.1.1k  FIPS 25 Mar 2021
> openssl s_client -connect [::1]:4433 -msg
[...]
New, TLSv1.3, Cipher is TLS_AES_256_GCM_SHA384
[...]
Verify return code: 0 (ok)
---
<<< ??? [length 0005]
    17 03 03 00 1d
<<< TLS 1.3 [length 0001]
    16
<<< TLS 1.3, Handshake [length 000c], NewSessionTicket
    04 00 00 08 00 00 00 00 00 00 00 00
>>> ??? [length 0005]
    17 03 03 00 13
>>> TLS 1.3 [length 0001]
    15
>>> TLS 1.3, Alert [length 0002], fatal decode_error
    02 32
139758528358208:error:1416E09F:SSL routines:tls_process_new_session_ticket:length mismatch:ssl/statem/statem_clnt.c:2592:
```
If my understanding is correct, in the messages above, the `16` indicates the `handshake` `ContentType`, `4` indicates the `new_session_ticket` `HandshakeType`, the `00 00 08` are the `Handshake` message's `length`. 

The following bytes are the `NewSessionTicket` message. The first 6 bytes might be the encoding from the [`statem_srvr.c`](https://github.com/openssl/openssl/blob/83ab43da0c9f67c5069605552b1332ca5fadecf1/ssl/statem/statem_srvr.c#L3788-L3805) (which also doesn't seem to match the `uint32 ticket_lifetime;` and `uint32 ticket_age_add;` definitions). I don't know what the final two are, maybe extensions?  In any case, I think the client is expecting bytes for the `ticket_nonce` and/or `ticket` fields and that's why it fails while decoding.

**Comment by mattcaswell** [comment] 2022-08-10 16:13
Thanks for the reproducer. I can replicate this in master too.

**Comment by mattcaswell** [comment] 2022-08-10 16:38
The problem is that we are issuing a TLSv1.2 format ticket in this case.

In TLSv1.2 if the callback returns 0, then we just issue a 0 length ticket. However, a further problem is that TLSv1.3 does not allow 0 length tickets (must be at least 1 byte), so its actually unclear what the correct behaviour should be in this case.

**Comment by sotodel** [comment] 2022-08-10 20:25
We use `SSL_CONNECTION_IS_TLS13` elsewhere. Can we check for that and append 4 bytes for ticket_lifetime, 4 bytes for ticket_age_add, no bytes for `ticket_nonce`, which I believe you omit if it's empty, and 1 byte for the length of the `ticket`, with value 0.?

**Comment by mattcaswell** [comment] 2022-08-11 08:08
It's actually quite unclear what a zero length ticket even means in TLSv1.2. But at least it is syntactically allowed.

For TLSv1.3 sending a 1 byte ticket would be possible - but this would make it indistinguishable from a real ticket to the client - so the client would be behaving reasonably if it cached that ticket and then attempted to use it (possibly repeatedly) for resumption attempts. This is probably not the behaviour we want.

RFC 8446 (TLSv1.3) does say this about the `ticket_lifetime` field:

>    ticket_lifetime:  Indicates the lifetime in seconds as a 32-bit
      unsigned integer in network byte order from the time of ticket
      issuance.  Servers MUST NOT use any value greater than
      604800 seconds (7 days).  The value of zero indicates that the
      ticket should be discarded immediately.  Clients MUST NOT cache
      tickets for longer than 7 days, regardless of the ticket_lifetime,
      and MAY delete tickets earlier based on local policy.  A server
      MAY treat a ticket as valid for a shorter period of time than what
      is stated in the ticket_lifetime.

So, potentially, we could send a 1 byte ticket with a ticket_lifetime of 0 indicating that the ticket should be discarded immediately.  This is only a "should" though, so some clients could potentially cache it anyway.

**Comment by sotodel** [comment] 2022-08-11 14:04
Can we also not send a `NewSessionTicket` message if the callback failed to produce the required material?

**Comment by mattcaswell** [comment] 2022-08-11 14:20
> Can we also not send a NewSessionTicket message if the callback failed to produce the required material?

At the point the callback is called we have already decided to send a NewSessionsTicket and have already constructed the message header (higher up in the callstack). The OpenSSL state machine doesn't currently have a mechanism for aborting the construction of the current message, rolling back and deciding not to send it after all. You can only abort the whole handshake or succeed. So that route seems quite hard (although possible).

**Comment by mattcaswell** [comment] 2022-08-12 12:50
I have a fix for master in #18990. It's a bit too invasive for backport to 3.0/1.1.1 but I think I can create a less invasive version that is more suitable there - but I'll wait for review of #18990 first.

**Comment by kaduk** [comment] 2022-08-12 21:36
> It's actually quite unclear what a zero length ticket even means in TLSv1.2. But at least it is syntactically allowed.

I think it's pretty clear, actually:

```quote
3.3.  NewSessionTicket Handshake Message

   [...]  If the server determines that it does not want to include a
   ticket after it has included the SessionTicket extension in the
   ServerHello, then it sends a zero-length ticket in the
   NewSessionTicket handshake message.
```

**Comment by kaduk** [comment] 2022-08-12 21:40
> For TLSv1.3 sending a 1 byte ticket would be possible - but this would make it indistinguishable from a real ticket to the client - so the client would be behaving reasonably if it cached that ticket and then attempted to use it (possibly repeatedly) for resumption attempts. This is probably not the behaviour we want.

We would of course reject such a 1-byte ticket when it came back to us, falling back to a full handshake.
Which is ... maybe not so bad, given how invasive #18990 is.

**Comment by mattcaswell** [comment] 2022-08-15 08:48
> I think it's pretty clear, actually:

Great - thanks. Somehow I couldn't find that reference.

**Comment by mattcaswell** [comment] 2022-08-15 08:50
> maybe not so bad, given how invasive https://github.com/openssl/openssl/pull/18990 is.

I'm fairly sure I can create a version of #18990 that is a lot less invasive (basically don't introduce the enum but keep it as a normal int). That seems like it might make it more suitable for a backport, i.e. do #18990 as-is for master, but a less invasive version for 3.0/1.1.1

**Comment by mattcaswell** [comment] 2022-08-15 08:51
> We would of course reject such a 1-byte ticket when it came back to us, falling back to a full handshake.
Which is ... maybe not so bad, given how invasive https://github.com/openssl/openssl/pull/18990 is.

:vomiting_face:

**Comment by mattcaswell** [comment] 2022-09-20 11:32
Reopening this. It was auto-closed due to the merge of #18990. However that PR only addresses master and we still need a backport to 3.0.

**Comment by mattcaswell** [comment] 2022-09-27 13:07
The fix was backported to 3.0 by #19249 which has now been merged. Closing this.

**Closed by mattcaswell** 2022-09-27 13:07 UTC
Labels: branch: master, branch: 1.1.1, triaged: bug, branch: 3.0

**Comment by sotodel** [comment] 2022-09-27 14:51
> The fix was backported to 3.0 by #19249 which has now been merged. Closing this.

Am I out of luck if I'm working with 1.1.1?

**Comment by mattcaswell** [comment] 2022-09-27 14:53
Unfortunately 1.1.1 is in security-fix only mode so the fix won't be backported there.

**Comment by sotodel** [comment] 2022-10-12 12:04
Cool, extra motivation to move on to newer versions. Thanks for the fix!
