### ISSUE TITLE
Upgrade openssl from 1.0.1m to 1.1.0d, client can't visit the same web site by https

### ISSUE THREAD

**Issue by forston** [openssl/openssl#4521] opened 2017-10-12 05:28 UTC
Hi 
  Recently, my project upgrade openssl from 1.0.1m to 1.1.0d. After upgrade, we can't visit the same web site by https in my project.
  I try to use openssl.exe cmd to visit the web site, it still failed, but use 1.0.1m verison it's ok.
  i provide wireshark log\web site configuration\openssl communication msg to you, please help me resolve the problem.
  Web site was build in IIS7 and accept client certificates. If ignore client certificates, the website can visit.
  The more information see in attach files.
Best regards.
Forston
[openssl.zip](https://github.com/openssl/openssl/files/1378150/openssl.zip)

**Comment by dyduyu** [comment] 2017-10-12 07:16
_Add a message, may be it's useful._
The connection failed in renegotiate, and the `AES128-SHA` cipher was chosen, the IIS log showed 500.0.64. 
The problem is, it was succeed when I tried to take a specific cipher `ECDHE-RSA-AES256-SHA` by using openssl 1.1.  Seems the server chose the weak one in default.
I know we can take a workaround by re-configuring the server to choose a stronger cipher in default, however, we still want to know why this happen, is this a bug? Because openssl 1.0 works fine with using `AES128-SHA` .

Thanks!
Best Regards

**Comment by richsalz** [comment] 2017-10-12 18:59
Look at the SECURITY_LEVEL in the ciphers page.  That might help.

**Comment by dyduyu** [comment] 2017-10-25 07:12
Seems it was a bug of IIS 7.5...
Here are some findings I investigated:
1. IIS 8 and higher version are able to handle properly using openssl 1.1;
2. Apache server can also handle it well;
3. The 500 error means it is failed in IIS. Btw, another evidence is, if I change `s->client_version` from 769(0x301) to 771(0x303) in renegotiate session(after `ssl_set_client_hello_version(s)` is called in `statem_clnt.c`), IIS 7.5 is able to work properly.

**Comment by mattcaswell** [comment] 2017-10-25 08:34
Ok, closing as this is assumed to be an IIS bug.

**Closed by mattcaswell** 2017-10-25 08:34 UTC

**Comment by davidben** [comment] 2017-10-25 12:46
This sounds like #1651. While an IIS bug, it's a workaround that every stack I know of, including OpenSSL before 1.1.0, would do.
