### ISSUE TITLE
Support for DTLS 1.3

### ISSUE THREAD

**Issue by pgriess** [openssl/openssl#4804] opened 2017-11-27 18:39 UTC
What are the plans / timeline for supporting DTLS 1.3?

I haven't found anything mentioned on the website, or in recent changes to indicate that this is in-progress. The current draft is https://tools.ietf.org/html/draft-ietf-tls-dtls13-02, but I'm sure you knew that.

**Comment by richsalz** [comment] 2017-11-27 18:46
It will be supported.  It is still very early in the revision of the protocol -- most of the working group attention has been on TLS 1.3 -- and no code has been written yet.

**Comment by richsalz** [comment] 2017-11-27 19:57
It's impossible to predict how long it will take the IETF to finish nor what roadblocks might come up at the last minute, like happened with TLS 1.3

**Comment by t8m** [comment] 2023-08-21 19:49
Duplicate of #13900

**Closed by t8m** 2023-08-21 19:49 UTC
Labels: triaged: feature
