### ISSUE TITLE
QUESTION: Is OAEP padding with hashes other than SHA1 supported or not?

### ISSUE THREAD

**Issue by levicki** [openssl/openssl#10171] opened 2019-10-14 10:45 UTC
I compiled OpenSSL for Windows from 1.1.1d commit, and when I use the following command line:
```
openssl rsautl -in data.enc -out data.dec -inkey key.pem -decrypt -oaep
```
RSA decryption is failing with the following message if `data.enc` is generated using any OAEP padding hash algorithm larger than SHA1:
```
RSA operation error
9828:error:04099079:rsa routines:RSA_padding_check_PKCS1_OAEP_mgf1:oaep decoding error:..\OpenSSL-source\crypto\rsa\rsa_oaep.c:263:
9828:error:04065072:rsa routines:rsa_ossl_private_decrypt:padding check failed:..\OpenSSL-source\crypto\rsa\rsa_ossl.c:491:
```
I am generating data.enc using Microsoft CNG provider which supports OAEP with larger hashes than SHA1 (I tried using SHA256 and SHA512). Note that if I use SHA1 OAEP padding when generating `data.enc`, the OpenSSL RSA decryption is working fine.

It would be nice to know if this is supported or not and whether there is any special build configuration needed to enable it.

**Comment by mattcaswell** [comment] 2019-10-14 10:53
libcrypto supports it, but the command line tool `rsautl` does not.

**Comment by levicki** [comment] 2019-10-14 11:00
Thanks for the quick clarification, is that due to a bug in the `rsautl`, or it simply needs to be added (i.e. should this be a feature request then)?

**Comment by mattcaswell** [comment] 2019-10-14 11:03
It's not a bug - it just doesn't implement it. So I guess its a feature request. Pull Requests welcome! :-)

**Comment by mattcaswell** [comment] 2019-10-14 11:07
Hmmm...you might be able to do this with pkeyutl instead...

**Comment by levicki** [comment] 2019-10-14 11:13
@mattcaswell I don't see how I could use `pkeyutl`, it has no `-oaep` switch?

Should I close this issue and create a feature request, or could you please rename it and put the proper tag?

**Comment by mattcaswell** [comment] 2019-10-14 11:18
Try this:

````
openssl pkeyutl -inkey key.pem -in data.enc -pkeyopt rsa_padding_mode:oaep -pkeyopt rsa_oaep_md:sha256 -decrypt -out data.dec
````

**Comment by levicki** [comment] 2019-10-14 11:22
@mattcaswell Thanks, that works.

**Comment by mattcaswell** [comment] 2019-10-14 11:22
The pkeyopt `rsa_oaep_md` is apparently undocumented on the `pkeyutl` page, although `rsa_padding_mode:oaep` is there. So, a new issue pointing out that missing option would be helpful (and a pull request fixing it would be even better!)

**Comment by levicki** [comment] 2019-10-14 11:25
Frankly I wasn't even aware of any of those options. I just needed to verify interoperability with Microsoft CNG (and in some way that I am not doing something wrong/unsupported).

Do you believe that `rsautl` should support that as well?

**Comment by mattcaswell** [comment] 2019-10-14 11:28
`rsautl` is legacy really. Probably the `rsautl` man page should point you towards `pkeyutl` instead.

**Comment by levicki** [comment] 2019-10-14 11:29
Do we need a bug report for that too or we can modify this one somehow?

**Comment by mattcaswell** [comment] 2019-10-14 11:31
Perhaps just include it in the description of #10174.

**Comment by levicki** [comment] 2019-10-14 11:36
Done.

**Comment by levitte** [comment] 2019-10-14 13:53
There's a slew of old commands that we should deprecated. On proposing that quite some time ago, I got quite a bit of pushback. Maybe now's the time...

**Comment by mattcaswell** [comment] 2019-12-05 15:15
Question seems to have been answered. Another related issue has been raised #10174. Closing this one.

**Closed by mattcaswell** 2019-12-05 15:15 UTC
Labels: resolved: answered
