### ISSUE TITLE
Persistent & random crypto failures on ARM64 Ubuntu 16.04

### ISSUE THREAD

**Issue by rvagg** [openssl/openssl#5526] opened 2018-03-06 03:06 UTC
We have a strange problem over at Node.js with our test infrastructure. I'm not sure exactly where the best place to go with this is so I'm going to try here first and perhaps you have an idea of where we might look next.

As part of our test infrastructure we use Cavium ThunderX (as available from packet.net) machines to help test our ARM64 support. We get occasional failures in crypto operations (either some direct crypto work or via tls) with errors that we don't see anywhere else but on these machines. These are the kinds of output we see along with failures, keeping in mind that we're working against a statically linked 1.0.2n out of our source tree:

```
    Error: 281472750350336:error:1408F119:SSL routines:SSL3_GET_RECORD:decryption failed or bad record mac:../deps/openssl/openssl/ssl/s3_pkt.c:535:
```

```
    Error: 281473003442176:error:140940F6:SSL routines:ssl3_read_bytes:unknown alert type:../deps/openssl/openssl/ssl/s3_pkt.c:1508:
```

```
    Error: write EPROTO 281473430319104:error:1409441B:SSL routines:ssl3_read_bytes:tlsv1 alert decrypt error:../deps/openssl/openssl/ssl/s3_pkt.c:1500:SSL alert number 51
    281473430319104:error:1409E0E5:SSL routines:ssl3_write_bytes:ssl handshake failure:../deps/openssl/openssl/ssl/s3_pkt.c:659:
```

And some higher-level failures that suggest deeper problems:

when trying to do a pbkdf2 test:

```
    AssertionError [ERR_ASSERTION]: '�æ�_]\u0013G\u000e;F§�Ù\u0013e+¸\u000fc�' strictEqual 'ÅäxÕ��ÈAªS\r¶�\\L��(� '
```

And an apparent failure when testing for memory leakage after performing a simple DH keypair creation, it's hard to be sure but the failure case does suggest there was an unexpected increase in retained memory somewhere in stack after cleanup.

The first error seems to show up most often.

There's a number of reasons why this is weird:

* As far as I can tell these are relatively new, perhaps since we started testing on this particular hardware
* The errors don't happen with the same frequency on different machines with the same configuration--we have two Ubuntu 16.04 machines in the mix here and one of them seems to throw these up much more often than the other, but they still happen on both so I don't think it's as likely to just be one dodgy machine.
* We have CentOS 7 running on two more of these machines and I can't find a record of the errors there at all.

Perhaps most disturbingly, this isn't limited to our direct OpenSSL usage. We first recognised this with repeated SSL errors thrown up by Jenkins while trying to maintain a connection on one of these machines. We saw a whole lot of this kind of thing:

```
javax.crypto.BadPaddingException: bad record MAC
	at sun.security.ssl.EngineInputRecord.decrypt(EngineInputRecord.java:238)
	at sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:974)
Caused: javax.net.ssl.SSLException: bad record MAC
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1728)
	at sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:981)
	at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:907)
	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:781)
	at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624)
```

Which has nothing to do with Node.js, this is communication between a Java (8 iirc) JNLP client and an nginx reverse proxy to the Jenkins server. But it appears to be a similar error to our most common failure. As far as I know the Java crypto stack doesn't touch OpenSSL does it?

/cc @vielmetti

**Comment by rvagg** [comment] 2018-03-06 03:10
Sorry, original issue where we've collected some of these reports is https://github.com/nodejs/build/issues/842

**Comment by mattcaswell** [comment] 2018-03-06 09:54
Hmmm, strange. "Bad record MAC" is a very generic "something bad happened" kind of error and can be caused by all sorts of underlying problems. Is it possible that the OpenSSL and Java errors are entirely co-incidental and have different causes?

If you can get to a point of being able to reliably reproduce the OpenSSL failures then we might stand some chance of trying to figure out where the issue is.

**Comment by dot-asm** [comment] 2018-03-06 11:55
I'd suggest to first try to start server [one that uses OpenSSL] with OPENSSL_armcap environment variable set to 0. This will suppress all NEON code paths (including hardware-accelerated crypto). If it helps, then, given the circumstances, it's not impossible to imagine that kernel doesn't handle NEON registers context switches right. I mean since there is no reason to believe that it's broken processor or inadequate power (since it apparently works on CentOS) and it's same user-land code (I assume it is), kernel is the only variable. [Well, libc is another, but since computer generally works, it's unlikely to be the culprit]. Thing about NEON is that it's customarily kind of lazy context switch. When NEON code is preempted by non-NEON and resumed, it's possible to avoid registers reload. And if you get the alternative case, i.e. when NEON code is preempted by another NEON code, wrong [say a kernel patch was mis-applied] then you'd be in trouble. And it's likely to manifest as sporadic failures [under load].

If running with OPENSSL_armcap set to 0 make difference, then one can wonder that's with Java then. Well, compiler and JVM are not prohibited to use NEON registers, so basically any code can suffer. This does mean that setting OPENSSL_armcap to 0 is not actually a solution, but only a way to detect specific problem. It's just that without OPENSSL_armcap set NEON will be used much more frequently, and you are simply more likely to hit the problem.

**Comment by vielmetti** [comment] 2018-03-06 15:33
Thanks for the heads up, I'll alert some more members of the Packet team to this issue.

**Comment by vielmetti** [comment] 2018-04-17 16:40
It's been about six weeks - any updates on frequency of errors, or any other changes?

**Comment by mattcaswell** [comment] 2018-04-30 09:35
@rvagg any update on this issue? Without further information I'm thinking we should close this until we know more.

**Comment by richsalz** [comment] 2018-05-06 20:50
Please re-open this issue if/when you get more information.

**Closed by richsalz** 2018-05-06 20:50 UTC
