### ISSUE TITLE
BLAKE3 integration?

### ISSUE THREAD

**Issue by veorq** [openssl/openssl#25784] opened 2024-10-23 20:45 UTC
Hi OpenSSL maintainers, I'm writing on behalf of the [BLAKE3](https://github.com/BLAKE3-team/BLAKE3) team (@oconnor663 @sneves @zooko).

BLAKE3 is the fastest cryptographic hash, it's also a key derivation function, pseudorandom function, MAC, and XOF. BLAKE3 is currently used by LLVM, Bazel, OpenZFS, IPFS, and the Tekken 8 videogame, [among others](https://github.com/BLAKE3-team/BLAKE3/?tab=readme-ov-file#adoption--deployment). BLAKE3 is also a [C2SP specification](https://c2sp.org/BLAKE3).

We've had several requests to integrate BLAKE3 in OpenSSL. How can we make this happen? (BLAKE3's predecessor, BLAKE2, is already in OpenSSL.) We'd be happy to help with the integration work, to adapt the API, provide portable and optimize code, and so on.

(Thanks @levitte for the email response and suggesting this post.)

**Comment by t8m** [comment] 2024-10-24 08:14
Duplicate of #11613

**Closed by t8m** 2024-10-24 08:14 UTC
Labels: branch: master, triaged: feature
