### ISSUE TITLE
1.0.2k SHA-256 Test failed on CPU J3455 with win10. It's correct in "no_asm" option.

### ISSUE THREAD

**Issue by wwc7654321** [openssl/openssl#7137] opened 2018-09-06 13:16 UTC
SHA-256 runs fine on CPU E1231 v3, both in asm and "no_asm".

but in asm option, SHA-256 gets wrong result on CPU J3455 with win10.
in "no_asm" option, the result is correct.

`
sha256( 00000000000000000000000000000000 ) should be 
6a 83 1d b2 7e 02 16 9a 19 0d 63 f8 e1 92 58 2d 15 d7 8b 44 c0 c5 53 c9 16 a6 0f 97 1d 1e 51 4e

but "asm" option gets that result on J3455 :
e7 52 a0 0e e7 52 a0 0e e1 03 b6 5a e1 03 b6 5a e5 37 ba b5 e7 52 a0 0e 69 59 a1 3a e1 03 b6 5a
`

**Comment by wwc7654321** [comment] 2018-09-06 13:34
sha("00…")  means sha(30 30 30…)


by the way, the problem seems only occurs in 64 amd version

**Comment by wwc7654321** [comment] 2018-09-06 13:35
sha("00…") means sha(30 30 30…)

by the way, the problem seems only occurs in  amd64 version

**Comment by dot-asm** [comment] 2018-09-06 20:09
Everything, 1,0,2k, Windows, Goldmont processor, suggests that this is duplicate of #3241.

**Comment by wwc7654321** [comment] 2018-09-07 03:36
thanks, it seems be a well-known problem. may I ask in witch version did the problem fixed? 
I tried Intel SDE , the Goldmont and Icelake both gets wrong result. And  Is the FamilyName  or   Instrution-Extension-Set of CPU that matters?

**Closed** 2018-09-10 03:34 UTC
