### ISSUE TITLE
OpenSSL::X509::CertificateError: nested asn1 error

### ISSUE THREAD

**Issue by sudarshna-gangwar** [openssl/openssl#6220] opened 2018-05-11 05:06 UTC
`str = "some string"`
`OpenSSL::X509::Certificate.new("-----BEGIN CERTIFICATE-----\n#{str}\n-----END CERTIFICATE-----")`

I executed in my system, it is working fine but when i tried to execute on my remote server, its throwing error OpenSSL::X509::CertificateError: nested asn1 error. I even updated my openssl version, its OpenSSL 1.0.2o

**Comment by richsalz** [comment] 2018-05-11 10:12
That's not C code, and it's not complete.  Can you post the actual cert and actual error?

**Comment by sudarshna-gangwar** [comment] 2018-05-11 10:59
referenced link for this issue https://stackoverflow.com/questions/50284995/opensslx509certificateerror-nested-asn1-error

**Comment by richsalz** [comment] 2018-05-11 11:46
Your link doesn't say anything else.  We cannot reproduce your problem.  What is the certificate?  What is the detailed error?

**Comment by levitte** [comment] 2018-05-12 07:56
I suspect that your string doesn't contain the correct base64 encoded public key material...

This is a type of question that I think would get a better response on the mailing list openssl-users@openssl.org (see https://www.openssl.org/community/mailinglists.html for more information on our mailing lists)...  so I think it's time we close this issue here.

**Closed by levitte** 2018-05-12 07:56 UTC
