### ISSUE TITLE
It would be nice to have internal libcrypto routines to query the defined algorithm properies

### ISSUE THREAD

**Issue by levitte** [openssl/openssl#14217] opened 2021-02-17 17:14 UTC
This would be most useful for handling the chain of decoders.  The way they are chained is by extra information apart from their "algorithm name" (which is the name of what they produce).  We do declare them with all sorts of properties, such as (as an OSSL_ALGORITHM):

``` C
...
{ "RSA", "provider=default,fips=yes,input=der,structure=pkcs8", ossl_PKCS8_der_to_rsa_decoder_functions }
...
{ "DER", "provider=default,fips=yes,input=pem", ossl_pem_to_der_decoder_functions) }
...
```

The properties `input` and `structure` are necessary information for the code in libcrypto to chain decoders with one another.  However, we don't really have any functionality to reliably retrieve the property definition of a method that's being looked at, nor to query for the value of a given property.  It would be nice to have some form of bag of key+values.

What has happen now is that the properties `input` and `structure` are duplicated in gettable OSSL_PARAM form, that makes the information reachable from within libcrypto.  Still, it's duplication, which comes with a maintenance burden.

It would be nice not having to duplicate this sort of information, and it would be even nicer not to push that on external providers (let alone having to explain that they must and why).

**Comment by paulidale** [comment] 2021-02-18 02:03
libcrypto should be able to link the property sting to the algorithm easily enough.

**Comment by levitte** [comment] 2021-02-18 04:25
Well yes. That's easy, and is already done for some methods. We could also save the parsed list (OSSL_PROPERTY_LIST). What I'm asking for is a function with which I can get the value of the property "input", for example.

**Comment by paulidale** [comment] 2021-02-18 08:01
We could convert property list entries back to text fairly easily and finding an entry in a property list would be quick enough.

**Comment by t8m** [comment] 2023-04-03 06:41
There is even ask for public API in #17470

**Comment by nhorman** [comment] 2024-06-11 15:51
Given that #17470 exists as a request from community members, should this be closed as a dupliate of that @t8m @paulidale @levitte

**Comment by t8m** [comment] 2024-06-13 22:18
I'd agree although this asks just for internal API. IMO such API would definitely be useful also externally so I'd see no point in not implementing it as public.

**Comment by paulidale** [comment] 2024-06-13 22:21
If we introduce this API, it should be public IMO.
I'm not completely convinced that we need it but am also not convinced we shouldn't provide it.

**Comment by nhorman** [comment] 2024-06-14 02:15
That wasn't the question.  The question was " is #17470 a duplicate of this issue"?

**Comment by paulidale** [comment] 2024-06-14 02:48
I think so.  This should be closed.

**Closed by paulidale** 2024-06-14 02:48 UTC
Labels: triaged: feature
