### ISSUE TITLE
How to `Remove ASM versions of libraries` and `Remove compiler optimisation flags`?

### ISSUE THREAD

**Issue by zwl1619** [openssl/openssl#956] opened 2016-04-09 16:39 UTC
```
[root@i001 ~]# uname -a
Linux i001 4.4.5-1.el7.elrepo.x86_64 #1 SMP Thu Mar 10 11:45:51 EST 2016 x86_64 x86_64 x86_64 GNU/Linux
```

```
[root@i001 ~]# lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.2.1511 (Core) 
Release:	7.2.1511
Codename:	Core

```
openssl:
```
openssl-SNAP-20160409
```
error:
```
engines/afalg/e_afalg.c:70:3: warning: #warning "AFALG ENGINE requires Kernel Headers >= 4.1.0" [-Wcpp]
 # warning "AFALG ENGINE requires Kernel Headers >= 4.1.0"
   ^
engines/afalg/e_afalg.c:71:3: warning: #warning "Skipping Compilation of AFALG engine" [-Wcpp]
 # warning "Skipping Compilation of AFALG engine"


...
...

./libcrypto.a(init.o): In function `ossl_init_engine_afalg':
init.c:(.text+0x31): undefined reference to `engine_load_afalg_internal'
collect2: error: ld returned 1 exit status
make[3]: *** [link_app.] Error 1
make[3]: Leaving directory `/root/openssl-SNAP-20160409'
make[2]: *** [apps/openssl] Error 2
make[2]: Leaving directory `/root/openssl-SNAP-20160409'
make[1]: *** [../openssl-SNAP-20160409/.openssl/include/openssl/ssl.h] Error 2
make[1]: Leaving directory `/root/nginx-1.9.14'
make: *** [build] Error 2

```

I guess it is relevant to this:
```
- Remove ASM versions of libraries
- Remove compiler optimisation flags
```
How to do it?

**Comment by ekasper** [comment] 2016-04-09 21:41
Duplicate of #890 - different OS but same problem I believe.

**Closed by ekasper** 2016-04-09 21:41 UTC

**Comment by zwl1619** [comment] 2016-04-10 09:21
```
#./configure --no-afalgeng --add-module=../nginx-ct-master --with-openssl=../openssl-SNAP-20160409 --with-http_v2_module --with-http_ssl_module

./configure: error: invalid option "--no-afalgeng"
```
what is the syntax?

**Comment by levitte** [comment] 2016-04-10 09:36
`no-afalgeng`

**Comment by zwl1619** [comment] 2016-04-10 09:45
@levitte https://github.com/openssl/openssl/issues/958
