### ISSUE TITLE
X509_STORE_CTX_set_purpose(), X509_verify_cert(), and intermediate certificates with Extended Key Usage extension

### ISSUE THREAD

**Issue by a20god** [openssl/openssl#8328] opened 2019-02-25 14:23 UTC
X509_STORE_CTX_set_purpose(), X509_verify_cert(), and intermediate certificates with Extended Key Usage extension

Apparently, X509_verify_cert() of OpenSSL 1.1.1a (and probably older versions too) check the purpose set with X509_STORE_CTX_set_purpose() also for the intermediate certificate. However, RFC 5280 reads:

>   4.2.1.12.  Extended Key Usage
> 
>      This extension indicates one or more purposes for which the certified
>      public key may be used, in addition to or in place of the basic
>      purposes indicated in the key usage extension.

That is, for an intermediate certificate, an Extended Key Usage extension restricts the usage of that intermediate certificate's public key, which is signing the end entity certificate.

AFAIK, RFC 5280 nowhere says that an intermediate certificate's Extended Key Usage extension  estricts the usage of the end entity certificate's public key.

The attached sample fails with

  error 26 at 1 depth lookup:unsupported certificate purpose

if "-purpose smimesign" is used. The sample does not fail if the

  extendedKeyUsage = serverAuth

line is removed from the configuration file.

Other X.509 implementations behave differently and check the purpose only against the end entity certiciate's key usage restrictions.

Unfortunately, this problem also occurs with real-life intermediate certificates.

[sample.zip](https://github.com/openssl/openssl/files/2900913/sample.zip)

**Comment by a20god** [comment] 2019-02-26 08:46
Here are the sample files inline for your convenience:

Makefile:
```
default: ee.pem
	@echo suceeds:
	openssl verify -CAfile ca.pem -untrusted intermediate.pem ee.pem
	@echo fails:
	openssl verify -purpose smimesign -CAfile ca.pem -untrusted intermediate.pem ee.pem

ee.pem:
	openssl req -new -newkey rsa:2048 -nodes -keyout ca.key -out ca.csr -subj "/CN=ca"
	openssl x509 -trustout -req  -in ca.csr -days 9999 -sha256 -signkey ca.key -out ca.pem -extfile config -extensions ca_policy
	openssl req -new -newkey rsa:2048 -nodes -keyout intermediate.key -out intermediate.csr -subj "/CN=intermediate" -days 9999
	openssl x509 -req -in intermediate.csr -CA ca.pem -CAkey ca.key -CAcreateserial -out intermediate.pem -sha256 -days 9999 -extfile config -extensions intermediate_policy
	openssl req -new -newkey rsa:2048 -nodes -keyout ee.key -out ee.csr -subj "/CN=chain3" -days 9999
	openssl x509 -req -in ee.csr -CA intermediate.pem -CAkey intermediate.key -CAcreateserial -out ee.pem -sha256 -days 9999 -extfile config -extensions ee_policy

clean:
	rm -f ca.csr ca.key ca.pem ca.srl
	rm -f intermediate.csr intermediate.key intermediate.pem intermediate.srl
	rm -f ee.csr ee.key ee.pem
```
config:

```
[ req ]
distinguished_name = req_distinguished_name

[ req_distinguished_name ]

[ ca_policy ]
subjectKeyIdentifier=hash
authorityKeyIdentifier=keyid:always,issuer:always
basicConstraints = CA:true

[ intermediate_policy ]
subjectKeyIdentifier=hash
basicConstraints = CA:true
extendedKeyUsage = serverAuth

[ ee_policy ]
keyUsage = digitalSignature
```

**Comment by mattcaswell** [comment] 2019-02-27 11:51
Perhaps @vdukhovni has an opinion on this?

**Comment by vdukhovni** [comment] 2019-02-27 15:39
The behaviour is a deliberate carefully considered choice beyond the RFC, because the RFC certificate policy mechanism is an unusable abomination. This choice IIRC was not made in OpenSSL first, and matches some other implementations (perhaps Microsoft?).  This has been discussed on openssl-users and/or the TLS WG list at length before.

The change in 1.1.0 just applies the same logic regardless of whether the intermediate certificate is from the trust store or received from the peer.

**Comment by vdukhovni** [comment] 2019-02-27 15:40
In other words, this is expected behaviour, and barring strong arguments to the contrary, I am inclined to close this issue after letting it cool down for a week or so...

**Comment by a20god** [comment] 2019-02-27 18:49
The behavior of OpenSSL does not match the behavior of Microsoft's implementation (which checks Extended Key Usage for the EE certificate only).

Unfiortunately, `X509_STORE_CTX_set_purpose(ctx, X509_PURPOSE_SMIME_SIGN)`
is hardcoded in PKCS7_dataVerify(), which makes that function unusable for those who disagree with OpenSSL's choice of checking the Extended Key Usage extension of every certificate in the certificate chain.

Note that for the (basic) Key Usage extension, OpenSSL seems to check only the EE certificate against the purpose set by X509_STORE_CTX_set_purpose(). Everything else obviously wouldn't work for CA certificates that have a Key Usage extension that includes just certKeySign. That is, there is a discrepancy between the handling of Key Usage and Extended Key Usage in OpenSSL.

**Comment by a20god** [comment] 2019-02-27 19:02
Also note that the extensions in my sample (which is a simplified version of a certain real-life CA) are non-critical.

**Comment by vdukhovni** [comment] 2019-02-27 21:49
CAs that do not wish to constrain the keyUsage of intermediate issuers, should not set the extendedKeyUsage of the intermediate issuer.  OpenSSL allows the parent CA to restrict the keyUsage of certificates that an intermediate CA can issue. The mechanism is not specified in RFC5280, but is a long-standing de-facto practice.

**Comment by vdukhovni** [comment] 2019-02-27 22:00
Note that OpenSSL 1.0.2 also enforces the same checks. The only change in 1.1.0 is that the logic is made consistent regardless of whether the intermediate certificate is obtained from the peer or from the trust store. In 1.0.2, the EKU checks were erroneously not applied for intermediates from the trust store. With 1.1.0, certificate lookup is "trusted first", and the EKU is checked either way.

If the intermediate cert is from the trust store, it can be "decorated" with auxiliary trust OIDs that override the EKU record in the cert by its issuer.

**Comment by vdukhovni** [comment] 2019-02-27 22:48
For the record, I just ran the test case provided against 1.0.2, and, as expected, it also fails to verify with 1.0.2:
```
openssl verify -purpose smimesign -CAfile ca.pem -untrusted intermediate.pem ee.pem
ee.pem: CN = intermediate
error 26 at 1 depth lookup:unsupported certificate purpose
OK
```

**Comment by mattcaswell** [comment] 2019-11-05 12:33
This issue seems to have been answered. Closing.

**Closed by mattcaswell** 2019-11-05 12:33 UTC
Labels: resolved: not a bug, triaged: question

**Comment by defacto64** [comment] 2020-02-18 07:14
Dear @vdukhovni , when you wrote "The mechanism is not specified in RFC5280, but is a long-standing de-facto practice.", what did you have in mind, exactly? Can you mention, with some precision, some cases wherein checking EKU of intermediate CAs is a "de facto practice"?
