### ISSUE TITLE
solaris x86 assembly fails

### ISSUE THREAD

**Issue by octeron** [openssl/openssl#5297] opened 2018-02-09 09:44 UTC
```c
cc  -I. -Icrypto/include -Iinclude -DDSO_DLFCN -DHAVE_DLFCN_H -DNDEBUG -DOPENSSL_THREADS -DOPENSSL_NO_STATIC_ENGINE -DOPENSSL_PIC -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPADLOCK_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/usr/local/ssl/ssl\"" -DENGINESDIR="\"/usr/local/ssl/lib/engines-1.1\"" -xtarget=woodcrest -xstrconst -Xa -DL_ENDIAN -xO5 -xdepend -xbuiltin -xinline=%auto -D_REENTRANT -DFILIO_H -KPIC -c -o crypto/aes/aes-x86_64.o crypto/aes/aes-x86_64.s
Assembler: 
	"crypto/aes/aes-x86_64.s", line 5 : Illegal register: "r15"
	"crypto/aes/aes-x86_64.s", line 5 : Syntax error
	Near line: "	xorl	0(%r15),%eax"
	"crypto/aes/aes-x86_64.s", line 6 : Illegal register: "r15"
	"crypto/aes/aes-x86_64.s", line 6 : Syntax error
	Near line: "	xorl	4(%r15),%ebx"
	"crypto/aes/aes-x86_64.s", line 7 : Illegal register: "r15"
	"crypto/aes/aes-x86_64.s", line 7 : Syntax error
	Near line: "	xorl	8(%r15),%ecx"
	"crypto/aes/aes-x86_64.s", line 8 : Illegal register: "r15"
	"crypto/aes/aes-x86_64.s", line 8 : Syntax error
	Near line: "	xorl	12(%r15),%edx"
	"crypto/aes/aes-x86_64.s", line 10 : Illegal register: "r15"
	"crypto/aes/aes-x86_64.s", line 10 : Syntax error
	Near line: "	movl	240(%r15),%r13d"
	"crypto/aes/aes-x86_64.s", line 10 : Illegal register: "r13d"
	"crypto/aes/aes-x86_64.s", line 11 : Illegal register: "r13d"
	"crypto/aes/aes-x86_64.s", line 11 : Syntax error
	Near line: "	subl	$1,%r13d"
	"crypto/aes/aes-x86_64.s", line 19 : Illegal register: "r14"
	"crypto/aes/aes-x86_64.s", line 19 : Syntax error
	Near line: "	movl	0(%r14,%rsi,8),%r10d"
	"crypto/aes/aes-x86_64.s", line 19 : Illegal register: "rsi"
	"crypto/aes/aes-x86_64.s", line 19 : Illegal register: "r10d"
	"crypto/aes/aes-x86_64.s", line 20 : Illegal register: "r14"
	"crypto/aes/aes-x86_64.s", line 20 : Syntax error
	Near line: "	movl	0(%r14,%rdi,8),%r11d"
	"crypto/aes/aes-x86_64.s", line 20 : Illegal register: "rdi"
	"crypto/aes/aes-x86_64.s", line 20 : Illegal register: "r11d"
	"crypto/aes/aes-x86_64.s", line 21 : Illegal register: "r14"
	"crypto/aes/aes-x86_64.s", line 21 : Syntax error
	Near line: "	movl	0(%r14,%rbp,8),%r12d"
	"crypto/aes/aes-x86_64.s", line 21 : Illegal register: "rbp"
	"crypto/aes/aes-x86_64.s", line 21 : Illegal register: "r12d"
	"crypto/aes/aes-x86_64.s", line 26 : Illegal register: "r14"
	"crypto/aes/aes-x86_64.s", line 26 : Syntax error
	Near line: "	xorl	3(%r14,%rsi,8),%r10d"
	"crypto/aes/aes-x86_64.s", line 26 : Illegal register: "rsi"
	"crypto/aes/aes-x86_64.s", line 26 : Illegal register: "r10d"
	"crypto/aes/aes-x86_64.s", line 27 : Illegal register: "r14"
	"crypto/aes/aes-x86_64.s", line 27 : Syntax error
	Near line: "	xorl	3(%r14,%rdi,8),%r11d"
Too many errors - Goodbye
cc: fbe failed for crypto/aes/aes-x86_64.s
```

fails with both 1.1.0g and the 1.1.0stable checkout from right now.
solaris 11.2 x86, sunpro 5.12

**Comment by dot-asm** [comment] 2018-02-13 12:19
> `cc ... -xtarget=woodcrest ... -xO5 -xdepend -xbuiltin -xinline=%auto`

Order of the flags suggests that it's custom config. Formally speaking it means that the question should be posed to that somebody who put together the custom config. Root of the problem is that you ask compiler to generate 32-bit binary code and feed 64-bit assembly code. This is what needs to be addressed in custom config. Since it's obviously beyond our reach, the case is being closed.

**Closed by dot-asm** 2018-02-13 12:19 UTC

**Comment by octeron** [comment] 2018-03-14 06:15
to wrap this up, the problem was not my options but that the makefile created by using solaris64-x86_64-cc lacked -m64 despite solaris64-x86_64-cc is obviously supposed to produce a 64bit result. after adding -m64 to the related makefile variables it worked fine.

**Comment by levitte** [comment] 2018-03-14 09:02
By default, `solaris64-x86_64-cc` has `-xarch=generic64`.  Like @dot-asm says, you obviously made some changes to the flags (`-xtarget=woodcrest` is a clear give-away), you should probably make sure to preserve that `-xarch` one...  or well, `-m64` seems to work as well.

As for `-m64`, we do have it among the default flags for `solaris64-x86_64-gcc`, which uses the GNU toolchain...
