### ISSUE TITLE
RSA implementation in FIPS module not thread safe

### ISSUE THREAD

**Issue by srahul123** [openssl/openssl#4180] opened 2017-08-17 12:33 UTC
I have a server application in which a global SSL_CTX is used by multiple threads for creating SSL session objects. The session establishment fails randomly when FIPS mode is turned on. I debugged the issue and found that the problem is happening because the RSA key associated with the SSL_CTX object is being used by multiple threads and the RSA decryption functionality is not thread safe. I have attached sample code to reproduce this failure.
[rsa-op.cpp.txt](https://github.com/openssl/openssl/files/1231244/rsa-op.cpp.txt)

**Comment by richsalz** [comment] 2017-08-17 13:16
yes.  most OpenSSL objects are not designed for concurrent use in multiple threads.

and also this is FIPS code which we cannot change. 

Sorry, closing the issue.

**Comment by srahul123** [comment] 2017-08-17 13:28
> most OpenSSL objects are not designed for concurrent use in multiple threads.
I just want to point out that this is not a case of incorrect usage of OpenSSL API. TLS handshake is failing because of this bug.

> this is FIPS code which we cannot change.
I get that

**Comment by richsalz** [comment] 2017-08-17 13:37
no, you are using an SSL object in multiple threads and that is also not allowed

**Comment by mattcaswell** [comment] 2017-08-17 13:43
My understanding from the original post was that SSL_CTX was used in multiple threads (not SSL). This *is* allowed.

**Comment by srahul123** [comment] 2017-08-17 13:46
> My understanding from the original post was that SSL_CTX was used in multiple threads (not SSL). This is allowed.

That is correct.

> no, you are using an SSL object in multiple threads and that is also not allowed

The attached code is a simplified version of the original code I am attaching below. The SSL object is not shared between threads. A global SSL_CTX object is used to create multiple SSL objects by different threads. And I have define locking callbacks using CRYPTO_set_locking_callback().
[ssl-server-rsa.cpp.txt](https://github.com/openssl/openssl/files/1231416/ssl-server-rsa.cpp.txt)

**Comment by richsalz** [comment] 2017-08-17 13:55
So this fails in FIPS which cannot be changed.  Why is this re-opened?

**Comment by mattcaswell** [comment] 2017-08-17 14:00
It's not entirely clear to me that this is a problem in the FIPS module. Where is the locking supposed to be happening here? In libssl or in the RSA implementation? I would have expected the former rather than the latter. If so then its not a bug in the FIPS module and can be fixed. If it *is* a bug in the FIPS module then you're right and we can't fix it. But until we establish that I think it should remain open.

**Comment by richsalz** [comment] 2017-08-17 18:38
From the original poster: "Also note that neither of these sample codes fail when FIPS mode is off."

**Comment by snhenson** [comment] 2017-08-18 14:30
Though just because something fails in FIPS mode doesn't necessarily mean it is a bug in the FIPS module: it could be in the glue code in OpenSSL that uses the FIPS module. Even if it is a bug in the FIPS module itself there may be a way to work around it in the glue code without modifying the FIPS module.

It isn't obvious which is the case here though.

**Comment by snhenson** [comment] 2017-08-18 17:07
Right looks like the FIPS thread ID callback isn't being set. If the deprecated CRYPTO_set_id_callback() function is used then everything works as expected.

#4192 should fix it.

**Comment by mattcaswell** [comment] 2017-08-18 21:43
It amazes me that this hasn't been discovered before.

**Closed by mattcaswell** 2017-08-18 21:43 UTC

**Comment by snhenson** [comment] 2017-08-18 22:10
I think it's down to the fact that the defaults often work as does the deprecated id callback: it was only the newer interface that wasn't passed through.
