### ISSUE TITLE
armhf broken

### ISSUE THREAD

**Issue by kroeckx** [openssl/openssl#4659] opened 2017-11-03 10:50 UTC
The upload of 1.1.0g to Debian unstable had lots of errors:
https://buildd.debian.org/status/fetch.php?pkg=openssl&arch=armhf&ver=1.1.0g-1&stamp=1509674400&raw=0

Most look related to aes, but I can't see any arm specific aes changes, nor does arm64 seem to be affected.

@dot-asm: Can you look at this?

**Comment by kroeckx** [comment] 2017-11-03 10:56
The 1.0.2m upload instead fails in sha256:
https://buildd.debian.org/status/fetch.php?pkg=openssl1.0&arch=armhf&ver=1.0.2m-2&stamp=1509704477&raw=0

**Comment by kroeckx** [comment] 2017-11-03 13:50
I see the same problem with 1.1.0g, so this is not a change in openssl that broke it.

**Comment by richsalz** [comment] 2017-11-03 13:55
Is one of those "1.1.0g" references a typo?

**Comment by kroeckx** [comment] 2017-11-03 13:57
No, it's me being confused ...

**Comment by dot-asm** [comment] 2017-11-03 13:57
I can't reproduce the problem, not under qemu or on Raspberry Pi. gcc 4.x. I did check all thee code paths, i.e. vanilla, NEON and ARMv8. [Well, ARMv8 was tested by copying evp_test binary from Raspberry Pi to ARMv8, but it's sufficient proof.] Can assembly modules be mis-linked? Or some extra compiler flag generating code that gets confused by assembly modules? Can you try to drop custom flags there?

**Comment by kroeckx** [comment] 2017-11-03 14:15
I'm reproducing this on an v7l (i.MX53)

**Comment by kroeckx** [comment] 2017-11-03 14:16
And it's a default ./config, if that's what you mean

**Comment by dot-asm** [comment] 2017-11-03 14:21
> I'm reproducing this on an v7l (i.MX53) ... default ./config

I.e. you are logged on that system. What happens if you `env OPENSSL_armcap=0 make test TESTS=test_evp`? gcc -v, as -v?

**Comment by dot-asm** [comment] 2017-11-03 14:25
> i.MX53

It's Cortex-A8, my Raspberry Pi is Cortex-A7, but it's same instruction set, my test is effectively representative...

**Comment by kroeckx** [comment] 2017-11-03 14:51
gcc is 7.2.1 (Debian 7.2.0-12) as is 2.29.1 (Debian 2.29.1-6). That information should be in the log I pointed to. I'm also building in a stretch chroot with has gcc 6.3.0-18 and binutils 2.28-5, but it's taking some time to build things.

**Comment by dot-asm** [comment] 2017-11-03 14:55
> it's taking some time to build things.

That's why I prefer qemu. Basically I go to hardware *only* if I have to, to single-step in debugger, or in times of doubt like this.

**Comment by kroeckx** [comment] 2017-11-03 15:59
1.1.0f in unstable shows the same problem, 1.1.0g in stretch doesn't have a problem. So this looks like it's caused by a change in the toolchain.

**Comment by dot-asm** [comment] 2017-11-03 16:18
Can you post/mail the "bad" binaries? test/evp_test along with shared libraries. And aes-armv4.o.

**Comment by kroeckx** [comment] 2017-11-03 17:20
The following files are a build of the 1.1.0f version in the unstable chroot using gcc 6.4.0 (gcc-6 6.4.0-9): 
[files.tar.gz](https://github.com/openssl/openssl/files/1441902/files.tar.gz)

So at least the gcc version doesn't seem to have an effect at first look, but it's a different gcc-6 version.

**Comment by kroeckx** [comment] 2017-11-03 17:25
OPENSSL_armcap=0 does result in a difference in behavior, but does not fix all errors.

**Comment by dot-asm** [comment] 2017-11-03 22:49
#4659 should fix 1.1.0 problems, one that fixes problems with 1.0.2 is coming up later...

**Comment by dot-asm** [comment] 2017-11-07 19:38
1.0.2 is addressed in #4673.

**Closed by dot-asm** 2017-11-07 19:38 UTC
Labels: 1.1.0
